### ISSUE TITLE
[UI] Log search is not case-insensitive

### ISSUE THREAD

**Issue by arku** [taskcluster/taskcluster#1002]
**Steps to reproduce**
1. Go to http://localhost:5080/tasks/ZeW7IKcDRQipFT2TN4UAcg/runs/0/logs/https%3A%2F%2Fqueue.taskcluster.net%2Fv1%2Ftask%2FZeW7IKcDRQipFT2TN4UAcg%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log
2. Search for 'Public'. You should find a match on line 6.

![image](https://user-images.githubusercontent.com/7039523/61002056-67f98000-a326-11e9-8185-a858815c12c2.png)

3. Search for 'public' now.

**Expected behavior**
A match on line 6

**Actual behavior**
0 matches

**Comment by helfi92** [comment]
In order to fix this, we could probably expose a `caseInsensitiveSearch` prop to in the `react-lazylog` repo.

**Comment by arshadkazmi42** [comment]
@helfi92 I can take this up, if no one is working

**Comment by helfi92** [comment]
👋 @arshadkazmi42 I think it’s free to grab. It’s all yours :-)

**Comment by arshadkazmi42** [comment]
<img width="919" alt="Screen Shot 2019-07-23 at 10 06 04 PM" src="https://user-images.githubusercontent.com/4654382/61730022-2345fe00-ad96-11e9-95a8-cd4778b6df0a.png">

@helfi92 I am seeing this error, and the url is giving me ResourceNotFound.
Do I need to configure something for this?

**Comment by helfi92** [comment]
@arshadkazmi42  give https://taskcluster-ui.herokuapp.com/tasks/ErcaD1nfRUiuXYCudbZO0A/runs/0/logs/https%3A%2F%2Fqueue.taskcluster.net%2Fv1%2Ftask%2FErcaD1nfRUiuXYCudbZO0A%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log a try.

**Comment by arshadkazmi42** [comment]
@helfi92 Looks like this will need a fix in this repo also https://github.com/mozilla-frontend-infra/react-lazylog
So, we will need to accept a flag in lazylog for `caseInsensitiveSearch` and need to pass this flag during search from taskcluster log search.
Is my thought process in right direction?

**Comment by arshadkazmi42** [comment]
I feel like this diff should be enough for LazyLog component
```diff
diff --git a/src/components/LazyLog/index.jsx b/src/components/LazyLog/index.jsx
index 8ef78de..5c6ed4f 100644
--- a/src/components/LazyLog/index.jsx
+++ b/src/components/LazyLog/index.jsx
@@ -149,6 +149,10 @@ export default class LazyLog extends Component {
      * of the log output.
      */
     extraLines: number,
+    /**
+     * Flag to enable/disable case insensitive search
+     */
+    caseInsensitiveSearch: boolean,
   };

   static defaultProps = {
@@ -177,6 +181,7 @@ export default class LazyLog extends Component {
     loadingComponent: Loading,
     lineClassName: '',
     highlightLineClassName: '',
+    caseInsensitiveSearch: false,
   };

   static getDerivedStateFromProps(
@@ -377,6 +382,10 @@ export default class LazyLog extends Component {

   handleSearch = keywords => {
     const { resultLines, searchKeywords } = this.state;
+    if (this.props.caseInsensitiveSearch) {
+      keywords = keywords.toLowerCase();
+    }
+
     const currentResultLines =
       !this.props.stream && keywords === searchKeywords
         ? resultLines
```

**Comment by helfi92** [comment]
Looks good. Feel free to open a pull-request there.

**Comment by arshadkazmi42** [comment]
@helfi92 Added a PR at [mozilla-frontend-infra/react-lazylog#47](https://github.com/mozilla-frontend-infra/react-lazylog/pull/47)

**Comment by helfi92** [comment]
@arshadkazmi42 The only thing left would be to update the dependency and add the appropriate prop :)
