### ISSUE TITLE
[UI] Notifications dialog has the cancel button selected with a "breathing" animation

### ISSUE THREAD

**Issue by jonalmeida** [taskcluster/taskcluster#1012]
**To Reproduce**
1. Click on 'Notifications' in a Task Group (e.g. [this one](https://taskcluster-ui.herokuapp.com/tasks/groups/SqW48e9cRt-93xlDXkQ6hw))
2. Observe the 'Cancel' button on the dialog

**Expected behavior**
The Cancel button is not selected in any way.

**Actual behavior**
The Cancel button is selected with a "breathing" animation on it.

**Screenshots**
<img width="362" alt="Screen Shot 2019-07-12 at 3 26 10 PM" src="https://user-images.githubusercontent.com/1370580/61153674-f3efe100-a4b9-11e9-8bbd-a129ee3476f5.png">

**Platform (please complete the following information):**
 - OS: n/a
 - Version if applicable: Today's version of the new TC UI.

**Comment by helfi92** [comment]
This is actually intentional. All buttons have a "breathable" effect when focused. We also set the initial focus on the least destructive action button (Cancel) to avoid unwanted consequences like accidentally pressing enter.
