### ISSUE TITLE
[UI] As a user, I want to know the progress of a build so far on the group view

### ISSUE THREAD

**Issue by jonalmeida** [taskcluster/taskcluster#1043]
This might not be feasible, so please close if so.

I sometimes find that I want to know which variant of a build is close to being done so I can monitor that more and it's hard to know which one is the closest to being completed.

For example, in the screenshot below, I want to know that at least one build variant of the `assemble` task passes because there's a high probability that everything else will pass.
<img width="813" alt="Screen Shot 2019-07-16 at 1 20 51 PM" src="https://user-images.githubusercontent.com/1370580/61315516-efcf0680-a7cc-11e9-96b7-8c634ad8de58.png">

**Comment by helfi92** [comment]
I'm not sure I know how to do that. I think it's hard to know how long is the duration of a command to be able to identify which variant is close to being done.

**Comment by djmitche** [comment]
I think the best you can do in this situation is filter down to the set of interesting jobs and look at that (so maybe Name Contains -> "assemble" in this case?).  We don't have any information on task duration: as far as TC is concerned, it's just a shell command that could last 3ms or 3 days.

**Comment by jonalmeida** [comment]
I figured as much, but thought I'd ask regardless. Thank you! :)
