### ISSUE TITLE
[web-server] Update dependency sift to v8

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1046]
From the release notes:

> DEPRECATED sift(query, array). You must now use array.filter(sift(query)).

This will involve changing all sift invocations and making sure .filter is not called on an undefined/null array.

**Comment by projectyang** [comment]
Hey @helfi92, I'd love to take this on.

**Comment by helfi92** [comment]
Hey @projectyang 👋 Welcome back!
