### ISSUE TITLE
[UI] [Docs] Taskcluster Hello World video link broken

### ISSUE THREAD

**Issue by arku** [taskcluster/taskcluster#1058]
The [video link](https://vreplay.mozilla.com/replay/showRecordingExternal.html?key=7AvN2iczQYcI3lY) mentioned in our [Hello World tutorial](https://github.com/taskcluster/taskcluster/blob/master/ui/docs/tutorial/hello-world.md#see-also) seems to be unavailable.

/cc @djmitche

**Comment by djmitche** [comment]
Hmm, @petemoore any idea if that was saved elsewhere?  vreplay was part of our Vidyo installation, which was shut down a few months ago.

**Comment by Patil2099** [comment]
@djmitche  Can I work on this issue if you found the video link?
Thanks!

**Comment by djmitche** [comment]
@Patil2099 sure, I think at this point we can just remove any broken links.

**Comment by vishakhanihore** [comment]
@djmitche Please assign me this. I would love to send a PR.

**Comment by djmitche** [comment]
Let's leave this for other Outreachy applicants.  It's good practice in the process of making a PR.

**Comment by sccofield** [comment]
Hi @djmitche I am an outreachy applicant. Can I work on this issue?

**Comment by djmitche** [comment]
All yours!

**Comment by sccofield** [comment]
hi @djmitche I worked on the issue on a new branch, and I have been trying to push, so that I can raise a PR, but I keep getting
`remote: Permission to taskcluster/taskcluster.git denied to sccofield.`
`fatal: unable to access 'https://github.com/taskcluster/taskcluster.git/': The requested URL returned error: 403`

**Comment by katherine95** [comment]
@sccofield, fork this repo then push to your remote, it will link the PR to this repo automatically. I hope this helps.

**Comment by sccofield** [comment]
@katherine95 Thanks a lot. It was really helpful.
