### ISSUE TITLE
[UI] Label is overflowing

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1073]
STR:

1. Navigate to https://taskcluster-ui.herokuapp.com/
2. Click sign in
3. Set Client ID to "test", Access Token to "test" and JSON certificate to `111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111`
4. Navigate to https://taskcluster-ui.herokuapp.com/profile

Expected: The certificate field has its value wrap around.
Actual: The certificate field value doesn't wrap around.

We use material-ui for our component. You can probably look at https://material-ui.com/components/lists/#align-list-items and see how they wrap around the text there.

**Comment by rbrishabh** [comment]
Hey! Can I take this up?

**Comment by helfi92** [comment]
Go for it.

**Comment by rbrishabh** [comment]
Hey @helfi92 ! I hope you're doing well.

![bug-2](https://user-images.githubusercontent.com/22501334/61574942-b0156100-aae3-11e9-8227-8d34371c6111.png)

Does this look okay?

Also to achieve this, I can do both -- Add inline styling on certificate field, or change it's styling from material-ui in node modules. Which way should I do it?

Thanks!

**Comment by helfi92** [comment]
I just created https://github.com/taskcluster/taskcluster/issues/1093. If you're interested, comment on the bug directly :)
