### ISSUE TITLE
Artifacts with URL encoded filenames can't be downloaded

### ISSUE THREAD

**Issue by ncalexan** [taskcluster/taskcluster#1079]
My Task Cluster task most naturally produces artifacts identified by URLs, so these URLs are encoded in the filename (well, in the directory part of the filename).  These appear to be uploaded correctly but they cannot be downloaded.  See, for example, https://tools.taskcluster.net/groups/Lp77UnjWSo65lTmcgyA1Pg/tasks/G7fVftFGTg6BMkjg0geGXQ/runs/0/artifacts which has an artifact named like `public/test_info/browsertime-results/https%3A%2F%2Fwww.facebook.com/browsertime.json` that links to https://queue.taskcluster.net/v1/task/G7fVftFGTg6BMkjg0geGXQ/runs/0/artifacts/public/test_info/browsertime-results/https%3A%2F%2Fwww.facebook.com/browsertime.json.  That link results in a 404.  If I manually URL encode further, like https://queue.taskcluster.net/v1/task/G7fVftFGTg6BMkjg0geGXQ/runs/0/artifacts/public/test_info%2Fbrowsertime-results%2Fhttps%253A%252F%252Fwww.facebook.com%2Fbrowsertime.json, I get an access denied message instead.

**Comment by djmitche** [comment]
The fully-encoded URL `https://queue.taskcluster.net/v1/task/G7fVftFGTg6BMkjg0geGXQ/runs/0/artifacts/public/test_info%2Fbrowsertime-results%2Fhttps%253A%252F%252Fwww.facebook.com%2Fbrowsertime.json` is correct.  That the UI generated an unescaped filename is a bug that we should fix.

There's an issue in cloud-mirror/S3 around escaped filenames.  I think setting the header [`x-taskcluster-skip-cache: true`](https://docs.taskcluster.net/docs/reference/platform/queue/api#getArtifact) in the request will avoid that issue.

**Comment by djmitche** [comment]
The second bug is not something we can fix quickly.  It's also not something that affects users who are not in EC2 (and thus not getting redirected by cloud-mirror).

The first is a UI bug that could be fixed..

**Comment by rbrishabh** [comment]
Hey @djmitche! Can I take up the first UI bug part of this issue?

Thanks!

**Comment by djmitche** [comment]
Yes please!  I think you can see an example of it at the first link in nick's comment, and the resulting URL should be the third link in their comment (with lots of %)

**Comment by rbrishabh** [comment]
> That the UI generated an unescaped filename is a bug that we should fix.

@djmitche Alright, I think I got it. But I still don't know where in code is the ui generating the unescaped filename. Can you please guide me with this?

Thanks!

**Comment by djmitche** [comment]
I'm not sure either -- I'd guess under https://github.com/taskcluster/taskcluster/tree/master/ui/src/components/TaskRunsCard since it appears in the task run card?

**Comment by rbrishabh** [comment]
Hey @djmitche ! 

Over inside of [https://github.com/taskcluster/taskcluster/blob/master/ui/src/components/TaskRunsCard/index.jsx](url), I am guessing -- 
```getArtifactUrl = ({ url, isLog }) => {
    if (!url) {
      return '';
    }

    const { taskId, runId } = this.getCurrentRun();

    if (isLog) {
      const encoded = encodeURIComponent(url);

      return this.isLiveLog()
        ? `/tasks/${taskId}/runs/${runId}/logs/live/${encoded}`
        : `/tasks/${taskId}/runs/${runId}/logs/${encoded}`;
    }

    return url;
  };
```

This is the relevant code that needs to be changed. Instead of returning url when if(isLog) is false, we need to return encoded url, something like, 
```return encodeURIComponent(url)``` in the end.

Did I get it right?

If not, just let me know, and I'll dig some more. Thanks!

**Comment by djmitche** [comment]
I think you're close, but it looks like that's for the livelog URL, which is used to show logs in the UI.  And it's already encoded.  The URLs that *aren't* encoded are in the "Artifacts" section of the run card.

**Comment by rbrishabh** [comment]
Hey @djmitche !

After going through the code again, I believe both ```live log``` section and ```Artifacts``` section make use of the same ```getArtifactUrl``` method to encode the url.

When ```live log``` calls the url, it calls it with ```isLog``` value which is ```true```, which returns the encoded url.

While ```Artifacts``` section calls ```renderArtifactsTable()``` method, which in turn calls ```this.getArtifactUrl(artifact)``` the same method is called with false. This time the URL never gets encoded as we simply return URL. See comment [https://github.com/taskcluster/taskcluster/issues/1079#issuecomment-513692540](url).

Here is the code for your reference. 
```
renderArtifactsTable() {
    const { classes, onArtifactsPageChange } = this.props;
    const run = this.getCurrentRun();
    const artifacts =
      run && this.createSortedArtifactsConnection(run.artifacts);

    return (
      <ConnectionDataTable
        connection={artifacts}
        pageSize={ARTIFACTS_PAGE_SIZE}
        columnsSize={3}
        onPageChange={onArtifactsPageChange}
        renderRow={({ node: artifact }) => (
          <TableRow
            key={`run-artifact-${run.taskId}-${run.runId}-${artifact.name}`}
            className={classNames(
              classes.listItemButton,
              classes.artifactTableRow,
              {
                [classes.pointer]: !!artifact.url,
              }
            )}
            hover={!!artifact.url}>
            <Link
              className={classes.artifactLink}
              to={this.getArtifactUrl(artifact)}>
              <TableCell className={classes.artifactsTableCell}>
                {artifact.isPublic && <LockOpenOutlineIcon />}
                {!artifact.isPublic && artifact.url && <LockIcon />}
              </TableCell>
              <TableCell
                className={classNames(
                  classes.artifactNameTableCell,
                  classes.artifactsTableCell
                )}>
                <div className={classes.artifactNameWrapper}>
                  {artifact.isLog && (
                    <Label status="info" mini className={classes.logButton}>
                      LOG
                    </Label>
                  )}
                  <Typography>{artifact.name}</Typography>
                </div>
              </TableCell>
              <TableCell
                className={classNames(
                  classes.linkCell,
                  classes.artifactsTableCell
                )}>
                {artifact.isPublic && <LinkIcon />}
                {!artifact.isPublic && artifact.url && <OpenInNewIcon />}
              </TableCell>
            </Link>
          </TableRow>
        )}
      />
    );
  }
```

I still think the patch I suggested above will work as getArtifactUrl() method is handling both urls, live log url and Artifact section url.

I would appreciate any help if I'm still going wrong. Thank you!

**Comment by djmitche** [comment]
(thanks for the note about editing the comment -- it's very confusing when comments get edited without any notes!)

Interesting, so it looks like we use encoding only for `isLog === true`.  Those links lead to another page in the UI that displays the log, rather than linking to the artifact itself.  So we can leave those along.

The only reason I can think of to *not* escape artifact links is to allow for "nice" looking URLs with un-escaped `/` characters, for artifacts that don't have any other characters that require escaping -- for example, `/api/queue/v1/tasks/${taskId}/runs/${runId}/artifacts/public/builds/linux/amd64/firefox` instead of `/api/queue/v1/tasks/${taskId}/runs/${runId}/artifacts/public%2Fbuilds/linux%2Famd64%2Ffirefox`.  Users often copy-paste links to other places, so a nice-looking link helps.

So, I think we need to do one of two things:
 * only escape the path if it contains characters other than `/` that require escaping; or
 * always escape the path but leave `/` un-escaped

Probably the second option is easier.

That said, I can't quite figure out where the `url` property of an artifact gets set -- it might even be under `services/web-server`?

**Comment by rbrishabh** [comment]
Hey @djmitche !

Following the second approach mentioned by you,

```
getArtifactUrl = ({ url, isLog }) => {
    if (!url) {
      return '';
    }

    const { taskId, runId } = this.getCurrentRun();

    if (isLog) {
      const encoded = encodeURIComponent(url);

      return this.isLiveLog()
        ? `/tasks/${taskId}/runs/${runId}/logs/live/${encoded}`
        : `/tasks/${taskId}/runs/${runId}/logs/${encoded}`;
    }

    const encodedUrl = var res = encodeURI(uri); 

    return encodedUrl;
  };
```

I think this should fix it.

That being said, even I don't know where ```artifact``` gets their ```url``` property from. Could be entirely possible it's from web-server as well. 

Should I make a PR with the above fix?

**Comment by djmitche** [comment]
Yeah, I think it's easier to discuss a fix in a PR.  I'm not sure that will work, but there's one way to find out :)
