### ISSUE TITLE
[UI] documentation menu is hard to close on mobile

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1093]
STR:

1. Navigate to https://taskcluster-ui.herokuapp.com/docs/resources
2. Open the developer tools and click on the responsive design mode button

![Screen Shot 2019-07-22 at 11 36 54 AM](https://user-images.githubusercontent.com/3766511/61645624-0665d980-ac75-11e9-9f16-a1bf370bf7d3.png)

3. Refresh the page
4. Click the hamburger menu to open the side drawer

Actual: It's hard to close the menu for users on mobile
Expected: It's easy to close the menu for users on mobile

Solution: Make the drawer smaller on mobile when it's open.

**Comment by rbrishabh** [comment]
Can I take this up? @helfi92

**Comment by helfi92** [comment]
Go for it.
