### ISSUE TITLE
[web-server] Cookies not working properly in production

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1099]
STR:

1. Navigate to https://taskcluster-ui.herokuapp.com/
2. Open the developer console and type window.open('/login/mozilla-auth0')
3. Login

Expected: The user is logged in
Actual: The user is not logged in in production. Works in localhost.

Problem: Cookies are not being set for some reason. https://github.com/taskcluster/taskcluster/pull/1097 was an attempt to fix the issue but that didn't fix it as far as I can tell.

**Comment by arku** [comment]
@helfi92 How do I go about testing this locally?

**Comment by helfi92** [comment]
👋 @arku 

I think it would be easiest to test this using GitHub. To configure the strategy,
you will need to register an application with GitHub. If you don’t have one,
you can create one at [developer applications](https://github.com/settings/applications/new) within
GitHub’s setting panel. Once the application is created, In order to enable the github strategy, changes to both`taskcluster-ui` and `web-server` are required. The changes are outlined in
[taskcluster-ui's (login strategies)](https://github.com/taskcluster/taskcluster/tree/master/ui#login-strategies) and [web-server (login strategies)](https://github.com/taskcluster/taskcluster/tree/master/services/web-server#login-strategies).

Let me know if you require more assistance. Like always, happy to help!

**Comment by arku** [comment]
@helfi92 I am running into a similar error when trying to use Github login strategy :confused: 

```
Error: Unable to use "github" login strategy without taskcluster clientId and accessToken
```

I am running the web server with `UI_LOGIN_STRATEGIES='{"github": {"clientId": "..", "clientSecret": ".."}}' TASKCLUSTER_ROOT_URL=https://taskcluster-staging.net yarn start`

What am I doing wrong? :thinking:

**Comment by helfi92** [comment]
Ah. That’s because the process running web-server needs taskcluster creds to run. You can get the taskcluster binary from https://github.com/taskcluster/taskcluster/blob/master/clients/client-shell/README.md

The command to run is written [here](https://github.com/taskcluster/taskcluster/blob/master/services/web-server/README.md#taskcluster-credentials). Make sure the command is run in the same terminal where web-server will be running since that command will export environment variables.

**Comment by arku** [comment]
@helfi92 Running into an 'Invalid client error' messsage :confused:

**Comment by helfi92** [comment]
Interesting. Were you able to sign-in in the browser after running the command?

**Comment by arku** [comment]
@helfi92 I ran `eval $(./taskcluster signin --name taskcluster-web-server)` and got the following output:
```
Starting
Listening for a callback on: http://localhost:44291
Opening URL: https://taskcluster-staging.net/auth/clients/new?name=taskcluster-web-server&description=Temporary+client+for+use+on+the+command+line&scope=%2A&expires=1d&callback_url=http%3A%2F%2Flocalhost%3A44291
```

And if I open the URL, I find a 'Client not found' message. Do you see what I am missing?

**Comment by helfi92** [comment]
> And if I open the URL, I find a 'Client not found' message. Do you see what I am missing?

You shouldn't try to open the URL yourself. The binary itself will open the browser tab for you. Is it possible you didn't see the tab that was opened for you?

**Comment by helfi92** [comment]
Will close after verifying that it works in production.

**Comment by djmitche** [comment]
> Opening URL: https://taskcluster-staging.net/auth/clients/new?name=taskcluster-web-server&description=Temporary+client+for+use+on+the+command+line&scope=%2A&expires=1d&callback_url=http%3A%2F%2Flocalhost%3A44291

That's on the taskcluster-staging cluster, which runs the new UI and does not support CLI logins (yet).  The URL is based on `$TASKCLUSTER_ROOT_URL`, and the only value of that variable that will work right now is `https://taskcluster.net`.

**Comment by helfi92** [comment]
@djmitche I'm not sure I understand the question or how it relates to this issue. Could you elaborate, please? Thanks!

**Comment by djmitche** [comment]
It wasn't a question, but an answer to @arku as to why that login process didn't work.
