### ISSUE TITLE
Run 'go mod tidy' in yarn generate

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#1122]
`go mod tidy` seems to do a good job of cleaning out the cruft that other `go` tools put into `go.mod` and `go.sum`.  Let's run that command in both `clients/client-go` and `clients/client-shell` on every `yarn generate` run.

It will also be useful to add that command to the [renovate config](https://renovatebot.com/docs/configuration-options/#gomod).

**Comment by rbrishabh** [comment]
Hey! I have little to no knowledge of go. Should I take up this issue?

**Comment by djmitche** [comment]
In fact most of the code to write would be in JS under `infrastructure/builder/src/generate`, so maybe!  But start by getting the `clients/client-go` and `clients/client-shell` tests to run -- in other words, get a working go development environment up and running.

**Comment by vishakhanihore** [comment]
@djmitche I would like to work on this

**Comment by djmitche** [comment]
Sure!  This is a bit of a tricky one, and not React-related, but in JS.  There are some notes in my last comment.

**Comment by djmitche** [comment]
It appears that the `go mod` in the version of go we use (go1.12.9) is not "stable" and will put different stuff in `go.sum` and `go.mod` depending on where it is run.  In `yarn generate`, we require stable behavior, since we must be able to reproduce the exact same output by running `yarn generate` again.  So for the moment, this issue can't be solved.  When we update to a newer go version, maybe that will work better.

**Comment by vnzongzna** [comment]
Is this issue still up for new contributors? I would like to take this since the `go.mod` is taking `go1.13` now

**Comment by djmitche** [comment]
It looks like this already got done -- sorry for not closing this issue!
```
commit 39994ed61f8d7b2cd81119af76ebe2c1e408b7d0 (origin/generate-go-mod-tidy, djmitche/generate-go-mod-tidy, generate-go-mod-tidy)                                                                                                                                                                                                                                                            
Author: Dustin J. Mitchell <dustin@mozilla.com>
Date:   Tue Mar 3 22:06:55 2020 +0000

    run 'go mod tidy' in 'yarn generate'
```
