### ISSUE TITLE
[UI] Log viewer links from artifacts list to empty artifacts keep spinning

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#1123]
**Describe the bug**
Artifacts for a run which are detected to be "logs" by the UI are displayed in a dedicated log-viewer window.  This doesn't seem to load.

**To Reproduce**
1. Go to https://taskcluster-ui.herokuapp.com/tasks/BkoMwSh5TbqEE_W69Zq8Wg
2. Click on "Artifacts"
1. Click on the `xvfb.log` artifact

**Expected behavior**
Displays the (short) logfile

**Additional context**
I don't see any warnings in console, and the log is being fetched successfully.

**Comment by helfi92** [comment]
Hm, doesn't seem to load in the old UI as well: https://tools.taskcluster.net/groups/BStks92NTxiOxwlEXajNlw/tasks/BkoMwSh5TbqEE_W69Zq8Wg/runs/0/artifacts

**Comment by djmitche** [comment]
Ah, looks like it's empty.  So perhaps the code doesn't detect empty artifacts correctly.  All of the other logfiles on that push *do* display correctly.

**Comment by Shubhamchinda** [comment]
Hey , can I work on this?

**Comment by Shubhamchinda** [comment]
Hey, Thanks a lot!

Could you please tell me what we need to show when the page keeps on loading since the artifacts are empty.
Thanks again!

**Comment by helfi92** [comment]
I think showing an empty log is okay.

**Comment by Shubhamchinda** [comment]
Hey @helfi92 , Sorry for late response I had some intern work to finish.

I tried to find the solution but I didn't see any change in the `props/state` of the Log file or anything which is related to fetching a log when there're empty log artifacts. Could please guide me a little here? 

Thanks a lot :)

**Comment by helfi92** [comment]
Hey @Shubhamchinda. I think the fix will need to be done in https://github.com/mozilla-frontend-infra/react-lazylog since it takes care of displaying the loading component. I think the issue lies in https://github.com/mozilla-frontend-infra/react-lazylog/blob/3cc37f8f32a5103ac3157c4c2a4ae32278512030/src/components/LazyLog/index.jsx#L573-L598. Hope that helps.

**Comment by Shubhamchinda** [comment]
Thank @helfi92 .
I looked into it and I noticed we have no condition for the return value when the log is empty in [`renderNoRows`](https://github.com/mozilla-frontend-infra/react-lazylog/blob/3cc37f8f32a5103ac3157c4c2a4ae32278512030/src/components/LazyLog/index.jsx#L573-L598). Do I need to add that or do you need the same [`Line`](https://github.com/mozilla-frontend-infra/react-lazylog/blob/3cc37f8f32a5103ac3157c4c2a4ae32278512030/src/components/LazyLog/index.jsx#L589). If the same [`Line`](https://github.com/mozilla-frontend-infra/react-lazylog/blob/3cc37f8f32a5103ac3157c4c2a4ae32278512030/src/components/LazyLog/index.jsx#L589)  is needed then the value of `count` is not changing in the beginning. We need to fix that.

Another thing I wanted to ask, I made changes in https://github.com/mozilla-frontend-infra/react-lazylog but when I'm debugging it with `console.log()` , it never allow the code to build, to temporarily fix it. I made the following changes in `.eslintrc.js` file :
```module.exports = Neutrino({ root: __dirname })
  .use('.neutrinojs',{
    eslint: {
      rules: { 
        semi: 'off',
        'no-console': 'off'
      } 
    }
  })
  .call('eslintrc');
```
but it's working here.

Let me know If I'm going correct.

Thanks a lot again! :)

**Comment by helfi92** [comment]
When the log is streaming, `loaded` will be `false`. I think that's why we don't do `if(loaded)` and do `if (count)`. I wonder if something like `if(count || (!stream && loaded))` would do it. Thoughts?

Regarding the `no-console`, issue, something like https://github.com/mozilla-frontend-infra/bugzilla-graphql-gateway/blob/651c3bd2d97411c21119cc1c0e348f6f515b425b/.neutrinorc.js#L31 should work.

**Comment by Shubhamchinda** [comment]
> When the log is streaming, `loaded` will be `false`. I think that's why we don't do `if(loaded)` and do `if (count)`. I wonder if something like `if(count || (!stream && loaded))` would do it. Thoughts?

I didn't put the `stream` in the `if` condition as it's value was `false` in both cases but yeah you're correct it should be in the condition. Anyways, I tested  `if(count || (!stream && loaded))`, it's working fine. 
```
if (count || (!stream && loaded)) {
      return (
        <Line
          className={lineClassName}
          highlightClassName={highlightLineClassName}
          data={[{ bold: true, text: `No filter matches` }]}
        />
      );
    }
```
The text `No filter matches` shouldn't be same for both conditions, right ?

**Comment by helfi92** [comment]
Ah, sorry, I didn't realize this was inside the `renderNoRows` method. I think something as simple as the following would do it:

```diff
diff --git a/src/components/LazyLog/index.jsx b/src/components/LazyLog/index.jsx
index 3f37729..926680d 100644
--- a/src/components/LazyLog/index.jsx
+++ b/src/components/LazyLog/index.jsx
@@ -576,7 +576,7 @@ export default class LazyLog extends Component {
       lineClassName,
       highlightLineClassName,
     } = this.props;
-    const { error, count } = this.state;
+    const { loaded, error, count } = this.state;
 
     if (error) {
       return this.renderError();
@@ -594,6 +594,11 @@ export default class LazyLog extends Component {
       );
     }
 
+    // Handle case where log is empty
+    if (!count && loaded) {
+      return null;
+    }
+
     return <Loading />;
   };
```

If the log is streaming, `loaded` will be false anyways.

**Comment by Shubhamchinda** [comment]
> Ah, sorry, I didn't realize this was inside the `renderNoRows` method. I think something as simple as the following would do it:
> 
> ```diff
> diff --git a/src/components/LazyLog/index.jsx b/src/components/LazyLog/index.jsx
> index 3f37729..926680d 100644
> --- a/src/components/LazyLog/index.jsx
> +++ b/src/components/LazyLog/index.jsx
> @@ -576,7 +576,7 @@ export default class LazyLog extends Component {
>        lineClassName,
>        highlightLineClassName,
>      } = this.props;
> -    const { error, count } = this.state;
> +    const { loaded, error, count } = this.state;
>  
>      if (error) {
>        return this.renderError();
> @@ -594,6 +594,11 @@ export default class LazyLog extends Component {
>        );
>      }
>  
> +    // Handle case where log is empty
> +    if (!count && loaded) {
> +      return null;
> +    }
> +
>      return <Loading />;
>    };
> ```
> 
> If the log is streaming, `loaded` will be false anyways.

Made the changes and created the [PR](https://github.com/mozilla-frontend-infra/react-lazylog/pull/51).
 Thanks a lot! :)

**Comment by helfi92** [comment]
@Shubhamchinda Thanks for your work in react-lazylog :) The last thing we need to do is update the package.json via `yarn add react-lazylog` inside the `ui` directory. Feel free to create a PR.

**Comment by Shubhamchinda** [comment]
> yarn add react-lazylog

My pleasure man. I'm looking forward to contribute more. :)

**Comment by Shubhamchinda** [comment]
> > yarn add react-lazylog
> 
> My pleasure @helfi92 . I'm looking forward to contribute more. :)
