### ISSUE TITLE
[UI] Allow pasting an full index to find tasks.

### ISSUE THREAD

**Issue by tomprince** [taskcluster/taskcluster#1148]
Most ways of interacting with the index don't treat the last component specially, so all components are separated by `.`. It would be nice to paste that form of index both into the UI, and into a URL, and be able to see the task. Currently, you need to edit the index to replace the trailing `.` with `/` to be able to see the index.

**Comment by helfi92** [comment]
Perhaps we could add a search box that takes in a namespace name (e.g., buildbot.branches.mozilla-esr52.linux64-artifact). Would that help?

**Comment by tomprince** [comment]
I often have a full index path, not just the namespace, and would like to be able to use this directly. This is particularly important for namespaces like https://taskcluster-ui.herokuapp.com/tasks/index/gecko.v2.try.revision that have hundreds or thousands of entries in effectively random order.

**Comment by helfi92** [comment]
> I often have a full index path, not just the namespace, and would like to be able to use this directly.

You would be able to use the full index path, for example, `gecko.v2.try.revision.0001b4f6ab73f02e12bc7594ed840bb6789357a7.firefox.decision` in the search box after the search component gets implemented.

**Comment by arku** [comment]
@helfi92 I would like to attempt building this feature.

**Comment by helfi92** [comment]
👋 @arku. Go for it :)

**Comment by arku** [comment]
My bad, totally forgot this task 🙈

Will make some progress tomorrow.

**Comment by arku** [comment]
@helfi92 I am occupied with other stuff that I am unable to address your comments in #1238

Do you mind reassigning this issue to someone to make sure it gets fixed? 

Thanks!

**Comment by helfi92** [comment]
No worries. Thanks for letting us know @arku :)

@Rolikasi are you interested in finishing up this PR?

**Comment by Rolikasi** [comment]
Sure! I want to work on it)

**Comment by arku** [comment]
@Rolikasi Thanks for taking it up!
