### ISSUE TITLE
[UI] The worker page doesn't contain worker information.

### ISSUE THREAD

**Issue by tomprince** [taskcluster/taskcluster#1150]
The page for an individual worker such as 
https://taskcluster-ui.herokuapp.com/provisioners/aws-provisioner-v1/worker-types/hg-push/workers/us-west-2/i-0130a316a7ba1733a
doesn't include the worker-id or worker-group.

**Comment by helfi92** [comment]
Re-opened https://github.com/taskcluster/taskcluster/issues/325.
