### ISSUE TITLE
Log search filter background color

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1181]
We should try to give a background color to the filter icon when selected.

STR:

1. Navigate to https://taskcluster-ui.herokuapp.com/tasks/Kp5viqUERuKejEkgz8u4dA/runs/0/logs/live/https%3A%2F%2Fqueue.taskcluster.net%2Fv1%2Ftask%2FKp5viqUERuKejEkgz8u4dA%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log

![Screen Shot 2019-08-14 at 2 19 57 PM](https://user-images.githubusercontent.com/3766511/63045756-04bbba00-be9f-11e9-8843-95bfff48b702.png)

2. Click on the filter button (4 lines icon)

Actual:

![Screen Shot 2019-08-14 at 2 20 03 PM](https://user-images.githubusercontent.com/3766511/63045757-04bbba00-be9f-11e9-9158-38245caf17cd.png)

Expected: The filter should have a background similar to the first button in the following screenshot:

![Screen Shot 2019-08-14 at 2 22 03 PM](https://user-images.githubusercontent.com/3766511/63045758-04bbba00-be9f-11e9-833d-7e3fd467d955.png)

**Comment by arku** [comment]
I'm on it.

**Comment by arku** [comment]
@helfi92 Got a question. Is it fine if we update the active filter styles [here](https://github.com/mozilla-frontend-infra/react-lazylog/blob/master/src/components/SearchBar/index.module.css#L23) or should we pass it to `LazyLog` component in some way?

**Comment by helfi92** [comment]
There's probably a way to override the css directly from this repo. I think we already do it somewhere.

**Comment by arku** [comment]
@helfi92 You're right. Let me get to it.
