### ISSUE TITLE
[docs] Make use of warning panels

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1207]
STR:

1. Navigate to https://taskcluster-ui.herokuapp.com/docs/reference/platform/auth/roles#stars-in-parameters
2. Find the text where it says ```"WARNING: be careful using * in scopes that will be expanded with a parameterization, as results may not be what you expect."```

Let's go over our docs and make warnings stand out so users see them.

For example, in https://taskcluster-ui.herokuapp.com/docs/reference/platform/auth/roles#stars-in-parameters, instead of

![Screen Shot 2019-08-21 at 1 31 04 PM](https://user-images.githubusercontent.com/3766511/63454067-11e52580-c418-11e9-9a88-f8f0ce8b88fc.png)

let's do

![Screen Shot 2019-08-21 at 1 31 19 PM](https://user-images.githubusercontent.com/3766511/63454050-0691fa00-c418-11e9-9ba4-71d1d15e8115.png)

The diff that made this happen:

```diff
diff --git a/ui/docs/reference/platform/auth/roles.md b/ui/docs/reference/platform/auth/roles.md
index 509e17059..61b158aa7 100644
--- a/ui/docs/reference/platform/auth/roles.md
+++ b/ui/docs/reference/platform/auth/roles.md
@@ -2,6 +2,7 @@
 title: Roles and Role Expansion
 order: 30
 ---
+import ErrorPanel from 'taskcluster-ui/components/ErrorPanel'
 
 # Roles and Role Expansion
 
@@ -91,8 +92,7 @@ a scope-set containing `"assume:project-admin:zap"` would expand to include
 
 ### Stars in Parameters
 
-*WARNING*: be careful using `*` in scopes that will be expanded with a
-parameterization, as results may not be what you expect.
+<ErrorPanel warning error="Be careful using `*` in scopes that will be expanded with a parameterization, as results may not be what you expect." />
 
 As a special case, if there is a `*` in the input suffixed matched by the
 role's `*`, then anything following the first `<..>` in the scope will be
```

Your task:
* Find as much warnings/important notes as you can in `ui/docs/` and replace them with the warning variant of the `ErrorPanel`.
* Add a prop (e.g., `keepOpen`) to `src/components/ErrorPanel` that would not show the "x" icon button

**Comment by aimenbatool** [comment]
I'm taking this issue.

**Comment by aimenbatool** [comment]
Hi @helfi92 ! which service am I suppose to run to get this documentation? [As mentioned](https://github.com/taskcluster/taskcluster#usage) there are individual services.

**Comment by arku** [comment]
@aimenbatool This issue is related to the docs site which lives in [`ui`](https://github.com/taskcluster/taskcluster/tree/master/ui). You can find the instructions [here](https://github.com/taskcluster/taskcluster/blob/master/dev-docs/development-process.md#hacking-on-the-ui) to get the UI up and running. Once done, you can visit http://localhost:5080/docs/ to view the docs. Let us know if you have any other questions.

**Comment by aimenbatool** [comment]
@arku Thanks!

**Comment by helfi92** [comment]
Resolved in https://github.com/taskcluster/taskcluster/commit/044e603f4e15bb326d4071dd6e9ef3ccb55660b5.
