### ISSUE TITLE
[UI] Can't copy from scope expander

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#1211]
Steps to reproduce:

* https://taskcluster-ui.herokuapp.com/auth/scopes/expansions
* enter a scope like `assume:project:taskcluster:gecko:level-3-sccache-buckets`
* click the expand button way down in the corner
* try to copy/paste the resulting expanded scopes

**Comment by helfi92** [comment]
To fix this issue, we would need to stop using the button prop https://github.com/taskcluster/taskcluster/blob/master/ui/src/views/Scopes/ScopesetExpander/index.jsx#L87

and instead add a hover effect similar to the one used by a button to 

https://github.com/taskcluster/taskcluster/blob/bb08a08d5aa050680b22cd6fe227ac0339dd03ad/ui/src/theme.js#L159-L170

In the interest of maintaining consistency, we would need to look for all places where we use the `button` prop with the `ListItem` component and remove the `button` prop.

**Comment by rbrishabh** [comment]
I would like to take this up!

**Comment by helfi92** [comment]
Go for it

**Comment by Hansolo-72** [comment]
can I take this ?

**Comment by rbrishabh** [comment]
Hi @Hansolo-72, I am already doing this! 😀
