### ISSUE TITLE
smoketest - create a task for built-in/succeed and wait for it to succeed

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#1240]
Add a new test to the `yarn smoketest` by adding a module to `infrastructure/tooling/src/smoketest/checks/`.  In this case, it would create a new task for the `built-in/succeed` worker-type, and wait for that task to be claimed and succeed.

See #1218.

**Comment by ededals** [comment]
Hi,

I would like to try to solve this. Is there some example on how to create a task of built/in succeed type ir should I pretty much go and discover it myself?

**Comment by djmitche** [comment]
You'll probably want to try creating such a task using the [task creator](https://tools.taskcluster.net/task-creator/).  Once you're signed in, if you let me know your clientId as shown at https://tools.taskcluster.net/credentials then I can grant you permission to create a task for that worker pool (specifically, you'll set provisionerId to `built-in` and workerType to `succeed`).

**Comment by ededals** [comment]
My clientId: mozilla-auth0/github|43218607|ededals

**Comment by djmitche** [comment]
You should be all set!

**Comment by ededals** [comment]
Hey @djmitche 
I think I finally understood how to do this, but there is one problem. When I am trying to run the test I receive some exception connected to permissions:

```
(node:7217) UnhandledPromiseRejectionWarning: Error: This request requires Taskcluster credentials that satisfy the following scope expression:
{
  "AllOf": [
    {
      "AnyOf": [
        {
          "AllOf": [
            "queue:scheduler-id:-",
            {
              "AnyOf": [
                "queue:create-task:highest:built-in/succeed",
                "queue:create-task:very-high:built-in/succeed",
                "queue:create-task:high:built-in/succeed",
                "queue:create-task:medium:built-in/succeed",
                "queue:create-task:low:built-in/succeed",
                "queue:create-task:very-low:built-in/succeed",
                "queue:create-task:lowest:built-in/succeed"
              ]
            }
          ]
        },
        {
          "AnyOf": [
            "queue:create-task:built-in/succeed",
            {
              "AllOf": [
                "queue:define-task:built-in/succeed",
                "queue:task-group-id:-/EfEcxJsZSfuTkOGMX3IDzg",
                "queue:schedule-task:-/EfEcxJsZSfuTkOGMX3IDzg/EfEcxJsZSfuTkOGMX3IDzg"
              ]
            }
          ]
        }
      ]
    }
  ]
}
```

Is this connected to wrong run method of my test or should I specify extra permissions in tools.taskcluster.net?

**Comment by djmitche** [comment]
Awesome!  That the error is unhandled *is* a problem, but otherwise the fix is to run the tests with credentials that have the necessary scopes.  What are you using for TASKCLUSTER_CLIENT_ID?
