### ISSUE TITLE
smoketest - create a task for built-in/fail and wait for it to succeed

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#1241]
Add a new test to the `yarn smoketest` by adding a module to `infrastructure/tooling/src/smoketest/checks/`.  In this case, it would create a new task for the `built-in/fail` worker-type, and wait for that task to be claimed and fail.

See #1218.

**Comment by ededals** [comment]
I think a small modification to succeed tests will also cover this case. I will try to make the changes.
