### ISSUE TITLE
smoketest - create a sequence of tasks with dependencies and see them succeed in order

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#1242]
Add a new test to the `yarn smoketest` by adding a module to `infrastructure/tooling/src/smoketest/checks/`.  In this case, it would create a sequence of dependent tasks for the `built-in/succeed` worker-type, and see that they are executed in order.

See #1218.

**Comment by ededals** [comment]
Hey,

I would like to try to solve this. How many tasks should I create?Will three be enaugh?

**Comment by djmitche** [comment]
Three is good, yeah.

**Comment by djmitche** [comment]
@all-contributors please add ededals for code

**Comment by ededals** [comment]
I am facing a problem that first task is starting to execute before last one is created. The solution I tried was to freeze first task execution by creating self-dependency and force scheduling it before status monitoring. There is a problem with permissions though, as taskId is added to schedule scope. When I try to modify my client scopes to ```queue:scheduler-id:*```  in taskcluster tools I receive an error. Is this the right approach at all? How can I modify the scope?

**Comment by ededals** [comment]
The scope error looks like this:

(node:4368) UnhandledPromiseRejectionWarning: Error: Client ID mozilla-auth0/github|43218607|ededals/ does not have sufficient scopes and is missing the following scopes:

```
{
  "AnyOf": [
    "queue:schedule-task:-/bdPWqM8FRB2V7EfJekzCXQ/bdPWqM8FRB2V7EfJekzCXQ",
    {
      "AllOf": [
        "queue:schedule-task",
        "assume:scheduler-id:-/bdPWqM8FRB2V7EfJekzCXQ"
      ]
    }
  ]
}
```

This request requires the client to satisfy the following scope expression:

```
{
  "AnyOf": [
    "queue:schedule-task:-/bdPWqM8FRB2V7EfJekzCXQ/bdPWqM8FRB2V7EfJekzCXQ",
    {
      "AllOf": [
        "queue:schedule-task",
        "assume:scheduler-id:-/bdPWqM8FRB2V7EfJekzCXQ"
      ]
    }
  ] 
}
```

The three lines where cut off in console. And I did not see the error to the end so I kind of am not sure about the ending. I will try to find how to fix this.

**Comment by djmitche** [comment]
That the error is unhandled signals an error in the code (missing await?).

What API method are you calling that returns this error?

**Comment by ededals** [comment]
Unhandled promise was caused by missing await in front of queue.scheduleTask(...) method. This consequently is also api method that is causing the error.

Here is the full error code message: 

```
{ Error: Client ID mozilla-auth0/github|43218607|ededals/ does not have sufficient scopes and is missing the following scopes:


{
  "AnyOf": [
    "queue:schedule-task:-/OglRFluERzeDj5XXrgcjIQ/OglRFluERzeDj5XXrgcjIQ",
    {
      "AllOf": [
        "queue:schedule-task",
        "assume:scheduler-id:-/OglRFluERzeDj5XXrgcjIQ"
      ]
    }
  ]
}


This request requires the client to satisfy the following scope expression:


{
  "AnyOf": [
    "queue:schedule-task:-/OglRFluERzeDj5XXrgcjIQ/OglRFluERzeDj5XXrgcjIQ",
    {
      "AllOf": [
        "queue:schedule-task",
        "assume:scheduler-id:-/OglRFluERzeDj5XXrgcjIQ"
      ]
    }
  ]
}


---

* method:     scheduleTask
* errorCode:  InsufficientScopes
* statusCode: 403
* time:       2019-10-13T07:27:29.690Z
```

**Comment by djmitche** [comment]
Got it, thanks.  So it looks like we'd need `queue:schedule-task:-/*`.  Unfortunately, that would let anyone who can run the smoketests schedule *any* task, which is probably undesirable.

Long-term, I think the fix will be to use schedulerId `smoketests` for all smoketests.

But in the short term, let's write this test to just use `createTask` and not `scheduleTask`.  That the tasks run immediately is OK, I think.  We can then assert that the start time of each task is `>=` the start time of the previous task.

**Comment by djmitche** [comment]
(we can do the long-term part in another PR)

**Comment by ededals** [comment]
Hey @djmitche ,

I see that repo is quite crowded with contributors, but I would like to continue working on this project. Maybe there is something in bugzilla I could try to work on?

**Comment by djmitche** [comment]
Would you like something in JS, or would Go be OK?

(closing this issue but we can keep discussing next project)

**Comment by ededals** [comment]
I have tried out a Go, but it was a while ago. I have nothing against brushing it up a little bit :), so I think it can be either of the two.

**Comment by djmitche** [comment]
I filed #1758.
