### ISSUE TITLE
smoketest - create an indexed task and find it in the index

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#1244]
Add a new test to the `yarn smoketest` by adding a module to `infrastructure/tooling/src/smoketest/checks/`.  In this case, it would create a task with routes for the index service, and once that task is completed look to see that the task is correctly shown in the index.

See #1218.

**Comment by Rolikasi** [comment]
@djmitche, can I take this issue?

**Comment by djmitche** [comment]
Sure!

**Comment by Rolikasi** [comment]
Do I need to sign in at https://tools.taskcluster.net/ and give you Client id?

**Comment by Rolikasi** [comment]
If you'll guide me a little bit it would be great!) I look at other smoketest issues and try to figure out how to do it)

**Comment by djmitche** [comment]
Yes, please.  The process is described in [these comments](https://github.com/taskcluster/taskcluster/issues/1247#issuecomment-537963420).

**Comment by Rolikasi** [comment]
mozilla-auth0/github\|44370635\|Rolikasi

**Comment by djmitche** [comment]
OK, I created https://tools.taskcluster.net/auth/roles/login-identity%3Amozilla-auth0%2Fgithub|44370635|Rolikasi

**Comment by Rolikasi** [comment]
For the first step do I need to create a task at https://tools.taskcluster.net/tasks/create and what do i need to put in deadline, name, description and owner?

**Comment by Rolikasi** [comment]
Sorry, I'm a bit confused. For the 1st step in task creator do i need to make task like this?
provisionerId: indexed-task
workerType: find
created: '2019-10-10T15:32:11.089Z'
deadline: '2019-10-10T18:32:11.090Z'
payload:
  image: 'ubuntu:latest'
  command:
    - /bin/bash
    - '-c'
    - for ((i=1;i<=600;i++)); do echo $i; sleep 1; done
  maxRunTime: 630
metadata:
  name: Smoketest create indexed task and read
  description: indexed task created during smoketest
  owner: smoketest@taskcluster.net
  source: 'https://tools.taskcluster.net/tasks/create'

Then the site will give me an accessToken, am I right?

**Comment by djmitche** [comment]
A "task" and a "client" are different things.  You won't be able to create a client with the task creator :)

If you still need to create a client, start at "The next step is for you to create a new client" in #1247

**Comment by djmitche** [comment]
@rolikasi were you still working on this?

**Comment by Rolikasi** [comment]
Sorry, it is hard to work on several issues at the same time. I wanna try to finish this one tomorrow

**Comment by Rolikasi** [comment]
@djmitche , I need to create task first and then find it, am I right?
I try to use createTask function, but get error bellow. Also I dont understand what did you mean by `add index routes` (
I'm very interested in finishing up this issue, it'd be great if you'll guide me a little bit))

X create an indexed task and find it in the index (Error: Client ID mozilla-auth0/github|44370635|Rolikasi/smoketests does not have sufficient scopes and is missing the following scopes:

```
{
   "AnyOf": [
     {
       "AnyOf": [
         "queue:create-task:highest:indexTask/find",
         "queue:create-task:very-high:indexTask/find",
         "queue:create-task:high:indexTask/find",
         "queue:create-task:medium:indexTask/find",
         "queue:create-task:low:indexTask/find",
         "queue:create-task:very-low:indexTask/find",
         "queue:create-task:lowest:indexTask/find"
       ]
     },
     {
       "AnyOf": [
         "queue:create-task:indexTask/find",
         {
           "AllOf": [
             "queue:define-task:indexTask/find",
             "queue:task-group-id:-/MU0QQYPVQy2Ev5M7PuHQQw",
             "queue:schedule-task:-/MU0QQYPVQy2Ev5M7PuHQQw/MU0QQYPVQy2Ev5M7PuHQQw"
           ]
         }
       ]
     }
   ]
}
```

This request requires the client to satisfy the following scope expression:

```
{
   "AllOf": [
     {
       "AnyOf": [
         {
           "AllOf": [
             "queue:scheduler-id:-",
             {
               "AnyOf": [
                 "queue:create-task:highest:indexTask/find",
                 "queue:create-task:very-high:indexTask/find",
                 "queue:create-task:high:indexTask/find",
                 "queue:create-task:medium:indexTask/find",
                 "queue:create-task:low:indexTask/find",
                 "queue:create-task:very-low:indexTask/find",
                 "queue:create-task:lowest:indexTask/find"
               ]
             }
           ]
         },
         {
           "AnyOf": [
             "queue:create-task:indexTask/find",
             {
               "AllOf": [
                 "queue:define-task:indexTask/find",
                 "queue:task-group-id:-/MU0QQYPVQy2Ev5M7PuHQQw",
                 "queue:schedule-task:-/MU0QQYPVQy2Ev5M7PuHQQw/MU0QQYPVQy2Ev5M7PuHQQw"
               ]
             }
           ]
         }
       ]
     }
   ]
}

**Comment by djmitche** [comment]
Each providerId/workerType requires corresponding scopes to start a task.  We have some "built-in" workers named built-in/succeed which the smoketests already have scopes to access. So you should be able to call createTask with providerId `built-in` and workerType `succeed`.

Once you've got that working (and you can see an example in `infrastructure/tooling/src/smoketest/checks/builtin.js`), try adding a routes property to the task definition with value `['project.taskcluster.smoketest.${randomId}']` where `randomId` is a random ID (example in `dependencies.js`).  There is a scope required for that, too, `queue:route:index.project.taskcluster.smoketest.${randomId}`, but that's already covered by queue:route:index.project.taskcluster.smoketest.* in the [project:taskcluster:smoketests role](https://tools.taskcluster.net/auth/roles/project%3Ataskcluster%3Asmoketests).

Once you've done that, you can find the task under the index browser (https://tools.taskcluster.net/index) and similarly can make an API call to index.findTask to get the taskId.

**Comment by Rolikasi** [comment]
Thanks for the help @djmitche !)
