### ISSUE TITLE
smoketest - create a client and use it

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#1245]
Add a new test to the `yarn smoketest` by adding a module to `infrastructure/tooling/src/smoketest/checks/`.  In this case, it would create a client in the auth service, get back an accessToken, and then use the resulting accessToken to make an API call.

See #1218.

**Comment by ANURADHAJHA99** [comment]
@djmitche I would like to take this issue and do more research on it and try to solve it. Can you please assign the following issue to me?

**Comment by ANURADHAJHA99** [comment]
Can you please give me an insight into how the clients are made? Also, how are we going to run the test(the platform where we are going to run the test) etc? I am sorry to cause you inconvenience, but it will be very helpful.

**Comment by djmitche** [comment]
Clients are made with the aptly-named [auth.createClient](https://docs.taskcluster.net/docs/reference/platform/auth/api#createClient) API method.  To create a client, you'll need some scopes, though.  I just added those scopes to the [`project:taskcluster:smoketests`](https://tools.taskcluster.net/auth/roles/project%3Ataskcluster%3Asmoketests) role.

The intent is for smoketests to be run by administrators to make sure a deployment is working properly.  So it would be run from a terminal with `yarn smoketest`.  To do that, you'll need to set `TASKCLUSTER_CLIENT_ID`, `TASKCLUSTER_ACCESS_TOKEN`, and `TASKCLUSTER_ROOT_URL` environment variables.  For which you will need to create a client.  If you sign in at https://tools.taskcluster.net/, and go to https://tools.taskcluster.net/credentials, and let me know what `clientId` you see there, I can set that up for you.

**Comment by ANURADHAJHA99** [comment]
![Screenshot from 2019-10-08 20-30-25](https://user-images.githubusercontent.com/34815869/66407297-990f4c80-ea0a-11e9-9b50-2c42e9b884ad.png)

The client-ID is mozilla-auth0/github|34815869|ANURADHAJHA99

**Comment by ANURADHAJHA99** [comment]
@djmitche I provided the details above. Can you kindly check them? Thank you or the help

**Comment by djmitche** [comment]
OK, you now have the smoketest role, giving you all of the scopes necessary.  You also have the scopes you need to create your own client using https://tools.taskcluster.net/auth/clients/.  The scope is `auth:create-client:mozilla-auth0/github|34815869|ANURADHAJHA99/*` so you can create any client beginning with `mozilla-auth0/github|34815869|ANURADHAJHA99/`.  Once you create a client, the UI will give you the access token for that new client.  You can use that to fill in the environment variables.  The root URL is `https://taskcluster.net`.

**Comment by ANURADHAJHA99** [comment]
@djmitche Thank you very much. Can you please give me instructions, as to how I have to proceed after generating the secret token? I am very sorry to bother but it will be highly helpful.

**Comment by ANURADHAJHA99** [comment]
@djmitche I have set the environment variables successfully, can you please tell me what is the next step?

**Comment by djmitche** [comment]
Great!  Now if you run `yarn smoketest` it should succeed.

If it does, then you can get on to writing your own smoketest.  The smoketests are all in https://github.com/taskcluster/taskcluster/tree/master/infrastructure/tooling/src/smoketest/checks and you can find an example of one that @ededals wrote in there, as well as @ajinkabeer 's in #1525.  This issue is a little more similar to #1525 in that it involves creating something, checking it, and then deleting it.  The tricky bit here is that when you create the client, you'll want to give it some scopes, and the return value will have an accessToken.  You'll want to create a new `taskcluster-client` client object using that returned accessToken, and then do something with the result to make sure it works.  I'd suggest that "something" be calling `auth.updateClient` to change the description of the client you just created.

Anyway, get a smoketest started and we can work on the details :)

**Comment by ANURADHAJHA99** [comment]
`const taskcluster = require('taskcluster-client');

const options = {
    method: 'post',
    url: '/clients/<clientId>',
    data = {
        "$id": "/schemas/auth/v1/create-client-request.json#",
        "$schema": "/schemas/common/metaschema.json#",
        "additionalProperties": false,
        "description": "Properties to create a client.\n",
        "properties": {
          "deleteOnExpiration": {
            "default": false,
            "description": "If `true`, the service may delete this client after it has expired.  If\n`false` (the default), the client will remain after expiration, although\nit cannot be used for authentication in that state.\n",
            "type": "boolean"
          },
          "description": {
            "description": "Description of what these credentials are used for in markdown.\nShould include who is the owner, point of contact.\n",
            "maxLength": 10240,
            "type": "string"
          },
          "expires": {
            "description": "Date and time where the clients access is set to expire\n",
            "format": "date-time",
            "type": "string"
          },
          "scopes": {
            "description": "List of scopes the client has (unexpanded).\n",
            "items": {
              "description": "A single scope. A scope must be composed of\nprintable ASCII characters and spaces.  Scopes ending in more than\none `*` character are forbidden.\n",
              "name": "Scope",
              "pattern": "^[ -~]*$",
              "type": "string"
            },
            "type": "array",
            "uniqueItems": true
          }
        },
        "required": [
          "expires",
          "description"
        ],
        "title": "Create Client Request",
        "type": "object"
      }
    
  };
  
  // send the request
  axios(options);`


@djmitche Can you please tell me if I am taking the right step, to call the createClient API method, do I need to change the request payload data? Thank you very much for your help.

**Comment by djmitche** [comment]
The request payload you're sending looks like the body of the schema for that API method.  And, I'm not sure what `axios` is in this context.  Here's an example of creating a secret, if that sets you on the right course:
https://github.com/taskcluster/taskcluster/blob/ceef3fee91538e01b7ed7bd4aa18c9da1536162b/infrastructure/tooling/src/smoketest/checks/secrets.js#L12-L22

The idea is to create a new client object (in your cause `new Auth`, rather than `new Secrets` in the above) and then call the API method using that client object.

**Comment by djmitche** [comment]
@ANURADHAJHA99 were you still working on this?

**Comment by ajinkabeer** [comment]
Hello @ANURADHAJHA99, are you still working on this? If you need any help please do ask and I will help you!

**Comment by djmitche** [comment]
I think we'll use a more restricted scope than that, like `auth:create-client:project/taskcluster/smoketest/*` :)

But before jumping onto that, could you take a look at the cleanup?  It doesn't appear to be cleaning up.. I still see lots of temporary roles in https://tools.taskcluster.net/auth/roles/project%3Ataskcluster%3Asmoketest%3ADGLJtjY1TW67aBrFtONl0w%3A* from many days ago.

**Comment by ajinkabeer** [comment]
I just called and  logged `listRoles2()` right after exiting the while loop. Seems like they are cleaned up. But I wonder whats actually going wrong in the test. I will keep testing it though!
@djmitche

**Comment by ajinkabeer** [comment]
Yes, got it! I found that my `anHourAgo` condition is not working properly. I will fix it at create a new pull request.
@djmitche

**Comment by ajinkabeer** [comment]
> I think we'll use a more restricted scope than that, like `auth:create-client:project/taskcluster/smoketest/*` :)
> 
> But before jumping onto that, could you take a look at the cleanup? It doesn't appear to be cleaning up.. I still see lots of temporary roles in https://tools.taskcluster.net/auth/roles/project%3Ataskcluster%3Asmoketest%3ADGLJtjY1TW67aBrFtONl0w%3A* from many days ago.

Can I start on this one please? 
@djmitche

**Comment by djmitche** [comment]
Have at it!

**Comment by ajinkabeer** [comment]
Oh, thank you!!. I managed to retrieve the access token. Are there any specific API's which I can call using this access token?
@djmitche

**Comment by djmitche** [comment]
I think you'll want `auth.createClient`, and create a client named `project/taskcluster/smoketest/${randomId}`.  If you set deleteOnExpiration and make expires an hour in the future, then there will be no need for cleanup.

**Comment by ajinkabeer** [comment]
Fantasic. Can you take a look at #1905 please?
@djmitche

**Comment by ajinkabeer** [comment]
I think we can close this issue, right @djmitche ?

**Comment by djmitche** [comment]
Yes, thanks for the reminder :)
