### ISSUE TITLE
smoketest - create a role and expand it

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#1246]
Add a new test to the `yarn smoketest` by adding a module to `infrastructure/tooling/src/smoketest/checks/`.  In this case, it would create a parameterized role in the auth service, then call `auth.expandScopes` to see that the role expands properly.

See #1218.

**Comment by JiwoonKim** [comment]
Hi! I am an Outreachy Applicant and have previously submitted one pull request for one of the `good first issue` labeled issues. I am still waiting for the pull request to be approved, but thought that this is an interesting issue because my last issue was about editing the role UI :)
I understand that the other `good first issue` labeled issues are reserved for other applicants (I hope they all get the opportunity to contribute, I learned a lot! :) )
Was wondering if it would be okay to maybe take one of the harder issues like this. Would it be okay to take this one, please?

**Comment by djmitche** [comment]
Are you still working on #987?

**Comment by ajinkabeer** [comment]
I am not assigned any issues at the moment, and if @JiwoonKim is not currently working on it, can I try this one out please?
@djmitche

**Comment by djmitche** [comment]
Sure!

**Comment by djmitche** [comment]
Whoops, sorry, mixed up the usernames there!

**Comment by djmitche** [comment]
I think we'll want to do something similar to what we did with clients, where we generate a random roleId each time.  So I've added
```
auth:create-role:project:taskcluster:smoketest:*
auth:update-role:project:taskcluster:smoketest:*
auth:delete-role:project:taskcluster:smoketest:*
```
and also, as a collection of scopes that you can give to the role you create,
```
project:taskcluster:smoketest:*
```

One difference from clients is, roles don't "expire".  So we'll need to find a way to make sure that smoketests clean up after themselves.  The first version of the test you write should just be careful to delete the role it creates; we can do a second PR to add some "cleanup" in case a test fails to delete its own role.

**Comment by ajinkabeer** [comment]
> I think we'll want to do something similar to what we did with clients, where we generate a random roleId each time. So I've added
> 
> ```
> auth:create-role:project:taskcluster:smoketest:*
> auth:update-role:project:taskcluster:smoketest:*
> auth:delete-role:project:taskcluster:smoketest:*
> ```
> 
> and also, as a collection of scopes that you can give to the role you create,
> 
> ```
> project:taskcluster:smoketest:*
> ```
> 
> One difference from clients is, roles don't "expire". So we'll need to find a way to make sure that smoketests clean up after themselves. The first version of the test you write should just be careful to delete the role it creates; we can do a second PR to add some "cleanup" in case a test fails to delete its own role.

Can you please take a look at my pull request?

**Comment by djmitche** [comment]
So, next steps:
 * [ ] [parameterized roles](https://docs.taskcluster.net/docs/reference/platform/auth/roles#parameterized-roles) - let's change the test to create a parameterized role (so, one with `<..>` in its scopes and `*` at the end of its roleId), and then expand an example of that scope, and verify that the resulting expansion is what we expect.
  * [ ] The assertion should have an explicit list of scopes that it expects, rather than just asserting that it is equal to `createdRole.expandedScopes`.  The rationale is that we want to test that the Auth service is generating the right output.  What landed in #1662 just checks that the Auth service generates the same output in two different ways -- but that output might be wrong!
 * [ ] clean up: at the end of the test, please use [listRoles2](https://docs.taskcluster.net/docs/reference/platform/auth/api#listRoles2), including its pagination feature, to look for roles that this check might have created in the past (based on the pattern of roleId it creates).  For any matching roles, look at the lastModified date, and if it is older than 1 hour, remove the role.  This will allow us to eventually "clean up" any leftover roles from failed test runs, crashed workers, etc.  The "older than 1 hour" part avoids deleting a role that is being used by another check running at exactly the same time (which can happen more often than you'd think!)

**Comment by djmitche** [comment]
You're doing great work on these, by the way.  This is some complex backend JS work!

**Comment by ajinkabeer** [comment]
> So, next steps:
> 
> * [ ]  [parameterized roles](https://docs.taskcluster.net/docs/reference/platform/auth/roles#parameterized-roles) - let's change the test to create a parameterized role (so, one with `<..>` in its scopes and `*` at the end of its roleId), and then expand an example of that scope, and verify that the resulting expansion is what we expect.
> * [ ]  The assertion should have an explicit list of scopes that it expects, rather than just asserting that it is equal to `createdRole.expandedScopes`.  The rationale is that we want to test that the Auth service is generating the right output.  What landed in #1662 just checks that the Auth service generates the same output in two different ways -- but that output might be wrong!
> * [ ]  clean up: at the end of the test, please use [listRoles2](https://docs.taskcluster.net/docs/reference/platform/auth/api#listRoles2), including its pagination feature, to look for roles that this check might have created in the past (based on the pattern of roleId it creates).  For any matching roles, look at the lastModified date, and if it is older than 1 hour, remove the role.  This will allow us to eventually "clean up" any leftover roles from failed test runs, crashed workers, etc.  The "older than 1 hour" part avoids deleting a role that is being used by another check running at exactly the same time (which can happen more often than you'd think!)

Wow!, looks challenging and I am really looking forward to solving it.

**Comment by ajinkabeer** [comment]
> You're doing great work on these, by the way. This is some complex backend JS work!

Thank you, that means a lot coming from you. And also thanks for guiding me through the tests, I will keep up my work.

**Comment by ajinkabeer** [comment]
Yes, got it! I found that my `anHourAgo` condition is not working properly. I will fix it at create a new pull request.
@djmitche

**Comment by ajinkabeer** [comment]
I think I managed to fix the clean up issue. Can you take a look at it please?
@djmitche

**Comment by ajinkabeer** [comment]
I think we can close this issue, right? 

@helfi92 @djmitche

**Comment by djmitche** [comment]
Yes, thanks!
