### ISSUE TITLE
smoketest - create a secret and read it back

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#1247]
Add a new test to the `yarn smoketest` by adding a module to `infrastructure/tooling/src/smoketest/checks/`.  In this case, it would create a secret in the secrets service, then read that secret back.

See #1218.

**Comment by ajinkabeer** [comment]
I am interested in working on this test. Can you assign it to me please?
@djmitche

**Comment by djmitche** [comment]
Sure!  You can find a bit of an example in #1240.  To finish this, you'll need Taskcluster credentials.  Sign in to https://tools.taskcluster.net, then go to "Manage Credentials" and tell me what it shows for ClientId.  Once that is done, we can create a client for you to use.

**Comment by ajinkabeer** [comment]
Yes, my client id is _mozilla-auth0/github\|30138596\|ajinkabeer_ 
@djmitche

**Comment by djmitche** [comment]
Great!  I created a role to give you the necessary scopes to run the smoketests: https://tools.taskcluster.net/auth/roles/login-identity%3Amozilla-auth0%2Fgithub|30138596|ajinkabeer

The next step is for you to create a new client, using https://tools.taskcluster.net/auth/clients/.  The tool will suggest the beginning of the clientId, and you can add "smoketests" to the end of it to remember what it's for.  Give the client the scope `assume:project:taskcluster:smoketests`.  Once you create the client, the site will give you an accessToken.  In your terminal, set these environment variables:

```
export TASKCLUSTER_ROOT_URL=https://taskcluster.net
export TASKCLUSTER_CLIENT_ID=..
export TASKCLUSTER_ACCESS_TOKEN=..
```
filling in the last two based on the client you have created.  Once that's done, running `yarn smoketest` should succeed.

Once all of that is done, we can get started!  You will see that the client you have created has scopes (among others):
```
secrets:get:project/taskcluster/smoketest/*
secrets:set:project/taskcluster/smoketest/*
```
so you will have permission to get and set secrets with names starting with `project/taskcluster/smoketest/`.  The test should invent a new secret name with this prefix, then set the secret, then get it and check that the value is the same, then remove it, and finally check that getting the secret fails (because it's gone).

**Comment by ajinkabeer** [comment]
Thanks for the detailed explanation. I have set the environment variables and on running `yarn smoketest` and it returns no errors.  

Now I can work on creating the test.

![smoke](https://user-images.githubusercontent.com/30138596/66248859-81557100-e749-11e9-8ac8-38ed6ad22a90.JPG)

@djmitche

**Comment by ajinkabeer** [comment]
I was able to set the secret, get it and check the value is same and then remove it and then getting the secret fails. @djmitche 

- Setting the secret

![1](https://user-images.githubusercontent.com/30138596/66248961-e3fb3c80-e74a-11e9-8af5-03c78af98c4a.JPG)

- Getting the secret and checking if the value is same

![2](https://user-images.githubusercontent.com/30138596/66248972-186ef880-e74b-11e9-91ba-627a1af6656f.JPG)

![3](https://user-images.githubusercontent.com/30138596/66248971-13aa4480-e74b-11e9-994c-374aeacf7d94.JPG)

- After deleting the secret

![delete](https://user-images.githubusercontent.com/30138596/66248975-2290f700-e74b-11e9-8ff3-6fdd7c528514.JPG)

Is is the right approach, correct me if I am wrong please.

**Comment by djmitche** [comment]
Hm, I got an email about a comment that I don't see here..

**Comment by djmitche** [comment]
whoops, wrong button!

**Comment by djmitche** [comment]
Anyway, yes, the next step is writing the test that will call those Secret service API methods.

**Comment by ajinkabeer** [comment]
> Hm, I got an email about a comment that I don't see here..

Yes, I deleted the comment because I felt it was irrelevant.  It was screenshots of some trivial doubts I had.  Yes, I understood the task.

**Comment by ANURADHAJHA99** [comment]
Hi @ajinkabeer!!! I am trying to set the environment variables too for creating a smoketest as well. However, I am having a lot of trouble. What steps did you take to set the environment variable? while I have done almost everything, like installed gvm and version 1.12.9 of go, run yarn generate and then try to set the environment variables but nothing is working! I am very sorry to disturb you but your help will be very appreciated.

**Comment by ajinkabeer** [comment]
> Hi @ajinkabeer!!! I am trying to set the environment variables too for creating a smoketest as well. However, I am having a lot of trouble. What steps did you take to set the environment variable? while I have done almost everything, like installed gvm and version 1.12.9 of go, run yarn generate and then try to set the environment variables but nothing is working! I am very sorry to disturb you but your help will be very appreciated.

Oh It's okay, I can help you out. What is the error exactly? Which environment variable are you not able to set?

**Comment by ANURADHAJHA99** [comment]
@ajinkabeer The error is mentioned below:-
TASKCLUSTER_CLIENT_ID= mozilla-auth0/github|34815869|ANURADHAJHA99
bash: export: `mozilla-auth0/github': not a valid identifier
34815869: command not found
ANURADHAJHA99: command not found

Also when I am trying to set the Client_id environment variable, the following error occurs.

**Comment by ajinkabeer** [comment]
Okay, can you try passing it like this with a single quote?
`TASKCLUSTER_CLIENT_ID= 'mozilla-auth0/github|34815869|ANURADHAJHA99'
`
The same applies for setting any environment variables. Tell me how it goes.

**Comment by ANURADHAJHA99** [comment]
@ajinkabeer Thank you very much. It ran successfully.

**Comment by ajinkabeer** [comment]
I am glad it helped. 
@ANURADHAJHA99

**Comment by helfi92** [comment]
Resolved in https://github.com/taskcluster/taskcluster/pull/1525.
