### ISSUE TITLE
smoketest - purge a cache

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#1248]
Add a new test to the `yarn smoketest` by adding a module to `infrastructure/tooling/src/smoketest/checks/`.  In this case, it would call the purge-cache service to create a purge, then pretend to be a worker and see that the purge was properly recorded.

See #1218.

**Comment by ajinkabeer** [comment]
Can I try this one out please?
@djmitche

**Comment by djmitche** [comment]
Sure thing!  If you need scopes added to the role, please let me know.

**Comment by ajinkabeer** [comment]
> Sure thing! If you need scopes added to the role, please let me know.

I have started working on this smoketest, I need scopes to make API requests to Purge Cache API and also can I set any random provisionerId and workerType or should I use any existing ones?

@djmitche

**Comment by djmitche** [comment]
Can you tell me the precise scopes you need?

Let's use `built-in` and `succeed` for provisionerId / workerType.

**Comment by ajinkabeer** [comment]
> Can you tell me the precise scopes you need?
> 
> Let's use `built-in` and `succeed` for provisionerId / workerType.

Yes, I need `purge-cache:built-in/succeed:This is a test cache name` as the scope.

**Comment by djmitche** [comment]
I added `purge-cache:built-in/succeed:smoketest-cache` to https://tools.taskcluster.net/auth/roles/project%3Ataskcluster%3Asmoketests

**Comment by ajinkabeer** [comment]
Okay, so that means my cacheName is smoketest-cache right? 
@djmitche

**Comment by ajinkabeer** [comment]
> I added `purge-cache:built-in/succeed:smoketest-cache` to https://tools.taskcluster.net/auth/roles/project%3Ataskcluster%3Asmoketests

Yes, It's working. Thank you.

**Comment by ajinkabeer** [comment]
I am having some doubts regarding this test. As you can see, the response I get is `request : {[object]}`. I want the data inside the object to compare if the cacheName is recorded right? Is this the right approach, can you take a loot at this screenshot please?
 
![Capture](https://user-images.githubusercontent.com/30138596/66657689-e1727880-ec5d-11e9-8baf-025a6181de80.JPG)

**Comment by djmitche** [comment]
It's looking pretty good, yeah.  I'm not sure why the errors are showing up like that, and not spelling out the actual differences.  But if you want to see what the data structure looks like, just add a `console.log` temporarily, and run `yarn smoketest | cat` to avoid the animated, colored output and show the result of console.log.

**Comment by djmitche** [comment]
#1579 fixes the error display.

**Comment by ajinkabeer** [comment]
> #1579 fixes the error display.

Nice work!

**Comment by helfi92** [comment]
Resolved in https://github.com/taskcluster/taskcluster/pull/1580.
