### ISSUE TITLE
[UI] Date picker hover effect

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1252]
STR:

1. Navigate to https://taskcluster-ui.herokuapp.com/auth/clients/mozilla-auth0%2Fad|Mozilla-LDAP|haali
2. Click on the calendar icon under "Expires"
3. Hover on the year

Expected: A hover effect similar to the demo examples in https://material-ui-pickers.dev/demo/datetime-picker

![Screen Shot 2019-08-27 at 10 20 41 AM](https://user-images.githubusercontent.com/3766511/63779323-5ce9b780-c8b4-11e9-8184-31d6fc5305a0.png)

Actual: There is no hover effect

**Comment by rbrishabh** [comment]
Definitely! I am doing this one! =)
