### ISSUE TITLE
Can't copy/paste label from task

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#1256]
**Describe the bug**
The label and other gray pills for a bug can't be copy/pasted.

![image](https://user-images.githubusercontent.com/28673/63941655-0e662580-ca3a-11e9-84aa-327b7fda3421.png)

In general, copy/paste doesn't work for a lot of parts of the UI, which makes debugging hard since I have to carefully retype things or find them in the DOM inspector and copy from there.  If it's possible to globally turn off whatever the UI is doing to prevent the browser from allowing copy/paste, that would be great.

**To Reproduce**
1. Go to https://taskcluster-ui.herokuapp.com/tasks/SDy5lkIuQiuKRxBVw-xnTA

**Expected behavior**
Every piece of text onscreen can be selected and copied

**Comment by rbrishabh** [comment]
Can I take this one up? @helfi92

**Comment by helfi92** [comment]
I think one way to make a chip selectable is via:

```diff
diff --git a/ui/src/views/Tasks/ViewTask/index.jsx b/ui/src/views/Tasks/ViewTask/index.jsx
index 7326ff8f7..e0a60a8a5 100644
--- a/ui/src/views/Tasks/ViewTask/index.jsx
+++ b/ui/src/views/Tasks/ViewTask/index.jsx
@@ -95,6 +95,16 @@ const getCachesFromTask = task =>
   link: {
     ...theme.mixins.link,
   },
+  chipLabel: {
+    whiteSpace: 'nowrap',
+    userSelect: 'text',
+    cursor: 'inherit',
+  },
+  chipRoot: {
+    whiteSpace: 'nowrap',
+    userSelect: 'text',
+    cursor: 'inherit',
+  },
 }))
 @graphql(taskQuery, {
   options: props => ({
@@ -726,6 +736,7 @@ export default class ViewTask extends Component {
               <Markdown>{task.metadata.description}</Markdown>
             </Typography>
             <Chip
+              classes={{ label: classes.chipLabel, root: classes.chipRoot }}
               className={classes.tag}
               label={
                 <Fragment>
```

A neat way to do this is to create `src/component/Chip` instead and all instances of Chip use that component.

**Comment by rbrishabh** [comment]
Alright, I'm on it!

**Comment by helfi92** [comment]
Resolved in https://github.com/taskcluster/taskcluster/commit/9708ad3226e0696947e1a5dd65eed60e7b346975.
