### ISSUE TITLE
Update date-fns to at least v2.0.0

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1263]
Relates to https://github.com/taskcluster/taskcluster/pull/1230.

The [pre-release CHANGELOG](https://gist.github.com/kossnocorp/a307a464760b405bb78ef5020a4ab136) will be useful to know what changed. We should pay special attention the changes prefixed with `BREAKING`.

**Comment by Shubhamchinda** [comment]
Can I take this?

**Comment by helfi92** [comment]
Go for it :)
