### ISSUE TITLE
[UI] Remove warning in devtools

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1273]
STR:

1. Navigate to http://localhost:5080/
2. Open devtools

**Actual:**

![Screen Shot 2019-09-03 at 10 26 28 AM](https://user-images.githubusercontent.com/3766511/64181921-55d32400-ce35-11e9-819c-2537290f5e98.png)

**Expected:** No warning in devtools.

**Comment by helfi92** [comment]
@Shubhamchinda Do you want to work on this issue? I think the issue is coming from the `Dashboard` component which every view uses. Removing this warning may actually remove this warning from every single view :)

**Comment by Shubhamchinda** [comment]
Hey @helfi92 , Why not. I 'll definitely work on this.

Thanks a lot! I'll submit a PR very soon.

**Comment by helfi92** [comment]
How is it going @Shubhamchinda? :-)

**Comment by Shubhamchinda** [comment]
Hey @helfi92 , Sorry I was a liitle busy this week, I'll do to it now! :)

**Comment by helfi92** [comment]
No worries. Sounds good!

**Comment by Shubhamchinda** [comment]
@helfi92 
The warnings are gone by removing the below line :
>https://github.com/taskcluster/taskcluster/blob/7743b620ade0d61bca3e596784962693373d7752/ui/src/components/Dashboard/index.jsx#L254

I read somewhere that `react-router-dom` doesn't have a component prop, So should we just remove it?

Thanks as always!

**Comment by helfi92** [comment]
I think the problem, if i understand correctly from the warning, is that the `div` element doesn't take a `component` prop. The `Link` component is needed so we can't remove it unfortunately.

You should be able to remove this warning by probably doing something like:

```jsx
const logoWithApplicationName = (
  <Fragment>
    <img ... />
    <Typography ... />
  </Fragment>
);
```

then if `DOCS_ONLY` is `true`, we could render:

```jsx
<Link ...>
  {logoWithApplicationName}
</Link>
```

else, we render:

```jsx
<div ...>
  {logoWithApplicationName}
</div>
```

**Comment by Shubhamchinda** [comment]
>. The `Link` component is needed so we can't remove it unfortunately.

Yes, I know.

Thanks a lot. I'll submit a PR tomorrow.
