### ISSUE TITLE
[UI] Can the task viewer's log viewer show the current run time for the task?

### ISSUE THREAD

**Issue by KWierso** [taskcluster/taskcluster#1305]
I feel like it would be a useful addition to show the runtime of the current task from the logviewer UI. If we're viewing a live log, having it autoupdate with the current runtime would be nice, too.

**Comment by KWierso** [comment]
Something like this: 

![Screenshot_2019-09-06 build-docker-image-desktop1604-test-iris](https://user-images.githubusercontent.com/172215/64465312-d8234880-d0c0-11e9-90ce-86bee816ea2e.png)

**Comment by helfi92** [comment]
By runtime, do you mean the status (e.g., "Running") of the Task? Also, I am assuming you are referring to the [new UI](https://taskcluster-ui.herokuapp.com/)?

**Comment by KWierso** [comment]
No. In a situation where a task started running at 10:34:00 and the current time is 10:38:00, the runtime for the task would be 04:00 (four minutes, zero seconds). 

30 seconds later, the runtime would be 04:30 (four minutes, thirty seconds).

When the task finishes at 10:45:37, the final runtime for the task would be 11:37 (eleven minutes, thirty-seven seconds).

**Comment by biddwan09** [comment]
Hi @helfi92  can I please work on this ??  I wanted to start contributing to this project

**Comment by lotas** [comment]
This might be combined with #222 to display extra information about runs
