### ISSUE TITLE
[UI] Hook form

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1306]
In an effort to start to start the ball rolling on https://github.com/taskcluster/taskcluster/issues/835, I think we can start by working on the hooks view (e.g., https://taskcluster-ui.herokuapp.com/hooks/garbage/abc456).

The main task may involve making use of extra spacing between sections, adding dividers/borders, changing header variants, etc. to make the form easier to read.

**Comment by rbrishabh** [comment]
Hey! I'm about to read more into this.. But I'm taking this one up!
@helfi92

**Comment by rbrishabh** [comment]
Hey @helfi92 !

For some reason, after pulling the latest code from master, and trying to work on this bug on a different branch, I keep getting this error: 

![now](https://user-images.githubusercontent.com/22501334/64626875-36776080-d40c-11e9-9605-9b5186463751.png)

I am not sure why this error is coming. I did try and restart both web-server and ui many times, but still this persists.

Any idea why this is happening?
Thanks!

**Comment by helfi92** [comment]
Any interesting output in the dev-tools? A screenshot might help.

**Comment by rbrishabh** [comment]
Nevermind! Fourth time lucky.

I restarted it again this to get a screenshot, and it worked.


Anyways, coming back to the main issue, by [this](https://github.com/taskcluster/taskcluster/issues/1306#issue-491094872) comment, you meant,

We want to make use of extra space by:
1. Adding dividers / borders (Is this what we need for dividers - https://material-ui.com/components/dividers/ - of course of Material-UI v3) 
2. Changing header variants (I am guessing making headers bigger to use space efficiently?)

Also, do we want to make some of the ListItems more compact by introducing ```row flex``` between some of the ListItems?

For eg:

![now](https://user-images.githubusercontent.com/22501334/64628700-7e4bb700-d40f-11e9-8f74-16ee37f45396.png)

We could flex together Hook Group ID & Hook ID together?

Do let me know! Thanks

**Comment by helfi92** [comment]
Right now the UI feels rather cluttered (things are too close to each other). Adding spacing and dividers might help make things more breathable. Dividers may not be needed but it is worth experimenting with them.

> Changing header variants (I am guessing making headers bigger to use space efficiently?)

Maybe. I'm not sure. When I referred to spacing, I was referring more to the space between each component. Feel free to experiment with whatever comes to mind.

> We could flex together Hook Group ID & Hook ID together?

Maybe. I'm also not sure here. Feel free to experiment with that if you want.

**Comment by rbrishabh** [comment]
Alright! That leaves me with a lot of open room to be artistic!

I'll get to this, and will soon create a PR where we can then discuss how to proceed this. :D

**Comment by helfi92** [comment]
How is it going @rbrishabh?

**Comment by rbrishabh** [comment]
I made some changes! I will put up a PR later today so that we can see how this is going.

**Comment by rbrishabh** [comment]
Hey @helfi92 ! Sorry for the short delay! I have exams till Friday. I will put a PR as soon as possible!

**Comment by helfi92** [comment]
No worries at all! Good luck on your exams :)

**Comment by rbrishabh** [comment]
Thanks!

**Comment by helfi92** [comment]
Hey @rbrishabh 👋 I have a local copy of some enhances I would like to integrate in the hook view. I think it might give an idea of what I am looking for which will help in other views that have forms. Perhaps you can work on improving the layout of http://localhost:5080/quickstart? If that sounds interesting, I can create an issue for it and have it assigned to you :) I plan on pushing my branch sometime today.

**Comment by rbrishabh** [comment]
Hey @helfi92! Alright! That sounds great!
I actually had to get a new laptop because the last one was too slow to run taskcluster (particularly after some patch during September - before that it worked a little faster on Windows) and in general - it was slow.

To put it into context, I had to wait at least 45 mins to get Taskcluster up and running. And then wait 10 mins for it to compile when I made even a small change. Anyways, my new laptop is arriving tomorrow and I'm getting back to work right after. 

Although, I made some changes to this one but couldn't put up a PR because of the reason I just mentioned, I'm happy to look into how you're going to do this. So yes, you can go ahead and create another issue, more than happy to look into that one. 

Thanks again!

**Comment by helfi92** [comment]
Wow. I'm so sorry you had to go through that. Hopefully you will have a better experience with the new laptop!

> So yes, please go ahead and create the other issue, more than happy to look into that one.

Filed https://github.com/taskcluster/taskcluster/issues/1412 :)

Have a look at https://github.com/taskcluster/taskcluster/pull/1410#issue-322846137 for the hook layout. It should give a general idea of the things we should try to do for the quickstart view. Let me know if you had any questions.

**Comment by rbrishabh** [comment]
I had a look at #1410! Looks great! I get the general idea!

I'll ask if I have any questions! Thanks! :)
