### ISSUE TITLE
[UI] Remove warning

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1315]
Navigate to http://localhost:5080/auth/clients/email%2Fbastien%40nextcairn.com%2Ftc-notify-test

![Screen Shot 2019-09-10 at 9 23 28 AM](https://user-images.githubusercontent.com/3766511/64617554-ab1ab280-d3ac-11e9-9b2b-bfa407593ded.png)

Let's try to remove this error from the dev-tools.

**Comment by MisraAnandita** [comment]
Hi I would like to  contribute to this issue.  I am a beginner in open source. I have gone through the Task cluster website and have read the initial details about the tool. However, I am unable to open the link provided above for the issue. Could you help me with this? 
Thank you!

**Comment by helfi92** [comment]
Hi @MisraAnandita 👋

The [README](https://github.com/taskcluster/taskcluster/tree/master/ui#readme) inside the `ui/` directory should have information on how to run the UI locally. Once that's done, the link above should work. Give it a try and let me know.

**Comment by helfi92** [comment]
[Hacking on the UI](https://github.com/taskcluster/taskcluster/blob/master/dev-docs/development-process.md#hacking-on-the-ui) will help as well.

**Comment by MisraAnandita** [comment]
Hi @helfi92 Thank you for your prompt reply. It helped me a lot. I cloned the repository to Github Desktop. Installed node and yarn. Did the dependency installations for yarn. As I set the TASKCLUSTER_ROOT_URL to point to a Taskcluster deployment and then try to run yarn start on the services/web-server folder, I have been getting the following error:
$ NODE_ENV=development node src/main.js devServer
'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
Have been trying to debug this issue but nothing seems to work.
If you could help me on this, it would be of huge help.
Also, wanted to add that I am using a windows laptop.
Thank you!

**Comment by rbrishabh** [comment]
Hi @MisraAnandita ! There was some talk regarding this issue in windows in [this](https://github.com/taskcluster/taskcluster/pull/1236#issuecomment-524837219) comment.

There seems to be an issue with running Taskcluster on Windows.

I am working on a PR to fix that.

Meanwhile, you could use WSL for Windows.

This will help you get started:
https://docs.microsoft.com/en-us/windows/wsl/install-win10

Also, you might have to reinstall yarn packages on wsl cli, but you can always try once before that!

Hope this helps!

**Comment by Patil2099** [comment]
@helfi92 If no one is working on it, can I take this issue?

**Comment by helfi92** [comment]
@MisraAnandita Are you still working on this issue?

**Comment by helfi92** [comment]
@Patil2099 I haven't heard back from @MisraAnandita. Feel free to tackle this issue.

**Comment by Rolikasi** [comment]
Hello, I'm studying react and try to learn on practice.
I've removed this error. Sorry that I didn't ask to work on this issue
Should I proceed with a PR?

**Comment by Patil2099** [comment]
@helfi92 i thought I was going to work on it.

**Comment by djmitche** [comment]
@Patil2099 oops, had you already gotten started?  #1388 might be a good one.

**Comment by helfi92** [comment]
Resolved in https://github.com/taskcluster/taskcluster/commit/b476ccce5f434cbc230586841328d20f1abac312 🎉
