### ISSUE TITLE
[UI] Change text field into text area

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1363]
STR:

1. Navigate to http://localhost:5080/worker-manager/gecko-t-tc-worker%2Fwcosta-build-tests

Actual:

![Screen Shot 2019-09-16 at 8 48 07 AM](https://user-images.githubusercontent.com/3766511/64959239-b9f6de80-d85e-11e9-879c-c31ee34d1428.png)

Expected: A text area of multi-line. Something similar to https://taskcluster-ui.herokuapp.com/auth/roles/hook-id%3Ahg-push%2Fci-admin

![Screen Shot 2019-09-16 at 8 50 22 AM](https://user-images.githubusercontent.com/3766511/64959400-0c37ff80-d85f-11e9-8431-611b0bbe2d4a.png)

**Comment by rajk1121** [comment]
Hello, I am a complete beginner towards open source contribution. I would like to fix this issue if possible. Please tell me if I can?

**Comment by djmitche** [comment]
@helfi92, the "Expected" section here still isn't rendering the markdown (it still shows the `[]` and `()` of the link, for example).  Didn't we solve this with tabs in another view?

**Comment by helfi92** [comment]
Ah right. We should use the `MarkdownTextArea` component similar to how it's done in  https://taskcluster-ui.herokuapp.com/hooks/garbage/abc456:

![Screen Shot 2019-09-16 at 10 45 19 AM](https://user-images.githubusercontent.com/3766511/64967770-1a8e1780-d86f-11e9-98ad-c921db7c8177.png)

https://github.com/taskcluster/taskcluster/blob/ac895214a24408b91d2b44f6c591c277950dacba/ui/src/components/HookForm/index.jsx#L604-L609

**Comment by helfi92** [comment]
@rajk1121 Go for it. To get your UI running locally, you can refer to [Hacking on the UI](https://github.com/taskcluster/taskcluster/blob/master/dev-docs/development-process.md#hacking-on-the-ui) docs.

**Comment by rajk1121** [comment]
Do I need to set up the project locally on my Windows machine. If yes, then please guide me or tell me from where I can get help regarding this matter. Thanks.

**Comment by helfi92** [comment]
Yes, you will need to set up the project locally. From https://github.com/taskcluster/taskcluster/blob/master/dev-docs/development-process.md#hacking-on-the-ui:

> The files comprising the Taskcluster UI are under [`ui/`](../ui).
It relies on a microservice called web-server, which you will need to run in a different terminal window.
To run the Taskcluster UI:
>
> * In a shell window for taskcluster-web-server:
>  * Set `TASKCLUSTER_ROOT_URL` to point to a Taskcluster deployment you wish to represent in the UI.
>    For example:
>
>    ```sh
>    export TASKCLUSTER_ROOT_URL=https://taskcluster-staging.net
>    ```
 > * Change to the `services/web-server` directory and run `yarn start`.
>    This will start a web server on port 3050.
>    Note that it will warn "No Pulse namespace defined".
>    Unless you are working on parts of the UI that require Pulse support (and most do not), this > is OK.

> * In another shell window for taskcluster-ui:
>   * Change to the `ui/` directory.
>   * Run `yarn` to install the user interface's dependencies.
>    You will only need to do this when the dependencies change.
>   * Run `yarn start` to start the development server.
>    It will output a localhost URL on which you can see the site.

**Comment by rajk1121** [comment]
Alright. Will get onto it. I will get in touch with you with ASAP after I set it up locally.

**Comment by rajk1121** [comment]
I tried running the project locally n my windows machine with WSL. On running 'yarn start' command I am getting this error in services/web-server/src/main.js
![os](https://user-images.githubusercontent.com/34133408/65017650-e4bb6280-d944-11e9-8ce0-0dac99c04927.PNG)

I am stuck at this error. Any special command to be executed before?

**Comment by helfi92** [comment]
You are running an older version of node. The one we use is https://github.com/taskcluster/taskcluster/blob/7743b620ade0d61bca3e596784962693373d7752/package.json#L7

You can use https://github.com/nvm-sh/nvm to switch between different versions of node.

**Comment by rajk1121** [comment]
Oh Thanks!! That thing worked for me. I will get back to you with further proceedings.

**Comment by rajk1121** [comment]
Whenever I go to http://localhost:5080/worker-manager/gecko-t-tc-worker%2Fwcosta-build-tests, the page shows the below error. Tried to figure out what could be the reason but couldn't help it. Please tell me where I am going wrong.
![os](https://user-images.githubusercontent.com/34133408/65236782-ea58aa00-daf6-11e9-8f77-6caf30697d61.PNG)

**Comment by helfi92** [comment]
Does http://localhost:5080/worker-manager work fine? Did you add any code or is this what you get when you first fire up the page?

**Comment by rajk1121** [comment]
No, http://localhost:5080/worker-manager also doesn't seems to be working. It too throws the same error. 

No I didn't add up any code. This is what I get as soon as I visit http://localhost:5080/worker-manager or http://localhost:5080/worker-manager/gecko-t-tc-worker%2Fwcosta-build-tests

**Comment by rajk1121** [comment]
This is what the browser console say:
![os1](https://user-images.githubusercontent.com/34133408/65239404-8c2ec580-dafc-11e9-94a7-038485dad6e6.PNG)

**Comment by helfi92** [comment]
The first warning was recently fixed so if you pull the latest changes it will be gone. However, that won't fix your issue.

Hm, can you try running the following in `ui/`:

```
export TASKCLUSTER_ROOT_URL=https://taskcluster.net
yarn start
```

**Comment by rajk1121** [comment]
No, it didn't worked. The error is coming due to the empty response for graphql:
![os2](https://user-images.githubusercontent.com/34133408/65241289-cc904280-db00-11e9-9153-a170e6c34878.PNG)

Can't figure out how to remove it.

**Comment by helfi92** [comment]
Apologies, https://github.com/taskcluster/taskcluster/issues/1363#issuecomment-533087594 was meant to be run in `services/web-server`:

```
cd services/web-server
export TASKCLUSTER_ROOT_URL=https://taskcluster.net
yarn start
```

If that doesn't fix this, do you have the `ui/src/static/env.js` file? The content of that file should be:

```js
window.env = {
  "APPLICATION_NAME": "Taskcluster",
  "TASKCLUSTER_ROOT_URL": "https://taskcluster.net",
  "GRAPHQL_ENDPOINT": "/graphql",
  "GRAPHQL_SUBSCRIPTION_ENDPOINT": "/subscription",
  "DOCS_ONLY": false,
  "UI_LOGIN_STRATEGY_NAMES": "",
  "GA_TRACKING_ID": "",
  "SENTRY_DSN": ""
};
```

**Comment by rajk1121** [comment]
Oh yes, 'export' statement should have been written in services/web-server but it really skipped from my mind too. I will try this and get back to you with a fix probably this time.

**Comment by rajk1121** [comment]
@helfi92  This should have been the expected behaviour after the fix or do I have to get the 'Write' and 'Preview' tabs as well.
![os1](https://user-images.githubusercontent.com/34133408/65337234-692c1080-dbe5-11e9-896e-65cc78704ec2.PNG)

**Comment by helfi92** [comment]
Yep, we should have the "Write" and "Preview" tabs as well (https://github.com/taskcluster/taskcluster/issues/1363#issuecomment-531810781). Feel free to proceed with a PR after that. Thanks!

**Comment by rajk1121** [comment]
Is it Fine now : 


![os1](https://user-images.githubusercontent.com/34133408/65368785-1f820b00-dc63-11e9-9da3-fffdb6ac7600.PNG)

**Comment by rajk1121** [comment]
@helfi92 Submitted a request for PR for issue #1363. Please review it and tell me if it's fine or not.

Thanks.

**Comment by petemoore** [comment]
> @helfi92 Submitted a request for PR for issue #1363. Please review it and tell me if it's fine or not.
> 
> Thanks.

I believe the PR is #1379.

**Comment by rajk1121** [comment]
@petemoore Yeah. It is indeed.

**Comment by helfi92** [comment]
Resolved in https://github.com/taskcluster/taskcluster/commit/0b850723ed6a880dcf18a900a4dbea3775c9b8d4. Thank you @rajk1121 🎉
