### ISSUE TITLE
Broken link to Taskcluster index from gecko-decision-task page

### ISSUE THREAD

**Issue by stephendonner** [taskcluster/taskcluster#1371]
Hi team!

Just letting you know there's a broken link on https://docs.taskcluster.net/docs/tutorial/gecko-decision-task in https://tc.example.com/index/#gecko.v2.mozilla-central.latest.firefox/gecko.v2.mozilla-central.latest.firefox.decision - the link text reads "the Taskcluster index".

**Comment by djmitche** [comment]
Thanks!  Yeah, the tutorial is pretty outdated.  Maybe we should just remove it :)

**Comment by djmitche** [comment]
This link has been removed in a renovation of the tutorial.  Thanks!
