### ISSUE TITLE
[UI] Add link to /tasks in homepage

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1375]
STR:

1. Navigate to http://localhost:5080/
2. Login (fyi: the client ID and access token can be set to anything)
3. Look at the logged in page

Actual:

![Screen Shot 2019-09-20 at 9 45 30 AM](https://user-images.githubusercontent.com/3766511/65331790-73212580-db8b-11e9-9096-a694654ac7f8.png)

Expected:

"I want to look at a task or group of tasks" is split into two:

1. I want to look at a task (should navigate to `/tasks` when clicked)
2. I want to look at a group of tasks (should keep the current behavior which navigates to `/tasks/groups`)

**Comment by aimenbatool** [comment]
Hi! Can I take this?
