### ISSUE TITLE
[UI] Add next page button to a page in docs

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1376]
STR:

1. Navigate to http://localhost:5080/docs/manual/design/

**Actual:** There is no button to navigate to the next page of the navigation tree

**Expected:** There should be a button similar to the other sections (e.g., http://localhost:5080/docs/manual/access-control)

**Comment by helfi92** [comment]
Actually, it turns out that going to http://localhost:5080/docs/manual/access-control/third-party then clicking on the next button will end up showing the buttons in http://localhost:5080/docs/manual/design/.

We can see the same behavior with every top level sections (i.e., the titles that are shown as capital letters in the UI).

**Comment by virgilt** [comment]
@helfi92 Hi, may I work on this please?

**Comment by helfi92** [comment]
Definitely. Go for it.

**Comment by virgilt** [comment]
@helfi92 Thanks!

**Comment by RajendrasinhParmar** [comment]
@virgilt Did you already started working on this issue?

**Comment by Rolikasi** [comment]
Hi, I'm beginner in FOSS and want to fix this issue. 
I'm trying to run project on windows using WSL
But getting error
Can you help me or provide some suggestions?
![error1](https://user-images.githubusercontent.com/44370635/65389034-6eb76100-dd73-11e9-93ce-5b1c4d46be26.PNG)

**Comment by virgilt** [comment]
@RajendrasinhParmar yes working on it

**Comment by virgilt** [comment]
@helfi92 I'm a bit stuck, this is much more complicated that any other react application I've worked on. I can see where the Button component is, but not sure how it is being rendered to the page.

**Comment by Rolikasi** [comment]
@virgilt , hi! Are you working on this issue? Do you need some help?

**Comment by vishakhanihore** [comment]
@djmitche I would like to work on this

**Comment by djmitche** [comment]
Let's see how @virgilt is doing first.  Then @Rolikasi :)

Open source apps aren't *always* this busy :)

**Comment by virgilt** [comment]
@djmitche I think I almost have it. If I don’t figure it out by tomorrow night then I’ll hand it off to @Rolikasi if that’s ok.

**Comment by djmitche** [comment]
Great, thanks!  Feel free to collaborate, too -- it's open source, after all :)

**Comment by Rolikasi** [comment]
@virgilt , how is it going?
I made research and found the solution for this issue!
The problem is with window.location.pathname (URL):
It is not only in top level sections, you can try to load http://localhost:5080/docs/manual/access-control/third-party/
If it end with "/" the function findChildFromRootNode(node) doesn't work

Should I make a PR for this issue?

**Comment by virgilt** [comment]
@Rolikasi Actually didn't see your comment until I had already figured it out. Wish I had seen it sooner, would have saved a lot of time. You're right though. I added a regular expression to remove the "/" at the end of the node.
