### ISSUE TITLE
[UI] Worker pool description should be rendered as markdown

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#1377]
**Describe the bug**
The worker pool page (https://taskcluster-ui.herokuapp.com/worker-manager/some-worker-pool-id) renders the worker pool description as plain text, but I believe this should be rendered as markdown.

**To Reproduce**
1. Go to https://taskcluster-ui.herokuapp.com/worker-manager/gecko-1%2Fwin2012-gamma

**Expected behavior**
Description to be rendered as markdown.

**Actual behavior**
Description is rendered as plain text.

**Comment by helfi92** [comment]
Duplicate of https://github.com/taskcluster/taskcluster/issues/1363.
