### ISSUE TITLE
[UI] Error panel "X" icon button in light theme

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1385]
**Reserved** for [outreachy](https://www.outreachy.org/) candidates. In order for this to be assigned to you, make sure to complete the first step of the application process outlined in the [project description](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/#build-a-component-that-can-display-a-json-schema).

---

STR:

1. Navigate to https://taskcluster-ui.herokuapp.com/notify/denylist
2. Click o the light bulb icon in the app bar to switch to the light theme

**Expected:** the "X" button is white

![Screen Shot 2019-09-24 at 1 23 51 PM](https://user-images.githubusercontent.com/3766511/65535014-9a9b2980-dece-11e9-9f92-f7c7a20b3a1d.png)

Note: This is only for when the `warning` prop is not set in the [`ErrorPanel`](https://github.com/taskcluster/taskcluster/blob/master/ui/src/components/ErrorPanel/index.jsx) component. When the component is rendered as `<ErrorPanel warning ... />`, it's okay to have a black "X" button.

**Actual:** the "X" button is black

![Screen Shot 2019-09-24 at 1 23 23 PM](https://user-images.githubusercontent.com/3766511/65534976-80614b80-dece-11e9-9c5b-304287f5262d.png)

**Comment by rbrishabh** [comment]
Hey! This seems like something I can do quickly! Can I take it up?

**Comment by helfi92** [comment]
@rbrishabh I just realized that you have a couple of issues assigned to your name so I went ahead and made the issue unassigned to make room for other contributors. Sorry about that. Wishing you all the best on your exams!

**Comment by marianazangrossi** [comment]
Can I try to resolve it?
