### ISSUE TITLE
[UI] Add breadcrumbs to /tasks/index/

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1389]
STR:

1. Navigate to https://community-tc.services.mozilla.com/tasks/index
2. Click on `Buildbot`
3. Click on `branches`
4. Click on  `mozilla-esr52` then `linux64-artifact`
5. Navigate back to the step 2

**Actual:** You need to press the back button a couple of times

**Expected:** There is a breadcrumbs component that you can just click on "Buildbot" for example and it will bring you back there.

---

We use the Breadcrumb components in a couple of places in the site (e.g., https://community-tc.services.mozilla.com/provisioners/aws-provisioner-v1/worker-types/gecko-t-win10-64-gpu-s). Our Breadcrumb [implementation](https://github.com/taskcluster/taskcluster/blob/master/ui/src/components/Breadcrumbs/index.jsx) sits on top of https://material-ui.com/components/breadcrumbs/#breadcrumbs so their docs are good place to read more about the component.

In the [old implementation of this view](https://tools.taskcluster.net/index/buildbot.branches.mozilla-esr52/linux64-artifact), we were actually using breadcrumbs. The logic for that view can be found [here](https://github.com/taskcluster/taskcluster-tools/blob/17302c900904b892bc66f359c683e855beccb9a3/src/components/IndexBrowser/index.jsx#L103-L125). You will probably not need this but I'm mentioning this just in case you may find it helpful.

**Comment by vishakhanihore** [comment]
I would like to work on this.

**Comment by vishakhanihore** [comment]
@helfi92 Can I be assigned this now? I have accepted the invite.

**Comment by 47analogy** [comment]
@helfi92 I would like to work on this issue for Outreachy. Could you please assign it to me?

**Comment by djmitche** [comment]
@vishakhanihore I see you're already assigned #1388.  @47analogy it's all yours!

**Comment by 47analogy** [comment]
Appreciate it! If I have any questions, I'll reach out here.

**Comment by djmitche** [comment]
@47analogy are you still working on this?

**Comment by vishakhanihore** [comment]
Can I take it ?

**Comment by djmitche** [comment]
@vishakhanihore there are still many people who have not made their first contribution, so please allow them to claim this one.  Note that you already have three open issues assigned to you!

**Comment by 47analogy** [comment]
@djmitche Yes, I'm still working on it. PR will be coming soon.

**Comment by helfi92** [comment]
@47analogy How is it going?

https://github.com/taskcluster/taskcluster/pull/1663 just got merged and should help makes things a lot easier for you. If you rebase your work on master, then all that is needed to finish your issue is to add the breadcrumb component.

**Comment by 47analogy** [comment]
@helfi92 I added the breadcrumb component, but wasn't getting the namespace params to render properly. I'll rebase and give it another go.

**Comment by helfi92** [comment]
How is it going @47analogy?

**Comment by Rolikasi** [comment]
@47analogy, hi, are you still working on this? Do you need some help?

**Comment by helfi92** [comment]
I haven't heard back from @47analogy.

**Comment by vishakhanihore** [comment]
Can i work on it?

**Comment by helfi92** [comment]
Sure.

**Comment by Rolikasi** [comment]
@vishakhanihore, hi) How is it going? Do you need help?

**Comment by vishakhanihore** [comment]
Hey Edil, thanks for asking । I have done changes on my loca. Will push it
once I wrap up my old PRs🙂

**Comment by helfi92** [comment]
This issue is still available for someone to pick up.

**Comment by StarWonder67** [comment]
@helfi92 Is this issue still open? I would like to work on it.

**Comment by helfi92** [comment]
Yep, it is. Go for it @StarWonder67. Let me know if you had any questions.

**Comment by StarWonder67** [comment]
@helfi92 I am new to FOSS. The link you have mentioned above is not available. Should I be adding the code to add breadcrumbs in index.jsx file under this path taskcluster/ui/src/index.jsx in the github repo?

**Comment by helfi92** [comment]
Sorry for that. I just updated the link. It should work now :)

**Comment by helfi92** [comment]
> Should I be adding the code to add breadcrumbs in index.jsx file under this path taskcluster/ui/src/index.jsx in the github repo?

No, I think the change will happen somewhere in `src/views/Tasks/TaskIndex/IndexedTask/index.jsx` and `src/views/Tasks/TaskIndex/ListNamespaces/index.jsx`.

**Comment by helfi92** [comment]
How is it going @StarWonder67 :) Still working on this?
