### ISSUE TITLE
[UI] Expand panel in Schema Index

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1391]
**Reserved** for [outreachy](https://www.outreachy.org/) candidates. In order for this to be assigned to you, make sure to complete the first step of the application process outlined in the [project description](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/#build-a-component-that-can-display-a-json-schema).

---

STR:

1. Navigate to https://taskcluster-ui.herokuapp.com/docs/reference/schema#%2Fschemas%2Fauth%2Fv1%2Fclient-message.json%23

**Expected:** the panel for "Client Message" is open since we link to it directly in the URL `#%2Fschemas%2Fauth%2Fv1%2Fclient-message.json%23`

<img width="1136" alt="Screen Shot 2019-09-24 at 4 10 15 PM" src="https://user-images.githubusercontent.com/3766511/65546619-da214000-dee5-11e9-8e62-e1a4c6191aa0.png">

**Actual:** the panel for "Client Message" is not open

<img width="1174" alt="Screen Shot 2019-09-24 at 4 10 25 PM" src="https://user-images.githubusercontent.com/3766511/65546618-d988a980-dee5-11e9-8273-26aa9566ae80.png">

This seems to only be an issue for anything under `/docs/reference/schema`. It works for other panels like `/docs/reference/platform/auth/api` (e.g., https://taskcluster-ui.herokuapp.com/docs/reference/platform/auth/api#disableClient)

**Comment by vishakhanihore** [comment]
I would love to solve the following.

**Comment by vishakhanihore** [comment]
Can I be assigned this issue now?

**Comment by 47analogy** [comment]
@helfi92  I would like to work on this issue for Outreachy. Could you please assign it to me?

**Comment by SirPhemmiey** [comment]
@helfi92 @djmitche I want to work on this issue for Outreachy. I have finished the first step as required and i've been given a go-ahead. Please assign this to me. Thanks

**Comment by djmitche** [comment]
@vishakhanihore and @47analogy both have issues assigned already, so this one is for @SirPhemmiey :)

**Comment by djmitche** [comment]
@SirPhemmiey are you still working on this?

**Comment by vishakhanihore** [comment]
Can I take it ?

**Comment by djmitche** [comment]
@vishakhanihore there are still many people who have not made their first contribution, so please allow them to claim this one.

**Comment by shilpiverma509** [comment]
Can I work on this ? @djmitche

**Comment by shilpiverma509** [comment]
I think the problem lies in the way the state variable expanded is set in this case. @djmitche Please let me know if I can try working on this one.

**Comment by shilpiverma509** [comment]
@djmitche  I have submitted a PR for this issue. Can you assign it to me now as @SirPhemmiey suggested to take this issue.
