### ISSUE TITLE
[UI] Remove copy icon button from Task view

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1395]
**Reserved** for [outreachy](https://www.outreachy.org/) candidates. In order for this to be assigned to you, make sure to complete the first step of the application process outlined in the [project description](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/#build-a-component-that-can-display-a-json-schema).

---

STR:

1. Navigate to https://taskcluster-ui.herokuapp.com/tasks/eWxW0D38QgOv9WZNKgCgAg
2. Locate the Worker Type item in the left panel

Actual:

![Screen Shot 2019-09-25 at 4 49 40 PM](https://user-images.githubusercontent.com/3766511/65638639-85002f80-dfb4-11e9-9934-abff84717652.png)

Expected:

![Screen Shot 2019-09-25 at 4 51 43 PM](https://user-images.githubusercontent.com/3766511/65638768-cf81ac00-dfb4-11e9-8aa8-acddfb44e93d.png)

Reason for change: we previously weren't able to select text in a list item button but that's no longer the case ever since https://github.com/taskcluster/taskcluster/issues/1256 was resolved.

A similar change should also be done to the Dependencies list item (click "More..." on the left panel to see it) and the Worker ID list item in the right panel:

![Screen Shot 2019-09-25 at 4 58 25 PM](https://user-images.githubusercontent.com/3766511/65639244-bb8a7a00-dfb5-11e9-8b8c-c76ad75df109.png)
![Screen Shot 2019-09-25 at 4 58 33 PM](https://user-images.githubusercontent.com/3766511/65639246-bb8a7a00-dfb5-11e9-9c26-199af5dfca8b.png)

**Comment by zbeproud** [comment]
@helfi92 Can I please try to fix this issue?

**Comment by helfi92** [comment]
Hi @zbeproud. From https://github.com/taskcluster/taskcluster/issues/1395#issue-498521170, this issue is actually reserved for [outreachy](https://www.outreachy.org/) candidates. In order for this to be assigned to you, make sure to complete the first step of the application process outlined in the [project description](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/#build-a-component-that-can-display-a-json-schema).

**Comment by zbeproud** [comment]
@helfi92 I seem to have missed the deadline to apply for this. If not this issue, is there another issue which I as a beginner can solve?

**Comment by djmitche** [comment]
Let's try https://github.com/taskcluster/tc-admin/issues/15 and see how that goes.  There are a few other bits to work on with tc-admin and ci-admin, if you enjoy that issue.

**Comment by Rolikasi** [comment]
I can work on it!

**Comment by djmitche** [comment]
All yours!
