### ISSUE TITLE
"Compare Scopesets" and "Expand Scopesets" should have a linkable URL

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#1398]
**Reserved** for [outreachy](https://www.outreachy.org/) candidates. In order for this to be assigned to you, make sure to complete the first step of the application process outlined in the [project description](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/#build-a-component-that-can-display-a-json-schema).

---

When working with scopes in a chat conversation, it would be useful to be able to link to these two tools with their values filled in already.  For example, I should be able to enter some scopes into the Scope Expander, click expand, and then copy the URL bar and paste it into a chat.  Currently, the URL does not change.

**Comment by mkneumann777** [comment]
I would like to try and tackle this 'bug.'

**Comment by djmitche** [comment]
All yours!

**Comment by djmitche** [comment]
You can find the scopesets utilities under "Authorization" section of the menu. It might help to read a little bit about scopes in the documentation to understand what these tools do.

As for the UI changes, if you search for task MSjwqraNRdS4Q4i3CSLjuw in the task inspector, you'll see that the URL changes to include the taskId, e.g., `https://localhost:5080/tasks/MSjwqraNRdS4Q4i3CSLjuw`.  We want to do the same kind of thing for these tools, so that I, as a user, can come and type some stuff into the boxes and then easily send a link to another person to show them what I'm seeing.

**Comment by djmitche** [comment]
@mkneumann777 are you still working on this?

**Comment by mkneumann777** [comment]
Yes, I am still working towards solving this issue. I just finished up my Web Developer Bootcamp and started working through a React.js course so I can have an understanding of JSX and React.js as a whole.

**Comment by mkneumann777** [comment]
I have made it through about 25% of my React course at this time. However, at this point, I don't think I'm any closer to solving this issue. From what I currently understand is that I need to get `scopeTextA` & `scopeTextB` values and update the URL params. Then when that URL is executed the application takes said params values and plugs them into the appropriate places.

**Comment by djmitche** [comment]
You've got it so far!

One good technique is to look for other examples of similar functionality.  One such example is the pulse inspector -- https://taskcluster-ui.herokuapp.com/pulse-messages?bindings%5B0%5D%5Bexchange%5D=abc&bindings%5B0%5D%5Bpattern%5D=%23

**Comment by mkneumann777** [comment]
I have developed a solution. First I used `history.push() `on the `this.props` object to explicitly return an object with 2 properties within the `if` statement in `handleCompareScopesClick()` method. I also accounted for comma use within scopes as seen in the example:

```
[
  "queue:create-task:aws-provisioner-v1/tutorial",
  "queue:route:index.garbage.*",
]
```

Within the `handleCompareScopesClick()` method:

```
handleCompareScopesClick = async () => {
  ...
  const scopeParamA = scopesA.join('%');
  const scopeParamB = scopesB.join('%');

  this.props.history.push({ 
    pathname: '/auth/scopes/compare',
    search: `?q1=${scopeParamA}&q2=${scopeParamB}`,
  });
...
}
```

This will push a new query string to the Url where each line is delimited by the '%' symbol. Now, in order for a user to share the Url. All the user has to do is share the Url in the address bar. I implemented a lifecycle method of `componentDidMount()` to take the Url parameters and set the state:

The `replace()` method is used to change all occurrences of the '%' within the query string to the newline syntax - '\n' this will place all text in the correct format.

```
componentDidMount() {
  const searchParams = new URLSearchParams(this.props.location.search);
  const scopesA = searchParams.get('qA');
  const scopesB = searchParams.get('qB');

  if (scopesA && scopesB) {
    this.setState(() => ({
      scopeTextA: scopesA.replace(/%/g, '\n'),
      scopeTextA: scopesB.replace(/%/g, '\n'),
    }));
  }
}
```

This will take any query values and pass them into the state properties. All the user has to do at this point is to click the "Compare Scopes" button.

[scopesetComparison-index.jsx.zip](https://github.com/taskcluster/taskcluster/files/3732133/scopesetComparison-index.jsx.zip)

**Comment by helfi92** [comment]
Feel free to create a pull-request. It would be easier to test the implementation that way.

**Comment by mkneumann777** [comment]
I have created a pull-request. However, do forgive me if it wasn't done correctly. This would be the first time I have creating a pull-request.

**Comment by mkneumann777** [comment]
I have closed the previous PR and created a development branch to fix the issue with `rebasing.` Opened new PR "Implementation of shareable Links #1398"
