### ISSUE TITLE
[UI] Add hover effect to the link icon in /auth/scopes

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1403]
**Reserved** for [outreachy](https://www.outreachy.org/) candidates. In order for this to be assigned to you, make sure to complete the first step of the application process outlined in the [project description](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/#build-a-component-that-can-display-a-json-schema).

---

**Describe the bug**
The hover effect on list items is missing for the list of scopes.

**To Reproduce**
1. Go to https://taskcluster-ui.herokuapp.com/auth/scopes
2. Hover your mouse on an item from the list

**Expected behavior**
Hovering adds an effect on the icon icon

**Screenshots**

Actual:

![Screen Shot 2019-09-26 at 4 03 01 PM](https://user-images.githubusercontent.com/3766511/65720988-264fba00-e077-11e9-8144-73d1a849131d.png)

![Screen Shot 2019-09-26 at 4 03 05 PM](https://user-images.githubusercontent.com/3766511/65720989-26e85080-e077-11e9-8a1d-fa8c995cddf2.png)

Expected:

![Screen Shot 2019-09-26 at 4 02 17 PM](https://user-images.githubusercontent.com/3766511/65720953-0d470900-e077-11e9-9ac8-30b664ca0c7d.png)

![Screen Shot 2019-09-26 at 4 02 22 PM](https://user-images.githubusercontent.com/3766511/65720952-0cae7280-e077-11e9-81a0-66f857e6e4da.png)

**Additional context**
The hover effect should be similar to how we do it on the rest of the site. Examples where the hover effect on the link icon works:
* https://taskcluster-ui.herokuapp.com/tasks/groups/Ld0iQrz7SQS-LgkMoIWb_Q
* https://taskcluster-ui.herokuapp.com/provisioners/aws-provisioner-v1
* https://taskcluster-ui.herokuapp.com/worker-manager

**Comment by Jo-IE** [comment]
Hi @helfi92 , I would like to work on this please :)

**Comment by Rolikasi** [comment]
@djmitche , @helfi92 , If nobody assigned to this issue, can I take it? I can't find unassigned UI issues without outreachy label.
Or can you suggest me an issue that will help me better understand how to work with JSON schema?

**Comment by Jo-IE** [comment]
Thank you @djmitche !

**Comment by djmitche** [comment]
@Jo-IE are you still working on this?

**Comment by Jo-IE** [comment]
hi @djmitche , I submitted my latest PR ( #1480 ) for it yesterday, you left a comment that I would need to wait for another reviewer for it to be merged.

**Comment by Jo-IE** [comment]
I am now working on #631 :)

**Comment by djmitche** [comment]
Perfect.  Sorry for my confusion!

**Comment by Jo-IE** [comment]
Hi @djmitche here is the link to the [gist](https://gist.github.com/Jo-IE/7a8023091ac397df59970f2975843370) with the problems i am facing regarding this issue.

**Comment by djmitche** [comment]
thanks! @helfi92 is the better person to answer

**Comment by helfi92** [comment]
Resolved in https://github.com/taskcluster/taskcluster/commit/8d7211ee6cdd20365111f145b16b3a739a5436fc.
