### ISSUE TITLE
[UI] Remove error in console

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1406]
**Reserved** for [outreachy](https://www.outreachy.org/) candidates. In order for this to be assigned to you, make sure to complete the first step of the application process outlined in the [project description](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/#build-a-component-that-can-display-a-json-schema).

---

**Describe the bug**
Navigating to the hook view shows an error in the console.

**To Reproduce**
1. Go to http://localhost:5080/hooks/garbage/abc456
2. Open the developer tools and find for the following error

![Screen Shot 2019-09-30 at 9 29 19 AM](https://user-images.githubusercontent.com/3766511/65883354-dc135500-e364-11e9-893d-8dcd7764249c.png)

**Expected behavior**
This error does not show up.

**Comment by katherine95** [comment]
I have completed the first step and would like to be assigned this one @helfi92

**Comment by ajinkabeer** [comment]
@helfi92 @djmitche 
I would like to work on this issue. Can you please assign it to me?

**Comment by djmitche** [comment]
@katherine95 it's all yours.  I'll assign to you once you accept the invitation.

**Comment by katherine95** [comment]
Thank you, Dustin. I am experiencing issues enabling the two-factor
authentication so that I can accept the repo invite.

**Comment by katherine95** [comment]
@djmitche I have a [PR](https://github.com/taskcluster/taskcluster/pull/1475) for this issue.
