### ISSUE TITLE
[UI] Remove material-ui warning in console

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1407]
**Reserved** for [outreachy](https://www.outreachy.org/) candidates. In order for this to be assigned to you, make sure to complete the first step of the application process outlined in the [project description](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/#build-a-component-that-can-display-a-json-schema).

---

**Describe the bug**
Some views complain about providing a disabled `button` child to the Tooltip component.

**To Reproduce**
1. Go to http://localhost:5080/hooks/garbage/abc456
2. Open the developer tools and spot the following error:

![Screen Shot 2019-09-30 at 9 36 30 AM](https://user-images.githubusercontent.com/3766511/65883829-cd796d80-e365-11e9-9c2e-db32eb7bd43d.png)

**Expected behavior**
This error does not show up.

**Additional context**
The reason why this happens is because when a user is logged out,  we have a Tooltip component wrapping a disabled button which material-ui doesn't like. The fix for that will probably involve wrapping the round button with a `div` element and moving the class names that the button had to the `div` element.

_Example:_

```jsx
              {/* Add <div /> to avoid material-ui error "you are providing
              a disabled `button` child to the Tooltip component." */}
              <div className={...}>
                <Button
                  variant="round" ... >
                  <ContentSaveIcon />
                </Button>
              </div>
```

You'll also probably need to do something similar for the speed dial component.

**Comment by Zitle-Nancy** [comment]
Hi, I want to try fix this is still available?

**Comment by helfi92** [comment]
Hi @Zitle-Nancy. From https://github.com/taskcluster/taskcluster/issues/1407#issue-500287017, this issue is actually reserved for outreachy candidates. In order for this to be assigned to you, make sure to complete the first step of the application process outlined in the project description.

**Comment by prehistoricpancake** [comment]
Hi @helfi92 I'd like to work on this. Already completed the first step of the process.

**Comment by djmitche** [comment]
All yours @prehistoricpancake

**Comment by djmitche** [comment]
@prehistoricpancake are you still working on this?

**Comment by prehistoricpancake** [comment]
@djmitche on it!

**Comment by prehistoricpancake** [comment]
Hey @djmitche quick question, I'm having trouble fixing this. Looked at [mui docs on this](https://material-ui.com/components/tooltips/#disabled-elements) implemented it in a similar way but I still get the console error.

Here's the code: 
`<div
          disabled={isDisabled}
          style={disabled ? { pointerEvents: 'none' } : {}}>
          <span {...spanProps}> {ButtonComponent}</span>
          </div>
      `
I moved the disabled prop from ButtonComponent to the div. 
What could I be missing?

**Comment by djmitche** [comment]
I'll defer to @helfi92 on that :)

**Comment by helfi92** [comment]
The disabled prop should stay on the Button since a disabled prop on a div doesn't do anything. A div is a HTML element whereas a Button is a React component.

Here's an example of another repo doing something similar: https://github.com/mozilla-frontend-infra/balrog-ui/blob/c403510923e2823f0575811185e8b34ee6d25413/src/views/Releases/Release/index.jsx#L321-L342. Hope that helps.

**Comment by Karskaya** [comment]
@helfi92 Can I try to fix this? As I see it's unassigned

**Comment by Karskaya** [comment]
@helfi92 As I see, warning is not because of Tooltip. Buttons which wrapped in MuiSpeedDialAction cause it. I do not see obvious way to fix it. Can you please suggest something?

**Comment by helfi92** [comment]
The fix under "Additional Context" in https://github.com/taskcluster/taskcluster/issues/1407#issue-500287017 doesn't remove this error?

**Comment by Karskaya** [comment]
@helfi92 I cannot understand how I can apply this fix to this component [MuiSpeedDialAction](https://github.com/taskcluster/taskcluster/blob/31e90eaa058c2d360e144c43a2745bc9bd0de064/ui/src/components/SpeedDialAction/index.jsx#L56)

The fix described in "Additional Context" can be applied to component like this - [Tooltip](https://github.com/taskcluster/taskcluster/blob/31e90eaa058c2d360e144c43a2745bc9bd0de064/ui/src/components/Button/index.jsx#L98). But it works fine, and do not cause warning

**Comment by helfi92** [comment]
What do you think about:

```diff
diff --git a/ui/src/components/SpeedDialAction/index.jsx b/ui/src/components/SpeedDialAction/index.jsx
index cbd08b42d..b7dc72abb 100644
--- a/ui/src/components/SpeedDialAction/index.jsx
+++ b/ui/src/components/SpeedDialAction/index.jsx
@@ -39,6 +39,7 @@ export default class SpeedDialAction extends Component {
       tooltipTitle,
       ...props
     } = this.props;
+    const other = {};
     const lackingAuth = requiresAuth && !user;
     const buttonProps = {
       ...ButtonProps,
@@ -52,12 +53,19 @@ export default class SpeedDialAction extends Component {
         }
       : null;
 
+    if (buttonProps.disabled) {
+      // Remove material-ui disabled prop warning
+      // https://github.com/mui-org/material-ui/issues/15216
+      other.component = 'span';
+    }
+
     return (
       <MuiSpeedDialAction
         className={classNames(classes.secondaryIcon, className)}
         ButtonProps={buttonProps}
         {...title}
         {...props}
+        {...other}
       />
     );
   }
```

**Comment by Karskaya** [comment]
@helfi92 Thank you! I'll try

**Comment by Karskaya** [comment]
@helfi92 This approach works perfectly! Thank you so much!
