### ISSUE TITLE
[UI] Remove defaultTabIndex warning in console

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1408]
**Reserved** for [outreachy](https://www.outreachy.org/) candidates. In order for this to be assigned to you, make sure to complete the first step of the application process outlined in the [project description](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/#build-a-component-that-can-display-a-json-schema).

---

**Describe the bug**
Clicking the "Preview" button in the MarkdownTextArea component throws an error in the console.

**To Reproduce**
1. Go to http://localhost:5080/hooks/garbage/abc456
2. Click the "PREVIEW" tab of the description box
3. Open the developer dev-tools and see error

![Screen Shot 2019-09-30 at 9 51 08 AM](https://user-images.githubusercontent.com/3766511/65885095-fd297500-e367-11e9-815b-09cb7ebd281f.png)

**Expected behavior**
This error does not show up.

**Additional context**
The fix for this will probably be in https://github.com/mozilla-frontend-infra/components/blob/b40349a6c398bb960ac7303f75043073340f7545/src/components/MarkdownTextArea/index.jsx#L109.

**Comment by vishakhanihore** [comment]
I want to work on it , Please assign me the following

**Comment by Rolikasi** [comment]
Hey, @helfi92 . For this issue do we need to clone https://github.com/mozilla-frontend-infra/components repo then change component and PR on that repo?
How can I see if error doesn't showing up after my fix?

**Comment by djmitche** [comment]
We want to make sure everyone gets a chance to work on an issue, and we don't have too many!  So let's save this for another applicant.  You can take a look at the other issues, not labeled "outreachy", and find one that looks good.  Those are likely to be a bit more challenging.

Let's see what @helfi92 says about the PR -- I suspect, especially given the red X's, that it's not the full solution.  But another applicant can pick up the issue and work on it, since @Rolikasi and @vishakhanihore already have other PRs up for review.  It's important that everyone is considerate of other applicants!

**Comment by ajinkabeer** [comment]
Can I work on this issue please? @djmitche

**Comment by djmitche** [comment]
Sure, have a look!

**Comment by ajinkabeer** [comment]
I was able to see the warning on my localhost. My question is should I fork and clone the repository that you mentioned in the context and then make a pull request ? 
Thanks
@helfi92 @djmitche

**Comment by vishakhanihore** [comment]
Yes,you need fork and clone to make a PR.

**Comment by ajinkabeer** [comment]
I have fixed the issue and have made a pull request. Can you please take a look ? @djmitche @helfi92 
#51 [UI] Remove defaultTabIndex warning in console #50

**Comment by ajinkabeer** [comment]
I think I have fixed the issue and have made a pull request. Can you please take a look ? @djmitche @helfi92

mozilla-frontend-infra/components#51

**Comment by ajinkabeer** [comment]
All checks have been passed. Can you take a look please ? @djmitche

**Comment by helfi92** [comment]
Resolved in https://github.com/mozilla-frontend-infra/components/pull/52.
