### ISSUE TITLE
[UI] Add tooltip to button icon

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1409]
**Reserved** for [outreachy](https://www.outreachy.org/) candidates. In order for this to be assigned to you, make sure to complete the first step of the application process outlined in the [project description](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/#build-a-component-that-can-display-a-json-schema).

---

**Describe the bug**
When a user hovers on a round button, we should show a tooltip with a label describing the action.

**To Reproduce**
1. Go to http://localhost:5080/hooks/garbage/abc456
2. Add a random schedule then click the plus icon

![Screen Shot 2019-09-30 at 10 06 45 AM](https://user-images.githubusercontent.com/3766511/65886291-0b789080-e36a-11e9-99dc-4842c547e00e.png)

3. Hover on the plus icon beside "Schedule" and the garbage icon below it.

**Expected behavior**
A tooltip with label "Add Schedule" on the plus icon and "Delete Schedule" on the garbage icon shows up when the user hovers on them. The implementation should be similar to the bindings sections below it:

![Screen Shot 2019-09-30 at 10 07 48 AM](https://user-images.githubusercontent.com/3766511/65886349-2d721300-e36a-11e9-9b12-91de912ac844.png)
![Screen Shot 2019-09-30 at 10 07 42 AM](https://user-images.githubusercontent.com/3766511/65886350-2d721300-e36a-11e9-8d70-0eb49ab70ada.png)

**Comment by bini11** [comment]
Hey @helfi92 I'm an outreachy applicant and have completed the first step & would like to work on this bug.

**Comment by devnoorfatima** [comment]
I want to work on this issue.

**Comment by Aishat-Akinyemi** [comment]
Hello @helfi92 I am an outreachy applicant, I  I want to contribute to "Improve Firefox Containers Add-ons" project. Can I choose any of the bugs on this link   
[https://codetribute.mozilla.org/languages/javascript?tag%3Doutreachy](url)    thank you!

**Comment by djmitche** [comment]
@bini11 all yours.  I'll assign this to you once you accept the invite.

@Aishat-Akinyemi you will want to look for issues in the mozilla/contain-facebook and mozilla/multi-account-containers GitHub repositories.  These issue are for another Outreachy project.  Sorry!

**Comment by shilpiverma509** [comment]
@djmitche  Can I work on this issue if this is still to be done? I have already worked this out on my local branch. However, I am unable to push as it gives me an error :ERROR: Permission to taskcluster/taskcluster.git denied to shilpiverma509.

**Comment by bini11** [comment]
@shilpiverma509 I have already added tooltips and submitted Pull request for this issue
 which is currently waiting for a review.

**Comment by djmitche** [comment]
Sorry @shilpiverma509 !  But, you can help out by having a look at @bini11's PR (#1471) and commenting on it.
