### ISSUE TITLE
[UI] Improve layout of worker pool view

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1413]
**Reserved** for [outreachy](https://www.outreachy.org/) candidates. In order for this to be assigned to you, make sure to complete the first step of the application process outlined in the [project description](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/#build-a-component-that-can-display-a-json-schema).

---

**Describe the bug**
In an effort to [improve the layout of our forms](https://github.com/taskcluster/taskcluster/issues/835), let's have the worker pool take in some of the [changes that were recently applied to the hook view](https://github.com/taskcluster/taskcluster/pull/1410#issue-322846137). Some of the changes that could be beneficial to this view:

* Reduce the spacing between the owner's email and the switch

![Screen Shot 2019-09-30 at 1 40 32 PM](https://user-images.githubusercontent.com/3766511/65902262-fe6a9a00-e387-11e9-9026-53936befedd9.png)

* Make spacing between each section similar to the one in the hooks view
* Make spacing between the section label and its content similar to the hook view. For example, we can reduce the following spacing between "Configuration" and the editor:

![Screen Shot 2019-09-30 at 1 43 28 PM](https://user-images.githubusercontent.com/3766511/65902414-60c39a80-e388-11e9-993a-383b8002571a.png)

**To Reproduce**
1. Go to https://taskcluster-ui.herokuapp.com/worker-manager/taskcluster-imaging%2Ftaskcluster-imaging-ci

That's it :)

**Expected behavior**
The overall layout is consistent with the hook view (e.g., https://taskcluster-ui.herokuapp.com/hooks/garbage/abc456)

**Comment by ANURADHAJHA99** [comment]
Kindly assign the following issue to me.

**Comment by djmitche** [comment]
We want to make sure everyone gets a chance to work on an issue, and we don't have too many!  So let's save this for another applicant.  You can take a look at the other issues, not labeled "outreachy", and find one that looks good.  Those are likely to be a bit more challenging.

**Comment by ANURADHAJHA99** [comment]
@djmitche I completely agree with you. Sure, I will find other issues and work on them. Thank you very much for the feedback.

**Comment by Henikilan** [comment]
@helfi92 @djmitche
I would like to work on this issue. Can you please assign it to me?

**Comment by djmitche** [comment]
Done!

**Comment by djmitche** [comment]
@Henikilan are you still working on this?

**Comment by Henikilan** [comment]
@djmitche 
Finished 3 days ago, there is a pull request for this one [here](https://github.com/taskcluster/taskcluster/pull/1470)

**Comment by djmitche** [comment]
Oh, sorry, I somehow missed the reference to that pull request right above my comment!
