### ISSUE TITLE
[UI] Search placeholder

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1416]
**Reserved** for [outreachy](https://www.outreachy.org/) candidates. In order for this to be assigned to you, make sure to complete the first step of the application process outlined in the [project description](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/#build-a-component-that-can-display-a-json-schema).

---

**To Reproduce**
1. Go to https://taskcluster-ui.herokuapp.com/tasks
2. Look at the search component

<img width="251" alt="Screen Shot 2019-09-30 at 4 45 55 PM" src="https://user-images.githubusercontent.com/3766511/65915617-cbcd9b00-e3a1-11e9-92e7-c3427a222027.png">

**Expected behavior**
A placeholder that tells the user what they should search for. For example, in https://taskcluster-ui.herokuapp.com/tasks, it should say "Search Task ID" instead of "Search". The change should be done to the following views:

https://taskcluster-ui.herokuapp.com/tasks -> Search Task ID
https://taskcluster-ui.herokuapp.com/tasks/SRPZN658R-y9nFjCq1TAKA -> Search Task ID
https://taskcluster-ui.herokuapp.com/tasks/groups -> Search Task Group ID
https://taskcluster-ui.herokuapp.com/tasks/groups/Sc6I-RrRR2ejlKVk0Z44TQ -> Search Task Group ID

**Comment by Soundharyaam** [comment]
Hi, I would like to contribute to this issue for outreachy project. Could you please assign it to me?

**Comment by djmitche** [comment]
done!

**Comment by somchi** [comment]
Hi, i have complete the first step to make contribution and i will like to make contribution to this issue.

**Comment by shilpiverma509** [comment]
Hi @djmitche I would like to work on this issue

**Comment by djmitche** [comment]
Hi folks - note that this is already assigned to someone :)

Unfortunately we always get a *lot* of contributors, and it's difficult to think of enough good first tasks for all of them!  Likely some folks will "disappear" and we can reassign those issues.  Note that you can also find a larger set of bugs to work on in https://codetribute.mozilla.org/projects/taskcluster.  Not all of them are quite as "quick" as those tagged "outreachy", but perhaps you'll find something there that sparks your interest.
