### ISSUE TITLE
[UI] Add helper text to scopes text field

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1417]
**Reserved** for [outreachy](https://www.outreachy.org/) candidates. In order for this to be assigned to you, make sure to complete the first step of the application process outlined in the [project description](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/#build-a-component-that-can-display-a-json-schema).

---

**Describe the bug**
The scopes text field should let the users know that they should enter scopes in new lines.

**To Reproduce**
1. Go to https://taskcluster-ui.herokuapp.com/auth/roles/hook-id%3Agarbage%2Fcron-task-johanlorenzo-android-components%2Fsnapshot
2. Look for the scopes text field

<img width="1548" alt="Screen Shot 2019-09-30 at 4 54 17 PM" src="https://user-images.githubusercontent.com/3766511/65916235-fb30d780-e3a2-11e9-9e0e-ef4284bea76a.png">

**Expected behavior**

It should say "Enter each scope on its own line", similar to how it's done in https://taskcluster-ui.herokuapp.com/auth/clients/email%2Fbastien%40nextcairn.com%2Ftc-notify-test

<img width="1541" alt="Screen Shot 2019-09-30 at 4 56 07 PM" src="https://user-images.githubusercontent.com/3766511/65916379-37643800-e3a3-11e9-8aac-49e55bf0fbc0.png">

**Comment by ANURADHAJHA99** [comment]
I have completed the first part of the application. KIndly assign the following issue to me.

**Comment by ANURADHAJHA99** [comment]
I have already made the pull request. The link to my pull request is https://github.com/taskcluster/taskcluster/pull/1446
