### ISSUE TITLE
[UI] Add tooltip to link

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1420]
**Reserved** for [outreachy](https://www.outreachy.org/) candidates. In order for this to be assigned to you, make sure to complete the first step of the application process outlined in the [project description](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/#build-a-component-that-can-display-a-json-schema).

---

**To Reproduce**
1. Go to https://taskcluster-ui.herokuapp.com/tasks/JH1bEpjqRTi_AhcpulPnxQ
2. Click on "More..." on the left panel
3. Hover your mouse over "Source"

<img width="783" alt="Screen Shot 2019-09-30 at 5 30 39 PM" src="https://user-images.githubusercontent.com/3766511/65918605-09352700-e3a8-11e9-97ac-5407e2793534.png">

**Expected behavior**
A tooltip shows up with the full url.

**Additional context**
The tooltip can be added using the `title=""` prop. https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title

**Comment by vishakhanihore** [comment]
@helfi92 Hello Hassan, I am Vishakha, an outreachy applicant. I would love to be a part of this project.
Regarding the first step, I have completed it. Please see the following attached Screenshots: 
<img width="1440" alt="Screenshot 2019-10-02 at 5 18 45 AM" src="https://user-images.githubusercontent.com/54327666/66008459-26ffaa80-e4d4-11e9-9136-4e25b3398c00.png">
<img width="713" alt="Screenshot 2019-10-02 at 5 18 57 AM" src="https://user-images.githubusercontent.com/54327666/66008462-2ebf4f00-e4d4-11e9-9d92-8f35d6169e4b.png">

**Comment by devnoorfatima** [comment]
Hi! @helfi92  .I have sent the email of the screenshots which have been checked by @djmitche. I also have sent the username of github which I was being asked. I want to work on this issue as my first contribution.

**Comment by djmitche** [comment]
Sounds good, it's all yours!

**Comment by devnoorfatima** [comment]
![1](https://user-images.githubusercontent.com/44938970/66063727-6b835880-e55d-11e9-9467-36d7e04bf3fe.png)
I get this error as I add the id in search bar and press enter

**Comment by djmitche** [comment]
Do you see anything in the console where you are running `yarn start`?  That usually happens when something returns an error message instead of JSON (since "Error" starts with "E").  You can also look in the browser's network inspector to see what the response body is -- you can probably see the whole error message there, and that might help to debug what's wrong.

**Comment by devnoorfatima** [comment]
![2](https://user-images.githubusercontent.com/44938970/66064794-88b92680-e55f-11e9-8a0b-73d4ef8e2985.png)
This is what I am getting in the console

**Comment by djmitche** [comment]
Are both the `ui/` and `services/web-server` running?

**Comment by devnoorfatima** [comment]
![3](https://user-images.githubusercontent.com/44938970/66064865-b0a88a00-e55f-11e9-938a-3ec18398f9d1.png)
this is the terminal

**Comment by djmitche** [comment]
Ah, looks like the web-server process isn't running.

**Comment by devnoorfatima** [comment]
![10](https://user-images.githubusercontent.com/44938970/66065247-6d025000-e560-11e9-9710-1e1e9e3ce041.png)
when I go to ui/ and give this command yarn start I get this error

**Comment by devnoorfatima** [comment]
It worked out. The website and the page is showing up now thanks a lot

**Comment by devnoorfatima** [comment]
https://github.com/taskcluster/taskcluster/pull/1456
the pull request for this issue
