### ISSUE TITLE
[UI] Add hover effect to the link icon in /auth/clients and /auth/roles

### ISSUE THREAD

**Issue by Rolikasi** [taskcluster/taskcluster#1448]
The same issue as #1403 

**Describe the bug**
The hover effect on list items is missing for the list of scopes.

**To Reproduce**
1. Go to http://localhost:5080/auth/roles
and http://localhost:5080/auth/clients
2. Hover mouse on an item from the list

**Expected behavior**
Hovering adds an effect on the icon.

Actual:

![Screen Shot 2019-09-26 at 4 03 01 PM](https://user-images.githubusercontent.com/3766511/65720988-264fba00-e077-11e9-8144-73d1a849131d.png)
 
 ![Screen Shot 2019-09-26 at 4 03 05 PM](https://user-images.githubusercontent.com/3766511/65720989-26e85080-e077-11e9-8a1d-fa8c995cddf2.png)
 
Expected:
 
![Screen Shot 2019-09-26 at 4 02 17 PM](https://user-images.githubusercontent.com/3766511/65720953-0d470900-e077-11e9-9ac8-30b664ca0c7d.png)

![Screen Shot 2019-09-26 at 4 02 22 PM](https://user-images.githubusercontent.com/3766511/65720952-0cae7280-e077-11e9-81a0-66f857e6e4da.png)

**Comment by Rolikasi** [comment]
@helfi92 @djmitche, I just found this similar to #1403 issue
Can you assign it to me

**Comment by djmitche** [comment]
We want to make sure everyone gets a chance to work on an issue, and we don't have too many!  I see this has a PR already, meaning another applicant doesn't get a chance.  You can take a look at the other issues, not labeled "outreachy", and find one that looks good.  Those are likely to be a bit more challenging.
