### ISSUE TITLE
Remove redundancy in index JSON schemas

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#1452]
`services/index/schemas/v1/list-tasks-response.yml` contains a subschema that is identical to `services/index/schemas/v1/indexed-task-response.yml`.  Use `$ref` to eliminate the duplication by referring from the former to the latter.  Let's also change the name of the latter from "indexed task response" to just "indexed task".

**Comment by Rolikasi** [comment]
Cool! I will work on this issue! 
I'll update you with my progress tomorrow
Thanks!

**Comment by Rolikasi** [comment]
@djmitche , do I need to use something like this:
items: {$ref: "schemas/v1/indexed-task-response.yml" }
or just
items: {$ref: "indexed-task-response.yml" } 
in line 13?

**Comment by djmitche** [comment]
The value of the $ref property is a relative URI (just like `href=..` in HTML), so the second form is correct.  Note, though, that schema ID's end with `.json#`, rather than `.yml`.

**Comment by Rolikasi** [comment]
Thank you! 1 more question before a PR:
Did you mean by "change the name" the title inside indexed-task-response.yml
or to change the indexed-task-response.yml to indexed-task.yml?

**Comment by djmitche** [comment]
both :)

**Comment by helfi92** [comment]
It looks like we aren't doing this anymore? Feel free to re-open if this still needs to be done.
