### ISSUE TITLE
Role editor should show description in markdown

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#1459]
**Describe the bug**
The role editor should show the description in rendered Markdown

**To Reproduce**
1. Go to any role
1. See the description as a text-entry box, rather than as rendered markdown (so for example `*foo*` instead of *foo*).

**Expected behavior**
A tabbed view showing both a preview and a place to write the description, similar to how hooks are displayed.  See https://taskcluster-ui.herokuapp.com/hooks/hg-push/try for example.

**Screenshots**
![Screenshot_2019-10-02 Hook - Taskcluster](https://user-images.githubusercontent.com/28673/66076586-2561d100-e52c-11e9-8e6f-2f65e1815bb3.png)
![Screenshot_2019-10-02 Role - Taskcluster](https://user-images.githubusercontent.com/28673/66076587-2561d100-e52c-11e9-8285-dcba89f91ee9.png)

**Comment by Rolikasi** [comment]
Do we also need to switch text-entry box to a rendered Markdown in https://taskcluster-ui.herokuapp.com/quickstart in description field or not?

**Comment by djmitche** [comment]
That particular example is OK because the description is always empty when that page loads.  But it may make sense for other views!

**Comment by JiwoonKim** [comment]
Hi! I just sent a screenshot regarding the first step for the Outreachy program. 
May I take this issue?

**Comment by FahdJamy** [comment]
Sent in the screenshot yesterday. Can I take on this Issue?

**Comment by somchi** [comment]
I did like to work on this issues

**Comment by echessa** [comment]
Hi @djmitche if no one get's assigned this, I'd like to take it on.

**Comment by sccofield** [comment]
hi @djmitche, can I work on this issue, I am one of the outreachy interns.

**Comment by djmitche** [comment]
Hi folks -- I'm sorry it's so busy here (it's not usually the case!).  First to ask was @JiwoonKim.

**Comment by djmitche** [comment]
I'm sorry things are so busy these days!  Unfortunately we always get a *lot* of contributors, and it's difficult to think of enough good first tasks for all of them!  Likely some folks will "disappear" and we can reassign those issues.  Note that you can also find a larger set of bugs to work on in https://codetribute.mozilla.org/projects/taskcluster.  Not all of them are quite as "quick" as those tagged "outreachy", but perhaps you'll find something there that sparks your interest.

**Comment by JiwoonKim** [comment]
@djmitche thanks!
