### ISSUE TITLE
Client editor should show description in markdown

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#1460]
**Describe the bug**
The client editor should show the description in rendered Markdown

**To Reproduce**
1. Go to a client like https://taskcluster-ui.herokuapp.com/auth/clients/static%2Ftaskcluster%2Froot
1. See the description as a text-entry box, rather than as rendered markdown (so for example `*foo*` instead of *foo*).

**Expected behavior**
A tabbed view showing both a preview and a place to write the description, similar to how hooks are displayed.  See https://taskcluster-ui.herokuapp.com/hooks/hg-push/try for example.

**Screenshots**
![Screenshot_2019-10-02 Client - Taskcluster](https://user-images.githubusercontent.com/28673/66076723-69ed6c80-e52c-11e9-8d04-ada35c1e7b1f.png)
![Screenshot_2019-10-02 Hook - Taskcluster](https://user-images.githubusercontent.com/28673/66076724-69ed6c80-e52c-11e9-86c8-c12cd630e5c2.png)

**Comment by vishakhanihore** [comment]
Can I be assigned this ?

**Comment by djmitche** [comment]
We want to make sure everyone gets a chance to work on an issue, and we don't have too many!  So let's save this for another applicant.  You can take a look at the other issues, not labeled "outreachy", and find one that looks good.  Those are likely to be a bit more challenging.

**Comment by LeoSilvaGomes** [comment]
Can I try to fix this issue?

**Comment by FahdJamy** [comment]
@LeoSilvaGomes are you going to take on this one??

**Comment by FahdJamy** [comment]
Hey @LeoSilvaGomes are you going to take on this or should I take it on?
I completed the first step for submitting a screenshot.

**Comment by somchi** [comment]
i did like to fix this issue

**Comment by echessa** [comment]
Hi @djmitche if no one who has responded before me get's assigned, than I'd like to take this issue.

**Comment by djmitche** [comment]
@LeoSilvaGomes is the first to ask after @vishakhanihore.

I'm sorry things are so busy these days!  Unfortunately we always get a *lot* of contributors, and it's difficult to think of enough good first tasks for all of them!  Likely some folks will "disappear" and we can reassign those issues.  Note that you can also find a larger set of bugs to work on in https://codetribute.mozilla.org/projects/taskcluster.  Not all of them are quite as "quick" as those tagged "outreachy", but perhaps you'll find something there that sparks your interest.

**Comment by olsenme** [comment]
Has this issue been assigned?

**Comment by FahdJamy** [comment]
Yes @olsenme, the Task was assigned to **Leo**.

**Comment by chefoce** [comment]
Hi, I would like to contribute to this issue for outreachy project. Could you please assign it to me?

**Comment by djmitche** [comment]
Oops, sorry, I meant to assign to @LeoSilvaGomes when I commented about 24h ago, and they have filed a PR for the issue.

**Comment by djmitche** [comment]
We have had an overwhelming response to this Outreachy round and the good getting-started issues we have accumulated are mostly assigned to other applicants already.  There are a few things you can do:
 * look for other good-first-bugs (not labeled "outreachy") in this issue tracker or in https://codetribute.mozilla.org/projects/taskcluster, noting that some of the bugs there are quite a bit harder
 * wait several days and check back on these issues - applicants are often working on several projects and may "forget" that they have claimed this issue as they get involved working on another.
 * experiment with the UI at https://taskcluster-ui.herokuapp.com/ and try to spot other small "polish" issues that you could fix.  For such a fix, it's OK to just file a PR with the fix and some screenshots describing what you changed, without first filing an issue.

**Comment by helfi92** [comment]
Resolved in https://github.com/taskcluster/taskcluster/commit/34a586f8270a9c9b96d36ad85b48063311d86269.
