### ISSUE TITLE
[UI] Focus on tab is broken in Create Worker Pool form

### ISSUE THREAD

**Issue by owlishDeveloper** [taskcluster/taskcluster#1487]
**Please do not work on this issue without asking and being assigned first! If you already have some issues assigned to you, please wait until your PR is merged before asking for a new one! Thank you!**

When filling out the form to create a workerpool, you can't move the focus from the last field of the form (the code editor) to Save button with the Tab key.

**To Reproduce**
1. Go to Worker Manager
2. Click on Create
3. Once the form opens, you will see the focus (the cursor) in the Workerpool ID field. Press the Tab key on the keyboard to move the cursor around.
4. Once the cursor in the Configuration field (the code editor) observe it not moving anymore.

**Expected behavior**
Upon pressing the Tab key, the focus goes from Configuration field to the Save button; upon the next pressing the Tab key, the focus (cursor) should go to the first field (Workerpool ID).

**Platform (please complete the following information):**
 - OS: OS X
 - Browser Firefox

**Comment by vishakhanihore** [comment]
@owlishDeveloper Please can you assign me this issue

**Comment by JiwoonKim** [comment]
Hi! I am an Outreachy Applicant and have been invited! Can I take this issue?

**Comment by djmitche** [comment]
We want to make sure everyone gets a chance to work on an issue, and we don't have too many!  So let's save this for another applicant.  You can take a look at the other issues, not labeled "outreachy", and find one that looks good.  Those are likely to be a bit more challenging.

**Comment by devnoorfatima** [comment]
Can I work on this issue.

**Comment by djmitche** [comment]
Sure!

**Comment by devnoorfatima** [comment]
When I click on create it says Auth required ?

**Comment by djmitche** [comment]
That's OK -- you don't need to actually create a worker pool here, just make sure the focus works (which, if hitting "tab" and "enter" shows that error, it does).

**Comment by devnoorfatima** [comment]
But the save button is disabled, so would i be able to see the results.

**Comment by djmitche** [comment]
Ah, good point.  If you click the "sign in" in the upper right and put nonsense in for the clientId and accessToken, it will enable that button.

**Comment by devnoorfatima** [comment]
I understood this issue [UI] Focus on tab is broken in Create Worker Pool
form #1487 but I am not getting that one point to work on.Can you help me a
bit.

**Comment by djmitche** [comment]
I'm not sure what the question is there.  My comment yesterday shows how you can enable the "create" button.  It will still give an error instead of actually creating a worker-pool, but that's good -- we don't want to actually create any worker pools! And the important thing is that "tab" works.

**Comment by devnoorfatima** [comment]
I tried the tabIndex it does not make it work also I tried doing it by making a function and putting an eventlistener but still it does not work.Can you please help me out a bit.

**Comment by devnoorfatima** [comment]
I declared a variable options and gave it the value ` extraKeys: {Tab: false,},` and mentioned it in the code editor tag like `options={options}` .
But it does nothing, I am certainly doing something wrong but can't figure out what.

**Comment by JiwoonKim** [comment]
@djmitche I've completed the issues assigned to me at the moment. Would like to work on this issue if @devnoorfatima is okay?

**Comment by djmitche** [comment]
I'll defer to @helfi92 for assigning issues.

**Comment by helfi92** [comment]
@devnoorfatima Are you still working on adding the change to https://github.com/mozilla-frontend-infra/components or did you want me to assign the issue to someone else? Let me know if you had questions.

**Comment by devnoorfatima** [comment]
I have made the changes I will now make the PR to get reviewed.

**Comment by devnoorfatima** [comment]
I made a PR here:
https://github.com/mozilla-frontend-infra/components/pull/65

**Comment by helfi92** [comment]
Fixed in https://github.com/taskcluster/taskcluster/commit/059a772d268775b9b0c86d9f69a582f0a16316aa.
