### ISSUE TITLE
[UI] Focus on tab is broken in Create Hook form

### ISSUE THREAD

**Issue by owlishDeveloper** [taskcluster/taskcluster#1488]
**Please do not work on this issue without asking and being assigned first! If you already have some issues assigned to you, please wait until your PR is merged before asking for a new one! Thank you!**

When filling out the form to create a hook, you can't move the focus from the last field of the form (the code editor) to Save button with the Tab key.

**To Reproduce**
1. Go to Hooks
2. Click on Create
3. Once the form opens, you will see the focus (the cursor) in the first field. Press the Tab key on the keyboard to move the cursor around.
4. Once the cursor in the Task Template field (the code editor) observe that pressing the Tab key adds tabulation to the form instead of moving around

**Expected behavior**
Upon pressing the Tab key, the focus goes from Task Template field to the Trigger Schema field; upon the next pressing the Tab key, the focus (cursor) should go to the Save Button; upon the next pressing the Tab key, the focus (cursor) should make the full circle and return to the first field.

**Platform (please complete the following information):**
 - OS: OS X
 - Browser Firefox

**Comment by Rolikasi** [comment]
Hello @owlishDeveloper, I'm assigned to some issues and made PRs to all of them, but mentor will check them only next week. Can I take this issue to work on?

**Comment by djmitche** [comment]
Hi @Rolikasi -- we still have lots of other applicants looking for their first contributions, and you have made a lot of good contributions already.  Good next steps for you would be to find some more-difficult tasks to work on, or to start in on writing your application.  Thanks!

**Comment by shilpiverma509** [comment]
Hi @djmitche @owlishDeveloper  Can I take this issue to work on?

**Comment by JiwoonKim** [comment]
Hi! I am an Outreachy Applicant and have been invited! Can I take this issue?

**Comment by djmitche** [comment]
Sure @, this will make a good first contirbution.

**Comment by shilpiverma509** [comment]
Can we use tabIndex attribute here if I am understanding correctly.

**Comment by shilpiverma509** [comment]
@djmitche  @JiwoonKim any guidance here?

**Comment by djmitche** [comment]
It sounds like you have the right idea.. try it out and see if it works?

**Comment by shilpiverma509** [comment]
@djmitche I tried doing with tabIndex={-1} on the CodeEditor. This didn't work out.

**Comment by djmitche** [comment]
We might have to wait for @helfi92 to return next week, then.  I'm not an expert on the topic.  Feel free to keep trying to figure it out, though!

**Comment by shilpiverma509** [comment]
@djmitche Sure I am trying out here. Meanwhile can I also work on some other unassigned issue?

**Comment by djmitche** [comment]
Let's see if @SirPhemmiey is still working on #1391, and if not you can take it.

**Comment by SirPhemmiey** [comment]
I didn't find my way around it. Another person can take it.

**Comment by devnoorfatima** [comment]
@djmitche I am working on issue #1487 which is similar to this one and i'm finding my way around so can I take this one too.

**Comment by shilpiverma509** [comment]
@devnoorfatima  I was working on it, However, I am blocked here and still trying out. If you have already figured out the solution you can take it and I will check your PR for your solution. I think we can learn from each other.

**Comment by SirPhemmiey** [comment]
@shilpiverma509, that's good of you. @devnoorfatima, we can learn from each other.

**Comment by devnoorfatima** [comment]
Yes sure why not I'll let you know as soon as I get the solution. I am working on it but nothing seems to be working. After all learning is what matters the most.

**Comment by devnoorfatima** [comment]
Oh I am sorry I just read your comment that you've asked for this issue already. I would never have asked for it if I knew it earlier.

**Comment by devnoorfatima** [comment]
Oh I am sorry @shilpiverma509 I thought it's you who said that "another person can take this issue" it was a misunderstanding ,I thought you are talking about this issue.Now I read the comments and get to know that two persons are talking about two issues.Sorry this issue is yours.

**Comment by shilpiverma509** [comment]
@devnoorfatima  No issues. Thankyou. Lets try figuring out the way @helfi92 has suggested.

**Comment by shilpiverma509** [comment]
@helfi92  I was trying to pass an options object as props in CodeEditor. Well this didn;t work and I am unable to understand how to map the tab key here
`const options = {extraKeys:{
      Tab:false,
      Shift:false,
      indentWithTabs:false,
      "Shift-Tab": false
  }};
and pass it under CodeEditor like :
       <CodeEditor
                    lint
                    value={taskInput}
                    onChange={this.handleTaskChange}
                    options={options.extraKeys}
                  />
`
I am not sure how to handle this. From my understanding we need to pass the extrakeys object in the options props of CodeEditor.

**Comment by helfi92** [comment]
Have you tried something like:

```jsx
options={{
  extraKeys: {
    Tab: false,
  }
}}
```

**Comment by devnoorfatima** [comment]
`const options = {
      extraKeys: {
        Tab: false,
      },
    };`
I have written it like this.Also I tried what you suggested but the double brackets are showing error in the code editor.

**Comment by helfi92** [comment]
```jsx
<CodeEditor options={{ extraKeys: { Tab: false } }} ... />
```

or

```jsx
const options = { extraKeys: { Tab: false } };

<CodeEditor options={options} ... />
```

**Comment by devnoorfatima** [comment]
I am doing it in the exact same way. The Tab key is disabled in the code editor but the focus does not transfer to the save button.

**Comment by helfi92** [comment]
The focus will not transfer to the save button if the button is disabled (i.e., cannot be clicked). Depending on the view, we sometimes disable a button when the user is not logged in or if there are no changes to be saved.

**Comment by shilpiverma509** [comment]
@helfi92 I was out for the weekend. Let me try with the way you suggested above

**Comment by shilpiverma509** [comment]
@helfi92  Well this still doesn't work for me. Pressing the Tab key  still adds tabulation/indentation to the form.  @devnoorfatima were you able to work your way out here? 
Also I am getting this in my console. Not sure what's wrong here.
[HPM] Error occurred while trying to proxy request /graphql from localhost:5080 to http://localhost:3050 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

**Comment by helfi92** [comment]
Fixed in https://github.com/taskcluster/taskcluster/commit/059a772d268775b9b0c86d9f69a582f0a16316aa.
