### ISSUE TITLE
client-go requires an invalid pseudo-version of streadway/amqp

### ISSUE THREAD

**Issue by Hexcles** [taskcluster/taskcluster#1492]
**Describe the bug**

In module-aware mode, `go get` complains about an invalid pseudo-version.

**To Reproduce**
1. Create a new go module that requires clients-go (`github.com/taskcluster/taskcluster/clients/client-go/v18 v18.0.3`).
2. Run `go get`.
3. See error:
```
go: github.com/taskcluster/taskcluster/clients/client-go/v18@v18.0.3 requires
        github.com/streadway/amqp@v0.0.0-20190827080102-edfb9018d271: invalid pseudo-version: does not match version-control timestamp (2019-08-27T07:21:41Z)
```

**Expected behavior**
No error produced

**Platform (please complete the following information):**
 - OS: Linux
 - Go: 1.13

**Additional context**
I only started using Go modules recently so maybe I'm doing something wrong...

**Comment by djmitche** [comment]
I think Renovate is actually the thing doing something wrong here :(

**Comment by djmitche** [comment]
Same issue in https://github.com/taskcluster/taskcluster-worker-runner/pull/47.  What I don't get is, things work fine running e.g., `go test ./...` in `clients/client-go`.  And the day is right, it just seems the time is a little off.  **weird**

I think go modules has some growing to do.. I'm hoping it's less buggy in go1.13!

**Comment by Hexcles** [comment]
Timezones? I didn't read too much about pseudo versions. Does it assume UTC?

---

**Comment by djmitche** [comment]
The minutes differ, and not by a multiple of 30.  Dunno..

**Comment by djmitche** [comment]
https://github.com/taskcluster/taskcluster-worker-runner/pull/48 suggests this is also true for `golang.org/x/tools@v0.0.0-20190722020823-e377ae9d6386`.  I will see if I can reproduce this reliably and shake out *all* of the fallout.

**Comment by djmitche** [comment]
It looks like this is a go1.13 problem?  There's lots of [workarounds for the issue in go1.13](https://tip.golang.org/doc/go1.13#version-validation) but no explanation of why this occurs.

> `replace github.com/docker/docker v1.14.0-0.20190319215453-e7b5f7dbe98c => github.com/docker/docker e7b5f7dbe98c`
> 
> currently resolves to
> 
> `replace github.com/docker/docker v1.14.0-0.20190319215453-e7b5f7dbe98c => github.com/docker/docker v0.7.3-0.20190319215453-e7b5f7dbe98c`

Wait, *currently*?  So, this might resolve to something else some other time?  Doesn't that defeat the whole purpose?  WAT?

**Comment by djmitche** [comment]
Hm, but taskcluster-worker-runner is running go1.12.9.

**Comment by djmitche** [comment]
I can only reproduce this locally with go1.13, so I'm not sure what's up with taskcluster-worker-runner.

```
(go1.12.9) (v10.16.3) dustin@lamport ~/p/taskcluster/clients/client-go [HEAD detached at v19.0.0] $ gvm use go1.13.1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
Now using version go1.13.1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
(go1.13.1) (v10.16.3) dustin@lamport ~/p/taskcluster/clients/client-go [HEAD detached at v19.0.0] $ rm -rf $GOPATH && go list -m all                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
go: golang.org/x/tools@v0.0.0-20190722020823-e377ae9d6386: invalid pseudo-version: does not match version-control timestamp (2019-07-19T00:56:02Z)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
```

**Comment by djmitche** [comment]
..sometimes.  So this is intermittent.

**Comment by Hexcles** [comment]
Hopefully this is now fixed by Renovate: https://github.com/renovatebot/renovate/pull/4386 (they used to generate the pseudo version from a pattern string...)

**Comment by djmitche** [comment]
Indeed, I haven't seen this in some time.  I'll remove the check in an upcomging PR.
