### ISSUE TITLE
[UI] Helper Text in `Info Tab` of `Task Index` missing

### ISSUE THREAD

**Issue by vishakhanihore** [taskcluster/taskcluster#1527]
**Describe the bug**

Helper Text in `Info Tab` of `Task Index` missing

**To Reproduce**

1. Go to 'http://127.0.0.1:5080/tasks/index'
2. Click on 'Page Information'
3. See error

**Expected behavior**

Please add the `Page Information`

**Screenshots**

<img width="1139" alt="Screenshot 2019-10-08 at 1 32 34 PM" src="https://user-images.githubusercontent.com/54327666/66377912-1a95b900-e9d0-11e9-9ae5-e787fcd7a12d.png">

**Additional context**

I would like to work on it.

**Comment by vishakhanihore** [comment]
@djmitche Can I work on it or should it be for newcomers ?

**Comment by sccofield** [comment]
@djmitche can I work on this?

**Comment by Rolikasi** [comment]
Hi @vishakhanihore, it is the same issue as #1386. I've already made PR for that one
I think you can close this issue

**Comment by vishakhanihore** [comment]
> Hi @vishakhanihore, it is the same issue as #1386. I've already made PR for that one
> I think you can close this issue

Sure
