### ISSUE TITLE
[UI] Redirect third-party to login strategy directly when only 1 strategy

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1529]
**Describe the bug**
When a third party site tries to get taskcluster credentials, they first need to redirect their users to our site to login. They navigate their users to `/third-party?...`.

**To Reproduce**
1. The frontend reads configuraiton variables from relative URL `./static/env.js` on page load. This file is written during `yarn start`. Modify `UI_LOGIN_STRATEGY_NAMES` to contain only one strategy (e.g., `"UI_LOGIN_STRATEGY_NAMES": "mozilla-auth0",`) and save the file.
2. Go to http://localhost:5080/third-party?client_id=treeherder-1234&redirect_uri=http%3A%2F%2Flocalhost%3A5000&response_type=code&scope=assume%3Atest+hello&state=21&expires=2000+years while being logged out.

**Actual behavior**

For a third party to login, they need to click the "Sign in" button then click on "Sign in with Auth0"

![Screen Shot 2019-10-08 at 9 47 01 AM](https://user-images.githubusercontent.com/3766511/66401109-9b44bd00-e9b0-11e9-937a-48f641b2f112.png)

![Screen Shot 2019-10-08 at 9 54 23 AM](https://user-images.githubusercontent.com/3766511/66401731-a51af000-e9b1-11e9-9c83-7400868c3d4d.png)

**Expected behavior**
When
1. the user is logged out and
2. the url contains `/third-party` and
3. `window.env.UI_LOGIN_STRATEGY_NAMES` has only one login strategy

then redirect directly to that strategy without having the user click on "Sign in" and then clicking on the strategy to use for login.

**Additional context**
For more information on login strategies, refer to [login strategies](https://github.com/taskcluster/taskcluster/tree/master/ui#login-strategies).

**Comment by helfi92** [comment]
Hi @JiwoonKim. This issue was actually assigned before it got created for @naimiii while discussing on IRC. Sorry for that.

**Comment by helfi92** [comment]
From IRC:
> usercontent.irccloud-cdn.com/file/T0nD74P2/image.png

The error suggests that we must provide a rootUrl. To do that, you could do:

on linux:

```diff
export TASKCLUSTER_ROOT_URL=https://taskcluster.net
yarn start
```

or on windows (i think it's): 

```
set TASKCLUSTER_ROOT_URL=https://taskcluster.net
yarn start
```

**Comment by naimiii** [comment]
Thank you .

**Comment by helfi92** [comment]
No problem!

**Comment by naimiii** [comment]
![image](https://user-images.githubusercontent.com/28563415/66658527-18935a80-ec5b-11e9-9800-96e25a4bb840.png)
How do i fix it ? Please assist

**Comment by helfi92** [comment]
Debugging ideas:
* Make sure `ui/static/env.js` has `GRAPHQL_ENDPOINT` set to `/graphql` otherwise it won't work. If that doesn't work, can you post the content of that file, please?
* Make sure the web-server service is running. You'll know it's running if `http://localhost:3050/playground` shows a playground. If it's running, can you post a screenshot of it working, please?
* What happens when you run `git diff`. Can you paste the content here?

**Comment by naimiii** [comment]
1.
![image](https://user-images.githubusercontent.com/28563415/66679446-9f5e2c80-ec87-11e9-9b6d-c8ccfc7cc0ef.png)
2.
![image](https://user-images.githubusercontent.com/28563415/66679472-b0a73900-ec87-11e9-8425-575dc768b1d7.png)
3.Nothing happens when i run git diff 
![image](https://user-images.githubusercontent.com/28563415/66679597-04b21d80-ec88-11e9-8d6d-48cd7de57383.png)

**Comment by helfi92** [comment]
In the playground, what happens when you put the following in the query and then click the play button?

```graphql
query Sample {
  task(taskId: "eWxW0D38QgOv9WZNKgCgAg") {
    status {
      state
    }
    
    metadata {
      name
    }
  }
}
```

**Comment by naimiii** [comment]
![image](https://user-images.githubusercontent.com/28563415/66684708-1b5e7180-ec94-11e9-9f10-014e65ff45d5.png)

**Comment by helfi92** [comment]
The server is running properly. Is it possible you have a firewall running that is catching all of these routes? Have you tried restarting your computer and trying again?

/cc @djmitche in case you have other ideas.

**Comment by naimiii** [comment]
yes I tried restarting the computer and tried again but useless . :(

**Comment by naimiii** [comment]
@djmitche  kindly help me to figure out what' s wrong in it .

**Comment by naimiii** [comment]
@helfi92   I tried 'git diff' again and here is the output 
![image](https://user-images.githubusercontent.com/28563415/66753301-e24d1980-eeac-11e9-8e83-8cdbf92eb557.png)
please assist.

**Comment by helfi92** [comment]
You can undo the changes by running `git checkout .` 

`git diff` after that shouldn't show anything. Does that help?

**Comment by djmitche** [comment]
`Cannot GET /login/mozilla-auth0` is expected -- that's an Express-style error message, which shows that it's being proxied to the web-server service (the UI doesn't use Express), and indeed
```
(go1.12.9) (v10.16.3) dustin@lamport ~/p/taskcluster [master] $ curl http://localhost:5080/login/mozilla-auth0
Error occured while trying to proxy to: localhost:5080/login/mozilla-auth0(go1.12.9) (v10.16.3) dustin@lamport ~/p/taskcluster [master] $ curl http://localhost:3050/login/mozilla-auth0
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /login/mozilla-auth0</pre>
</body>
</html>
```
so in [this comment](https://github.com/taskcluster/taskcluster/issues/1529#issuecomment-541081743) I think you were just accessing an incorrect URL on the UI.  Try just accessing `http://localhost:5080` and it should work fine.

**Comment by naimiii** [comment]
@djmitche  Thank you for the response  :)  but i just accessing  http://localhost:5080   and still same problem .

**Comment by naimiii** [comment]
@helfi92  trying to solve it by using 'git diff' . I hope it helps .

**Comment by helfi92** [comment]
@naimiii What's the problem. What do you get when you try to access http://localhost:5080?

**Comment by naimiii** [comment]
@helfi92  when i try to access http://localhost:5080 then it shows like 
![image](https://user-images.githubusercontent.com/28563415/66855901-8f9f5a80-ef9d-11e9-80a2-bcf7d583a937.png)
Afterwords i try to 'signup with Auth0' then  this problem happens all the time . :(
![image](https://user-images.githubusercontent.com/28563415/66855995-b1004680-ef9d-11e9-840c-792f9cec1f7e.png)

**Comment by helfi92** [comment]
Are you able to access a page like http://localhost:5080/provisioners?

**Comment by naimiii** [comment]
@helfi92   it shows me like this  
![image](https://user-images.githubusercontent.com/28563415/66857810-7a2c2f80-efa1-11e9-9079-eaaa41d9ed12.png)

**Comment by naimiii** [comment]
@helfi92  let me check it :)

**Comment by naimiii** [comment]
@helfi92   Yeah i am able to access 
![image](https://user-images.githubusercontent.com/28563415/66859073-017aa280-efa4-11e9-8cc9-05d1556f2c21.png)

**Comment by helfi92** [comment]
From https://github.com/taskcluster/taskcluster/issues/1529#issuecomment-541222527, I see that your web-server is properly configured. It looks like the UI is not communicating with web-server effectively however. For some reason, the proxy is not working...

https://github.com/taskcluster/taskcluster/blob/dc700ea3b0690967fcf0af585d9b34cf60307a7d/ui/.neutrinorc.js#L52-L65

The only thing that comes to mind is that there's some kind of a firewall or something not allowing intercepting proxies...

**Comment by naimiii** [comment]
@helfi92  So how do i fixed it ? I checked all the firewall  working normally .  :(

**Comment by helfi92** [comment]
Oh, I thought you weren't able to access it. Never mind, the proxy works.

**Comment by helfi92** [comment]
Can you try on a different browser (e.g., Firefox)?  I wonder if there's an installed extension causing this to happen.

**Comment by naimiii** [comment]
@helfi92  yeah i can try it on Firefox :) yeah maybe installed extension causing it . I will try both :)

**Comment by naimiii** [comment]
I tried on both browsers  and it's useless . :( 
![image](https://user-images.githubusercontent.com/28563415/66865942-c3847b00-efb1-11e9-9a0e-97c2c8263cd9.png)
![image](https://user-images.githubusercontent.com/28563415/66866005-dd25c280-efb1-11e9-8fee-e391b3c29f37.png)

**Comment by helfi92** [comment]
OMG. Obviously it wouldn't work. It's because `strategies['mozilla-auth0']` is not defined! Actually, we don't need to set this up because the required task doesn't require the user to be logged in. We just need to make sure the redirect works even the redirect will show you a blank page. Does that help?

**Comment by naimiii** [comment]
@helfi92 ohky .No need of sorry  :) Let me try to   define strategies . And yeah i understand your point .

**Comment by naimiii** [comment]
@helfi92  kindly assign me another issue .. :(
