### ISSUE TITLE
[tc-client-web] Fix regression

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1536]
There may have been a regression introduced in https://github.com/taskcluster/taskcluster/issues/285. I noticed it while working on third party logins. `v8.1.1` should work.

**Comment by helfi92** [comment]
Blocks https://bugzilla.mozilla.org/show_bug.cgi?id=1587145.

**Comment by djmitche** [comment]
The last released version of this library was 19.0.0 ;)

**Comment by vishakhanihore** [comment]
@helfi92 @djmitche Do we need to upgrade the library and fix the regression for `tc-client-web` in the following issue ? If yes, Can I give it a shot?

**Comment by helfi92** [comment]
We need to fix the regression but it will be a bit more than just updating the version.

**Comment by vishakhanihore** [comment]
> We need to fix the regression but it will be a bit more than just updating the version.

@helfi92 Can you guide what else, I can give it a try IMO ?

**Comment by armenzg** [comment]
This is preventing us updating Treeherder to the latest version.
Can we back out the code that caused the regression?

**Comment by sarah-clements** [comment]
Any idea when you'll get to this? We're still on v8.1.1 :)

**Comment by djmitche** [comment]
Is there still an issue here?  Details are light and my memory, at least, has faded..

**Comment by sarah-clements** [comment]
hrm, I don't remember what this bug was for either. I tried installing v29.2.0 via yarn and I'm seeing a `ReferenceError: hawk is not defined` from
    `taskcluster index.js:1`

Wondering if that's a webpack/neutrino issue.

**Comment by helfi92** [comment]
I will look into that now.

**Comment by helfi92** [comment]
I believe that's a webpack issue. Created https://github.com/taskcluster/taskcluster/pull/2755 for the fix.

**Comment by helfi92** [comment]
The fix should be available in the next release of taskcluster `v29.3.0` (not yet released).

**Comment by sarah-clements** [comment]
> The fix should be available in the next release of taskcluster `v29.3.0` (not yet released).

Thanks! I was just gonna ask that :)

**Comment by djmitche** [comment]
v29.3.0 is long out, so I'll close this up :)
