### ISSUE TITLE
[UI] Remove warnings in console

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1545]
**Reserved** for [outreachy](https://www.outreachy.org/) candidates. In order for this to be assigned to you, make sure to complete the first step of the application process outlined in the [project description](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/#build-a-component-that-can-display-a-json-schema).

---

**To Reproduce**
1. Go to http://localhost:5080/tasks/MH_HRhwxRZ-3zk7AvF0_vQ
2. Open the developer tools

**Actual behavior**

There are a bunch of `Warning: validateDOMNesting(...):` warnings.

![Screen Shot 2019-10-09 at 10 45 14 AM](https://user-images.githubusercontent.com/3766511/66492149-f397bf80-ea81-11e9-8a52-c75c792585ca.png)

**Expected behavior**
`Warning: validateDOMNesting(...)` warnings are removed.

**Comment by ajinkabeer** [comment]
I managed to fix the warnings in the console. Please excuse the closed PR's because both were accidental. Can you take a look at #1553 please?
@helfi92

**Comment by helfi92** [comment]
Resolved in https://github.com/taskcluster/taskcluster/pull/1553.
