### ISSUE TITLE
[UI] no way to go back from a detail page

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#1558]
**Describe the bug**
When creating or editing a resource using a view for that specific resource, there is no clear way to get back to the list of resources

**To Reproduce**
1. Go to the clients view
1. Click "+"
1. Create a clientId with a name `<clientId>/testy`, substituting your signed-in clientId
1. Wonder how to get back to the list of clients (clicking back isn't an obvious choice since I just submitted a form, and sure enough it takes me back to the create-secret form)

This would be the same with secrets, hooks, worker pools, denylist entries, etc.

Note that reproducing this will require the scopes to create a resource, which is not easily arranged right now.  With https://github.com/mozilla/community-tc-config/issues/6 we can support this in the community-tc deployment.

**Expected behavior**
A simple way to get back the list of secrets.

**Comment by yellowwoods12** [comment]
@helfi92 @djmitche should I give this a shot?

**Comment by djmitche** [comment]
I'd like to hear from @helfi92 if and how this should be solved.

**Comment by helfi92** [comment]
To resolve this issue, we can avoid pushing state to the history when saving a client since we are not really changing views internally. We can use the replace state behavior instead. In other words, we should use `history.replace` instead of `history.push`.

**Comment by djmitche** [comment]
So "back" from the created secret would take me to the secrets list?  That works for me..

**Comment by helfi92** [comment]
> Note that reproducing this will require the scopes to create a resource, which is not easily arranged right now. With mozilla/community-tc-config#6 we can support this in the community-tc deployment.

One easy way to test this without requiring scopes:

1. Navigate to http://localhost:5080/auth/clients
2. Click on any client
3. Login manually with any credentials
4. Change the description of the client 
5. Click save and wait until a red error banner shows up
6. Click the browser's back button

**Actual:** The user is not navigated to the list of clients.
**Expected:** The user is navigated to the list of clients.

**Comment by helfi92** [comment]
Are you still working on this issue @yellowwoods12? Let me know if you had questions :-)

**Comment by helfi92** [comment]
We've been having an overwhelming response to this Outreachy round. Seeing there hasn't been any activity in the past week I've re-assigned this issue to someone else. @yellowwoods12, if you are still interested in tackling an issue, there are a few things you can do:

* look for other good-first-bugs (not labeled "outreachy") in this issue tracker or in https://codetribute.mozilla.org/projects/taskcluster, noting that some of the bugs there are quite a bit harder
 * wait several days and check back on these issues - applicants are often working on several projects and may "forget" that they have claimed this issue as they get involved working on another.
 * experiment with the UI at https://taskcluster-ui.herokuapp.com/ and try to spot other small "polish" issues that you could fix.  For such a fix, it's OK to just file a PR with the fix and some screenshots describing what you changed, without first filing an issue.

**Comment by lailahgrant** [comment]
Sir, on this Taskcluster signIn, what do I enter? I really don’t have those credentials.

Sent from Mail for Windows 10

**Comment by helfi92** [comment]
Any credentials will do (e.g., `test` for clientID, `test` for access token).

**Comment by lailahgrant** [comment]
i created a back button and i would like to know if that is the right thing or not??

it doesn't have action yet though

import React, { Component } from 'react';

import ArrowBackIcon from '@material-ui/icons/ArrowBack';


export default class BackButton extends Component {
render() {
    return (
        <div>
            <ArrowBackIcon></ArrowBackIcon>
        </div>
    );
    }
}



this code is in src/components/button/BackButton.jsx

**Comment by helfi92** [comment]
@lailahgrant 👋

I don't think we need a back button. We can just use the browser native back button. The code for this is to replace `push` with `replace`. In other words, it will only be a one line change. The task is to figure out what line it is :)

**Comment by lailahgrant** [comment]
is it ok for me to be asking such questions here thou?????

**Comment by helfi92** [comment]
The file `ViewAwsWorkerTypeDefinition/index.jsx` doesn't exist anymore if you pull the latest changes. I think it's somewhere in `src/views/Clients`.

> is it ok for me to be asking such questions here thou?????

Yes, it's okay.

**Comment by helfi92** [comment]
I think so. You can open a pull-request now :)

**Comment by lailahgrant** [comment]
I need help here, which one is gives navigation that's redirecting from an invalid url ??
I'm hoping it is the one that I should put for replace(), is it right thou?

**Comment by helfi92** [comment]
I'm not sure I understand the question. Could you elaborate, please?

**Comment by lailahgrant** [comment]
Good morning sir, I'm just so happy today :+1: 
Thanks for the good mentoring... @helfi92 

I like the word ```Merged```
it is really an honour

**Comment by helfi92** [comment]
Awesome work!

**Comment by lailahgrant** [comment]
> Awesome work!

:smile:  :simple_smile:
