### ISSUE TITLE
Replace "foo: bar" in the secret creation view with a placeholder

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#1572]
**Describe the bug**
When creating a secret, the secret area has the literal text `foo: bar` in it, which must be deleted to create a secret.

**To Reproduce**
1. Go to the secrets view
2. Click on '+'

**Expected behavior**
A placeholder that disappears when the user starts entering text

**Comment by susanreenesaa** [comment]
Assign this to me, please. I am an outreachy applicant and i accepted the invitation. please also help me know in which directory/file can I find this bug in order to fix it.
thanks

**Comment by djmitche** [comment]
I think @helfi92 is tracking who's up next for Outreachy applications, so I'll let him decide.

```
(go1.12.9) (v10.16.3) dustin@lamport ~/p/taskcluster [checks-links] $ git grep 'foo.*bar' ui/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
ui/src/components/SecretForm/index.jsx:          foo: 'bar',      
```

**Comment by susanreenesaa** [comment]
okay, You let me know about any feedback. But this issue was not signed to outreachy. thanks

**Comment by susanreenesaa** [comment]
thanks. i am working on it

**Comment by susanreenesaa** [comment]
i am not familiar with js yml or safeDump. I realized that whenever i type js in that method, its not recognized and shows an error. so I am requesting for any documentation that can help me fix this, please.

**Comment by djmitche** [comment]
The format there is [YAML](https://yaml.org/), not JS.  Hopefully that helps!  [The wikipedia](https://en.wikipedia.org/wiki/YAML) has some nice examples.

**Comment by susanreenesaa** [comment]
@djmitche, @helfi92  please help me review my pull request. If what I did was the right thing. thanks
I replaced <CodeEditor> with <Textfield> deleted the imported code editor module and also have not included the value attribute because it throws an error.

**Comment by djmitche** [comment]
It looks like there's some commented-out code in https://github.com/susanreenesaa/taskcluster/commit/12cd3704b30b5750061c6993e4eddb3c9d8baa73 - can you describe the error you're seeing and what you've tried in order to solve it?

**Comment by susanreenesaa** [comment]
I commented out the code just in case what I did is wrong, I just uncomment it but if the code is okay, then I will delete the commented code
currently, there is no error be couese i didnot include the value propety. But when I include the value={editorValue} property,
in the UI, it displays foo: bar in the textField. On trying to delete "foo: bar" it displays "{object Object} which does nto delete or allow a user to to type anything in the text field despite the presence of a blinking cursor

**Comment by helfi92** [comment]
@susanreenesaa If you open a pull-request, I would be able to look at the code and be in a better position to test and help :)

**Comment by susanreenesaa** [comment]
@helfi92
Sorry, I thought that I had created one.
the link to the pull request is https://github.com/taskcluster/taskcluster/pull/1686

**Comment by helfi92** [comment]
Resolved in https://github.com/taskcluster/taskcluster/commit/0c6171af4b2ecca0f94ce60a775db65f2e103178.
