### ISSUE TITLE
Remove aws-provisioner support from UI

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#1576]
**Reserved** for [outreachy](https://www.outreachy.org/) candidates. In order for this to be assigned to you, make sure to complete the first step of the application process outlined in the [project description](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/#build-a-component-that-can-display-a-json-schema).

---

The "AWS Provisioner" component will no longer have anything to talk to as of November 9.  Let's remove it.  This involves:
 * removing from the navigation menu
 * removing the view and any associated components
 * removing the aws-provisioner-related GraphQL queries from the `web-server` service

**Comment by helfi92** [comment]
Anything under `/aws-provisioner` belongs to the aws-provisioner. https://taskcluster-ui.herokuapp.com/aws-provisioner.

**Comment by kellim** [comment]
Can you assign this to me please?

**Comment by kellim** [comment]
@helfi92 I was looking to see if there was a pull request for when AWS Provisioner was added so I could figure out everything that needs to be removed, but instead I found one where it was removed already- https://github.com/taskcluster/taskcluster/pull/929/files
It looks like those changes are no longer in the repo, and that pull request also had some code for Provisioners too, which looks like you don't want removed at this time. 

Would that pull request linked above be the best guide I can use for code to remove -- only removing what's related to AwsProvisioner and not Provisioner?

**Comment by djmitche** [comment]
See the comments on that PR -- the aws-provisioner view is now OK to remove (worker-manager is in production) but the provisioners view should stay.

**Comment by helfi92** [comment]
We previously removed the `/aws-provisioner` and `/provisoners` views but reverted the change a day or two later. At this time we want to keep `/provisoners` but remove `/aws-provisioner`.
