### ISSUE TITLE
[UI] Make workers view mobile friendly

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1585]
**Reserved** for [outreachy](https://www.outreachy.org/) candidates. In order for this to be assigned to you, make sure to complete the first step of the application process outlined in the [project description](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/#build-a-component-that-can-display-a-json-schema).

---

**To Reproduce**
1. Go to https://taskcluster-ui.herokuapp.com/provisioners/gce/worker-types/gecko-1-b-linux
2. Make the width of the screen smaller

**Actual behavior**

<img width="325" alt="Screen Shot 2019-10-11 at 3 42 02 PM" src="https://user-images.githubusercontent.com/3766511/66680098-b9731d00-ec3d-11e9-909b-b1630a705dc2.png">

**Expected behavior**
The breadcrumbs and dropdown components both sit on their own lines.

**Comment by alphaCentaauri** [comment]
May I be assigned to work on this issue?

**Comment by helfi92** [comment]
I think you are assigned to https://github.com/taskcluster/taskcluster/issues/1587. We don't have a lot of issues for everyone :)

**Comment by biddwan09** [comment]
Hi Can I get assigned to this issue please ?? I am looking for a first contribution in this project

**Comment by helfi92** [comment]
Hey @biddwan09. This issue is reserved to Outreachy candidates. In order for this to be assigned to you, make sure to complete the first step of the application process outlined in the [project description](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/#build-a-component-that-can-display-a-json-schema).

**Comment by JiwoonKim** [comment]
Hi! I've finished all the tasks assigned to me at the moment. May I take this issue?

**Comment by naimiii** [comment]
can you please assign it to me ? I am an Outreachy candidate ?

**Comment by Rolikasi** [comment]
Hi, @helfi92. Can I take this issue please?
