### ISSUE TITLE
[UI] Text is not vertically centered

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1588]
**Reserved** for [outreachy](https://www.outreachy.org/) candidates. In order for this to be assigned to you, make sure to complete the first step of the application process outlined in the [project description](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/#build-a-component-that-can-display-a-json-schema).

---

**To Reproduce**
1. Go to https://taskcluster-ui.herokuapp.com/tasks/eWxW0D38QgOv9WZNKgCgAg
2. Click on "Artifact" to open the panel
3. Look for an artifact that doesn't have the label "LOG"

**Actual behavior**

The text is not vertically centered. There is more space below the text.

<img width="805" alt="Screen Shot 2019-10-11 at 4 16 32 PM" src="https://user-images.githubusercontent.com/3766511/66682491-42d91e00-ec43-11e9-9bf9-c3db330426b9.png">

**Expected behavior**
The text is vertically centered.

**Comment by naimiii** [comment]
can i contribute on this one too ? I m an Outreachy applicant.

**Comment by biddwan09** [comment]
Hi can I contribute on this one ?? Please assign to this one to me

**Comment by naimiii** [comment]
![image](https://user-images.githubusercontent.com/28563415/66714297-84e29b00-edce-11e9-942a-a23d86167511.png)
when i run it locally it shows like this . please assist

**Comment by helfi92** [comment]
Do you get a different error after adding the following line?

```diff
diff --git a/ui/src/views/Tasks/TaskGroup/index.jsx b/ui/src/views/Tasks/TaskGroup/index.jsx
index c3b7c56b5..6bab8b137 100644
--- a/ui/src/views/Tasks/TaskGroup/index.jsx
+++ b/ui/src/views/Tasks/TaskGroup/index.jsx
@@ -593,6 +593,7 @@ export default class TaskGroup extends Component {
     // so handle task-not-found errors gracefully
     return (
       error.graphQLErrors &&
+      error.graphQLErrors[0] &&
       error.graphQLErrors[0].statusCode === 404 &&
       error.graphQLErrors[0].requestInfo.method === 'task'
     );
```

**Comment by naimiii** [comment]
No . Still same error .

**Comment by naimiii** [comment]
yes i m getting different error 

![image](https://user-images.githubusercontent.com/28563415/66719964-fc84ea00-ee0f-11e9-8403-f7d885b6d4ca.png)

**Comment by helfi92** [comment]
This error usually happens when the web-server service is not running. Make sure that `ui` and `services/web-server` are both running on a separate terminal.

**Comment by naimiii** [comment]
@helfi92 
![image](https://user-images.githubusercontent.com/28563415/66833022-82ba4100-ef74-11e9-9773-c4cc4e1fb8d9.png)
I  figure out that i have  to add code in this portion of file  to fix the bug  .M i right ?

**Comment by helfi92** [comment]
If you open up a pull-request, It would be easier for me to check the implementation :)

**Comment by naimiii** [comment]
@helfi92  Sure . I will .Let me add some code into it according to myself : )

**Comment by JiwoonKim** [comment]
Hi, @naimiii ! Do you need any help?

**Comment by naimiii** [comment]
@JiwoonKim  Thank you for your concern but i  already fixed the issue . :)
