### ISSUE TITLE
Various dependancies is `ui` are backlogged or not maintained

### ISSUE THREAD

**Issue by vishakhanihore** [taskcluster/taskcluster#1591]
**Describe the bug**

Various dependencies is `ui` are backlogged or not maintained. Update them to a new version or a maintained version.

**Comment by vishakhanihore** [comment]
@helfi92 @djmitche When I installed the dependency, Many warnings were there due to incorrect peer or unmaintained version. Should I update and test the `UI` and push a PR for this issue ?

**Comment by djmitche** [comment]
Some of those can be tricky to untangle, but that would be a great contribution!  I'd suggest taking one single issue and figuring out a minimal fix for it.  It may turn out that many are not easily fixed because they are dependencies of neutrino or other packages we don't directly control.
