### ISSUE TITLE
reference documentation fail with e.items is undefined

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#1599]
**Describe the bug**
Lots of reference pages such as https://docs.taskcluster.net/docs/reference/core/purge-cache are showing `e.items is undefined`

**To Reproduce**
1. Go to https://docs.taskcluster.net/docs/reference/core/purge-cache
1. See error

**Expected behavior**
docs!

**Comment by JiwoonKim** [comment]
May I take this issue?

**Comment by djmitche** [comment]
If you know how to solve it, sure!

**Comment by helfi92** [comment]
I don't seem to replicate. Perhaps a screenshot might help.

**Comment by djmitche** [comment]
Indeed, it appears to be working again.  :weird:
