### ISSUE TITLE
[UI] Deep link the Compare Scopes view

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1600]
**Describe the bug**
It's hard to share links of the compare scopes view without having to re-type scopes.

**To Reproduce**
1. Go to https://taskcluster-ui.herokuapp.com/auth/scopes/compare
2. Ensure the scope editors have the following values

<img width="1586" alt="Screen Shot 2019-10-13 at 10 40 51 AM" src="https://user-images.githubusercontent.com/3766511/66717345-f78b5080-eda5-11e9-9484-fbab42c85991.png">

3. Click the compare scopes button in the lower right
4. Refresh the page

**Actual behavior**
When the user refreshes the page, the editors become empty, and the comparison output that was displayed after clicking the compare scopes is cleared.

**Expected behavior**
When the user refreshes the page, the page looks like before:

<img width="1671" alt="Screen Shot 2019-10-13 at 10 42 30 AM" src="https://user-images.githubusercontent.com/3766511/66717368-2bff0c80-eda6-11e9-9fb8-1742a34a53ee.png">

**Additional context**
We can store the editor values as query parameters and use the [`qs`](https://www.npmjs.com/package/qs) package (already imported in the `ui` directory) to manipulate the query string. We can name the query parameters `scopesA` and `scopesB`.

**Comment by devnoorfatima** [comment]
Can I work on this issue.

**Comment by devnoorfatima** [comment]
@helfi92 I tried doing it in the past days but I can't figure out how to use the qs package.Can you please help me a bit.

**Comment by shilpiverma509** [comment]
@devnoorfatima  I was working on a similar issue. We need the qs package to manipulate the url.
xI did like this to manipulate my url to add query params:
store the editor value from the query params in the url.
    const query = parse(this.props.location.search.slice(1));

To add the editor value to the url , you can use the replace method from javascript and stringify from qs package. 
You are replacing your current url by adding the editor value as query params 
    `URL.replace(
      `/auth/scopes/compare${stringify(query, { addQueryPrefix: true })}`
    ); `.
This was my approach . @helfi92 will be able to guide you better :)

**Comment by devnoorfatima** [comment]
Thank you so much for the help @shilpiverma509

**Comment by helfi92** [comment]
This has been resolved. It is no longer an issue.
