### ISSUE TITLE
[UI] CodeEditor placeholder text color

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1615]
**Describe the bug**
The placeholder for the CodeEditor component doesn't look like a placeholder.

**To Reproduce**
1. Add the following diff

```diff
diff --git a/ui/src/components/SecretForm/index.jsx b/ui/src/components/SecretForm/index.jsx
index 8245b7127..fb7c5c9cd 100644
--- a/ui/src/components/SecretForm/index.jsx
+++ b/ui/src/components/SecretForm/index.jsx
@@ -226,6 +226,7 @@ export default class SecretForm extends Component {
             {showSecret && (
               <ListItem className={classes.editorListItem}>
                 <CodeEditor
+                  placeholder="yadi yadi yada"
                   onChange={this.handleEditorChange}
                   mode="yaml"
                   lint
```

2. Go to http://localhost:5080/secrets/create
3. Erase the content of the editor so that we can see the placeholder

**Actual behavior**

The placeholder looks like actual text, not a placeholder.

_Dark theme:_
![Screen Shot 2019-10-14 at 11 02 17 AM](https://user-images.githubusercontent.com/3766511/66761483-1e16bd80-ee72-11e9-9664-5455ceb19829.png)

_Light theme:_
![Screen Shot 2019-10-14 at 11 04 52 AM](https://user-images.githubusercontent.com/3766511/66761716-882f6280-ee72-11e9-82de-616b94cf9f8b.png)

**Expected behavior**
A placeholder should look a bit ligher than normal text. For example, if you navigate to https://material-ui.com/components/text-fields/#textfield, "Cat in the Hat" is text value whereas "Password" is a placeholder value.

![Screen Shot 2019-10-14 at 11 04 16 AM](https://user-images.githubusercontent.com/3766511/66761638-6504b300-ee72-11e9-8a83-b4e34a284d30.png)

**Comment by bini11** [comment]
Hey @helfi92 I want to work on this bug. can you assign it to me?

**Comment by helfi92** [comment]
I haven't heard back from @bini11.

**Comment by ergilaze** [comment]
Hi, I want to have a try on this one

**Comment by helfi92** [comment]
Go for it.

**Comment by ergilaze** [comment]
@helfi92 is there like a global styles file, because I think that I need to use CSS (I don't see you using styled-components) to change the placeholder color.

**Comment by helfi92** [comment]
We use css in js. Here’s where styles are defined in the code editor component:
https://github.com/mozilla-frontend-infra/components/blob/master/src/components/CodeEditor/index.jsx#L16

**Comment by ergilaze** [comment]
@helfi92 I managed to do it this way. I don't if this will do it, but tell me if there is a better way.
<img width="754" alt="Screenshot 2020-01-08 at 03 39 19" src="https://user-images.githubusercontent.com/44012466/71945998-a9c98d00-31c8-11ea-8433-e9cae8268a51.png">
<img width="793" alt="Screenshot 2020-01-08 at 03 41 05" src="https://user-images.githubusercontent.com/44012466/71946014-ba7a0300-31c8-11ea-8f7e-c5009ca60ccb.png">

**Comment by helfi92** [comment]
hm, I think the change should be in mozilla-front end-infra/components, not in this repo.

**Comment by helfi92** [comment]
See the comment in https://github.com/taskcluster/taskcluster/pull/1755 for some context.

**Comment by ergilaze** [comment]
@helfi92 I changed the style from mozilla-front end-infra/components, but I don't have permission to push my code

**Comment by helfi92** [comment]
Ah, you’ll have to create a fork of the repo and push to that fork rather than pushing directly to the repo. The GitHub UI will then give you the ability to create a pull-request from your fork branch.

**Comment by ergilaze** [comment]
@helfi92 https://github.com/mozilla-frontend-infra/components/pull/75

**Comment by helfi92** [comment]
Thanks! I'll take a look soon.
