### ISSUE TITLE
[taskcluster-lib-scopes] Remove usage of Node built-in 'assert' from published library

### ISSUE THREAD

**Issue by edmorley** [taskcluster/taskcluster#162]
Hi!

Treeherder uses `taskcluster-lib-scopes` in the browser, for the taskcluster actions feature - eg:
https://github.com/mozilla/treeherder/blob/23036375f9faec4c0f343e51024eb7feb2195c45/ui/models/taskcluster.js#L64-L68

In the upcoming webpack 5, webpack no longer automatically polyfills node built-ins in imported libraries in an effort to reduce unintended bundle size bloat.

Trying webpack 5 out against Treeherder I get several errors like:

```
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need these module and configure a polyfill for it.

If you want to include a polyfill, you need to install 'assert'.
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.alias: { "assert": false }
 @ ./node_modules/taskcluster-lib-scopes/src/index.js 7:2-26
 @ ./ui/models/taskcluster.js 4:0-61 59:11-30
 @ ./ui/models/push.js 11:0-45 94:11-27 97:13-29 110:11-27 113:13-29 157:13-29 160:15-31
 @ ./ui/logviewer/App.jsx 10:0-39 150:8-17
 @ ./ui/logviewer/index.jsx 12:0-24 13:27-30
```

Whilst we could configure a polyfill, I think it would be best for `taskcluster-lib-scopes` to stop using `assert` in non-test code, so it's browser-compatible out of the box. 

Many thanks :-)

**Comment by djmitche** [comment]
Hm, we no longer publish `taskcluster-lib-scopes`.  I had forgotten that it was being used in treeherder.  Perhaps we should move this functionality to tc-client/tc-client-web.

**Comment by edmorley** [comment]
Ah sorry I didn't know. Moving that functionality to tc-client-web would work for us :-)

**Comment by djmitche** [comment]
In fact, once we have scope expression evaluation support, I think we will want to call the auth service to make this check, rather than doing so locally (/cc @imbstack)

**Comment by djmitche** [comment]
https://github.com/taskcluster/taskcluster-lib-scopes/pull/31

**Comment by imbstack** [comment]
Moving it into clients makes sense to me. I'm not really sure when we'll get expression support in auth but once that happens the rest of the plan is A+.

**Comment by djmitche** [comment]
You should be good to use taskcluster-lib-scopes@10.0.2 without assert.

**Comment by edmorley** [comment]
Thank you :-)
