### ISSUE TITLE
[UI] Action buttons (re-run, edit, cancel) directly in group view

### ISSUE THREAD

**Issue by reuben** [taskcluster/taskcluster#1630]
I'm trying out the new TC UI and it's great :D

It'd be really cool to have at least a "rerun task" button inline in the task group view, as otherwise one has to open the details page for each task individually. This would be particularly useful in situations like: forgot to purge a cache used by workers of type XYZ, so now all XYZ jobs in the group need to be re-run.

**Comment by helfi92** [comment]
> I'm trying out the new TC UI and it's great :D

\o/

> It'd be really cool to have at least a "rerun task" button inline in the task group view, as otherwise one has to open the details page for each task individually. This would be particularly useful in situations like: forgot to purge a cache used by workers of type XYZ, so now all XYZ jobs in the group need to be re-run.

Would handling this via [actions](https://docs.taskcluster.net/docs/manual/design/conventions/actions) help? For example, we could add an action to rerun/retrigger failed tasks on a group. They would be located bottom right in the speed dial.

**Comment by reuben** [comment]
Sometimes one task fails and I know several others of the same type will also fail for the same reason, so I preemptively cancel them. I can't think of a way to capture that as a single action. But for re-running I think the action approach would work, yes.

**Comment by helfi92** [comment]
Continued in https://bugzilla.mozilla.org/show_bug.cgi?id=1588857.
