### ISSUE TITLE
[UI] Improve user experience of a paginated table (ConnectionDataTable)

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1633]
**Describe the bug**
**Reserved** for [outreachy](https://www.outreachy.org/) candidates. In order for this to be assigned to you, make sure to complete the first step of the application process outlined in the [project description](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/#build-a-component-that-can-display-a-json-schema).

---

Knowing when a table is paginated is not straightforward. For example, navigating to 
https://taskcluster-ui.herokuapp.com/auth/clients requires the user to scroll all the way down to know this table is paginated. Another issue is that a user that tries to search for a client using the browser's "CMD + F" page search feature might not find what they're looking for if the search term happens to be in a different page. For big paginated tables, users need to know right away that a table is paginated without having to scroll down to the end.

**To Reproduce**
1. Go to https://taskcluster-ui.herokuapp.com/auth/clients

**Expected behavior**
A user knows when a table is paginated without having to scroll all the way down to the end.

**Comment by JiwoonKim** [comment]
Hi! I've completed all the tasks assigned to me at the moment. May I take this issue?

**Comment by JiwoonKim** [comment]
@djmitche @helfi92 
hmm... I'm trying to get the web-server running but it seems to get this error that I should provide `option.accountId`. The web-server was working fine until I rebased my code on the upstream/master. Maybe I'm missing something?

<img width="700" alt="error" src="https://user-images.githubusercontent.com/29671309/66859406-34ce2900-efc6-11e9-8ca0-f479e642a737.PNG">

**Comment by helfi92** [comment]
It will be fixed once https://github.com/taskcluster/taskcluster/pull/1637#pullrequestreview-302126230 is merged :) Sorry about that.

**Comment by djmitche** [comment]
(I assigned #1246 to @JiwoonKim so no need here)

**Comment by JiwoonKim** [comment]
No problem! solved it after rebasing the code based on #1637 :)

This sounds like an interesting task. 
So I'm thinking a simple solution would be to maybe bring the pages back and forth button (< >), which is at the bottom, to the top of the page? But while this might solve the first problem, I'm thinking it might not help for the second problem for searching a specific client. Should I think of an entirely different way to figure out the ui?

**Comment by JiwoonKim** [comment]
Oh wow. @djmitche Thanks for assigning me to #1246 , but I was asssigned to this task first and was wondering if I can keep working on this issue. I feel like #1246 will maybe be more fitted for @ajinkabeer  who has already handled a few tasks regarding smoke tests.

**Comment by helfi92** [comment]
> So I'm thinking a simple solution would be to maybe bring the pages back and forth button (< >), which is at the bottom, to the top of the page?

I think that's a great idea. What we can possibly do is add the pagination both on top and bottom. We can possibly expose a boolean prop  (e.g., withTopPagination) that would allow us to have small tables like the artifacts table in https://taskcluster-ui.herokuapp.com/tasks/f2WzQXE5RUSVDjPrHZubCQ rendered without the top pagination and have other tables (that take most of the screen)  rendered with a top and bottom pagination.

> But while this might solve the first problem, I'm thinking it might not help for the second problem for searching a specific client. Should I think of an entirely different way to figure out the ui?

That's fine. We don't need to worry about this issue for now. A lot of the views actually have a search component in the app bar that allows searching through the pages.

**Comment by helfi92** [comment]
Resolved in https://github.com/taskcluster/taskcluster/commit/bee9a224fd150ce320966b2d7001214b43c3c11a.
