### ISSUE TITLE
[UI] Icon replacement

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1657]
**Reserved** for [outreachy](https://www.outreachy.org/) candidates. In order for this to be assigned to you, make sure to complete the first step of the application process outlined in the [project description](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/#build-a-component-that-can-display-a-json-schema).

---

[FileXmlIcon](https://github.com/taskcluster/taskcluster/blob/4786885e8f2680c8067e4ca34bb1b3b61476ceae/ui/src/utils/constants.js#L13) doesn't seem to exist anymore in mdi-react v6. Before we are able to [migrate](https://github.com/taskcluster/taskcluster/pull/1655) from `^5.0.0 -> ^6.0.0`, we will need to replace that icon with another one that makes sense.

You can find the list of icons in https://materialdesignicons.com/.

**Comment by km-js** [comment]
Hey! Just wondering if this one works as an XML file icon?


![Screenshot_41](https://user-images.githubusercontent.com/39799586/66962022-9c02e080-f08d-11e9-8510-860f243ad957.png)

**Comment by helfi92** [comment]
Sure, that works. I think we already use this icon in https://github.com/taskcluster/taskcluster/blob/4786885e8f2680c8067e4ca34bb1b3b61476ceae/ui/src/utils/constants.js#L17

We can definitely re-use it.

**Comment by km-js** [comment]
Hey, am getting this error. I think the FileCodeIcon is not supported by v5. 

![Screenshot_42](https://user-images.githubusercontent.com/39799586/67076297-8505e080-f1aa-11e9-9fcb-7ba717561898.png)

**Comment by helfi92** [comment]
What code gives this error?

**Comment by km-js** [comment]
import FileCodeIcon from 'mdi-react/FileCodeIcon'

Though it's working in mdi-react v6.

**Comment by helfi92** [comment]
I see. Then perhaps you can migrate to mdi-react v6 in this PR while we're at it to make it work.

**Comment by km-js** [comment]
Sure👍
