### ISSUE TITLE
[UI] Error message hard to read in docs

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1660]
**Describe the bug**
When viewing docs, sometimes error panel are hard to see.

**To Reproduce**
1. Add the following diff

```diff
diff --git a/ui/docs/manual/README.mdx b/ui/docs/manual/README.mdx
index 68a7e270f..a05dac2ca 100644
--- a/ui/docs/manual/README.mdx
+++ b/ui/docs/manual/README.mdx
@@ -36,3 +36,5 @@ describes how these tasks are executed.  The next chapter, [System
 Design](/docs/manual/system-design), provides the details you will need to interact
 with Taskcluster. Finally, [Using Taskcluster](/docs/manual/using) presents a
 collection of common use cases and approaches to satisfy them.
+
+<>
```

2. Go to http://localhost:5080/docs/manual/
3. See error

![Screen Shot 2019-10-16 at 11 42 02 AM](https://user-images.githubusercontent.com/3766511/66935461-fe1a0200-f009-11e9-8d07-02997bd5b776.png)

**Expected behavior**
We can see the full content of the error message.

**Comment by naimiii** [comment]
@helfi92  can i contribute into it please ? I am an outreachy  candidate .

**Comment by THEozmic** [comment]
What's the status of this?

**Comment by helfi92** [comment]
This issue is free to grab. I haven't heard back from @DrFeederino.
