### ISSUE TITLE
[UI] Make homepage mobile friendly

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1664]
**Describe the bug**
The mobile experience of the homepage view is not ideal. We can't see the full text without scrolling for example.

**To Reproduce**
1. Go to https://taskcluster-ui.herokuapp.com/ or http://localhost:5080
2. Make the window really small in width

<img width="319" alt="Screen Shot 2019-10-16 at 2 19 15 PM" src="https://user-images.githubusercontent.com/3766511/66946938-f8c7b200-f01f-11e9-8fba-aed458980aec.png">

**Expected behavior**
The text is fully readable without having to scroll.

**Comment by naimiii** [comment]
@helfi92  thank you for assigning it . :)

**Comment by naimiii** [comment]
@helfi92  Do we have a mock up of what this screen should look like on mobile? should I make the font smaller or is the requirement to keep the font size the same?

**Comment by naimiii** [comment]
@helfi92  this is an idea  i am  having for mobile.
![73395272_412224322777389_6333367398975930368_n](https://user-images.githubusercontent.com/28563415/67110002-32004d80-f1eb-11e9-8fdb-352d7835a26d.png)

**Comment by helfi92** [comment]
Making the font size smaller would be a really good fix. We don't need to change the layout.

**Comment by naimiii** [comment]
@helfi92  Alright , thank you ! :)

**Comment by helfi92** [comment]
Resolved in https://github.com/taskcluster/taskcluster/commit/5d28247612d82a2f393a8194c1bb99301c41311b.
