### ISSUE TITLE
[web-server] CORS for TPL endpoints

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1665]
CORS is only configured for the rootUrl. We should configure CORS for third party login endpoints. We can get the origins from the registered clients redirect URI field.

**Comment by djmitche** [comment]
I'm curious what the lack of CORS breaks.. I thought CORS was only for XHR requests?

**Comment by helfi92** [comment]
Our current endpoints only work for requests made from the taskcluster UI so `/login/oauth/token` and `/login/oauth/credentials` (called from third party sites) won't work. Does that help answer your question?

**Comment by djmitche** [comment]
Ah, yes -- those are indeed accessed with XHR.  Thanks!
