### ISSUE TITLE
How I can contribute to "Support GitHub Logins in Taskcluster"  projects.

### ISSUE THREAD

**Issue by iFlameing** [taskcluster/taskcluster#167]
@djmitche can you help me with getting  started with this project ? . sorry for opening this issue but I am asking the same question in irc channel for 2 days but didn't get any response.

**Comment by djmitche** [comment]
I'm sorry!  That channel gets a bit busy, and while we try to spot everything, sometimes it gets missed. There's also a #tc-contributors channel that might be better.

That project is only just proposed, so it may not be accepted by Mozilla or by Google.  But!  You could get started on it by looking at the `login` service in this repository as well as the login strategies in the `web-server` service.  `login` is the old version (designed to work with the existing [tools site](https://tools.taskcluster.net)) and the login strategies are the new version, designed to work with the code in the `ui/` directory.

What we want to do is this:
 * support signing in with github (so the UI knows your github username)
 * support securely getting Taskcluster credentials corresponding to your github identity
   * with scopes based on the user's team membership and organization administration

(there's probably more -- we're not done designing the project yet)

**Comment by iFlameing** [comment]
@djmitche ok then I will wait for the final proposal by the mozilla organisation . As I already contributed to [Iodide](https://github.com/iodide-project/iodide) (which is also a mozilla project )which support singning in with github we can use there's approach also, just for suggestion. Is there any starter issue related to this project at which I might work .I am doing react, node and javascript for last 1year.

**Comment by djmitche** [comment]
Sounds good!
