### ISSUE TITLE
[UI] broken links in page information

### ISSUE THREAD

**Issue by Rolikasi** [taskcluster/taskcluster#1671]
**Describe the bug**
Links in page information in some views redirect to dead site

**To Reproduce**
1. Go to http://localhost:5080/tasks/create
2. Click on 'page information'
3. Click on 'documentation' link
4. See dead site https://tc.example.com/docs/

**Expected behavior**
Links must be relevant

**Additional context**
Same with http://localhost:5080/quickstart

**Comment by helfi92** [comment]
Ah, that value comes from `TASKCLUSTER_ROOT_URL` which is configured in `ui/static/env.js`. To have that link work, it should point to a deployment. I have mine locally pointing to `https://taskcluster.net`. It should work on https://taskcluster-ui.herokuapp.com/tasks/create/ for example.
