### ISSUE TITLE
[UI] Add confirmation dialog for delete button

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1684]
**Reserved** for [outreachy](https://www.outreachy.org/) candidates. In order for this to be assigned to you, make sure to complete the first step of the application process outlined in the [project description](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/#build-a-component-that-can-display-a-json-schema).

---

**To Reproduce**
1. Go to https://taskcluster-ui.herokuapp.com/worker-manager
2. Click on the garbage icon
3. See error

**Expected behavior**
A confirmation dialog pops asking for confirmation.

![Screen Shot 2019-10-18 at 9 03 10 AM](https://user-images.githubusercontent.com/3766511/67096437-35152280-f186-11e9-9edb-9cf0c2d209a2.png)

**Additional context**
The implementation should be similar to the delete button inside the speed dial in https://taskcluster-ui.herokuapp.com/worker-manager/gce%2Fgecko-1-b-linux. To be able to delete, you would need to login with any credentials (e.g., clientId `test` and accessToken`test`).

**Comment by naimiii** [comment]
can  you please assign me this issue ?

**Comment by naimiii** [comment]
@helfi92  I was debugging the 'deleteRequest' function and got an error for wrong 'clientId' error . Is this a right behavior ? 
![74389760_934055763631215_4553600592953475072_n](https://user-images.githubusercontent.com/28563415/67316055-36957080-f521-11e9-8dec-ac214a413a20.png)

**Comment by helfi92** [comment]
Yes, you won't be able to perform the actual delete action. You can comment it out to make it look like it worked.

**Comment by naimiii** [comment]
@helfi92    so I will create a pop-up that will render before so user will have to confirm deletion just like in the Worker Pool form.

**Comment by naimiii** [comment]
@helfi92  what should the string say in the DialogAction component when deleting from the worker pools table component? should it still join the workerPool.workerPoolId1, workerPool.workerPoolId2 ID's?

**Comment by helfi92** [comment]
Do what you think makes sense then we can adjust things on the PR.

**Comment by naimiii** [comment]
@helfi92  Kindly check the PR of this issue . :)  thanks .

**Comment by vishakhanihore** [comment]
@naima-shaikh Are you still working on this ticket ?

**Comment by naima-shaikh** [comment]
@vishakhanihore  I already fixed it .Just waiting for the review . :(
