### ISSUE TITLE
[UI] Make a worker pool that is "scheduled for deletion" editable

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1685]
**Reserved** for [outreachy](https://www.outreachy.org/) candidates. In order for this to be assigned to you, make sure to complete the first step of the application process outlined in the [project description](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/#build-a-component-that-can-display-a-json-schema).

---

**Describe the bug**

**To Reproduce**
1. Go to https://taskcluster-ui.herokuapp.com/worker-manager?include_deleted=true
2. Look for a worker pool that has the "SCHEDULED FOR DELETION" label

![Screen Shot 2019-10-18 at 9 20 57 AM](https://user-images.githubusercontent.com/3766511/67097711-ace44c80-f188-11e9-9f5e-d55cfb45c002.png)

3. Click on the Worker Pool ID (e.g., `gecko-t/linux-large`)

**Actual behavior**
Nothing happens. The text is not a button.

**Expected behavior**
The user is navigated to the edit view of that worker pool.

**Additional context**
This bug was originally filed in https://bugzilla.mozilla.org/show_bug.cgi?id=1581863.

**Comment by ajinkabeer** [comment]
Can I try this one out if there aren't any new outreachy candidates looking for working on issues?

**Comment by km-js** [comment]
Can I try this one??

**Comment by helfi92** [comment]
Resolved in https://github.com/taskcluster/taskcluster/commit/1cdc517bd9948bf86c893ad4346715bfed2929d5.
