### ISSUE TITLE
[UI] Provider dropdown acting weird

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1688]
**Reserved** for [outreachy](https://www.outreachy.org/) candidates. In order for this to be assigned to you, make sure to complete the first step of the application process outlined in the [project description](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/#build-a-component-that-can-display-a-json-schema).

---

**To Reproduce**
1. Go to http://localhost:5080/worker-manager/create
2. Find the Provider dropdown and select 'aws'
3. See error in the code editor

![Screen Shot 2019-10-18 at 2 59 13 PM](https://user-images.githubusercontent.com/3766511/67120738-e4b6b880-f1b7-11e9-8914-2ba9a2c222bf.png)

![Screen Shot 2019-10-18 at 2 59 16 PM](https://user-images.githubusercontent.com/3766511/67120737-e4b6b880-f1b7-11e9-9aa4-35a11c2b690e.png)

**Expected behavior**

The code editor doesn't show an error.

**Additional context**

For step 2, if you select anything that isn't 'aws', it seems to work.

**Comment by Jo-IE** [comment]
can I take this up?

**Comment by katherine95** [comment]
I would also love to work on this one
