### ISSUE TITLE
[taskcluster-web] Can't trigger hook

### ISSUE THREAD

**Issue by mitchhentges** [taskcluster/taskcluster#171]
**Describe the bug**
The menu that shows all the hook actions doesn't pop up

**To Reproduce**
1. Go to [a hook](https://taskcluster-web.netlify.com/hooks/project-mobile/reference-browser-nightly-staging)
2. Mouse over the bottom right menu
3. Option to trigger hook doesn't appear

**Expected behavior**
I should be able to click a button to trigger a hook

**Screenshots**
![out](https://user-images.githubusercontent.com/7784737/52088615-3acbc900-2561-11e9-93da-bfcf422c7ce8.gif)

**Platform (please complete the following information):**
* OS: Ubuntu 18.04
* Firefox 64

**Comment by mitchhentges** [comment]
Interestingly, I can only reproduce this on my laptop (Dell P56F).
Perhaps this is related to its 4K screen?

I'm back on my desktop today, and the bottom-right circle is properly raising the menu with the "trigger" button, but my laptop still isn't showing it today. I did a force-refresh for kicks, but that didn't fix it.

(I've also just updated to Firefox 65 to see if that somehow solves the problem, but it did not)

**Comment by helfi92** [comment]
I can't seem to replicate. @mitchhentges Could you try clicking on the lower-left side of the button and see if the menu opens up? fwiw, the speed dial component is supposed to open on hover as well. It is also worth checking if the behavior is the same on Chrome.

**Comment by mitchhentges** [comment]
This behaviour is working properly in Chrome :thinking: 
I tried clicking the lower-left side, but it still wouldn't open. This is bizarre!

**Comment by helfi92** [comment]
@mitchhentges I created a possible fix :) Could you tell me if https://deploy-preview-255--taskcluster-web.netlify.com/hooks/garbage/abc456 works for  you?

**Comment by helfi92** [comment]
I got a confirmation on IRC that it works :)
