### ISSUE TITLE
Update initial value for worker-manager create-workerpool UI 

### ISSUE THREAD

**Issue by imbstack** [taskcluster/taskcluster#1715]
**Reserved** for [outreachy](https://www.outreachy.org/) candidates. In order for this to be assigned to you, make sure to complete the first step of the application process outlined in the [project description](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/#build-a-component-that-can-display-a-json-schema).

---

**Describe the bug**
As discussed in #1707, please update the initial values for `workerPool` configs.

**To Reproduce**
1. Go to https://taskcluster-ui.herokuapp.com/worker-manager/create
2. Select 'google' from provider drop down
3. See that the configuration field is an old version. 

**Expected behavior**
[this](https://taskcluster-ui.herokuapp.com/worker-manager/taskcluster-imaging%2Ftaskcluster-imaging-ci) is a more recent version of the config. You can use that as a base to build the new config on. Please remove anything "specific" and replace with `...`. Also the `launchConfigs` array should have only one element.

**Comment by Jo-IE** [comment]
Hi Could I please take this up?

**Comment by Jo-IE** [comment]
Hi @imbstack I have a quick clarification question about your posting. What does "anything specific" mean?

Thanks!

**Comment by imbstack** [comment]
Yeah, I mostly mean not having a value for `imageId` other than `...` in there or something.

**Comment by Jo-IE** [comment]
ok thank you @THEozmic @imbstack

**Comment by helfi92** [comment]
Resolved in https://github.com/taskcluster/taskcluster/commit/ebd4a7debb7490aa17f4d444abaac7023d05771c.
