### ISSUE TITLE
[UI] Align Card title with content

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1750]
**To Reproduce**
1. Go to http://localhost:5080/provisioners

**Actual behavior**

"aws-provisioner-v1" is indented.

![Screen Shot 2019-10-25 at 10 43 52 AM](https://user-images.githubusercontent.com/3766511/67580484-6a84b780-f714-11e9-91fd-a1c85452f179.png)

**Expected behavior**

"aws-provisioner-v1" is left aligned with the card content.

![Screen Shot 2019-10-25 at 10 44 07 AM](https://user-images.githubusercontent.com/3766511/67580483-6a84b780-f714-11e9-9854-d1c424de01d4.png)

**Comment by aryamanpuri** [comment]
@helfi92 I am looking forward for it .

**Comment by vishakhanihore** [comment]
@aryamanpuri We follow a proper development workflow here. Since @helfi92 assigned this issue to @somchi, You must have waited till you were assigned this issue. But rather than waiting you dropped a PR. Please read `contributing.md`.

**Comment by aryamanpuri** [comment]
@vishakhanihore I got your point . So no-one will review the changes I have made .
And for the time being what I can do for this projects. Please give direction .

**Comment by vishakhanihore** [comment]
Well I cant comment about the PR you have made, the final decision
obviously is in hands of maintainers.
For the time being you can read the docs and setup the project on your
local and look out for an unclaimed good first issue or any bug which you
think you may solve it. Maintainers will assign you the issue and then, you
are good to go.

**Comment by helfi92** [comment]
Done in https://github.com/taskcluster/taskcluster/commit/f51b9b0c762cff536aa1eee901c3aaec20336b3f.
