### ISSUE TITLE
[UI] Artifact names in Task Details are misaligned

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1751]
**Reserved** for [outreachy](https://www.outreachy.org/) candidates. In order for this to be assigned to you, make sure to complete the first step of the application process outlined in the [project description](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/#build-a-component-that-can-display-a-json-schema).

---

**Describe the bug**
Artifact names in Task Details are misaligned in small screens.

**To Reproduce**
1. Go to https://github.com/taskcluster/taskcluster/invitations
2. In the Task Details panel, click on Artifacts
3. Resize the window and make it really small in width

**Actual behavior**

![Screen Shot 2019-10-25 at 11 00 03 AM](https://user-images.githubusercontent.com/3766511/67582048-0ca59f00-f717-11e9-8836-30129eff95c1.png)

**Expected behavior**

The text is properly left aligned.

![Screen Shot 2019-10-25 at 11 00 14 AM](https://user-images.githubusercontent.com/3766511/67582047-0ca59f00-f717-11e9-9bac-5b0bebecd1de.png)

**Comment by naimiii** [comment]
Hi ! Could i please take this up ?  :)
