### ISSUE TITLE
[UI] Make search case insensitive

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1754]
**Reserved** for [outreachy](https://www.outreachy.org/) candidates. In order for this to be assigned to you, make sure to complete the first step of the application process outlined in the [project description](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/#build-a-component-that-can-display-a-json-schema).

---

**To Reproduce**
1. Go to https://taskcluster-ui.herokuapp.com/auth/roles/
2. Search for "Github" using the search bar

**Expected behavior**

<img width="1680" alt="Screen Shot 2019-10-25 at 5 08 03 PM" src="https://user-images.githubusercontent.com/3766511/67604681-3af0a200-f74a-11e9-880c-da9f2c2bbabb.png">

**Actual behavior**

<img width="1576" alt="Screen Shot 2019-10-25 at 5 08 07 PM" src="https://user-images.githubusercontent.com/3766511/67604680-3af0a200-f74a-11e9-8342-65c2ef830fd3.png">

Other views that need this change:
* https://taskcluster-ui.herokuapp.com/auth/clients
* https://taskcluster-ui.herokuapp.com/secrets
* https://taskcluster-ui.herokuapp.com/hooks
* https://taskcluster-ui.herokuapp.com/worker-manager

**Comment by Karskaya** [comment]
Hi! Can I take it as outreachy applicant?

**Comment by aryamanpuri** [comment]
@helfi92 I am too looking forward for this .

**Comment by mkneumann777** [comment]
I would like to tackle this issue if I may.

**Comment by naimiii** [comment]
@helfi92  Can i grab it as i completed all the assigned tasks . :)
