### ISSUE TITLE
Update `taskcluster signin` to work with new deployments

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#1758]
The [taskcluster shell client](https://github.com/taskcluster/taskcluster/tree/master/clients/client-shell#readme), available for download [here](https://github.com/taskcluster/taskcluster/releases/tag/v21.2.0), has a `taskcluster signin` command which interacts with a deployment's UI to get Taskcluster credentials on the command line.  In #1714, @helfi92 added support for this to the new UI.  However, the query arguments differ slightly between the old (tools.taskcluster.net) and new (everything else) UIs.

The bug here is to update the `taskcluster signin` implementation to use the new query parameters for all rootUrls *except* `https://taskcluster.net`, for which it should use the old query parameters.

RootUrls to try this against are https://stage.taskcluster.nonprod.cloudops.mozgcp.net or https://community-tc.services.mozilla.com (both will behave the same).

**Comment by ededals** [comment]
Is this one for me? Judging by the #1714 the new query parameters should look like this:
```http://localhost:5080/auth/clients/create?client_id=foo&callback_url=http%3A%2F%2Flocalhost%3A9500&expires=3%20days&scope%5B%5D=assume%3Abar&description=client%20for%20cli%20usage```

I guess i will have to modify signin.go url construction part to match the new format.

Just to double check, is the expected result a succesfull authentification when trying against https://stage.taskcluster.nonprod.cloudops.mozgcp.net ?

**Comment by djmitche** [comment]
> I guess i will have to modify signin.go url construction part to match the new format.

Indeed

> Just to double check, is the expected result a succesfull authentification when trying against https://stage.taskcluster.nonprod.cloudops.mozgcp.net ?

Correct.  Also, it should still work against https://tools.taskcluster.net (with TASKCLUSTER_ROOT_URL=https://taskcluster.net).

**Comment by helfi92** [comment]
@ededals Feel free to create a separate issue to handle the UI bit discussed in https://github.com/taskcluster/taskcluster/pull/1760#pullrequestreview-308029839 if that's more convenient for you. Otherwise, I'm fine keeping the discussion here.

**Comment by ededals** [comment]
We can continue all discussion here. I think there is a mistake in my code, because I am using ```name``` as ```client_id```. TASKCLUSTER_CLIENT_ID may be allready set as environment variable. In this case we I modify the query to include both ```client_id``` and ```name```. But there can be cases where it is not available, because I think TASKCLUSTER_ROOT_URL is only requirement for this tool

I can implement the functionality where the user needs to authenticate before signin in. I could show message "Please log in before to continue" in ```<ErrorPanel>``` component, if user is not logged in, otherwise show the  ```<ClientForm>```

From my perspective I used signin  mostly because I just needed to refresh the access token for existing client. In this case it was really convenient for me when the old ui offered me two choices: refresh access token or create new client after logging in. Maybe it would also be possible to include such choice in the new ui?

**Comment by helfi92** [comment]
> I modify the query to include both client_id and name.

I think we should just use `name` and `callback_url` as a queries. In the UI, we would read the name and then append it to the clientId which we can retrieve by reading the current logged in user.

> I can implement the functionality where the user needs to authenticate before signin in. I could show message "Please log in before to continue" in <ErrorPanel> component, if user is not logged in, otherwise show the <ClientForm>

We can make it like the /profile view when the user is logged out:

![Screen Shot 2019-10-29 at 7 36 40 AM](https://user-images.githubusercontent.com/3766511/67763784-df126b80-fa1e-11e9-804c-e23d2435a59a.png)

> As a side note, I used signin mostly because I just needed to refresh the access token for existing client. In this case it was really convenient for me when the old ui offered me two choices: refresh access token or create new client after logging in. Maybe it would also be possible to include such choice in the new ui?

That's a good idea but I think it would be better as a follow-up. Good thinking!

**Comment by ededals** [comment]
I loved how this turned out. Is there anything else I could work on?

**Comment by helfi92** [comment]
> I loved how this turned out.

Me too :)

> Is there anything else I could work on?

Are you interested in tackling https://github.com/taskcluster/taskcluster/issues/1878 by any chance? Feel free to comment directly on the issue if you are. Thanks!

**Comment by djmitche** [comment]
I think this is done...
