### ISSUE TITLE
[UI]:Introduce a field for `Client-Name` in `Sign-In Options`

### ISSUE THREAD

**Issue by vishakhanihore** [taskcluster/taskcluster#1764]
#### Description -:
Currently, We don't have a field for `Client Name` in our sign-in options. So when the user sees his profile `Client Id` is used at the place of `Name`.
I propose to introduce a field for `Client Name` during the Sign-In.

#### Screenshots -:

<img width="759" alt="Screenshot 2019-10-27 at 7 53 32 AM" src="https://user-images.githubusercontent.com/54327666/67628635-edca1880-f88e-11e9-8ae9-805f8ff9f97f.png">

**Comment by vishakhanihore** [comment]
@djmitche @helfi92 Please review if the following seems valid for our app. Thanks

**Comment by djmitche** [comment]
If I understand what you're suggesting, it's prompting the user for a name which is only ever used to display back to the user.  That seems like asking for extra work (and potentially causing people to get confused and ask us "what do I have to write for client name?") that has no real benefit.

What does bother me is that when I'm signed in manually, it shows "s" in the upper-right corner, presumably for the `s` in 'static/taskcluster/root`.  That could be addressed by showing some standard icon there when the user is signed in manually.

Are there other issues that would be solved by having a "client name"?

**Comment by vishakhanihore** [comment]
> What does bother me is that when I'm signed in manually, it shows "s" in the upper-right corner, presumably for the `s` in 'static/taskcluster/root`. That could be addressed by showing some standard icon there when the user is signed in manually.

I didn't quite get it, Whenever you are signed in the first character of your `Client ID` is used to display in the upper-right corner indicating you are signed in.

> Are there other issues that would be solved by having a "client name"?

I dont think it is going to solve any other potential issue. 

> If I understand what you're suggesting, it's prompting the user for a name which is only ever used to display back to the user. That seems like asking for extra work (and potentially causing people to get confused and ask us "what do I have to write for client name?") that has no real benefit.

Having a `Client_Name` may distinguish us to see who is logged in, As treating `client_id` with same as the name may also be confusing. If `Client_Name` is confusing what we can do is to introduce a field with `User_Name` it is sharper and may enable to see which user is logged in. 

@djmitche

**Comment by djmitche** [comment]
OK, I think I understand the idea, but in that case we're asking a user to enter their name, and the *only* thing we are going to do is display that name back to the user in their browser.  There's no way to verify that what the user enters is correct, and there's nowhere else to send that information.

**Comment by vishakhanihore** [comment]
> OK, I think I understand the idea, but in that case we're asking a user to enter their name, and the _only_ thing we are going to do is display that name back to the user in their browser. There's no way to verify that what the user enters is correct, and there's nowhere else to send that information.

I am getting your point. What I can think of a makeover is rather than giving a field in sign in, We can display an `edit icon` when the user views his profile in front of his name so that he can set his name?
@djmitche
