### ISSUE TITLE
change color in "By Type" button drop-down

### ISSUE THREAD

**Issue by susanreenesaa** [taskcluster/taskcluster#1765]
Check http://localhost:3000/tag/blog. The "By Type" button dropdown menu should have a consistent color. either the blue should appear on select or hover but it should not be on only Research Notes.
Therefore remove research Notes color and place it on hover over on the dropdown menu

![image](https://user-images.githubusercontent.com/49034794/67631807-1f051180-f8ac-11e9-8b03-8c5a21566444.png)

**Comment by susanreenesaa** [comment]
feel free to convert it to an  FTO issue

**Comment by Rolikasi** [comment]
Hi @susanreenesaa, I think you posted the issue in wrong repository. It's taskcluster project, not publiclab
