### ISSUE TITLE
display ellipsis bottom-right drop-down menu on hover

### ISSUE THREAD

**Issue by susanreenesaa** [taskcluster/taskcluster#1766]
The ellipsis icon should display the drop-down menu on hover over so that it becomes obvious for the user to see the dropdown even before clicking on the ellipsis button.
*currently dropdown is displayed on click*
*expecting*
dropdown to be displayed on hover and on click
![image](https://user-images.githubusercontent.com/49034794/67631829-828f3f00-f8ac-11e9-98de-f66029990ab8.png)

**Comment by Rolikasi** [comment]
@susanreenesaa I think you post the issue in wrong repository. It's taskcluster project, not publiclab
