### ISSUE TITLE
[UI] Saving an existent client

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1771]
**Reserved** for [outreachy](https://www.outreachy.org/) candidates. In order for this to be assigned to you, make sure to complete the first step of the application process outlined in the [project description](https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/mozilla/#build-a-component-that-can-display-a-json-schema).

---

**To Reproduce**
1. Go to http://localhost:5080/auth/clients/email%2Fbastien%40nextcairn.com%2Ftc-notify-test
2. Login with fake credentials (e.g., clientId `test` and accessToken `test`)
3. Click on the "Delete on Expiration" switch

**Actual behavior**
The save button is not clickable after making a change to the "Delete on Expiration".

![Screen Shot 2019-10-28 at 8 37 40 AM](https://user-images.githubusercontent.com/3766511/67678939-4e745680-f95e-11e9-816f-e329df8ef48c.png)

**Expected behavior**
The save button should be clickable

![Screen Shot 2019-10-28 at 8 37 45 AM](https://user-images.githubusercontent.com/3766511/67678916-3bfa1d00-f95e-11e9-9e65-0911e3d7ff9d.png)

**Additional context**
The button becomes clickable when a user changes any of the other fields. It just doesn't work for the switch for some reason. Let's fix that.

**Comment by Rolikasi** [comment]
Can I work on this issue?

**Comment by djmitche** [comment]
@Rolikasi you mentioned it's hard working on multiple issues at once.. one way to avoid that is working on only one or two at a time :)

**Comment by km-js** [comment]
I would like to work on this!
