### ISSUE TITLE
[docs] Add syntax highlighting to code blocks

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1772]
**Describe the bug**
In many places in our codebase, the UI seems to be missing some code highlighting.

**To Reproduce**

For example,

1. Go https://taskcluster-ui.herokuapp.com/docs/reference/integrations/github/taskcluster-yml-v0#deadlines-and-the-fromnow-function
2. The code block has one color (white) but if you navigate to https://taskcluster-ui.herokuapp.com/docs/reference/integrations/github/taskcluster-yml-v0#branch-filtering, the code blocks are properly syntax highlighted.

**Expected behavior**

Syntax highlighting is done on most code block inside `ui/docs`.

**Context**

The following should help you figure out which code blocks are missing syntax highlighting:

```
cd ui/docs
git grep '```$'
```

**Comment by lailahgrant** [comment]
Thank you Sir, let me get straight to it.

**Comment by lailahgrant** [comment]
Sir, should I put the given css on these different elements that have no highlighting??

I don't know what I did was right but when you inspect the different urls, one has <span></span> tags with css declared on them, and the other has no. Should I add those given span tags to the other url or is there reusable code I could use?

Thanks Sir.

**Comment by helfi92** [comment]
To add syntax highlighting, all we have to do is specify the language after the ` ``` `. For example, if the code block is something in javascript, then the latter should have ` ```js ` at the top.

**Comment by lailahgrant** [comment]
thank you sir..

This is also handy.
https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

**Comment by lailahgrant** [comment]
Sir, I'm through with it... 
Thanks.

**Comment by helfi92** [comment]
If you are done, the next step is to open a pull-request so I can review it.

**Comment by lailahgrant** [comment]
should i change the PR in the branch and create a new one?

**Comment by helfi92** [comment]
No, it's okay.

**Comment by helfi92** [comment]
What's up? :)

**Comment by lailahgrant** [comment]
it is about the emails we have been receiving.. 
I don't know, is it ok to be asking that here??

**Comment by lailahgrant** [comment]
Sir, what is the feedback on this issue #1772 ?

**Comment by helfi92** [comment]
I approved the pull-request. We're just waiting on #1729 to be done first before merging the code. I will take care of merging the PR. Feel free to add this to the list of contributions.

**Comment by lailahgrant** [comment]
Okay sir, thanks.

**Comment by lailahgrant** [comment]
Sir,I have been going through the <#1729> and it is really the most knowledgeable issue I have so far gone through and maybe about the feedback on issue <#1772>.

If it is okay with you, I would like to get an issue or you could refer a task to keep me busy.

*Thanks sir*

**Comment by helfi92** [comment]
Assigned you to https://github.com/taskcluster/taskcluster/issues/1953 :)

**Comment by helfi92** [comment]
Resolved in https://github.com/taskcluster/taskcluster/commit/084648878d0c7ddff97eacc9e78b397d06745141.
