### ISSUE TITLE
[UI] next/prev icon in light theme

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1773]
**Describe the bug**
The next and previous icon buttons are not showing in the light theme.

**To Reproduce**

1. Go to https://taskcluster-ui.herokuapp.com/tasks/eWxW0D38QgOv9WZNKgCgAg
2. Click on the light bulb icon in the app bar to switch to the light theme
3. Look at the right panel Task Run

**Actual behavior**

![Screen Shot 2019-10-28 at 11 29 44 AM](https://user-images.githubusercontent.com/3766511/67692340-62c44d80-f976-11e9-85e8-984abf508bb4.png)

**Expected behavior**

![Screen Shot 2019-10-28 at 11 30 30 AM](https://user-images.githubusercontent.com/3766511/67692338-62c44d80-f976-11e9-8135-4799d4eed377.png)

**Comment by aryamanpuri** [comment]
@helfi92 Can you assign me. I will look forward to it .

**Comment by aryamanpuri** [comment]
@helfi92 Should I add two function calls on clicking the toggle light / dark theme button .

**Comment by helfi92** [comment]
Hm, I'm not sure I understand the question. Feel free to create a pull-request then we can look at it there.

**Comment by helfi92** [comment]
Resolved in https://github.com/taskcluster/taskcluster/commit/be2876a740821888562fbd57717fadadc42b37b5.
