### ISSUE TITLE
[UI] Error not showing in Task Group view

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1774]
**To Reproduce**

1. Go to https://taskcluster-ui.herokuapp.com/tasks/groups/ZeW7IKcDRQipFT2TN4UAcg

**Actual behavior**

An empty view

![Screen Shot 2019-10-28 at 11 42 32 AM](https://user-images.githubusercontent.com/3766511/67693422-0bbf7800-f978-11e9-84b5-b5e866cd5adc.png)

**Expected behavior**
An error ``` No task-group with taskGroupId: `ZeW7IKcDRQipFT2TN4UAcg` ``` shows up. The error message to display will be in the response of the network request.

![Screen Shot 2019-10-28 at 11 43 45 AM](https://user-images.githubusercontent.com/3766511/67693560-45907e80-f978-11e9-9e64-e7df25d82a9a.png)

**Comment by aryamanpuri** [comment]
@helfi92 I am looking forward for it . Can you assign this to me .

**Comment by aryamanpuri** [comment]
@helfi92 Actually it is showing up . On going to  this link 
https://taskcluster-ui.herokuapp.com/tasks/groups/ZeW7IKcDRQipFT2TN4UAcg

![Screenshot from 2019-10-28 21-49-35](https://user-images.githubusercontent.com/43513114/67696552-1a844a00-f9cd-11e9-8420-6952ef3e2221.png)

**Comment by helfi92** [comment]
Ah, it looks like it doesn't always show. Try hard refreshing a couple of times.
