### ISSUE TITLE
[UI]: Unwanted extra space block in `auth/scopes`

### ISSUE THREAD

**Issue by vishakhanihore** [taskcluster/taskcluster#1813]
**Describe the bug**

There is a large patch of unwanted space under `Auth/Scopes` which makes no sense.

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to `http://127.0.0.1:5080/auth/scopes`
2. See error

**Expected behavior**

Remove this space as it looks worsens our UI.

**Screenshots**

<img width="1429" alt="Screenshot 2019-10-29 at 10 23 02 AM" src="https://user-images.githubusercontent.com/54327666/67738878-50114d80-fa36-11e9-8147-271710e1596e.png">

**See the Red Box**

**Comment by vishakhanihore** [comment]
@djmitche @helfi92 Is there any use of this unwanted patch of space which is blocking the list of `scopes` ?

**Comment by helfi92** [comment]
There is no use. Feel free to make the list cover more height.
