### ISSUE TITLE
[UI] Update react-styleguidist to v9

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1819]
`yarn styleguide` inside the ui directory should fire up the styleguide. You can see what changed by looking at https://github.com/styleguidist/react-styleguidist/releases. `yarn.lock` shows that we are currently on v7.3.11.

**Comment by vishakhanihore** [comment]
@helfi92 Should we fire up directly to 10.0 ? As there would be breaking changes in upgrading to 9.0 too then why not go for 10 :smile: ?

**Comment by helfi92** [comment]
Good idea.

**Comment by vishakhanihore** [comment]
Hello @PaliwalArpit, how is it going, feel free to ask for any help 😄 .

**Comment by vishakhanihore** [comment]
Hello @PaliwalArpit, how is it going, feel free to ask for any help 😄 .

**Comment by PaliwalArpit** [comment]
@vishakhanihore Hey, I have received confirmation from @helfi92 about v10 version working fine. So please go-ahead to close this issue as we have another PR with v10 in place.
Thanks!

**Comment by vishakhanihore** [comment]
@helfi92 Are we already using v.10 in place ?

**Comment by djmitche** [comment]
dup #3964
