### ISSUE TITLE
[UI] Pagination not working in workers table

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1823]
**To Reproduce**

1. Go to https://taskcluster-ui.herokuapp.com/provisioners/aws-provisioner-v1/worker-types/ami-test-pv
2. Open the developer devTools
3. Click on ">" for next page. Notice how the list of results is not updated
4. Click on "<" for previous page
5. Look at the error in developer tools console

![Screen Shot 2019-10-29 at 1 51 38 PM](https://user-images.githubusercontent.com/3766511/67794588-3f230500-fa53-11e9-8f85-c05a38725c32.png)

**Expected behavior**
Clicking on ">" should update the table with new rows.

_Note: Clicking next seems to work on a different worker-type. For example, it works on https://taskcluster-ui.herokuapp.com/provisioners/aws-provisioner-v1/worker-types/app-services-1-b-linux_

**Comment by Shubhamchinda** [comment]
Hey, I'd like to take this!

**Comment by helfi92** [comment]
Yay! Go for it :)

**Comment by vishakhanihore** [comment]
Hey @Shubhamchinda How is it going, Feel free to ping if you need help 😄

**Comment by helfi92** [comment]
Are you still working on this @Shubhamchinda?

**Comment by AtharvaSune** [comment]
Hey I would like to take this

**Comment by Shubhamchinda** [comment]
@helfi92 I Didn't get time for this, pardon!

**Comment by djmitche** [comment]
For whatever reason, this appears to work now.
