### ISSUE TITLE
[Depreciation] Remove react depreciation warnings from console

### ISSUE THREAD

**Issue by vishakhanihore** [taskcluster/taskcluster#1829]
**Describe the bug**

Whenever I fire up the app, multiple warnings of depreciation due to `components` also show up.

**Expected behaviour**

Remove the warnings.

**Screenshots**

<img width="1001" alt="Screenshot 2019-10-30 at 10 37 31 AM" src="https://user-images.githubusercontent.com/54327666/67830657-7b14a380-fb01-11e9-9445-23decc9e19c1.png">

**Comment by vishakhanihore** [comment]
@helfi92 @djmitche Your opinions?

**Comment by helfi92** [comment]
This was fixed a while ago :)
