### ISSUE TITLE
Can't sign in with github on community instance with Firefox Nightly

### ISSUE THREAD

**Issue by glandium** [taskcluster/taskcluster#1839]
With Firefox Nightly 72.0a1 (2019-10-30):
- Go to https://community-tc.services.mozilla.com/
- Click Sign in
- Click Sign in with GitHub
- Possibly authenticate with github
- The "temporary" tab that is now open on https://community-tc.services.mozilla.com/login/github/callback?code=... is now stuck on that, instead of disappearing and coming back to the original tab, reloading it, signed in.

**Comment by glandium** [comment]
(It works in Firefox Release)

**Comment by djmitche** [comment]
I feel like this has been a bug "in nightly" for several FF release cycles now.  Is there some feature that's preffed off in release that causes this?

**Comment by glandium** [comment]
mozregression points at https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=b526d511169a3ba8ea647d6de9183a62df0da1c8&tochange=e6a4330eb15f1536f505d6794c4efac3ca9fcf7e aka https://bugzilla.mozilla.org/show_bug.cgi?id=1503681

**Comment by glandium** [comment]
And setting `dom.targetBlankNoOpener.enabled` to `false` on Nightly fixes it. So presumably, TC would need to adjust to work with the new browser behavior.

**Comment by glandium** [comment]
Hotpatching the `<button>` to add `rel="opener"` works, so presumably this patch should fix it, assuming it's the right place:
```diff
diff --git a/ui/src/components/SignInDialog/index.jsx b/ui/src/components/SignInDialog/index.jsx
index 5ecd88adb..8baa8bc59 100644
--- a/ui/src/components/SignInDialog/index.jsx
+++ b/ui/src/components/SignInDialog/index.jsx
@@ -107,6 +107,7 @@ export default class SignInDialog extends Component {
                 button
                 component="a"
                 href="/login/github"
+                rel="opener"
                 target="_blank">
                 <ListItemAvatar>
                   <Avatar>
```
