### ISSUE TITLE
client auth UI: can't persist 'delete on expiration'

### ISSUE THREAD

**Issue by aerickson** [taskcluster/taskcluster#1853]
**Describe the bug**
I can't persist changes to the 'delete on expiration' flag for clients.

https://firefox-ci-tc.services.mozilla.com/auth/clients/project%2Fautophone%2Fbitbar-x-batt-g5

I switch the client to not 'delete on expiration', but the save icon doesn't activate.

**To Reproduce**

1. Go to https://firefox-ci-tc.services.mozilla.com/auth/clients/project%2Fautophone%2Fbitbar-x-batt-g5
2. Click on 'delete on expiration'
3. The save icon doesn't become active.

**Expected behavior**
At step 3, I would be able to click 'Save' and have it work.

**Screenshots**
n/a

**Platform (please complete the following information):**

 - OS: Mac OS X 10.14.6
 - Browser if applicable: Firefox
 - Version if applicable: 70.0 (64-bit)

**Additional context**
n/a

**Comment by helfi92** [comment]
This will be fixed in https://github.com/taskcluster/taskcluster/pull/1811.

**Comment by helfi92** [comment]
PR merged. Should be fixed in the next deployment.
