### ISSUE TITLE
[UI] No cancel button for tasks

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#1875]
**Describe the bug**
Cancel should be an option alongside "rerun" and "schedule"

**To Reproduce**

1. Go to https://community-tc.services.mozilla.com/tasks/KdwFUTxUTiWiHoRDBYhEmA/runs/0
2. Hover over the thing in the lower right

**Expected behavior**
A "cancel" option

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/28673/68091155-33b44d00-fe4a-11e9-92fe-dd9b2200318a.png)

**Comment by glandium** [comment]
Retrigger would be nice too.

**Comment by aryamanpuri** [comment]
@djmitche Can you assign me this issue ?

**Comment by helfi92** [comment]
web-server uses the following logic to fetch actions https://github.com/taskcluster/taskcluster/blob/7c58773472eac01f3771c7779a9397da5b503eaf/services/web-server/src/loaders/tasks.js#L36-L40

https://community-tc.services.mozilla.com/api/queue/v1/task/QA6K2qySQNaQBb2B806_vg/artifacts/public%2Factions.json returns a 404. @djmitche are we using a bad url or is this file simply non-existent in the community deployment?

**Comment by SimonSapin** [comment]
Isn’t `actions.json` for customizable, task-specific actions? Shouldn’t "cancel" be built-in without each task configuring it?

**Comment by helfi92** [comment]
> Shouldn’t "cancel" be built-in without each task configuring it? Like "rerun" seems to be.

Agreed.

**Comment by helfi92** [comment]
@aryamanpuri Let me know if you had questions.

**Comment by lissyx** [comment]
> Retrigger would be nice too.

I filed the same :) https://github.com/taskcluster/taskcluster/issues/1892

**Comment by aryamanpuri** [comment]
@helfi92 Can you help me with the onclick function of the cancel button.  The remaining buttons for tasks are " disabled: actionLoading" .

**Comment by helfi92** [comment]
@aryamanpuri Here's one way to add the new cancel button: https://github.com/taskcluster/taskcluster/compare/master...helfi92:fix-cancel-task?expand=1

**Comment by aryamanpuri** [comment]
@helfi92 There is no action on the click of buttons in this  link . https://community-tc.services.mozilla.com/tasks/KdwFUTxUTiWiHoRDBYhEmA/runs/0 . So the task performed by them is still active .

**Comment by helfi92** [comment]
I'm not sure I understand the question. Can you elaborate, please?

**Comment by aryamanpuri** [comment]
On this link https://community-tc.services.mozilla.com/tasks/KdwFUTxUTiWiHoRDBYhEmA/runs/0 , All the icons/buttons are still active or not? That is these icons are static (there is no action on clicking them).

**Comment by helfi92** [comment]
If the buttons are disabled, there should be a tooltip explaining why. If you see "(Auth Required)", it means you need to login first to use these buttons.

**Comment by aryamanpuri** [comment]
@helfi92  My bad .

**Comment by helfi92** [comment]
> Retrigger would be nice too.

https://github.com/taskcluster/taskcluster/pull/1893

**Comment by helfi92** [comment]
@aryamanpuri I see that you opened a pull request then closed it. Let me know when you want me to review a pull-request.

**Comment by helfi92** [comment]
@aryamanpuri How is it going? :-)

**Comment by helfi92** [comment]
@aryamanpuri I guess I can create a pull-request from my earlier comment https://github.com/taskcluster/taskcluster/issues/1875#issuecomment-549806424.
