### ISSUE TITLE
[UI] Update eslint to v6

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1878]
We use eslint v6 throughout the repo but use v5 in `ui`. We previously tried to upgrade eslint to v6 but for some reason, some pages in the docs site stopped working and so we had to revert the change. See https://github.com/taskcluster/taskcluster/issues/1842 for more information.

After updating eslint to v6, we should test that `http://localhost:5080/docs/reference/platform/queue/api` still works.

**Comment by ededals** [comment]
I would like to work on this.

**Comment by helfi92** [comment]
How is it going @ededals? :-)

**Comment by Manish-Giri** [comment]
I'd be interested to work on this, if it is still open.

**Comment by helfi92** [comment]
@Manish-Giri I just assigned you to a different issue. Let's do one at a time :)

**Comment by aryamanpuri** [comment]
@helfi92 Can I take this issue ?

**Comment by ededals** [comment]
Hey @aryamanpuri  what I found out is that there is some conflict in mdx package. At least the MDX component is the one that is throwing the error. Hope this helps.

**Comment by aryamanpuri** [comment]
@helfi92 On "npm i eslint" eslint upgraded to "^5.16.0". Do I have completely remove the package and then reinstall it to get v6 ?

**Comment by helfi92** [comment]
We use `yarn`, not `npm` to handle dependencies.

```
yarn add eslint
```

**Comment by aryamanpuri** [comment]
@helfi92  http://localhost:5080/docs/reference/platform/queue/api , queue/exhanges ,auth/api and api/exhanges are also not working. 
But how does Eslint cause a faliure at the runtime , which is a dependency

**Comment by helfi92** [comment]
Updating eslint to v6 [updates](https://github.com/taskcluster/taskcluster/pull/1863/files#diff-41c7b0973853207d6085c8df75e6dc50R1629) acorn-jsx which for some reason seems to break the docs site. You can try to figure out why that specific update breaks the site and whether there's anything we can do from our end.

**Comment by aryamanpuri** [comment]
@helfi92 From the console error I have changed "CollapseProps" to "collapseprops" in entry.jsx .
 I doubt at the following code in /api and /exchanges
 _const { serviceName, apiVersion } = this.props;
    const { ref, version } = findRefDoc({
      type: 'api',
      serviceName,
      apiVersion,
    }); ._
What are your thoughts on that ?
Because the rest code looks fine .

**Comment by aryamanpuri** [comment]
>  what I found out is that there is some conflict in mdx package. At least the MDX component is the one that is throwing the error. 

I am not sure about that because in the _/logs_ it is working properly, whereas it is throwing an error on the _/api and /exchange_

**Comment by helfi92** [comment]
What does the error say?

**Comment by aryamanpuri** [comment]
@helfi92 
WARNING in ./docs/manual/deploying/github.mdx
Module build failed (from ./node_modules/mdx-loader/index.js):
SyntaxError: unknown: Expected corresponding JSX closing tag for <deployment-name> (13:97)

Same for login-strategies.mdx

**Comment by djmitche** [comment]
I think @helfi92 fixed that yesterday, if you want to pull the latest from master.

**Comment by aryamanpuri** [comment]
@djmitche He has fixed the bug of <deployement> in #2102  .
But I am talking about this issue .
Looks like problem in the mdx packge

**Comment by aryamanpuri** [comment]
@helfi92 Your views on the error ?

**Comment by helfi92** [comment]
The error seems to say that there's a syntax error of an unexpected token. Did you try finding the token it is complaining about?

**Comment by aryamanpuri** [comment]
@helfi92 It is not specific about the error?
