### ISSUE TITLE
[UI] Can't copy artifact links from index browser

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#1879]
**Describe the bug**

Users often use the index browser to find an artifact, and then want to use that artifact elsewhere such as in a `curl` command.  They need a link that is pointing to `<rootUrl>/api/index`.

**To Reproduce**

1. Go to https://community-tc.services.mozilla.com/tasks/index/project.deepspeech.tensorflow.pip.r1.14.e77504ac6b941fd2af495b49a0bcd56f25ca0e1e/win
2. Try to copy a link to one of the artifacts.. you can't!

**Expected behavior**
You can!  Ideally through the normal right-click-copy-link, but as a backup through clicking a "copy" icon.

Note that the copied link should be of the form `<rootUrl>/api/index`, *without* following the redirects that URL returns.

**Comment by katherine95** [comment]
I would like to work on this one. @djmitche

**Comment by helfi92** [comment]
It has been done in https://github.com/taskcluster/taskcluster/pull/1880.
