### ISSUE TITLE
Task name is mangled in task view page title

### ISSUE THREAD

**Issue by SimonSapin** [taskcluster/taskcluster#1881]
In https://community-tc.services.mozilla.com/tasks/W3MxM2o_Tw24Nz7oM8LtLw we see 

> Servo: macOS x64: WPT chunk 6 / 6 + extra

(which is correct), and above that and in the tab’s title:

> Servo Mac Os X64 Wpt Chunk 6 6 Extra

Similarly in https://community-tc.services.mozilla.com/tasks/UxQR1tHSRN6imKedMGQGsQ/

> Servo: Android ARMv7: Dev build

… becomes:

> Servo Android Ar Mv7 Dev Build

I would be nice if we could disable this mangling.

**Comment by naima-shaikh** [comment]
@SimonSapin  May i get this issue ? :)

**Comment by naima-shaikh** [comment]
@helfi92  Thank you :)

**Comment by helfi92** [comment]
You'll want to use https://github.com/taskcluster/taskcluster/blob/08a316b1111cab297910034ca7f42c75a05d087a/ui/src/components/Dashboard/index.jsx#L198-L201

**Comment by naima-shaikh** [comment]
@helfi92   I started looking into the issue and saw we have this logic "const pageTitle = disableTitleFormatting ? title : makeTitle(title);" and when we take the title "test-linux64/debug-mochitest-e10s-15" and format it, it converts to "Test Linux64 Debug Mochitest E10s 15". My question is should I not format the Task title in the header or update the formatting so it more closely relates to the unformatted title?

**Comment by helfi92** [comment]
Correct. We should not format the task title and instead use the  `disableTitleFormatting` prop.
