### ISSUE TITLE
[UI] Choose more appropriate "create task" icon

### ISSUE THREAD

**Issue by imbstack** [taskcluster/taskcluster#1884]
**Describe the bug**
The "create task" button currently uses the floppy disk save icon. While this is somewhat appropriate, it doesn't really feel right for creating a task. I think (although others can disagree with me) that something with the feeling of "starting", "running", "go", "schedule", etc would make sense.

If my spelunking of the issues is correct, https://materialdesignicons.com is where our icons come from. Does this issue and that link make senes, @helfi92? If this is frivilous feel free to close :laughing: 

**To Reproduce**

1. Go to https://community-tc.services.mozilla.com/tasks/create
2. Observe the green floppy disk circle in the lower right

**Screenshots**
![image](https://user-images.githubusercontent.com/127521/68171608-4fdaeb80-ff29-11e9-874b-4c83294f4e05.png)

**Comment by vishakhanihore** [comment]
@imbstack Can I please work on this issue ?

**Comment by helfi92** [comment]
@imbstack This used to be a plus icon but changed to a diskette icon for better consistency/accessibility. Let me know if you disagree with the thread in https://github.com/taskcluster/taskcluster/issues/867. Happy to discuss.

**Comment by imbstack** [comment]
Let's wait for @owlishDeveloper to be back and we can discuss the diskette vs plus icon

**Comment by vishakhanihore** [comment]
Cool!

**Comment by vishakhanihore** [comment]
@owlishDeveloper ?

**Comment by imbstack** [comment]
Looks like we've decided to stick with the diskette. Thanks for the good work on this, @vishakhanihore sorry it didn't end up getting used. That was my bad.
