### ISSUE TITLE
[UI] Unable to perform rerun on mobile

### ISSUE THREAD

**Issue by lissyx** [taskcluster/taskcluster#1887]
**Describe the bug**
Trying to re-run a task from a mobile browser (Fennec Nightly) does not work

**To Reproduce**

0. Ensure you are signed in
1. Go to a failed task
2. Tap on the menu in the bottom right
3. Tap "Rerun"

**Expected behavior**
The modal dialog to confirm rerun is quickly visible but then disappears

**Screenshots**
Unable to capture screenshots, this is too quick.

**Platform (please complete the following information):**

 - OS: Android 9
 - Browser if applicable [e.g. firefox, safari]: Fennec
 - Version if applicable [e.g. 57]: latest nightly

**Additional context**
No problem on Firefox Nightly

**Comment by helfi92** [comment]
Weird. I can't replicate on my ios device. Let's test again after https://github.com/taskcluster/taskcluster/pull/1729 is merged. The material-ui upgrade may fix the issue.

**Comment by lissyx** [comment]
> Weird. I can't replicate on my ios device. Let's test again after #1729 is merged. The material-ui upgrade may fix the issue.

Yeah, reuben tested at lunchtime, it was working on his apple device. Mine is Xperia XZ2 Compact, "smaller" screen.

**Comment by djmitche** [comment]
Confirmed in Firefox Preview on Android.  But yeah, let's wait for #1729.

**Comment by djmitche** [comment]
@lissyx can you still reproduce?  #1729 is deployed now.

**Comment by lissyx** [comment]
> @lissyx can you still reproduce? #1729 is deployed now.

It's been fixed for a while, I even totally forgot about that :).
