### ISSUE TITLE
Form labels for check boxes might be misbehaving

### ISSUE THREAD

**Issue by rbrishabh** [taskcluster/taskcluster#1889]
**Describe the bug**
For example, in [taskcluster-ui.herokuapp.com/quickstart](taskcluster-ui.herokuapp.com/quickstart), clicking on checkboxes focuses the form label "This Task Should Run On" at irregular times.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22501334/68187872-d6490900-ffcd-11e9-9ac3-49325073260e.gif)

1. Go to [taskcluster-ui.herokuapp.com/quickstart](taskcluster-ui.herokuapp.com/quickstart),
2. Scroll down to 'This Task Should Run On'
3. Click on random checkboxes

**Expected behavior**
Form label doesn't change focus like this for checkboxes.

**Currently**
Form label keeps changing irregularly.

**Additional context**
The same actually does happen for Material UI Checkboxes and their labels as well. (https://material-ui.com/components/checkboxes/)
However, a simple fix would be to add global CSS to not let the label become focused on selecting a checkbox.

What do you think @helfi92.  I would like to make a PR for this if you think this is an issue!

Thanks!

**Comment by helfi92** [comment]
Hm, if this is a material-ui bug, maybe we should a raise an issue upstream in material-ui repo. Is there an issue already open for this?

**Comment by rbrishabh** [comment]
I don't think it's present there. I will create an issue there as well. Anyhow, would you like me to create a PR to fix this one? @helfi92

**Comment by helfi92** [comment]
> Anyhow, would you like me to create a PR to fix this one? @helfi92

Not at the moment. Let's wait to hear back from material-ui folks first. Also, I noticed that this issue is only on Chrome, not Firefox.

**Comment by helfi92** [comment]
You can post a link to the issue here if that helps.

**Comment by rbrishabh** [comment]
https://github.com/mui-org/material-ui/issues/18210

**Comment by helfi92** [comment]
It looks like material-ui won't be fixing this. Closing this as a won't fix.
