### ISSUE TITLE
Browser session expiry is too aggressive

### ISSUE THREAD

**Issue by SimonSapin** [taskcluster/taskcluster#1890]
**Describe the bug**

I regularly work with https://community-tc.services.mozilla.com lately, and often needs to click the "Sign in with GitHub" button again and again.

**To Reproduce**

1. Navigate to https://community-tc.services.mozilla.com/profile
2. If already signed in, click on "Sign out" in the top right menu
3. Sign (back) in with GitHub
4. See that the profile page says your client IDs "Expires in 14 minutes"

Now it’s not actually every 14 or 15 minutes that I need to click the button again, so it looks like there is something (I assume some JavaScript in the browser) that auto-renews this client ID. I haven’t kept track exactly, but it’s possible that the session actually expires (at least) every time I’ve put my laptop to sleep for more than a few minutes, such that the auto-renew request cannot run.

Sometimes this happen while I’m making some changes to something editable. Only when it’s time to save those changes do I realize that I’m signed out. Signing in reloads the page and looses my changes.

**Expected behavior**

Being able to go for longer (a week seems reasonable?) without busywork of clicking on the "Sign in" button again.

Or is there a point to clientID expiry being so aggressive?

**Comment by Archaeopteryx** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1515758

**Comment by helfi92** [comment]
@SimonSapin Are you still being logged out every 15 minutes?

**Comment by SimonSapin** [comment]
No. I am still logged out occasionally, but much less frequently now. What changed?

**Comment by helfi92** [comment]
I don't remember what changed exactly but I think it was an issue with the renewal not working due to CORS issues on the new site. Glad to hear that it's working again.
