### ISSUE TITLE
[UI] No retrigger button

### ISSUE THREAD

**Issue by lissyx** [taskcluster/taskcluster#1892]
**Describe the bug**
Previous TC would allow to rerun or retrigger. Current Community TC only allows for rerun.

**Expected behavior**
I want to be able to rerun or retrigger.

**Comment by lissyx** [comment]
When will this get deployed ? I really need it right now ...

**Comment by helfi92** [comment]
It will be deployed on the next deployment.

> I really need it right now ...

@djmitche Any chance we could deploy today?
