### ISSUE TITLE
`taskcluster-cli signin` fails to create clientId

### ISSUE THREAD

**Issue by lissyx** [taskcluster/taskcluster#1895]
STR:

1. Ensure `taskcluster-cli` recent (v22.0)
2. `TASKCLUSTER_ROOT_URL=https://community-tc.services.mozilla.com taskcluster-cli signin`
3. Browser open, clientId creation UI is here
4. `scopes` is filed with `*`
5. Click `create`

Expected:
ClientId is created

Actual:
Error:
```
Client ID github/1645737|lissyx does not have sufficient scopes and is missing the following scopes:

*

This request requires the client to satisfy the following scope expression:
{
  "AllOf": [
    "auth:create-client:github/1645737|lissyx/cli-TnrMJq",
    "*"
  ]
}
```

**Comment by djmitche** [comment]
I think the missing bit is that the `scope[]` args should be intersected with the user's scopes to generate the set of scopes added to the client.

**Comment by helfi92** [comment]
Yep.

**Comment by lissyx** [comment]
@helfi92 It's still not working. Does this requires a new release of `taskcluster-cli` ? New deployment of the web app ?

**Comment by helfi92** [comment]
It requires a new deployment of the web app.
