### ISSUE TITLE
[UI] include reasons "above the fold" in task runs

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#1900]
**Describe the bug**

The status of each run is shown at the top (and without clicking "More..."), but that information is incomplete without the reason indication -- things like "claim-expired" for example.  Users often miss that information because it is hidden behind "More...".

I propose moving all three of those "pills" onto the same line of the run, at the top.

![image](https://user-images.githubusercontent.com/28673/68231411-00e49300-ffc9-11e9-83c8-dff3839084fc.png)

**Comment by km-js** [comment]
I would like to work on this.

**Comment by helfi92** [comment]
Be back in a bit, but I would like to ask questions & get clarifications on this proposal.

**Comment by vishakhanihore** [comment]
@djmitche What about the mobile view, The current screen is compatible with the mobile view but I don't think making them inline would retain such consistency?

**Comment by djmitche** [comment]
If they stacked in that view, that'd be OK -- or just always stack them.  I think this information is a little more important than the scheduled/started/resolved times, so perhaps those could be moved below the fold?

**Comment by helfi92** [comment]
Looks like "Reason Resolved" is mainly useful when the task state is an exception to help users understand the reason. I'm unsure, however, whether "Reason Created" is something users look at often when inspecting a task.

Here's what I would like to propose, but feel free to disagree:

<img width="1442" alt="Screen Shot 2019-11-05 at 5 04 08 PM" src="https://user-images.githubusercontent.com/3766511/68250246-83337e00-ffee-11e9-9cc2-1f2e5095afae.png">

Main changes:

1. Include Reason Resolved above the fold but keep Reason Created below the fold.
2. The label for Reason Resolved and Reason Created is set to always be the default grey color even when the label says "COMPLETED" or "FAILED". This will make sure we don't always grab the user's attention when most people only care about the task run status.

@djmitche Thoughts?

**Comment by djmitche** [comment]
It's better, but I'm not sure why that's buried at the bottom?  It feels like

"Hey, your task failed

The weather is nice today

How about those Bills?  Did you see the game?

I was thinking of heading around the corner for lunch, you want to come?

Oh, the reason your task failed is .."

**Comment by helfi92** [comment]
Haha

> but I'm not sure why that's buried at the bottom?

I just thought Having "Resolved" then "Reason Resolved" sat nicely. We can definitely put it higher, perhaps after "Artifacts".

@vishakhanihore were you interested in tackling this issue?

**Comment by vishakhanihore** [comment]
Yes!

**Comment by vishakhanihore** [comment]
> It's better, but I'm not sure why that's buried at the bottom? It feels like
> 
> "Hey, your task failed
> 
> The weather is nice today
> 
> How about those Bills? Did you see the game?
> 
> I was thinking of heading around the corner for lunch, you want to come?
> 
> Oh, the reason your task failed is .."

That was savage 😆

**Comment by djmitche** [comment]
I was going for "funny" not "savage" :)
