### ISSUE TITLE
Log files are not scrollable horizontally on mobile

### ISSUE THREAD

**Issue by SimonSapin** [taskcluster/taskcluster#1903]
**Describe the bug**

The end of long lines in log files is impossible to see in a mobile browser.

**To Reproduce**

1. In Firefox for Android (or Chrome Android, or Firefox Preview, or Firefox Focus), navigate to https://community-tc.services.mozilla.com/tasks/VUtnBHlyTNuvCUBupdiaeA/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FVUtnBHlyTNuvCUBupdiaeA%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log
2. Try panning and zooming around the content
3. See that lines are not wrapped, and horizontal scrolling is disabled. Zooming in works, but zooming out beyond the initial zoom level is also disabled. As a result, some of the content is impossible to see. (Zooming out is not a good solution as text quickly becomes too small to read comfortably, but it might have been a way to see some more of the content.)

**Expected behavior**

It is possible to scroll / pan in both direction, in order to see all of the content including long lines.

Alternatively, long lines are forcibly wrapped. (Wrapping on spaces is not enough: it’s not rare for long files to contain more than one screen worth of line without a space, for example as an URL.)

**Screenshots**

<img src=https://user-images.githubusercontent.com/291359/68253873-59e41380-0029-11ea-8d6d-394f2c6cb23a.jpeg width=50%>

**Platform (please complete the following information):**

 - OS: Android
 - Browser: all tested

**Comment by naima-shaikh** [comment]
@SimonSapin  May i take this one please ?

**Comment by helfi92** [comment]
This is fixed in the next deployment of Taskcluster.
