### ISSUE TITLE
URLs of log viewing pages are large and redundant

### ISSUE THREAD

**Issue by SimonSapin** [taskcluster/taskcluster#1904]
**Describe the bug**

It would be nice if those URLs would be shorter

**To Reproduce**

1. Go to https://community-tc.services.mozilla.com/tasks/VUtnBHlyTNuvCUBupdiaeA/runs/0
2. Click on "View live log"
3. See that the browser’s URL bar now contains https://community-tc.services.mozilla.com/tasks/VUtnBHlyTNuvCUBupdiaeA/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FVUtnBHlyTNuvCUBupdiaeA%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log

**Expected behavior**

It seems that the same page could be available some address like https://community-tc.services.mozilla.com/tasks/VUtnBHlyTNuvCUBupdiaeA/runs/0/logs/public/logs/live.log without any loss of information or functionality. This would be nicer when copy/pasting such URLs in chat or into a bug report.

**Comment by naima-shaikh** [comment]
@SimonSapin  May i get this issue ?

**Comment by djmitche** [comment]
Simon just filed the issue, and doesn't control who works on it :)

That said, please do have a look!

**Comment by naima-shaikh** [comment]
@djmitche  Oh sorry i forget about it . And thanks for assigning it to me :)

**Comment by naima-shk** [comment]
@helfi92  @djmitche @SimonSapin 
```
{
    component: TaskLog,
    path: ${path}/:taskId/runs/:runId/logs/:logUrl,
  }
```
Is the goal of this issue to remove/format the logUrl at the end of the TaskLog route to make it easier to read and if so, how it will we make it unique for each logUrl? Sorry, I'm not familiar with the specifics for each route parameter.

**Comment by SimonSapin** [comment]
Instead of a full `:logUrl`, could we have a (relative) `:artifactFilename`? Since a task ID and a run ID are also provided separately, that should be enough to find a unique log file.

**Comment by helfi92** [comment]
Yes, that's definitely possible. It would add an extra request but I think that's okay. @naima-shk Let me know if you had questions.

**Comment by naima-shk** [comment]
@helfi92  After debugging more I see there is function to generate url that redirects to the logs called [getArtifactUrl](https://github.com/taskcluster/taskcluster/blob/bee9a224fd150ce320966b2d7001214b43c3c11a/ui/src/components/TaskRunsCard/index.jsx#L153). I change the route to use `:artifactFileName` but when we get url we are taking log url and encoding it using `encodeURIComponent` and attaching to end of url. My question is what part of `this.getCurrentRun()` data object do we use to replace encoded url? I don't see `artifactFileName` in `getCurrentRun` object. Also, what extra request do we need to make?

**Comment by naima-shk** [comment]
@helfi92 After debugging more I see there is function to generate url that redirects to the logs called getArtifactUrl. I change the route to use :artifactFileName but when we get url we are taking log url and encoding it using encodeURIComponent and attaching to end of url. My question is what part of this.getCurrentRun() data object do we use to replace encoded url? I don't see artifactFileName in getCurrentRun object. Also, what extra request do we need to make?

**Comment by SimonSapin** [comment]
Oh and also (sorry I didn’t mention this earlier), I think it’s important that existing URLs keep working. Maybe add a new route (with `/log/` instead of `/logs/` or something) instead of modifying the existing one?

**Comment by naima-shk** [comment]
> @helfi92 After debugging more I see there is function to generate url that redirects to the logs called [getArtifactUrl](https://github.com/taskcluster/taskcluster/blob/bee9a224fd150ce320966b2d7001214b43c3c11a/ui/src/components/TaskRunsCard/index.jsx#L153). I change the route to use `:artifactFileName` but when we get url we are taking log url and encoding it using `encodeURIComponent` and attaching to end of url. My question is what part of `this.getCurrentRun()` data object do we use to replace encoded url? I don't see `artifactFileName` in `getCurrentRun` object. Also, what extra request do we need to make?

@helfi92 I am looking for your reply  since last  5  days on this comment  .

**Comment by naima-shk** [comment]
> @helfi92 After debugging more I see there is function to generate url that redirects to the logs called [getArtifactUrl](https://github.com/taskcluster/taskcluster/blob/bee9a224fd150ce320966b2d7001214b43c3c11a/ui/src/components/TaskRunsCard/index.jsx#L153). I change the route to use `:artifactFileName` but when we get url we are taking log url and encoding it using `encodeURIComponent` and attaching to end of url. My question is what part of `this.getCurrentRun()` data object do we use to replace encoded url? I don't see `artifactFileName` in `getCurrentRun` object. Also, what extra request do we need to make?

@helfi92  Can i get a reply please ?

**Comment by helfi92** [comment]
The URL should have the log name. For example, navigating to https://community-tc.services.mozilla.com/tasks/VUtnBHlyTNuvCUBupdiaeA/runs/0 then clicking on "Artifacts" then on "public/logs/live.log" should navigate to https://community-tc.services.mozilla.com/tasks/VUtnBHlyTNuvCUBupdiaeA/runs/0/logs/public%2Flogs%2Flive.log

To have access to the log name:

![Screen Shot 2019-11-18 at 11 29 27 AM](https://user-images.githubusercontent.com/3766511/69070900-01ccea00-09f7-11ea-99f4-2375a521ba42.png)

Once you've successfully navigated to the log view, you would need to find a way to extract the log URL given the task ID (e.g., `VUtnBHlyTNuvCUBupdiaeA`) , run ID (e.g., `0`), and the  log name (e.g., `public/logs/live.log`).

**Comment by naima-shk** [comment]
@helfi92  Thanks !

**Comment by djmitche** [comment]
More updated version of this bug is #3878
