### ISSUE TITLE
[UI] long enough title makes it hard to see the status on mobile

### ISSUE THREAD

**Issue by lissyx** [taskcluster/taskcluster#1908]
![Screenshot_20191106-094249](https://user-images.githubusercontent.com/1645737/68294758-35bc1d00-0091-11ea-9d76-4cbc48e57bdc.png)

As you can see, one has to constantly scroll to see status.

At first, it might be good if we could avoid wasting so much space on sides, especially on mobile. The "link" item also wastes space on the same direction.

**Comment by helfi92** [comment]
> As you can see, one has to constantly scroll to see status.

Agreed. We should definitely improve the experience. Since we only have two columns, we could allocate up to 50% of the screen width to each column.

**Comment by kellim** [comment]
@helfi92 Can I work on this one please?
