### ISSUE TITLE
[UI] Log display page title and header should include task name

### ISSUE THREAD

**Issue by lissyx** [taskcluster/taskcluster#1909]
**Describe the bug**
There is no reminder of the task name being inspected when displaying a log page.

**To Reproduce**

1. Go to a task
2. Click on log artifact

**Expected behavior**
I should not have to go back and forth just to remember **what** log I am viewing

**Comment by kellim** [comment]
@helfi92 can I work on this one please? 
And would this be an example of a page with the issue? 
https://taskcluster-ui.herokuapp.com/tasks/Hp78eA-4RxWoDir4i8CDFA/runs/0/logs/https%3A%2F%2Fqueue.taskcluster.net%2Fv1%2Ftask%2FHp78eA-4RxWoDir4i8CDFA%2Fruns%2F0%2Fartifacts%2Fpublic%2Fchain-of-trust.json

**Comment by helfi92** [comment]
>  And would this be an example of a page with the issue?

Yep!
