### ISSUE TITLE
[docs]: Discrepancies in Heading Title for Docs .

### ISSUE THREAD

**Issue by vishakhanihore** [taskcluster/taskcluster#1933]
**Describe the bug**

Currently, Some of the documentation pages have `Heading Title` and some don't have which makes their UI look uglier.

**For Example**

**Workers** has a heading
<img width="1020" alt="Screenshot 2019-11-09 at 2 11 32 PM" src="https://user-images.githubusercontent.com/54327666/68525747-e5e08e80-02fa-11ea-8878-705d97682fc4.png">
**Queue** doesn't have any
<img width="1068" alt="Screenshot 2019-11-09 at 2 11 38 PM" src="https://user-images.githubusercontent.com/54327666/68525754-eda03300-02fa-11ea-98a1-7a9ddb7799f2.png">

**Expected**
There should be no such discrepancy and pages should have heading as possible

**Comment by vishakhanihore** [comment]
@djmitche @helfi92 Does this seems legit ?

**Comment by helfi92** [comment]
If a page contains a subheader (i.e., h2, h3, h4, h5, h6), then it needs an `<h1>` header at the top. If a page contains no headers, that's fine since the app bar will contain the title of the page. That being said, I think the current representation seems okay to me.

**Comment by vishakhanihore** [comment]
> If a doc page contains a subheader (i.e., h2, h3, h4, h5, h6), then it needs an `<h1>` header at the top. If a page contains no headers, that's fine since the app bar will contain the title of the page. That being said, I think the current representation seems okay to me.

Perfect!
