### ISSUE TITLE
[UI]: GitHub Quickstart is not mobile friendly

### ISSUE THREAD

**Issue by vishakhanihore** [taskcluster/taskcluster#1934]
**Describe the bug**

Fields and Descriptions in GitHub Quickstart is not responsiveness.

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to 'http://127.0.0.1:5080/quickstart'
2. Choose <iPhone 8 device
3. See error

**Expected behaviour**

Make the page responsive for all the mobile device.

**Screenshots**

<img width="376" alt="Screenshot 2019-11-09 at 5 16 51 PM" src="https://user-images.githubusercontent.com/54327666/68528140-cb1b1380-0314-11ea-9d79-97248a07da19.png">

**See the Label Cutout and Also see the extra space in `Description` and the `Field`**

**Comment by vishakhanihore** [comment]
@helfi92 @djmitche May I get assigned 😄 ?

**Comment by helfi92** [comment]
This view is being revamped in https://github.com/taskcluster/taskcluster/pull/1449.
> > See the Label Cutout

We can probably just rename the placeholders to "Org Name" and "Repo Name". Feel free to send a PR :)

> and Also see the extra space in Description and the Field

The description field is a text area component that takes allows multiple lines as input. The space is expected.

**Comment by vishakhanihore** [comment]
Or we can placeholders inline in mobile view?

**Comment by helfi92** [comment]
> Or we can placeholders inline in mobile view?

There's a third icon that has a relationship with both inputs. We would need to always have it beside those two inputs.

If we put them inline, then the icon would need on the right centered between the two inputs. Changing the repo placeholder on the other hand makes more sense to me since that doesn't add any code complexity.
