### ISSUE TITLE
Double <iframe> nesting on interactive SSH page

### ISSUE THREAD

**Issue by SimonSapin** [taskcluster/taskcluster#1935]
**Describe the bug**

Pages whose URL start with https://community-tc.services.mozilla.com/shell/ show the usual bar at the top with a hamburger menu, page title, theme toggle, docs link, and auth menu. As expected so far.

The body of the page is an `<iframe>` element. In that iframe is another HTML document that contains the same top bar *again*, and another `<iframe>` element. Only that second, nested element contains the shell. See screenshot below.

**To Reproduce**

1. Find a task running on Linux, for example https://community-tc.services.mozilla.com/tasks/SICvgC4jR7ekIOIkSs4D_w
2. In the bottom right menu, click on "Create with SSH / VNC"
3. In the page that shows up, under "Select a Session", click "Shell"
4. In the next page, observe the double header describe above and screenshotted below.

**Expected behavior**

Shell shows up with a single header. (Most likely,) only one `<iframe>` element is involved.

**Screenshots**

![image](https://user-images.githubusercontent.com/291359/68528249-6221a480-02f0-11ea-94db-bb1815cf80fa.png)

**Platform (please complete the following information):**

 - OS: Linux
 - Browser: Firefox
 - Version: 70.0.1

**Comment by vishakhanihore** [comment]
Duplicate of https://github.com/taskcluster/taskcluster/issues/217

**Comment by vishakhanihore** [comment]
Also, refer to https://github.com/taskcluster/taskcluster/issues/217#issuecomment-548300388

Following is a bug in `chromium's/h-term`.

**Comment by SimonSapin** [comment]
Thanks! Closing in favor of #217.
