### ISSUE TITLE
link to worker from task details links to lists of workers for worker pool because url misses worker pool id

### ISSUE THREAD

**Issue by Archaeopteryx** [taskcluster/taskcluster#1937]
1. Go to Treeherder https://treeherder.mozilla.org/#/jobs?repo=mozilla-central&resultStatus=success%2Ctestfailed%2Cbusted%2Cexception&classifiedState=unclassified&searchStr=windows%2Cbuild
2. Click on a running or finished task.
3. At the bottom left, click on the task id link next to `Task`.
4. On the right, click on "More...".
5. Click on the "Worker ID".
Expected result: Lists of tasks machine had run opened, e.g. https://firefox-ci-tc.services.mozilla.com/provisioners/gecko-3/worker-types/b-win2012/workers/aws/i-0c3220d23d8fbef92
Actual result: List of workers for that provisioner opened: https://firefox-ci-tc.services.mozilla.com/provisioners/gecko-3/worker-types/b-win2012/workers/i-0c3220d23d8fbef92

The worker pool id `aws` is missing.

**Comment by djmitche** [comment]
This looks like a bug in URL generation in treeherder (the `aws` is the workerGroup).

**Comment by djmitche** [comment]
302'd to a treeherder issue

**Comment by djmitche** [comment]
Sorry, this is totally valid!  I misunderstood the STR.

That link needs a `${workerGroup}` in it.
