### ISSUE TITLE
Allow to copy worker id from task page

### ISSUE THREAD

**Issue by Archaeopteryx** [taskcluster/taskcluster#1945]
Currently the worker ID cannot be selected (and copied) from a task page like e.g. https://firefox-ci-tc.services.mozilla.com/tasks/Dw2UN8mfTwOwW1Dsv89Q7A

I frequently need it for SQL queries and work around that by inspecting the element and copying the test from the developer tools's inspector.

Please either allow to select the worker id text or add a button to copy it.

**Comment by helfi92** [comment]
I am able to select the worker id text:

![Screen Shot 2019-11-11 at 8 12 01 AM](https://user-images.githubusercontent.com/3766511/68589818-f4de5280-045a-11ea-9bfb-10c49dabdc13.png)

One trick that helps me copy text in a button is to start the text selection outside the button.

**Comment by aryamanpuri** [comment]
@helfi92 But that is not an ideal way I guess .
