### ISSUE TITLE
Provide a link to the build artifacts in taskcluster community web pages.

### ISSUE THREAD

**Issue by bluemarvin** [taskcluster/taskcluster#1949]
**Describe the bug**

The the previous version of taskcluster, it was possible to get a link to a page listing the build artifacts. However, after being moved to community taskcluster, the new web pages no longer provide a way to get a direct link to the build artifacts. I now have to provide a link to the task run page and provide instructions to click the little arrow to show the artifacts.

**To Reproduce**

1. Go to 'https://community-tc.services.mozilla.com/tasks/QW3amtG3SkK3Tp5lBSq_tg'

**Expected behavior**

There should be a way to either link to the build artifacts or the UI state should be saved in the URL so that when the artifact arrow is toggled the link reflects that. 
**Screenshots**

![Screenshot_2019-11-11 Firefox Reality For Android Build Master Update - Community-TC](https://user-images.githubusercontent.com/3066/68609519-535efd00-046a-11ea-8a0f-ace1e281a3a8.png)

**Platform (please complete the following information):**

 - OS: [e.g. windows] Probably not relevant but both linux and mac.
 - Browser if applicable [e.g. firefox, safari] Firefox
 - Version if applicable [e.g. 57] All

**Comment by helfi92** [comment]
Good idea. Clicking on "Artifacts" could add a hash to the url (e.g., https://community-tc.services.mozilla.com/tasks/QW3amtG3SkK3Tp5lBSq_tg#artifacts) and then clicking again (to close the panel) can remove it.

**Comment by vishakhanihore** [comment]
Can I @helfi92 ?

**Comment by helfi92** [comment]
@vishakhanihore Perhaps after https://github.com/taskcluster/taskcluster/issues/1389, https://github.com/taskcluster/taskcluster/pull/1932, https://github.com/taskcluster/taskcluster/pull/1845 are done?

**Comment by km-js** [comment]
Should I try this one?

**Comment by helfi92** [comment]
This will be available in the next deployment of Taskcluster.
