### ISSUE TITLE
[UI] Add "cancel" button to task view

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#1952]
**Describe the bug**
The Task view, e.g., https://community-tc.services.mozilla.com/tasks/BnTeGj9BRxymQP70fZgBjQ, should have a "Cancel" button in the spinner-thing in the lower right corner.

**To Reproduce**

1. Go to https://community-tc.services.mozilla.com/tasks/BnTeGj9BRxymQP70fZgBjQ
1. Hover over the vertical-dot thing in the lower right

**Expected behavior**
A cancel button

**Comment by aryamanpuri** [comment]
@djmitche  This bug is fixed in  #1910  by @helfi92 .

**Comment by lissyx** [comment]
> @djmitche This bug is fixed in #1910 by @helfi92 .

It's marked as fixed, but there is still no button. Was there no deployment since ?

**Comment by djmitche** [comment]
Looks like it's in 22.1.0, which is not yet deployed on community.  I'll get on that today.

**Comment by djmitche** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1595809

**Comment by lissyx** [comment]
> Looks like it's in 22.1.0, which is not yet deployed on community. I'll get on that today.

Thanks @djmitche, now we have it \o/
