### ISSUE TITLE
[UI] Rename Purge Cache to Purge Caches

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1953]
**To Reproduce**

1. Go to http://localhost:5080/
2. Open the menu drawer

![Screen Shot 2019-11-12 at 9 33 46 AM](https://user-images.githubusercontent.com/3766511/68680411-9e8f1380-052f-11ea-8ef8-24cfa4ddccf0.png)

**Actual behavior**

Clicking on Purge Cache takes the user to /purge-caches

**Expected behavior**
"Purge Cache" should be renamed to "Purge Caches"

![Screen Shot 2019-11-12 at 9 36 05 AM](https://user-images.githubusercontent.com/3766511/68680567-deee9180-052f-11ea-9a82-bb7792ae39eb.png)

**Comment by lailahgrant** [comment]
Thanks Sir, I modified  ``` ui/src/components/Dashboard/SidebarList.jsx```  to 
```
<SidebarListItem to="/purge-caches" icon={<BackupRestoreIcon />}>
          Purge Caches
        </SidebarListItem>
```

**Comment by lailahgrant** [comment]
I have made a pull request @helfi92 ..

**Comment by helfi92** [comment]
Where is it? I don't see it in https://github.com/taskcluster/taskcluster/pulls

**Comment by lailahgrant** [comment]
sorry sir, have you seen it??
seems I had forgotten something.

**Comment by helfi92** [comment]
@lailahgrant Were you able to figure out what was missing?

**Comment by lailahgrant** [comment]
@helfi92 , yes I did. 

Actually this was about the pull request. but I went past that & now I hope my ```commits and  the rebase commands``` worked.. :sweat:

**Comment by helfi92** [comment]
Resolved in https://github.com/taskcluster/taskcluster/commit/ab2fb8a17789ba40592c8ce82d93441cd4690989.
