### ISSUE TITLE
[UI] Form "save" button

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1961]
In the old UI, whenever a user wanted to edit a form, they had to click "Edit" first, perform their change, then click "Save". Clicking on "Edit" made it clear that they had to click on "Save" to finish the transaction.

In the new UI, the edit/view/create modes are done in a single view. In order to inform users to not forget to save their changes, we presently animate the save button whenever the form becomes "dirty" (i.e., changed). One problem is that we don't animate this button when the user is logged out. Consider the following scenario to understand the problem:

1. Navigate to https://firefox-ci-tc.services.mozilla.com and make sure you are logged out
2. Navigate to https://firefox-ci-tc.services.mozilla.com/hooks/hg-push/ash
3. Delete or add a schedule

**Expected:** The save button becomes enabled
**Actual:** The save button is disabled with a tooltip "Save Hook (Auth Required)". A user that is logged out will not receive the feedback that they need to save the hook

One promising option is to not disable the save button when the user is logged out so that changes to the hook will immediately animate the save button from a disabled state to the bright green color. We would still disable action buttons that require user authentications to avoid having to do an extra request.

Forms that will need this change:

* [x] ui/src/components/HookForm/index.jsx
* [x] ui/src/components/SecretForm/index.jsx
* [x] ui/src/components/ClientForm/index.jsx
* [x] ui/src/components/RoleForm/index.jsx
* [ ] ~ui/src/views/Quickstart/index.jsx~
* [x] Worker pool form

**Comment by mmbis** [comment]
Hey, can I help out with this?

**Comment by helfi92** [comment]
Go for it.

**Comment by helfi92** [comment]
How is it going @mmbis?

**Comment by mmbis** [comment]
Hey @helfi92, I was able to get the app setup with yarn and :link dependencies, but I'm not quite sure how to run the app locally.

**Comment by helfi92** [comment]
No need to link dependencies. Did you have a look at https://github.com/taskcluster/taskcluster/blob/master/dev-docs/development-process.md#hacking-on-the-ui by any chance?

**Comment by helfi92** [comment]
How is it going @mmbis?

**Comment by mmbis** [comment]
Just got it up and running in the browser. Will look at the bug tonight and into the weekend! Thanks for the help.

**Comment by helfi92** [comment]
Great to hear!

**Comment by mmbis** [comment]
Hey @helfi92, looks like removing the requiresAuth attribute for non-new hooks in the /HookForm index.jsx offers the desired functionality. Is the removal of this attribute sufficient or would you want something like another conditional Save Hook fragment button?

**Comment by helfi92** [comment]
> Is the removal of this attribute sufficient

Yeah, I believe that would be sufficient :)

**Comment by mmbis** [comment]
Good deal. Do you want me to add a save button to the quick-start view? Right now, there is no save button or requiresAuth attributes.

**Comment by helfi92** [comment]
No save button required to the quick-start view.

**Comment by mmbis** [comment]
Thanks for all the help with the app given my newb status @helfi92! I'll PR in the next few minutes. Let me know if there's anything incorrect or additional that I need to work on.

**Comment by mmbis** [comment]
Actually, I'm getting a 403 permission denied when attempting to push.

**Comment by helfi92** [comment]
> Actually, I'm getting a 403 permission denied when attempting to push.

You will need to create a fork of the repo first and then push to your fork.

**Comment by mmbis** [comment]
Thank you! PR is out there

**Comment by helfi92** [comment]
@aryamanpuri It looks like we're still missing the implementation in "ui/src/views/Quickstart/index.jsx".

**Comment by aryamanpuri** [comment]
@helfi92 oh misses it .

**Comment by helfi92** [comment]
> Should I make another pr or commit in the previous one

New PR. The previous one was already merged.

**Comment by aryamanpuri** [comment]
Okay

**Comment by aryamanpuri** [comment]
@helfi92 There is no feature of saving in the Quickstart, so I have to implement the whole save feature right.

**Comment by helfi92** [comment]
Oh, you're right. My bad.

**Comment by aryamanpuri** [comment]
And one more thing, the title of the page is `Git Hub Quickstart` 
Is it done intentionally?

**Comment by helfi92** [comment]
Good observation! That's a bug. We can use the Dashboard component `disableTitleFormatting` prop to fix this. Feel free to send a fix. Thanks!

**Comment by aryamanpuri** [comment]
@helfi92 okay

**Comment by aryamanpuri** [comment]
@helfi92 Can you add me to the contributors in README.md !

**Comment by aryamanpuri** [comment]
@helfi92 Can you add me to the contributors?

**Comment by helfi92** [comment]
@all-contributors please add @aryamanpuri for code.

**Comment by helfi92** [comment]
Definitely.

**Comment by aryamanpuri** [comment]
@helfi92 Looking forward to working more with this organization. Learned a lot from this project.

**Comment by helfi92** [comment]
Grateful for your help!
