### ISSUE TITLE
Insufficient scope modal is not scrollable

### ISSUE THREAD

**Issue by worldomonation** [taskcluster/taskcluster#1962]
**Describe the bug**

Insufficient scope modal that appears when user attempts to execute an action that they do not have permission for is not scrollable.

**To Reproduce**

1. Authenticate as a user with minimal scope.
2. Shrink the browser window such that browser window height is a small but usable number.
3. Search for Task ID RiKSwl_jTc26ldcyeSIMQQ
4. Using the overflow menu on bottom right, select 'Edit'
5. Click on the Create Task button on bottom right, in green.

**Expected behavior**

Red modal appears warning user of insufficient scope. 
User is expected to inspect the missing scopes, and file a bug on Bugzilla to request the scope.
In order to do so, user is expected to copy and paste the details of the error which may extend past the browser window.

**Screenshots**

**Platform (please complete the following information):**

 - OS: macosx1014
 - Browser: firefox
 - Version: 72.0a1

**Additional context**

This may occur with any other fullscreen modal that appears on page.

**Comment by worldomonation** [comment]
![Screen Shot 2019-11-12 at 17 19 10](https://user-images.githubusercontent.com/6549265/68724787-542e8680-0571-11ea-9ff6-5215bdb50d8f.png)

**Comment by helfi92** [comment]
I can replicate. Thanks for bringing this up!

**Comment by helfi92** [comment]
Should be fixed in the next deployment.
