### ISSUE TITLE
[client-shell] Making it easier to update taskcluster cli client 

### ISSUE THREAD

**Issue by srfraser** [taskcluster/taskcluster#1963]
Updating the `taskcluster` cli binary is currently a manual process, as is checking for updates. Adding a package to apt/homebrew/etc seems like overkill.  Perhaps it would be useful if there was an `update` sub-command that either:

1. Reported on whether a new version was available, displaying the download url for copy/paste
or
2. Downloaded the new version and copied it in place, if the installation location (os.Argv[0]?) is writable by the current user. 

The current client-shell version is at https://github.com/taskcluster/taskcluster/blob/master/clients/client-shell/cmds/version/version.go#L21 and could be compared to the tag_name returned from https://api.github.com/repos/taskcluster/taskcluster/releases/latest 

The `browser_download_url` is also listed under the assets at the above endpoint, or one could use https://github.com/taskcluster/taskcluster/releases/latest/download/taskcluster-(linux|darwin)-amd64

**Comment by DantrazTrev** [comment]
Is this issue open to work for?

**Comment by djmitche** [comment]
It is!

It's a bit exploratory -- probably a good place to start is to look at how similar CLI tools for cloud services update themselves.  I can think of a few examples: `travis`, `heroku`, `aws`, `gcloud`, `kubectl`, `az` (for Azure).  Ideally we'd have a way to update securely, so that users aren't at risk of installing and using a malicious binary!

**Comment by DantrazTrev** [comment]
Does this issue needs the update command to be created in CLIs other then shell?
I've completed the one with shell , using the first approach.

**Comment by DantrazTrev** [comment]
What level should the changelog be of?

**Comment by DantrazTrev** [comment]
I'm facing an issue that the check taskcluster-client-shell-1.12.13 is failing in the PR . Can you please help me with this?

**Comment by srfraser** [comment]
I've commented in the PR. I won't be able to look again until Monday, however. Thanks for working on this!

**Comment by DantrazTrev** [comment]
I've made the desired changes and ran the tests

**Comment by djmitche** [comment]
> Does this issue needs the update command to be created in CLIs other then shell?

Nope, just that one.
