### ISSUE TITLE
[UI] search in log view

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#1968]
STR:

1. Navigate to https://firefox-ci-tc.services.mozilla.com/tasks/bGO6bNT0RV6ztQn6mE66xQ/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FbGO6bNT0RV6ztQn6mE66xQ%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log

Tasks:
* Add a search input to the app bar similar to https://firefox-ci-tc.services.mozilla.com/tasks/bGO6bNT0RV6ztQn6mE66xQ/runs/0

<img width="296" alt="Screen Shot 2019-11-13 at 6 35 40 PM" src="https://user-images.githubusercontent.com/3766511/68813630-688f8380-0644-11ea-8791-e914c50d6260.png">

* Remove the "View Different Task" button that's in the speed dial component.

<img width="194" alt="Screen Shot 2019-11-13 at 5 47 55 PM" src="https://user-images.githubusercontent.com/3766511/68811103-d08e9b80-063d-11ea-973d-579c94543481.png">

**Comment by Shavindra** [comment]
@helfi92 just to be absolutely clear the search bar should be at the very top on the left hand of the light bulb?

i am happy to pick this up

**Comment by helfi92** [comment]
Yep, that’s correct. Go for it :)

**Comment by Shavindra** [comment]
@helfi92 Great :) I made a fork. but can't assign it to me though.

**Comment by helfi92** [comment]
That's fine for now.

**Comment by aryamanpuri** [comment]
@helfi92 Can I work on this  issue

**Comment by helfi92** [comment]
I believe @Shavindra is working on the issue.

**Comment by aryamanpuri** [comment]
@helfi92 Not a problem, but I have done half of the work .
Should I stop working on that?

**Comment by helfi92** [comment]
How is it going @Shavindra?

**Comment by Shavindra** [comment]
@helfi92 yes I am working on it. Looking at it I've noticed that search bar is part of this `react-lazylog` And it doesn't have a prop to take `searchKeyword`.

`repo https://github.com/mozilla-frontend-infra/react-lazylog/blob/5bafa6a115af6c2efd51012152fc6c0a29569e6f/src/components/LazyLog/index.jsx#L36.`

I will need to open a PR for that too. Any issues with that?

**Comment by helfi92** [comment]
No need to touch react-lazylog. The search in the log searches within a log but what we are trying to do is add an input to search to a completely different task. Clicking enter on that new search view should navigate the user to `/tasks/${taskId}` where the taskId is from the search input.
