### ISSUE TITLE
Workers list view is unusable for cloud worker pools

### ISSUE THREAD

**Issue by SimonSapin** [taskcluster/taskcluster#1972]
**Describe the bug**

The worker list view such as https://community-tc.services.mozilla.com/provisioners/proj-servo/worker-types/docker is not useful for pools managed by worker-manager.

**To Reproduce**

1. Go to https://community-tc.services.mozilla.com/provisioners/proj-servo/worker-types/docker. This pool has short-lived workers started on demand by worker-manager.
2. Try to find a currently-active or recently-active worker
3. This is hard or impossible because:
  * The list is flooded with workers that have been long stopped
  * The list is paginated, only showing a small number of workers per page. (Varies between 5 and 12 or so.)
  * The total number of pages is unknown
  * What workers end up on a given page appears to be arbitrary
  * Sorting only works within a page
  * The "Filter by" drop-down does not allow hiding workers that are stopped.

**Expected behavior**

There should exist a view (this one or something separate) that can answer useful questions about cloud-based worker pools. This could involve:

* Show more workers at a time. Pagination can be important to avoid overloading a system when showing very many entries, but it seems that actual issues would start around the thousands rather than the dozen.

* Show at least an estimate of the total number of entries

* Make sorting work on the overall list so that it influences what goes in what page, not just sort within an arbitrary current page

* Allow filtering out workers that are not running anymore. (Those with `state == "stopped"` in worker-manager’s `listWorkersForWorkerPool` API.)

**Comment by helfi92** [comment]
https://github.com/taskcluster/taskcluster/pull/1973 will increase the page size from ~15 to up to 1000. This should show all entries in the same page.

> 

Show at least an estimate of the total number of entries

**Comment by SimonSapin** [comment]
#1973 will improve the situation, thanks.

Are stopped workers removed entirely from that list at some point? How long does that usually take?

**Comment by helfi92** [comment]
> Allow filtering out workers that are not running anymore. (Those with state == "stopped" in worker-manager’s listWorkersForWorkerPool API.)

I don't think this view uses the worker-manager's listWorkersForWorkerPool API. Anything under `/provisioners` currently has the same stuff from the old site. A new Worker UI will be created in the near future. /cc @djmitche.
