### ISSUE TITLE
Hooks have limiting length

### ISSUE THREAD

**Issue by Callek** [taskcluster/taskcluster#1986]
https://github.com/taskcluster/taskcluster/blob/d740e32431941ce438de2060f3336272cb462bed/services/hooks/src/api.js#L16

I have a case where I was creating a hook as it would be defined if it was a `cron_target` for the android-components repo, and it was defined as `project-releng/cron-task-mozilla-mobile-android-components/geckoview-update-nightly`  [src](https://hg.mozilla.org/ci/ci-configuration/rev/7f48a015136d9f6c30bbf5a87ab2e0e88a80363e#l1.58)

This one is length 68... is `{1,64}` an actual limit here, or can we go larger?

**Comment by djmitche** [comment]
Basically, we need a limit, and one that allows us to embed this value comfortably in other things like scopes, and to fit in URLs, etc.  The idea with 64 was that it's enough to avoid having to artificially shorten things, but without inviting whole paragraphs.

The hookId `cron-task-mozilla-mobile-android-components/geckoview-update-nightly` is startng to feel like a paragraph :)

But, I'm basically committing the "slippery slope" logical fallacy.  We could probably raise this limit somewhat without running into other issues.  I think the major limiting factor is the space allowed by Azure, which is 256 characters in the storage emulator (and the overall table row size of 1MB).

**Comment by djmitche** [comment]
We could extend this further now -- these are stored in `text` columns in postgres that are of arbitrary size.

To start working on this bug, get your development environment set up, and then look at the JSON schemas in `services/hooks/schemas` that define the `hookGroupId` and `hookId` properties.  Those will need to be increased.

Let's pick 1000 characters as a nice, arbitrary limit there.

**Comment by pret3nti0u5** [comment]
Hey, I would like to work on this issue. If i understand correctly I'll have to increase the `maxLength` for `hookGroupId` and 'hookId` to 1000 in `services/hooks/schemas/constants.yml`. Please let me know. Thanks!

**Comment by djmitche** [comment]
That is correct.  It's all yours!

**Comment by pret3nti0u5** [comment]
Here's the [PR](https://github.com/taskcluster/taskcluster/pull/3329).
