### ISSUE TITLE
[UI] Add last worker claimTask date

### ISSUE THREAD

**Issue by lissyx** [taskcluster/taskcluster#1987]
On https://community-tc.services.mozilla.com/provisioners/proj-deepspeech/worker-types/ds-macos-light for example, we only know about latest task claimed / executed.

Sometime, workers dies (`generic-worker` runs out of space, laptop unplugged, VM crashed) and we only know after some timeout (seems to be 24h) and the worker disappears from the list.

Having a new column showing date of last successfull `claimTask()` (even one that returns no task, then) would help see that earlier.

**Comment by naima-shk** [comment]
It looks interesting ! 
can i try this one ?

**Comment by helfi92** [comment]
> Having a new column showing date of last successfull claimTask() (even one that returns no task, then) would help see that earlier.

That makes sense to me. We could add a "Last Claim" column. I don't think we currently expose this data so it will have to be added in the queue service first before we can do any UI changes.

**Comment by djmitche** [comment]
Dup #4355.
