### ISSUE TITLE
[UI]: Complete Logs are not readable

### ISSUE THREAD

**Issue by vishakhanihore** [taskcluster/taskcluster#1990]
There is no x-scrolling in logs, which results in half rendered logs and errors. It makes difficult to understand what is the error. 

#### Screenshot 
<img width="1424" alt="Screenshot 2019-11-15 at 9 39 36 PM" src="https://user-images.githubusercontent.com/54327666/68957634-72ee8080-07f0-11ea-8c82-222091944b66.png">

**Comment by vishakhanihore** [comment]
@djmitche Can I be assigned ?

**Comment by helfi92** [comment]
Do you have a link example where it doesn't work. https://firefox-ci-tc.services.mozilla.com/tasks/WzZiD99QRyqUhc9geCehYg/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FWzZiD99QRyqUhc9geCehYg%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log works for me:

![Screen Shot 2019-11-15 at 11 32 47 AM](https://user-images.githubusercontent.com/3766511/68959291-be2a7400-079b-11ea-9e30-5b2241b8aecb.png)

**Comment by vishakhanihore** [comment]
I am using safari and I am not able to scroll in x direction if logs are
extending screen view, same applies for mobile view too.
Screen Browser: Safari
Mobile Broser : Chrome/Brave

**Comment by vishakhanihore** [comment]
@helfi92 @djmitche ?

**Comment by helfi92** [comment]
Works for me on Chrome and Safari but fails to work on mobile. Sure, you can take a look.

**Comment by vishakhanihore** [comment]
No it does fail on safari and chrome, just make sure you have a line in log
which is greater than screen width. you wont be able to scroll on right to
see the complete error.

**Comment by helfi92** [comment]
This is how it looks for me on Chrome:

![Screen Shot 2019-11-15 at 1 58 14 PM](https://user-images.githubusercontent.com/3766511/68968200-0358a100-07b0-11ea-8c39-22a6f6d98424.png)

**Comment by vishakhanihore** [comment]
On safari navigate to `https://community-tc.services.mozilla.com/tasks/DYFUu2q_Q6GLFLQ02MYnjw/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FDYFUu2q_Q6GLFLQ02MYnjw%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log`
Try to squeeze window a little bit and then see some logs which gets cut from the window are not scrollable, mean you cant scroll window in x-direction to see the complete logs

**Comment by vishakhanihore** [comment]
I was going to send the PR @helfi92 😅. Anyway faster the resolve better is
it.
