### ISSUE TITLE
Any possibility of offering a CI Status badge for TaskCluster CI Integration 

### ISSUE THREAD

**Issue by vishakhanihore** [taskcluster/taskcluster#1993]
Can we have a badge for our CI to get shown in ReadMe and with every commit?

@helfi92 @djmitche How does this sound to you ?

**Comment by djmitche** [comment]
We have one :)

https://docs.taskcluster.net/docs/reference/integrations/github/api#badge

**Comment by vishakhanihore** [comment]
Why aren't we using in our ReadME ? 🤔

**Comment by djmitche** [comment]
It doesn't work very well with the Checks API, which Taskcluster uses.  When the Checks API is finished, we'll add it back.
