### ISSUE TITLE
Long URL in taskcluster log gets truncated horizontally in web UI

### ISSUE THREAD

**Issue by rpappalax** [taskcluster/taskcluster#1997]
**Describe the bug**

Our taskcluster logs for fenix jobs are being truncated horizontally in the web UI.  Most of us are experiencing this, but not everyone.

for example, at the very bottom of this log:  [](https://firefox-ci-tc.services.mozilla.com/tasks/U6o95fCJQWG5sUqVX6bwUw/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FU6o95fCJQWG5sUqVX6bwUw%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log)
when we see a test failure, one of the last lines in the log will provide us with a link out to firebase.  In this case, there was a failure and the link provided is:  https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/570
however, the index num at the end is should be much longer  like this:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8884787474108861790/
so when we try to reference the error, Firebase gives us a 404

**Expected behavior**

The entire link should be visible in the log

**Screenshots**

![image](https://user-images.githubusercontent.com/3699494/68974157-e36fb000-07a4-11ea-94f7-7a33a1d5ea84.png)

**Platform (please complete the following information):**

 - OS: OSX
 - Browser: Firefox Nightly 72.0a1

**Additional context**

**Comment by rpappalax** [comment]
Also, I know we can still access this URL from the raw log by clicking on the 3dot menu in the lower right hand corner, however, the text for the 3 dot menu is extremely small and nearly illegible:

![image](https://user-images.githubusercontent.com/3699494/68974442-a0620c80-07a5-11ea-81a9-b387965f21d9.png)

**Comment by helfi92** [comment]
I don't seem to have permissions to access both links. Any chance I could have access so I can understand the issue?

**Comment by rpappalax** [comment]
@helfi92 Sorry for the confusion.  Those links are posted at the end of the taskcluster log.  For [](example:  https://firefox-ci-tc.services.mozilla.com/tasks/U6o95fCJQWG5sUqVX6bwUw/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FU6o95fCJQWG5sUqVX6bwUw%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log)
You actually don't need to click on the link to Firebase itself to understand the issue.  If the link is truncated it goes to a 404.

**Comment by helfi92** [comment]
Ah, thanks for the clarification. This is how it looks for me:

![Screen Shot 2019-11-18 at 4 33 48 PM](https://user-images.githubusercontent.com/3766511/69095943-600ec280-0a21-11ea-908b-01a4f1bc50cf.png)

It looks like it works for me but not for you for some reason. What device are you using?

**Comment by rpappalax** [comment]
Firefox Nightly on MacBook Pro.  Others on my team are seeing same.

**Comment by helfi92** [comment]
The fix will make it in the next deployment of Taskcluster.
