### ISSUE TITLE
Show task payload in YAML syntax?

### ISSUE THREAD

**Issue by SimonSapin** [taskcluster/taskcluster#2004]
**Describe the bug**

The payload of taks is shown in the UI as JSON syntax, which is hard to read.

**To Reproduce**

1. Go to https://community-tc.services.mozilla.com/tasks/QBv-eQ6ERE-x67E5bZXT6Q
2. Click on Payload
3. See that the payload is shown in JSON syntax. Part of it is:

```json
  "command": [
    [
      "/bin/bash",
      "--login",
      "-x",
      "-e",
      "-c",
      "git init repo\n cd repo\n echo \"$ALTERNATE_OBJDIR\" > .git/objects/info/alternates\n time git fetch --no-tags --depth 30 \"$GIT_URL\" \"$GIT_REF\"\n time git reset --hard \"$GIT_SHA\"\n \n\n export PATH=\"$HOME/Library/Python/2.7/bin:$PATH\"\n python -m ensurepip --user\n pip install --user virtualenv\n \ntime brew bundle install --verbose --no-upgrade --file=etc/taskcluster/macos/Brewfile-gstreamer\n\n mkdir -p $(dirname \"$CURL_1_PATH\")\n curl --retry 5 --connect-timeout 10 -Lf \"$CURL_1_URL\" -o \"$CURL_1_PATH\"\n \ntar -xzf target.tar.gz\n\n ./mach test-wpt-failure\n time ./mach test-wpt --release --binary-arg=--multiprocess                     --processes $PROCESSES                     --log-raw test-wpt-mp.log                     --log-errorsummary wpt-mp-errorsummary.log                     eventsource                     | cat\n time ./mach test-wpt --release --product=servodriver --headless                      tests/wpt/mozilla/tests/mozilla/DOMParser.html                     tests/wpt/mozilla/tests/css/per_glyph_font_fallback_a.html                     tests/wpt/mozilla/tests/css/img_simple.html                     tests/wpt/mozilla/tests/mozilla/secure.https.html                     | cat\n time ./mach test-wpt --release --processes $PROCESSES --product=servodriver                     --headless --log-raw test-bluetooth.log                     --log-errorsummary bluetooth-errorsummary.log                     bluetooth                     | cat\n time ./mach test-wpt --release --processes $PROCESSES --timeout-multiplier=4                     --headless --log-raw test-wdspec.log                     --log-errorsummary wdspec-errorsummary.log                     --always-succeed                     webdriver                     | cat\n ./mach filter-intermittents                     wdspec-errorsummary.log                     --log-intermittents intermittents.log                     --log-filteredsummary filtered-wdspec-errorsummary.log                     --tracker-api default                     --reporter-api default"
    ]
  ],
```

Because it is given in an single string literal, JSON syntax mandates that the interesting part of this payload is shown on a single line. This makes it hard to read.

**Expected behavior**

Some other parts of the site (for example https://community-tc.services.mozilla.com/tasks/create) use YAML syntax with a serializer that automatically picks between several of the many flavors of string literal syntax that YAML is famous for.

It would be nice to use that serializer for showing a task’s payload.

**Comment by djmitche** [comment]
Ideally we'd be consistent everywhere, both in data-entry and in read-only displays, and allow a tabbed view, or some other way of indicating preference, between the two formats.

**Comment by SimonSapin** [comment]
Consistency is good in general, though the payload in a task view is not quite the data entered on the create page (only part of it, and most tasks aren’t created manually).

I don’t know if I’d go all the way to an explicit switch. YAML is a superset of JSON, so entering JSON in editiable fields would still work. Are there cases where you’d want to copy-paste from a task’s payload into something that only accept JSON syntax?

**Comment by petemoore** [comment]
This sounds like a great win for user experience. What do you think @helfi92?

**Comment by helfi92** [comment]
A simple fix to be able to see the entire command without having to use the scroller would be to wrap the text. Thoughts?

![Screen Shot 2020-02-21 at 9 48 21 AM](https://user-images.githubusercontent.com/3766511/75044436-a3008c00-548f-11ea-808e-80ccae83e573.png)

**Comment by SimonSapin** [comment]
This is certainly an improvement.

As far as I can tell the YAML serializer has some heuristic for choosing between multiple syntax styles for string literals, some of which render multi-line strings (with `"…\n…"` in JSON) on as many lines, which would be even better.

**Comment by helfi92** [comment]
> This is certainly an improvement.
> 

Awesome, great to hear!

> As far as I can tell the YAML serializer has some heuristic for choosing between multiple syntax styles for string literals, some of which render multi-line strings (with `"…\n…"` in JSON) on as many lines, which would be even better.

Got it. For now, I would say let's just wrap the text to maintain the consistency of the [task definition](https://community-tc.services.mozilla.com/api/queue/v1/task/QBv-eQ6ERE-x67E5bZXT6Q) format with the payload (JSON). We could revisit this if we start hearing complaints with the new way data is being displayed.
