### ISSUE TITLE
NetworkError when attempting to fetch resource when attempting to view logs for currently running task.

### ISSUE THREAD

**Issue by worldomonation** [taskcluster/taskcluster#2018]
**Describe the bug**

**To Reproduce**

1. Schedule a task to be run on Try se/rver.
Once the task appears on Treeherder...
2. From Treeherder, click on the task to view the task details.
3. Click on the task ID to open in Taskcluster.
4. Under Task Run 0 > View Live Log, click on the chain icon

**Expected behavior**
5. Live log of currently executing task is shown.

**Actual Behavior**
5. Error in title is shown.
6., If the link is clicked, Firefox warns user of security risk.

**Screenshots**

**Platform (please complete the following information):**

 - OS: macOS 14.5
 - Browser: Firefox
 - Version: 72.0a1

**Additional context**
![Screen Shot 2019-11-18 at 11 44 54](https://user-images.githubusercontent.com/6549265/69084818-e1525f00-09f9-11ea-8959-d0ce78aed798.png)
![Screen Shot 2019-11-18 at 11 45 11](https://user-images.githubusercontent.com/6549265/69084819-e1525f00-09f9-11ea-8092-c720ec533986.png)

**Comment by djmitche** [comment]
Can you link to the specific task?  This looks like a worker misconfiguration.

**Comment by worldomonation** [comment]
This happens on all sorts of tasks spread out over many different try pushes. You should be able to reproduce it with this one for now: https://firefox-ci-tc.services.mozilla.com/tasks/RA_2p7zyRFWvblX8AxjMLg

**Comment by djmitche** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1597384 so hopefully we can stop seeing this bug :)

**Comment by worldomonation** [comment]
@djmitche Thanks, would you prefer to close this bug instead?

**Comment by djmitche** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1597386

Thanks :)
