### ISSUE TITLE
[UI] Menu items appear lighter

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#2019]
**Describe the bug**
After migrating to material-ui v4, menu items appear lighter.

![Screen Shot 2019-11-18 at 4 07 52 PM](https://user-images.githubusercontent.com/3766511/69094005-96e2d980-0a1d-11ea-9566-8f007b761568.png)

**Comment by Rolikasi** [comment]
Material-ui v4 removed color styles for MuiMenuItem
We can add it in overrides in theme.js, because we use MenuItem in several components
