### ISSUE TITLE
docs.taskcluster.net redirects to community deployment

### ISSUE THREAD

**Issue by vishakhanihore** [taskcluster/taskcluster#2044]
Wrong link to documentation in Repository Description as it is still pointing to `taskcluster.net`

**Comment by vishakhanihore** [comment]
@helfi92 @djmitche  I think only guys can fix this up 😅

**Comment by djmitche** [comment]
What link are you describing?

And, why can only guys fix it??

**Comment by vishakhanihore** [comment]
The link given in repo description. Only repo maintainers can fix it.

**Comment by djmitche** [comment]
This one?

![image](https://user-images.githubusercontent.com/28673/69268056-6d9c8780-0b9c-11ea-83d2-015d614dffde.png)

that's fine -- it's docs.taskcluster.net, which will stay as the docs generated from the master commit.

**Comment by vishakhanihore** [comment]
But it redirects to communitytc

**Comment by djmitche** [comment]
That's definitely a bug -- we're working on it now.

**Comment by vishakhanihore** [comment]
> That's definitely a bug -- we're working on it now.

Ok, cool atleast there was a bug.

**Comment by helfi92** [comment]
> That's definitely a bug -- we're working on it now.

Fixed.
