### ISSUE TITLE
[UI] Worker page appears to only display only the month of the quarantine.

### ISSUE THREAD

**Issue by tomprince** [taskcluster/taskcluster#2049]
If you look at [thjis worker](https://firefox-ci-tc.services.mozilla.com/provisioners/scriptworker-k8s/worker-types/comm-3-tree/workers/comm-3-tree/comm-3-tree-bgwc9kawqe6l3is4uydwpg), it has a quarantine of `3019-11-21T04:53:54.847Z` but only displays `11`.

**Comment by helfi92** [comment]
This was fixed in https://github.com/taskcluster/taskcluster/pull/1954. It should be there in the next deployment. One thing we could do here is add the time in addition to the date. I'll make sure it's being taken care of in https://github.com/taskcluster/taskcluster/issues/2031.
