### ISSUE TITLE
Engine "node" is incompatible with this module

### ISSUE THREAD

**Issue by aryamanpuri** [taskcluster/taskcluster#2058]
Taskcluster works on node version "10.16.3". 
But those developers who are on node version more/updated than "10.16.3"  are giving the error "The engine "node" is incompatible with this module".
How to make it comfortable for the developer to have version equal to or more than "10.16.3" will work fine for them.

**Comment by djmitche** [comment]
We require a specific version of Node, to avoid issues with differences between node versions.  The tool `nvm.sh` makes it very easy to switch node versions, so we suggest using that.

Note that we now require node 12, rather than node 10.

**Comment by djmitche** [comment]
See https://github.com/taskcluster/taskcluster/blob/d6a4adddb44f22c6b202773ce334bfdff56de8c5/dev-docs/development-process.md#node
