### ISSUE TITLE
[UI] Kebab menu button on a task should not open when hovered on.

### ISSUE THREAD

**Issue by jonalmeida** [taskcluster/taskcluster#2076]
**Describe the bug**

When looking at a particular task, the kebab menu on the bottom right opens when hovered over it. This is a confusing UX since that menu type is meant to open when clicked on only which leads one to click immediately on the button, and then have it close.

**To Reproduce**

1. Go to a task page. [This one](https://firefox-ci-tc.services.mozilla.com/tasks/am7BLkS3QiKpTGywE0Nvwg) for example.
2. Hover over three dots menu button.
4. Observe
3. Click the button.
4. Observe

**Expected behavior**

- At 3, nothing should happen.
- At 5, the menu should expand.

**Taskcluster version**

v23.0.0

**Screenshots**

<img width="277" alt="Screen Shot 2019-11-25 at 2 39 14 PM" src="https://user-images.githubusercontent.com/1370580/69572092-635dfd00-0f91-11ea-93cf-59c738ab11e3.png">

**Platform (please complete the following information):**

 - ~OS: [e.g. windows]~
 - ~Browser if applicable [e.g. firefox, safari]~
 - ~Version if applicable [e.g. 57]~

**Comment by helfi92** [comment]
I tried to replicate a similar behavior as the one shown in https://material.io/components/buttons-floating-action-button/#extended-fab under the "Behavior" subheader under "Extended FAB".

**Comment by jonalmeida** [comment]
I think that's correct, but even in the extended FAB, a touch or click is needed to change the state of the button.
