### ISSUE TITLE
[taskcluster-web] Missing view titles

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#208]
STR:

1. Navigate to http://localhost:5080/tasks/groups/cbxWJaKyTKagmTMjEb17FQ

Actual: There is no view title.
Expected: "Task Group"  shows in the app bar.

![screen shot 2019-02-11 at 9 53 42 am](https://user-images.githubusercontent.com/3766511/52571122-f652ef80-2de2-11e9-9917-7bd335a681b5.png)

2. Navigate to http://localhost:5080/tasks/groups

Actual: There is no view title.
Expected: "Task Groups" show in the app bar.

3. Navigate to http://localhost:5080/tasks/cbxWJaKyTKagmTMjEb17FQ

Actual: There is no view title.
Expected: "Task" shows in the app bar.

4. Navigate to http://localhost:5080/tasks

Actual: There is no view title.
Expected: "View Tasks" shows in the app bar.

---

In order to add a title to the app bar, one has to provide the `title` prop to the `Dashboard` component of the view.

**Comment by ededals** [comment]
I would like to work on this issue

**Comment by helfi92** [comment]
Go for it.

**Comment by iFlameing** [comment]
@helfi92 since there is no work going on this issue can I take this?

**Comment by helfi92** [comment]
@iFlameing Aren't you working on https://github.com/taskcluster/taskcluster/issues/164?

**Comment by helfi92** [comment]
@ededals How is it going?

**Comment by iFlameing** [comment]
@helfi92 yes I just created a pr related to that issue. If @ededals is working on it I will choose another issue. thanks :)

**Comment by helfi92** [comment]
I will review the PR now :)
