### ISSUE TITLE
[UI] search on scopes page only filters clients

### ISSUE THREAD

**Issue by mozbhearsum** [taskcluster/taskcluster#2088]
**Describe the bug**
When applying a filter on https://firefox-ci-tc.services.mozilla.com/auth/scopes, it only affects the "Clients" section. I would expect it to also filter "Roles".

**To Reproduce**

1. Go to https://firefox-ci-tc.services.mozilla.com/auth/scopes
2. Type "shipit" in the Search field
3. Observe that the list of Roles does not change, but the list of Clients does

**Expected behavior**
Filter the Roles in addition to the Clients

**Taskclster version**
23.0.0

**Platform (please complete the following information):**

 - OS: Linux
 - Browser if applicable: Firefox
 - Version if applicable: Nightly (20191126)

**Comment by helfi92** [comment]
> 3. Observe that the list of Roles does not change, but the list of Clients does

The list of roles seems to change. Are you seeing something different?

![Kapture 2019-11-26 at 10 00 00](https://user-images.githubusercontent.com/3766511/69645066-92c54600-1033-11ea-980c-97b159334f6f.gif)

**Comment by mozbhearsum** [comment]
I don't see a change. Before:
![image](https://user-images.githubusercontent.com/49649/69645403-1ed76d80-1034-11ea-8628-e4e09332315f.png)

After:
![image](https://user-images.githubusercontent.com/49649/69645440-2c8cf300-1034-11ea-8f00-ff05d0c893b1.png)

**Comment by mozbhearsum** [comment]
Perhaps it's filtering in a way that I don't expect though. I was expecting the first level of Roles to only show things with "shipit" in them. If I enter gibberish, all the Roles are filtered away, so I guess it's filtering on Roles that hold a scope matching the search string?

**Comment by helfi92** [comment]
Correct. This view helps identify which roles/clients have a certain scope, hence the search placeholder "Scope contains". If you are looking for a specific role or client, then there's https://firefox-ci-tc.services.mozilla.com/auth/scopes and https://firefox-ci-tc.services.mozilla.com/auth/clients.

We should perhaps make this a bit clearer...

**Comment by helfi92** [comment]
We tried making this clearer with:

<img width="1782" alt="Screen Shot 2020-03-31 at 9 28 03 AM" src="https://user-images.githubusercontent.com/3766511/78031760-f806ac00-7331-11ea-96f6-9945ca8d7c98.png">
