### ISSUE TITLE
[UI] The "provisioners" page is not very dense.

### ISSUE THREAD

**Issue by tomprince** [taskcluster/taskcluster#2096]
If I go to https://firefox-ci-tc.services.mozilla.com/provisioners/ I can only see ~6 of 38 "provisioners"[1]. I wanted to look at what all was being used and this made it hard to get an overview.

[1] These no longer represent provisioners, but the part of the worker-pool name before the `\`, but the point still stands.

**Comment by helfi92** [comment]
Hm, I can definitely see more than 6:

<img width="816" alt="Screen Shot 2019-11-26 at 6 23 57 PM" src="https://user-images.githubusercontent.com/3766511/69680780-f4a89e80-1079-11ea-81bf-250d471fabb4.png">

A screenshot or something I can look at to understand the issue would help. Thanks!

**Comment by tomprince** [comment]
I think we may have different size monitors. My screen fits 6 (of 38) cards.. And I can see more if I scroll, but it makes it hard to see all them easily.

I think a table, rather than cards makes more sense, given the number of entries.

**Comment by helfi92** [comment]
OH, I thought you were only seeing 6 in total even if you tried to scroll down. I guess I read the issue description without really paying attention to the title 😅

I believe https://bugzilla.mozilla.org/show_bug.cgi?id=1577840 will create a whole new UI in the near future. I agree that the table is a bit easier to scan so we will probably stay away from using cards.

**Comment by tomprince** [comment]
That will likely address the issue. Though if this bug is straightforward, and the linked one will take some time, I think it may be worthwhile doing this anyway?

**Comment by MooseJ** [comment]
Did not know that putting the issue number in the commit message actually links the two 😅
I guess now is a good time to ask, can I help with this issue?

**Comment by helfi92** [comment]
👋 @MooseJ 

Thanks for offering your help :) Let me know if you had questions. Also, if you have something working, feel free to create a PR and we can iterate on it there if necessary.
