### ISSUE TITLE
[UI] Deep link search in /secrets

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#2123]
**To Reproduce**

1. Go to https://firefox-ci-tc.services.mozilla.com/secrets/
2. Type "project/" in the search bar located in the app bar and then press enter.
3. Click on any secret
4. Click back

**Expected behavior**
The list of secrets only contains secrets that start with "project/".

**Taskcluster version**
23.0.0

**Additional context**
In order to fix this issue, we would need to use a query parameter (e.g., search). An example would be `https://firefox-ci-tc.services.mozilla.com/secrets?search=project%2F`.

**Comment by Manish-Giri** [comment]
@helfi92 Can I claim this one and #2124 (since they're both similar)? My other contribution is still in-progress, so technically I'm still a new contributor, and no one else has asked for these two issues either!

**Comment by helfi92** [comment]
Yep, go for it :)

**Comment by helfi92** [comment]
@Manish-Giri How is it going? :-) Still interesting in finishing this up? Happy to help.

**Comment by Manish-Giri** [comment]
@helfi92 Sorry, I had to step away for a few weeks for interview prep, and then completely forgot about this due to what's going around. 

I already did some work on this (and #2124) the last time, I'll get back on both right away. Thank You for bearing with me.

**Comment by helfi92** [comment]
No worries! Stay safe.
