### ISSUE TITLE
[web-server]  Replace Promise.all in loaders with try/catch

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#2125]
**Describe the bug**
If an error is thrown in Promise.all, the whole thing is rejected. We should gracefully catch errors in graphql loaders.

**Taskcluster version**
23.0.0

**Additional context**
We would need to find all `Promise.all` calls in `src/loaders` and replace them with try catch statement. The change should be similar to https://github.com/taskcluster/taskcluster/pull/1944/files.

**Comment by MooseJ** [comment]
Hey @helfi92, mind if I work on this bug?
