### ISSUE TITLE
[UI] Clicking on the copy icon should show feedback

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#2127]
**Describe the bug**
Clicking on the copy icon does not show any kind of feedback that whatever the user was trying to copy has now been copied to the clipboard.

**To Reproduce**

1. Go to https://firefox-ci-tc.services.mozilla.com/tasks/UBaqTi4kQ0elIUsYW2YdKg
2. Click on the list item with the copy icon

![Screen Shot 2019-12-03 at 2 43 28 PM](https://user-images.githubusercontent.com/3766511/70083932-58334e80-15db-11ea-8669-afbba9d2afb2.png)

**Actual behavior**
Nothing happens.

**Expected behavior**
A feedback is shown to the user that it was copied.

**Taskcluster version**
23.0.0

**Additional context**

Whenever a user tries to copy something after clicking on a list item or the copy icon, we can replace the copy icon with a check icon (e.g., ✔️) for a short duration. This will make sure the user knows that whatever they were trying to copy has been copied to the clipboard. This will avoid having users click on the button multiple times. In order to do this, we can create a custom component that augments it with this feature.

**Comment by aryamanpuri** [comment]
@helfi92 Can I give this a try?
Thinking of changing the icon to the text "copied" .

**Comment by aryamanpuri** [comment]
@helfi92 How to setup locally as the task is already submitted and creating new task locally is giving Unknown server error ?

**Comment by helfi92** [comment]
Does http://localhost:5080/tasks/fFaGg92IRWa5Rmj69FMDNQ work?

**Comment by aryamanpuri** [comment]
@helfi92 No

**Comment by aryamanpuri** [comment]
@helfi92 Yes it worked

**Comment by aryamanpuri** [comment]
>  https://firefox-ci-tc.services.mozilla.com/tasks/UBaqTi4kQ0elIUsYW2YdKg

Yes it worked

**Comment by helfi92** [comment]
Resolved in https://github.com/taskcluster/taskcluster/commit/22772ba5c17aaeaab6a192245600db20afa5a197
