### ISSUE TITLE
[UI] Remove error in console from /tasks and /tasks/groups

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#2128]
**Describe the bug**
Navigating to https://firefox-ci-tc.services.mozilla.com/tasks/ or https://firefox-ci-tc.services.mozilla.com/tasks/groups on a private window shows an error in the console.

![Screen Shot 2019-12-03 at 2 51 16 PM](https://user-images.githubusercontent.com/3766511/70084504-6170eb00-15dc-11ea-9980-6131187111a5.png)

Let's fix this.

**Taskcluster version**
23.0.0

**Comment by katherine95** [comment]
I would like to work on this but I can't reproduce the console error. 
<img width="1437" alt="Screenshot 2019-12-17 at 15 12 29" src="https://user-images.githubusercontent.com/17095461/70994612-aec28180-20df-11ea-9b0d-a4ad29f3e5b2.png">

**Comment by helfi92** [comment]
The error seems to show on Firefox, but not on Chrome.

**Comment by katherine95** [comment]
This is what I have from firefox. 
<img width="1435" alt="Screenshot 2019-12-17 at 18 19 45" src="https://user-images.githubusercontent.com/17095461/71008567-de7e8300-20f9-11ea-9203-04ed01232ea6.png">

**Comment by helfi92** [comment]
Interesting. Do you have the latest code pulled from the github repository? What does `git log --oneline -n 10` show for you?

**Comment by katherine95** [comment]
This is what `git log --oneline -n 10` shows. My forked repo is in sync with the original repo
<img width="718" alt="Screenshot 2019-12-18 at 17 48 22" src="https://user-images.githubusercontent.com/17095461/71096045-aee57e80-21be-11ea-9743-3469877db7c2.png">

**Comment by helfi92** [comment]
Hm...Were you running on a private window in Firefox?

**Comment by katherine95** [comment]
Got it. Thanks @helfi92. Let me start working on it.
<img width="499" alt="Screenshot 2019-12-19 at 07 53 29" src="https://user-images.githubusercontent.com/17095461/71146049-b7789c00-2234-11ea-9f44-632054fb0629.png">

**Comment by helfi92** [comment]
How is it going @katherine95? :-) Are you still working on this?

**Comment by helfi92** [comment]
Ah, the error seems to come from `db.userPreferences.get('theme')` in `App/index.jsx`.

**Comment by djmitche** [comment]
This seems fine now..
