### ISSUE TITLE
[UI] Deep link views roles, clients, scope views

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#2129]
**Describe the bug**
The `/auth/scopes`, `/auth/roles` views are not deep-linked. In other words, you cannot search for something then share the URL with somebody else without losing the refined search result.

**To Reproduce**

1. Go to https://firefox-ci-tc.services.mozilla.com/auth/scopes
2. Search for something in the app bar (e.g., "list") and press enter
3. Search a client/role in the app bar (e.g., "ci-admin") and press enter
3. Look at the new updated list
3. Refresh the page

**Actual behavior**
The old list is showing (before typing "ci-admin").

**Expected behavior**
The new list is showing (after typing "ci-admin").

**Taskcluster version**
23.0.0

**Comment by ss77995ss** [comment]
Hi, @helfi92 could I take this one up?
I might use `URL parameters` to store the information we need in `URL`
Something like `?k=list`

**Comment by helfi92** [comment]
Ah, I forgot to reply back :( @ss77995ss do you still have the bandwidth to work on this? Happy to help :)

**Comment by ss77995ss** [comment]
Yeah, I could help! I'll start working on it if there is no concern. 
I might use `react-router`'s `history.push` to set query parameters then use `useQuery` to get it to do the deep links.

**Comment by helfi92** [comment]
Awesome, thanks! We use deep linking in other views of the site so you could use that to see how they are implemented.

**Comment by ss77995ss** [comment]
Hi @helfi92, 
Hmm looks like `auth/client` and `auth/scopes` has deep linking already.
Then I only need to handle `roles` views?

**Comment by helfi92** [comment]
I just updated the bug description for /auth/scopes (the view had changed slightly since last time). Looks like /auth/clients already has deep linking.

**Comment by ss77995ss** [comment]
Thanks for the update!
BTW, could I have a try on rewriting `<ViewScope />` and `<ViewRoles />` with `react hooks`?

**Comment by ss77995ss** [comment]
Hi @helfi92 , I've created a PR for this issue, have a look!

**Comment by helfi92** [comment]
Reviewed. Let me know if you had any questions.

**Comment by ss77995ss** [comment]
Thank you! I just updated the PR. Have a look :)
