### ISSUE TITLE
[web-server] Add graphql tests

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#2130]
**Describe the bug**
Whenever we get new updates from the renovate-bot to bump package versions related to the web-server service, we are [not confident](https://github.com/taskcluster/taskcluster/pull/2067#issuecomment-558659636) 100% that things will still work. We should look into adding some tests to tests graphql queries, mutations, and subscriptions.

**Comment by MooseJ** [comment]
@helfi92 So I started working on this, but then realized that I'm not 100% what you wanted. Are you looking for tests to be created for every GraphQL query, mutation, and subscription?

**Comment by helfi92** [comment]
> @helfi92 So I started working on this, but then realized that I'm not 100% what you wanted. Are you looking for tests to be created for every GraphQL query, mutation, and subscription?

You have the right idea :) We can start with "Roles" first.

**Comment by helfi92** [comment]
@MooseJ How do you feel about giving the following a try https://github.com/taskcluster/taskcluster/blob/de2c662e1780f884204b94c167d0a54d61f5d05d/services/web-server/src/graphql/Tasks.graphql#L376-L379

It would be our first subscription test.  Once we have a subscription tested, we would be able to merge https://github.com/taskcluster/taskcluster/pull/2067

**Comment by MooseJ** [comment]
@helfi92 Yeah I can give that shot!

**Comment by helfi92** [comment]
Thank you so much!

**Comment by helfi92** [comment]
@MooseJ Happy new year! How is it going? :-)

**Comment by MooseJ** [comment]
@helfi92 Hey sorry, I've been going a bit slower with this because of the holidays. I have an idea of what the tests are going to be, but this was a more difficult than I thought it would be 😄I also think I have an idea of what I need to do, but I'm going to ask you some questions later because I feel like I'm going to get stuck. I should have a better idea of things by the end of the weekend

**Comment by MooseJ** [comment]
@helfi92 

So, I am currently getting this error from my test results:
```js
{
  "graphQLErrors": [
    {
      "message": "Cannot destructure property `tasksSubscriptions` of 'undefined' or 'null'.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "tasksSubscriptions"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot destructure property `tasksSubscriptions` of 'undefined' or 'null'.",
            "    at resolve (/Users/moose/github/taskcluster/services/web-server/src/resolvers/Tasks.js:155:17)",
            "    at field.resolve (/Users/moose/github/taskcluster/node_modules/graphql-extensions/dist/index.js:133:26)",
            "    at resolveFieldValueOrError (/Users/moose/github/taskcluster/node_modules/graphql/execution/execute.js:467:18)",
            "    at resolveField (/Users/moose/github/taskcluster/node_modules/graphql/execution/execute.js:434:16)",
            "    at executeFields (/Users/moose/github/taskcluster/node_modules/graphql/execution/execute.js:275:18)",
            "    at executeOperation (/Users/moose/github/taskcluster/node_modules/graphql/execution/execute.js:219:122)",
            "    at executeImpl (/Users/moose/github/taskcluster/node_modules/graphql/execution/execute.js:104:14)",
            "    at Object.execute (/Users/moose/github/taskcluster/node_modules/graphql/execution/execute.js:64:35)",
            "    at /Users/moose/github/taskcluster/node_modules/apollo-server-core/dist/requestPipeline.js:238:46",
            "    at Generator.next (<anonymous>)",
            "    at /Users/moose/github/taskcluster/node_modules/apollo-server-core/dist/requestPipeline.js:8:71",
            "    at new Promise (<anonymous>)",
            "    at __awaiter (/Users/moose/github/taskcluster/node_modules/apollo-server-core/dist/requestPipeline.js:4:12)",
            "    at execute (/Users/moose/github/taskcluster/node_modules/apollo-server-core/dist/requestPipeline.js:217:20)",
            "    at Object.<anonymous> (/Users/moose/github/taskcluster/node_modules/apollo-server-core/dist/requestPipeline.js:157:42)",
            "    at Generator.next (<anonymous>)",
            "    at fulfilled (/Users/moose/github/taskcluster/node_modules/apollo-server-core/dist/requestPipeline.js:5:58)",
            "    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
          ]
        }
      }
    }
  ],
  "networkError": null,
  "message": "GraphQL error: Cannot destructure property `tasksSubscriptions` of 'undefined' or 'null'."
}
```

And this is what I currently have for my subscription test:
```js
test('subscribe works', async function(){
  const beat = () => new Promise(resolve => setTimeout(resolve, 10));
  const client = getClient();
  const task = helper.makeTaskDefinition();
  const taskGroupId = task.taskGroupId;
  const subscriptions = [
     'tasksRunning',
     'tasksDefined'
  ]


  let taskSubscription = client.subscribe({
    query: gql`${subscribeTasks}`,
    variables: {
      taskGroupId,
      subscriptions
    }
  }).subscribe(
    (value) => console.log(value),
    (error) => console.log(JSON.stringify(error, null, 2))
  );

  await beat(); //The error doesn't occur without this beat
  taskSubscription.unsubscribe();
})
```

I mocked out the PulseEngine in the helper.js file since I saw it was being used is the task resolver and was getting issues before mocking it out https://github.com/taskcluster/taskcluster/blob/master/services/web-server/src/resolvers/Tasks.js#L128. I'm wondering if I'm also going to have to mock out the queueEvents client too. 

This is how I mocked out the PulseEngine:

```js
//other imports
const { withPulse } = require('taskcluster-lib-testing');
const PulseEngine = require('../src/PulseEngine');

exports.withPulse = (helper, skipping) => {
  withPulse({helper, skipping, namespace: 'taskcluster-web-server'});
};

exports.withPulseEngine = (mock, skipping) => {
  suiteSetup('withPulseEngine', async function() {
    if (skipping()) {
      return;
    }

    const pulseEngine = new PulseEngine({
      monitor: await exports.load('monitor'),
      pulseClient: await exports.load('pulseClient')
    })

    exports.load.inject('pulseEngine', pulseEngine);
  });

  suiteTeardown(function () {
    exports.load.remove('pulseEngine');
  });
}
````

Any suggestions on what I should try or look into?

**Comment by helfi92** [comment]
> @helfi92
> 
> So, I am currently getting this error from my test results:
> 
> ```js
> {
>   "graphQLErrors": [
>     {
>       "message": "Cannot destructure property `tasksSubscriptions` of 'undefined' or 'null'.",
>       "locations": [
>         {
>           "line": 2,
>           "column": 3
>         }
>       ],
>       "path": [
>         "tasksSubscriptions"
>       ],
>       "extensions": {
>         "code": "INTERNAL_SERVER_ERROR",
>         "exception": {
>           "stacktrace": [
>             "TypeError: Cannot destructure property `tasksSubscriptions` of 'undefined' or 'null'.",
>             "    at resolve (/Users/moose/github/taskcluster/services/web-server/src/resolvers/Tasks.js:155:17)",
>             "    at field.resolve (/Users/moose/github/taskcluster/node_modules/graphql-extensions/dist/index.js:133:26)",
>             "    at resolveFieldValueOrError (/Users/moose/github/taskcluster/node_modules/graphql/execution/execute.js:467:18)",
>             "    at resolveField (/Users/moose/github/taskcluster/node_modules/graphql/execution/execute.js:434:16)",
>             "    at executeFields (/Users/moose/github/taskcluster/node_modules/graphql/execution/execute.js:275:18)",
>             "    at executeOperation (/Users/moose/github/taskcluster/node_modules/graphql/execution/execute.js:219:122)",
>             "    at executeImpl (/Users/moose/github/taskcluster/node_modules/graphql/execution/execute.js:104:14)",
>             "    at Object.execute (/Users/moose/github/taskcluster/node_modules/graphql/execution/execute.js:64:35)",
>             "    at /Users/moose/github/taskcluster/node_modules/apollo-server-core/dist/requestPipeline.js:238:46",
>             "    at Generator.next (<anonymous>)",
>             "    at /Users/moose/github/taskcluster/node_modules/apollo-server-core/dist/requestPipeline.js:8:71",
>             "    at new Promise (<anonymous>)",
>             "    at __awaiter (/Users/moose/github/taskcluster/node_modules/apollo-server-core/dist/requestPipeline.js:4:12)",
>             "    at execute (/Users/moose/github/taskcluster/node_modules/apollo-server-core/dist/requestPipeline.js:217:20)",
>             "    at Object.<anonymous> (/Users/moose/github/taskcluster/node_modules/apollo-server-core/dist/requestPipeline.js:157:42)",
>             "    at Generator.next (<anonymous>)",
>             "    at fulfilled (/Users/moose/github/taskcluster/node_modules/apollo-server-core/dist/requestPipeline.js:5:58)",
>             "    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
>           ]
>         }
>       }
>     }
>   ],
>   "networkError": null,
>   "message": "GraphQL error: Cannot destructure property `tasksSubscriptions` of 'undefined' or 'null'."
> }
> ```

This is coming from https://github.com/taskcluster/taskcluster/blob/7257c949b2ec724d65bcffbe6ae6d526578ae209/services/web-server/src/resolvers/Tasks.js#L150

If you change this to:

```jsx
resolve: (payload) => {
  console.log(payload);
```

you'll notice that the input for the resolve function is probably null so destructuring doesn't work.

> And this is what I currently have for my subscription test:
> 
> ```js
> test('subscribe works', async function(){
>   const beat = () => new Promise(resolve => setTimeout(resolve, 10));
>   const client = getClient();
>   const task = helper.makeTaskDefinition();
>   const taskGroupId = task.taskGroupId;
>   const subscriptions = [
>      'tasksRunning',
>      'tasksDefined'
>   ]
> 
> 
>   let taskSubscription = client.subscribe({
>     query: gql`${subscribeTasks}`,
>     variables: {
>       taskGroupId,
>       subscriptions
>     }
>   }).subscribe(
>     (value) => console.log(value),
>     (error) => console.log(JSON.stringify(error, null, 2))
>   );
> 
>   await beat(); //The error doesn't occur without this beat
>   taskSubscription.unsubscribe();
> })
> ```

Before subscribing to a task group, we might need to create the task first

```jsx
// 1. first create the task
await client.mutate({
  mutation: gql`${createTaskQuery}`,
  variables: {
    taskId,
    task,
  },
});

// 2. subscribe for updates to the task that we just created
client.subsribe({ query, variables })
  // from https://blog.apollographql.com/graphql-subscriptions-in-apollo-client-9a2457f015fb#eeba,
  // subscribe here seems to take next and error as keys
  .subscribe({
    next(data) {...},
    error(err) {...}
  });

// 3. Create a task that has the same taskGroupId as the one we just created but with a different taskId.
await client.mutate({
  mutation: gql`${createTaskQuery}`,
  variables: {
    taskId: secondTaskId,
    task,
  },
});
```

> 
> I mocked out the PulseEngine in the helper.js file since I saw it was being used is the task resolver and was getting issues before mocking it out https://github.com/taskcluster/taskcluster/blob/master/services/web-server/src/resolvers/Tasks.js#L128. I'm wondering if I'm also going to have to mock out the queueEvents client too.
> 
> This is how I mocked out the PulseEngine:
> 
> ```js
> //other imports
> const { withPulse } = require('taskcluster-lib-testing');
> const PulseEngine = require('../src/PulseEngine');
> 
> exports.withPulse = (helper, skipping) => {
>   withPulse({helper, skipping, namespace: 'taskcluster-web-server'});
> };
> 
> exports.withPulseEngine = (mock, skipping) => {
>   suiteSetup('withPulseEngine', async function() {
>     if (skipping()) {
>       return;
>     }
> 
>     const pulseEngine = new PulseEngine({
>       monitor: await exports.load('monitor'),
>       pulseClient: await exports.load('pulseClient')
>     })
> 
>     exports.load.inject('pulseEngine', pulseEngine);
>   });
> 
>   suiteTeardown(function () {
>     exports.load.remove('pulseEngine');
>   });
> }
> ```
> 
> Any suggestions on what I should try or look into?

That's a good question. I'm not entirely sure. @djmitche Do you happen to know?

**Comment by djmitche** [comment]
I'm not sure, and it's hard to say without seeing the code in a PR.

Creating a task as suggested wouldn't work because tests don't run against a "real" service -- everything should be mocked internally.  So, if necessary you could [fake queue methods to return tasks](https://github.com/taskcluster/taskcluster/tree/master/clients/client#fake-api-methods), but that wouldn't get you any events.

You've chosen a good path in mocking the pulseClient.  Once that's done, I think just `exports.load('pulseEngine')` would work, as it would find the mocked pulse client.  Then you'll need to [inject pulse messages](https://github.com/taskcluster/taskcluster/blob/master/libraries/testing/README.md#withpulse) into the fake pulseClient with `helper.fakePulseMessage(..)`.

In general the key to good unit tests it to concentrate on the inputs and outputs of the smallest unit you can isolate.  The approach in the previous paragraph ends up testing all of PulseEngine, PulseIterator, and the `taskSubscriptions` resolver -- three "units".  PulseIterator is already tested.  PulseEngine isn't, but that's another project for another day.  The resolver's inputs are `pulseEngine.eventIterator` and `clients.queueEvents`.  If you can create a fake `pulseEngine.eventIterator` method that returns an async iterator that produces messages of the correct form, that should be a minimal input.  The `queueEvents` object just creates routing keys without any external access, so there shouldn't be any need to fake it.
