### ISSUE TITLE
click on collapsed 'Artifacts' dropdown goes to next run, shall expand artifacts list

### ISSUE THREAD

**Issue by Archaeopteryx** [taskcluster/taskcluster#2155]
If one clicks the collapsed 'Artifacts' dropdown at the right of
https://firefox-ci-tc.services.mozilla.com/tasks/H5nU0YljTqyBTxcJSY9TZw/runs/0 , one gets taken from run 0 to run 1 instead of expanding the list of artifacts. Is there no artifact for run 0?

**Comment by helfi92** [comment]
Yikes, that's a bug. Feel free to use https://firefox-ci-tc.services.mozilla.com/tasks/H5nU0YljTqyBTxcJSY9TZw/runs/0#artifacts for now but I'll get that fixed ASAP.

**Comment by helfi92** [comment]
will be resolved in the next deployment.
