### ISSUE TITLE
web ui: can't remove worker from quarantine

### ISSUE THREAD

**Issue by aerickson** [taskcluster/taskcluster#2166]
**Describe the bug**
I can't remove machine-23 from quarantine. The job it's trying to bring up has been purged.

https://firefox-ci-tc.services.mozilla.com/provisioners/terraform-packet/worker-types/gecko-t-linux/workers/packet-sjc1/machine-23

`XPOFNuq0TsCPvleqTCdubw does not correspond to a task that exists. Are you sure this task exists?`

**To Reproduce**

1. Go to https://firefox-ci-tc.services.mozilla.com/provisioners/terraform-packet/worker-types/gecko-t-linux
2. Click on machine-23 with the hopes of removing from quarantine.
3. See error: `XPOFNuq0TsCPvleqTCdubw does not correspond to a task that exists. Are you sure this task exists?`

**Expected behavior**
At step 3 the worker's page is displayed and I'm able to remove it from quarantine.

**Taskcluster version**
v24.0.2

**Screenshots**
let me know if required

**Platform (please complete the following information):**

 - OS: Mac
 - Browser if applicable Firefox
 - Version if applicable 71.0

**Additional context**

**Comment by helfi92** [comment]
I can reproduce. Thank you for bringing this up.

**Comment by helfi92** [comment]
The fix for that will be deployed in the next deployment of firefoxci.
