### ISSUE TITLE
[UI] Remove duplicate navigation bars

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#217]
STR:

1. Navigate to http://localhost:5080/shell

<img width="1680" alt="screen shot 2018-12-24 at 3 48 50 pm" src="https://user-images.githubusercontent.com/3766511/50406467-8eddd380-0793-11e9-848c-a9db411e7013.png">

Actual: There are 2 navigation bars on the left

Expected: There is 1 navigation bar on the left

**Comment by helfi92** [comment]
This issue only happens in Firefox and seems to be coming from `hterm-umdjs`. Created https://github.com/dbkaplun/hterm-umdjs/issues/6.

**Comment by djmitche** [comment]
@helfi92 it looks like dbkaplun/hterm-umdjs might be unmaintained?  Should we consider forking it and fixing it locally?

**Comment by helfi92** [comment]
We could try sending a pull-request to `dbkaplun/hterm-umdjs` first and see if we can get it merged. If that doesn't work, forking it might be a good idea.

**Comment by whimboo** [comment]
Any update here? Thanks

**Comment by Shubhamchinda** [comment]
Can I take it?

**Comment by helfi92** [comment]
Definitely. The bug is in hterm-umdjs. There's an issue filed [here](https://github.com/dbkaplun/hterm-umdjs/issues/6). You will want to clone that repo and symlink it so you can test the changes using Taskcluster UI.

Reference: https://yarnpkg.com/lang/en/docs/cli/link/

Hope that helps.

**Comment by carpecodeum** [comment]
can i take this ?

**Comment by helfi92** [comment]
Go for it.

**Comment by Pep-DEV101** [comment]
I am up for it

**Comment by helfi92** [comment]
How is it going @carpecodeum?

**Comment by carpecodeum** [comment]
I am sorry but i am already working on this

**Comment by helfi92** [comment]
Sounds good. @Pep-DEV101 feel free to tackle another issue.

**Comment by vishakhanihore** [comment]
@djmitche Please assign me this, its been stale . Thanks

**Comment by djmitche** [comment]
@carpecodeum if you are still working on this, please let us know.  Hopefully the two of you can divide up this issue and #444 :)

**Comment by vishakhanihore** [comment]
@helfi92 @djmitche So, I did a research and tried to `symlink` the `hterm-udmjs` library on local and tried to solve, But ALAS, The issue regarding FF Bug was already solved in original `chromium's hterm` and the following package is made from that consideration. I think there is some error in our code. 
I will try to debug using our code. In the meanwhile if you have any suggestion, I am all ears.
Thanks

**Comment by carpecodeum** [comment]
yes @vishakhanihore you can take this up

**Comment by vishakhanihore** [comment]
@djmitche @helfi92 I read about the bug opened in the `Library` but it has no relation to the line mentioned in here.
Moreover, the `hterm-udmjs` is not also maintained. Can you guide what could be the potential way to solve the bug.
```js
hterm.ScrollPort.prototype.decorate = function(div) {
  // ...

  if ('mozInnerScreenX' in window)  // detect a FF only property
    this.iframe_.src = '#';

 // ...
```

**Comment by helfi92** [comment]
Looks like you're on the right track. You can try experimenting locally by changing the code directly there. Once you found a fix, you can share it here, then once we agree on the fix, we could fork the library and publish our own version of it with the fix.

**Comment by vishakhanihore** [comment]
@helfi92 @djmitche After a lot of trying, I thought to look into h-term for the issue. It is nice to know that the following is not the issue of `hterm-umdjs`. 
This error is occurring due to `chromium-hterm` and there is a bug already opened for this in `h-term` repo.
https://bugs.chromium.org/p/chromium/issues/detail?id=980671
I have starred the following bug and hence this multiple hterm issue will be solved when the following is fixed by `hterm-maintainers`.

**Comment by vishakhanihore** [comment]
We can remove the label `good-first-issue` and label it `later` until `hterm` fixes this problem for firefox.

**Comment by vishakhanihore** [comment]
@helfi92 ?

**Comment by djmitche** [comment]
Thanks, I've adjusted the labels as you suggested.

**Comment by helfi92** [comment]
I may have an idea :)

When a user clicks on a log, we can stop showing the menu and instead just render the log full screen.

**Comment by vishakhanihore** [comment]
Are you suggesting to redirect to shell rather than showing our hamburger
menu and navbar?

**Comment by helfi92** [comment]
Correct.

**Comment by vishakhanihore** [comment]
> Correct.

But not only there is dual rendering of nav bar and side menu, But the `h-term` is also rendering twice in the window .

**Comment by helfi92** [comment]
Can you show me in the DOM where you see two renderings of h-term?

**Comment by vishakhanihore** [comment]
when I resize the window, I see two screen widths on shell. Of which I guessed that the h-term is also getting double rendered

**Comment by helfi92** [comment]
Oh, okay. When in doubt, you can open the developer tools and see if there are two h-terms.
