### ISSUE TITLE
[UI] Form resetting when creating a new client

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#2187]
**Describe the bug**
Creating a new client while missing scopes will show an error but then clear the form. We should not clear the form when there is an error.

**To Reproduce**

1. Go to http://localhost:5080/auth/clients/create and make sure you are not logged in
2. Fill the form with any values
2. Click on the save button icon on the lower right
3. Close the error panel

**Expected behavior**
The form values are still there.

**Actual behavior**
The form values have been cleared out

**Taskcluster version**
24.1.1

**Additional context**
The reason why this is happening is because the key prop is changing when an error happens:

https://github.com/taskcluster/taskcluster/blob/caec22bccd3481e7d0f02c091ce1bc8eba3263a7/ui/src/views/Clients/ViewClient/index.jsx#L361

When a `key` prop changes in React, it re-creates a whole component, hence losing all of the internal state. One way to fix this issue is to make sure that `JSON.stringify(initialClient)` doesn't change on subsequent renders. We can probably do it with https://github.com/caiogondim/fast-memoize.js#custom-serializer (we use this in a couple of places in the repo).

**Comment by ss77995ss** [comment]
Hi, can I take this one up?

**Comment by theprover97** [comment]
Hi @helfi92 , can I work on this issue?

**Comment by helfi92** [comment]
@ss77995ss Go for it.

**Comment by helfi92** [comment]
How is it going @ss77995ss? :-)

**Comment by ss77995ss** [comment]
Hi @helfi92 , I just start developing today, I'll update my status if I have some process!

**Comment by helfi92** [comment]
Sounds good. Thanks for the update.

**Comment by ss77995ss** [comment]
Hi @helfi92 , I have created a PR for this ticket, could you help me review it?
I use `expires` from `query` as the `memoize` cache key so the `key` prop should not update until we get data from `GraphQL`
