### ISSUE TITLE
[UI] Hooks: behaviour when group (but not items) matches search isn't ideal

### ISSUE THREAD

**Issue by mitchhentges** [taskcluster/taskcluster#219]
**Summary:**
Searching for all hooks in a group doesn't quite work, since the search that matches the hook's name probably doesn't match the items, too

**To reproduce:**
1. Go to [hooks](https://taskcluster-web.netlify.com/hooks)
2. Search for "project-gecko"
3. Expand the "project-gecko" group
* There's no hooks in "project-gecko" :thinking: 

**Preferred behaviour:**
We could show all items in a group if the group name matches? :thinking:

**Comment by djmitche** [comment]
It might make sense to remove the group/hook distinction in the UI and just treat them as slash-separated strings.  I don't know why I designed hooks with two levels of names like that.
