### ISSUE TITLE
[UI] Can't save worker config when editing

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#2200]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1605430:

> Sometimes, when you finish editing the worker config, the UI doesn't allow you to save it, but neither provides a visual indication of what's wrong. If you create a brand new worker-pool and paste the edited configuration, the UI doesn't complain.

**Comment by helfi92** [comment]
@walac Are you still seeing this issue these days?

**Comment by walac** [comment]
I haven't seen it since then
