### ISSUE TITLE
[UI] Worker manager required owner field

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#2201]
STR:

1. Navigate to http://localhost:5080/worker-manager/create
2. Fill out all the fields except the owner field

![Screen Shot 2019-12-20 at 2 00 03 PM](https://user-images.githubusercontent.com/3766511/71284575-0a377e00-2331-11ea-8ea1-228731d839bd.png)

**Actual:** The save button (diskette icon) is enabled.
**Expected:** The save button is disabled since the owner field is required but empty

Possibly also relates to https://github.com/taskcluster/taskcluster/issues/2200.

**Comment by theprover97** [comment]
Hi @helfi92 ,can I work on this issue? Are we required to add an appropriate indication for the missing field of ' owner ' ?

**Comment by helfi92** [comment]
> Hi @helfi92 ,can I work on this issue?

Yep, go for it.

> Are we required to add an appropriate indication for the missing field of ' owner ' ?

Good question. There should be a "*" beside Owner's Email to indicate that this field is required. Also, when a user writes something that is not an email, there's already an error that will show up:

<img width="326" alt="Screen Shot 2019-12-23 at 7 59 22 AM" src="https://user-images.githubusercontent.com/3766511/71359356-25390680-255a-11ea-89e9-ae059b5903a1.png">

To answer your question, there shouldn't be a need to add an extra indication for the missing field other than have the save button disabled when that value is not defined.

**Comment by theprover97** [comment]
Got it. Thanks.

**Comment by theprover97** [comment]
I have opened a PR for it ( #2220 Fixed #2201). Please check it.

**Comment by theprover97** [comment]
![check1](https://user-images.githubusercontent.com/43466272/71539629-2062c100-2965-11ea-9c3f-040ca24e38ea.png)
