### ISSUE TITLE
[UI] Support triggering tasks in response to pulse messages

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#221]
This is similar as https://github.com/taskcluster/taskcluster-tools/pull/595 but for taskcluster-web.

**Comment by djmitche** [comment]
Looks like this needs to be finished.. @ydidwania do you have time to work on it?

**Comment by ydidwania** [comment]
@djmitche I am sorry I cannot work on this for now. I can maybe get back to it around end of July. Is that okay?

**Comment by djmitche** [comment]
Ah, now that I look more closely @arshadkazmi42 is working on this in #730.  So, all good :)
