### ISSUE TITLE
[UI] Tab switching

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#223]
STR:

1. Navigate to https://taskcluster-web.netlify.com/aws-provisioner/gecko-1-b-win2012
2. Click on the "EC2 Resources" tab

Actual: It takes a couple of seconds before the tab switches

Expected: The tab switches right away and a `<Spinner loading />` is displayed inside the tab while the list is being loaded.

**Comment by sudipt1999** [comment]
I would like to solve this ! Basically what I am getting is to add a loader to the site , unless all the data is loaded.

**Comment by helfi92** [comment]
> I would like to solve this

Awesome! Go for it.

> Basically what I am getting is to add a loader to the site , unless all the data is loaded.

Not quite. What we want is to "virtualize" the table. You can achieve that by using the `react-window` package.

For inspiration, you can look at the roles view:
* https://github.com/taskcluster/taskcluster/blob/7b058a76c4a92305c85083cfbcf19effcb53603a/ui/src/components/RoleScopesTable/index.jsx#L16
* https://taskcluster-web.netlify.com/auth/roles.

**Comment by djmitche** [comment]
(I've invited sudipt1999 to the org; once that is accepted, this issue can be assigned)

**Comment by sudipt1999** [comment]
@helfi92  can you please tell me what does this `size` means , In what terms is size in https://github.com/taskcluster/taskcluster/blob/7b058a76c4a92305c85083cfbcf19effcb53603a/ui/src/components/RoleScopesTable/index.jsx#L141

**Comment by sudipt1999** [comment]
@helfi92  I am getting `Network error: NetworkError when attempting to fetch resource.` when I am opening the `http://localhost:8080/aws-provisioner` I have started the web-server then I started the ui.

**Comment by helfi92** [comment]
in `ui/.env`, try adding `PORT=5080` and see if that fixes it.

**Comment by sudipt1999** [comment]
Ya it worked ! but why that was happening ? any idea !

**Comment by helfi92** [comment]
We will soon remove the aws-provisioner view. No need to spend time optimizing it anymore :) Closing for now.
