### ISSUE TITLE
[UI] Icon size not consistent

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#2232]
**Describe the bug**
The icon size in the table is not the same.

**To Reproduce**

1. Go to https://firefox-ci-tc.services.mozilla.com/provisioners/mobile-3/worker-types/b-linux-large
2. Resize the window width until the icons under the First Claim and Worker ID column change

**Expected behavior**
The icons don't change in size when the window width changes.

**Actual behavior**

![Screen Shot 2020-01-03 at 9 46 25 AM](https://user-images.githubusercontent.com/3766511/71729503-ecc4e280-2e0d-11ea-8417-a468100e2675.png)

**Taskcluster version**
24.1.1

**Comment by aryamanpuri** [comment]
@helfi92 Can I look upon this?

**Comment by helfi92** [comment]
Definitely. Also, for future PRs, it would be great to send them from a branch other than master. https://www.atlassian.com/git/tutorials/using-branches/git-checkout

**Comment by aryamanpuri** [comment]
@helfi92 It is in all the Columns, maybe we should fix this with fixing the Icon size ?

**Comment by aryamanpuri** [comment]
@helfi92 What about making Icon out of the _TableCellItem_, It will look like this.
![Screenshot](https://user-images.githubusercontent.com/43513114/71813436-9bcc1d00-309f-11ea-847f-671595bee32e.png)
Your views?

**Comment by helfi92** [comment]
The copy icon should be inside the table cell item. One way to do this, I think, is to wrap the icon with a div element.

```diff
diff --git a/ui/src/components/CopyToClipboardTableCell/index.jsx b/ui/src/components/CopyToClipboardTableCell/index.jsx
index 96dd7b8f9..ff31faea6 100644
--- a/ui/src/components/CopyToClipboardTableCell/index.jsx
+++ b/ui/src/components/CopyToClipboardTableCell/index.jsx
@@ -21,9 +21,13 @@ function CopyToClipboardTableCell(props) {
         <TableCellItem button>
           {text}
           {isCopy ? (
-            <CheckIcon size={iconSize} />
+            <div>
+              <CheckIcon size={iconSize} />
+            </div>
           ) : (
-            <ContentCopyIcon size={iconSize} />
+            <div>
+              <ContentCopyIcon size={iconSize} />
+            </div>
           )}
         </TableCellItem>
       </TableCell>
```

^ This is untested. You might need to change some stuff to make sure it aligns properly.

**Comment by aryamanpuri** [comment]
The use of the div element will make sure that the icon size is the same in each case. But those table cell item having time in minutes is touching with the icon.

**Comment by helfi92** [comment]
I'm not sure I understand the problem. A screenshot might help here.

**Comment by aryamanpuri** [comment]
![Screenshot from 2020-01-06 22-14-51](https://user-images.githubusercontent.com/43513114/71833020-29286500-30d2-11ea-8019-f3c7ae20d44b.png)
