### ISSUE TITLE
[UI] Improve /provisioners UX for aws-provisioner

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#224]
Allow a user to somehow transition to the aws-provisioner view when viewing aws-provisioner worker types & workers from the `/provisioners` view.

**Comment by djmitche** [comment]
We won't have an AWS provisioner for much longer (it will not be redeployed, and will be replaced with worker-manager), so I'd suggest dropping this issue.

**Comment by helfi92** [comment]
Good to know :)
