### ISSUE TITLE
[UI] Show live log when available

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#2240]
**Describe the bug**

When a user clicks on the Taskcluster status link on GitHub, we navigate the user to the task viewer rather than the log viewer because we don't have the log URL at the time the link is posted on Github.

Users [most of the time](https://bugzilla.mozilla.org/show_bug.cgi?id=1527606#c0), however, just want to know why a task has failed. The current behavior requires too many clicks.

#### Current Behavior

The current way to access the logs from Github is:

1. Click on the status dot icon beside the commit message

![Screen Shot 2020-01-06 at 11 10 19 AM](https://user-images.githubusercontent.com/3766511/71830672-3bc08100-3075-11ea-908f-1c4a21503efc.png)

2. Click on "Details" beside the failed task

![Screen Shot 2020-01-06 at 11 10 25 AM](https://user-images.githubusercontent.com/3766511/71830671-3bc08100-3075-11ea-943a-e80428569077.png)

3. Click on "View more details on Community-TC Integration" from Github

4. Click on "View Live Log"

![Screen Shot 2020-01-06 at 11 12 57 AM](https://user-images.githubusercontent.com/3766511/71830809-8a6e1b00-3075-11ea-9d55-fbdece198fd1.png)

#### Expected behavior

The expected behavior is to view the log after clicking on "Details" in step 2 and avoid having to do step 3 and 4.

One way to do this is to introduce a query parameter `e.g., ?log=1` and use this to navigate the user directly to the log from the task view if the live log is found. The steps to implementing that would be:

1. Add a query parameter `log`.
2. If the live log is found and `log=1` then redirect the user to the log viewer.

---

Note: Once this is done, we would need to modify the Github status link slightly to add the query parameter to it. https://bugzilla.mozilla.org/show_bug.cgi?id=1527606

**Comment by Shubhamchinda** [comment]
Hi @helfi92 , I'd like to work on this!

**Comment by helfi92** [comment]
Go for it :)

**Comment by Shubhamchinda** [comment]
Hey @helfi92 , Could you please provide some information on where to start?

Thanks a lot!

**Comment by helfi92** [comment]
A good place to start would probably be `src/views/Tasks/ViewTask/index.jsx`. 
> One way to do this is to introduce a query parameter `e.g., ?log=1` and use this to navigate the user directly to the log from the task view if the live log is found. The steps to implementing that would be:
> 
>     1. Add a query parameter `log`.

To add a query parameter, you can look at how we do it in other places. One place is the workers view https://firefox-ci-tc.services.mozilla.com/provisioners/gecko-t/worker-types/t-linux-large. Changing the filter dropdown will add a `?filterBy` query at the end of the url. This is handled in https://github.com/taskcluster/taskcluster/blob/18098a861d7724e39dc54c6d9f2ef1b6b72e6136/ui/src/views/Provisioners/ViewWorkers/index.jsx#L119-L124.

Let me know if you had other questions. Hopefully that helps you get started.

**Comment by Shubhamchinda** [comment]
> A good place to start would probably be `src/views/Tasks/ViewTask/index.jsx`.
> 
> > One way to do this is to introduce a query parameter `e.g., ?log=1` and use this to navigate the user directly to the log from the task view if the live log is found. The steps to implementing that would be:
> > ```
> > 1. Add a query parameter `log`.
> > ```
> 
> To add a query parameter, you can look at how we do it in other places. One place is the workers view https://firefox-ci-tc.services.mozilla.com/provisioners/gecko-t/worker-types/t-linux-large. Changing the filter dropdown will add a `?filterBy` query at the end of the url. This is handled in
> 
> https://github.com/taskcluster/taskcluster/blob/18098a861d7724e39dc54c6d9f2ef1b6b72e6136/ui/src/views/Provisioners/ViewWorkers/index.jsx#L119-L124
> 
> .
> Let me know if you had other questions. Hopefully that helps you get started.

Thank you so much, I'm on it now!

**Comment by helfi92** [comment]
How is it going, @Shubhamchinda :-)

**Comment by lotas** [comment]
I will close this one as we have already implemented secondary link to take user directly to the log:
<img width="443" alt="image" src="https://user-images.githubusercontent.com/83861/168251202-fd259586-a003-4ef1-b6d8-8925bdff3c68.png">
