### ISSUE TITLE
[UI] Update material-ui to v4.8.3+

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#2241]
material-ui introduced the Alert component that we should try to at least use in our documentation site rather than create our own component in https://github.com/taskcluster/taskcluster/pull/2209 for documentation.

We're currently running on v4.5.1 https://github.com/taskcluster/taskcluster/blob/4f935ea671b1255f0f2598406e8fdeb656c3b75e/ui/yarn.lock#L1159-L1160

The [releases page](https://github.com/mui-org/material-ui/releases) is a good way to see what changed to make sure we add any necessary code changes.

**Comment by theprover97** [comment]
Can I work on this issue?

**Comment by theprover97** [comment]
I have opened a PR for this (#2248 ). Please check it.

**Comment by helfi92** [comment]
Resolved in https://github.com/taskcluster/taskcluster/pull/2418.
