### ISSUE TITLE
[worker-manager] Estimator reports false overprovisioned error when capacityPerInstance > 1

### ISSUE THREAD

**Issue by walac** [taskcluster/taskcluster#2246]
Description:
------------

`minCapacity` and `maxCapacity` are in terms of the number of instances, while `existingCapacity` is the number of instances times capacity per instance. This may trigger false overprovisioned errors when `capacityPerInstance` is greater than 1.

How to reproduce:
------------------

Set `minCapacity=0`, `maxCapacity=2` and `capacityPerInstance=30`. When we have one instance running, next time `Estimator.simple` is called, it will report an overprovisioned error.

**Comment by imbstack** [comment]
We discussed this in chat and figured out that this was a miscommunication about what `maxCapacity` means. It is the same "capacity" as `existingCapacity` is talking about rather than number of instances.
