### ISSUE TITLE
[UI] Remove error in console

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#2263]
**To Reproduce**

1. Go to http://localhost:5080/worker-manager/create
2. Open dev-tools
3. See error

![Screen Shot 2020-01-13 at 10 33 48 AM](https://user-images.githubusercontent.com/3766511/72268662-37094900-35f0-11ea-85dd-76369060735d.png)

**Expected behavior**
The 6 errors in the screenshot do not show on the console.

**Taskcluster version**
v24.1.1

**Comment by aryamanpuri** [comment]
@helfi92 Can I give this a try too.

**Comment by helfi92** [comment]
Go for it

**Comment by aryamanpuri** [comment]
@helfi92 Changing children from `node.isRequired` to `node` solves the first error .
Not sure about the material UI ones

**Comment by helfi92** [comment]
> @helfi92 Changing children from node.isRequired to node solves the first error .
Not sure about the material UI ones

children doesn't seem to be used so we can just do:

```diff
diff --git a/ui/src/components/MarkdownTextArea/index.jsx b/ui/src/components/MarkdownTextArea/index.jsx
index fd66fecb7..472031bd1 100644
--- a/ui/src/components/MarkdownTextArea/index.jsx
+++ b/ui/src/components/MarkdownTextArea/index.jsx
@@ -1,5 +1,4 @@
 import React from 'react';
-import { node } from 'prop-types';
 import MuiMarkdownTextArea from '@mozilla-frontend-infra/components/MarkdownTextArea';
 import { withStyles } from '@material-ui/core/styles';
 
@@ -20,8 +19,4 @@ function MarkdownTextArea({ classes, ...props }) {
   );
 }
 
-MarkdownTextArea.propTypes = {
-  children: node.isRequired,
-};
-
 export default withStyles(styles)(MarkdownTextArea);
```

**Comment by parshva-b** [comment]
Can I give this issue a try as well, @helfi92? Or is this issue assigned to @aryamanpuri

**Comment by aryamanpuri** [comment]
Hi @parshva-b  , you can try on other issues .This issue has been solved

**Comment by aryamanpuri** [comment]
@helfi92 Should be closed!
