### ISSUE TITLE
automatically generate the links in clients/client-go/README.md

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#2268]
#2267 identifies some bad links in this file.  Rather than try to maintain them automatically, let's make this a part of the code-generation process in `clients/client-go`.

To solve this, first get this repository out and get set up to where `yarn generate` will run without error.  Then look at the [code-generation process](https://github.com/taskcluster/taskcluster/tree/master/clients/client-go#generating) in `clients/client-go`.  Update that to automatically fix the list of links in the README.md file.

**Comment by jaskeerat789** [comment]
Hey @djmitche I would like to work on this...

**Comment by djmitche** [comment]
All yours!

**Comment by djmitche** [comment]
@ajinkabeer any interest in hacking on this?

**Comment by ajinkabeer** [comment]
Hello there @djmitche , I would very much like to take it up :)

**Comment by djmitche** [comment]
All yours!

**Comment by ajinkabeer** [comment]
Thanks, @djmitche. I would also like to get some more insight into this issue. I have looked at #2267 and found that you manually removed `v24 `from the links in `clients/client-go/README.md`.

When I ran `yarn generate`, got the following errors.

```
$ yarn generateyarn run v1.22.4$ node infrastructure/tooling/src/main.js generate... 50 completed tasks⣟ Go Mod Tidy
× Generate References for auth  (Error: Command failed: node src/main generateReferences)× Generate References for github  (Error: Command failed: node src/main generateReferences)
× Generate References for hooks  (Error: Command failed: node src/main generateReferences
)× Generate References for index  (Error: Command failed: node src/main generateReferences
)
× Generate References for notify  (Error: Command failed: node src/main generateReferences
)
× Generate References for purge-cache  (Error: Command failed: node src/main generateReferences
)
× Generate References for queue  (Error: Command failed: node src/main generateReferences
)
× Generate References for secrets  (Error: Command failed: node src/main generateReferences
)
× Generate References for worker-manager  (Error: Command failed: node src/main generateReferences
)
69% finished
```

**Comment by djmitche** [comment]
Hm, when it finished running it should have shown a full traceback for one
of those.  What did that say?

**Comment by ajinkabeer** [comment]
Thanks for the quick response @djmitche . Here is the traceback I got.

```
Command failed: node src/main generateReferences

    at ChildProcess.exithandler (child_process.js:303:12)    at ChildProcess.emit (events.js:311:20)
    at ChildProcess.EventEmitter.emit (domain.js:482:12)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:311:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at Pipe.<anonymous> (net.js:668:12) {
  killed: false,  code: 1,
  signal: null,
  cmd: 'node src/main generateReferences',
  stdout: 'Error: v1\\all-purge-cache-request-list.json: schema.$id should match format "uri-reference"; v1\\purge-cache-request-list.json: schema.$id should match format "uri-reference"; v1\\purge-cache-request.json: schema.$id should  match format "uri-reference"; v1\\purge-cache-requests.json: schema.$id should match format "uri-reference"\n' +
    '    at exports.validate (C:\\Users\\ajiin\\OneDrive\\Desktop\\taskcluster\\libraries\\references\\src\\validate.js:279:11)\n' +    '    at References.validate (C:\\Users\\ajiin\\OneDrive\\Desktop\\taskcluster\\libraries\\references\\src\\references.js:129:5)\n' +
    '    at References.validate (C:\\Users\\ajiin\\OneDrive\\Desktop\\taskcluster\\libraries\\references\\src\\references.js:124:16)\n' +
    '    at References.makeSerializable (C:\\Users\\ajiin\\OneDrive\\Desktop\\taskcluster\\libraries\\references\\src\\references.js:148:10)\n' +
    '    at References.generateReferences (C:\\Users\\ajiin\\OneDrive\\Desktop\\taskcluster\\libraries\\references\\src\\references.js:241:59)\n' +
    '    at setup (C:\\Users\\ajiin\\OneDrive\\Desktop\\taskcluster\\services\\purge-cache\\src\\main.js:74:8)\n' +
    '    at C:\\Users\\ajiin\\OneDrive\\Desktop\\taskcluster\\libraries\\loader\\src\\index.js:109:33\n' +
    '    at new Promise (<anonymous>)\n' +    '    at C:\\Users\\ajiin\\OneDrive\\Desktop\\taskcluster\\libraries\\loader\\src\\index.js:107:18\n',
  stderr: ''
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by djmitche** [comment]
Hm, that looks like a Windows path issue.  We haven't had great luck doing development of Taskcluster services on Windows.  Do you have WSL available?

**Comment by ajinkabeer** [comment]
Oh, I am really sorry for that  @djmitche 

Yes, I have WSL. So I guess after ``yarn generate`` runs without error, I can go ahead and look into ``codegenerator/model``  directory to start working on the issue.

**Comment by ajinkabeer** [comment]
``yarn generate`` ran without any errors. Yay!
```
100% finished
Done in 84.19s.

```

**Comment by ajinkabeer** [comment]
Hello @djmitche, I have a few questions in my mind. So are we going to write a function that reads the `README.md` file line by line and check the status codes of links by sending HTTP requests to all the links in the file?

**Comment by djmitche** [comment]
There was a bug to do something like that, but this is not it!  This one is easier :)

The idea is to automatically generate a part of the README file, based on information read directly from the repository.  Here's another example: [this code](https://github.com/taskcluster/taskcluster/blob/master/infrastructure/tooling/src/generate/generators/db-users.js) reads the list of DB users indirectly from [db/access.yml](https://github.com/taskcluster/taskcluster/blob/master/db/access.yml) and updates the list of users [here](https://github.com/taskcluster/taskcluster/blob/master/ui/docs/manual/deploying/database.mdx#db-users).  In the [raw view](https://raw.githubusercontent.com/taskcluster/taskcluster/master/ui/docs/manual/deploying/database.mdx) there are markers like `<!-- USERLIST BEGIN -->` that the script uses to figure out which part of the README to update.

So we'd like to do a similar thing here to generate links to godoc links and add them to the go-client README.

NOTE: Taskcluster currently doesn't show up on pkg.go.dev.  I don't know why, but if you can figure that out that'd be cool :)

**Comment by ajinkabeer** [comment]
I was able to find an older version of Taskcluster client package on [pkg.go.dev]( https://pkg.go.dev/github.com/taskcluster/taskcluster/v28@v28.2.3/clients/client-go?tab=doc). But since the latest version is v29, it should be automatically updated right?

**Comment by djmitche** [comment]
Indeed, yes.  If you'd like to work on that, that's great -- let's file another issue here to track that work, though.

**Comment by ajinkabeer** [comment]
Yes. Thanks for confirming that. I think I will move onto that issue once I finish this one up

**Comment by ajinkabeer** [comment]
So should we add a marker in `README.md ` file before writing a function?

**Comment by djmitche** [comment]
Yes

**Comment by ajinkabeer** [comment]
Thanks. I will open a PR once I make some meaningful progress.
