### ISSUE TITLE
[UI] Hooks: Disable "save" button unless some values have changed

### ISSUE THREAD

**Issue by mitchhentges** [taskcluster/taskcluster#227]
**Summary:**
When I go back to an old hook tab that I had open, I see that the "save" button isn't disabled, which makes me wonder: do I have unsaved changes? Did I change the hook before I left the tab some hours ago? If we disabled the hook unless there's unsaved changes, it could improve usability.

**To reproduce:**
1. Go to [a hook](https://taskcluster-web.netlify.com/hooks/project-mobile/focus-nightly-staging)

**Comment by helfi92** [comment]
@mitchhentges This should now be fixed. Thanks again for creating the issue. If you have a similar problem with other views of the new site, feel free to create another issue :)
