### ISSUE TITLE
Client creator "blanks" the scopes

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#2293]
**Describe the bug**
When using the `taskcluster signin` command line tool to login, the user is redirected to the client creator, e.g.,
  https://firefox-ci-tc.services.mozilla.com/auth/clients/create?scope=assume%3Aproject%3Ataskcluster%3Asmoketests&name=smoketest-TmaUSR&expires=1d&callback_url=http%3A%2F%2Flocalhost%3A36339&description=Temporary+client+for+use+on+the+command+line

This screen should display the list of desired scopes in the bottom of the form.  However, at least intermittently that field is empty.  It *looks* like it is briefly populated on page load, then reset -- but I can't quite tell.

**To Reproduce**

1. Download a taskcluster client (see the releases tab)
2. Run `TASKCLUSTER_ROOT_URL=https://community-tc.services.mozilla.com taskcluster signin --name --scope assume:login-identity:*`
3. See an empty set of scopes in the resulting page (if the scopes appear, try again)

**Expected behavior**
Scopes appear and are granted

**Taskcluster version**
24.1.0

**Comment by MooseJ** [comment]
Hey @djmitche. I started taking a look at this issue. I was unable to get scopes to not show up. I followed the steps above, and logged in through my Github account. 

I was always getting this:
![image](https://user-images.githubusercontent.com/15016463/74610548-374ea580-50c2-11ea-902c-5960965c9f48.png)

Should I be logging in through my github or is there another way I should be logging in?

**Comment by djmitche** [comment]
Hm, I can't reproduce right now either.  However, I just signed in.

When it does work, I see that scopes is initially `*`, then is expanded to all of my scopes.

I wonder if this occurs if you haven't accessed the site in something like 6 hours, so the UI needs to refresh the authentication informatin -- and expands the scopes before it can refresh the authentication.  Maybe try it first thing next time you sit down to hack on Taskcluster things, before opening any other page on the site.

**Comment by MooseJ** [comment]
@djmitche I was just able to reproduce the bug. Yeah it seems to happen if I haven't used the taskcluster app for a while, like about an hour for me. It works again right after a refresh. 

I'll take a closer look at when the scopes get expanded and when the authentication gets refreshed

**Comment by djmitche** [comment]
Awesome!  A bit of me was worrying it was just me :)

**Comment by MooseJ** [comment]
I was trying to reproduce the bug by running the ui and web server locally, but I can't seem to get the option to sign in with Github to work

I have the option to sign in with credentials, but then the client won't have any scopes, and I am unable to add scopes to that client.

Any idea what I should do next? Is there a test client I can use to sign in that has scopes, or is the a way to add scopes to a client.  Or is there a way to get Github sign in working when running locally

**Comment by djmitche** [comment]
Getting sign-in to work locally is pretty hard -- GitHub apps are intended to work with "real" sites, not local development.  I think it may be easier to get to the bottom of this with the developer tools on the "real" site -- maybe putting a breakpoint on the render method, and watching the network tools to see what network transaction happens between renders?

I suspect that this won't be reproducible if signing in with credentials.  That said, you can use https://community-tc.services.mozilla.com/auth/clients to create a client, as long as that client matches an `auth:create-client:<clientId>` scope in your [profile](https://community-tc.services.mozilla.com/profile).  So a clientId something like `github:1234/MooseJ` (but with different digits).

**Comment by djmitche** [comment]
I haven't seen this in a while.. I'll close as irreproducible and re-open if I see it again (which, knowing my luck, will be in 20 minutes)
