### ISSUE TITLE
New taskcluster UI: List of tasks doesn't use full height.

### ISSUE THREAD

**Issue by pocmo** [taskcluster/taskcluster#231]
The list of tasks doesn't use the full height of my browser window. In the following screenshot there are a lot of tasks, but I can only scroll the list in a small rectangle/window:

![screenshot_2019-02-14 taskcluster](https://user-images.githubusercontent.com/89638/52795200-97ef7080-3071-11e9-86ae-31acc400c2cf.png)

Task: https://taskcluster-web.netlify.com/tasks/groups/fVcAa2R5Qt-sSItyLFK5Rg

**Comment by helfi92** [comment]
We are using displaying a virtualized list which requires a number for the height in order to calculate how many rows to display. That being said, we could try calculating how much space there is available before rendering the list.

**Comment by lebonganza** [comment]
Hi,
I'm new to open source contribution and I would like to start here!
Thank you.

**Comment by helfi92** [comment]
Hi @lebonganza, this issue is being taken care of in https://github.com/taskcluster/taskcluster/pull/264. Feel free to find another issue :) Happy to help.

**Comment by lebonganza** [comment]
Thanks for the quick reply.
I'm just new to all of this,I thought if an issue was open then I could work on it?

**Comment by helfi92** [comment]
> I thought if an issue was open then I could work on it

The best thing is to ask if it can be assigned to you and start working on the issue once you get a confirmation :)

**Comment by lebonganza** [comment]
Got it.
Thank you!

**Comment by helfi92** [comment]
You can also look at https://codetribute.mozilla.org/projects/taskcluster for good first bugs if that helps.

**Comment by djmitche** [comment]
@ebonganza usually we try to assign issues to people when they start working on them, but that's hard to do in github.  There are lots of good bugs out there that nobody else is working on, to get started on!
