### ISSUE TITLE
Show pending tasks in worker pool page

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#2336]
When I'm in the task group inspector, and I see I have a pending task, I can click on the link that takes me to the worker pool page showing recent tasks for that worker pool.

It would be useful on that page to show the number of pending tasks, and maybe current pool size, and max capacity, and even possibly average task time (which is most useful if pool is at max capacity). Even cooler, when we have postgres backend, would be able to see how many tasks are in the queue before the task you are looking at in the pending state in the group inspector. If you could see next to the pending label in the task group inspector, how many tasks are ahead of the pending task in the queue, that would be awesome. Then you could watch that number drop to 0, and then see the task get claimed.

OK I realise this is a mix of feature requests, I guess I mostly wanted to highlight that we have some cool opportunities to provide some extra data that might be informative for users, and that in future when we have a postgres backend, we'll have even more opportunities.

So maybe this issue can just be about showing the pending count / pool size / max capacity of a worker pool when you click a link from the task group inspector to the worker pool of a task, and the other ideas we can discuss once we have the postgres backend in place.

**Comment by helfi92** [comment]
> So maybe this issue can just be about showing the pending count / pool size / max capacity of a worker pool when you click a link from the task group inspector to the worker pool of a task,

We can use the WorkerPool graphql query to get that information.

https://github.com/taskcluster/taskcluster/blob/7f19e8098cfc797ebea8d8fbf88e63dcee7549b9/services/web-server/src/graphql/WorkerManager.graphql#L75

Example:

```graphql
query WorkerPoolSummary {
  WorkerPool(workerPoolId:"proj-bors-ng/ci") {
    pendingTasks
    config
  }
}
```

Pending count would be `pendingTasks`. Max capacity can be found inside `config`. @petemoore by pool size, do you mean `capacityPerInstance`?

**Comment by djmitche** [comment]
Be careful about assuming things about the shape of data that are not defined in the documentation.  Not every workerPool has a `config.maxCapacity`, and potentially it could mean something totally different for some worker pools.

**Comment by petemoore** [comment]
OK maybe pending count is enough for a first stab, and that is well-defined. I've noticed that if we navigate up one level, we see the pending count already, but this would save one extra click.

So for example, if I am looking at https://community-tc.services.mozilla.com/provisioners/proj-firefoxreality/worker-types/ci-linux which I reached from a given task, I don't see the pending count directly, but if I navigate up one level by clicking on "proj-firefoxreality" I think see the pending count per worker type, and can find "ci-linux" in the list to know what the pending count is for proj-firefoxreality/ci-linux. It would therefore be nice to have this pending count directly on the https://community-tc.services.mozilla.com/provisioners/proj-firefoxreality/worker-types/ci-linux page.

Agree with dustin that we probably should hold off with pool size and max capacity for now. Thanks!

**Comment by djmitche** [comment]
Also worth noting that this is going to be completely rewritten in the "Worker UI" project, if that affects the level of investment it warrants..

**Comment by lotas** [comment]
@petemoore do you think we can close this one now? I feel like some of the issues were fixed already, some are in progress in different tickets

**Comment by petemoore** [comment]
> @petemoore do you think we can close this one now? I feel like some of the issues were fixed already, some are in progress in different tickets

I think the big thing it still misses is seeing the tasks that have been created but not claimed yet.

**Comment by petemoore** [comment]
@lotas Is this covered by the work we are planning in 2023 H2?

**Comment by lotas** [comment]
@petemoore somewhat yes I believe, we are going to make it possible to see what tasks are pending, so they can be later shown in the UI as well
