### ISSUE TITLE
[UI] Loading circle is momentarily not centred

### ISSUE THREAD

**Issue by worldomonation** [taskcluster/taskcluster#235]
**Describe the bug**
When the page is loading, the loading circle (or spinner) is not centred until the side and top bar appear.

**To Reproduce**
1. Access a task, such as [this](https://taskcluster-web.netlify.com/tasks/PEQi4rYBSR6QQ-fXGLUE_g)

**Expected behavior**
Either:
- loading circle first appear in the dead centre of the browser window, then relocate when the side and top bar loads.
or
- side and top bar are prioritized to be drawn on screen first, thereby not requiring the loading circle to relocate.

**Screenshots**
Attached.
<img width="1197" alt="screen shot 2019-02-14 at 11 47 14" src="https://user-images.githubusercontent.com/6549265/52813550-e0496700-304e-11e9-9fec-b3082c73994c.png">
<img width="1213" alt="screen shot 2019-02-14 at 11 47 11" src="https://user-images.githubusercontent.com/6549265/52813552-e0496700-304e-11e9-8af2-d48ad5c83901.png">

**Platform (please complete the following information):**
 - OS: macOS
 - Browser: Firefox Nightly 
 - Version: 67.0a1

**Additional context**
I understand this is a very superficial issue, though I feel it affects the first time perception of users.

**Comment by helfi92** [comment]
Agreed. We should have this fixed.
