### ISSUE TITLE
Deleting roles

### ISSUE THREAD

**Issue by owlishDeveloper** [taskcluster/taskcluster#2386]
This probably applies to deleting other things, not just roles, but I noticed this when working with roles in the UI.

1. Feature request: can we have a Delete button in the table so that I don't have to open a role editor to delete a role? It would be one click less.

2. Once the role is deleted and the role table is loaded, the deleted role appears in that table. I need to refresh the page to make the role disappear. It would be nice if I didn't have to do it.

**Comment by helfi92** [comment]
> This probably applies to deleting other things, not just roles, but I noticed this when working with roles in the UI.
> 
>     1. Feature request: can we have a Delete button in the table so that I don't have to open a role editor to delete a role? It would be one click less.
> 

Yep, we can. I'll go ahead and create a separate issue listing all the views that need to be changed.

>     2. Once the role is deleted and the role table is loaded, the deleted role appears in that table. I need to refresh the page to make the role disappear. It would be nice if I didn't have to do it.

I just created https://github.com/taskcluster/taskcluster/pull/2392 to have this fixed :)

**Comment by owlishDeveloper** [comment]
Thank you Hassan! Closing this one because new issues were open
