### ISSUE TITLE
[UI] Add a delete action in roles, clients, secrets, hooks views

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#2393]
Feature initially proposed in https://github.com/taskcluster/taskcluster/issues/2386#issue-568468798.

**Describe the bug**
In order to delete something from (e.g., https://community-tc.services.mozilla.com/auth/roles), a user needs to click on the role to delete, then click/hover on the triple dot fab button on the lower right then click on "Delete". That's a lot of clicks that we can perhaps avoid by having the list of hooks show a delete icon beside the name.

**To Reproduce**

1. Go to https://community-tc.services.mozilla.com/auth/roles

**Expected behavior**
A delete icon is shown beside each role. Clicking on the delete icon should behave the same way as the one in the speed dial (triple dots). In other words, it should first show a confirmation dialog prior to performing the actual delete.

**Taskcluster version**
v24.3.0

**Additional context**
Once we have a good idea about the implementation, we'll probably need to do the same on the following views:
* https://community-tc.services.mozilla.com/auth/clients
* https://community-tc.services.mozilla.com/secrets
* https://community-tc.services.mozilla.com/hooks

**Comment by crystalarc** [comment]
@helfi92 I'd like to work on this one.

**Comment by helfi92** [comment]
Awesome! Go for it.

**Comment by mushie101** [comment]
Heyya is someone already working on this? I was wondering If i could pick this issue up.

**Comment by crystalarc** [comment]
@mushie101 Yeah, I'm, sorry for the delay, I was busy lately.

**Comment by helfi92** [comment]
@crystalarc Are you working on this?

**Comment by crystalarc** [comment]
@helfi92 Yeah, half-done, will finish it soon.

**Comment by virgilt** [comment]
@helfi92 Is this still being worked on or may I work on it?

**Comment by crystalarc** [comment]
@virgilt you can take it, I didn't get to it

**Comment by virgilt** [comment]
@crystalarc Ok, thanks for getting back to me 👍🏻

**Comment by mrsVelena** [comment]
@helfi92 I'd like to work on this.

**Comment by djmitche** [comment]
Sounds good!  Have you gotten Taskcluster set up for development already?

**Comment by mrsVelena** [comment]
> Sounds good! Have you gotten Taskcluster set up for development already?

Not yet. Following directions on Development Process page to set up what I might need.

**Comment by mrsVelena** [comment]
I made changes only for the Roles page for now. If these changes are ok, I'll change other views the same way.

**Comment by djmitche** [comment]
Oh, I forgot there were other views involved, so I'll re-open this.

**Comment by mrsVelena** [comment]
@djmitche, @helfi92, I am trying to add "delete" functionality on the Hooks page and encountered a difficulty with adding "delete" button next to each hook. It looks like MuiTreeView is a custom component and I don't have means to change view of its items. Could you give me some advice on how to get around this problem? Thanks.

**Comment by djmitche** [comment]
@mrsVelena it might be easiest to remove use of the tree view there and just list hooks out -- like we do for other things.

In fact, that's the only use of MuiTreeView, so removing it will simplify the UI nicely.

**Comment by mrsVelena** [comment]
Ok. Got it. Thanks.

**Comment by lotas** [comment]
I believe we can close this one, it was mostly implemented, and hooks page deserves a bigger refactoring to make it more usable: expand/collapse all, search/filter, etc.
