### ISSUE TITLE
[docs] Provide a way to link to site-specific docs

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#2395]
The docs site is currently identical for every deployment.  But deployments are different, and it would make sense to have some links to specific documentation for each deployment.

Let's add a UI configuration parameter, similar to `ui.banner_message`, that gives some links that are substituted into the docs, if they are set.

I would like to allow multiple links, since there are several places users may want to substitute their own docs.  At least:
 * A top-level link on https://docs.taskcluster.net/docs
 * A link describing how to get credentials, for use in https://docs.taskcluster.net/docs/tutorial (useful for #2394)

We will also need to build a React component that can display content if the link exists, and do nothing if the link does not exist.  Something like

```
<IfSiteSpecificDoc doc="deployment-info">
  <h2>Information About This Deployment</h2>
  <p>You can find out more about this deployment of Taskcluster <SiteSpecificDocLink doc="deployment-info">here</SiteSpecificDocLink>.</p>
</IfSiteSpecificDoc>
```

**Comment by djmitche** [comment]
@helfi92 I'm curious what you think about this idea -- maybe there are other things we could include too?

**Comment by helfi92** [comment]
Do you have an example of a link that you want to include to a specific deployment? Why not show it on every deployment?

**Comment by djmitche** [comment]
For Firefox-CI, https://firefox-source-docs.mozilla.org/taskcluster/taskcluster/ would be an example.

**Comment by helfi92** [comment]
Ah I see. Thanks for the link.

> A top-level link on https://docs.taskcluster.net/docs

By top level link, do you mean an external link that would be added after "Resources" both as a menu in the left drawer navigation and a card in the main content of that view?

> We will also need to build a React component that can display content if the link exists, and do nothing if the link does not exist. Something like

Where were you thinking of displaying this on the docs site?

**Comment by djmitche** [comment]
> By top level link, do you mean an external link that would be added after "Resources" both as a menu in the left drawer navigation and a card in the main content of that view?

I was just thinking of including it as a card, actually.

> Where were you thinking of displaying this on the docs site?

Primarily for the cord on the "Resources" page, but also in the tutorial where there would be additional links such as "how to get credentials" or "what worker pool to use for a tutorial task".

**Comment by helfi92** [comment]
> Primarily for the card on the "Resources" page, but also in the tutorial where there would be additional links such as "how to get credentials" or "what worker pool to use for a tutorial task".

Got it. That makes sense to me.

**Comment by djmitche** [comment]
Thinking more about this, it will probably be important to "call out" these additions visually so that users know they are seeing something site-specific.  Something like

![image](https://user-images.githubusercontent.com/28673/76760696-7aa14000-6764-11ea-8f5e-56402e911246.png)

So, I'm envisioning something in the tc-ui config:

```yaml
ui:
  deploymentSpecifics:
    rootUrl: https://dustin-dev.taskcluster.net
    githubIntegrationUrl: https://github.com/apps/dustindev-tc-integration
```

Then a component that generates a card like the above, with something like

```html
<DeploymentSpecific>
To add the integration to a GitHub organization or repository on this deployment of Taskcluster, add <a href="{{githubIntegrationUrl}}">this GitHub application</a>.
</DeploymentSpecific>
```

My thinking is that we could use a common, simple templating engine in there, and just hide the entire card if the template rendering fails because a referenced context variable is not set.

This would be safe since we're always using values from the config, not the user, for the templates.  I don't think we'd ever do anything terribly complicated with the templating, but using an existing engine means that we could add conditionals where necessary, for example.

This allows a few neato things:
 * Tools in the UI (not just docs) can use this component to provide context for users
 * Docs can use this component to link directly to the current deployment (for example, linking to `/worker-manager` for the list of worker pools in the manual) using `{{rootUrl}}`.  Then those direct links will appear in a deployment's docs, but not on https://docs.taskcluster.net.

**Comment by djmitche** [comment]
work in progress at https://docs.taskcluster.net/docs/reference/integrations/github/api#badge
