### ISSUE TITLE
[UI] Update react-router to v5

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#2396]
**Describe the bug**
Renovate opened a PR in https://github.com/taskcluster/taskcluster/pull/1728 but turns out something broke. Let's try to fix this.

**Additional context**
Check out the [releases](https://github.com/ReactTraining/react-router/releases?after=v5.0.1) page of react-router to see what has changed.

**Comment by aryamanpuri** [comment]
@helfi92 Can I take up this issue?

**Comment by aryamanpuri** [comment]
Sorry @helfi92 , I got stuck in some other work.
I bumped the version to 5.0.0 but got stuck as it is showing the same error.
I will try to debug this and respond to you shortly.

**Comment by helfi92** [comment]
Sounds good. https://github.com/taskcluster/taskcluster/pull/1728#pullrequestreview-362689060 suggests there was a breaking change so it will probably involve figuring out what changed in their react-router changelog/releases page then fixing it here.

**Comment by helfi92** [comment]
Are you still working on this @aryamanpuri?

**Comment by aryamanpuri** [comment]
Sorry @helfi92, I am bit busy nowadays.
Please reassign this issue to someone else.

**Comment by helfi92** [comment]
No worries!
