### ISSUE TITLE
Make it easier to find API docs from the reference documentation

### ISSUE THREAD

**Issue by gijsk** [taskcluster/taskcluster#2398]
I opened https://docs.taskcluster.net/docs/reference/core/index to find the documentation for the index APIs, and I was disappointed. The page does a great job explaining concepts behind the index, but doesn't actually contain the API doc. Nor did I see an obvious link to it - I ignored the "next page" and "previous page" buttons at the bottom, one of which would have helped me.

It would be nice if there was a more obvious pointer to the API docs in the body of the page.

**Taskcluster version**
88017ca6eef228b8ec042e8f05f028c814d135a2

**Comment by helfi92** [comment]
One thing we could perhaps do is add the next/previous buttons at the top. We would then have these buttons at the top and bottom of each page.

**Comment by gijsk** [comment]
I think moving next/previous would *maybe* help a bit, but to be quite honest I would still be very likely to just skim over them, because if I'm looking at a reference section, "next" and "previous" are no use to me. It's like looking in an index; I don't really mind what got sorted alphabetically before/after the thing I'm interested in. I'm not reading the entire book / website, I just want the bit I'm interested in. I think on all the pages where there's a general intro, an obvious link to the "API" page for the same entry would be helpful.

In this particular page, there are even some API methods called out (i.e. `insertTask`) but they are not linked to the documentation for that API method, either.
