### ISSUE TITLE
could not terminate livelog exposure: close tcp [::]:xxxxx: use of closed network connection

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#2408]
https://community-tc.services.mozilla.com/tasks/SKpYULcgTwmvtVklJwy25g/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FSKpYULcgTwmvtVklJwy25g%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log
```
2020/02/24 18:29:36Z Created dir: /task_1582568020/taskcluster/workers/generic-worker/testdata/TestRunAfterUserCreation/task_1582568020/generic-worker
2020/02/24 18:29:36Z WARNING: Not purging previous task directories/users since config setting cleanUpTaskDirs is false
--- PASS: TestRunAfterUserCreation (0.05s)
FAIL
FAIL	github.com/taskcluster/taskcluster/v25/workers/generic-worker	159.888s
```

The failure occurred on the landing of https://github.com/taskcluster/taskcluster/pull/2389 but the landing after that one succeeded.

@petemoore can you take a look?

**Comment by petemoore** [comment]
The real issue was little disguised, further up the log:

```
--- FAIL: TestPublicDirectoryArtifact (2.13s)
    helper_test.go:230: Scheduled task Z84gjoj3QVilvG9FmEYJ4A
    helper_test.go:243: Worker exited with exit code 0 as required.
    helper_test.go:319: Task Z84gjoj3QVilvG9FmEYJ4A resolved as completed/completed as required.
    artifacts_broken_on_docker_test.go:42: Was expecting 3 artifacts, but got 2
```

When go tests fail, I typically open the raw log and search for `FAIL:` and that usually finds it (as the failure can be a little buried).

The cause of that intermittent failure seems to be a problem the test had with livelogging. If you go to https://community-tc.services.mozilla.com/tasks/Z84gjoj3QVilvG9FmEYJ4A#artifacts you will see indeed there was no live log. :-/

**Comment by petemoore** [comment]
Looks like several failed for the same reason:
```
--- FAIL: TestPublicDirectoryArtifact (2.13s)
--- FAIL: TestConflictingFileArtifactsInPayload (2.31s)
--- FAIL: TestFileArtifactTwiceInPayload (1.51s)
--- FAIL: TestArtifactIncludedAsFileAndDirectoryInPayload (2.15s)
--- FAIL: TestChainOfTrustUpload (2.44s)
--- FAIL: TestProtectedArtifactsReplaced (2.41s)
```

The error in the [worker logs](https://community-tc.services.mozilla.com/tasks/SKpYULcgTwmvtVklJwy25g/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FSKpYULcgTwmvtVklJwy25g%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log#L14403-14405) was e.g.

```
2020/02/24 18:26:58Z WARNING: could not create livelog: WARNING: Livelog terminated early with error 'exit status 1' and output:
2020/02/24 18:26:58 input server listening... :43264
2020/02/24 18:26:58 listen tcp :43264: bind: address already in use
```

**Comment by petemoore** [comment]
So probably it failed to shutdown on a previous task. Perhaps a race condition killing the livelog, and the next task's livelog starting up? I bet that's it! Perhaps the process kill was non-blocking, i.e. didn't wait for the kill to complete.

**Comment by petemoore** [comment]
I see things like [this](https://community-tc.services.mozilla.com/tasks/SKpYULcgTwmvtVklJwy25g/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FSKpYULcgTwmvtVklJwy25g%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log#L2360) in the log:

```
2020/02/24 18:24:17Z WARNING: could not terminate livelog exposure: close tcp
```

@djmitche Do you know what might cause this?

**Comment by djmitche** [comment]
I see the "use of closed network connection" error quite frequently in otherwise-successful runs even before the merge to monorepo (such as [this one](https://community-tc.services.mozilla.com/tasks/AOeeTXnBSfiEfPlHAc68lw/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FAOeeTXnBSfiEfPlHAc68lw%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log)).  So this is easily reproduced locally.  

https://golang.org/pkg/net/http/#Server.Close
> Close immediately closes all active net.Listeners and any connections in state StateNew, StateActive, or StateIdle. For a graceful shutdown, use Shutdown. 

but here we are trying to close both the `http.Server` (wrapped in an `httpProxy`) and the listener it is using.  So that's an easy fix -- I'll make a PR.  But, this is also a warning and, I think, not related to what we're seeing here.

---

POSIX `kill` is not a blocking operation: it delivers a signal to the other process and returns.  So it's possible that there's a race condition here in starting a new process before the old dies.  

https://golang.org/pkg/os/#Process
> Kill causes the Process to exit immediately. Kill does not wait until the Process has actually exited. This only kills the Process itself, not any other processes it may have started. 

However, it seems that once this error occurs, it "sticks" for multiple subsequent tests.  So I suspect we're failing to kill the process at all.

Here's the lead-up to the first instance of the "address already in use" error:

```
2020/02/24 18:26:16Z Creating task feature Live Log...
2020/02/24 18:26:16Z Creating task feature OS Groups...
2020/02/24 18:26:16Z Creating task feature Mounts/Caches...
2020/02/24 18:26:16Z Creating task feature Supersede...
2020/02/24 18:26:16Z Starting task feature Live Log...
2020/02/24 18:26:16Z Starting task feature OS Groups...
2020/02/24 18:26:16Z Starting task feature Mounts/Caches...
2020/02/24 18:26:16Z Stopping task feature Mounts/Caches...
2020/02/24 18:26:16Z Stopping task feature OS Groups...
2020/02/24 18:26:16Z Stopping task feature Live Log...
2020/02/24 18:26:16Z Redirecting public/logs/live.log to public/logs/live_backing.log
2020/02/24 18:26:17Z WARNING: could not terminate livelog exposure: close tcp [::]:44419: use of closed network connection
...
2020/02/24 18:26:18Z Starting task feature Live Log...
2020/02/24 18:26:18Z WARNING: could not create livelog: WARNING: Livelog terminated early with error 'exit status 1' and output:
2020/02/24 18:26:18 input server listening... :43264
2020/02/24 18:26:18 listen tcp :43264: bind: address already in use
```

It looks like the task at 18:26:16 started and almost immediately stopped "Live Log".  Maybe the process hadn't yet started when `LiveLog.Terminate()` was called? There's a mutex here -- maybe to make the go race detector happy -- but it doesn't actually address that race condition.  But in that case I would expect a panic because `l.cmd.Process` was nil.

The port 43264 is in the "ephemeral port" range, meaning that the kernel assigns ports randomly in this range.  So it's quite possible that in this case, the kernel has assigned this port to another process.  This happens more often than you'd think, and we've taken pains in the services to let the kernel give us a port number rather than hard-coding one.  You can do this by setting the listener address to `:0` and getting the port with `_, portStr, _ := net.SplitHostPort(listener.Addr().String())` (`workers/generic-worker/expose/local.go` has an example of this).

**Comment by djmitche** [comment]
I think what remains is ephemeral port collisions, which we can fix if we see again..
