### ISSUE TITLE
"Unauthorized: Bad mac" when viewing private log artifacts.

### ISSUE THREAD

**Issue by jschwartzentruber** [taskcluster/taskcluster#2427]
**Describe the bug**

When a task generates private `.log` artifacts, those logs are not viewable from the online log viewer.

**To Reproduce**

1. Create a task with private `.log` artifacts.
2. Once task has completed, click on the private log under Artifacts.
3. See error message.

**Expected behavior**

Private logs should be viewable using the log viewer.

**Taskcluster version**

v25.4.0

**Screenshots**

![image](https://user-images.githubusercontent.com/4673461/75563393-474a7b80-5a18-11ea-9a5d-ce6179790c03.png)

**Platform (please complete the following information):**

 - OS: Linux
 - Browser: Firefox
 - Version: 75.0a1 (nightly 2020-02-27)

**Additional context**

The task is: https://community-tc.services.mozilla.com/tasks/NRWtkio3QtizFc4Ccvuo-g

@djmitche [indicated on Matrix](https://chat.mozilla.org/#/room/#taskcluster:mozilla.org/$ROl5hL9xVmmEHPrWI_GsWGV6OEZ5tvEzgy5GmO9j9b8) this is probably the bewit being generated incorrectly.

The full response to the failing request is:
```
{
  "code": "AuthenticationFailed",
  "message": "Unauthorized: Bad mac\n\n---\n\n* method:     getArtifact\n* errorCode:  AuthenticationFailed\n* statusCode: 401\n* time:       2020-02-28T02:28:07.513Z",
  "requestInfo": {
    "method": "getArtifact",
    "params": {
      "0": "project/fuzzing/private/logs/live.log",
      "taskId": "NRWtkio3QtizFc4Ccvuo-g",
      "runId": "0",
      "name": "project/fuzzing/private/logs/live.log"
    },
    "payload": {},
    "time": "2020-02-28T02:28:07.513Z"
  }
}
```

**Comment by djmitche** [comment]
You can reproduce this by copying the URL from the browser and running `curl -v <url>`.

I had a look at the bewit when I ran this.  I don't see anything wrong.  It's a base64-encoded string containing `<clientId>\<expiry>\<accessToken>\<ext>`.  For me, the clientId was `github/28673|djmitche`, the expiry was 30 minutes from the time of the request, and the `ext` contained a certificate with a reasonable set of scopes and appropriate `start` and `expiry` properties.

I didn't check any of the signatures, but it seems those are what's wrong -- perhaps a different URL is being signed than is being returned??

I didn't have permission to read the artifact, but should have gotten a 403 InsufficientScopes.

**Comment by helfi92** [comment]
The line that generates the URL for the private artifact in web-server is https://github.com/taskcluster/taskcluster/blob/024bd6f2ad0d511ed1943475a7de2e838433373d/services/web-server/src/loaders/artifacts.js#L52

**Comment by jschwartzentruber** [comment]
btw, I can access the artifact via the Go CLI client. It looks normal.

**Comment by djmitche** [comment]
I suspect this is fixed in v27 (so some time ago).  Can you confirm @jschwartzentruber ?

**Comment by jschwartzentruber** [comment]
It is not. Same error here: https://community-tc.services.mozilla.com/tasks/aqXDpGutSqq9zL8n9ebojg#artifacts (TC v28.0.0)

**Comment by djmitche** [comment]
I think this is superseded by #2992
