### ISSUE TITLE
[UI] API endpoint description font size

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#2442]
**To Reproduce**

1. Go to http://localhost:5080/docs/reference/platform/auth/api#createClient

**Actual behavior**

The description has the same font size as "Description"

![Screen Shot 2020-03-03 at 10 33 20 AM](https://user-images.githubusercontent.com/3766511/75791462-98b97a00-5d3a-11ea-8ed9-cabb42a512c3.png)

**Expected behavior**

The description has a smaller font size than "Description". It should look similar to the text under "Signature"

**Taskcluster version**
v25.4.0

**Additional context**
The code for that is in `ui/src/views/Documentation/Reference/Entry.jsx`.

**Comment by championshuttler** [comment]
@helfi92 Can i take this up?

**Comment by helfi92** [comment]
Go for it :-)
