### ISSUE TITLE
New UI: can't search for a task in task group list

### ISSUE THREAD

**Issue by glandium** [taskcluster/taskcluster#245]
When you have thousands of tasks in a group, like in https://taskcluster-web.netlify.com/tasks/groups/OedTF0wpS6Cg_AJUpFdcvw, you can't search in the page to find the task you'd be looking for, because not all tasks are actually in the page from the browser's perspective.

**Comment by helfi92** [comment]
Agreed. A search component could be added to the view which could either filter the list or make the scroller jump to the first task name it matches.

**Comment by helfi92** [comment]
STR:

1. Navigate to https://taskcluster-web.netlify.com/tasks/groups/BcRLZJV4SgSIj_qCGznsrg

**Expected**: There is a search component that allows searching for task group names by filtering out task names that don't match the search value.

**Actual**: There is no search component.

Why not use something like CTRL + F? Because we don't render the full list of tasks at any time. We only render enough for the user to see. This allows rendering over 10,000 tasks without slowing down the browser.

**Comment by Manish-Giri** [comment]
Hi, I'd like to work on this. Would appreciate any getting-started pointers!

**Comment by helfi92** [comment]
Hi @Manish-Giri. The first step is to have the front end and server running. The client can be found in https://github.com/taskcluster/taskcluster/tree/master/ui and the server in https://github.com/taskcluster/taskcluster/tree/master/services/web-server. Once you're able to view the list of task groups in localhost:5080/tasks/groups/BcRLZJV4SgSIj_qCGznsrg then you're all set.

https://github.com/taskcluster/taskcluster/blob/master/ui/src/views/Tasks/TaskGroup/index.jsx is the entry point for that particular view. You will probably want to use our [`Search`](https://github.com/taskcluster/taskcluster/blob/master/ui/src/components/Search/index.jsx) to implement the search component. I think we can put the search component right above the list of tasks.

**Comment by vansjyo** [comment]
@helfi92 How can the local server have the tasks groups or the tasks? Do we need to be running something else too?

**Comment by iFlameing** [comment]
@vansjyo you have to start two servers on in the UI folder and one in the web-server. just open the terminal in these folders and install dependencies. After that just run yarn start, now you are good to go and you can see the UI at localhost 5080. just one note please configure  user-config.yml to getting started with the server.

**Comment by vansjyo** [comment]
@iFlameing I have already set it up as instructed by @helfi92 in the last comment and it runs successfully. However, the task groups is empty.
![screenshot from 2019-03-01 16-49-49](https://user-images.githubusercontent.com/25532570/53635194-58fd1580-3c42-11e9-913c-f35077bb6b79.png)

**Comment by iFlameing** [comment]
@vansjyo then you have to just add the id of  task and you see the task group like this
![screenshot from 2019-03-01 16-56-53](https://user-images.githubusercontent.com/33936987/53635443-26075180-3c43-11e9-962d-6aa396204d4c.png)

here is the link for localhost
http://localhost:5080/tasks/groups/BcRLZJV4SgSIj_qCGznsrg

**Comment by vansjyo** [comment]
@iFlameing Can you please tell me how should the user-config.yml file in the web-server look like(the root_url) ? I guess I might have made some mistake there.

**Comment by iFlameing** [comment]
just put these configs in user-config.yml.
```
 defaults:
  taskcluster:
      rootUrl: https://taskcluster.net
```

**Comment by vansjyo** [comment]
@iFlameing Thanks. That worked.

**Comment by iFlameing** [comment]
@vansjyo if you are getting started with this issue please ask to @Manish-Giri and @helfi92 before.

**Comment by helfi92** [comment]
@iFlameing is correct. Before working on the issue, it would be nice to see if @Manish-Giri is currently working on this issue since they claimed it 2 days ago :)

**Comment by Manish-Giri** [comment]
Hi, sorry. Yes, I am currently working on this. I'll be sending a PR soon.

**Comment by helfi92** [comment]
@Manish-Giri Many people are asking for this feature. I have an implementation of this feature on my local machine which I think we can use. I'll create a PR and you can let me know what you think.
