### ISSUE TITLE
New UI feels slower

### ISSUE THREAD

**Issue by glandium** [taskcluster/taskcluster#248]
Loading a large task group feels slower than in the old UI, despite being actually faster, because it only displays the list once it has everything while the old UI would start displaying things before everything is downloaded.

Displaying one task, though, _is_ slower.

**Comment by helfi92** [comment]
The new UI should now feel a lot faster. We no longer wait for the whole list to load before displaying it in the UI. Resolved in https://github.com/taskcluster/taskcluster/commit/fd837dfde1cce4e813c054c41091f9c1d57bc519.
