### ISSUE TITLE
Missing line wrapping in generic-worker payload schema docs

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#2518]
**Describe the bug**
The descriptions in https://community-tc.services.mozilla.com/docs/reference/workers/generic-worker/multiuser-windows-payload are unreadable since there is no line wrapping, and the text goes off-screen.

**To Reproduce**

Click [here](https://community-tc.services.mozilla.com/docs/reference/workers/generic-worker/multiuser-windows-payload) and read the descriptions.

**Expected behavior**

Text is shown in full, and lines are wrapped so that all text is visible.

**Taskcluster version**
v28.0.0

**Screenshots**
<img width="848" alt="Screenshot 2020-03-17 at 11 37 02" src="https://user-images.githubusercontent.com/190790/76848331-c7a81380-6843-11ea-8721-3193448afbf9.png">

**Platform (please complete the following information):**

 - macOS Mojave 10.14.6
 - firefox 74.0 (64 bit)

**Comment by helfi92** [comment]
This is by design. It's not the best, but we considered the trade-offs and decided to only show the text on hover. For more information on that, see comment/thread in https://github.com/taskcluster/taskcluster/pull/2412#issuecomment-592580364.
