### ISSUE TITLE
Add monitoring for DB activity

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#2522]
* DB pool client counts
 * function invocation counts (aggregate?)

**Comment by djmitche** [comment]
WIP in `issue2522` on my repo.

**Comment by helfi92** [comment]
Completed in https://github.com/taskcluster/taskcluster/commit/979653f465104abb27709e7532128a9cf5963dbc.

**Comment by djmitche** [comment]
Not quite done yet -- still need to rebase and land https://github.com/taskcluster/taskcluster/pull/2571/commits/a5072f023182373398c02091328bb1ece3f67ac7 from #2571.

**Comment by djmitche** [comment]
And note to self, #2600.
