### ISSUE TITLE
Build an api-based importer for secrets, clients, etc. that are signed / encrypted in production

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#2523]
We cannot import these items from production into a staging or development environment because they contain secrets that are encrypted and/or signed (and anyway we don't want such secrets in staging / dev environments).

Let's build a very temporary importer that uses the TC API to import them, without the secret data.  For example, it can list the clients and their scopes on production, and then create new clients with the same scopes in staging/dev, but with a different accessToken.  Similarly for secrets, etc.

**Comment by djmitche** [comment]
https://github.com/djmitche/tc-api-importer

@helfi92 do you think this will be useful for you?

**Comment by helfi92** [comment]
Yes, that would be helpful. Thank you. Should we also add the signed/encrypted tables in the web-server service?

**Comment by djmitche** [comment]
I think it's OK to just initialize those to blank tables.  They don't have CRUD API methods, so they can't be copied using this approach.
