### ISSUE TITLE
web ui: feature request: sticky sorting

### ISSUE THREAD

**Issue by aerickson** [taskcluster/taskcluster#2534]
It would be sweet if the sorting order was injected into the URL. Whenever I refresh the URL below the sort order needs to be set again (e.g. if I'm sorting by resolved, newest first).

https://firefox-ci-tc.services.mozilla.com/provisioners/terraform-packet/worker-types/gecko-t-linux/workers/packet-sjc1/machine-13

Thanks!

**Comment by helfi92** [comment]
Good idea. Thanks for bringing this up.

**Comment by ashishzingh** [comment]
hey!! can i take up this issue?

**Comment by helfi92** [comment]
Hey @ashishzingh. Your help will be greatly appreciated. Go for it.

We do something similar in https://firefox-ci-tc.services.mozilla.com/provisioners/xpi-1/worker-types/b-linux where we have the URL tied to the "Filter By" ([source](https://github.com/taskcluster/taskcluster/blob/62cbb7a62eddda0b45e0b917f55247c97207550f/ui/src/views/Provisioners/ViewWorkers/index.jsx#L237-L248)) dropdown. Toggling that dropdown will change the query part of the URL. We will want to do something similar to the link in the issue description but on the table columns.

**Comment by helfi92** [comment]
How is it going @ashishzingh? Let me know if you had questions :-)

**Comment by ashishzingh** [comment]
@helfi92  just did the setup for ui and web-server . i am a newbie so am going through the codebase and learning graphQL, will post my doubts soon.

**Comment by helfi92** [comment]
Sounds good to me. Thanks for spending the time looking at this. The change will most probably just be inside the `ui` directory and will not involve any changes to the graphql query.

**Comment by ashishzingh** [comment]
@helfi92  i am trying to figure out how to get the url in the prop of WorkerTable component so that i can tie the url to the table columns.
The prop and State on clicking sort is structured as below
<img width="609" alt="doubt" src="https://user-images.githubusercontent.com/13368710/78331122-060f3380-75a3-11ea-90d1-cd0719cf0a7a.PNG">

can you guide me ?

**Comment by ashishzingh** [comment]
@helfi92  I have finished the feature but have some linting errors. i am new to open source. what should be by next steps before raising a PR. on doing yarn test 23 test cases are passing.

**Comment by helfi92** [comment]
You can fix most linter errors by running `yarn lint --fix` from within the `ui` directory. Once this is done, feel free to create a PR.
