### ISSUE TITLE
Set statementTimeout to 30s in server processes

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#2566]
tc-notify has
```
statementTimeout: process === 'server' ? 30000 : 0,
```
and I think all services should have the same.  This aborts queries after 30s in server processes (those serving APIs) and lets them run forever in other processes (e.g., expiration).

**Comment by helfi92** [comment]
Completed in https://github.com/taskcluster/taskcluster/commit/10b8db02858e4af4843cc3d2958615f1a048ce35.
