### ISSUE TITLE
New UI: Width of some elements

### ISSUE THREAD

**Issue by srfraser** [taskcluster/taskcluster#258]
The width of some UI elements could ideally be wider, such as the search box, which truncates contents:

<img width="247" alt="screenshot 2019-02-15 at 18 09 53" src="https://user-images.githubusercontent.com/5933384/52875716-efaeda00-314c-11e9-84d8-20621795d8d9.png">

Or the payload expansion, which requires side-scrolling. Would it be better with Payload/Extra expansions in their own box, so that they can use the full width of the screen instead of the 1/3 width column?
<img width="400" alt="screenshot 2019-02-15 at 18 10 03" src="https://user-images.githubusercontent.com/5933384/52875721-f2113400-314c-11e9-95e6-9870dcc32b10.png">

**Comment by helfi92** [comment]
> The width of some UI elements could ideally be wider, such as the search box, which truncates contents:

Clicking on the search box should expand the component. We truncate the search box when not being used so that it we could fit other things in the app bar for smaller screens:

![screen shot 2019-02-15 at 1 51 10 pm](https://user-images.githubusercontent.com/3766511/52877762-f4fa2d80-3128-11e9-8ad8-56a3aef16a44.png)

> Would it be better with Payload/Extra expansions in their own box, so that they can use the full width of the screen instead of the 1/3 width column?

I'll experiment with this idea.

**Comment by helfi92** [comment]
That definitely didn't sit well :(

![screen shot 2019-02-15 at 2 19 58 pm](https://user-images.githubusercontent.com/3766511/52879633-9e432280-312d-11e9-8045-cd1895bb3d67.png)

**Comment by srfraser** [comment]
> That definitely didn't sit well :(
> 
> ![screen shot 2019-02-15 at 2 19 58 pm](https://user-images.githubusercontent.com/3766511/52879633-9e432280-312d-11e9-8045-cd1895bb3d67.png)

Thank you for trying it out. I'm not sure what the best option is there, but with Tab Center down the left side, then the page's own left menu, there isn't a lot of room left for the expanded json. 

Perhaps I need to adjust my own layout and stop using tabs down the side.

Or Copy icons for Task Definition, Payload and Extra so we can paste the json elsewhere? Random idea rather than necessarily great suggestion.

**Comment by helfi92** [comment]
Ah, perhaps allowing the left drawer to collapse would improve the UX. There's an issue already filed for that [here](https://github.com/taskcluster/taskcluster/issues/225).

**Comment by helfi92** [comment]
The left drawer is no longer permanent.

![screen shot 2019-02-26 at 1 59 52 pm](https://user-images.githubusercontent.com/3766511/53438899-db7d9f00-39ce-11e9-939d-5b8004065e68.png)

**Comment by helfi92** [comment]
Closing this as resolved.
