### ISSUE TITLE
Add UI banner to community 1 week before migration

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#2594]
[Instructions](https://github.com/taskcluster/taskcluster/blob/caec22bccd3481e7d0f02c091ce1bc8eba3263a7/ui/README.md#banner-message) on how to add a banner.

**Comment by helfi92** [comment]
The message could perhaps be "Community-TC will be down for maintenance on 3/17".

**Comment by helfi92** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1627324.

**Comment by edunham** [comment]
Banner is added. 

As Dustin mentioned in that bug: "Let's get a note out to tools-taskcluster@ and TaskCluster-"Announce <taskcluster-announce@lists.mozilla.org> announcing this.

**Comment by helfi92** [comment]
> Banner is added.
> 
> As Dustin mentioned in that bug: "Let's get a note out to tools-taskcluster@ and TaskCluster-"Announce [taskcluster-announce@lists.mozilla.org](mailto:taskcluster-announce@lists.mozilla.org) announcing this.

Done.
