### ISSUE TITLE
[postgres] Grant access to cloudops for hassan's deployment

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#2595]
Grant bpitts, edunham, and dustin project viewer access to hassan’s deployment as well provide superuser login to the postgresql instance

**Comment by helfi92** [comment]
<img width="590" alt="Screen Shot 2020-04-02 at 9 24 37 AM" src="https://user-images.githubusercontent.com/3766511/78254374-cfaeb700-74c3-11ea-96ff-a14e620b52d3.png">

It looks like I am missing permissions to grant viewer access to my deployment that's in taskcluster-dev. @djmitche / @imbstack Are you able to provide me with permissions?

**Comment by djmitche** [comment]
I think this is a project-owner-only thing?  Hopefully @imbstack can work on this when he's back, as he's the owner of the project iirc.

**Comment by helfi92** [comment]
Ah, I see. I'll reach out to him tomorrow.
