### ISSUE TITLE
Add GraphQL docs

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#2598]
From slack:

> I scared myself pretty badly with the query logging in web-server yesterday before I realized that the inputs go into variables and not the query

GraphQL can be a bit overwhelming for users that don't interact with it on a daily basis. Let's add some documentations on how to add an endpoint (i.e., graphql, resolver, loader) and on how to use the playground.

**Comment by ajinkabeer** [comment]
Hello @helfi92, I would love to work on this but I have a very basic GraphQL knowledge. What do you think?

**Comment by helfi92** [comment]
Hey! I actually already started working on this on a separate branch. Is there a different task you are interested in tackling? If not, we can always create new issues :-)

**Comment by ajinkabeer** [comment]
Oh, you already started working on it, that's awesome. Yes, I will be on the lookout for new issues :)
