### ISSUE TITLE
[UI] Search terms with empty table results

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#2607]
**To Reproduce**

1. Go to https://firefox-ci-tc.services.mozilla.com/secrets
2. Search for something that doesn't exist (e.g., foo-bar-foo)

**Expected behavior**
"No  items for this page with search term foo-bar-foo." is shown.

**Actual behavior**

"No items for this page." is shown. It's hard to infer whether there are no results for this page or no results for this search term.

<img width="1482" alt="Screen Shot 2020-04-06 at 8 36 38 AM" src="https://user-images.githubusercontent.com/3766511/78559077-c08c7980-77e1-11ea-9701-2e698b4e923f.png">

**Taskcluster version**
28.0.0

---

Once this is done for the secrets view, we will want to replicate this to all of the other tables we use in the UI.

**Comment by rohanharikr** [comment]
On it!

**Comment by helfi92** [comment]
Thanks @rohanharikr!

**Comment by julienpan** [comment]
Hi, is this issue still open ?

**Comment by helfi92** [comment]
Not at the moment. There's a pull-request fix for that already.
