### ISSUE TITLE
AssertionError [ERR_ASSERTION]: readDbUrl is required

### ISSUE THREAD

**Issue by aryamanpuri** [taskcluster/taskcluster#2637]
**Describe the bug**
Unable to start the graphql server

**To Reproduce**

Follow the dev docs to produce local web server using https://github.com/taskcluster/taskcluster/blob/master/dev-docs/development-process.md#hacking-on-the-ui

**Error Log**
```
AssertionError [ERR_ASSERTION]: readDbUrl is required
    at Function.setup (/home/aryaman/taskcluster/libraries/postgres/src/Database.js:54:5)
    at Object.exports.setup (/home/aryaman/taskcluster/db/src/setup.js:6:25)
    at setup (/home/aryaman/taskcluster/services/web-server/src/main.js:188:48)
    at /home/aryaman/taskcluster/libraries/loader/src/index.js:109:33
    at new Promise (<anonymous>)
    at /home/aryaman/taskcluster/libraries/loader/src/index.js:107:18
```

**Additional context**
I don't if there are any server code changes that are giving this error.

**Comment by helfi92** [comment]
We're in the midst of a migration today. Once the migration is done, I think you would be able to have it point at the community deployment db url as a default. For now, I think you can just `git checkout 012c24e4073df8a8e67c41836ec9977324ba5571` (commit right before the db change) and then try again. It should work.

**Comment by djmitche** [comment]
Credentials for that URL won't be available.  I think we'll have to run postgres in docker from here on out, even for running the web-server process.

**Comment by aryamanpuri** [comment]
It is not working. Giving the same error. Hold on until the migration is done.
>  For now, I think you can just `git checkout 012c24e4073df8a8e67c41836ec9977324ba5571` (commit right before the db change) and then try again. It should work.

**Comment by djmitche** [comment]
Do the docs in #2638 help?

**Comment by rohanharikr** [comment]
@aryamanpuri if you are still facing this issue, try these commands
```export READ_DB_URL=postgresql://postgres@localhost/postgres

export WRITE_DB_URL=postgresql://postgres@localhost/postgres
```
thanks @helfi92 !
