### ISSUE TITLE
Figure out phase 2 importing story

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#2646]
Figure out an efficient way to import data out of tables created in phase 1 to phase 2 tables. We will be moving a lot of data and so we want to minimize the time it takes to do so in order to avoid going over the TCW (8 hours).

Have a better understanding of how postgres behaves around ALTER and so on.

**Comment by helfi92** [comment]
2 strategies for importing the data:

1. Clone the table and then use ALTER & UPDATE

This would involve creating a clone of the entities tables, then using ALTER to modify the table as we find fit.

2. Create an empty table and then use INSERT

```sql
CREATE TABLE new_table
(
  field1 text,
  field2 text,
  ...
);
```

```sql
INSERT INTO new_table(field1, field2, ...)
(
  SELECT FROM ...
)
```

---

It turns out ALTER is not super great on large tables. The process involves touching two rows for row that is modifed (one to delete the row and another to create using the correct format). So copying all of the data then using alter & update to modify is probably not the most efficient way and consumes plenty of resources. I am leaning towards the second strategy.

Performance boosters:
* Increase value of [temp_buffers](https://www.postgresql.org/docs/9.6/runtime-config-resource.html). Default is 8mb. Using RAM instead of disk should improve performance. I don't see why we can't bring this up during the migration to a value like 5GB.
* drop indexes from table during migration for faster inserts
* Increase value of [shared_buffers](https://www.postgresql.org/docs/9.4/runtime-config-resource.html). Default is `128 MB` but they recommend setting it 25% of the DB RAM for DB machines with > 1 GB RAM.
* Update in batches to avoid disk writes. For large updates, postgres will load pages into memory and modify them, but will eventually run out of memory. When that happens, the fallback is to write to disk which is slow.

Thoughts on using the 2nd strategy?

**Comment by djmitche** [comment]
For the second option, could we be sure that concurrent modifications to the old table were reflected in the new table?  Insertions?  Deletions?

I suspect that to avoid those issues we'd have to lock the old table during the transaction, which if the transaction takes more than a few seconds would result in a service outage (or downtime if planned).

If an alter can occur with less locking and downtime, that might be a better strategy even if it requires more space and time.

**Comment by djmitche** [comment]
A few other half-baked ideas that have been knocking about in my head:
 * We could use multiple upgrade "steps", for example a step adding a new table and updating the functions to read from both old and new, but only write to the new table.  Then a later step can move data out of the old table and into the new, knowing that nothing is writing to the old table
 * Rows in some tables are never modified, and only deleted when expired.  This is true of Tasks, and might be true for others.  We could take advantage of that.  Having a better idea of which tables we need to worry about due to their size, and the characteristics of those tables, would help.
 * Currently upgrades run in a single transaction.  We could modify that code to allow running them in multiple, shorter, transactions where it's possible

**Comment by helfi92** [comment]
> For the second option, could we be sure that concurrent modifications to the old table were reflected in the new table? Insertions? Deletions?

Hm, I was under the impression that taking a downtime would be okay. In that case, the "multiple upgrade" step you suggested might make more sense to ensure no downtime.

> We could use multiple upgrade "steps", for example a step adding a new table and updating the functions to read from both old and new, but only write to the new table. Then a later step can move data out of the old table and into the new, knowing that nothing is writing to the old table

That's a good idea to avoid using a downtime. I think that shouldn't be too complicated and also removes the burden of trying to fit the full upgrade in the TCW. Perhaps we could write to the db in small batches rather than one by one (to avoid an upgrade step that takes forever) and then inform users that TC will be slower than usual but that things are still working.

> Rows in some tables are never modified, and only deleted when expired. This is true of Tasks, and might be true for others. We could take advantage of that. Having a better idea of which tables we need to worry about due to their size, and the characteristics of those tables, would help.

If we can have a general solution for all tables, then I think that would minimize the chances of screwing up somewhere.

> Currently upgrades run in a single transaction. We could modify that code to allow running them in multiple, shorter, transactions where it's possible

That's a really good idea. It would help in the "multiple steps" strategy to slowly move everything form the old to the new tables incrementally without hogging the DB.

**Comment by djmitche** [comment]
> Hm, I was under the impression that taking a downtime would be okay. In that case, the "multiple upgrade" step you suggested might make more sense to ensure no downtime.

I think downtime is OK, but we should try to avoid it.  It will mean waiting for a TCW, which will be six weeks now.

**Comment by helfi92** [comment]
> I think downtime is OK, but we should try to avoid it.

There's definitely a way to avoid it, but obviously there are trade-offs which don't seems to be that bad. Ok, let's avoid it :)

**Comment by djmitche** [comment]
We met and talked about this and still have a number of unknowns. We're both continuing to work on different services, and going to regroup and see what we've run into and how to do this after gathering a bit more experience.

**Comment by helfi92** [comment]
Still trying to figure this out but so far the tentative plan is to migrate things table by table where each migration will be split in two parts. The parts are db migration and service migration. The db migration will involve touching code under the db directory and the service migration would involve rewriting the affected service to use the new db methods.

**Comment by imbstack** [comment]
Just looking through for issues for the next sprint and saw that this one is "done" (at least we've figured out how we're doing it) so I'm closing it now. Please reopen if I'm mistaken
