### ISSUE TITLE
Websocktunnel leaks memory and cpu

### ISSUE THREAD

**Issue by sciurus** [taskcluster/taskcluster#2657]
Over time, the amount of memory used by the firefox ci deployment of websocktunnel grows. The rate of cpu utilization also grows. See the graphs below. I believe the drops in them are due to restarts.

<img width="1189" alt="Screen Shot 2020-02-19 at 17 17 20" src="https://user-images.githubusercontent.com/677595/74881703-cdd9cb80-533b-11ea-9dcb-f755ec60bdee.png">
<img width="1181" alt="Screen Shot 2020-02-19 at 17 17 57" src="https://user-images.githubusercontent.com/677595/74881706-cf0af880-533b-11ea-95be-65ea7ed7968d.png">

**Comment by BenGHolmes** [comment]
Hi, I'm interested in working on this! I've got websocktunnel running locally and have successfully connected from a simple client that I wrote.

As I understand it, the next steps are to connect several clients and viewers at the same time, leave that running for a while, and see if the memory and CPU usage grows over time like it does in the plots above. Do I understand that correctly, or is there a better way for me to reproduce the issue?

**Comment by jwhitlock** [comment]
> As I understand it, the next steps are to connect several clients and viewers at the same time, leave that running for a while, and see if the memory and CPU usage grows over time like it does in the plots above. Do I understand that correctly, or is there a better way for me to reproduce the issue?

I don't know if the multiple clients and viewers are necessary (a single client, or a series of single clients may work), but yes, the next steps are to try to reproduce the memory leak locally, so it can be debugged using ``pprof``. It is not clear to me that the issue will reproduce locally - it may only be an obvious issue at the scale of firefox-ci.

**Comment by BenGHolmes** [comment]
I haven't been able to reproduce this locally. I tried many viewers making simultaneous connections to 20 clients without seeing a measurable increase in memory usage. Any thoughts on whether I should be adding more connections or increasing the amount of data transferred per connection?

**Comment by jwhitlock** [comment]
Thanks for trying to reproduce this @BenGHolmes. Before you do more work, let me see if this issue is still happening in Firefox-CI. I don't recognize the graph, so I'll need to ask around to see where this data is captured.

**Comment by BenGHolmes** [comment]
@jwhitlock, any update on the issue?

**Comment by jwhitlock** [comment]
@BenGHolmes, no one I contacted could determine how to get this data, and the two who worked on this in Feb 2020 are no longer with Mozilla.

I'm going to close this for now, and it can be reopened if future ops detects it again. Or, maybe it was fixed by a unknown change, and you confirmed that it is no longer an issue 🤷.
