### ISSUE TITLE
[tc-proxy] Bug when rewriting url with %2F%2F

### ISSUE THREAD

**Issue by owlishDeveloper** [taskcluster/taskcluster#2721]
https://github.com/taskcluster/taskcluster-proxy/issues/44

**Comment by djmitche** [comment]
I suspect this was related to some automation in the Go HTTP libraries.  Let's see if this is still happening and fix it if so.

**Comment by djmitche** [comment]
The details are in the linked issue, but basically URLs containing `%2f%2f` are being rewritten incorrectly by the proxy.

I can confirm from some experimentation that this is occurring before the HandleFunc is even being called.

**Comment by djmitche** [comment]
https://golang.org/pkg/net/http/#ServeMux
>  ServeMux also takes care of sanitizing the URL request path and the Host header, stripping the port number and redirecting any request containing . or .. elements or repeated slashes to an equivalent, cleaner URL.
