### ISSUE TITLE
New UI: Getting to task from id in log more complicated

### ISSUE THREAD

**Issue by pocmo** [taskcluster/taskcluster#274]
Quite often I need to go through the following flow:

* Open a task that was triggered by a hook, e.g. this one: https://tools.taskcluster.net/groups/eOMZxg6lS-mst_yYNZBTKg
* Go to the log and get the group ID of the scheduled task
* Paste the group id into the box at the top and then look at the new graph.

In the new UI that is way more complicated:
https://taskcluster-web.netlify.com/tasks/groups/eOMZxg6lS-mst_yYNZBTKg

* I click on the task and need to find the link to the log (that's more hidden now in the list of data that shows up)

* In the list of logs I can't jump to the end any more, I think ("follow log"). So I have to grab the toolbar and scroll down manually.

* I copy the task id but I can't jump to the task immediately. I have to go to "view task" first and then search for it there.

* When I finally end up on the task page I do not see the whole group. I have to do one more click to get to the group.

* Getting back to the group from the log of a task is also complicated; it requires me to mostly rely on my browser's back stack - and once back I need to refresh the group list.

**Comment by pocmo** [comment]
Sorry, a bit vague. :)

**Comment by helfi92** [comment]
>  I click on the task and need to find the link to the log (that's more hidden now in the list of data that shows up)

There's a "View Live Log" list item above the Artifacts dropdown which should get you to the Log faster. Perhaps we should make that a bit clearer by adding one of these "LOG" labels:

![screen shot 2019-02-19 at 12 45 51 pm](https://user-images.githubusercontent.com/3766511/53035837-5c272300-3444-11e9-9226-d18148e04891.png)

>  In the list of logs I can't jump to the end any more, I think ("follow log"). So I have to grab the toolbar and scroll down manually.

I'll create a separate bug to bring that back :) We currently only show the "follow log" button for logs that are currently "live".

> * I copy the task id but I can't jump to the task immediately. I have to go to "view task" first and then search for it there.
> * When I finally end up on the task page I do not see the whole group. I have to do one more click to get to the group.

A faster flow would be to click "Task Groups" from the navigation drawer and paste the text in the search bar. The whole process would become:

1.  Click on "View Live Log"
2. Copy the group ID of the scheduled task
3. Click on "Task Groups"
4. Paste the group ID in the search box

I agree with you that we need some way to jump to a different task group/task ID in less clicks. I'll try to think about ways we could improve the workflow.

**Comment by djmitche** [comment]
@helfi92 is there anything left to do here?

**Comment by helfi92** [comment]
The only thing I think that is left to do is possibly to figure out a way to jump to a task and task group ID from the log viewer in less clicks. I've filed https://github.com/taskcluster/taskcluster/issues/818 to tackle this issue. We should be okay closing this issue now.
