### ISSUE TITLE
Remove material-ui-treeview

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#2749]
We started using https://github.com/helfi92/material-ui-treeview/ in https://community-tc.services.mozilla.com/hooks because material-ui did not have a tree view component available at the time, but now they do. Let's move away from what we were using and use material-ui's [TreeView](https://material-ui.com/api/tree-view/#treeview-api) component. The [demo](https://material-ui.com/components/tree-view/#rich-object) shows that they support rendering the same tree structure that we have so switching to it shouldn't be too demanding from our end.

**Comment by rohanharikr** [comment]
I would love to work in this project!

**Comment by helfi92** [comment]
All yours.
