### ISSUE TITLE
[UI] Bring back the "Follow Log" button for logs that are not live

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#275]
STR:

1. Navigate to https://taskcluster-web.netlify.com/tasks/eOMZxg6lS-mst_yYNZBTKg/runs/0/logs/https%3A%2F%2Fqueue.taskcluster.net%2Fv1%2Ftask%2FeOMZxg6lS-mst_yYNZBTKg%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log

Actual: There is no follow log button
![screen shot 2019-02-19 at 1 06 04 pm](https://user-images.githubusercontent.com/3766511/53037058-32bbc680-3447-11e9-8f37-5f6a20b7dbcb.png)

Expected: There is a follow log button
![screen shot 2019-02-19 at 1 05 37 pm](https://user-images.githubusercontent.com/3766511/53037062-351e2080-3447-11e9-88b1-fc4fbd167be3.png)

We currently don't show the "follow log" button when a log has finished running. Let's make it show at all times. 

Relates to https://github.com/taskcluster/taskcluster/issues/274.

**Comment by Aditya-Kolla** [comment]
I'll try.

**Comment by helfi92** [comment]
Awesome, go for it.

**Comment by Aditya-Kolla** [comment]
@helfi92 Please verify if I've done what is required.
