### ISSUE TITLE
[UI] Add a "Sign In" button to the app bar

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#277]
Now that https://github.com/taskcluster/taskcluster/issues/225 is completed, the navigation bar is closed by default on the site. The current flow of signing-in when the user is not on the home page requires 2 clicks:

1. Open the navigation bar
2. Click on Sign In

Let's make that process easier. In addition to the sign in button in the left drawer, let's add one in the app bar.

When the user is not signed in, we should show a button with a label "Sign In". Upon logging in, we should replace the button with the Avatar icon button that we currently use in the left drawer navigation. For example, my avatar after logging in looks like this:

![screen shot 2019-02-19 at 3 51 17 pm](https://user-images.githubusercontent.com/3766511/53046528-3f97e480-345e-11e9-88a0-f474d21f3564.png)

Clicking on the avatar should show the same dropdown as the one in the left navigation drawer:

![screen shot 2019-02-19 at 3 53 37 pm](https://user-images.githubusercontent.com/3766511/53046660-88e83400-345e-11e9-863c-b30244be29ee.png)

**Comment by iFlameing** [comment]
@helfi92  I would like to work on this issue.

**Comment by helfi92** [comment]
Go for it.

**Comment by iFlameing** [comment]
@helfi92 I implemented the above feature but there is lot of code repeation is going on because most of code is already their in usermenu component. what should I do?

**Comment by helfi92** [comment]
You can try to minimize code duplication by extracting common code into their own file.

**Comment by helfi92** [comment]
Resolved in https://github.com/taskcluster/taskcluster/commit/6ada7a7519e5e8ff2b79199ca9635df795ff1d97.
