### ISSUE TITLE
Show worker tasks from most-recent to least-recent

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#2776]
**Describe the bug**

The Worker historic tasks view has a default task ordering that lists the tasks from oldest to newest, but would be much nicer to reverse the order and list from newest to oldest.

See e.g. https://community-tc.services.mozilla.com/provisioners/proj-taskcluster/worker-types/gw-ci-macos/workers/proj-taskcluster/63-135-170-250

**Comment by helfi92** [comment]
If you click on the "Started" column, it will re-order the list. The link will also be deep linked so it can be shared for example:

https://community-tc.services.mozilla.com/provisioners/proj-taskcluster/worker-types/gw-ci-macos/workers/proj-taskcluster/63-135-170-250?sortBy=started&sortDirection=desc

Does that help?
