### ISSUE TITLE
Please add build URL to version.json in Taskcluster Docker image

### ISSUE THREAD

**Issue by edunham** [taskcluster/taskcluster#2781]
Version.json currently looks like this: 

```
$ docker run --rm --entrypoint=cat taskcluster/taskcluster:v29.3.0 version.json
{"version": "v29.3.0", "commit": "8d0600004fcaff7c1661e650bc48e424e7d409de", "source": "https://github.com/taskcluster/taskcluster", "build": "NONE"}
```

Cloudops would like to use this version information to validate Docker images when deploying them to Mozilla-run clusters. However, to validate a Docker image we also need the `build` parameter to contain the URL of the build which created the image, in order to pass the validation checks at https://github.com/mozilla-services/cloudops-infra-deploylib/blob/master/deploylib/docker.py#L207-L219 (basically checking that the image came from a build we trust). 

Please add the URL of the build that created the Docker image to the image's version.json. Thanks!

(relatedly, https://bugzilla.mozilla.org/show_bug.cgi?id=1636193)

**Comment by djmitche** [comment]
What would that look like?

**Comment by djmitche** [comment]
It would need to be a link to a TC raw log, and should contain the image digest somewhere in that log.

**Comment by djmitche** [comment]
The version.json is currently hardcoded in the Dockerfile, so making that dynamic would be a bit of work, and we'd need to make it conditional on actually being built in a task (since we also build locally for development).
