### ISSUE TITLE
Speed Dial disappears on click

### ISSUE THREAD

**Issue by klahnakoski** [taskcluster/taskcluster#2805]
In the bottom right there is a triple-dots icon

<img src="https://user-images.githubusercontent.com/2334429/81614120-8f3d3580-93ad-11ea-99d2-a168f3cbc34b.png" width=60>

Hovering over the icon show the "trigger hook" option.

<img src="https://user-images.githubusercontent.com/2334429/81614210-b1cf4e80-93ad-11ea-9cc3-efdfd027f04d.png" width=200>

When I move my pointer to "trigger hook" it disappears, reverting back to the triple-dots, and  preventing me from clicking it.

Previously, the menu worked, but was difficult to use.  In theory the procedure is:

1) **move** pointer to the triple-dots
2) **move** pointer to the trigger action (**do not click**)
3) **click** on trigger action

The **move-move-click** motion is not intuitive; The natural tenancy is to click the triple-dots to opening it; instead, clicking on the triple-dots closes the menu (the triple-dots is actually an "X", but only when you are over it).  My muscle memory is programmed to click on menus to expand them, and I left trying to open the menu multiple times:

1. Move to triple-dots 
2. Muscle memory clicks on the triple-dots
3. Menu is now closed 
4. Goto 1

Please change this to 

1) **move** over the triple-dots does nothing, except maybe show "more actions"
2) **click** on the triple-dots expands the menu, **and it stays open** 
3) **move** to action desired
4) **click** to active desired action, and minimize the menu 

The **move-click-move-click** procedure follows the common procedure for most other menus; widget state changes only when clicked.

**Comment by djmitche** [comment]
I find this annoying, too, but maybe this is the way such elements typically work?  Could we easily remove the hide-on-click functionality?

**Comment by djmitche** [comment]
We don't have the UX expertise on the team to know whether the current or proposed functionality is the appropriate functionality.  So I think this is best left as-is.
