### ISSUE TITLE
[UI] Add a view for blacklist notifications

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#282]
Blocks https://bugzilla.mozilla.org/show_bug.cgi?id=1520918.

**Comment by helfi92** [comment]
Regarding the view, I was thinking of having:

* A "+" button in the bottom right (similar to http://localhost:5080/tasks/create). Hovering on the button should show a tooltip.
* A table using the `DataTable` component that we have under `ui/src/components/DataTable` with 3 columns:
  - "Notification Type"
  - "Destination"
  - A column with an empty title to hold the delete buttons

* Clicking a column should change the sorting of the table similar to the functionality in http://localhost:5080/provisioners/aws-provisioner-v1

* If there is an error somewhere (e.g., when deleting without the proper scopes), an error panel should appear at the top with the error. You can use the `ErrorPanel` component that we have in `ui/src/components/ErrorPanel`.

**Comment by OjaswinM** [comment]
I feel this is enough to get started. I'll ping you if I have any doubts along the way :)

**Comment by OjaswinM** [comment]
@helfi92 actually, won't it be better if we use `ConnectionDataTable` as the notification list results are in from of a grpahql connection?

**Comment by helfi92** [comment]
> @helfi92 actually, won't it be better if we use `ConnectionDataTable` as the notification list results are in from of a grpahql connection?

Yep!
