### ISSUE TITLE
docs.taskcluster.net not updating

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#2841]
Its current revision is 5e011a8c213f46f3198a0aa1870ca8e4e94d4ab7 from May 7.

**Comment by helfi92** [comment]
That's probably because the CI has been failing on master.

**Comment by djmitche** [comment]
Oh, sweet, so should be fixed now.

**Comment by djmitche** [comment]
Well, stuff's still failing (d-w and g-w) on master.. I'll leave it open until we get a green build.

**Comment by djmitche** [comment]
There are at least a couple of green checkmarks since May 7, but it is still on the same revision :(

**Comment by djmitche** [comment]
![image](https://user-images.githubusercontent.com/28673/82214040-268d1600-98e3-11ea-86b5-fc5bc7d1123b.png)
deploy cancelled?

**Comment by djmitche** [comment]
This got fixed -- it's on the latest commit now.
