### ISSUE TITLE
[client-web] Bundle size increase in v9.0.0

### ISSUE THREAD

**Issue by edmorley** [taskcluster/taskcluster#285]
**Describe the bug**
The minified bundle size of the `taskcluster-client-web` package was 92KB (18KB gzipped) in v8.1.1, but increased to 145KB (35KB) in v9.0.0:
https://bundlephobia.com/result?p=taskcluster-client-web@8.1.1
https://bundlephobia.com/result?p=taskcluster-client-web@9.0.0

This resulted in our webpack build exceeding the size threshold for the Renovate PR updating us to v9.0.0:
https://github.com/mozilla/treeherder/pull/4683
https://travis-ci.org/mozilla/treeherder/jobs/497201761#L539

**Expected behavior**
The package size is kept as small as is possible.

**Additional context**
Looking at the size breakdown chart at the bottom of the bundlephobia page, it seems that perhaps `crypto-js` is not listed as an external? Maybe doing so would help allow webpack to tree-shake the unused imports more easily?

Another thing that would help is if an ES6 module version was included in the package (listed under the `module` key in `package.json`), since webpack could then tree shake it?

**Comment by helfi92** [comment]
> if ES6 module version was included

The ES6 version is the default export of the package. I don't know if adding a `module` property would help in this case.

> it seems that perhaps `crypto-js` is not listed as an external? Maybe doing so would help allow webpack to tree-shake the unused imports more easily?

I think that might be it :) We could certainly try.

**Comment by edmorley** [comment]
It seems be to packaged as CJS? See the `module.exports` here:
https://unpkg.com/taskcluster-client-web@9.0.0/build/index.js

**Comment by helfi92** [comment]
> It seems be to packaged as CJS

Apologies for my confusion. You're absolutely right. Is there a way to generate an es6 version? I don't seem to see  a `module` value for webpack's `libraryTarget` property. https://webpack.js.org/configuration/output/#outputlibrarytarget. Would having the `module` property point to [`src/index.js`](https://github.com/taskcluster/taskcluster/blob/b34aacc27c4e96565b598abf7c638e8fa3ce5530/clients/client-web/src/index.js) be good enough?

**Comment by helfi92** [comment]
Added crypto-js to webpack's externals in `v9.1.0`.

**Comment by sarah-clements** [comment]
Unfortunately, the bundle size is still high: 144.7kB (Minified 34.5 kB) https://bundlephobia.com/result?p=taskcluster-client-web@9.1.0

**Comment by djmitche** [comment]
It looks like crypto-js is still in there..

**Comment by edmorley** [comment]
webpack cannot tree shake CJS modules - releasing taskcluster as a dual CJS (under `main`) and ESM (under `module`) library would likely be the best next step :-)

**Comment by helfi92** [comment]
I published v9.2.0. https://bundlephobia.com/result?p=taskcluster-client-web@9.2.0 (17.6
kB minified).

@sarah-clements Let me know if that works for you.

**Comment by helfi92** [comment]
Closing as resolved but feel free to re-open if you are still experiencing an issue.

**Comment by sarah-clements** [comment]
Thanks Hassan!
