### ISSUE TITLE
[UI] Reopen the section menu when clicking "next"

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#286]
STR:

1. Navigate to https://taskcluster-web.netlify.com/docs/reference
2. Click on "Reference" on the side menu. This should collapse the Reference section.
3. Click on the "NEXT" button (bottom of the page)

Expected: The Reference section in the navigation menu re-opens.
Actual: The Reference section is collapsed.

**Comment by sudipt1999** [comment]
I would like to work on this @helfi92

**Comment by helfi92** [comment]
Go for it.

**Comment by sudipt1999** [comment]
@helfi92  I have started the web server and its showing
`yarn run v1.13.0
$ NODE_ENV=development webpack

webpack is watching the files…

Hash: d900399b73e3bafcffb2
Version: webpack 4.29.0
Time: 2860ms
Built at: 02/23/2019 1:58:48 AM
   Asset     Size  Chunks             Chunk Names
index.js  494 KiB   index  [emitted]  index


No Pulse namespace defined; no Pulse messages will be received.


Web server running on port 3050.

Open the interactive GraphQL Playground and schema explorer in your browser at:
        http://localhost:3050/playground`

How can reach the url  locally ! Kindly give some pointers .

**Comment by iFlameing** [comment]
@sudipt1999 You have to open another terminal and run the yarn start in UI folder to interact with url locally. After that, the website is accessible on localhost:5080.

**Comment by sudipt1999** [comment]
Thanks @iFlameing  !

**Comment by helfi92** [comment]
Thanks @iFlameing for helping. @sudipt1999 Let me know if you had any questions :)

**Comment by sudipt1999** [comment]
@helfi92  I am sorry but I am not able to recognize which jsx file if for sidebar ! Kindly help me out ! Thank You

**Comment by helfi92** [comment]
The file used for the documentation sidebar is https://github.com/taskcluster/taskcluster/blob/master/ui/src/components/Dashboard/DocsSidebarList.jsx. Hope that helps.

**Comment by sudipt1999** [comment]
Yeah surely will do ! Thank you

**Comment by sudipt1999** [comment]
@helfi92 
https://github.com/taskcluster/taskcluster/blob/master/ui/src/utils/constants.js
this is where the content of the page is present but I am unable to find the children of reference . Kindly guide me here!

**Comment by iFlameing** [comment]
@sudipt1999 can you explain what are you trying to do so that I can help you.

**Comment by sudipt1999** [comment]
On the link above when on reference section two buttons appear on the main
div next and prev when we click next or prev we want our refence section to
collapse! But i am unable to find the child components of reference ,
because there will be the buttons that can toggle the collapase bar

**Comment by iFlameing** [comment]
@sudipt1999 I think this is the file you are searching for https://github.com/taskcluster/taskcluster/blob/master/ui/src/components/Dashboard/DocsSidebarList.jsx

**Comment by sudipt1999** [comment]
@iFlameing  I have already checked that out but that dosen't contain the children of reference component . I am lost there I guess! Any pointer would be really appreciated! @helfi92

**Comment by helfi92** [comment]
@sudipt1999 The list of children is coming from https://github.com/taskcluster/taskcluster/blob/master/ui/src/autogenerated/docs-table-of-contents.json. Hope that helps.

**Comment by vansjyo** [comment]
@helfi92 I have fixed the bug and made a pull request. Please have a look.

**Comment by sudipt1999** [comment]
@vansjyo I was working on that issue .

**Comment by helfi92** [comment]
@vansjyo In the future, we ask that contributors ask if they can work on an issue before committing  to it, please. @sudipt1999 I'm sorry for that :(

**Comment by sudipt1999** [comment]
No problem ! Will work on some another one then.

**Comment by vansjyo** [comment]
@helfi92 . I am sorry about that. I am a newbie to open source. Since the label for this issue was unassigned, I thought I could work on it.  @sudipt1999. I apologize.

**Comment by sudipt1999** [comment]
Don't be sorry , even I am not much experienced with open source . It's was
not even your mistake either , I was a bit slow to fix the bug .

On 28-Feb-2019 10:40 PM, "Vanshika Gupta" <notifications@github.com> wrote:

@helfi92 <https://github.com/helfi92> . I am sorry about that. I am a
newbie to open source. Since the label for this issue was unassigned, I
thought I could work on it. @sudipt1999 <https://github.com/sudipt1999>. I
apologize.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/taskcluster/taskcluster/issues/286#issuecomment-468355245>,
or mute the thread

**Comment by helfi92** [comment]
Resolved in https://github.com/taskcluster/taskcluster/commit/2e5ea8038ce24b771d398bb2c64c3d7118675319 🎉.
