### ISSUE TITLE
[UI] Add search feature in /purge-caches

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#2865]
**To Reproduce**

1. Go to https://community-tc.services.mozilla.com/purge-caches

**Expected behavior**
You should be able to search for a cache

**Actual behavior**
There is no easy way to search for a cache name. You need to click the next page button until you find the cache you are looking for.

Like other views, we should add a functional search box in the upper right. Here's an example: https://community-tc.services.mozilla.com/worker-manager of a search box showing in the UI
The code for that example begins in https://github.com/taskcluster/taskcluster/blob/6200d45870f0f3c05aefcef6a814988378b62106/ui/src/views/WorkerManager/WMViewWorkerPools/index.jsx#L138-L142

**Taskcluster version**
v29.6.0

**Comment by helfi92** [comment]
Let's also increase the number of entries per page to 1000.

**Comment by ajinkabeer** [comment]
Hey @helfi92, this one looks interesting. Can I work on this?

**Comment by helfi92** [comment]
Hey @ajinkabeer 👋 It's all yours!
