### ISSUE TITLE
[UI] Table styling in docs

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#287]
STR:

1. Navigate to https://taskcluster-web.netlify.com/docs/reference/platform/auth/references/events#clientUpdated
2. Look at the table under the "Routing Keys" header

**Expected**: The styling looks similar to a table that is being used outside docs (e.g., https://taskcluster-web.netlify.com/provisioners/aws-provisioner-v1)

**Actual**: My eyes are bleeding. The spacing and border coloring is off.

![screen shot 2019-02-22 at 3 17 31 pm](https://user-images.githubusercontent.com/3766511/53268773-01e0c900-36b5-11e9-8dc5-911575bb0eab.png)

**Comment by Aditya-Kolla** [comment]
I would like to work on this.

**Comment by helfi92** [comment]
Go for it :)

**Comment by Aditya-Kolla** [comment]
@helfi92 Hey, sorry I was away for a bit. 
Any suggestions how I may get started with this?

**Comment by helfi92** [comment]
Hey @Aditya-Kolla, I'm working on rewriting the way we style each components that is being rendered in docs and so I'm not sure anymore if you should focus your energy this issue (or anything that relates to the documentation section of the site) since it will most likely overlap with my current change. I forgot to comment in here. Apologies for not letting you know earlier. Let me know if you want to work on a different issue, I have a couple in mind that I haven't created yet :)

**Comment by Aditya-Kolla** [comment]
Hello @helfi92, It's completely fine. I hadn't started any comprehensive work on it anyway. 
And yes, I'm interested to work on another issue :D

**Comment by helfi92** [comment]
Would you like to work on the breadcrumb issue in https://github.com/taskcluster/taskcluster/issues?q=is%3Aopen+is%3Aissue+label%3Aui+label%3A%22good+first+issue%22?

**Comment by Aditya-Kolla** [comment]
Well, looks like someone has contacted you already. It's okay, I'll pick up another issue :smile:
