### ISSUE TITLE
add a ui page for workers that combines data from queue and worker-manager

### ISSUE THREAD

**Issue by imbstack** [taskcluster/taskcluster#2881]
This should also include a page that lists workers in a workerpool whether or not they've claimed work.

This is blocked on converting all standalone workers to static (#2926)

**Comment by imbstack** [comment]
From a card about this by @owlishDeveloper:

Examine the workers' view to make sure it includes the necessary info.

* Worker Group (since workers' view will be accessed from within worker pools - maybe this one not as a table column, but as a table subheader)
* provider ID
* WorkerPool ID (with a link to the editing interface)
* Worker ID
* Most Recent Task (from queue)
* Task State (from queue)
* Task Started & Task Resolved
* Worker Age (nee First Claim)
* Quarantine button / quarantined status
* Running capacity/tasks
* Pending capacity/tasks

Data on the task might be put in a drawer type component, so that it could be retrieved on demand?

**Comment by djmitche** [comment]
I'll build up some wireframes for this and #2882, and perhaps break it out into a few smaller issues.

**Comment by djmitche** [comment]
I sketched up some stuff for this before putting it back in the backlog

![rect1454](https://user-images.githubusercontent.com/28673/83292668-81165400-a1b8-11ea-81a8-2094a0c30727.png)

In subsequent discussion we decided that trying to write the UI such that it mixes standalone and non-standalone workers and worker pools is not a good idea, and we should build a UI that assumes that everything is registered with worker-manager, which is an assumption we can make after #2927.  If there are things not so registered, they'll be "invisible" but still work.

**Comment by djmitche** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1518928

**Comment by djmitche** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1518927 - sort by last-seen, task state, lsat-resolved

**Comment by matt-boris** [comment]
Tracking work in duplicate ticket https://github.com/taskcluster/taskcluster/issues/3060.
