### ISSUE TITLE
azure provider may leak resources on removeWorker API call

### ISSUE THREAD

**Issue by imbstack** [taskcluster/taskcluster#2884]
Reported by @djmitche:

From my read of the source:

* a call to the removeWorker API method will call the removeWorker method of the provider
* this method will call removeResource for the VM and return. Notably, it does not modify the state in the workers table
* on the next checkWorker call, when the VM has been deleted, the call to get its status will return a 404
*  checkWorker will do nothing since the state is still RUNNING

So I think that means it leaks disks and NICs. Or I've missed something in my reading of the source. I give it 50/50 odds..

**Comment by imbstack** [comment]
I'm 70% sure that it actually handles this correctly. @milescrabill will be the best person to diagnose this when he returns.

**Comment by djmitche** [comment]
Having stared at this for #2827 I think I am also 70% sure this is right.  I'll take another look.

**Comment by djmitche** [comment]
So to reproduce I:
 * stole the Azure configuration from miles' dev env and set it up in my dev env, running 30.0.2 and with a different resource group configured
 * copied the worker definition from miles' dev env and set minCapacity=1
 * watched it create a pip, a nic, and a vm+disk
 * called removeWorker
 * watched it delete all the things
 * noted #2925, which confirms that something is setting state=STOPPING in this case.

But, I still don't understand *how* that is happening.

**Comment by djmitche** [comment]
Ah, I see it now.  I had forgotten that there's an extended "Deleting" phase for VMs.  So

* removeWorker API call deletes the VM, does not change state in the workers table (the provider method returns STOPPING but the API ignores the return value)
* checkWorker runs, sees VM in Deleting state, which is one of `failProvisioningStates`, and calls removeWorker
* removeWorker returns STOPPING again
* checkWorker updates `worker.state` to `STOPPING`
* #2925 

The key thing here is that we see the VM in the "Deleting" state.  If the VM wasn't found, it would still be considered "RUNNING".  So this *is* a bug, but minor.  I'm going to put it back in the backlog as I think the best way to solve this will be some refactoring of the provider, which is already in the backlog.

**Comment by djmitche** [comment]
#3505 fixes this.  Now `removeWorker` moves the worker to the `STOPPING` state and does nothing more.  Subsequent runs of `checkWorker` will call `deprovisionResources` until that method decides it's done and marks the worker as `STOPPED`.
