### ISSUE TITLE
google provider might be hiding user errors?

### ISSUE THREAD

**Issue by imbstack** [taskcluster/taskcluster#2885]
Reported by @djmitche

Once handleOperation is called for an instance, the instance state is set to STOPPED, which means that checkWorker won't be called again. So this comment

    // Let's check back in on the next provisioning iteration if unfinished
    if (operation.status !== 'DONE') {
      return true;
    }

is incorrect. However, handleOperation is only called when the instance is not found, so perhaps the status is never not DONE?

I'm not sure if the comment should be updated, or if there's an error here that means we will be missing error messages that might be useful to the user.

**Comment by djmitche** [comment]
I'll see if I can test this out with #2921.
