### ISSUE TITLE
add a background scanner to worker-manager

### ISSUE THREAD

**Issue by imbstack** [taskcluster/taskcluster#2888]
background scanner to get orphaned instances/volumes/nics that worker-manager has lost track of. it needs to get all resources in a project and scan them to see if they're made by w-m and delete them if they're "unknown"

**Comment by helfi92** [comment]
> background scanner to get orphaned instances/volumes/nics that worker-manager has lost track of

Does this mean that worker-manager previously knew about these resources but somehow lost track of them? Why does this happen?

> it needs to get all resources in a project

What would be the way to fetch all worker resources. Do we have an endpoint for that? Do we need to create one? I see that we tag workers with a created-by/CreatedBy field but don't see an endpoint that returns this.

> scan them to see if they're made by w-m and delete them if they're "unknown"

Thoughts on simply deleting the resource if it doesn't have a created-by/CreatedBy tag prefixed with `taskcluster` and is not a static provider?

**Comment by imbstack** [comment]
Yeah, it's for things we lose track of. Ideally there's never anything there but there's a few cases that can happen:

1. A bug that we don't know about yet is leaking workers slowly
2. A bug is introduced that loses a bunch of workers quickly and we never notice
3. In the case of normal operations, we submit a request to a cloud provider to spawn a worker but crash before we can write the result into the database.

The call to fetch all resources would actually be a call to the cloud provider itselfs. Something like, `listInstances` and `listDisks`, etc. So rough steps would be to get all resources in the cloud account, filter by tags to get just ones that w-m is responsible for, and then check to see if any aren't tracked by w-m itself, deleting those ones. @ccooper has a script that roughly does this so we can just translate it into a background process hopefully.

We can't necessarily just delete things with the wrong tags because people sometimes need to run other machines in the account/project and we want to let them exist.

**Comment by ccooper** [comment]
> @ccooper has a script that roughly does this so we can just translate it into a background process hopefully.

My cleanup scripts are here: https://github.com/ccooper/cloud-cleanup

**Comment by helfi92** [comment]
The product owner has spoken and we decided to focus my energy on supporting re-registration in worker-manager instead.

**Comment by imbstack** [comment]
Nevermind, splitting this up into multiple sub-cards
