### ISSUE TITLE
New UI feedback: use a max viewport for widescreen monitors

### ISSUE THREAD

**Issue by jonalmeida** [taskcluster/taskcluster#289]
With the new UI, lists of items (e.g. task groups) are harder to see when information is separated to either end of the page.

For example, looking at this task group on a widescreen 4k monitor where the browser is fullscreen is harder: https://taskcluster-web.netlify.com/tasks/groups/OXQNcpc6SNeSUYII8attgA

This wasn't an issue with old UI since the task names were left aligned and fairly close together.

I suggest some sort of max width so that the contents are together. Other sites that do this:
- Github
- Firebase

<img width="3120" alt="screen shot 2019-02-22 at 4 37 09 pm" src="https://user-images.githubusercontent.com/1370580/53274600-cef30100-36c5-11e9-999d-ed4274f7d12e.png">

<img width="3120" alt="screen shot 2019-02-22 at 4 34 26 pm" src="https://user-images.githubusercontent.com/1370580/53272656-e202d280-36bf-11e9-9f6a-da520c52fb89.png">

**Comment by helfi92** [comment]
Good idea, thanks for bringing that up.
