### ISSUE TITLE
Add worker online status to Workers Explorer

### ISSUE THREAD

**Issue by worldomonation** [taskcluster/taskcluster#291]
**Describe the bug**
Worker Explorer shows a lot of relevant information for workers, but one piece of information that I feel is missing is whether worker is currently online or not.

This difficulty is particularly pronounced during new worker setup process such as with windows10-aarch64, where users would like to determine if a particular machine is online and ready to accept tasks. Currently, the only method I know of to determine if a machine is ready is to send a dummy task such as https://tools.taskcluster.net/groups/eaYNUEsYRkq1AY9RDnJ9_A/tasks/eaYNUEsYRkq1AY9RDnJ9_A/details.

**To Reproduce**
1. Go to https://tools.taskcluster.net/provisioners/bitbar/worker-types/gecko-t-win64-aarch64-laptop
2. Look at the list of workers.

**Expected behavior**
Workers are listed, and the current online/offline status of the workers are displayed.

**Screenshots**
Attached.

**Platform (please complete the following information):**
 - OS: n/a
 - Browser: Firefox
 - Version: 67.0a1

**Additional context**
This is an UX improvement idea, not a bug.
<img width="1219" alt="screen shot 2019-02-22 at 15 16 47" src="https://user-images.githubusercontent.com/6549265/53276721-2fc60d80-36b5-11e9-965e-e4cab2896d12.png">

**Comment by djmitche** [comment]
We don't necessarily know if a worker is online or offline -- only how recently it has contacted the queue.  For a worker with idle capacity, we expect it to be calling claimWork every minute or so.  For a worker that is active, we expect it to be calling reclaimTask every 15 minutes or so.  We could potentially use the timing of those calls to determine a `lastSeen` property which, if within 15 minutes, could be considered "online".

**Comment by worldomonation** [comment]
> e

I understand and would like to agree that using the `reclaimTask` action to also imply the worker has been online within 15 minutes is a good approach.

**Comment by djmitche** [comment]
@owlishDeveloper FYI!

This is something that we can address once we have better support from queue and worker-manager.

**Comment by tomprince** [comment]
I think this is probably possible now, for worker-manager based worker-pools.

**Comment by djmitche** [comment]
Dup #4366.
