### ISSUE TITLE
Set a deprecation date and alert users that standalone workers will no longer be supported

### ISSUE THREAD

**Issue by imbstack** [taskcluster/taskcluster#2927]
Once reregistration is supported, we're going to start assuming that all workers are registered in worker-manager. This means we'll start building UI and tooling that works with this assumption.

At first, standalone workers (workers that are not known to worker-manager) will still be supported but they will not show up in UI, etc. Eventually we'll want to disallow this at all. Options include:

* Don't allow unregistered workers to claim work at all
* Require a scope to be allowed to claim work while unregistered (this could be useful to support testing)

We should select one of these options, then set a date 6 months in the future or so where it will be enabled. We then should tell all of the users who support workers of this and help them migrate. For most of these users, they will need to start using worker-runner where they have not been yet. This is good because we want to make worker-runner the official way to talk to worker-manager.

@djmitche lists the following as standalone workers currently (possibly more that we are unaware of):

* all hardware
* all scriptworker
* a bunch of community workers
* worker tests

This blocks on #2890 and #2893

**Comment by imbstack** [comment]
How does End of Year sound for this? If we like that I can draft an email.

**Comment by imbstack** [comment]
~~~~~~~~~~~ DRAFT ~~~~~~~~~~~

If you don't build custom Taskcluster images or run standalone workers yourself you can skip the rest of this message.

For the rest of you, we are deprecating the ability to run a Taskcluster worker that does not register with Worker Manager. It will continue to be supported until January 1, 2021 at which time workers that have not registered will not be able to claim work.

This upgrade should be easy if you already use worker-runner. In that case, simply updating to the most recent version of worker runner and whichever worker implementation you use will be sufficient. If you do not use worker-runner yet, now is the time to migrate.

This change will allow you to always know the status of your workers and automatically do the right thing in many cases of crashed/stuck workers. It also unlocks other improvements we wish to provide to you over the coming years!

If you have any questions about what needs to be done or help doing it, please reach out to us in the taskcluster matrix channel or wherever you normally talk to us.

**Comment by helfi92** [comment]
Nice write-up.

> If you do not use worker-runner yet, now is the time to migrate.

How would people know how to migrate to start using worker-runner?

**Comment by djmitche** [comment]
I like the inclusion of the positive benefits!

It's not quite a drop-dead day -- we're saying that all releases before Jan 1 will support unregistered workers, and that the next major release after that date will not support unregistered workers.  So the precise timing is up to the TC deployment - maybe later for Firefox CI for example.

Do we have things we want to land on Jan1 that would be hard or impossible if still supporting unregistered workers?  If not, should we extend the date a bit?

**Comment by imbstack** [comment]
> How would people know how to migrate to start using worker-runner?

I'm just going to add "talk to us in matrix if you want help figuring out next steps" since each situation will be different I think.

> Do we have things we want to land on Jan1 that would be hard or impossible if still supporting unregistered workers? If not, should we extend the date a bit?

Not in particular I guess. What date are you thinking would be best?

**Comment by djmitche** [comment]
I think we'd talked about 1 year, with the idea that we'll increasingly have features that only work with "real" workers.  The idea I had in mind was that by the time the deadline comes around, everyone has either converted to get the features, or is hopelessly behind and would be happy to put one of our SSH keys on the box and let us take care of it.

**Comment by djmitche** [comment]
(so we could say June 1, to pick a specific date)

**Comment by djmitche** [comment]
I don't think our users have the bandwith, or risk tolerance, to actually migrate from standalone right now.  And, we are unlikely to do work that would require removing support.  So, I'm going to close this for now.  We can re-visit, of course, when conditions change.
