### ISSUE TITLE
try to make db fns take named rather than positional arguments

### ISSUE THREAD

**Issue by imbstack** [taskcluster/taskcluster#2928]
Right now db fns take ordered arguments due to how postgres takes arguments. This is mostly fine but many of our fns have 7 or even more arguments and this gets unwieldy with chances of transposition high. Theoretically tests should catch cases where we do this by accident but it would be nice if we just ensured it at the library interface level by taking named arguments. This could also allow us to write better error messages.

If this ends up being a lot of work, let's cancel it and live with positional args however if it is relatively straightforward it feels like an easy win now before we have a lot of uses of db fns!

**Comment by helfi92** [comment]
It looks like postgres supports this https://www.postgresql.org/docs/9.1/sql-syntax-calling-funcs.html#SQL-SYNTAX-CALLING-FUNCS-NAMED.

This issue will most probably involve changing the way arguments are accepted in https://github.com/taskcluster/taskcluster/blob/9ab49efcff79ba14d7ee993686ec6079969d43fa/libraries/postgres/src/Database.js#L82-L121 then rewriting every db function call to use named arguments.
