### ISSUE TITLE
port authorization_codes_table_entities & access_token_table_entities to use normal DB tables

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#2930]
This service currently uses azure-entities emulation to store its data in the DB. This bug entails writing a new DB version that will smoothly migrate the service to use more typical DB tables with nicely-named columns and easy joins.

https://bugzilla.mozilla.org/show_bug.cgi?id=1630022

Complications:
 * tables are encrypted and signed

**Comment by helfi92** [comment]
This involves porting

* authorization_codes_table_entities
* access_token_table_entities
* session_storage_table_entities
* github_access_token_table_entities

**Comment by djmitche** [comment]
We could probably drop some of those tables too, at the cost of logging out current users.  ..if that makes things easier!

**Comment by helfi92** [comment]
Filed https://github.com/taskcluster/taskcluster/issues/3148 to have @petemoore tackle `github_access_token_table_entities`.

**Comment by helfi92** [comment]
For future readers, we have decided during our weekly meeting to skip step 1 of the migration for all of the tables in the web-server service. It's okay if users are signed out after the migration.

**Comment by helfi92** [comment]
@petemoore is currently working on porting `session_storage_table_entities`. Filed https://github.com/taskcluster/taskcluster/issues/3204.
