### ISSUE TITLE
Port the secrets_entities table to use a normal DB table

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#2931]
This service currently uses azure-entities emulation to store its data in the DB. This bug entails writing a new DB version that will smoothly migrate the service to use more typical DB tables with nicely-named columns and easy joins.

https://bugzilla.mozilla.org/show_bug.cgi?id=1630021

Complications:
 * tables are encrypted and signed

**Comment by helfi92** [comment]
This service involves porting a single table `secrets_entities`.
