### ISSUE TITLE
port the queue's task-tracking tables to use normal DB tables

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#2932]
This involves 7 tables:

* queue_task_group_active_sets_entities:
* queue_task_requirement_entities:
* queue_task_groups_entities:
* queue_tasks_entities:
* ~queue_artifacts_entities:~ #3112 
* queue_task_group_members_entities:
* queue_task_dependency_entities:

The queue relies on the details of Azure's semantics for correctness around these tables, so care will be required in ensuring that the replacements make the same guarantees.

Some of these tables are quite large.  Consider ways to make the migration not block operations for too long, or timing the deployment of the migration for a TCW.

https://bugzilla.mozilla.org/show_bug.cgi?id=1630020

**Comment by helfi92** [comment]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1626314#c26, we can identify the small tables:

* queue_provisioner_entities: 38
* queue_worker_type_entities: 133
* queue_task_group_active_sets: 24818
* queue_worker_entities: 90135
* queue_task_groups_entities: 469297
* queue_task_group_members_entities: > 1M
* queue_task_requirement: 837635
* queue_task_dependency_entities: > 1M
* queue_tasks_entities: > 1M
* queue_artifacts_entities: > 1M

**Comment by helfi92** [comment]
It looks like `queue_task_group_active_sets_entities` may be handled separately since we don't need to consider ways to make this table not block operations.

**Comment by helfi92** [comment]
I took out `queue_task_group_active_sets_entities` from this list just in case we do want to do the migration of the large tables during the TCW in which case let's not squeeze in more work than is necessary.

Filed https://github.com/taskcluster/taskcluster/issues/3084 to port `queue_task_group_active_sets_entities`.

**Comment by helfi92** [comment]
I went ahead and took out `queue_task_groups_entities` and `queue_task_requirement_entities` from this list. The migration time for these tables will most probably be acceptable.

Filed https://github.com/taskcluster/taskcluster/issues/3084 to port `queue_task_group_active_sets_entities`.
Filed https://github.com/taskcluster/taskcluster/issues/3087 to port `queue_task_requirement_entities`.

**Comment by djmitche** [comment]
Oops, this is the bigger tables so should wait until nearer the TCW.

**Comment by helfi92** [comment]
I think it's fine to work on this. We just won't merge until nearer the TCW.

**Comment by djmitche** [comment]
I've drawn out a map of the task-related tables in the queue, and got some updated sizes:
 * Artifact - 217m
 * TaskDependency - 85m
 * ~TaskRequirement - 1m~ (#3087)
 * Task - 24m
 * ~TaskGroupActiveSet - 16k~ (#3084)
 * TaskGroupMember - 20m
 * ~TaskGroup - 603k~ (#3086)

Some of those sizes are inflated by the [failing expiration crontasks](https://bugzilla.mozilla.org/show_bug.cgi?id=1638921).  For example, TaskGroupMember is just a copy of a few rows of Task but indexed by taskGroupId, so those two tables should be the same size.  I think we can probably get a bit of additional speed in the migration by filtering on the `expires` property of each table and just not migrating expired data.

I'm struggling a bit with where to start here - if I start on this issue now but don't land it, and then someone else works on the smaller tables and lands those changes, that'll be a pretty massive conflict, as use of the various tables is quite intertwined in the JS code, and especially in `data.js`.  One option may be to get step 1 of this migration finished and then wait until the smaller tables are finished and landed, then follow up with step 2.  Another option is to just do the smaller tables first.  And yet another option is to do all seven tables in this issue.

**Comment by djmitche** [comment]
Per discussion with @helfi92 I'm going to fold the three small tables back in here -- it will be easier to do all at once, especially since their use is intertwined, than to coordinate doing them separately.

**Comment by djmitche** [comment]
status:
 * ~Artifact - 217m~ - #3112
 * Step 1
   * TaskDependency
   * TaskRequirement
   * [DONE] Task
   * [DONE] TaskGroupActiveSet
   * [DONE] TaskGroupMember
   * TaskGroup
 * Step 2

**Comment by djmitche** [comment]
Per discussion today, we'll land step 1 of this during the TCW, so the time constraints for step 2 are reduced.  I'll stop working on that for a while to focus on other things, but plan to return to it soon, and hopefully have a PR ready to land directly after the TCW.
