### ISSUE TITLE
port the queue's worker tables to use normal DB tables

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#2933]
This involves

* queue_worker_entities:
* queue_worker_type_entities:
* queue_provisioner_entities:

These tables might be quite large, and the information they contain is of a historical nature only.  It may make sense to drop some or all of that data during the transition (e.g., workers that haven't been seen in more than a day)

https://bugzilla.mozilla.org/show_bug.cgi?id=1630020

**Comment by helfi92** [comment]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1626314#c26:
* queue_worker_entities: ~90135 rows
* queue_worker_type_entities: ~133 rows
* queue_provisioner_entities: ~38 rows

It will take 2/3 seconds to upgrade these 3 tables so probably no need to drop some or all of the data during the transition.
