### ISSUE TITLE
port the index service to use normal DB table

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#2935]
These tables can be quite large, so consider finding ways to handle them efficiently or do the migration in a TCW, perhaps with #2932.

https://bugzilla.mozilla.org/show_bug.cgi?id=1630017

**Comment by helfi92** [comment]
There are two tables to migrate for this service. From https://bugzilla.mozilla.org/show_bug.cgi?id=1626314#c26:
* indexed_tasks_entities ~7755715 rows
* namespaces_entities  ~1592344 rows

**Comment by helfi92** [comment]
We probably don't need to consider namespaces_entities a "large" table. Assuming a migration of 40k rows per second, the full upgrade for that table would take ~40 seconds. As long as the hang is <1 min, we should be fine to migrate this outside of a TCW.
