### ISSUE TITLE
 port the hooks service's tables to use normal DB tables

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#2936]
https://bugzilla.mozilla.org/show_bug.cgi?id=1630016

Complications:
 * some tables are encrypted and signed

**Comment by helfi92** [comment]
The signed tables are:
* hooks_entities
* last_fire_3_entities

Until https://github.com/taskcluster/taskcluster/issues/3082 is resolved, 2/3 of the tables are blocked.
