### ISSUE TITLE
port the github service's tables to use normal DB tables 

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#2937]
https://bugzilla.mozilla.org/show_bug.cgi?id=1630015

**Comment by helfi92** [comment]
Tables to migrate:
* taskcluster_github_builds_entities: 23677 
* taskcluster_integration_owners_entities: 13
* taskcluster_checks_to_tasks_entities: 678358
* taskcluster_check_runs_entities: 678364

The number of rows are an estimation. They were taken from https://bugzilla.mozilla.org/show_bug.cgi?id=1626314#c26. It looks like they are all relatively small tables.

**Comment by helfi92** [comment]
Feel free to break this into multiple PRs if that makes it easier.
