### ISSUE TITLE
Port the roles_entities table to use a normal DB table

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#2938]
https://bugzilla.mozilla.org/show_bug.cgi?id=1630014

Complications:
 * Roles must be validated and updated as a complete set of roles; concurrent operations to, for example, remove one role and add another role can lead to an inconsistent set of roles due to use of role parameterization.

**Comment by helfi92** [comment]
@djmitche now that this issue only tackles migrating roles, would this still be considered a large 8 points or would 5 points make more sense to you?

> remove one role and add another role can lead to an inconsistent set of roles

Why would one care about removing a role in the migration script?

**Comment by djmitche** [comment]
Not in the migration script -- in production.  So if a `removeRole` and `updateRole` API call happen concurrently, they might together create a collection of roles that is inconsistent, even though they modify different roles.

**Comment by helfi92** [comment]
Thanks for clarifying. From what I understand, this would would mean we would need some kind of full table locking when modifying a role.

**Comment by djmitche** [comment]
Yes, exactly.
