### ISSUE TITLE
Allow longer deadlines

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#2942]
The task deadline limit is based on Azure's limit for queue entry lifetime (7 days).  We're not using Azure anymore, though.

https://bugzilla.mozilla.org/show_bug.cgi?id=1604175

We can actually lift this restriction now, but let's wait for #2940 so as not to cause headaches.

**Comment by gabrielBusta** [comment]
#6269

**Comment by petemoore** [comment]
I think this issue is about task deadline, not maxRunTime.

**Comment by gabrielBusta** [comment]
Thanks for clarifying @petemoore I got them mixed up. This is also an issue for the translations training pipeline. If we run tasks with a high `maxRunTime` by the time its dependencies run they will already have exceeded the deadline. It sounds like this depends on which queue implementation we are using now (is it Pulse?)
