### ISSUE TITLE
WorkerPool using old API

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#2952]
https://github.com/taskcluster/taskcluster/blob/b2c6f6131e56cd84d0de65bfe55ccbbbb1364dc1/services/worker-manager/src/providers/testing.js#L22-L24

WorkerPool was previously migrated to phase 2 but ^ is still using the old API.

**Comment by helfi92** [comment]
@djmitche should this rather use `this.db.fns`? Unless the migration of worker pool hasn't been deployed, I wonder why we haven't seen any errors for this yet.

**Comment by djmitche** [comment]
That's in the test provider that's only used for testing.  And the very next line is throwing an error.  So I'm guessing it's failing due to the missing method and that's enough for the tests (of failure-handling) to succeed.
