### ISSUE TITLE
private artifact links in ui now go nowhere

### ISSUE THREAD

**Issue by imbstack** [taskcluster/taskcluster#2992]
**Describe the bug**
The link for private artifacts appears to go right back to the ui home.

**To Reproduce**

1. Go to https://community-tc.services.mozilla.com/tasks/a3TRMvMERZuRwCGHb9dpcA/runs/0#artifacts
2. Click on any of the private artifacts

**Expected behavior**
I _think_ I should be linked to the artifact? If my understanding is wrong please feel free to close. The [runs in the api](https://community-tc.services.mozilla.com/api/queue/v1/task/a3TRMvMERZuRwCGHb9dpcA/runs/0/artifacts) appear correct to me.

**Taskcluster version**
30.0.2

**Platform (please complete the following information):**

 - OS: Linux
 - Browser if applicable: Firefox
 - Version if applicable: 79.0a1 (2020-06-05) (64-bit)

**Comment by helfi92** [comment]
There's two underlying issues here:

1. The UI should be better at showing that login is required when clicking on this link.
2. The UI is probably failing to send the authorization header when accessing the artifact URL.

**Comment by helfi92** [comment]
OK, I think I may have figured out the issue. Looking into a possible fix now.

**Comment by helfi92** [comment]
The fix for this is in v36.0.1.
