### ISSUE TITLE
[UI] Copy-and-paste task definition into "create task" fails validation

### ISSUE THREAD

**Issue by mitchhentges** [taskcluster/taskcluster#300]
**Describe the bug**
I frequently need to run tasks very similar to existing tasks, such as to diagnose a failing build.
However, when I copy-and-paste the definition of the existing task, it fails validation, such as for `.requires`: when I copy it ([e.g.: from here](https://queue.taskcluster.net/v1/task/KtK5-mBtQ3uMuHsCgDpnGQ)), it has a value in lowercase with hyphens (like `all-completed`), but when I run the task, validation fails saying it expected something in uppercase with underscores (like `ALL_COMPLETED`)

**To Reproduce**
1. Find an [existing task](https://taskcluster-web.netlify.com/tasks/KtK5-mBtQ3uMuHsCgDpnGQ)
2. Click to "View Task Definition"
3. Copy  the raw JSON
4. Go to [create a new task](https://taskcluster-web.netlify.com/tasks/create)
5. Paste the raw JSON
6. Create the task

**Expected behavior**
A task should be created that's identical to the task that was copied

**Platform (please complete the following information):**
 - OS: Ubuntu 18.10
 - Browser: Firefox 65.0

**Comment by helfi92** [comment]
Sorry for that, It's most probably a bug from our end. I will take care of that one. Thanks for the issue!
