### ISSUE TITLE
Add support for reregister endpoint in worker-runner

### ISSUE THREAD

**Issue by imbstack** [taskcluster/taskcluster#3012]
The implementer of this issue should work closely with the implementer of  #3011.

This will make worker-runner support being handed a token back at `registerWorker` time. The token must be securely stored in a way that makes it inaccessible from tasks. It will pass this token back to worker-manager when it calls `reregisterWorker` and then update the worker with the new creds it gets in return.

This is one part of #2893

**Comment by djmitche** [comment]
I went down a bit of a wrong path, I think, adding accessor functions for all of the State properties.  That turned out to be a huge change, and still not quite an airtight guarantee against race conditions that are already pretty unlikely.  That work is [tucked away here](https://github.com/taskcluster/taskcluster/compare/master...djmitche:issue3012-wrongpath?expand=1) for posterity.  In the end I went for a much simpler "lock the state when you access it" approach.

**Comment by djmitche** [comment]
[Work in progress](https://github.com/taskcluster/taskcluster/compare/master...djmitche:issue3012?expand=1)

**Comment by djmitche** [comment]
OK, I'm pretty much there, just waiting on hassan's work to stabilize.

**Comment by djmitche** [comment]
Almost! :)

**Comment by djmitche** [comment]
I'm working on testing this all together, and it's not quite working yet.  With a few PRs I've gotten things mostly up and running with docker-worker in dev.  I have a provider set up pointing to taskcluster-aws-staging, and a [worker pool](https://dustin.taskcluster-dev.net/worker-manager/test%2Faws) set up to run there.  I built an image with worker-runner and docker-worker from master (with the necessary PRs).  So here's what happens:

```

Jun 16 22:52:40 ip-172-31-34-97 docker-worker: 2020/06/16 22:52:40 Loading worker-runner configuration from /etc/taskcluster/worker-runner/start-worker.yml
Jun 16 22:52:40 ip-172-31-34-97 docker-worker: 2020/06/16 22:52:40 Configuring with provider aws
Jun 16 22:52:41 ip-172-31-34-97 docker-worker: 2020/06/16 22:52:41 Identified as worker us-west-2/i-06566263b3ad2a054
Jun 16 22:52:41 ip-172-31-34-97 docker-worker: 2020/06/16 22:52:41 Getting secrets from secrets service
Jun 16 22:52:41 ip-172-31-34-97 docker-worker: 2020/06/16 22:52:41 WARNING: No worker secrets for worker pool test/aws.
Jun 16 22:52:41 ip-172-31-34-97 docker-worker: 2020/06/16 22:52:41 Configuring for worker implementation docker-worker
Jun 16 22:52:41 ip-172-31-34-97 docker-worker: 2020/06/16 22:52:41 Writing files
Jun 16 22:52:41 ip-172-31-34-97 docker-worker: 2020/06/16 22:52:41 Starting worker
Jun 16 22:52:41 ip-172-31-34-97 docker-worker: 2020/06/16 22:52:41 Worker credentials expire in 5m0s 
...
lots of docker-worker logging
...
Jun 16 22:57:11 ip-172-31-34-97 docker-worker: 2020/06/16 22:57:11 Taskcluster Credentials are expiring in 30s; re-registering
Jun 16 22:57:11 ip-172-31-34-97 docker-worker: 2020/06/16 22:57:11 Sending new credentials to worker 
...
Jun 16 22:57:47 ip-172-31-34-97 docker-worker: 2020/06/16 22:57:47 {"type":"task run","source":"top","provisionerId":"test","workerId":"i-06566263b3ad2a054","workerGroup":"us-west-2","workerType":"aws","workerNodeType":"m3.2xlarge"} 
```
and then nothing, and the instance appears to be have been terminated.  AWS console says "User initiated (2020-06-16 22:57:47 GMT)".  Docker-worker doesn't log anything when it gets new credentials.

**Comment by djmitche** [comment]
The timing of that shutdown is pretty close to the five minute `reregistrationTimeout`.

https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_StateReason.html suggests that this would be "Instance Initiated" if the instance itself had run `halt`, so likely that message means that something called the AWS API.  That something would probably be worker-manager.  Which suddenly makes sense, as we don't update `providerData.terminateAfter` when reregistering.  Oops!

And once I futzed my stackdriver searches, lo and behold:
![image](https://user-images.githubusercontent.com/28673/84838678-0303db00-b009-11ea-9682-817259c6d703.png)

#3079

**Comment by djmitche** [comment]
Based on the success in #3088, I think this is done (once that lands).
