### ISSUE TITLE
[Feature request] [tc-github] Allow annotations to be configured

### ISSUE THREAD

**Issue by NotWoods** [taskcluster/taskcluster#3013]
Currently, Taskcluster supports [adding custom output text](https://firefox-ci-tc.services.mozilla.com/docs/reference/integrations/github/checks#custom-output-in-checks) when using Github Checks. This lets the [`output.text`](https://github.com/taskcluster/taskcluster/blob/f755e70b8674fa5a70698700b13fb654d633e000/services/github/src/handlers.js#L563) field be configured.

It would be great if the [`output.annotations`](https://developer.github.com/v3/checks/runs/#annotations-object-1) array could also be configured. This would allow tasks to add annotations to specific lines in PRs and make task output easier to read.

See [Checks](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-status-checks#checks) for some screenshots of how annotations appear in the Github UI.

**Comment by djmitche** [comment]
This would be great -- we've discussed this before.  Hopefully this can get taken up in a future sprint on tc-github.
