### ISSUE TITLE
taskcluster-db tests output to provide guidance on setting up a suitable dev environment, or how to skip db tests

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#3021]
**Describe the bug**
When running `yarn test` without `TEST_DB_URL` set, the failure message says that the env var must be set to run tests, but does not describe how to skip the tests for users that don't have postgres set up, or provide more detailed setup instructions, for users that want to run the tests.

**To Reproduce**

Check out taskcluster repo, run `yarn install && yarn test`.

**Expected behavior**
If DB tests can't be run, the failure message should say how the DB tests can be skipped, or point to setup instructions (perhaps a pointer to a markdown doc in the repo).

**Taskcluster version**
Commit 9e7a0f559787963f3ccc0f6f245c6ac3605fcf85.

**Console output**
```
...
...

> taskcluster-db
$ mocha test/*_test.js test/**/*_test.js

AssertionError [ERR_ASSERTION]: TEST_DB_URL must be set to run db/ tests
    at Object.<anonymous> (/Users/pmoore/git/taskcluster/db/test/helper.js:10:1)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/pmoore/git/taskcluster/db/test/upgrade_downgrade_test.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at requireOrImport (/Users/pmoore/git/taskcluster/node_modules/mocha/lib/esm-utils.js:15:12)
    at Object.exports.loadFilesAsync (/Users/pmoore/git/taskcluster/node_modules/mocha/lib/esm-utils.js:28:26)
    at async singleRun (/Users/pmoore/git/taskcluster/node_modules/mocha/lib/cli/run-helpers.js:107:3)
    at async exports.runMocha (/Users/pmoore/git/taskcluster/node_modules/mocha/lib/cli/run-helpers.js:144:5)
    at async Object.exports.handler (/Users/pmoore/git/taskcluster/node_modules/mocha/lib/cli/run.js:306:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /Users/pmoore/.nvm/versions/node/v12.18.0/bin/node
Arguments: /Users/pmoore/git/taskcluster/.yarn/releases/yarn-1.22.4.js run test
Directory: /Users/pmoore/git/taskcluster/db
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspaces for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by petemoore** [comment]
Note, this is what I tried:

```
$ brew install postgres
...
...
$ pg_ctl -D /usr/local/var/postgres start
$ createuser pete --createdb
$ createdb petedb
$ export TEST_DB_URL=postgres://pete:petefeet@localhost:5432/petedb
$ psql postgres
psql (12.3)
Type "help" for help.

postgres=# alter role pete superuser;
ALTER ROLE
postgres=# \du
                                        List of roles
      Role name      |                         Attributes                         | Member of 
---------------------+------------------------------------------------------------+-----------
 pete                | Superuser, Create DB                                       | {}
 pmoore              | Superuser, Create role, Create DB, Replication, Bypass RLS | {}

postgres=# \q

However, now when I run `yarn test` I get:

```
...
...
queue/test/noop_test.js (mock)
    ✓ createQueue
    ✓ deleteQueue
    ✓ setMetadata
    ✓ setMetadata
    ✓ listQueues

  libraries/azqueue/test/noop_test.js (real)
2020-06-10 11:25:22.727 CEST [25364] ERROR:  relation "tcversion" does not exist at character 21
2020-06-10 11:25:22.727 CEST [25364] STATEMENT:  select version from tcversion
    ✓ createQueue
    ✓ deleteQueue
    ✓ setMetadata
    ✓ setMetadata
    ✓ listQueues

  libraries/azqueue/test/slow_test.js (real)
2020-06-10 11:25:23.049 CEST [25368] ERROR:  relation "tcversion" does not exist at character 21
2020-06-10 11:25:23.049 CEST [25368] STATEMENT:  select version from tcversion
    huge queue with visible messages
      - get from queue
    typical high-volume TC install
      - get pending queue
      - get claim queue
      - get deadline queue
      - get dependency queue

  libraries/azqueue/test/update_message_test.js (mock)
    ✓ update message after getting

  libraries/azqueue/test/update_message_test.js (real)
2020-06-10 11:25:23.374 CEST [25372] ERROR:  relation "tcversion" does not exist at character 21
2020-06-10 11:25:23.374 CEST [25372] STATEMENT:  select version from tcversion
    14) update message after getting


  28 passing (6s)
  5 pending
  14 failing

  1) libraries/azqueue/test/count_messages_test.js (real)
       count queue with visible messages:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

0 !== 1

      + expected - actual

      -0
      +1
      
      at Context.<anonymous> (test/count_messages_test.js:35:12)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  2) libraries/azqueue/test/count_messages_test.js (real)
       count queue with invisible messages:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

0 !== 1

      + expected - actual

      -0
      +1
      
      at Context.<anonymous> (test/count_messages_test.js:43:12)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  3) libraries/azqueue/test/count_messages_test.js (real)
       count queue with expired messages:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

0 !== 2

      + expected - actual

      -0
      +2
      
      at Context.<anonymous> (test/count_messages_test.js:54:12)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  4) libraries/azqueue/test/count_messages_test.js (real)
       count many messages in several queues:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected

  {
+   messageCount: 0
-   messageCount: 100
  }
      + expected - actual

       {
      -  "messageCount": 0
      +  "messageCount": 100
       }
      
      at Context.<anonymous> (test/count_messages_test.js:63:12)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  5) libraries/azqueue/test/delete_expired_test.js (real)
       expired messages are deleted in cleanup:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected

+ []
- [
-   'bar-3'
- ]
      + expected - actual

      -[]
      +[
      +  "bar-3"
      +]
      
      at Context.<anonymous> (test/delete_expired_test.js:34:12)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  6) libraries/azqueue/test/delete_message_test.js (real)
       delete message after getting:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected

+ []
- [
-   'bar-1'
- ]
      + expected - actual

      -[]
      +[
      +  "bar-1"
      +]
      
      at Context.<anonymous> (test/delete_message_test.js:29:12)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  7) libraries/azqueue/test/get_messages_test.js (real)
       get from one-item queue:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected

+ []
- [
-   'bar-1'
- ]
      + expected - actual

      -[]
      +[
      +  "bar-1"
      +]
      
      at Context.<anonymous> (test/get_messages_test.js:38:12)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  8) libraries/azqueue/test/get_messages_test.js (real)
       get marks items invisible:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected

+ []
- [
-   'bar-1'
- ]
      + expected - actual

      -[]
      +[
      +  "bar-1"
      +]
      
      at Context.<anonymous> (test/get_messages_test.js:47:12)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  9) libraries/azqueue/test/get_messages_test.js (real)
       get from multi-item queue:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected

+ []
- [
-   'bar-1',
-   'bar-2'
- ]
      + expected - actual

      -[]
      +[
      +  "bar-1"
      +  "bar-2"
      +]
      
      at Context.<anonymous> (test/get_messages_test.js:72:12)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  10) libraries/azqueue/test/get_messages_test.js (real)
       get skips invisible items:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected

+ []
- [
-   'bar-2'
- ]
      + expected - actual

      -[]
      +[
      +  "bar-2"
      +]
      
      at Context.<anonymous> (test/get_messages_test.js:82:12)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  11) libraries/azqueue/test/get_messages_test.js (real)
       get skips expired items:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected

+ []
- [
-   'bar-2'
- ]
      + expected - actual

      -[]
      +[
      +  "bar-2"
      +]
      
      at Context.<anonymous> (test/get_messages_test.js:96:12)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  12) libraries/azqueue/test/get_messages_test.js (real)
       getting multiple items returns them in insertion order:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected

+ []
- [
-   'bar-1',
-   'bar-2',
-   'bar-3',
-   'bar-4'
- ]
      + expected - actual

      -[]
      +[
      +  "bar-1"
      +  "bar-2"
      +  "bar-3"
      +  "bar-4"
      +]
      
      at Context.<anonymous> (test/get_messages_test.js:109:12)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  13) libraries/azqueue/test/get_messages_test.js (real)
       multiple parallel gets:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected ... Lines skipped

+ []
...
- [
-   'foo-0',
-   'foo-1',
-   'foo-10',
-   'foo-100',
-   'foo-101',
-   'foo-102',
-   'foo-103',
-   'foo-104',
-   'foo-105',
-   'foo-106',
-   'foo-107',
-   'foo-108',
-   'foo-109',
-   'foo-11',
-   'foo-110',
-   'foo-111',
-   'foo-112',
-   'foo-113',
-   'foo-114',
-   'foo-115',
-   'foo-116',
-   'foo-117',
-   'foo-118',
-   'foo-119',
-   'foo-12',
-   'foo-120',
-   'foo-121',
-   'foo-122',
-   'foo-123',
-   'foo-124',
-   'foo-125',
-   'foo-126',
-   'foo-127',
-   'foo-128',
-   'foo-129',
-   'foo-13',
-   'foo-130',
-   'foo-131',
-   'foo-132',
-   'foo-133',
-   'foo-134',
-   'foo-135',
-   'foo-136',
-   'foo-137',
-   'foo-138',
-   'foo-139',
-   'foo-14',
-   'foo-140',
-   'foo-141',
...
      + expected - actual

      -[]
      +[
      +  "foo-0"
      +  "foo-1"
      +  "foo-10"
      +  "foo-100"
      +  "foo-101"
      +  "foo-102"
      +  "foo-103"
      +  "foo-104"
      +  "foo-105"
      +  "foo-106"
      +  "foo-107"
      +  "foo-108"
      +  "foo-109"
      +  "foo-11"
      +  "foo-110"
      +  "foo-111"
      +  "foo-112"
      +  "foo-113"
      +  "foo-114"
      +  "foo-115"
      +  "foo-116"
      +  "foo-117"
      +  "foo-118"
      +  "foo-119"
      +  "foo-12"
      +  "foo-120"
      +  "foo-121"
      +  "foo-122"
      +  "foo-123"
      +  "foo-124"
      +  "foo-125"
      +  "foo-126"
      +  "foo-127"
      +  "foo-128"
      +  "foo-129"
      +  "foo-13"
      +  "foo-130"
      +  "foo-131"
      +  "foo-132"
      +  "foo-133"
      +  "foo-134"
      +  "foo-135"
      +  "foo-136"
      +  "foo-137"
      +  "foo-138"
      +  "foo-139"
      +  "foo-14"
      +  "foo-140"
      +  "foo-141"
      +  "foo-142"
      +  "foo-143"
      +  "foo-144"
      +  "foo-145"
      +  "foo-146"
      +  "foo-147"
      +  "foo-148"
      +  "foo-149"
      +  "foo-15"
      +  "foo-16"
      +  "foo-17"
      +  "foo-18"
      +  "foo-19"
      +  "foo-2"
      +  "foo-20"
      +  "foo-21"
      +  "foo-22"
      +  "foo-23"
      +  "foo-24"
      +  "foo-25"
      +  "foo-26"
      +  "foo-27"
      +  "foo-28"
      +  "foo-29"
      +  "foo-3"
      +  "foo-30"
      +  "foo-31"
      +  "foo-32"
      +  "foo-33"
      +  "foo-34"
      +  "foo-35"
      +  "foo-36"
      +  "foo-37"
      +  "foo-38"
      +  "foo-39"
      +  "foo-4"
      +  "foo-40"
      +  "foo-41"
      +  "foo-42"
      +  "foo-43"
      +  "foo-44"
      +  "foo-45"
      +  "foo-46"
      +  "foo-47"
      +  "foo-48"
      +  "foo-49"
      +  "foo-5"
      +  "foo-50"
      +  "foo-51"
      +  "foo-52"
      +  "foo-53"
      +  "foo-54"
      +  "foo-55"
      +  "foo-56"
      +  "foo-57"
      +  "foo-58"
      +  "foo-59"
      +  "foo-6"
      +  "foo-60"
      +  "foo-61"
      +  "foo-62"
      +  "foo-63"
      +  "foo-64"
      +  "foo-65"
      +  "foo-66"
      +  "foo-67"
      +  "foo-68"
      +  "foo-69"
      +  "foo-7"
      +  "foo-70"
      +  "foo-71"
      +  "foo-72"
      +  "foo-73"
      +  "foo-74"
      +  "foo-75"
      +  "foo-76"
      +  "foo-77"
      +  "foo-78"
      +  "foo-79"
      +  "foo-8"
      +  "foo-80"
      +  "foo-81"
      +  "foo-82"
      +  "foo-83"
      +  "foo-84"
      +  "foo-85"
      +  "foo-86"
      +  "foo-87"
      +  "foo-88"
      +  "foo-89"
      +  "foo-9"
      +  "foo-90"
      +  "foo-91"
      +  "foo-92"
      +  "foo-93"
      +  "foo-94"
      +  "foo-95"
      +  "foo-96"
      +  "foo-97"
      +  "foo-98"
      +  "foo-99"
      +]
      
      at Context.<anonymous> (test/get_messages_test.js:128:12)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  14) libraries/azqueue/test/update_message_test.js (real)
       update message after getting:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected

+ []
- [
-   'bar-1'
- ]
      + expected - actual

      -[]
      +[
      +  "bar-1"
      +]
      
      at Context.<anonymous> (test/update_message_test.js:29:12)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)



error Command failed with exit code 14.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 14
Command: /Users/pmoore/.nvm/versions/node/v12.18.0/bin/node
Arguments: /Users/pmoore/git/taskcluster/.yarn/releases/yarn-1.22.4.js run test
Directory: /Users/pmoore/git/taskcluster/libraries/azqueue
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspaces for documentation about this command.
error Command failed with exit code 14.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by petemoore** [comment]
> Here's what I usually do:
> 
> Terminal 1:
> 
> ```
> ➜ docker run -e POSTGRES_HOST_AUTH_METHOD=trust -ti -p 127.0.0.1:5432:5432  --rm postgres:11 -c log_statement=all
> ```
> 
> Terminal 2:
> 
> ```
> export TEST_DB_URL=postgresql://postgres@localhost/postgres
> yarn workspace taskcluster-queue test
> ```
> 
> Terminal 3 (dynamically access the db for debugging purposes):
> 
> ```
> ➜  docker container ls
> CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                   
> fec180439331        postgres:11         "docker-entrypoint.s…"   21 seconds ago      Up 21 seconds       127.0.0.1:5432->5432/tcp
> 
> ➜ docker exec -ti fec180439331 psql -U postgres
> ```
> 
> Using the docker image instead of running a local version of pg might help. Give that a try and let me know if it helps.

Perfect! These steps worked for me, and I now get 1020 passing tests now, with 0 failures.

Let's add this to the dev docs, and update the test failure message to refer to it if the postgres database isn't set up.

**Comment by djmitche** [comment]
https://github.com/taskcluster/taskcluster/blob/master/dev-docs/development-process.md#postgres

The POSTGRES_HOST_AUTH_METHOD should get added there, though -- that's a new requirement of the postgres docker image that appeared a month or two ago.

**Comment by djmitche** [comment]
By the way, this:
```
$ psql postgres
psql (12.3)
```
is why the tests didn't pass for you -- pg requires postgres 11.  Postgres major versions are not generally inter-compatible, and 11 is the latest version supported by cloud providers like Google.

**Comment by petemoore** [comment]
Many thanks, this is great.

I think the only missing piece, is that if a test fails due to `TEST_DB_URL` not being set, it would be super-useful to point the user to `development-process.md` in the test failure message. But I can make a separate PR for that.

**Comment by petemoore** [comment]
> Many thanks, this is great.
> 
> I think the only missing piece, is that if a test fails due to `TEST_DB_URL` not being set, it would be super-useful to point the user to `development-process.md` in the test failure message. But I can make a separate PR for that.

Created #3043 for this.
