### ISSUE TITLE
Worker expiration seems to be missing workers

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#3034]
Details in #3032, but it seems that the expire-workers job is not expiring all workers.

The job completes in about 80s, so it's doing something but not getting overwhelmed.  It logs the number of expired workers, but that's at level INFO and we're only logging NOTICE - prod level change [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1645212), and let's use this issue to track changing the level of that log message in the code.

(assigned to @imbstack not necessarily to finish but to add any other findings here)
(I guess the young kids call them "learnings" now, ugh, kids these days)

**Comment by djmitche** [comment]
![image](https://user-images.githubusercontent.com/28673/84689743-67427400-af0f-11ea-9ffb-f6d2f11fb832.png)

@imbstack those numbers seem roughly aligned with what we'd expect, no?

**Comment by imbstack** [comment]
Hmmm, yeah those do seem right. So maybe it is not successfully deleting? We might need to inspect some of the rows that do exist.

**Comment by djmitche** [comment]
I've forgotten whether this complaint started when we were running 30.0.5 (which uses tc-lib-entities `scan` and `remove`) or 30.1.1 (which uses a dedicated [db function](https://github.com/taskcluster/taskcluster/blob/3d23732e0923c80faf28bf38c1a522a38eeb6da2/db/versions/0012.yml#L411-L429) that should be pretty bulletproof).

firefox-ci is running 30.1.1 now, and was during the last crontask run, so if that is indeed bulletproof then the DB expirations should be good right now.  I've asked @sciurus to run the following to verify:

```
select state, date_trunc('day', expires) as expires_day, count(*) from workers group by state, date_trunc('day', expires);
```

**Comment by djmitche** [comment]
It's working now.  So this must have been an issue with the old, limit-based expiration in 30.0.5.

```
taskcluster=> select state, date_trunc('day', expires) as expires_day, count(*) from workers group by state, date_trunc('day', expires);
   state   |      expires_day       | count 
-----------+------------------------+-------
 requested | 2020-06-19 00:00:00+00 |     2
 requested | 2020-06-20 00:00:00+00 |     1
 requested | 2020-06-21 00:00:00+00 |     1
 requested | 2020-06-22 00:00:00+00 |     7
 running   | 2020-06-19 00:00:00+00 |     3
 running   | 2020-06-20 00:00:00+00 |     4
 running   | 2020-06-21 00:00:00+00 |     8
 running   | 2020-06-22 00:00:00+00 |  1249
 stopped   | 2020-06-15 00:00:00+00 | 41981
 stopped   | 2020-06-16 00:00:00+00 | 44737
 stopped   | 2020-06-17 00:00:00+00 | 41462
 stopped   | 2020-06-18 00:00:00+00 | 36935
 stopped   | 2020-06-19 00:00:00+00 | 30224
 stopped   | 2020-06-20 00:00:00+00 | 19692
 stopped   | 2020-06-21 00:00:00+00 | 17602
 stopped   | 2020-06-22 00:00:00+00 | 18163
```
