### ISSUE TITLE
Check Postgres version in lib-postgres

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#3039]
Since we require 11.x, let's verify that on connection in taskcluster-lib-postgres

https://www.postgresql.org/docs/11/runtime-config-preset.html#GUC-SERVER-VERSION-NUM

Refs #3021

**Comment by bhushan-borole** [comment]
Hey,
I would like to work on this issue!

**Comment by bhushan-borole** [comment]
I think we will have to make changes in this file:
https://github.com/taskcluster/taskcluster/blob/main/libraries/postgres/src/Version.js
Am I right @djmitche ?

**Comment by djmitche** [comment]
Probably `Database.js` instead -- there are some other `_checkXxx` methods there.

**Comment by bhushan-borole** [comment]
So if the version is not 11.x, then what should be the procedure?

**Comment by djmitche** [comment]
The check should be similar to
https://github.com/taskcluster/taskcluster/blob/65bca4145c2adb012d1f3435270cd5bd82eeee33/libraries/postgres/src/Database.js#L349-L387

that is, if the check fails, throw an error.
