### ISSUE TITLE
New UI: Bring back 'notify on failure' in Task Group view

### ISSUE THREAD

**Issue by jonalmeida** [taskcluster/taskcluster#304]
Not sure if it was intentionally removed, but it was very helpful to have a notification go off if there was a TC failure in the group.

**Comment by helfi92** [comment]
You can rely on the favicon to see if there was a failure:

<img width="227" alt="screen shot 2019-02-25 at 3 20 17 pm" src="https://user-images.githubusercontent.com/3766511/53366243-1faa6a00-3911-11e9-8d7d-d32cf07c0b17.png">

**Comment by jonalmeida** [comment]
> You can rely on the favicon to see if there was a failure:
> 
> <img alt="screen shot 2019-02-25 at 3 20 17 pm" width="227" src="https://user-images.githubusercontent.com/3766511/53366243-1faa6a00-3911-11e9-8d7d-d32cf07c0b17.png">

See #306. TC tabs aren't always in the current window or if you have 50+ tabs. :)

**Comment by jonalmeida** [comment]
Thank you! I used it today and it was :sparkles:!
