### ISSUE TITLE
[UI] Enhance the empty state for the hooks view

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#3044]
**To Reproduce**

1. Go to http://localhost:5080/hooks

**Expected behavior**
If there are no hooks to display, it should say something other than "No items for search term".

**Actual behavior**
"No items for search term "

<img width="855" alt="Screen Shot 2020-06-12 at 1 35 04 PM" src="https://user-images.githubusercontent.com/3766511/84530829-89d75180-acb1-11ea-9c9f-eb177ec931a9.png">

**Taskcluster version**
v30.1.1

**Additional context**
This only happens when there are no hooks to display.

**Comment by Manish-Giri** [comment]
@helfi92 May I take this up?

**Comment by helfi92** [comment]
Hey! Go for it :)

**Comment by codershona** [comment]
Hello Is this issue still open, can I work on this issue?

**Comment by djmitche** [comment]
Sure, it's all yours!

**Comment by codershona** [comment]
Thank you

**Comment by djmitche** [comment]
So the issue here is that when there are no hooks at all (rather than a search that didn't return anything), the text is "No items for search term".  Which is confusing, because there is no search term.

So in the case where there are no hooks *and* no search term, let's display "No hooks are defined", instead.

**Comment by rayyanQ** [comment]
I am a new contributor and would like to work on this issue, if it is still open.

**Comment by djmitche** [comment]
Sure thing!  #4104 should have some extra context on what the desired state is here.

**Comment by rayyanQ** [comment]
Thanks!

**Comment by cerkiewny** [comment]
I think this issue is slightly outdated, I will include fix for that in my [PR](https://github.com/taskcluster/taskcluster/pull/4919) as it is changing a lot about the hook tree anyway

**Comment by jwhitlock** [comment]
Fixed in PR #4921 and #4948.
