### ISSUE TITLE
New UI: Add notify on task group success

### ISSUE THREAD

**Issue by jonalmeida** [taskcluster/taskcluster#305]
Similar to #304 it's useful to know when a task group is completed in addition to the green status icon in the tab icon.

Making this another opt-in feature would probably work.

**Comment by sudipt1999** [comment]
Can I work on this @jonalmeida  !Some pointers would be really helpful!

**Comment by helfi92** [comment]
@sudipt1999 We should wait until we have a setting view before we decide to implement this feature. Feel free to tackle another issue :)

**Comment by ccooper** [comment]
Duplicate of #304 

I think we would tackle both types of notifications at the same time.
