### ISSUE TITLE
[azure provider] simplify the logic in checkWorker

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#3056]
* step creation/deletion state machine forward
* change worker.state to RUNNING or STOPPING or STOPPED based on VM state and current worker state
* handle lifetime expirations
* handle extending worker.expires

This is all in there, but inter-mingled.  Let's factor it out into nice functions.

**Comment by helfi92** [comment]
Resolved in https://github.com/taskcluster/taskcluster/commit/1d49719b8d84efd44cf5658c37d92b9e358d1b72.
