### ISSUE TITLE
[azure provider] better-defined 'RUNNING' state

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#3057]
Only move to worker.state = RUNNING when *both* the worker-creation process has completed and `registerWorker` has been called.  These can happen in any order.

We can consider returning something like 409 from `registerWorker` if the worker-creation process hasn't completed by that time, and updating worker-runner to handle that situation by retrying.

**Comment by djmitche** [comment]
An advantage of fixing this is that it will avoid the case that @grenade has seen where a worker starts up, calls registerWorker, and claims a task, only to be killed by worker-manager because of some issue with provisioning.

Note that #3505 might address this sufficiently (it fixes a bug where the worker is marked RUNNING before registerWorker is called).  So, it's possible there may be nothing to do here, after some discussion.

**Comment by djmitche** [comment]
@helfi92 / @petemoore perhaps you can take a look at decide if this can be closed?

**Comment by helfi92** [comment]
Closing SGTM

**Comment by petemoore** [comment]
Fine for me to close it. Indeed we can reopen if the situation reappears.
