### ISSUE TITLE
Mix information from queue and worker-manager in UI and worker-manager

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#3060]

**Comment by djmitche** [comment]
Let's have a little brainstorm here.

At the top level, we currently have "Worker Manager" and "Workers" menu items.  The "Workers" is currently structured by "provisioner" and then "workerType" and then a list of workers (notably, workerGroup is not a level, and that's probably just as well).

Instead, we really have "task queues" and "worker pools".  These are sort-of joined by name, but it's possible to have one without the other. For example, the `built-in/succeed` task queue exists on the queue, but not in worker-manager.  And worker-manager may have pools defined which have no tasks and no workers, and thus no task-queue exists.  So, the view I'm picturing has a row for each task-queue/worker-pool:

* taskQueueId = workerPoolId (linking to workers view)
* queue
  * pending tasks
  * stability
  * description
* worker-manager
  * providerId
  * current capacity
  * owner
  * link to errors
  * link to definition edit/delete

Some of that information might make more sense in a sidebar, or even in a full-page view.  Especially description, and we have long talked about adding a schema for each task queue as well.

For rows that are missing one or the other, those fields would be blank.

Information about workers also comes from both the queue and worker-manager, but in a fashion that's less visible to users.  Again we can have workers known to the queue but not worker-manager (such as `built-in/*`) and workers known to worker-manager but not the queue (such as workers that have been created but not yet claimed a task, or have otherwise failed).  Also, both services keep track of workers for some time after they have stopped doing work.  We should give a unified view of workers, but make it clear what different pieces of information mean, as that information is often crucial to debugging.

So, a similar tabular view for workers makes sense, with the following information:
 * workerGroup / workerId
 * queue
   * last seen by queue (#4366)
   * most recent task / state
   * quarantine state + button
 * worker-manager
   * state
   * capacity
   * providerId
   * terminate button

Similarly, some of this information, and perhaps more (first claim, created, list of tasks, etc.) might make sense in a sidebar.

Setting aside the UI, it's not clear how best to get all of this information from the DB, since it is spread over two services.  The data we want is basically an OUTER JOIN of the queue and worker-manager tables.  Our DB access rules allow a service to have *read* access to another service's tables, so we would have to select one service or the other to run that OUTER JOIN.  It probably makes sense to do so in worker-manager, in keeping with our standard that platform services don't know about core services.

In doing so, it will make sense to get rid of some of the existing queue endpoints.  For sure the workerType- / provisionerId-related endpoints, and probably also the declareWorker endpoint.

**Comment by jwhitlock** [comment]
I'm helping to debug some issues with a worker pool with an Azure provisioner, and finding that I need to query the API to get some information that seems appropriate for the UI. I'd like to see:

* Worker manager state included in the queue's worker detail view - it would be useful to see that a worker is in the ``stopped`` state
* In the queue worker list view, filter the list of workers by worker state - it would be useful to exclude ``stopped`` workers, or to only focus on ``running`` workers.

I'm not sure if joined views are required or not. It may be enough to have a list and detail view from the worker manager perspective, and some optimistic linking between the two.

**Comment by matt-boris** [comment]
I'm thinking I'll pick up https://github.com/taskcluster/taskcluster/issues/5379 before starting this work because doing this will add additional columns, making the table even less user-friendly.
