### ISSUE TITLE
Generate regular report of worker version installed on each worker pool.

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#3066]
We could do this either by querying the workers directly, or by parsing logs for the most recent task for each worker type.

**Comment by lotas** [comment]
#5306 might be a better way of achieving this, if we modify workers to send its own version as part of `registerWorker` call, then we would always have the actual info without extra work.
wdyt @djmitche, can we close this one?

**Comment by djmitche** [comment]
Yeah, it makes more sense to just _have_ that information rather than generating a report.
