### ISSUE TITLE
[UI] Task Group view polling

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#307]
The group view polls every 2.5 minutes for new results. For groups with <1000 tasks, this is fine but for a group with >3000 tasks this means the user would be looking at a spinner for a bit. We should figure out a way to show the old data until the new data has finished loading.

**Comment by iFlameing** [comment]
@helfi92 I would like to work on this :)

**Comment by helfi92** [comment]
Awesome! Go for it :)

**Comment by helfi92** [comment]
Note that I will be away all of next week so I won't be there to help answer questions.

**Comment by iFlameing** [comment]
can you give me an overview of the work which I have to do for this issue? 

I will wait for you. and please merge [this](https://github.com/taskcluster/taskcluster/pull/280).

**Comment by helfi92** [comment]
We are moving away to a subscription model instead of polling. This issue will no longer be relevant once https://github.com/taskcluster/taskcluster/pull/477 is merged.
