### ISSUE TITLE
[UI] Worker Pool view enhancement

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#3070]
From https://github.com/taskcluster/taskcluster/pull/3037#pullrequestreview-430622083:

> Now that we show most information on this view, I wonder if we can remove "view workers", "view errors" and the delete icon from the parent view.

Consensus: Let's wait for a more complete overhaul of the workerpool UI before doing this.

**Comment by djmitche** [comment]
Let's close this in favor of that overhaul, which will almost automatically include this.
