### ISSUE TITLE
Add support for data signing

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#3082]
Some of our tables that are still using taskcluster-lib-entities use signing to protect the integrity of the data. In order to successfully move away from taskcluster-lib-entities and migrate those tables to postgres phase 2, we would need to add inherent support for signing.

Tables affected:
* clients_entities - auth
* hooks_entities - hooks
* last_fire_3_entities - hooks
* queues_entities - hooks
* secrets_entities - secrets
* access_token_table_entities - web_server
* authorization_codes_table_entities - web_server
* github_access_token_table_entities - web_server
* session_storage_table_entities - web_server

**Comment by helfi92** [comment]
The change will likely happen in taskcluster-lib-postgres. Similar to taskcluster-lib-entities, we can add a field `signingKey` to the database [setup method](https://github.com/taskcluster/taskcluster/blob/138611a01fe039ff0ff3b591c6f31d6d70e29ad1/libraries/postgres/src/Database.js#L55).

**Comment by helfi92** [comment]
This morning @djmitche and I met and brainstormed ideas. Here's what we agreed on:
* The `secrets_entities`, `clients_entities`, and `hooks_entities` tables should have all of their data migrated. It's fine for the other signed tables to discard their data.
* Migrating signed data is not trivial in postgres. We will experiment with 2 different ideas:
  - Write a script that would run after the migratin script that would take care of migrating the data. The `xxxx_modify` and `xxxx_remove` entity functions for the tables that will need to have their data migrated can be rewritten to always fail to avoid updating the old tables while cloudops is running the javsacript migration script.
  - Have a stringify method create the signing key. This would allow us to generate the same hash as the one in tc-lib-entities.

**Comment by djmitche** [comment]
I'm doing a timeboxed exercise in #2.  The question is whether we can represent, byte-for-byte, the data that azure-entities used to generate the signature.  The timestamps columns are causing me the most worry, as those are signed in their `.toJSON()` format, so issues of precision and rounding could cause differences in the representation (postgres has microsecond accuracy, while JS typically uses millisecond accuracy).

My rough timebox plan is:
 * Get a copy of a clients_entities table since that is signed (my dev environment has one)
 * Write a migration script to convert that to a "normal" table like any other
 * Get a local snapshot of the DB containing both entities and new tables, so I can repeat this
 * Write a signature-validation function that calculates sigs based on the new table, and see if it matches

I started off with the hooks table, but I now see that it doesn't include datestamps.  The other two tables -- secrets and clients -- do.  So I'll do clients.

**Comment by djmitche** [comment]
```
client_id    | project/taskcluster/generic-worker/ci-macos-staging
description  | 
access_token | {"kid": "azure", "algo": "aes-256", "__buf0_val": "4LoRs4gxAVbbq5fwX2Vi+FuIHZBSNel0Q9BNBL1WUKMjWLnZLpfKcQZcryfIHnep6etS9xb/bfkfzbVTbhjl/A==", "__bufchunks_val": "1"}
expires      | 3000-01-01 00:00:00+00
details      | {"created": "2020-06-22T18:04:52.900Z", "lastRotated": "2020-06-22T18:04:52.900Z", "lastDateUsed": "2020-06-22T18:04:52.900Z", "lastModified": "2020-06-22T18:04:52.900Z", "deleteOnExpiration": false}
scopes       | ["assume:worker-id:proj-taskcluster/*", "assume:worker-pool:proj-taskcluster/gw-ci-macos-staging"]
disabled     | 0
signature    | xRLjHu5ETXJmkaaEYEFPSUdEa1mY4boyrQBgLsFGGTTeRUWqBA+YPvwaYe3d4T1RhdYytQ3lCCfwnzXfP3wykQ==
etag         | caf75b2f-7876-46d4-ae4e-d37b6f9e845d
```
(don't worry, this is from my dev env with a dummy accessToken)

**Comment by djmitche** [comment]
That's missing the description, but I fixed that.  I have been successful in verifying the signature of all clients after migrating them to postgres.  To prove the concept, I just wrote a loader component in Auth's `main.js`:

```
  'scan-clients-pg': {
    requires: ['cfg', 'db', 'monitor'],
    setup: ({cfg, db, monitor}, ownName) => {
      return monitor.oneShot(ownName, async () => {
        const signingKey = Buffer.from(cfg.azure.signingKey, 'utf8');
        const lengthEncode = (value, hash) => {
          let len;
          if (typeof value === 'string') {
            len = Buffer.byteLength(value, 'utf8');
          } else {
            len = value.length;
          }
          const buf = Buffer.alloc(4);
          buf.writeUInt32BE(len, 0);
          console.log(buf);
          hash.update(buf);
          console.log(Buffer.from(value, 'utf8'));
          hash.update(value, 'utf8');
        };
        await db._withClient('read', async client => {
          const res = await client.query('select * from clients');
          for (const row of res.rows) {
            console.log('signing', row.client_id, 'with', signingKey);
            const hash = crypto.createHmac('sha512', signingKey);

            lengthEncode('accessToken', hash);
            const accessToken = db.decrypt({value: row.access_token}).toString('utf-8');
            lengthEncode(accessToken, hash);

            lengthEncode('clientId', hash);
            lengthEncode(row.client_id, hash);

            lengthEncode('description', hash);
            lengthEncode(row.description, hash);

            lengthEncode('details', hash);
            lengthEncode(stringify(row.details), hash);

            lengthEncode('disabled', hash);
            lengthEncode(row.disabled.toString(), hash);

            lengthEncode('expires', hash);
            lengthEncode(row.expires.toJSON(), hash);

            lengthEncode('scopes', hash);
            lengthEncode(stringify(row.scopes), hash);

            const d = hash.digest();
            console.log('result', d);
            assert.equal(d.toString('base64'), row.signature);
          }
        });
      });
    },
  },
```
and all of those assertions pass.  So I think this is option is possible!

**Comment by djmitche** [comment]
So in summary, Hassan's option #2 looks like the winner.  In a bit more detail:
 * use the same signing key we've used for Azure
 * during migration, just copy the signature value over unchanged
 * when validating a signature, construct the same hash input that tc-lib-entities would have constructed and validate the signature.  The exercise above is confirmation that "the same hash input" is achievable.

We'll use a JSON container similar to that used for the encryption support we landed two weeks ago, that specifies the key being used and the algorithm.  That will allow us to rotate keys just as we can for encryption.  

Something we need to consider is how we will add or remove columns from the set of columns being signed.  I'm not sure what the answer is, and we don't need to know right now, but I bet having a version field in the JSON container will be useful when we want to do that.  So let's include a `{"v": 1}` in the container now.

@imbstack do you have any thoughts on this idea?

@ajvb we're going to delay implementing this a bit until we finish some other tasks, so now might be a good time to get your feedback.  Do you see any vulnerabilities or other issues with this approach?

**Comment by djmitche** [comment]
We have decided not to support signing with postgres, as it does not deliver much value to us.
