### ISSUE TITLE
Port the queue_task_requirement_entities table to use a normal DB table

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#3087]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1626314#c26:

* queue_task_requirement_entities: 837635 rows

We were able to migrate the workers table in 1 second (~40,000 workers). Assuming we can migrate things at a rate of 40k/second, then migrating queue_task_requirement_entities should take ~21 seconds. That should probably be fine and we don't need to do this in a TCW.

**Comment by djmitche** [comment]
Folded back into #2932.
