### ISSUE TITLE
Ensure postgres is using a fixed collation

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#3116]
This seems to be different in CI and locally.

It can be checked with
```
SELECT datcollate AS collation
FROM pg_database 
WHERE datname = current_database();
```

so let's check it.

**Comment by djmitche** [comment]
Here's how I spotted this -- in CI I got a set of taskIds sorted by C locale, whereas I expected them sorted by en_US.UTF8 (specifically, case-insensitively):
```
got [
  {
    taskId: '7-bz8j_nQQaDQGa9SokueA',
    taskGroupId: 'FvvdpeGtQW-fCN1K0Fwzbg'
  },
  {
    taskId: 'GXCEcvbRSJeYrKw5XbnOZw',
    taskGroupId: 'FvvdpeGtQW-fCN1K0Fwzbg'
  },
  {
    taskId: 'bday-EyrSvOCX5sWf5y0vQ',
    taskGroupId: 'FvvdpeGtQW-fCN1K0Fwzbg'
  },
  {
    taskId: 'fIYgOS8aS1mIFw6m-uNhVw',
    taskGroupId: 't2QC2Q3nRf68CCU80124bg'
  },
  {
    taskId: 'lxUFJhJFS2CKHCcbuKCMhA',
    taskGroupId: 'FvvdpeGtQW-fCN1K0Fwzbg'
  },
  {
    taskId: 'orr9Pla4S2SzNbKkRqP0sg',
    taskGroupId: 'FvvdpeGtQW-fCN1K0Fwzbg'
  }
]
exp [
  {
    taskId: '7-bz8j_nQQaDQGa9SokueA',
    taskGroupId: 'FvvdpeGtQW-fCN1K0Fwzbg'
  },
  {
    taskId: 'bday-EyrSvOCX5sWf5y0vQ',
    taskGroupId: 'FvvdpeGtQW-fCN1K0Fwzbg'
  },
  {
    taskId: 'fIYgOS8aS1mIFw6m-uNhVw',
    taskGroupId: 't2QC2Q3nRf68CCU80124bg'
  },
  {
    taskId: 'GXCEcvbRSJeYrKw5XbnOZw',
    taskGroupId: 'FvvdpeGtQW-fCN1K0Fwzbg'
  },
  {
    taskId: 'lxUFJhJFS2CKHCcbuKCMhA',
    taskGroupId: 'FvvdpeGtQW-fCN1K0Fwzbg'
  },
  {
    taskId: 'orr9Pla4S2SzNbKkRqP0sg',
    taskGroupId: 'FvvdpeGtQW-fCN1K0Fwzbg'
  }
]
```
C locale is what we want, I think.  Just waiting for confirmation that's what's running in CI and production.

**Comment by djmitche** [comment]
In the CI image, after starting postgres with `pg_ctlcluster 11 main start`:
```
postgres=# select datname, datcollate from pg_database;
  datname  | datcollate 
-----------+------------
 postgres  | C.UTF-8
 template1 | C.UTF-8
 template0 | C.UTF-8
```
so I guess the way we're starting the `postgres:11` image is not getting the right collation.

**Comment by djmitche** [comment]
much better:
```
postgres=# select datname, 
       datcollate
from pg_database;
  datname  | datcollate 
-----------+------------
 postgres  | C.UTF-8
 template1 | C.UTF-8
 template0 | C.UTF-8
(3 rows)

postgres=# select 'abc' < 'DEF';
 ?column? 
----------
 f
(1 row)
```

**Comment by bqbn** [comment]
It is

```
 collation
------------
 en_US.UTF8
(1 row)
```

for both `communitytc` and `firefoxcitc` databases in production.

**Comment by djmitche** [comment]
Guh, and that looks like a thing you can't change without recreating the DB.  Ugh.

**Comment by djmitche** [comment]
@helfi92 looks like this is going to need a bit of thought.. let's talk at standup tomorrow.

**Comment by djmitche** [comment]
Collation documentation is [here](https://www.postgresql.org/docs/11/collation.html).

I've confirmed that collation order affects order, but is stable and does not affect equality.  So for example in `en_US.UTF8`, 'ABC' > 'abc' and the two values are considered distinct.  So, we haven't accidentally created a DB that cannot store slugids differing only in capitalization.  I think we've gotten away with not caring about collation order so far.  In production, I doubt it matters for correctness.  Users might see things sorted differently in the API, but for the most part things like clientIds are all lower-case ASCII so there's no visible difference between the collations.

That said, we should ensure we do not get caught out by this kind of thing again.  I can think of a few ways to do that:

 * pick a collation and fail if the default collation does not match (in which case we either pick `en_US.UTF8` or take a much longer TCW to dump and restore the production DBs with the `C.UTF8` collation)
 * test with both `en_US.UTF8` and `C.UTF8` default collations and override the collation for specific columns as necessary (`create table .. ( .. thing_id collate "C" .. ) ..`).  I don't think there's an automatic way to check that this is done, aside from requiring a collation on *every* column (collation is per-column, not per-table, with a per-database default that can't be changed).

**Comment by djmitche** [comment]
The tests helpfully enforce that entity-style and new-style tables and functions produce identical output, which reminds me that switching from en_US to C in production will change the output users see.  Maybe harmless, but worth noting that it will have an effect.

**Comment by djmitche** [comment]
Per standup, we're going to pick the first option and use en_US.UTF8 everywhere.
