### ISSUE TITLE
Remove fake db functions

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#3131]
Now that we've moved away from Azure and are using Postgres, the time it takes to run tests via a local postgres db vs fake db functions is not much of a big difference. Rather than having us duplicate the db business logic in two places, let's just run our tests with the postgres db. This will consist of the following changes:
* Delete `db/src/fakes`
* Remove the automation that runs the tests twice
* Update the guideline docs to reflect the new changes to step 2 of the migration

**Comment by djmitche** [comment]
We'll need to update the development docs, too.

Also, note that almost all of the tests run twice:
 * service tests treat TEST_DB_URL as a secret, and don't run in "real" mode without it -- this will require some changes
 * DB function tests automatically run against both fake and real functions

**Comment by helfi92** [comment]
Removing myself from assignee as I am not actively working on this at the moment.
