### ISSUE TITLE
Run the performance test suite on the large tables db migrations

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#3137]
...and check that performance is not affected.

**Comment by sciurus** [comment]
I think it would be a good idea to generate a report showing the frequency and average timing of the old queries and the new queries against production data, so we can understand what changes in postgres resource utilization we might see.

You should be able to dig that out of pg_stat_statements after performance test runs.

**Comment by sciurus** [comment]
As a reminder when setting up your tests, the firefox-ci-tc db currently has 8 vCPUs and 15 GB memory.
.

**Comment by djmitche** [comment]
My DB is set up with those parameters (it was already, to get good timings on the migrations).

Pushing about 600rps at my dev environment shows performance being just fine, and the SQL CPU usage is 10%.  And that's with fewer k8s pods than prod.

**Comment by djmitche** [comment]
I seem to have lost all superuser accounts on this DB, which means I can't reset statement stats or really even access them very well.  I can look at stats as they've stood since I created the DB, but of course that includes lots of old stuff like the migration scripts.  I can see:

```
dustindev=> SELECT                                                                                       
  (total_time / 1000 / 60) as total_minutes,
  (total_time/calls) as average_time_ms,
  calls,
  query
FROM pg_stat_statements
WHERE dbid=16462 and query like 'select %'
ORDER BY 2 DESC
LIMIT 10;
    total_minutes    | average_time_ms  | calls |                                                query                                                
---------------------+------------------+-------+-----------------------------------------------------------------------------------------------------
       0.37423944475 |     22454.366685 |     1 | select count(*) from indexed_tasks
        19.318426503 |     12878.951002 |    90 | select version from tcversion for update
        0.0210420843 |      1262.525058 |     1 | select * from queue_task_groups_entities
  0.0282566734333333 |       847.700203 |     2 | select * FROM pg_stat_statements
  0.0574846588833333 |      689.8159066 |     5 | select * from hooks_entities
 0.00675337746666667 |       405.202648 |     1 | select count(*) from index_namespaces
  0.0103289342333333 |       309.868027 |     2 | select value -> $1 as expires from queue_task_groups_entities where not (value -> $2)::text like $3
        0.0048984943 |       293.909658 |     1 | select count(*) from namespaces_entities
   0.841910668199999 | 190.621283366038 |   265 | select * from "queue_task_group_members_entities_scan"($1,$2,$3,$4,$5)
  0.0831114231833334 | 171.954668655172 |    29 | select * from "session_storage_table_entities_remove"($1,$2)
(10 rows)
```

many of which are just me futzing around.

Nothing is leaping out here as concerning, and we're about to do the community migration, so I'm going to count this as done :)
