### ISSUE TITLE
[UI] Keyboard accessibility

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#314]
STR:

1. Navigate to https://taskcluster-web.netlify.com/tasks/index
2. Click the tab key until the focus goes to the first namespace item:

![screen shot 2019-02-26 at 3 13 56 pm](https://user-images.githubusercontent.com/3766511/53443209-2ac8cd00-39d9-11e9-82ed-0093e3f23b31.png)

**Problem**: The is no way to jump the app bar with the tab key.

**Expected**: A "Skip to Content" button appears after the first usage of the tab key allowing the user to skip navigating the app bar if they press on enter.

**Actual**: The user is required to press the tab key 6 times before having the focus on a list item

You can see it live in action on https://github.com/taskcluster/taskcluster. Click tab and you will see a hidden button pop up.

**Comment by Aditya-Kolla** [comment]
Could I work on this? 
I'll just list out the steps I need to do, please guide me.
1] Setup a component which has three props

- id: the id of the Skip to Content button
-text: the text that we want to be displayed
-target: the target id to where we want to jump

2]Make the SkipToContent button appear after one one single tab press. (Should I do this by adding a eventlistener to the window? )

3] Properly position the SkipToContent button in our project.

Am I thinking right? :thinking:

**Comment by helfi92** [comment]
Go for it. Heading to sleep now :)

**Comment by helfi92** [comment]
We can discuss more when I’m back online. Good luck!

**Comment by helfi92** [comment]
> Setup a component which has three props

I'm not sure we need a component but I guess you can try. We can always change the code once we have something working.

> Make the SkipToContent button appear after one one single tab press. (Should I do this by adding a eventlistener to the window? )

We don't need to create any event listeners. We just need to create an `onClick` event on the button that would jump the focus to the first focusable element in `<main>`.

**Comment by helfi92** [comment]
You can also see a working example on chrome (is not supported on firefox for some reason).

_Example: After searching for "hello" in google_

![screen shot 2019-03-01 at 1 32 44 pm](https://user-images.githubusercontent.com/3766511/53658823-e97a2c80-3c27-11e9-9bee-008b58512c60.png)

_After disabling some of the css properties:_

![screen shot 2019-03-01 at 1 33 56 pm](https://user-images.githubusercontent.com/3766511/53658817-e54e0f00-3c27-11e9-9046-7baed8470d06.png)

**Comment by Aditya-Kolla** [comment]
I just opened a PR with initial commit. Please look into it :smiley:
