### ISSUE TITLE
Figure out if there are any other migrations on July 11 (TCW)

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#3144]
During the postgres 1.0 migration, there were a couple of migrations we weren't aware of which blocked us from being able to test certain functionalities during the TCW until the other migrations were done. Let's try to figure out if there's anything happening on July 11 so that we are better prepared.

**Comment by ccooper** [comment]
No other activities are planned for the TCW, although I've had it rescheduled to July 18th to give us the bake-time we'd like in the Community cluster.

I sent out the TCW notification to developers today: https://groups.google.com/a/mozilla.com/g/firefox-ci/c/-TtWCYOU_xo/m/SN0MDleyCQAJ
