### ISSUE TITLE
Add .nvmrc

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#3160]
`nvm` will look at a `.nvmrc` file to decide what version of Node to use.  This would make it a bit easier to install/use the version of node for a particular checkout:
```
lamport ~/p/taskcluster [renovate/node-12.x*] $ echo 12.18.2 > .nvmrc 
lamport ~/p/taskcluster [renovate/node-12.x*] $ cat .nvmrc 
12.18.2
lamport ~/p/taskcluster [renovate/node-12.x*] $ nvm use
Found '/home/dustin/p/taskcluster/.nvmrc' with version <12.18.2>
Now using node v12.18.2 (npm v6.14.5)
```

Can I add that file and add a generate task to update it?

**Comment by djmitche** [comment]
@helfi92 @imbstack would this work well for you or interfere with your process?

**Comment by helfi92** [comment]
I typically use `nvm alias default 12.18.2` to pin and only change it whenever we bump the version. Do we still have to `nvm install <node-version>` when using `.nvmrc`? If yes then I am unclear what benefit this would bring. Any clarifications would be appreciated :) Thanks!

**Comment by djmitche** [comment]
Different apps I work on have different defaults.  One big advantage of checking this in is that when we've landed a node version bump and some of your branches are using the old node and some the new node, just typing `nvm use` will use whatever is in `.nvmrc`.

**Comment by imbstack** [comment]
This is fine with me!

**Comment by djmitche** [comment]
ok, sounds like it will be a no-op or a little easier for everyone.
