### ISSUE TITLE
Backup the secrets in the community deployment

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#3162]
We'll want to do that during the planned downtime on July 10. It will most probably just be a script.

**Comment by helfi92** [comment]
@djmitche Where would the backup store the data?

**Comment by helfi92** [comment]
S3?

**Comment by djmitche** [comment]
No, let's put it on someone's laptop, ideally downloaded to /dev/shm and then gpg-encrypted so it never rests on disk in cleartext.

**Comment by imbstack** [comment]
How's https://gist.github.com/imbstack/402ea776aa0f3823681b55cb2559e39a for this?

**Comment by helfi92** [comment]
LGTM!
