### ISSUE TITLE
Certain github app events are being deprecated by October 1

### ISSUE THREAD

**Issue by imbstack** [taskcluster/taskcluster#3175]
Hi @taskcluster Admin,

We're contacting you regarding upcoming changes to GitHub Apps owned by your organization:
  - tc-cat
  - Community-TC Integration

We no longer support two events which your GitHub Apps may rely on, "integration_installation" and "integration_installation_repositories".

These events can be replaced with the "installation" and "installation_repositories" events respectively.

The "integration_installation" and "integration_installation_repositories" events will be removed after October 1st, 2020.

Please visit https://developer.github.com/changes/2020-04-15-replacing-the-installation-and-installation-repositories-events for more information about suggested changes, brownouts, and removal dates.

Thanks,
The GitHub Team

**Comment by ccooper** [comment]
I'm moving this issue up to the current sprint because we need a plan. Note: this issue is just for the planning portion.
