### ISSUE TITLE
[client-shell] MacOSX taskcluster cli tool isn't signed/notarized

### ISSUE THREAD

**Issue by srfraser** [taskcluster/taskcluster#3178]
**Describe the bug**

When downloading from the [client-shell readme](https://github.com/taskcluster/taskcluster/releases/download/v32.0.0/taskcluster-darwin-amd64), running the binary on recent MacOSX versions gets a warning about being unable to verify the developer, and requires the extra steps mentioned in [Apple's support](https://support.apple.com/en-gb/guide/mac-help/mh40616/mac) in order to run.

**To Reproduce**

Download and run the cli tool, without having done so before on that installation

**Expected behavior**

The binary should be trusted.

**Platform (please complete the following information):**

MacOSX 10.15.*

So the question for me is: What's the balance between this trust set-up and getting the binary trusted? I suspect this is a signing/notarisation step, and it may well be that it's more effort than we need given the scale of the current audience.

**Comment by srfraser** [comment]
Perhaps it's just a case of linking to the apple support docs and how to get it running

**Comment by djmitche** [comment]
That seems like a good start, and perhaps a good first pull request to make.

Going a little further, it'd be great to figure out if we could automate signing these binaries somehow.  My sense from what I've heard is "no", but let's find out.

**Comment by anubhabsen** [comment]
As far as I understand, to notarize, an application has to be in .app, .zip, or .pkg format, which can be exported from Xcode, but as this is a CLI tool in binary form, I doubt that is desired.
Then it needs to be uploaded to Notarization Service, from a Taskclutter/ Mozilla account, which typically takes less than an hour to get approved.
Finally, the returned ticket is "stapled" to the exported app.

Worth noting: The warning about unknown developer seems to show up only when double-clicking to run the binary. Using the command line to use it leads to no such issues (chmod +x followed by ./binary).

Fixes to double-clicking leading to the warning would be: System Preferences -> Security & Privacy -> General -> Click open anyway against the binary next to Allow apps downloaded from:.

**Comment by srfraser** [comment]
> Worth noting: The warning about unknown developer seems to show up only when double-clicking to run the binary. Using the command line to use it leads to no such issues (chmod +x followed by ./binary).

I encountered this issue trying to run the binary on the command-line.

**Comment by escapewindow** [comment]
There are two workarounds, which we should document:

1. [Unquarantine the binary](https://derflounder.wordpress.com/2012/11/20/clearing-the-quarantine-extended-attribute-from-downloaded-applications/) after downloading, using `xattr`.
1. Download via curl, wget, or another tool. Downloading via the browser sets the quarantine flag.

We do have notarization support in the FirefoxCI cluster, specifically for the `gecko` and `comm` trust domains. These use CoT verification to secure the signing pipeline. I imagine moving the taskcluster monorepo automation to FirefoxCI is a non-starter.

Another option would be to set up a mac, with XCode, for taskcluster monorepo automation. We would need an Apple developer account with a production DeveloperID (signing cert) and a notarization-enabled AppleID. That mac could use logic from [iscript](https://github.com/mozilla-releng/scriptworker-scripts/tree/master/iscript) to sign and notarize the binary. The machine will need monitoring and maintenance, and the cert and creds will need to be secured (any leak and Mallory will be able to sign and notarize any arbitrary binary using the Taskcluster cert). I imagine this is also heavyweight for the taskcluster monorepo.

I recommend the workarounds.

**Comment by djmitche** [comment]
Thanks, @escapewindow !

**Comment by anubhabsen** [comment]
So, the fix would be to add the procedure to get-around the issue on to the CLI tool's README?

**Comment by djmitche** [comment]
I think so -- it sounds like that's just using wget, curl, etc. or unquarantining with xattr

**Comment by pret3nti0u5** [comment]
Hey, I would like to work on this issue. From what I can understand I only have to document @escapewindow's workarounds to the README. If so please let me know which files I would be required to edit.

**Comment by anubhabsen** [comment]
`xattr -dr com.apple.quarantine taskcluster-darwin-amd64` should work. Should using the GUI be added too?
I am not aware of a way to do it with wget or curl. Or were you talking about fetching the file with wget and using xattr to unquarantine?

**Comment by djmitche** [comment]
@pret3nti0u5, @anubhabsen is already working on this issue.

@anubhabsen from what I understand, wget and curl automatically do the equivalent of that xattr call, so if one of those is used to download the binary then there's no need for further action.

**Comment by escapewindow** [comment]
> wget and curl automatically do the equivalent of that xattr call, so if one of those is used to download the binary then there's no need for further action.

+1.

> Should using the GUI be added too?

Since `taskcluster-darwin-amd64` is a command line tool, I would assume the person downloading it would be ok with a command line solution to unquarantine.

**Comment by anubhabsen** [comment]
So, something like `curl https://github.com/taskcluster/taskcluster/releases/download/v36.0.0/taskcluster-darwin-amd64 --output taskcluster` under Installation in the client-shell readme?

**Comment by djmitche** [comment]
That looks good!  And `curl` is installed on all macs so that should work for everyone.
