### ISSUE TITLE
static provisioner calls worker.remove, which does not exist

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#3189]
Its `removeWorker` method appears to be untested.

**Comment by djmitche** [comment]
This was broken in 30.1.1, it looks like, when we landed the worker table migration. So we should fix, but not a huge rush.

This will require adding a `remove_worker` method, so it will require a new DB version.

**Comment by djmitche** [comment]
@imbstack should we add this to the next sprint?

**Comment by milescrabill** [comment]
Looking at the behavior of the other provisioners, they don't delete workers from the DB, they delete them from their respective clouds - I suppose the assumption is that the workers will expire naturally.

We already have a `delete_worker` database function for removing workers from the DB - was there something else in mind for the static provisioner here? Perhaps the `worker.remove()` call should become `worker.delete()` to mirror the DB function and make it clearer about what is happening?

A static worker is out effectively of the control of a worker-manager provisioner aside from using the workerproto to call shutdown - maybe that's what should happen in the static provisioner's `removeWorker()` method?

**Comment by milescrabill** [comment]
Here's a snippet of what I would imagine we add to providers and to `data.js` if we choose to have providers delete workers from the DB:

```
// in data.js Worker class
async delete(db) {
  await db.fns.delete_worker(db, {
    workerPoolId: this.workerPoolId,
    workerGroup: this.workerGroup,
    workerId: this.workerId,
  });
}
```

```
// in a provider
async removeWorker({worker, reason}) {
  // delete the worker however the provider does

  // ...

  // delete the worker from the DB
  await worker.delete(this.db);
}
```

**Comment by djmitche** [comment]
The `worker.delete` method seems a good fix, but you're right that it's different from other providers, and maybe that's confusing for users.  One downside to deleting immediately would be that any history for that worker would be lost, too.  We don't actually store any history right now, but someday we will!

The alternative would be to make this act more like the other providers: put the worker into a STOPPED state, preventing it from calling (re)registerWorker anymore, and then let the worker expire naturally as you say.  Worker-manager doesn't have a direct line to the worker instance, so it can't cause an immediate shutdown command, but a failing reregisterWorker call will at least prevent the worker from doing any more work.

**Comment by djmitche** [comment]
^^ The downside with the approach I suggested there is that you can't immediately re-create the worker.  You might want to do that if you want to rotate the static secret for the worker, for example.

**Comment by djmitche** [comment]
I would like to implement the alternative here -- I think that's more in line with other providers, and in particular will keep the history of the worker intact, just like for cloud-based workers.  And since worker-runner calls `removeWorker` in some cases, it will avoid "mysteriously disappearing" workers.

That leaves the question of how to rotate the secret (or other information) for a static worker.  The expectation with the current API is "remove and re-create", but if removeWorker doesn't actually remove it then that's not such a great option.  So, I think I'll introduce an updateWorker API method which will do nothing for cloud-based provisioners but will allow updating the secret, expires, and capacity for a worker.
