### ISSUE TITLE
Enable managing the banner via the API

### ISSUE THREAD

**Issue by sciurus** [taskcluster/taskcluster#3206]
Currently the banner is controlled via [`BANNER_MESSAGE`](https://github.com/taskcluster/taskcluster/blob/48e882045d8b0891a60e40aa5196b72ba04bba63/infrastructure/k8s/templates/taskcluster-ui-secret.yaml#L16) which requires editing config and restarting the service to pick up a change. It would be handy if this could be managed via the API instead.

**Comment by helfi92** [comment]
This would probably involve adding the endpoint to the web-server service and then rewiring the UI to read from there to determine whether to show/hide the UI banner.

**Comment by djmitche** [comment]
These banners are typically related to deployment issues, so I think the current arrangement is actually the right choice.
