### ISSUE TITLE
Error displays have white-on-white text

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#324]
The background of the error display has white-on-white text

**To Reproduce**
1. Go to https://taskcluster-web.netlify.com/aws-provisioner/hg-push without being signed in
2. See error

**Screenshots**
![screenshot_2019-02-28 aws provisioner hg push - taskcluster](https://user-images.githubusercontent.com/28673/53592608-a7d47d80-3b64-11e9-83cf-9e047ea7317c.png)

Note that I have the "dark" theme, if that makes a difference..

**Comment by djmitche** [comment]
The them *does* make a difference!

**Comment by vansjyo** [comment]
@djmitche @helfi92 . I would like to work on this.
