### ISSUE TITLE
taskcluster and websocktunnel have inconsistent image tag names for the same version

### ISSUE THREAD

**Issue by bqbn** [taskcluster/taskcluster#3245]
**Describe the bug**
Take version 34.0.1 for example, the tag for image taskcluster/taskcluster is `v34.0.1`, whereas it is `34.0.1` for image taskcluster/websocktunnel.

I'm not sure if there is a historical reason for the inconsistency. If not then maybe it's a good idea to make them consistent, i.e., either both have the `v` in the tag name, or neither has it.

**To Reproduce**

1. Try `sudo docker pull taskcluster/taskcluster:v34.0.1` and `sudo docker pull taskcluster/websocktunnel:34.0.1` and see both succeed.
2. Try `sudo docker pull taskcluster/taskcluster:34.0.1` or `sudo docker pull taskcluster/websocktunnel:v34.0.1` and see either succeeds.

**Expected behavior**

Consistent naming for docker image tags.

**Taskcluster version**

Found in version 34.0.1. Probably all lower versions too.

**Screenshots**

n/a

**Platform (please complete the following information):**

n/a

**Additional context**

n/a

**Comment by djmitche** [comment]
It looks like we have at least been consistent about this :)
