### ISSUE TITLE
[UI] Add breadcrumbs to the Provisioners view

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#325]
We want to implement breadcrumbs in a similar fashion to the old taskcluster site

Old site with breadcrumbs: https://tools.taskcluster.net/provisioners/aws-provisioner-v1
New site has no breadcrumbs: https://taskcluster-web.netlify.com/provisioners/aws-provisioner-v1

![kapture 2019-02-28 at 15 43 54](https://user-images.githubusercontent.com/3766511/53597270-bc6a4300-3b6f-11e9-9a27-96552ecd6c68.gif)

For the breadcrumbs, we can use https://material-ui.com/lab/breadcrumbs/#simple-breadcrumbs.

**Comment by Paarmita** [comment]
Hey @helfi92,
I would like to work on it?

**Comment by helfi92** [comment]
Awesome, go for it.

**Comment by Paarmita** [comment]
Can you please provide some details on which file needs to be changed?

**Comment by helfi92** [comment]
> Can you please provide some details on which file needs to be changed?

The entry point for the provisioners view is in `ui/src/views/Provisioners/index.jsx`.

**Comment by Paarmita** [comment]
And I could see the new site has a different UI, so where should there be breadcrumbs?

**Comment by helfi92** [comment]
1. Same height as the dropdown
![screen shot 2019-02-28 at 4 21 24 pm](https://user-images.githubusercontent.com/3766511/53599324-ebcf7e80-3b74-11e9-891d-bba30fb51be3.png)


2. Below the blue bar 
![screen shot 2019-02-28 at 4 21 17 pm](https://user-images.githubusercontent.com/3766511/53599325-ebcf7e80-3b74-11e9-83ac-638389d46190.png)


3. Same height as the dropdown
![screen shot 2019-02-28 at 4 20 52 pm](https://user-images.githubusercontent.com/3766511/53599326-ec681500-3b74-11e9-8daa-36a82f004257.png)

**Comment by Paarmita** [comment]
New Site is this one and it has provisioners view like this. Am I right?
<img width="1440" alt="screenshot 2019-03-01 at 2 54 31 am" src="https://user-images.githubusercontent.com/26546816/53599514-5d3b1b80-3bcd-11e9-8ea7-5e8f893d9a09.png">

**Comment by helfi92** [comment]
> New Site is this one and it has provisioners view like this. Am I right?

Yep.

**Comment by Paarmita** [comment]
Thanks! Got it.

**Comment by Paarmita** [comment]
Hey @helfi92, I got some other high priority issues assigned, so I would not be able to work on this one. You can assign it someone else. 
Thanks for the help.

**Comment by vansjyo** [comment]
@helfi92  Can I work on this?

**Comment by helfi92** [comment]
Definitely!

**Comment by helfi92** [comment]
Note that I will be away all of next week. If you have questions, feel free to ask me either today. I will be able to review it when I'm back. I'm really looking forward to this feature :)

**Comment by vansjyo** [comment]
@helfi92  sure.

**Comment by vansjyo** [comment]
@helfi92 Just to clarify, I need to make a breadCrumbs components in the component folder as there was in the previous taskcluster site right?

**Comment by helfi92** [comment]
> Just to clarify, I need to make a breadCrumbs components in the component folder as there was in the previous taskcluster site right?

You can look at the old site code to have an idea of the implementation but I wouldn't do something just because it's in the old site. The new site is different than the old one. Do what you think is best. As long as the functionality works, we could always change the code structure later :)

**Comment by helfi92** [comment]
@vansjyo How is it going? Let me know if you had any questions for me :)

**Comment by ziyadElon** [comment]
@vansjyo Are you still working on this?
If not, @helfi92 may i pick this up?

**Comment by helfi92** [comment]
@ziyadElon Go for it. I haven't heard back from @vansjyo.

**Comment by ziyadElon** [comment]
@helfi92 Picking this up!

**Comment by helfi92** [comment]
Go for it.

**Comment by helfi92** [comment]
How is it going @ziyadElon? I recently added breadcrumbs to the Task Group view in  https://github.com/taskcluster/taskcluster/commit/5ac70a15886a5e7fe64b5b67bd48ffa5f8787834. You can use it for inspiration. Here's how it looks live: https://taskcluster-web.netlify.com/tasks/fBCfJ3vFRK-3zYVPs8SsLw

![Screen Shot 2019-04-18 at 10 40 48 AM](https://user-images.githubusercontent.com/3766511/56368969-75d7b300-61c6-11e9-8529-00704e42a767.png)

**Comment by ziyadElon** [comment]
@helfi92 I've hit a bit of a roadblock.
I'm assuming you have created a component for breadcrumbs to do this?

**Comment by helfi92** [comment]
Yeah. It's in `src/components/Breadcrumbs`. If you pull the latest changes, you'll be able to see it in your codebase.

**Comment by helfi92** [comment]
Also, if you're stuck, just shoot me me a message here and I'll try my best to help.

**Comment by ziyadElon** [comment]
@helfi92 Awesome! I'll look into the component and get back to you if I need any further help :)

**Comment by ziyadElon** [comment]
@helfi92 I'm unable to see my changes on the UI. 
I'm running into one issue after another. 
First, 
`Invalid value for prop `component` on <div> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM.`

Even If I bypass the above error, 
I'm getting a `network error: Failed to fetch`
`http://localhost:5080/graphql net::ERR_CONNECTION_REFUSED`

I have followed the instructions here: 
https://github.com/taskcluster/taskcluster/blob/master/dev-docs/development-process.md

But I'm still running into these issues.
Please help.

**Comment by helfi92** [comment]
> Invalid value for prop component on <div> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM.

There seems to be a bad property value being fed to a `<div>` element. If you haven't changed any code and you see that error, feel free to ignore it for now. There a couple of console message we need to fix.

> I'm getting a network error: Failed to fetch
http://localhost:5080/graphql net::ERR_CONNECTION_REFUSED

This error happens when the `services/web-server` is not configured properly. To fix the issue, you have to make sure `TASKCLUSTER_ROOT_URL` is properly configured as well as the server is running. From the root of the project, run

```bash
export TASKCLUSTER_ROOT_URL=https://taskcluster-staging.net

yarn workspace taskcluster-web-server start
```

You will know that `web-server` is is running if you see the following output:

```bash
> yarn workspace taskcluster-web-server start
yarn workspace v1.15.2
yarn run v1.15.2
$ NODE_ENV=development node src/main.js devServer

Web server running on port 3050.

Open the interactive GraphQL Playground and schema explorer in your browser at:
          http://localhost:3050/playground
```

In another terminal, you should have the `ui` running with:

```bash
# change into the ui directory
cd ui

# download the ui dependencies
yarn

# run the ui
yarn start
```

Hope that helps.

**Comment by helfi92** [comment]
This view will be removed soon. Closing for now.

**Comment by helfi92** [comment]
Re-opening this issue since it was agreed to keep this view for the beginning of redeployability.

**Comment by helfi92** [comment]
@ziyadElon Are you still interested in tackling this issue?

**Comment by rbrishabh** [comment]
I would love to take this up @helfi92 !

**Comment by helfi92** [comment]
Go for it @rbrishabh.

**Comment by rbrishabh** [comment]
Hey @helfi92 ! 

Sorry for the short delay! 
Had a busy week! Working on this, will create a PR and ask some questions today!

Have a wonderful day =)!

**Comment by helfi92** [comment]
Awesome, thanks!
