### ISSUE TITLE
Estimate worker config prices for Azure

### ISSUE THREAD

**Issue by imbstack** [taskcluster/taskcluster#3271]
Take as input an array of worker configs and give as output a price per unit time of the config.

**Comment by imbstack** [comment]
Progress today:

Looks like we can get on-demand pricing for everything in a region with a single api call. All time units are in hours. The names of instance types in this api don't match 100% with the names in the vm api itself but we can find some way to translate I expect.

Would probably want to have this running in the background once every few hours or something to update an internal list of pricing and then have decisions based on the cached data. Next steps will be to make sure we can translate instance type names reliably and some more poking to see if we can get spot worked in somehow.

```js
const got = require('got');


const main = async () => {
    const subscriptionId = process.env.AZURE_SUBSCRIPTION;
    const apiVersion = '2016-08-31-preview';
    const rateCardBaseUrl = `https://management.azure.com/subscriptions/${subscriptionId}/providers/Microsoft.Commerce/RateCard`;
    const resp = await got(rateCardBaseUrl, {
        responseType: 'json',
        headers: {
          'Authorization': `bearer ${process.env.AZURE_TOKEN}`,
          'Content-Type': 'application/json',
        },
        searchParams: {
          'api-version': apiVersion,
          '$filter': "OfferDurableId eq 'MS-AZR-0003p' and Currency eq 'USD' and Locale eq 'en-US' and RegionInfo eq 'US'",
        },
    });
    console.log(JSON.stringify(resp.body));
};
main().catch(console.error);
```

In this case, `MS-AZR-0003p` just means "on-demand pricing" in general as can be seen [here](http://azure.microsoft.com/en-us/support/legal/offer-details/)

**Comment by djmitche** [comment]
Cool!!  Some googling based on that info leads me to https://medium.com/@dmaas/how-to-query-the-azure-rate-card-api-for-cloud-pricing-complete-step-by-step-guide-4498f8b75c2c, which says that "Enterprise accounts or other special pricing plans might have a different offer ID" which sounds a lot like "Enterprise accounts have a different offer ID but I'm not sure I can say that publicly".  Maybe the offer ID should be a configuration option, and maybe there's some way to determine the offer ID for a subscription?

https://docs.microsoft.com/en-us/azure/cost-management-billing/understand/understand-usage
```
PricingModel | All | Identifier that indicates how the meter is priced. (Values: On Demand, Reservation, Spot)
```

it's so tantalizing!

Further googling to try to see if there's a way to get the cost for a particular interest came up empty.  It just confirms that Azure docs remain a rats-nest of dead links and duplicated content.  Yuck.

**Comment by imbstack** [comment]
I'm going to mark what we have here as done I think.

Next steps on making this data in a certain shape can happen when we merge it into w-m and we know what the other clouds give us.
