### ISSUE TITLE
Check that old db methods have been deprecated when redefining a function

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#3274]
When redefining DB functions the convention is to append `_{N}` where `N` is an integer representing the next version of that function. We should add a check to make sure `_{2, N-1}` have been deprecated using the `deprecated: true` field otherwise we throw an error. For example, the tests should fail if redefining `get_widgets` to `get_widgets_2` is done without deprecating `get_widgets`.

**Comment by djmitche** [comment]
We're not really following this convention, so this check wouldn't really work.  I think the `fns.md` is clear enough here.
