### ISSUE TITLE
[tc-provisioning-simulator] provide a replay of a day's worth of firefox-ci tasks

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#3333]
Let's capture a few workerpools' worth of task events for a day or two and allow replaying those.

**Comment by djmitche** [comment]
I've started capturing data.  It's probably best to run this over two days, since today was Civic Holiday in .ca.

**Comment by djmitche** [comment]
Current status:
```
  15834 gecko-3-b-linux.csv
  51325 gecko-t-t-linux-large.csv
  11674 gecko-t-t-linux-metal.csv
  16753 gecko-t-t-win10-64.csv
     81 mobile-1-decision.csv
   1685 mobile-3-b-linux-large.csv
     99 mobile-3-decision.csv
  97451 total
```
this is pretty easy, so I think I'll just leave it running for a few more days.  We can use Monday as the "ramp up" period in this data, followed by a few days of full work, and then ramp down on Saturday.

**Comment by helfi92** [comment]
> Let's capture a few workerpools' worth of task events for a day or two and allow replaying those.

Out of curiosity, how are you capturing the data from the production deployment?

**Comment by djmitche** [comment]
By listening to pulse messages -- code is [here](https://github.com/taskcluster/taskcluster-provisioning-simulator/compare/main...djmitche:issue3333?expand=1)

**Comment by djmitche** [comment]
Issue moved to [taskcluster/taskcluster-provisioning-simulator #12](https://github.com/taskcluster/taskcluster-provisioning-simulator/issues/12) via [**ZenHub**](https://www.zenhub.com/)
