### ISSUE TITLE
azure_queue_get can return the same row multiple times

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#3339]
See #3337 for what lead to this.

One thing to note here: the `azure_queue_get` calls are at *exactly* the same time.  If there's some comparison of date-times to see if they've been updated, then perhaps those date-times are exactly equal (despite microsecond accuracy).

**Comment by djmitche** [comment]
It's important to note here that we've been using `azure_queue_get` [since v29.0.0](https://github.com/taskcluster/taskcluster/commit/cf1e00c47474c92ac1d2df2ae82746236e00dbc8).

**Comment by lotas** [comment]
not valid anymore, as we got rid of those methods
