### ISSUE TITLE
Replace use of hasPrefixedScopes in docker-worker with scope expressions

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#3344]
@tomprince did something similar in #3327, but left `buildVolumeBindings` un-changed.  That's the last use of `hasPrefixedScopes`, so fixing it will allow us to remove this function's definition.

Why?
 * taskcluster-lib-scopes allows generation of better error messages for the user
 * `hasPrefixedScopes` is only used in docker-worker, so not well-tested and well-used, and poorly-tested security-sensitive code is bad
 * removing code generally simplifies a codebase -- less code to read, less code to have bugs

Note that running docker-worker's tests locally can be difficult.  It's OK to make what you think the change should look like and create a draft PR, then watch the test results on that PR.

**Comment by tomprince** [comment]
It may also be worthwhile to move docker-worker to use taskcluster-lib-scopes. It appears that it is currently using a vendored copy of that library.

**Comment by bhushan-borole** [comment]
Hello @djmitche 
I would like to work on this issue.
I referred to #3327 , but I didn't understand quite a lot.
I understood that we have to remove all the usages of `hasPrefixedScopes`, does this mean, removing the function and its usage directly?

**Comment by djmitche** [comment]
Yes, this is basically doing the same as @tomprince did, but in buildVolumeBindings.

Once that is done, no calls to hasPrefixedScopes will remain, so the function definition can be removed.

**Comment by bhushan-borole** [comment]
Thank you @djmitche for assigning me this issue.
I will start working on it.
