### ISSUE TITLE
Handle error when GitHub check artifacts are not valid JSON

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#3354]
https://github.com/taskcluster/taskcluster/blob/849fedfd567d56c6a45b48dba03984ab4283c418/services/github/src/handlers.js#L558-L565

This is trying to parse an artifact provided by a task, and on failure calling `monitor.reportError`.  But, that kind of error reporting is intended for "Quick, something's wrong with Taskcluster!" not "Oops, something's wrong with a task", which is the case here.

Instead of calling reportError in this situation, let's report the error to the person looking at the check run in GitHub.  How could we do that?

**Comment by rohitgeddam** [comment]
I would like to work on it.

**Comment by rohitgeddam** [comment]
I had setup the project locally. Can you tell me what should i do to reproduce the same bug?

**Comment by djmitche** [comment]
Here's a similar test case:
https://github.com/taskcluster/taskcluster/blob/1c027bdc7d8cc3573e89dd29420121e8fc2c4d27/services/github/test/handler_test.js#L861-L877
I'd start by making a new test case based on that one, but where the returned text is not valid JSON.  That should generate an error report.  Once that's done, look for an example of how we report errors to users, and see if you can do the same here.

**Comment by rohitgeddam** [comment]
> Here's a similar test case:
> https://github.com/taskcluster/taskcluster/blob/1c027bdc7d8cc3573e89dd29420121e8fc2c4d27/services/github/test/handler_test.js#L861-L877
> 
> 
> I'd start by making a new test case based on that one, but where the returned text is not valid JSON. That should generate an error report. Once that's done, look for an example of how we report errors to users, and see if you can do the same here.

*  if in above code snippet we use ' text: null '  at line 869, it will be an invalid json right?
* in the case where json returned is invalid. is the status still 200?
* What error should the test throw if json is invalid?

     Don't know if i asked the right questions, Please Help me through this,
