### ISSUE TITLE
Badge SVG renders as a black mask

### ISSUE THREAD

**Issue by jonalmeida** [taskcluster/taskcluster#3358]
**Describe the bug**

You cannot see the `badge.svg` that is rendered from a successful build.

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to https://firefox-ci-tc.services.mozilla.com/api/github/v1/repository/mozilla-mobile/android-components/master/badge.svg
2. Observe the SVG image that renders

**Expected behaviour**

The image of a hatchling with the text "no info"

**Actual behaviour**
You see a black mask of the image instead.

**Taskcluster version**

34.0.1

**Screenshots**

<img width="138" alt="Screen Shot 2020-08-06 at 10 34 03 AM" src="https://user-images.githubusercontent.com/1370580/89544634-5fe16d80-d7d0-11ea-82f2-717374ad8c04.png">

**Platform (please complete the following information):**

 - OS: Mac OS 10.15.6 (19G73)
 - Browser if applicable: Firefox Nightly 
 - Version if applicable: 81.0a1 (2020-08-04) (64-bit)

**Additional context**
SVGs in other web content load correctly, so I do not believe it is a bug with the browser.

**Comment by helfi92** [comment]
From https://github.com/taskcluster/taskcluster/issues/1993#issuecomment-554492194, it looks like it doesn't work very well right now.

>  When the Checks API is finished, we'll add it back.

@taskcluster/core, is the Checks API finished now?

**Comment by djmitche** [comment]
That's a separate bug -- this is some issue with the SVG.  But no, it's not finished and doesn't support badges.  I'll add that to the tracking for the tc-github sprint.

**Comment by djmitche** [comment]
I think the image here is https://github.com/taskcluster/taskcluster/blob/main/services/github/assets/newrepo.svg.

**Comment by djmitche** [comment]
Looking in the inspector in Firefox, all of the elements have `style=""`, whereas in the source SVG (and in the result of a `curl` of that URL) the style is filled in.  Filling in that style manually in the inspector fixes the coloring.  So maybe this is a browser bug..

**Comment by djmitche** [comment]
Loading the file directly works fine, and it shows up fine in https://github.com/taskcluster/taskcluster/blob/main/services/github/assets/newrepo.svg and https://raw.githubusercontent.com/taskcluster/taskcluster/main/services/github/assets/newrepo.svg

**Comment by djmitche** [comment]
Ah, it looks like using CSS in an SVG is a violation of the CSP:

blocked-uri	"inline"
column-number	10
document-uri	"https://firefox-ci-tc.services.mozilla.com/api/github/v1/repository/mozilla-mobile/android-components/master/badge.svg"
line-number	593
original-policy	"report-uri https://firefox-ci-tc.services.mozilla.com/__cspreport__; default-src 'none'; frame-ancestors 'none'"
source-file	"resource://devtools/server/actors/inspector/css-logic.js"
violated-directive	"default-src"

I'm guessing from the source-file line.  There is no line 593 in the SVG file.
