### ISSUE TITLE
queue: feature request: provide queue-max-age or queue-last-consumed

### ISSUE THREAD

**Issue by aerickson** [taskcluster/taskcluster#340]
I maintain a cluster of workers. We recently had some downtime, but it wasn't easy to detect. The queues kept growing, but that can be normal if lots of pushes/merges are happening.

If a queue is non-zero and a task hasn't been consumed in X minutes, alert.
If a queue's max-age is over X minutes, alert.

**Comment by djmitche** [comment]
Could you file this in Bugzilla?  It's something that will be more possible when the queue uses postgres, so it will need to get linked into the dependency tree.

**Comment by aerickson** [comment]
Definitely. https://bugzilla.mozilla.org/show_bug.cgi?id=1532360

**Comment by djmitche** [comment]
Thanks!  We need to have more clear guidelines on when to file a GH issue and when a Bugzilla bug.  Sorry about that..
