### ISSUE TITLE
401 on accessing artifact I have scopes for

### ISSUE THREAD

**Issue by imbstack** [taskcluster/taskcluster#3415]
**Describe the bug**
An artifact I can access using root credentials and the api is not accessible in the ui.

**To Reproduce**

1. Go to https://community-tc.services.mozilla.com/tasks/UrdriJ3rTdCnWjKMrEk6Mw/runs/0
2. Click on 'Artifacts'
3. Try to open `debug-logs/docker-push.log`
4. See the error:
```
Unauthorized (HTTP 401)
An error occurred attempting to load the provided log.
Please check the URL and ensure it is reachable.
```

**Expected behavior**
This should load the artifact

**Taskcluster version**
35.0.0-1-g6d5b0c70b (this is on community currently)

**Screenshots**
N/A

**Platform (please complete the following information):**

 - OS: linux
 - Browser if applicable: firefox nightly
 - Version if applicable: 81.0a1 (2020-08-18) (64-bit)

**Additional context**
N/A

**Comment by helfi92** [comment]
Are you trying to view a private log? If it is, then that is hopefully fixed in v37. https://github.com/taskcluster/taskcluster/commit/f8e55d2d755c13a7ec890d2872df1c5ba3c90607

**Comment by djmitche** [comment]
I get a 403 now (which makes sense, as I don't have that scope).  However, if I reload then it turns back to a 401.

**Comment by helfi92** [comment]
> However, if I reload then it turns back to a 401.

Ugh, it looks like it's trying to access `/api/queue/v1/task/UrdriJ3rTdCnWjKMrEk6Mw/runs/0/artifacts/debug-logs/docker-push.log` rather than `/api/queue/v1/task/UrdriJ3rTdCnWjKMrEk6Mw/runs/0/artifacts/debug-logs%2Fdocker-push.log` on page reload for some reason which would explain the 401.
