### ISSUE TITLE
web ui: worker detail page: sorting multiple times causes duplicate entries

### ISSUE THREAD

**Issue by aerickson** [taskcluster/taskcluster#3426]
**Describe the bug**
When clicking on the row headers to sort, if you click more than once, entries will be duplicated.

**To Reproduce**

1. Go to https://firefox-ci-tc.services.mozilla.com/provisioners/gecko-t/worker-types/t-linux-metal/workers/us-west-1/i-0ae79fdf6917dfd0c
2. Note the result count.
3. Click on 'Resolved' several times.
4. Note the result count. it has increased (some entries are duplicated).

**Expected behavior**
No duplicates would be created when sorting.

**Taskcluster version**
34.0.1

**Screenshots**
![sorting_bug_resized_optimized](https://user-images.githubusercontent.com/47889/90822103-cabe9880-e2e8-11ea-9050-c4f5b4672633.gif)

**Platform (please complete the following information):**

 - OS: Mac
 - Browser if applicable : FF
 - Version if applicable: 79

**Comment by aerickson** [comment]
It seemed to be the exceptions.

I can't reproduce either (but I can't find any workers with exceptions either).

**Comment by helfi92** [comment]
@djmitche Is there an easy way to produce an exception in a worker (maybe in a dev deployment)?

**Comment by djmitche** [comment]
It might be easiest to just hack something into the UI code to rewrite all of the statuses to exception.  But otherwise, injecting tasks with an invalid payload should do it.  https://dustin.taskcluster-dev.net/tasks/Bsvj0re1R6OJlP9jdZ7xaw for example.

**Comment by helfi92** [comment]
@aerickson I can't seem to replicate when using https://dustin.taskcluster-dev.net/provisioners/built-in/worker-types/succeed/workers/built-in/succeed.

**Comment by aerickson** [comment]
Strange. I'll reopen if I notice it again.
