### ISSUE TITLE
Bug 1527606 'Details' link on GitHub should directly point to the task logs

### ISSUE THREAD

**Issue by sudipt1999** [taskcluster/taskcluster#345]
[Bugzilla bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1527606)

Most of the time, when you click on the Taskcluster status link on GitHub, you want to see why a task failed, so it makes sense to go to the logs by default.

@helfi92  could you give some pointers on how to solve this . I would love to solve this

**Comment by djmitche** [comment]
Let's keep this on Bugzilla until we figure out how to solve it..

**Comment by owlishDeveloper** [comment]
@sudipt1999 FYI - this bug is about taskcluster-github. That is the component I mostly work on, not Hassan, so I am the one whom you should be asking.

**Comment by sudipt1999** [comment]
I am really sorry ! Wasn't aware of that !will keep in mind from next time
really sorry!
