### ISSUE TITLE
Zombie worker on proj-deepspeech/ds-macos-ds-tests workerPool

### ISSUE THREAD

**Issue by lissyx** [taskcluster/taskcluster#3471]
**Describe the bug**
Worker is up and running and executing tasks but does not show up on https://community-tc.services.mozilla.com/provisioners/proj-deepspeech/worker-types/ds-macos-ds-tests

`2020/09/01 06:01:59 WORKER_METRICS {"eventType":"taskFinish","instanceType":"","region":"","runId":0,"taskId":"VUwJqCbnTGSjbrCAQqH4og","timestamp":1598965319,"worker":"generic-worker","workerId":"tuf-1-ds-tests-cff1af83","workerPoolId":"proj-deepspeech/ds-macos-ds-tests"}`

Worker is on PDT timezone, so it's 15:01, hence 10 minutes ago.

Checking the task https://community-tc.services.mozilla.com/tasks/VUwJqCbnTGSjbrCAQqH4og shows it has been ran by `tuf-1-ds-tests-cff1af83`

This worker was deployed end of last week and has been visible on the UI since.

**Comment by lissyx** [comment]
https://community-tc.services.mozilla.com/provisioners/proj-deepspeech/worker-types/ds-macos-ds-tests/workers/proj-deepspeech/tuf-1-ds-tests-cff1af83 shows an error as well

**Comment by lissyx** [comment]
same with
`2020/09/01 06:06:26 WORKER_METRICS {"eventType":"workerReady","instanceType":"","region":"","timestamp":1598965586,"worker":"generic-worker","workerId":"ber-3-tf-build-d328a1f1","workerPoolId":"proj-deepspeech/ds-macos-tf-build"}`

**Comment by lissyx** [comment]
same with
`2020/08/29 02:40:40 WORKER_METRICS {"eventType":"workerReady","instanceType":"","region":"","timestamp":1598694040,"worker":"generic-worker","workerId":"par-2-tf-build-b992a325","workerPoolId":"proj-deepspeech/ds-macos-tf-build"}`

**Comment by lissyx** [comment]
It looks like 10 hours ago something happened, and now they are back to be visible.

**Comment by djmitche** [comment]
The queue service caches the last time it updated the status for a worker, but it looks like it caches that regardless of whether the update succeeded.  I think these workers started during an upgrade which caused DB queries to fail.  So maybe the queue's cache was "poisoned" by those failures.

**Comment by imbstack** [comment]
Ok great, going to close this for now and will reopen if we see this again!
