### ISSUE TITLE
Build a Kubernetes Operator to manage Taskcluster

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#3485]
Ricky mentioned building a K8s [operator](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/) for Taskcluster.  Basically, it's a small bit of Kubernetes that knows how to set up and manage a larger resource, or set of resources.

This looks like a great approach for making Taskcluster easier to install -- a short script to install the operator itself, followed by configuration of a "Taskcluster" resource with all the data needed to build a deployment.

This would allow us to stop using Helm, and also move a bunch of the configuration out of automatic generation of Helm and into the controller itself.

This issue is to mark this as an idea for further exploration, not a decision to do this..

**Comment by djmitche** [comment]
(and, in fact, this would deserve an RFC as we would want input from all the folks currently deploying Taskcluster)

**Comment by djmitche** [comment]
@imbstack did you want to comment on this and maybe close it up?

**Comment by imbstack** [comment]
I think the state we should leave this in is as follows:

An operator would work to deploy tc but for now it's maybe more than we need and also diverges from how mozilla deploys services so we would be maintaining two deployment mechanisms.

Let's close this for now and revisit if things change!
