### ISSUE TITLE
scan only worker pools with errors in azure::scanCleanup

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#3490]
https://github.com/taskcluster/taskcluster/blob/7f89ac84e7834a1bcc511872aa21614585e362d3/services/worker-manager/src/providers/azure.js#L787-L800

That gets every worker pool that has a worker (`this.seen`) but then does nothing for those which have nothing in `this.errors`.  That could be more efficient.

**Comment by codershona** [comment]
Hello Is this issue still open Can I work on this issue?

**Comment by djmitche** [comment]
Sounds good!

**Comment by codershona** [comment]
Thank you
