### ISSUE TITLE
authenticateHawk response has non-array scopes

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#3502]
https://sentry.prod.mozaws.net/operations/taskcluster-firefox-ci/issues/9581113/activity/?referrer=alert_email
```
Output schema validation error: 
Schema Validation Failed!
Rejecting Schema: https://firefox-ci-tc.services.mozilla.com/schemas/auth/v1/authenticate-hawk-response.json#
Errors:
  * data.scopes should be array
  ..(some other complaints about not matching the error arm of the `oneOf`)..
```
see more comment on the sentry issue.

**Comment by djmitche** [comment]
Searching by traceId (SO COOL!):

![image](https://user-images.githubusercontent.com/28673/93089711-b3fe2e00-f669-11ea-8f70-7247942c04c7.png)

So, it looks like the `authenticateHawk` call was from `queue.claimWork`, was retried after just 200ms, and the retry was successful.

We do zillions of `authenticateHawk` calls, and this is the first time we've seen this issue.

**Comment by djmitche** [comment]
I think I see the issue -- we use `scopes === null` in a place where `scopes` is `undefined`.

**Comment by djmitche** [comment]
Hm, I don't think that's it.  Looking more closely, `this._clients` has clients with undefined `scopes`, but `this._clientCache` is filled in a loop that sets `scopes` to null.

**Comment by djmitche** [comment]
BTW this occurred in v36.0.0, after 3fd060c69c265ecbdf1ef6e6690906dd453c2f5b and 9edca22ec89533160f9cd2cfde57942634489649 modified how the auth service interacts with the DB such that it uses the DB functions directly.  But, `scopes` is calculated and not retrieved from the DB, so I'm not sure how that would be related.  And a look at the diffs didn't reveal any smoking guns.

**Comment by djmitche** [comment]
Hm, I don't think that PR's putting debugging info at the right place.  `queue.claimWork` is called with temporary credentials, so the returned scopes are from `cert.scopes`, not from the client object.

**Comment by djmitche** [comment]
The worker in this case was `mobile-t-signing/mobile-t-signing-gk4fytmcssixdimll7vpq` using static client [`project/releng/scriptworker/signing/prod/firefoxci-mobile-t`](https://firefox-ci-tc.services.mozilla.com/auth/clients/project%2Freleng%2Fscriptworker%2Fsigning%2Fprod%2Ffirefoxci-mobile-t).  So my assertion in the previous comment that this call was made with temporary creds was incorrect.

**Comment by djmitche** [comment]
OK, I've spent *way* too long staring at this.  Since these are permacreds, things are pretty simple.  I've looked through the codepaths, and scopes are only manipulated in a few places.  Several of those only occur with temporary credentials.  For permacreds, it comes down to `loadClient`:

https://github.com/taskcluster/taskcluster/blob/c489ae982c06dbdc912aab6e0993e344ef5e5ce7/services/auth/src/scoperesolver.js#L315-L320

That calls the resolver:
https://github.com/taskcluster/taskcluster/blob/c489ae982c06dbdc912aab6e0993e344ef5e5ce7/services/auth/src/scoperesolver.js#L267-L292

and both return paths from the resolver return the result of [mergeScopeSets](https://github.com/taskcluster/taskcluster-lib-scopes/blob/v11.0.0/src/index.js#L144-L218).  That function would probably choke on arguments that are null or undefined, since it calls `.length` and indexes them.  It could probably survive being passed strings.  In any case, it unconditionally returns an Array: it only sets local var `scopes` once, to `[]`, and its only return path returns that variable.  So the resolver certainly returns an Array.

So `loadClient` returns the client containing the scopes to `loadCredentials`:
https://github.com/taskcluster/taskcluster/blob/c489ae982c06dbdc912aab6e0993e344ef5e5ce7/services/auth/src/signaturevalidator.js#L215-L254
`ext` is not set here, so that destructures the client and returns the scopes unmodified to the signature validator:
https://github.com/taskcluster/taskcluster/blob/c489ae982c06dbdc912aab6e0993e344ef5e5ce7/services/auth/src/signaturevalidator.js#L255-L290
Here `hawk.server.authenticate` is a part of the Hawk library and doesn't know a thing about scopes.  It returns the result of its second argument as `authResult.credentials`
https://github.com/taskcluster/taskcluster/blob/c489ae982c06dbdc912aab6e0993e344ef5e5ce7/services/auth/src/signaturevalidator.js#L292
That's then encoded into the API response shape and returned:
https://github.com/taskcluster/taskcluster/blob/c489ae982c06dbdc912aab6e0993e344ef5e5ce7/services/auth/src/signaturevalidator.js#L335-L341
and the API method changes the `expires` format and returns it:
https://github.com/taskcluster/taskcluster/blob/c489ae982c06dbdc912aab6e0993e344ef5e5ce7/services/auth/src/signaturevalidator.js#L335-L341

In all of that, my suspicion is that `if (client.scopes === null)` is the culprit and that `.scopes` wasn't null but also wasn't an Array.  So, #3504 is probably a good PR after all.

**Comment by djmitche** [comment]
Let's give this a few weeks between deployment and closing as can't-reproduce.

**Comment by djmitche** [comment]
Deployed to community today.

**Comment by djmitche** [comment]
This also occured September 18 2020 22:10:08 UTC in firefox-ci (a total of two times now)

**Comment by petemoore** [comment]
> This also occurred September 18 2020 22:10:08 UTC in firefox-ci (a total of two times now)

Ah too bad that https://github.com/taskcluster/taskcluster/pull/3504/commits/658487e8e8f940154584cd5f5760ad74814e16af hasn't made it to production in firefox cluster yet. I see we're running 37.1.0 but the extra debugging went into 37.2.0.... Hopefully it will happen again once 37.2.0 or higher is deployed...

**Comment by djmitche** [comment]
Still last reported in 37.1.0 (and I don't see it at all for community).  I'll give it another week or so.

**Comment by djmitche** [comment]
Still not seen since Sept 18.  We can re-open if this gets spotted.

**Comment by djmitche** [comment]
Occurred again at October 27 2020 10:24:08 UTC

**Comment by djmitche** [comment]
The assertion in #3502 did not fail!

**Comment by djmitche** [comment]
Here's the logging this time
```json
{
  "timestamp": "2020-10-27T10:24:08.596573156Z",
  "Fields": {
    "message": "Output schema validation error: \nSchema Validation Failed!\nRejecting Schema: https://firefox-ci-tc.services.mozilla.com/schemas/auth/v1/authenticate-hawk-response.json#\nErrors:\n  * data.scopes should be array\n  * data should NOT have additional properties: \"scheme\"\n  * data should NOT have additional properties: \"expires\"\n  * data should NOT have additional properties: \"scopes\"\n  * data should NOT have additional properties: \"clientId\"\n  * data should NOT have additional properties: \"hash\"\n  * data.status should be equal to one of the allowed values\n  * data should have required property 'message'\n  * data should match exactly one schema in oneOf",
    "incidentId": "5d75a682-63f6-4f9e-82f8-28a9b0c1876a",
    "params": {},
    "name": "Error",
    "schema": "https://firefox-ci-tc.services.mozilla.com/schemas/auth/https://firefox-ci-tc.services.mozilla.com/schemas/auth/v1/authenticate-hawk-response.json#",
    "payload": {
      "port": 443,
      "host": "firefox-ci-tc.services.mozilla.com",
      "sourceIp": "34.83.21.167",
      "authorization": "Hawk mac=\"lHeXRLchvLu44Fo0RYYG4PcTPEEryvapNjNwJn3OWZw=\", hash=\"9O/k6UTxx2c7Wq2ZG28XE/uXFX3WbGMARo7Tb0jgbCc=\", id=\"project/releng/scriptworker/beetmover/prod/firefoxci-gecko-3\", ts=\"1603794248\", nonce=\"GCW6fH\", ext=\"e30=\"",
      "resource": "/api/queue/v1/claim-work/scriptworker-k8s/gecko-3-beetmover",
      "method": "post"
    },
    "url": "/authenticate-hawk",
    "reportId": "2eaf16b208c9432981110a5fb0561c43",
    "method": "authenticateHawk",
    "stack": "Error: Output schema validation error: \nSchema Validation Failed!\nRejecting Schema: https://firefox-ci-tc.services.mozilla.com/schemas/auth/v1/authenticate-hawk-response.json#\nErrors:\n  * data.scopes should be array\n  * data should NOT have additional properties: \"scheme\"\n  * data should NOT have additional properties: \"expires\"\n  * data should NOT have additional properties: \"scopes\"\n  * data should NOT have additional properties: \"clientId\"\n  * data should NOT have additional properties: \"hash\"\n  * data.status should be equal to one of the allowed values\n  * data should have required property 'message'\n  * data should match exactly one schema in oneOf\n    at ServerResponse.res.reply (/app/libraries/api/src/middleware/schema.js:80:23)\n    at /app/services/auth/src/api.js:970:16\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
    "v": 1
  }
}
{
  "timestamp": "2020-10-27T10:24:08.597856875Z",
  "Fields": {
    "public": true,
    "sourceIp": "::ffff:10.4.4.132",
    "statusCode": 500,
    "method": "POST",
    "query": {},
    "name": "authenticateHawk",
    "expires": "",
    "clientId": "",
    "resource": "/authenticate-hawk",
    "hasAuthed": false,
    "satisfyingScopes": [],
    "v": 1,
    "duration": 285.785589,
    "apiVersion": "v1"
  }
}
{
  "timestamp": "2020-10-27T10:24:08.853340003Z",
  "Fields": {
    "query": {},
    "resource": "/authenticate-hawk",
    "duration": 6.161082,
    "v": 1,
    "expires": "",
    "hasAuthed": false,
    "method": "POST",
    "sourceIp": "::ffff:10.4.4.132",
    "satisfyingScopes": [],
    "statusCode": 200,
    "clientId": "",
    "name": "authenticateHawk",
    "public": true,
    "apiVersion": "v1"
  }
}
{
  "timestamp": "2020-10-27T10:24:28.857431344Z",
  "Fields": {
    "satisfyingScopes": [
      "queue:claim-work:scriptworker-k8s/gecko-3-beetmover",
      "queue:worker-id:gecko-3-beetmover/gecko-3-beetmover-av4vicjstlu4shcl2hvm"
    ],
    "public": false,
    "hasAuthed": true,
    "name": "claimWork",
    "query": {},
    "resource": "/claim-work/scriptworker-k8s/gecko-3-beetmover",
    "clientId": "project/releng/scriptworker/beetmover/prod/firefoxci-gecko-3",
    "method": "POST",
    "v": 1,
    "apiVersion": "v1",
    "expires": "3019-11-07T00:02:07.485Z",
    "duration": 20753.919976,
    "statusCode": 200,
    "sourceIp": "34.83.21.167"
  }
}
```

**Comment by djmitche** [comment]
Interesting that this is from scriptworker both times!

**Comment by djmitche** [comment]
Full error stack:
```
Error: Output schema validation error:                                                                                               Schema Validation Failed!
Rejecting Schema: https://firefox-ci-tc.services.mozilla.com/schemas/auth/v1/authenticate-hawk-response.json#
Errors:
  * data.scopes should be array
  * data should NOT have additional properties: "scheme"
  * data should NOT have additional properties: "expires"
  * data should NOT have additional properties: "scopes"
  * data should NOT have additional properties: "clientId"
  * data should NOT have additional properties: "hash"
  * data.status should be equal to one of the allowed values
  * data should have required property 'message'
  * data should match exactly one schema in oneOf
    at ServerResponse.res.reply (/app/libraries/api/src/middleware/schema.js:80:23)
    at /app/services/auth/src/api.js:970:16
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by djmitche** [comment]
Doing some experimenting with schema validation, I confirm that this is message corresponds to an auth-success response with a _present_ but non-array `scopes` (string, null, undefined).  But note that JSON serialization maps `undefined` to `null`, so `{..., scopes: undefined}` produces this error mesage.

**Comment by djmitche** [comment]
@imbstack and I found the issue.  The `client` returned by the scope resolver is a reference to the client object used internally in the ScopeResolver object.  The resolver lazily computes the client's expanded scopes on-demand, putting the result in `client.scopes`.  

When a client's last-used date needs to be updated, we `await` a database operation, so there's time for concurrent things to happen.

When there's a change to clients or roles, the `_rebuildResolver` method runs through all of the clients and sets `client.scopes` to null.

So we think what's happening is:
 * resolver lazily computes scopes, sets `client.scopes` to an array of strings
 * resolver calls DB to update last-used date
 * `_rebuildResolver` sets `client.scopes` to null
 * DB call returns, signatureValidator validates the signature, returns `client.scopes` -- but that's null
 * error gets thrown

@imbstack will be putting up a PR shortly, to shallow-clone the returned value and avoid this issue.

**Comment by petemoore** [comment]
Nice sleuthing! I'll take a closer look tomorrow, out for the day now.
