### ISSUE TITLE
[RFC#166] Optionally sign public S3 URLs

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#3517]
Per [RFC 166 - Sign Public S3 URLs](https://github.com/taskcluster/taskcluster-rfcs/blob/main/rfcs/0166-Sign-public-S3-urls.md)

**Comment by imbstack** [comment]
Actually @ricky26 is handling this in #3601

**Comment by ricky26** [comment]
I didn't realise this was being pulled into the private taskcluster work you were looking at (I thought you were going to be looking at just RFC#165). Sorry if I've trodden on any toes!

**Comment by djmitche** [comment]
Quite the contrary -- thank you!

**Comment by ricky26** [comment]
As I wrote the PR before I saw this, I didn't put the magic 'Fixes' comment but I think this can be closed now that #3601 has landed.

**Comment by djmitche** [comment]
Thanks for the reminder :)
