### ISSUE TITLE
[UI] Task group list some times flickers or shows blank rows

### ISSUE THREAD

**Issue by jonalmeida** [taskcluster/taskcluster#3529]
**Describe the bug**
Task group list some times flickers or shows blank results when there are a large number of updates.

**To Reproduce**

Steps to reproduce the behaviour:

1. Have a large number of tasks running.
2. Wait and watch the states of the tasks change.

**Expected behavior**
 - The task list shouldn't disappear.

**Taskcluster version**
37.1.0 (this may not be accurate, I haven't had a large list of tasks to run since 2020-09-02)

**Screenshots**
<img width="1407" alt="Screen Shot 2020-09-02 at 5 39 37 PM" src="https://user-images.githubusercontent.com/1370580/93549055-7bdf3f80-f936-11ea-9ba0-1224fc385ba3.png">

**Platform (please complete the following information):**

 - OS: Mac OS 
 - Browser if applicable: Firefox Nightly 
 - Version if applicable: 2020-09-02

**Comment by helfi92** [comment]
When did this start happening?

**Comment by djmitche** [comment]
no response here :(

This sounds like some kind of intermittent bug..

**Comment by jonalmeida** [comment]
Oops, sorry I missed this notification.

> When did this start happening?

It started on the day I filed it. I haven't seen it since, so I guess it's fair to close as intermittent.
