### ISSUE TITLE
Deprecate db function get_workers

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#3538]
**Describe the bug**
From https://github.com/taskcluster/taskcluster/pull/3520, we replaced  `get_workers` with `get_workers_without_provider_data`. We'll need to do some cleanup work:
* deprecate `get_workers` (see https://github.com/taskcluster/taskcluster/tree/main/db on how to do that)
* remove usage of `get_workers` in tests

**Comment by djmitche** [comment]
@alopezz is looking at working on this.
