### ISSUE TITLE
Replace tools-taskcluster@lists.mozilla.org list with e.g. taskcluster category on https://discourse.mozilla.org/

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#3539]
tools-taskcluster@lists.mozilla.org seems not to be working for contributors, and the mailman services are to be discontinued. We should move to a different platform.

One option is having a category "taskcluster" on https://discourse.mozilla.org/

Any other suggestions?

**Comment by ccooper** [comment]
I filed a [Jira ticket](https://jira.mozilla.com/browse/SE-1347) for this.

**Comment by ccooper** [comment]
We now have a category in Discourse: https://discourse.mozilla.org/c/taskcluster/

I've posted a message to mailing list letting people know, and have turned on the auto-responder as well so people will be reminded if/when they post to the mailing list.
