### ISSUE TITLE
Create script for building of kernel packages for docker-worker images

### ISSUE THREAD

**Issue by ccooper** [taskcluster/taskcluster#3574]
We should script up the steps in the [README](https://github.com/taskcluster/monopacker/blob/main/files/var/kernel/README.md).

**Comment by djmitche** [comment]
OK, brain dump here:
 * we need custom kernels for a few reasons:
    * need snd-aloop for loopbackAudio support
    * need v4l2loopback for loopbackVideo support
    * upgrade to avoid security issues (e.g., https://bugzilla.mozilla.org/show_bug.cgi?id=1665052)
    * need extra device nodes for AWS metal instances (snd-aloop and v4l2loopback both default to 32 loopback devices)
 * in community, only fuzzing uses loopbackAudio, and nothing uses loopbackVideo (judging by scopes)
 * -gcp kernels include snd-aloop as a module by default, but with 32 devices.  This config is used for array sizes in static variables so it's not a runtime option.
 * -aws kernels do not include snd-aloop at all (not even as a module)
    * it's possible to build and install modules for a kernel without rebuilding the kernel
 * v4l2loopback is an out-of-tree module, so it can be built with dkms against a kernel, but isn't in the kernel source
 * The v4l2loopback-dkms package is [version 0.10.0](https://packages.ubuntu.com/bionic/v4l2loopback-dkms).  We install version 0.12.5.  ISTR there's a good reason for that, although I can't find a relevant bug now.
 * v4l2loopback also defaults to 32 devices, and this is also a compile-time parameter

As far as upgrading to avoid security issues, Canonical ships updates to base images pretty quickly.  As a matter of policy we should probably rely on them to do so as upstream.

So, going back to our multi-dimensional worker configuration matrix:
 * *community / docker-worker / gcp* - needs no special treatment -- just enable snd-aloop in `/etc/modules`
 * *community / docker-worker / aws* - unused
 * *firefox-ci / docker-worker / gcp* - needs v4l2loopback module built (taskcluster/monopacker#83), snd-aloop just needs to be enabled
 * *firefox-ci / docker-worker / aws* - needs v4l2loopback and snd-aloop modules built
 * *firefox-ci / docker-worker / aws-metal* - needs v4l2loopback and snd-aloop modules built, both patched to support 96 devices

**Comment by djmitche** [comment]
So, my plan is for the ubuntu_bionic scripts to take
 * $CLOUD
 * $NUM_LOOPBACK_AUDIO_DEVICES
 * $NUM_LOOPBACK_VIDEO_DEVICES

Then build some general support, with failures for things that aren't needed and are hard.  In particular, it seems that rebuilding the kernel on gcp is hard -- the "kernel sources" appear to be a wrapper package around some signed sources.  So if anything would require rebuilding the GCP kernel (basically, if either of the NUM_* are not 32 or 0), we'll bail out.

For AWS, if NUM_LOOPBACK_AUDIO_DEVICES is zero, no build is needed.  Otherwise, we rebuild the kernel.

**Comment by djmitche** [comment]
Ah, it looks like the AWS kernel lacks some support for v4l2 as well.  So that will trigger a recompile as well.

**Comment by ccooper** [comment]
Following up on my mtg with @imbstack today re: metal instance support.

The most important thing is that we need to continue supporting the metal instances in AWS. I've reached out to GCP to see whether they're planning to launch a metal offering before the end of 2021, but as of now, they have nothing.

Second, I'd like to clarify with someone who understands the tests that require the loopback devices why we need 3 devices per worker. Maybe @jmaher knows. If we can drop that requirement, everything gets easier.

The sticking point for me with AWS support is that I don't think we know what the job distribution looks like on these metal instances with high worker concurrency. How often do we end up saturating a single instance vs running a few concurrent tasks on multiple instances? I would love to ensure that we always made sure a single instance was running at full concurrency before spinning up a new instance, but I don't think we have anyway of assessing that right now. Could the scalingRatio help here?

If we rarely hit full concurrency, I would suggest scaling back the # of workers per instance to fit under the existing loopback device limit in the kernel and avoid rebuilding the kernel/module at all. Note that we already run with only 15 workers on the m5.metal instances, so dropping it to 10 workers isn't as large a delta. 

We're spending a third of what we were spending in packet.net for AWS bare metal, so we have headroom if we need to increase the number of instances we do run, assuming AWS has the capacity.

**Comment by jmaher** [comment]
in answer to the multiple devices needed - I don't know why we would need more than 1 audio or 1 video devices; maybe we need a device for input/output and maybe multiple streams in parallel?  If we had an image with a single audio and single video device it could be run through try server and we could see what is broken.

**Comment by djmitche** [comment]
I'm pretty sure docker-worker only gives each container a single video device and a single audio device.

I think the "3" came from 96 / 32, where 96 is the total number of devices configured in the existing image scripts, and 32 is the largest value of `capacity` in the worker configs.  My guess is that wcosta selected 96 while experimenting with total capacity and performance, and didn't change that after selecting 32 as the best value of `capacity`.
