### ISSUE TITLE
Experiment with using GCP-based images for building docker-worker kernels

### ISSUE THREAD

**Issue by ccooper** [taskcluster/taskcluster#3575]
We currently use `-aws` kernel packages for both AWS and GCP. We should try creating kernels for GCP using a `-gcp` rev kernel package.

If the process, works we should run some basic tests to see if we get any speed-up or related wins.

**Comment by djmitche** [comment]
It turned out that the GCP kernels were a lot easier to deal with, so this sort of went from "experiment" to "let's do it".  We can probably close this once we see that a worker on GCP with a GCP kernel can successfully complete a task with loopbackAudio/Video. /cc @imbstack
