### ISSUE TITLE
Measure baseline load on auth service before making any changes

### ISSUE THREAD

**Issue by ccooper** [taskcluster/taskcluster#3584]
Before we make any changes for anonymous scopes, we should make sure we can assess what the impact might be in terms of increased load.

**Comment by djmitche** [comment]
I'll get some figures for
 * hourly average rps for the auth service
 * corresponding pod load figures (count, cpu, memory)
across both production deployments.

**Comment by djmitche** [comment]
firefox-ci-tc: requested 1.000 CPU for 10 pods (so 0.100 each), uses about 0.200-0.300, pretty steadiliy over a week.  Total memory requested is 2GB, with about 650MB used.

**Comment by djmitche** [comment]
community-tc: requested 0.100 CPU for 1 pod, uses 0.020 - 0.050.  Total memory request is 200M, used is 62M.

**Comment by djmitche** [comment]
As for rps of calls to authenticateHawk, looking over the last 7 days and reading the stackdriver histogram:
* community-tc: about 3.5rps with spikes to 9rps
* firefoxci-tc: 400,000-500,000 requests per 2-hour bucket, or about 110-140rps.

Stackdriver wasn't able to give a full 7-day result for firefox-ci, but that seemed pretty stable over 4 days.  Most of the API access occurs via automation, so it's not too surprising that it would not have a large 24-hour component.
