### ISSUE TITLE
Update taskcluster-lib-api to deal with anonymous scopes

### ISSUE THREAD

**Issue by ccooper** [taskcluster/taskcluster#3586]
The authentication middleware in taskcluster-lib-api, used by all services, needs to no longer early out if there are no authorization headers.

Also, the API builder in taskcluster-lib-api needs to be changed to assert that at least one scope is required except for endpoints which explicity opt-out (which should be just authenticateHawk and authenticateAnonymous).

See https://github.com/taskcluster/taskcluster-rfcs/pull/165

**Comment by petemoore** [comment]
WIP in #3615
