### ISSUE TITLE
[PROJECT SETUP] Server not starting on `yarn start`

### ISSUE THREAD

**Issue by Jaffrey98** [taskcluster/taskcluster#359]
I have followed the steps mentioned [here](https://github.com/taskcluster/taskcluster/tree/master/services/web-server#user-content-running-taskcluster-web-server-locally) 

But when I run `yarn start` the server doesn't seem to start but it seems a build operation is being performed:

Since I'm running it on Windows I had to modify the `start` script to :
```json
"start": "SET NODE_ENV=development && webpack"
```

This is the output when I execute `yarn start`
```
D:\Projects\GSOC\taskcluster\services\web-server>yarn start
yarn run v1.13.0
$ webpack
Hash: cdae6da011a399da162c
Version: webpack 4.29.0
Time: 3523ms
Built at: 03/05/2019 7:24:01 PM
       Asset     Size  Chunks             Chunk Names
    index.js  101 KiB       0  [emitted]  index
index.js.map  203 KiB       0  [emitted]  index
Done in 6.22s.
```

**Comment by djmitche** [comment]
I think you changed the definition of `yarn start` to the wrong thing.  Check what the original setting is, and try to modify that to work on Windows.

**Comment by Jaffrey98** [comment]
@djmitche Thanks for the tip!!

I installed a package called `cross-env` and modified the `start` script to 
```json
"start": "cross-env NODE_ENV=development webpack"
```

and that fixed it!!!!

**Comment by djmitche** [comment]
Great!
