### ISSUE TITLE
Update signature validators to be deal with anonymous scopes 

### ISSUE THREAD

**Issue by ccooper** [taskcluster/taskcluster#3590]
The remote signature validator (used by all services except the auth service) should call authenticateAnonymous if no authorization headers are passed.

The auth service signature validator should be changed to return the scopes expanded from ["assume:anonymous"] if no credentials are passed.

The auth service signature validator should include the expanded anonymous scopes when using credentials after applying scope restriction.

See https://github.com/taskcluster/taskcluster-rfcs/pull/165

**Comment by petemoore** [comment]
WIP in #3615
