### ISSUE TITLE
DB collation tests are invalid

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#3598]
**Describe the bug**
In #3219 we introduced db collation tests, that don't accurately capture if the DB collation is correct or not.

They check, for example, that `'a' >= 'A'` - which is true for case sensitive comparison _and_ case insensitive comparison.

Instead the check should be `>` rather than `>=`. For a case-insensitive collation, the first character is always considered less than or equal to the second character, whereas, for a case-sensitive collation, there are entries in the list where the first character is considered higher than the second character.

To recap, the __desired__ collation is case-insensitive ordering (i.e. __doesn't care__ about case).

The pairs checked are [here](https://github.com/taskcluster/taskcluster/pull/3219/files#diff-57f9f48e1fee6178bc651b965dd71599R391). With `>=` changed to `>` they would work correctly as follows:

* `'a' > 'A'` => nondesirable ordering (e.g. case sensitive)
* `'a' > 'b'` => nondesirable ordering (really bad ordering - not even case sensitive ordering)
* `'A' > 'b'` => nondesirable ordering (really bad ordering - not even case sensitive ordering)
* `'a' > 'B'` => nondesirable ordering (e.g. case sensitive)
* `'A' > 'B'` => nondesirable ordering (really bad ordering - not even case sensitive ordering)
* `'0' > 'a'` => nondesirable ordering (some weird ordering for numbers to come after Latin letters)
* `'0' > 'A'` => nondesirable ordering (some weird ordering for numbers to come after Latin letters)

If _none_ of these results return `true`, there is a _reasonable_ chance the collation is suitable, and the ordering is correct.

**Comment by petemoore** [comment]
@djmitche @helfi92 @ricky26 At the time I wrote the description above, I misunderstood the requirements, and believed that case-insensitive partial ordering was required. It is now clear to me (from #3600) that a total ordering is required, and therefore if any of the character pairs are considered equal, an error should be thrown. Therefore I believe the former _stricter_ check that used `>=` rather than `>` captures more failure cases than the version from this PR. In other words, I think we should revert this PR. Do you agree?

Kudos to @helfi92 for pointing out that `>=` works in a correctly configured database, and to @djmitche for pointing out that a [total ordering](https://en.wikipedia.org/wiki/Total_order) is required. I think we since established that @ricky26 experienced a genuine failure case that the test caught (which the updated test would have also caught, but the original stricter version may also catch cases that the updated test wouldn't). And with #3600 the error message is more understandable.

**Comment by ricky26** [comment]
@petemoore sorry for my part in this but I agree. I think #3600 is the real solution.

**Comment by djmitche** [comment]
> Do you agree?

I do.  Reference my earlier comment about me and inequalities!
