### ISSUE TITLE
New UI: Task group summary requires more attention than the old one

### ISSUE THREAD

**Issue by glandium** [taskcluster/taskcluster#361]
With the old task group summary, it was obvious, at a quick glance, whether everything was green or not: if that were the case, you'd have a 100% width green bar, and nothing else. If there were some failures, then the green bar would be smaller and other colors would pop in.

In the new UI, all the statuses take up the same space in all cases, and now you actually need to go through all the statuses to see whether one of the non-greens is not zero.

Note that I'm not necessarily asking that the old UI is duplicated, but that some thought be given to making the "all green" case is more visible somehow.

**Comment by helfi92** [comment]
Agreed. In order to improve the experience, one thing we can do is decrease the opacity of a status button that has a "0".

![Screen Shot 2019-03-11 at 2 17 34 PM](https://user-images.githubusercontent.com/3766511/54147595-e857b500-4408-11e9-87f4-906474ef2286.png)
