### ISSUE TITLE
inconsistencies in workers ui for worker types that haven't taken jobs recently

### ISSUE THREAD

**Issue by bhearsum** [taskcluster/taskcluster#3612]
While bringing a new worker online today I noticed a bit of weirdness in the `Workers` UI. It's possibly there's two issues, but I'm not really sure so I'll describe them both here.

At the time of writing, there is at least one active `tb-depsigning-mac-v1` workers. In the `scriptworker-prov-v1` workerPool, that workerType is not shown at all:
![image](https://user-images.githubusercontent.com/49649/94952286-bce95f00-04b3-11eb-8849-15e6e11dd33e.png)

However, https://firefox-ci-tc.services.mozilla.com/provisioners/scriptworker-prov-v1/worker-types/tb-depsigning-mac-v1 clearly shows one worker for it:
![image](https://user-images.githubusercontent.com/49649/94952340-d12d5c00-04b3-11eb-9c58-171f44b97b69.png)

But if I click into https://firefox-ci-tc.services.mozilla.com/provisioners/scriptworker-prov-v1/worker-types/tb-depsigning-mac-v1/workers/mdc2/dep-mac-v3-signing1tb, it 404s:
![image](https://user-images.githubusercontent.com/49649/94952375-e1ddd200-04b3-11eb-9074-483081a1f724.png)

I'm guessing (without any real evidence) that this is related to the fact that we haven't seen any tasks for these workers for months.

**Comment by imbstack** [comment]
That's a correct assumption. That page is all queue data which is just from claiming work. We have an api to find worker-manager's view of workers but never finished building UI for it :/

Maybe this is just another vote for us finishing that work

**Comment by lotas** [comment]
We have refactored workers and worker pools UI, I think we show both queue and w-m views to give full overview. 
I'll close this one, feel free to reopen
