### ISSUE TITLE
Decide best way to get tests passing that require role `anonymous` to have `service:*`

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#3617]
In production, the `anonymous` role will be defined in our public taskcluster deployments,  and will probably contain the single scope `service:*`. Probably, a bunch of our tests will currently fail, since when the tests run, this role does not exist by default. However, the scopes that the `anonymous` role will have in our deployment, is different to what they will be in other (private) deployments, so it does not necessarily follow that we only care about the situation when the role exists and has specifically the `service:*` scope.

It may be worth having our test harness(es) create the role `anonymous` created with the single scope `service:*` by default, but where we are able to disable that behaviour for specific test cases where we want to test it having a different set of scopes.

So this sprint task is really about assessing which tests currently fail in #3615 due to the absence of the `anonymous` role, and then deciding the best way to fix them, perhaps by updating all the failing tests individually, or perhaps making a blanket change in the test harness to create a reasonable default value, and then having extra tests that check when it has a different value.

**Comment by djmitche** [comment]
Which tests are you concerned about, in particular?  Most tests don't talk to the "real" auth service (for this reason).

**Comment by petemoore** [comment]
In the end we didn't go with `service:*` scope names, and also it was relatively straightforward to either create the `anonymous` role in tests that needed it, or to grant the client that ran the test more scopes than it previously had, so this was all solved in #3615.
