### ISSUE TITLE
workerproto is internal and can't be consumed by other Go projects

### ISSUE THREAD

**Issue by ricky26** [taskcluster/taskcluster#3619]
**Describe the bug**
`internal/workerproto` contains an implementation of the protocol used by worker-runner to talk to workers. Due to being in an `internal` directory, it can't be used in out-of-tree projects.

**Expected behavior**
`workerproto` should be available for out-of-tree worker implementations.

**Taskcluster version**
v37.3.0

**Comment by djmitche** [comment]
The reasoning for this was that, at the time, I was making lots of changes to the API.   I think that's better now.  So this should just be a rename to `tools/workerproto`.
