### ISSUE TITLE
Error thrown for duplicate key value violates unique constraint "indexed_tasks_pkey"

### ISSUE THREAD

**Issue by imbstack** [taskcluster/taskcluster#3635]
**Describe the bug**

It appears that index inserting is behaving differently than before. I'm guessing in this case we should either throw a user-facing error or idempotently succeed.

[View this in Sentry](https://sentry.prod.mozaws.net/operations/taskcluster-firefox-ci/issues/9746308/)

**Comment by djmitche** [comment]
same as #3463?

**Comment by djmitche** [comment]
yup
