### ISSUE TITLE
UI: Intermittent `Network error: JSON.parse: unexpected character at line 2 column 1 of the JSON data` 

### ISSUE THREAD

**Issue by JohanLorenzo** [taskcluster/taskcluster#3636]
**Describe the bug**
Sometimes, the UI reports this error: 

![image](https://user-images.githubusercontent.com/5907366/95560456-98dccf00-0a19-11eb-99ab-57dfe2e187c1.png)

The URL I wanted to reach was https://firefox-ci-tc.services.mozilla.com/auth/clients/project%2Freleng%2Fscriptworker%2Fbeetmover%2Fdev%2Ffirefoxci-mobile-1.

**To Reproduce**

I don't know how to reproduce it 😞 I know @alopezz, a contributor, saw it yesterday. He wanted to see the logs of a task. Today, I hit it on another TC resource. In my case, I opened the page yesterday, and it was working fine. I switched to another tab, then put my laptop into hibernate mode. Today, I unlock my laptop, switch to FIrefox Nightly, switch to that tab and get the error.

The devtools didn't show any error in the console. The network tab didn't show any requests. 

So I'm just filing this issue for the sake of tracking it until we get more reliable STRs. 

**Expected behavior**
The taskcluster webui should display the expected resource, instead.

**Taskcluster version**
v37.3.0

**Screenshots**
See above.

**Platform (please complete the following information):**

 - OS: macos 10.15
 - Browser: Firefox Nightly
 - Version: 83.0a1, 20201005215809

**Additional context**
None.

**Comment by djmitche** [comment]
I believe this was a result of some errors talking to the backend, which the Apollo GraphQL client blindly tries to parse as JSON.  These have been fixed in 38.x, as well as error messages improved.
