### ISSUE TITLE
Be able to cancel an entire Task Group

### ISSUE THREAD

**Issue by gsnedders** [taskcluster/taskcluster#3652]
It would be nice to be able to do the operations one can do on a Task (e.g. Cancel/Retrigger/Rerun etc.) at the Task Group level. My primary use-case for this is to decrease CI load when I end up making multiple pushes in quick succession and only care about the latest running to completion.

**Comment by djmitche** [comment]
The shell client has support for this:

```
rubin ~ $ taskcluster group cancel --help
Cancel a whole group by taskGroupId.

Usage:
  taskcluster group cancel <taskGroupId> [flags]

Flags:
  -f, --force                Skip cancellation confirmation.
  -h, --help                 help for cancel
  -w, --worker-type string   Only cancel tasks with a certain worker type.
```

Historically, it wasn't possible to implement this any more efficiently in the queue service than just listing the task group and repeatedly calling cancelTask (which is what the shell client does).  We've avoided providing such "wrappers" in the services as they tend to obscure complexity and make error-handling difficult without offering any performance benefit.

But, now that we're using Postgres, it may be possible to do this in a single DB transaction, keeping the various guarantees about task statuses.  In which case, it would make sense to add `cancelTaskGroup` and `rerunTaskGroup` API methods (I don't think `scheduleTaskGroup` would make sense).

**Comment by lotas** [comment]
During the latest [community meeting](https://docs.google.com/document/d/1dCQScxwH04VInIntxesYVQ8te1IvLTZXWYrHNgi1Irc/edit#heading=h.9h1z3fyzizkv) it was agreed that we would always pass both `taskGroupId` and `projectId` to simplify permission system  and to avoid cancelling tasks from different projects in the same task group

**Comment by lotas** [comment]
ok, we had a bit more of the conversation with @petemoore and we discussed different scenarios and use cases.
we have later agreed that cancelling tasks in task group that is not sealed is not ideal.

So we are going to add #6059 first and require task group to be sealed before one could cancel all tasks within.

CLI tool can do this  manually by first calling `q.sealTaskGroup(tgId)` and then doing `q.cancelTaskGroup(tgId, [..projectIds..])`
