### ISSUE TITLE
✨ See also: Bugzilla ✨

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#366]
The Taskcluster team uses Bugzilla as its primary bug-tracking tool.  In particular, bugs which are connected to other work or people at Mozilla and bugs which involve a large amount of work are best tracked in Bugzilla.

*tl;dr*: **If the issue you are raising is not a UI bug or is more than a quick-fix, please file it on Bugzilla.**

You can see a list of all Taskcluster bugs [here](https://bugzilla.mozilla.org/buglist.cgi?list_id=14601424&resolution=---&query_format=advanced&product=Taskcluster), or file a new bug [here](https://bugzilla.mozilla.org/enter_bug.cgi?product=Taskcluster).

**Comment by imbstack** [comment]
We're now tracking as much work as possible in github issues
