### ISSUE TITLE
Investigate feasibility of AWS marketplace taskcluster offering

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#3663]
It may be possible to offer taskcluster as a service via the AWS marketplace to arbitrary AWS users. At the moment we don't know much about the mechanics of the AWS marketplace, so this epic is to perform a feasibility study, prior to any actual implementation. The goal of this epic is to have an understanding of the amount of work that would be involved in order to offer taskcluster as a service, how the offering would look to users, how it could be marketed inside AWS, and to have an overview of how the financing works, should Mozilla choose to offer it as a paid service.

**Comment by djmitche** [comment]
@petemoore can you add an initiative tag?

**Comment by djmitche** [comment]
(moved to taskcluster/scrum#43)
