### ISSUE TITLE
[object service] add a simple, temporary upload API

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#3715]
This is just a way to make an API call to upload some data.  We will make no promises about API compatibility, and this doesn't have to be especially featureful.  This is basically a way to get some data into a test deployment and exercise backends, etc.

**Comment by helfi92** [comment]
From what I understand, the API (e.g., `/upload`) would take `data` (which is a json with no particular schema attached to it for the mvp) as input and then call a db function to insert that data inside the objects table. Is that correct? Is there anything else I'm overlooking here? Thanks.

**Comment by djmitche** [comment]
The data should be stored in the the storage backend (we'll make an InMemoryBackend or something like that for testing).  So this issue should make a rough draft of how we'll handle that: the response from `/upload` should have enough information that the caller can upload the data to the backend.

**Comment by djmitche** [comment]
I put some notes in #3861.  We'll also want to decide on a backend when beginning the upload.

**Comment by djmitche** [comment]
(I'm trying to balance solving one or two problems per issue, so we don't want the *simplest* solution, but we also want something that can be written in a day or so)
