### ISSUE TITLE
[object service] build a download API with future-expandable "approaches" and a temporary approach

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#3716]
Let's build a way of downloading files that is future-expandable.  Basically, the client sends the approaches it knows how to use, and the server responds with the best of those approaches that it also supports, or an error.

This is for the "full" download API, so the response is a data structure with enough information for the caller to reliably get the data, rather than a redirect or anything like that.

Implement an initial, temporary approach that gets the job done, but which we don't plan to keep compatibility with for very long.

**Comment by helfi92** [comment]
I had a few questions:

> Basically, the client sends the approaches it knows how to use

Do you have examples of approaches?

> the server responds with the best of those approaches that it also supports

How is "best" determined?

> the response is a data structure with enough information for the caller to reliably get the data

Do you have an example of "enough information"? Would that just be a `url` to send the request to download?

Thanks!

**Comment by djmitche** [comment]
Those are good questions so I don't have precise answers to them.  But I can try to at least fill out the ideas :)

> Do you have examples of approaches?

Approaches might be:
 * A single URL to which a GET request should be made
 * A URL that supports Range requests
 * A bittorrent-style download seed so workers can share data with each other (crazy!)

The general idea is that we want to be future-compatible with interesting new ideas for how to perform a download.  We would probably always have a "preferred" approach, maybe one or two deprecated approaches, and maybe some interesting optional approaches like bittorrent.  So something like scriptworker would probably stick to the preferred approach, while the fanciest workers would support both the preferred approach and the bittorrent approach.

From the negative perspective, the general idea is to avoid locking ourselves into an approach that doesn't support some kind of functionality we would like.

> How is "best" determined?

To be determined.  I would guess that the services define an order of preferences, and just take the most-preferred of the options that both the API client and the object's backend support.  For example, bittorrent > url-with-ranges > single-url.  But not all backends support bittorrent.  So a download request where the client supports [bittorrent, url-with-ranges, single-url] and the backend supports [url-with-ranges, single-url] would choose url-with-ranges.

> Do you have an example of "enough information"? Would that just be a url to send the request to download?

It would depend on the approach.  It would include a URL or a bittorrent seed or whatever information is necessary to get the data, plus metadata like hashes, size, and compression.
