### ISSUE TITLE
[object service] define a db table for objects

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#3717]

**Comment by djmitche** [comment]
I've been tossing around what this needs to look like, having lots sight of the "MVP" approach we're taking for now.

For the moment, working on a branch, it really doesn't matter.  Just build it :)

**Comment by helfi92** [comment]
An `object_service` table with columns `name`:string , and `data`:jsonb is what you had in mind for the "MVP" approach?

**Comment by djmitche** [comment]
That sounds good.  Probably `objects` is a good table name.
