### ISSUE TITLE
Routes containing slashes do not get indexed, with no visible error

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#3721]
Thanks to @ricky26 for spotting this.  

https://community-tc.services.mozilla.com/tasks/c4FFtHALTq6MqZqZregE1Q
```
{
  "provisionerId": "built-in",
  "workerType": "succeed",
  "schedulerId": "taskcluster-ui",
  "taskGroupId": "c4FFtHALTq6MqZqZregE1Q",
  "dependencies": [],
  "requires": "all-completed",
  "routes": [
    "index.project.taskcluster.foo/bar/slash"
  ],
  "priority": "lowest",
  "retries": 0,
  "created": "2020-10-21T15:52:53.138Z",
  "deadline": "2020-10-22T03:52:53.138Z",
  "expires": "2020-10-28T15:52:53.138Z",
  "scopes": [],
  "payload": {},
  "metadata": {
    "name": "Testy",
    "owner": "unkown@localhost.local",
    "source": "http://foobar.com",
    "description": "jonas damn you <-- :heart:"
  },
  "tags": {},
  "extra": {}
}
```
this task succeeded, but no index entry appeared.  I don't see any logging (aside from db-pool-counts) from index at this time.  Modifying the task to change `/` to `.` in the route succeeds.

Nothing in the [AMQP Spec](https://www.rabbitmq.com/resources/specs/amqp-xml-doc0-9-1.pdf) disallows `/`, so I think this is an issue in the index, and I'm not sure how best to make the error obvious to users.

**Comment by djmitche** [comment]
The proximal cause appears to be
https://github.com/taskcluster/taskcluster/blob/b3a64063e941cbd55c3c650b21cbf429dcde840a/services/index/src/helpers.js#L7
that format is used to filter routes:
https://github.com/taskcluster/taskcluster/blob/b3a64063e941cbd55c3c650b21cbf429dcde840a/services/index/src/handlers.js#L76-L82
and also appears in the API, restricting the `index.insertTask` method:
https://github.com/taskcluster/taskcluster/blob/b3a64063e941cbd55c3c650b21cbf429dcde840a/services/index/src/api.js#L25-L28

I'm not sure if `/` was disallowed there by accident, or on purpose.  The reasons I can think of to intentionally disallow it are to avoid confusion in a URL and to avoid scopes shadowing one another.  Those would happen where a namespace is embedded in a string that is looking for a `/` after the namespace.

Scopes don't appear to be an issue:
```
lamport ~/p/taskcluster [main] $ grep scopes: services/index/src/api.js 
  scopes: 'index:insert-task:<namespace>',
  scopes: { if: 'private', then: 'queue:get-artifact:<name>' },
```

however, routes are problematic:
```
lamport ~/p/taskcluster [main] $ grep route: services/index/src/api.js 
  route: '/task/:indexPath',
  route: '/namespaces/:namespace?',
  route: '/namespaces/:namespace?',
  route: '/tasks/:namespace?',
  route: '/tasks/:namespace?',
  route: '/task/:namespace',
  route: '/task/:indexPath/artifacts/:name(*)',
```

A request like `/task/project.taskcluster.foo/artifacts/bar/artifacts/some/artifact.json` is ambiguous, with two valid pairs of `indexPath` and `name`.

So:
 * We should document this more clearly; those regexp's in `api.js` don't end up in the docs anywhere.
 * We should look for ways to give some indication to the user that their route wasn't accepted.

Good-first-bug for the first part.

**Comment by djmitche** [comment]
Oh, and for the record:
https://github.com/taskcluster/taskcluster/blob/b3a64063e941cbd55c3c650b21cbf429dcde840a/services/index/src/handlers.js#L84-L88
`debug()` only logs things during testing, and then only if `DEBUG=*`.  Even so, service logs aren't typically visible to people creating tasks, so changing that to `monitor.log` isn't a great solution.

**Comment by djmitche** [comment]
One thing we could do, that would reduce some user confusion, is to add a new `indexAt` property to a task, with a list of index paths at which to index this task.  The queue could still accomplish that indexing by sending pulse messages, or we could switch to the queue calling `index.insertTask` directly.  Either way, this property could include in its schema a prohibition on `/`.  (This is not part of the good-first-issue)

**Comment by SushantAA** [comment]
I want to work on this issue

**Comment by djmitche** [comment]
Sounds good!  Let's focus on
 * We should document this more clearly; those regexp's in api.js don't end up in the docs anywhere.

**Comment by SushantAA** [comment]
Thank you @djmitche  
So, In the documentation I have to specify the regexp's like route and name present in api.js, then mention the ambiguous case.

**Comment by djmitche** [comment]
That's right, although it would be easier for users to understand if the documentation just said that slashes aren't allowed, rather than giving a regular expression :)

Note that documentation is automatically generated, so you will want to add the documentation in https://github.com/taskcluster/taskcluster/blob/main/services/index/src/api.js and then run `yarn generate` to distribute that to all the places it needs to be shown.

**Comment by SushantAA** [comment]
Is this ok 
https://github.com/SushantAA/taskcluster/blob/main/services/index/src/api.js
I haven’t run yarn generate

**Comment by SushantAA** [comment]
tell me something is missing or wrong 
then I will PR it

**Comment by djmitche** [comment]
It's usually best to just start a PR, rather than link to commits.  In this case, you've made the change in the right place, but it's a little unclear where the slashes aren't allowed.

Let's also add a note here -- https://docs.taskcluster.net/docs/reference/core/index/#indexing-routes -- since that's where people might learn that they can put indexes into a task's `routes`.

It will be good for you to get the development environment up and running for future work on the project, but while you're working on that we can run `yarn generate` on a PR for you and get it merged.

**Comment by djmitche** [comment]
My comment wasn't very clear.  I'm asking for two changes:
 * clarify where slashes are not allowed
 * add a note to the other location in the docs
