### ISSUE TITLE
Python client does not list 'aiohttp' dependency

### ISSUE THREAD

**Issue by ahal** [taskcluster/taskcluster#3730]
**Describe the bug**
The Python client depends on `aiohttp` but does not list it in its requirements:
https://github.com/taskcluster/taskcluster/blob/main/clients/client-py/setup.py#L26

This is causing errors in `mozci` where we depend on the Python client.

**Comment by djmitche** [comment]
It does, though (just only on Py3):
https://github.com/taskcluster/taskcluster/blob/d76576786c3b7efb69af0b74eefc9d369213ac2d/clients/client-py/setup.py#L65

Are you using Py3?

**Comment by djmitche** [comment]
Looks like py3.7 from https://travis-ci.org/github/mozilla/mozci/builds/737770686 and that also installs aiohttp (this job is from before 1df4bc8)

**Comment by ahal** [comment]
Oh, I missed that! I was getting `ImportError` on `aiohttp` locally even after running `poetry install`. Am using Python 3.8, but this is my problem not yours. Sorry for the noise!

**Comment by ahal** [comment]
Just noting that for whatever reason `aiohttp` does not appear in the `poetry.lock` file prior to when I added it there manually. This means that it's expected that it not get installed. I'm not sure if that's a bug in poetry, or an unavoidable side-effect of how the `aiohttp` is behind an if statement in the client's setup.py. It does appear that projects that use poetry and depend on taskcluster could be broken.

A possible fix might be to use environment markers rather than if statements:
https://www.python.org/dev/peps/pep-0496/#examples

I'll leave it up to you on how to proceed. In the meantime adding `aiohttp` manually is a simple enough workaround for us.

**Comment by djmitche** [comment]
Hm, environment markers seems like an interesting idea -- let's try that out?
