### ISSUE TITLE
UI flow when rerunning a task is unintuitive

### ISSUE THREAD

**Issue by bhearsum** [taskcluster/taskcluster#3780]
When rerunning a task with the Taskcluster UI I find the flow to be confusing. Beginning on a task page, I use the "Rerun" button from the hamburger menu, which ends up redirecting me to an `Action: Rerun` task. When this task goes green, it always makes me think my rerun has succeeded (not that triggering the rerun has succeeded).

As a user that cares about the task I'm rerunning, I don't _really_ care about the `Action: Rerun` task. I would expect that either I would be redirected back to the task page immediately after requesting the rerun, or perhaps redirected back to the orginal task after the `Action: Rerun` task completes successfully.

**Comment by lotas** [comment]
I will close this issue and work on a fix in #5046
