### ISSUE TITLE
allPurgeRequests returns a continuationToken when there's nothing more`

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#3789]
```
}(ve) rubin ~/tmp $ curl https://dustin.taskcluster-dev.net/api/purge-cache/v1/purge-cache/list
{
  "continuationToken": "",
  "requests": []
}
```

When there's no more data, the `continuationToken` property should be omitted, not just an empty string.

Depending on implementation, that could cause a caller to loop endlessly calling this endpoint.

Other endpoints (at least `auth.listClients`) get this right, so what's the difference for this method?

**Comment by rbrishabh** [comment]
Hi @djmitche, I can take a look into this one!

**Comment by djmitche** [comment]
Sure!  Let me know if you need some pointers.

**Comment by rbrishabh** [comment]
Hi @djmitche! I spent some time with the issue, and the implementations of `AllPurgeRequests` in `clients/client-go/tcpurgecache/tcpurgecache.go` and `ListClients` in `clients/client-go/tcauth/tcauth.go` look really similar w.r.t to how the `continuationToken` is handled.

So, at the moment, I'm not 100% sure what the difference is!

For what it's worth, in `clients/client/src/apis.js`, inside the `listClients` api description, it does say: 
"It may also return a `continuationToken` even though there are no more\nresults."

https://github.com/taskcluster/taskcluster/blob/main/clients/client/src/apis.js#L27-L40

What do you think?

**Comment by djmitche** [comment]
The files you've linked to are in the automatically-generated _client_ library for talking to the services.  They look similar because they are generated by the same code :)

The difference is in the server implementation of those two methods:
https://github.com/taskcluster/taskcluster/blob/3380d73f2bdefb9a9cd3e00d2715466a983f5418/services/purge-cache/src/api.js#L67-L104
https://github.com/taskcluster/taskcluster/blob/3380d73f2bdefb9a9cd3e00d2715466a983f5418/services/auth/src/api.js#L158-L190

**Comment by rbrishabh** [comment]
ah! thanks for pointing that out! I'll take a look! :)
