### ISSUE TITLE
Unhandled issue when creating a GitHub check

### ISSUE THREAD

**Issue by jwhitlock** [taskcluster/taskcluster#3797]
https://sentry.prod.mozaws.net/operations/taskcluster-firefox-ci/issues/9746308/events/54504661/ shows one instance of this partial error:

```
error: duplicate key value violates unique constraint "github_checks_pkey"
DETAIL: Key (task_group_id, task_id)=(RpFZlBiZQ6ehpPvw15uU5A, DCmRhBn4SJ2SFAeKoZJiOA) already exists.
WHERE: SQL statement "insert into github_checks (task_group_id, task_id, check_s...
  ?, in null.<anonymous>
```

It is likely to be one of the two calls to [create_github_check](https://github.com/taskcluster/taskcluster/blob/63da02e46b7d49da394a3ff3f8e0477e8f3aa242/db/versions/0037.yml#L174-L183) in [taskcluster/services/github/src/handlers.js](https://github.com/taskcluster/taskcluster/blob/main/services/github/src/handlers.js).

**Comment by djmitche** [comment]
I wrote this in channel so I might as well put it here:

> The problem has occurred because we're using GitHub's Octokit plugins for rate-limiting, and it backs off much more aggressively than our custom-rolled GitHub access ever did, so it can take tens of seconds to make an API call.  And that means quick-running tasks can actually complete before they are marked as running, so the "mark as running" occurs after the "mark as complete", and a yellow dot results.
