### ISSUE TITLE
[azure provider] include failed SDK method in worker pool error log

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#3808]
There are errors that just say "Cannot parse the request" in the worker pool error log, with title "VM Creation Error".  That's not too helpful!

That title comes from a `catch` block in `services/worker-manager/src/providers/azure.js` that catches errors from a number of operations on IPs, NICs, and VMs.

It'd be nice if it was refactored so that there was some indication which of those failed.

**Comment by djmitche** [comment]
To get started here, get a development environment set up, and then have a look at the try/catch in `azure.js` that results in "VM Creation Error".  How could that be modified so that the error message indicated which part of the try block failed?

**Comment by SushantAA** [comment]
I want to work on this issue

**Comment by djmitche** [comment]
Awesome!  It's all yours!

**Comment by SushantAA** [comment]
I am a little bit confused about how what is causing an error in IPs ,NICs and VMs.

**Comment by SushantAA** [comment]
I am little bit confused about what is causing error in IPs, NICs and VMs.

**Comment by djmitche** [comment]
There are three calls to `this.provisionResources`, any of which could fail.  The idea of this issue is to make it clear in the error message *which* of those three calls failed.
