### ISSUE TITLE
web-server provides access to pulse messages in private deployments

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#3823]
As part of building a private deployment, we will want to prevent the web-server process from sharing pulse messages with the UI.

We use pulse messages in two ways:
 * pulse inspector (arbitrary messages)
 * to subscribe to task-group or task status updates

Let's tackle those separately.

**Comment by thakkarujas5** [comment]
will it be possible to provide an example on how to simulate this issue, so I could start debugging from that point.

**Comment by lotas** [comment]
> will it be possible to provide an example on how to simulate this issue, so I could start debugging from that point.

Idea is quite simple - you can check https://community-tc.services.mozilla.com/pulse-messages?bindings%5B0%5D%5Bexchange%5D=exchange%2Ftaskcluster-queue%2Fv1%2Ftask-running&bindings%5B0%5D%5Bpattern%5D=%23 page where you can subscribe to all pulse events even as unauthorized user.

UI is working with web-server service that doesn't currently check if user has access to those events or not

[Anonymous role](https://docs.taskcluster.net/docs/manual/deploying/anonymous-role#anonymous-role) tells what is public and what is not.

I think question here is do we want to introduce new scope for this or use the existing ones

**Comment by lotas** [comment]
@thakkarujas5  I have removed all anonymous role on our dev instance - feel free to test there as well if needed: https://dev.alpha.taskcluster-dev.net/
