### ISSUE TITLE
Without permissions, the Task Group view shows a JS error instead of a permissions error

### ISSUE THREAD

**Issue by ricky26** [taskcluster/taskcluster#3829]
**Describe the bug**
When the user does not have the `queue:list-task-group:` permission, a `Cannot read property 'status' of undefined` error shows instead of a relevant permissions error.

**To Reproduce**

1. Make sure the 'anonymous' roles does not contain 'queue:list-task-group:*'.
2. Create a new task.
3. Navigate to the task group.
4. Log out.
5. See error

**Expected behavior**
An error explaining which scopes are missing should be displayed.

**Taskcluster version**
v38.0.1

**Screenshots**
https://i.snipboard.io/jTYIgV.jpg

**Comment by helfi92** [comment]
@ricky26 How can I try to reproduce this error? Steps to reproduce would be appreciated.

**Comment by ricky26** [comment]
Erk, I wear I filled out the body text here... I even had a screenshot. Wonder where that all went.

**Comment by djmitche** [comment]
It looks like #3844 fixed this.  I can reproduce this in my dev environment, which does not have #3844 applied, but applying that patch locally (to web-server and ui) gives me a nice error regarding missing scopes.

I think I confused this bug with the other one that I accidentally closed.  Sorry!
