### ISSUE TITLE
Too hard to find the logs in the new UI

### ISSUE THREAD

**Issue by jgraham** [taskcluster/taskcluster#383]
When using taskcluster with GitHub the most common reason for people to be looking at a task is to understand why something failed. In time hopefully the checks api support allows us to upload a summary of the error and a direct link to the logs, but even so it seems like it should be obvious at a glance how to see the output from a task. At present it isn't; the log link is right at the bottom on the right hand side and is no more prominement than information that is of little use to anyone other than taskcluster developers (e.g. anything about the worker id/type/group/provisioner/etc.). 

For users who aren't taskcluster developers, the most important pieces of information are task name/status/live log/artifacts, all for the latest run only. It would be great if they were correspondingly more prominent in the UI.

**Comment by helfi92** [comment]
Agreed, we should find a way to make the live log more prominent. Thank you for bringing that up!

**Comment by helfi92** [comment]
@jgraham Is it better now?

**Comment by helfi92** [comment]
Closing as resolved.
