### ISSUE TITLE
Task using indexed-image fails: "could not find task associated with namespace"

### ISSUE THREAD

**Issue by jschwartzentruber** [taskcluster/taskcluster#3843]
**Describe the bug**

A task created using an indexed-image fails with:

    [taskcluster:error] Pulling docker image has failed.
    [taskcluster:error] Error: Could not find a task associated with "project.fuzzing.config.master" namespace. Supplied credentials do not satisfy authorizedScopes; credentials have scopes:
    ```
    assume:worker-type:proj-fuzzing/linux-pool1
    assume:worker-pool:proj-fuzzing/linux-pool1
    assume:worker-id:us-east1/7625143841217902745
    queue:worker-id:us-east1/7625143841217902745
    secrets:get:worker-type:proj-fuzzing/linux-pool1
    secrets:get:worker-pool:proj-fuzzing/linux-pool1
    queue:claim-work:proj-fuzzing/linux-pool1
    worker-manager:remove-worker:proj-fuzzing/linux-pool1/us-east1/7625143841217902745
    worker-manager:reregister-worker:proj-fuzzing/linux-pool1/us-east1/7625143841217902745
    ```
    authorizedScopes are:
    ```
    docker-worker:capability:device:loopbackAudio
    docker-worker:capability:device:hostSharedMemory
    secrets:get:project/fuzzing/credstash-aws-auth
    queue:scheduler-id:-
    queue:cancel-task:-/*
    queue:create-task:highest:proj-fuzzing/linux-pool1
    secrets:get:project/fuzzing/decision
    ```
    ---
    * method:     findTask
    * errorCode:  AuthenticationFailed
    * statusCode: 401
    * time:       2020-11-03T12:02:23.268Z

**To Reproduce**

The tasks are created by a scheduled hook: https://community-tc.services.mozilla.com/hooks/project-fuzzing/linux-pool1

**Expected behavior**

Tasks should be able to find the public docker image specified. The namespace called out is indexed here: https://community-tc.services.mozilla.com/tasks/index/project.fuzzing.config/master and the image is accessible from the UI.

**Taskcluster version**
38.0.1
worker version 30.1.1

**Comment by imbstack** [comment]
Investigating this we found that this will be a somewhat larger fix than initially expected. With that in mind we have rolled back community deployment to the previous version. Will update this bug more once we have a fix.

**Comment by jschwartzentruber** [comment]
@imbstack This issue started again ~24h ago. Same hook, same error.

**Comment by jschwartzentruber** [comment]
Updating the image used by these worker pools to `projects/taskcluster-imaging/global/images/docker-worker-community-gcp-googlecompute-2020-11-06t20-07-40z` resolved this.
