### ISSUE TITLE
web-server should check session when fetching

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#3868]
https://github.com/taskcluster/taskcluster/blob/12f59699fa1efeea1136decb98b1eca49bcd19bd/services/web-server/src/login/PostgresSessionStore.js#L48-L58

This fetches the session by hashedSessionId, but does not verify that the sessionId actually matches the row.  Given a hash collision (unlikely), this could be used to steal sessions given access to the DB.  So it's not a huge deal.  But we should fix it.

**Comment by rbrishabh** [comment]
Hi @djmitche ! How are you?
I would like to work on this! 
Can you give a little more context of what you mean by "sessionId actually matches the row?"

That would be helpful! Thanks

**Comment by djmitche** [comment]
Hi Rishabh!

Here's the context: users have a sessionId that identifies them to the web-server service, and we need to have a way to store sessions between requests to the service.  However, we  want to store sessionIds in a way where, if someone had access to the DB, they not figure out any user's sessionId.  So just storing them in a `session_id` column won't work.

We have support for encrypted columns, which can only be decrypted with a key that is never on the DB server.  So we can store the session ID in such a column.  You can see the schema [here](https://github.com/taskcluster/taskcluster/blob/main/db/schema.md#sessions).

However, the encrypted form of an encrypted column is different every time it's written, so it doesn't make a good DB table key.  So, we added another column, `hashed_session_id`, that is a stable hash of the session ID.

The code snippet above is given a session ID (unencrypted) and is responsible for finding the session.  The bug is that it never looks at encrypted_session_id -- it just assumes that if `hash(sessionId)` matches a row in the table, then that row is the right session.

The fix is, after finding that row, to [decrypt](https://github.com/taskcluster/taskcluster/blob/main/libraries/postgres/README.md#encryption) the `encrypted_session_id` column and check that the decrypted value matches `sessionId`.

**Comment by rbrishabh** [comment]
I think I got it! I'll give it a go.
Thanks for the explanation :)

**Comment by djmitche** [comment]
@rbrishabh did you get a chance to work on this?  Would you like to continue?

**Comment by rbrishabh** [comment]
oh no! I totally forgot about this! Sorry!
I am currently out of my city and would be back on the 20th of this month. If it can wait till then, I'd like to work on this.
If it's urgent, please take it up!
thank you! @djmitche

**Comment by djmitche** [comment]
No problem.  We'll see if we get to it by the 20th :)

**Comment by djmitche** [comment]
Hi Rishabh -- we'll be away until early January, but you are still welcome to work on this..
