### ISSUE TITLE
Worker Types view displays an error if no sortBy is specified

### ISSUE THREAD

**Issue by ricky26** [taskcluster/taskcluster#3873]
**Describe the bug**
The worker types view (`/provisioners/<provisioner-id>`), displays an error `Cannot read property 'replace' of null` when navigated to. This error can be avoided by adding `?sortBy=Hams` to the end of the URL.

**To Reproduce**

1. Click Workers on the navigation bar.
2. Click a provisioner type.
3. Notice error.

**Expected behavior**
Worker types should be displayed correctly.

**Taskcluster version**
v38.0.4

**Additional context**
It looks like this might be to do with how `sortBy` is defaulted in the WorkerTypesTable component.

**Comment by djmitche** [comment]
Possibly related to #3837?  Or at least fixed by it?

**Comment by ricky26** [comment]
I'm not 100% sure but I don't think so. I tried to follow the call-stack along and it looks like it's being passed as `null` to `createSortedWorkerTypesConnection`, which in turn calls `camelCase`, (which is where the `.replace()` error originates from).

**Comment by djmitche** [comment]
ah, ok, the other bizarrely-breaking change :(
