### ISSUE TITLE
log viewer URLs are huge and temporary

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#3878]
Observe:

https://stage.taskcluster.nonprod.cloudops.mozgcp.net/tasks/IN-ZKBSzRxevRR_9xolC9Q/runs/0/logs/https%3A%2F%2Fstage.taskcluster.nonprod.cloudops.mozgcp.net%2Fapi%2Fqueue%2Fv1%2Ftask%2FIN-ZKBSzRxevRR_9xolC9Q%2Fruns%2F0%2Fartifacts%2Fpublic%252Flogs%252Flive.log%3Fbewit%3DbW96aWxsYS1hdXRoMC9hZHxNb3ppbGxhLUxEQVB8ZG1pdGNoZWxsXDE2MDQ5NDQyNjdceHJZUFBJVzg4UnFLYVgzbkd3Y0F6dEsyNEM2ZkZjblkycXNadTdpRVhLQT1cZXlKalpYSjBhV1pwWTJGMFpTSTZleUoyWlhKemFXOXVJam94TENKelkyOXdaWE1pT2xzaVlYTnpkVzFsT20xdmVtbHNiR0V0WjNKdmRYQTZSR1YyVTJWeWRtbGpaWE5YYVd0cElpd2lZWE56ZFcxbE9tMXZlbWxzYkdFdFozSnZkWEE2UjNKaGNHaHpRV1J0YVc0aUxDSmhjM04xYldVNmJXOTZhV3hzWVMxbmNtOTFjRHBKYm5SeVlXNWxkRmRwYTJraUxDSmhjM04xYldVNmJXOTZhV3hzWVMxbmNtOTFjRHBTWld4RmJtZFhhV3RwSWl3aVlYTnpkVzFsT20xdmVtbHNiR0V0WjNKdmRYQTZVM1JoZEhORVlYTm9ZbTloY21RaUxDSmhjM04xYldVNmJXOTZhV3hzWVMxbmNtOTFjRHBUZVhOQlpHMXBibGRwYTJraUxDSmhjM04xYldVNmJXOTZhV3hzWVMxbmNtOTFjRHBoWTNScGRtVmZjMk50WDJ4bGRtVnNYekVpTENKaGMzTjFiV1U2Ylc5NmFXeHNZUzFuY205MWNEcGhZM1JwZG1WZmMyTnRYMnhsZG1Wc1h6SWlMQ0poYzNOMWJXVTZiVzk2YVd4c1lTMW5jbTkxY0RwaFkzUnBkbVZmYzJOdFgyeGxkbVZzWHpNaUxDSmhjM04xYldVNmJXOTZhV3hzWVMxbmNtOTFjRHBoYkd4ZmJHUmhjRjkxYzJWeWN5SXNJbUZ6YzNWdFpUcHRiM3BwYkd4aExXZHliM1Z3T21Gc2JGOXpZMjFmYkdWMlpXeGZNU0lzSW1GemMzVnRaVHB0YjNwcGJHeGhMV2R5YjNWd09tRnNiRjl6WTIxZmJHVjJaV3hmTWlJc0ltRnpjM1Z0WlRwdGIzcHBiR3hoTFdkeWIzVndPbUZzYkY5elkyMWZiR1YyWld4Zk15SXNJbUZ6YzNWdFpUcHRiM3BwYkd4aExXZHliM1Z3T21GMFpXRnRJaXdpWVhOemRXMWxPbTF2ZW1sc2JHRXRaM0p2ZFhBNllYZHpYek15TURRMk5ESXdOVE00Tmw5eVpXRmtYMjl1YkhraUxDSmhjM04xYldVNmJXOTZhV3hzWVMxbmNtOTFjRHBpZFdsc1pIUmxZVzBpTENKaGMzTjFiV1U2Ylc5NmFXeHNZUzFuY205MWNEcGpiRzkxWkdobFlXeDBhQzF6ZEdGdVpHRnlaQ0lzSW1GemMzVnRaVHB0YjNwcGJHeGhMV2R5YjNWd09tVm5aVzVqYVdGZmRYTWlMQ0poYzNOMWJXVTZiVzk2YVd4c1lTMW5jbTkxY0RwcGJuWmxiblJ2Y25raUxDSmhjM04xYldVNmJXOTZhV3hzWVMxbmNtOTFjRHBwYm5abGJuUnZjbmxmWW5WcGJHUWlMQ0poYzNOMWJXVTZiVzk2YVd4c1lTMW5jbTkxY0RwdGNIUjJjRzRpTENKaGMzTjFiV1U2Ylc5NmFXeHNZUzFuY205MWNEcHVZV2RwYjNOaFpHMXBiaUlzSW1GemMzVnRaVHB0YjNwcGJHeGhMV2R5YjNWd09tOW1abWxqWlY5eVpXMXZkR1VpTENKaGMzTjFiV1U2Ylc5NmFXeHNZUzFuY205MWNEcHdhRzl1WldKdmIydGZZV05qWlhOeklpd2lZWE56ZFcxbE9tMXZlbWxzYkdFdFozSnZkWEE2YzNCbFkyOXdjeUlzSW1GemMzVnRaVHB0YjNwcGJHeGhMV2R5YjNWd09uUmhZbXhsWVhWZmRYTmxjbk1pTENKaGMzTjFiV1U2Ylc5NmFXeHNZUzFuY205MWNEcDBaV0Z0WDIxdlkyOGlMQ0poYzNOMWJXVTZiVzk2YVd4c1lTMW5jbTkxY0RwMFpXRnRYM1JoYzJ0amJIVnpkR1Z5SWl3aVlYTnpkVzFsT20xdmVtbHNiR0V0WjNKdmRYQTZkRzl2YkhSdmIyeGxaR2wwYjNJaUxDSmhjM04xYldVNmJXOTZhV3hzWVMxbmNtOTFjRHAyY0c1ZllXUnRhVzRpTENKaGMzTjFiV1U2Ylc5NmFXeHNZUzFuY205MWNEcDJjRzVmWTI5eWNDSXNJbUZ6YzNWdFpUcHRiM3BwYkd4aExXZHliM1Z3T25ad2JsOWtaV1poZFd4MElpd2lZWE56ZFcxbE9tMXZlbWxzYkdFdFozSnZkWEE2ZG5CdVgyZHBkR2xmZEdOZmMyVmpjbVYwYzE5eWR5SXNJbUZ6YzNWdFpUcHRiM3BwYkd4aExXZHliM1Z3T25ad2JsOXVZV2RwYjNOZmQyVmlJaXdpWVhOemRXMWxPbTF2ZW1sc2JHRXRaM0p2ZFhBNmRuQnVYM0psYkdWdVp5SXNJbUZ6YzNWdFpUcHRiM3BwYkd4cFlXNXpMV2R5YjNWd09taGxjbTlyZFMxdFpXMWlaWEp6SWl3aVlYTnpkVzFsT214dloybHVMV2xrWlc1MGFYUjVPbTF2ZW1sc2JHRXRZWFYwYURBdllXUjhUVzk2YVd4c1lTMU1SRUZRZkdSdGFYUmphR1ZzYkNKZExDSnpkR0Z5ZENJNk1UWXdORGswTWpFd016TTJOQ3dpWlhod2FYSjVJam94TmpBME9UUXpPVEF6TXpZMExDSnpaV1ZrSWpvaVVsZGxMWFp6TkVkU2RHMXJjRkZJWVUxZk1VRmtaMFZPYWxOamVWOWpVVUpwWW5WV2FYcDVPVTV4YmtFaUxDSnphV2R1WVhSMWNtVWlPaUp0TDFKSFlrMDVPRmxwVjNWTksxUjNPVWRSZVZWbVUxTk9XbFZ6UjFSbU5XRjJhVk5FYzBVMllsaEJQU0lzSW1semMzVmxjaUk2SW5OMFlYUnBZeTkwWVhOclkyeDFjM1JsY2k5M1pXSXRjMlZ5ZG1WeUluMTk

The problem is that we're passing URLs via react-router, and those URLs include a bewit.  The bewit is only valid for a short length of time, so even if someone did paste this link into a bug or issue or whatever, it would be useless soon after.

From first principles, the information required for a log is
 * taskId
 * runId
 * artifact name

So, let's change things around such that only those three parameters appear in the URL.

That will require a change to how the logs are fetched.  That can either be via a new GraphQL interface, or by generating the signed URL within the UI code using taskcluster-client-web.

**Comment by helfi92** [comment]
We would no longer use a bewit anymore?

**Comment by djmitche** [comment]
Behind the scenes, we might continue to use a bewit, but not include it in a place where users can copy/paste it.

**Comment by helfi92** [comment]
By using it in a header instead?

**Comment by djmitche** [comment]
The invariant is that the frontend needs to be able to use `fetch` on a `getArtifact` URL that will redirect to the log artifact.  The easiest way to do that is to have a bewit in the URL, but it's also possible to attach an `Authorization` header with a Hawk signature.

The part where there's some flexibility is, where does that URL come from.  Right now, web-server creates the URL and puts it in a GraphQL response on the task view page, which embeds it in a link to the log-view page, which decodes the URL and uses it in a `fetch` call.  That has a bunch of downsides (huge URLs in the address bar, react-router's urlencoding bug, and limited validity time of the bewit).

So, it would make sense to
* pass the URL from web-server to the UI in a way that doesn't appear in the address bar
* pass the URL in a way that isn't parsed by react-router
* generate the URL closer to the time of its use (avoiding the time validity time)

**Comment by SimonSapin** [comment]
> From first principles, the information required for a log is
> 
>     * taskId
>     * runId
>     * artifact name
> So, let's change things around such that only those three parameters appear in the URL.

That would be ideal. Even before the `bewit` was included, the log viewer URL unnecessarily included a full other URL incuding the deployment root URL: https://github.com/taskcluster/taskcluster/issues/1904

**Comment by djmitche** [comment]
## Current Situation

The web-server serves up artifacts with a `url` property containing a signed
URL to fetch the artifact, and an isPublic property indicating
whether it is public.

Issues:
* The signed URL is huge
* The signed URL is time-limited
* The isPublic property is based on the artifact name and no longer accurate

In the UI, artifacts appear a few places, and each handles them a bit differently.
* index viewer
* interactive connect
* task runs pane

Issues:
* Index viewer
  * looks for `public/` in the name to see if an artifact is public (no longer accurate)
  * generates unsigned URLs for "public" artifacts
* Interactive connect
  * Uses URLs from the web-server process
* Task runs pane
  * full URLs are embedded in the routes
    * they're huge
    * they're time-limited
    * they can be copy/pasted
    * react-router doesn't handle them well

## Plan

Web-server will no longer provide the `url` or `isPublic` properties, leaving
just `name` and the parent task's `taskId` and (when not getting latest)
`runId`.

The UI will have utility functions that sign artifact URLs at the time of use
(that is, just before fetching them).  Links will have their URLs generated
just before they are loaded.

This will require using React context to make the AuthController available to subcomponents, as the user's credentials will be required to sign the URLs.  If the user is not signed in, we will create unsigned URLs.

**Comment by djmitche** [comment]
(I'll get rid of `isLog` at the same time -- the web-server has no business deciding that)

**Comment by djmitche** [comment]
WIP - https://github.com/taskcluster/taskcluster/compare/main...djmitche:issue3878

**Comment by djmitche** [comment]
I didn't address the `artifacts.json` fetching on the server side.  That doesn't suffer from the issues I'm trying to solve here.
