### ISSUE TITLE
Determine required cost/usage reporting for object service

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#3896]

**Comment by djmitche** [comment]
We have historically done a poor job of providing data on costs associated with Taskcluster. For the object service, let's get out in front of that.

At completion of this epic, we have a document describing the information that deployers and administrators will get regarding usage and costs associated with the object service. This should include precise definitions of that information (what is and is not included) and a proposal for how to calculate it as part of the operation of the object service across storage backends. #39 covers implementation.

**Comment by imbstack** [comment]
@djmitche and I just had a nice chat about this. Takeaways are as follows:

1. It is probably going to be hard to generically get per-object or pre-project cost data in a similar way in every cloud so let's just avoid attacking the issue head-on.
2. Instead admins can check their costs using whatever dashboards the clouds provide themselves and taskcluster will only report things like "X object is responsible for N bytes of storage and M bytes of transfer". This will allow an admin to dig down into what is responsible for costs when needed.
3. With this in mind there should be a column on the object row for `size`, and `downloads` which store the size of the object in bytes and the number of times it has been downloaded respectively. In addition there should be a to-be-named column that contains arbitrary json that a backend can store there if it has more data it thinks would be useful but that isn't applicable to all backends.
4. We should avoid making an api that exposes this information at first and instead document some useful queries an admin can run across the objects table to determine things like "what are my most expensive objects", "which projects are responsible for how many bytes in each cloud", etc.
5. probably something else I am forgetting?
