### ISSUE TITLE
Release events don't work?

### ISSUE THREAD

**Issue by mozbhearsum** [taskcluster/taskcluster#39]
I started trying to make use of release events today, and as far as I can tell, events are never fired for them. For example, I was watching the "exchange/taskcluster-github/v1/release" exchange with the Pulse Inspector while I created both tags and full fledged releases on https://github.com/testbhearsum/balrog/releases, but no events showed up. I also have two Tasks that should be created when a Release event is fired that have routes attached to them, and neither one of them showed up in the Index Browser.

**Comment by ccooper** [comment]
@mozbhearsum Is this fixed for you now?

**Comment by mozbhearsum** [comment]
It is!
