### ISSUE TITLE
Azure worker-manager: Add support for ECC / ECDCA certificates

### ISSUE THREAD

**Issue by jwhitlock** [taskcluster/taskcluster#3923]
For Azure worker registration, support an [attested data](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service#attested-data) [PKCS#7](https://en.wikipedia.org/wiki/PKCS_7) message that has been signed with an [Elliptic Curve Digital Signature Algorithm](https://en.wikipedia.org/wiki/Elliptic_Curve_Digital_Signature_Algorithm) that uses [Elliptic Curve Cryptography](https://en.wikipedia.org/wiki/Elliptic_Curve_Digital_Signature_Algorithm), or chains up to an ECC root CA.

## Background
 
Azure [has announced](https://docs.microsoft.com/en-us/azure/security/fundamentals/tls-certificate-changes) that they intend to add 5 more root certificates by February 2021. One of these, "Microsoft ECC Root Certificate Authority 2017", uses ECC. It is unclear which root certificates will be used when signing the attested data message, used as an identify proof for worker registration.

We use [node-forge](https://github.com/digitalbazaar/forge) to read the attested data message, the signing and intermediate certificates, and to verify the certificate chain. `node-forge` does not support ECC (https://github.com/digitalbazaar/forge/issues/116, filed 2014). It also doesn't natively support verification of PKCS#7 signatures; we use node's [crypto library](https://nodejs.org/api/crypto.html) to verify it.

## Options

After a few hours of research, there are a few options:

* We could add ECC support to ``node-forge``, and improve the PKCS#7 implementation.
* node.js has cryptography support, including ECC, in `crypto`, and certificate support in the [TLS](https://nodejs.org/api/tls.html) library. However, it doesn't have a PKCS#7 implementation, and the API doesn't see suited for our needs.
* [PKI.js](https://github.com/PeculiarVentures/PKI.js) is a pure JS library that support ECDSA, as well as some certificate features that are not fully implemented in `node-forge`. It does not seem to support PKCS#7 directly, but does have an [example](https://github.com/PeculiarVentures/PKI.js/blob/master/examples/P7BSimpleExample/es6.js) of creating the P7B sub-format.

One of the difficulties in the crypto code is testing. It is challenging to create the fixtures needed to test different validation scenarios. The tests also rely on `node-forge` for loading fixtures and manipulating the trusted certificate store. Replacing the library may first require removing `node-forge` from tests, and adding test-specific APIs to `AzureProvider` to avoid directly manipulating the trusted certificate store. A good replacement library needs to support testing.

**Comment by jwhitlock** [comment]
The Azure team has [clarified the cert changes for the Azure Instance Metadata Service](https://docs.microsoft.com/en-us/answers/questions/172717/action-required-for-attested-data-tls-with-azure-i.html). The new issuing certs will be "Microsoft RSA TLS CA 01" and "Microsoft RSA TLS CA 02" (both TLS not ECC), issued by the same "Baltimore CyberTrust Root" cert.

Supporting ECC certs is not a priority at this time, and the library support may be available when and if it is needed.

**Comment by djmitche** [comment]
Per the December update here, I think we can close this.
