### ISSUE TITLE
Remove or repurpose legacy Microsoft intermediate certificates when revoked

### ISSUE THREAD

**Issue by jwhitlock** [taskcluster/taskcluster#3925]
Remove the `microsoft_it_tls_ca_#.pem` certificates from the repo when they are revoked, if not sooner.

The Azure worker-manager uses the [attested data](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service#attested-data) message as a proof-of-identity when registering a newly provisioned worker. As of November 4, 2020, the signing certificate for this message is issued by one of four "Micosoft IT TLS CA" certificates listed [here](https://www.microsoft.com/pki/mscorp/cps/default.htm). They are added to a trusted certificate list when worker-manager starts up, so no network connection is needed to confirm the messages.

Azure [plans](https://docs.microsoft.com/en-us/azure/security/fundamentals/tls-certificate-changes) to migrate from the Microsoft IT TLS certificates to new certificates, issued by 6 total root CAs. It plans to revoke the Microsoft IT TLS certificates on [February 15, 2021](https://docs.microsoft.com/en-us/azure/security/fundamentals/tls-certificate-changes).

When the certificates are revoked, they are no longer needed and can be removed from the repo.

When a new certificate is seen, it will be downloaded, verified, and added to the trusted store. This means the legacy Microsoft certificates could be removed sooner, and instead dynamically downloaded at worker registration.

These certificates are also used in tests, and used to sign test fixtures. It may be non-trivial to completely remove them. It may instead be useful to move them into the test fixtures folder and continue to use them, at least until messages signed via the new certificates are available. 

The certificates are set to expire in May 2024.

**Comment by djmitche** [comment]
I suspect this will fix, or is related to fixing, #4744.
