### ISSUE TITLE
No task-group-resolved pulse message for mozilla-central groups

### ISSUE THREAD

**Issue by marco-c** [taskcluster/taskcluster#3926]
We have a pulse listener running for task-group-resolved messages, triggering a hook in specific conditions (if the group is from try or m-c and has at least one ccov job in it).

Since ~ a week ago, I'm only receiving task-group-resolved messages for try, and nothing for m-c.

The last message I received was for push e4aeb40526cc5ba0717a0c1e835e1f88fe5d8a01, task group DxJdsokzRCq-tjNavbbouQ.

**Comment by djmitche** [comment]
I'm not sure what's up with this.  I remember looking into it and not seeing anything specific in the timing of the change, and seeing at least some task-group-resolved messages.  Let's re-open if still occurring.
