### ISSUE TITLE
a .taskcluster.yml in a PR without one in the master branch is skipped

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#3927]
copied from https://bugzilla.mozilla.org/show_bug.cgi?id=1564512
---
https://github.com/taskcluster/taskcluster/blob/8bf75678626567ec2fdae3889dff2f6d86235958/services/github/src/handlers.js#L603-L605

This means experimenting with `.taskcluster.yml` in a PR silently does nothing.

Could we assume the most restrictive policy (collaborators), instead?

**Comment by mraethel** [comment]
Hi, could you please assign this issue to me?

**Comment by djmitche** [comment]
Sure!
