### ISSUE TITLE
[UI] links are hard to see when text is selected (dark theme only)

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#394]
STR:

1. Navigate to https://taskcluster-web.netlify.com/docs
2. Select the text: "Follow the tutorial to learn about Taskcluster, focusing on the parts most relevant to you."

**Expected**: The links are visible.

**Actual**: The links are hard to see in the dark theme.

![Screen Shot 2019-03-12 at 9 24 19 AM](https://user-images.githubusercontent.com/3766511/54203533-d0d00900-44a8-11e9-920b-e082c3ba34e4.png)

**Comment by Anubhavshakya** [comment]
@helfi92 Can I work on this...

**Comment by helfi92** [comment]
Go for it.

**Comment by helfi92** [comment]
I was thinking maybe we could remove the blue color and simply use a dotted bottom line. Something like:

![Screen Shot 2019-03-12 at 6 10 18 PM](https://user-images.githubusercontent.com/3766511/54239668-3dbbc100-44f2-11e9-8a6a-87540a454cc2.png)

```css
text-decoration: none;
border-bottom: 1px dotted;
```

**Comment by Anubhavshakya** [comment]
Yes, We can remove the blue colour but without blue colour, the UI is not looking good. So I was thinking that change the colour of **selection** and **reduce the opacity**
![github](https://user-images.githubusercontent.com/38704248/54276482-71125480-45b3-11e9-9a7f-5f71ed00f4a9.png)

**Comment by helfi92** [comment]
In order to keep the blue color, we could possibly do something like:

![Screen Shot 2019-03-13 at 7 55 35 AM](https://user-images.githubusercontent.com/3766511/54277222-a5f7ba80-4565-11e9-908b-3eee40bf8a90.png)

**Comment by helfi92** [comment]
Feel free to create a PR with the change :)

**Comment by Anubhavshakya** [comment]
@helfi92 Please check #408

**Comment by helfi92** [comment]
Resolved in  https://github.com/taskcluster/taskcluster/pull/410 🎉
