### ISSUE TITLE
Choose new name for object service "full download"

### ISSUE THREAD

**Issue by imbstack** [taskcluster/taskcluster#3940]
As it stands we're going to roughly have a `download` method and a `simpleDownload` method which correspond to an endpoint that fetches a bunch of data about an object and one that simple does a download.

Let's change these names to `?????` and `download` to correspond to what they do.

One note @djmitche brings up is that the `????` actually might take some action on behalf of the user (copying an object around in the cloud I assume) so just a simple `fetchDetails` doesn't cover everything.

This bug is for bikeshedding about this to our heart's content.

**Comment by djmitche** [comment]
(note, so we are clear what we're talking about, that the current name for it is `downloadObject`)
https://github.com/taskcluster/taskcluster/blob/96379ee9b9e5417d37ca05cbea7bc7ca17c08808/services/object/src/api.js#L36-L39

**Comment by djmitche** [comment]
@imbstack where did this conversation end up?

**Comment by imbstack** [comment]
Still where we left it afaik. Happy to choose any new name personally.

**Comment by imbstack** [comment]
How about we call `simpleDownload` `download` and we call `downloadObject` `fetchObjectMetadata` just to get the ball rolling here. That's roughly what we said at the meeting a few weeks back iirc

**Comment by djmitche** [comment]
Sounds good, time for a PR :)
