### ISSUE TITLE
Make reclaim time configurable per Taskcluster instance

### ISSUE THREAD

**Issue by ricky26** [taskcluster/taskcluster#3981]
At the moment, reclaim time is fixed as 20 minutes, if it was exposed as config, smaller instances could use a much smaller reclaim time to improve the responsiveness of cancellations (and thus save some compute resource).

**Comment by ricky26** [comment]
cc @djmitche, if I find time, I'll try and get a PR in for this, otherwise adding 'good-first-bug' would be cool. :smile:

**Comment by djmitche** [comment]
Sounds good.  I think this involves:
 * adding the config parameter to the queue (`services/queue/config.yml`), defaulting to 20 minutes
 * using that config parameter in the queue
 * running `yarn generate` to update all of the kubernetes stuff
 * updating docs that mention an explicit 20 minutes (I think some of the schemas mention this value)
 * adding deployment docs for this parameter

**Comment by imbstack** [comment]
We should definitely do this. I think the 20 minute thing was based on some mental math from azure tables days. We should make this much shorter everywhere and we may as well start by making it configurable.

**Comment by djmitche** [comment]
> adding the config parameter to the queue (services/queue/config.yml), defaulting to 20 minutes

This exists:
```
    # Number of seconds before the claim to a run expires
    claimTimeout:                 1200
```
