### ISSUE TITLE
Allow "approval" of a push by collaborators

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#40]
From https://github.com/taskcluster/taskcluster-rfcs/issues/95

The idea would be that someone on a whitelist (configurable in the defeault-branch `.taskcluster.yml`) can write something specific in a comment like `@taskcluster: please run` and the push would be re-run as if it had been allowed to begin with.

The downside is that this requires either caching the Github PR webhook payload, or re-constructing it from the comment webhook payload.  With JSON-e, we will be exposing payloads to the users directly, so re-constructing is not a great option as it would be constantly out of date.

**Comment by owlishDeveloper** [comment]
Currently the build can be triggered in those cases if one of the core maintainers closes and reopens the PR.

**Comment by escapewindow** [comment]
@sladyn98 this is relevant.

**Comment by sladyn98** [comment]
@escapewindow Thanks

I did a bit of research on how prow bot for kubernetes does it they use a GH Cache that caches responses from github. We could lookout for the comment in the PR comments where taskcluster is tagged and then use the cache to validate the request and trigger a run based on the comment

```
ghCache is an HTTP cache optimized for caching responses from the GitHub API (https://api.github.com). Specifically, it has the following non-standard caching behavior:

Every cache hit is revalidated with a conditional HTTP request to GitHub regardless of cache entry freshness (TTL). The 'Cache-Control' header is ignored and overwritten to achieve this.
Concurrent requests for the same resource are coalesced and share a single request/response from GitHub instead of each request resulting in a corresponding upstream request and response.
```

**Comment by djmitche** [comment]
GitHub's rate limiting *has* been a problem for us in the past, and ghCache might be a good fix for that -- but let's see if we have issues with rate limits before we start solving those issues.  Please mention that in the RFC, though.

**Comment by sladyn98** [comment]
@djmitche yeah that can be worried about later. Any draft PR steps I can take for this RFC so we make progress  ?

**Comment by djmitche** [comment]
If you'd like to start implementing what seems to be the consensus in the RFC, that's fine.  I suspect #3985 will generate a lot of conflicts, though, so it might be best to start with that one first.

**Comment by lotas** [comment]
I believe we should close this, since https://github.com/taskcluster/taskcluster/issues/5073 was implemented and allows listening for the `issue_comment` events to react to `/taskcluster cmd` comments by collaborators.
I'll close it, please reopen if it was meant to be something else :)
