### ISSUE TITLE
Upgrade UI to Webpack 5 when Neutrino supports it

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#4001]
https://github.com/neutrinojs/neutrino/issues/1624

(or stop using Neutrino, as it seems to add more complexity than it solves for an app of this size)

**Comment by jwhitlock** [comment]
karma-webpack 4.0.2 supports webpack 4, but [karma-webpack 5.0.0](https://github.com/taskcluster/taskcluster/pull/4352) requires webpack v5. 

karma-webpack 4.0.2 uses a deprecated feature of karma (``customFileHandlers``), which will be removed in Karma 7. There were 7 months between Karma 5 and 6, so we may need to make this upgrade this year.

**Comment by lotas** [comment]
I will close this one in favor of #5265
