### ISSUE TITLE
allow to fire hook for tasks whose owner is not in email format

### ISSUE THREAD

**Issue by Archaeopteryx** [taskcluster/taskcluster#4032]
**Describe the bug**
When the hooks which set up the decision task don't fire, the hooks might be initiated again later with the `fxci replay-hg-push` [command](https://hg.mozilla.org/ci/ci-admin/file/tip/src/fxci/hg_pushes.py). Mozilla's [Try](https://treeherder.mozilla.org/jobs?repo=try&group_state=expanded&resultStatus=testfailed%2Cbusted%2Cexception%2Cretry%2Cusercancel%2Crunnable) repository has many pushes from automation by the user `reviewbot`. Attempts to fire the hook again with `fxci replay-hg-push try revision12345678` fail with:
```
Could not get create hg-push task: data.payload.data.pushlog_pushes[0].user should match format "email"
```

**To Reproduce**

0. Run: `export TASKCLUSTER_ROOT_URL=https://firefox-ci-tc.services.mozilla.com`
1. `taskcluster signin`
2. Install [ci-admin](https://hg.mozilla.org/ci/ci-admin/)
3. Run `fxci replay-hg-push try 4aaf76a3b2c00018e6d82998dc0db0c6c1595637
`

**Expected behavior**
A successful rerun will return a task url like https://firefox-ci-tc.services.mozilla.com/tasks/GuDpSQsJQVeQcoQQRAH7HQ

**Taskcluster version**
39.0

**Comment by djmitche** [comment]
I think that's a bug in the replay-hg-push script -- it should be replaying the original push just as it occurred.

That said, the schema that's requiring the email format is also generated by ci-admin, so if the format really isn't critical, then that schema could be changed.

Either way, that would require a bugzilla bug, I think.

**Comment by Archaeopteryx** [comment]
This is being tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1695175
