### ISSUE TITLE
[UI] docs logs deep linking not working

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#405]
STR:

1. Navigate to https://taskcluster-web.netlify.com/docs/reference/platform/auth/logs#monitor.count (notice the `#monitor.count` at the end of the url)

**Expected**: The `monitor.count` panel is expanded
**Actual**: The `monitor.count` panel is not expanded

**Comment by ziyadElon** [comment]
Hi @helfi92 
The attached url directs to a 404.
Could you please look into this?

**Comment by helfi92** [comment]
Sorry about that. It should work now.

**Comment by RehabHussein** [comment]
@helfi92 Hi Hassan, I'm new to open source contribution - would like to get started on this. Is it OK?

**Comment by helfi92** [comment]
Go for it. I sent you an invitation via email. Let me know once your accept it so I can assign the issue to you.

**Comment by RehabHussein** [comment]
@helfi92 Perfect ! 
I accepted the invitation. Thank you !

**Comment by helfi92** [comment]
How is it going Rehab? Let me know if you had questions.

**Comment by helfi92** [comment]
I can take care of it this time, np. If you're still interested in another problem, let me know and I can assign it to you.

**Comment by RehabHussein** [comment]
@helfi92 I was just stuck in some issues deploying the app :( 
Sorry for being late ! 
Sure I am still interested in participating in task cluster, will find another suitable issue and ping you :)
Thanks Hassan for your understanding !
