### ISSUE TITLE
The live log from generic-worker is not viewable after the task ends without assume:anonymous

### ISSUE THREAD

**Issue by ricky26** [taskcluster/taskcluster#4050]
**Describe the bug**
After a generic-worker task completes on a Taskcluster instance with an empty anonymous role, the live log link no longer works, instead returning 403.

**To Reproduce**

1. Remove all scopes from the anonymous role.
2. Run a task with generic-worker.
3. Wait for the task to complete.
4. Try to view the live log.
5. See error

**Expected behavior**
The live log link should redirect to `public/live_backing.log` after task completion.

**Taskcluster version**
v39.0.0

**Platform (please complete the following information):**

 - OS: [e.g. windows]
 - Browser if applicable [e.g. firefox, safari]
 - Version if applicable [e.g. 57]

**Additional context**
The UI redirects to:
- https://taskcluster.my.org/api/queue/v1/task/Kko3Y4iMSump_cB7SLdDgA/runs/0/artifacts/public%2Flogs%2Flive.log?bewit=BEWIT
- https://taskcluster.my.org/api/queue/v1/task/Kko3Y4iMSump_cB7SLdDgA/runs/0/artifacts/public%2Flogs%2Flive_backing.log

The second redirect has no credentials (no headers are passed to redirects and there is no bewit), so unless `queue:get-artifact:public/live_backing.log` is fulfilled, the redirect fails.

Example error payload from navigating to the artefact path in the browser:
````
{
  "code": "InsufficientScopes",
  "message": "This request requires Taskcluster credentials that satisfy the following scope expression:\n\n```\nqueue:get-artifact:public/logs/live_backing.log\n```\n\n---\n\n* method:     getArtifact\n* errorCode:  InsufficientScopes\n* statusCode: 403\n* time:       2020-12-07T14:09:32.923Z",
  "requestInfo": {
    "method": "getArtifact",
    "params": {
      "0": "public/logs/live_backing.log",
      "taskId": "Kko3Y4iMSump_cB7SLdDgA",
      "runId": "0",
      "name": "public/logs/live_backing.log"
    },
    "payload": {},
    "time": "2020-12-07T14:09:32.923Z"
  }
}
````

I'm not sure what the best way to solve this is, since the redirect artefact is designed to be flexible. Possible blunt solutions could be along the lines of:
- Allow claimed task credentials to be able to sign URLs that expire when the task does, then store the signed URL in the redirect.
- If the next URL is an artefact URL in the same taskcluster instance, sign the target before redirecting. (ick)

**Comment by ricky26** [comment]
CC @djmitche

**Comment by djmitche** [comment]
I let this "marinate" in my head a bit, and the best I've come up with so far is to introduce a new artifact type in the queue, LinkArtifact.  This would be similar to RedirectArtifact, but rather than storing a URL it would store an artifact name.  Fetching a LinkArtifact would be equivalent to fetching the linked artifact on the same task.  We'd need to check scopes on that linked artifact, and check for link cycles, but neither of those would be too hard.

We'd need to patch the workers to create LinkArtifacts instead of RedirectArtifact.

That change itself won't be so hard, but upgrading workers can be a bit tricky.  To help with compatibility, we could translate `createArtifact` calls that create a RedirectArtifact containing a signed or unsigned artifact URL for the same task into a LinkArtifact.  But let's only do that if it truly is difficult to upgrade the workers.

**Comment by ricky26** [comment]
Is there any particular benefit to it being an artefact type vs just another permutation of inputs in `createArtifact`? At least that way, you wouldn't need to introduce a new storage type. (Under the hood it should be relatively safe to store a redirect to `getArtifact` signed by the queue, which expires when the task does.)

To be clear about the permissions implications here, if creating a LinkArtifact requires `queue:get-artifact:<artifact-path>` then all this mechanism is allowing is effectively extending the deadline for your read access to an artefact (i.e. from the task claim duration, to the lifetime of the task). Provided the linked artefact is on the same task, this seems pretty limited in terms of risk.

With regards compatibility, presumably the Mozilla-run TC instances currently only use redirects for public artefacts, so does there need to be a migration? These redirects will keep working on those instances. On our TC instances, it's already broken, so there's no harm there either!

**Comment by djmitche** [comment]
> Is there any particular benefit to it being an artefact type vs just another permutation of inputs in createArtifact? At least that way, you wouldn't need to introduce a new storage type. (Under the hood it should be relatively safe to store a redirect to getArtifact signed by the queue, which expires when the task does.)

If I understand correctly, the idea is that the queue would get `createArtifact(RedirectArtifact{url: signedArtifactUrl})` and rewrite the signature on that URL to last as long as the task expiration?  I think that would work (I have a vague sense that there's a maximum validity duration for signed URLs, but I can't find it in the code), but I'm not sure it's simpler or less surprising than the alternative.  It would be more compatible with existing workers, but as you say that's not necessary.  Adding a new artifact type shouldn't be too difficult, especially in this case where RedirectArtifact already provides a good template.

Regarding permissions, my thinking was that the scopes required for `queue.createArtifact` wouldn't change, but for `queue.getArtifact`, you'd need both `queue:get-artifact:<link-artifact>` and `queue:get-artifact:<link-destination>`.  So there's no escalation at all.

> With regards compatibility, presumably the Mozilla-run TC instances currently only use redirects for public artefacts, so does there need to be a migration? These redirects will keep working on those instances. On our TC instances, it's already broken, so there's no harm there either!

Good point -- there's probably no need to think too hard about compatibility.

**Comment by ricky26** [comment]
> If I understand correctly, the idea is that the queue would get `createArtifact(RedirectArtifact{url: signedArtifactUrl})` and rewrite the signature on that URL to last as long as the task expiration? I think that would work (I have a vague sense that there's a maximum validity duration for signed URLs, but I can't find it in the code), but I'm not sure it's simpler or less surprising than the alternative. It would be more compatible with existing workers, but as you say that's not necessary. Adding a new artifact type shouldn't be too difficult, especially in this case where RedirectArtifact already provides a good template.

Actually, I was just thinking about specifying that either `url` or `artifact` would be required for `RedirectArtifact`. (I'm pretty sure you can do that with JSON-schema.) IIUC there are still ways to read the `storageType` after creation and introducing another type might mean more code duplication elsewhere (I might be wrong on this point though!). Either way is good for me. :smile:

**Comment by djmitche** [comment]
Ah, that makes good sense and might be simpler to implement; thanks!

**Comment by djmitche** [comment]
I started in on that approach, and to be honest it's more confusing than it is helpful.  I think adding a LinkArtifact will be clearer.

**Comment by djmitche** [comment]
https://github.com/djmitche/taskcluster/pull/new/issue4050 <-- got a start on this before the holiday break..

**Comment by djmitche** [comment]
Just a few more tests to write and I'll have the queue support finished.  Then I'll update the workers.
