### ISSUE TITLE
Taskcluster-proxy should not attach authorization header to requests with a bewit

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#4056]
Now that we support requiring authentication for all API endpoints, it's much more common to work with a signed URL.  As in #4022, though, if tc-proxy gets a request for a signed URL (containing `bewit=..` in the query), then it adds an authorization header anyway.  Auth doesn't like that.  A simple fix will be to pass signed URLs through unchanged.

**Comment by djmitche** [comment]
Hm, this needs some more investigation.  A bewit signed for the taskcluster-proxy's hostname won't be valid on the "real" service, and a URL for a "real" service containing a bewit shouldn't be fetched from the proxy.  What the heck is the python client doing here??

**Comment by djmitche** [comment]
https://stage.taskcluster.nonprod.cloudops.mozgcp.net/tasks/HAN-698wRtCTkML6FimXKQ

**Comment by djmitche** [comment]
..which passed??

**Comment by djmitche** [comment]
[same](https://stage.taskcluster.nonprod.cloudops.mozgcp.net/tasks/FBLg4gnnSyiXkD9LNO6QZw) with python-3.8.  Huh..

**Comment by djmitche** [comment]
https://stage.taskcluster.nonprod.cloudops.mozgcp.net/tasks/W-wFgBRNRH-FkB5IC7nAZQ is just a re-trigger of the task in #4022.  @grenade can you think of a reason that this would succeed now?

**Comment by grenade** [comment]
> https://stage.taskcluster.nonprod.cloudops.mozgcp.net/tasks/W-wFgBRNRH-FkB5IC7nAZQ is just a re-trigger of the task in #4022. @grenade can you think of a reason that this would succeed now?

yes. i [modified](https://gist.github.com/grenade/d681a022c0fc525f6147d1bad99e9f53/revisions#diff-91a15b4d3a7e097ba08e68b3c177c26bb4b824e890f03c3874246e51cc31aa6eL13) the gist that is executed to not `raise` the exception (the modified gist goes on to call the unproxied index api, to demonstrate that the unproxied call succeeds). the task livelog still [shows](https://stage.taskcluster.nonprod.cloudops.mozgcp.net/tasks/W-wFgBRNRH-FkB5IC7nAZQ/runs/0/logs/https%3A%2F%2Fstage.taskcluster.nonprod.cloudops.mozgcp.net%2Fapi%2Fqueue%2Fv1%2Ftask%2FW-wFgBRNRH-FkB5IC7nAZQ%2Fruns%2F0%2Fartifacts%2Fpublic%252Flogs%252Flive.log%3Fbewit%3DbW96aWxsYS1hdXRoMC9hZHxNb3ppbGxhLUxEQVB8cnRoaWpzc2VuXDE2MDgxOTExMDZcM2pwUm4vK2d6SVBua3lBeVRKRE9nWWMxakxkVktoNTJ4ckIraW1GUEYzTT1cZXlKalpYSjBhV1pwWTJGMFpTSTZleUoyWlhKemFXOXVJam94TENKelkyOXdaWE1pT2xzaVlYTnpkVzFsT20xdmVtbHNiR0V0WjNKdmRYQTZSR1YyVTJWeWRtbGpaWE5YYVd0cElpd2lZWE56ZFcxbE9tMXZlbWxzYkdFdFozSnZkWEE2UjNKaGNHaHpRV1J0YVc0aUxDSmhjM04xYldVNmJXOTZhV3hzWVMxbmNtOTFjRHBKYm5SeVlXNWxkRmRwYTJraUxDSmhjM04xYldVNmJXOTZhV3hzWVMxbmNtOTFjRHBTWld4RmJtZFhhV3RwSWl3aVlYTnpkVzFsT20xdmVtbHNiR0V0WjNKdmRYQTZVM1JoZEhORVlYTm9ZbTloY21RaUxDSmhjM04xYldVNmJXOTZhV3hzWVMxbmNtOTFjRHBUZVhOQlpHMXBibGRwYTJraUxDSmhjM04xYldVNmJXOTZhV3hzWVMxbmNtOTFjRHBoWTNScGRtVmZjMk50WDJacGNtVm1iM2hqYVNJc0ltRnpjM1Z0WlRwdGIzcHBiR3hoTFdkeWIzVndPbUZqZEdsMlpWOXpZMjFmYkdWMlpXeGZNU0lzSW1GemMzVnRaVHB0YjNwcGJHeGhMV2R5YjNWd09tRmpkR2wyWlY5elkyMWZiR1YyWld4Zk1pSXNJbUZ6YzNWdFpUcHRiM3BwYkd4aExXZHliM1Z3T21GamRHbDJaVjl6WTIxZmRtVnljMmx2Ym1OdmJuUnliMndpTENKaGMzTjFiV1U2Ylc5NmFXeHNZUzFuY205MWNEcGhiR3hmYkdSaGNGOTFjMlZ5Y3lJc0ltRnpjM1Z0WlRwdGIzcHBiR3hoTFdkeWIzVndPbUZzYkY5elkyMWZabWx5WldadmVHTnBJaXdpWVhOemRXMWxPbTF2ZW1sc2JHRXRaM0p2ZFhBNllXeHNYM05qYlY5c1pYWmxiRjh4SWl3aVlYTnpkVzFsT20xdmVtbHNiR0V0WjNKdmRYQTZZV3hzWDNOamJWOXNaWFpsYkY4eUlpd2lZWE56ZFcxbE9tMXZlbWxzYkdFdFozSnZkWEE2WVd4c1gzTmpiVjkyWlhKemFXOXVZMjl1ZEhKdmJDSXNJbUZ6YzNWdFpUcHRiM3BwYkd4aExXZHliM1Z3T21WblpXNWphV0ZmWjJJaUxDSmhjM04xYldVNmJXOTZhV3hzWVMxbmNtOTFjRHBsWjJWdVkybGhYM1ZySWl3aVlYTnpkVzFsT20xdmVtbHNiR0V0WjNKdmRYQTZhVzUyWlc1MGIzSjVJaXdpWVhOemRXMWxPbTF2ZW1sc2JHRXRaM0p2ZFhBNmFXNTJaVzUwYjNKNVgySjFhV3hrSWl3aVlYTnpkVzFsT20xdmVtbHNiR0V0WjNKdmRYQTZibUZuYVc5ellXUnRhVzRpTENKaGMzTjFiV1U2Ylc5NmFXeHNZUzFuY205MWNEcHZabVpwWTJWZmNtVnRiM1JsSWl3aVlYTnpkVzFsT20xdmVtbHNiR0V0WjNKdmRYQTZjR2h2Ym1WaWIyOXJYMkZqWTJWemN5SXNJbUZ6YzNWdFpUcHRiM3BwYkd4aExXZHliM1Z3T25KbGJHOXdjeUlzSW1GemMzVnRaVHB0YjNwcGJHeGhMV2R5YjNWd09uTndaV052Y0hNaUxDSmhjM04xYldVNmJXOTZhV3hzWVMxbmNtOTFjRHAwWVdKc1pXRjFYM1Z6WlhKeklpd2lZWE56ZFcxbE9tMXZlbWxzYkdFdFozSnZkWEE2ZEdWaGJWOXRiMk52SWl3aVlYTnpkVzFsT20xdmVtbHNiR0V0WjNKdmRYQTZkR1ZoYlY5eVpXeHZjSE1pTENKaGMzTjFiV1U2Ylc5NmFXeHNZUzFuY205MWNEcDJjRzVmWVdSdGFXNGlMQ0poYzNOMWJXVTZiVzk2YVd4c1lTMW5jbTkxY0RwMmNHNWZZV1J0YVc1ZmMyVnlkbVZ5YzE5a1l5SXNJbUZ6YzNWdFpUcHRiM3BwYkd4aExXZHliM1Z3T25ad2JsOWlhWFJpWVhKZlpHVjJhV05sY0c5dmJDSXNJbUZ6YzNWdFpUcHRiM3BwYkd4aExXZHliM1Z3T25ad2JsOWpiM0p3SWl3aVlYTnpkVzFsT20xdmVtbHNiR0V0WjNKdmRYQTZkbkJ1WDJSbFptRjFiSFFpTENKaGMzTjFiV1U2Ylc5NmFXeHNZUzFuY205MWNEcDJjRzVmWkhoeUlpd2lZWE56ZFcxbE9tMXZlbWxzYkdFdFozSnZkWEE2ZG5CdVgyZHBkR2xmY21Wc1pXNW5YMlozZEdWemRITmZjbmNpTENKaGMzTjFiV1U2Ylc5NmFXeHNZUzFuY205MWNEcDJjRzVmWjJsMGFWOXlaV3hsYm1kZmNISnBkbUYwWlY5eWR5SXNJbUZ6YzNWdFpUcHRiM3BwYkd4aExXZHliM1Z3T25ad2JsOW5hWFJwWDNKbGJHOXdjMTluY0djaUxDSmhjM04xYldVNmJXOTZhV3hzWVMxbmNtOTFjRHAyY0c1ZmJtRm5hVzl6WDNkbFlpSXNJbUZ6YzNWdFpUcHRiM3BwYkd4aExXZHliM1Z3T25ad2JsOXlaV3hsYm1jaUxDSmhjM04xYldVNmJXOTZhV3hzWVMxbmNtOTFjRHAyY0c1ZmNtVnNaVzVuWDI1aFoybHZjeUlzSW1GemMzVnRaVHB0YjNwcGJHeGhMV2R5YjNWd09uWndibDkyWTJWdWRHVnlYM0psYkc5d2N5SXNJbUZ6YzNWdFpUcHNiMmRwYmkxcFpHVnVkR2wwZVRwdGIzcHBiR3hoTFdGMWRHZ3dMMkZrZkUxdmVtbHNiR0V0VEVSQlVIeHlkR2hwYW5OelpXNGlYU3dpYzNSaGNuUWlPakUyTURneE9Ea3lNREEyTXpZc0ltVjRjR2x5ZVNJNk1UWXdPREU1TVRBd01EWXpOaXdpYzJWbFpDSTZJbTFvUzBKUlZHUnpVbmxYTlRoa1FqaE1TRUpIZW1kb1dsSnFjWFJyZDFFMWFVMUtaRTlXYW10d09WZEJJaXdpYzJsbmJtRjBkWEpsSWpvaUszcHVVV1J2YXpSR1kxbFRkMUJPYzJObmRHbGFNeTlDWVRaSVltWm9jV3hzTWtoSlNFcFVWa05XV1QwaUxDSnBjM04xWlhJaU9pSnpkR0YwYVdNdmRHRnphMk5zZFhOMFpYSXZkMlZpTFhObGNuWmxjaUo5ZlE9PQ#L128) the behaviour (`Cannot use two authentication schemes at once this request has both bewit in querystring and 'authorization' header`) it just doesn't throw the exception and cause the task to fail anymore, but it still demonstrates that proxied calls fail while direct calls succeed.

**Comment by djmitche** [comment]
Ah, got it.  I interpreted the sha in the URL to be pinning a version, but it's only the gist ID.  That was silly of me!

**Comment by djmitche** [comment]
OK, I'm able to repro this with a local proxy.

**Comment by djmitche** [comment]
It looks like the Python library is not at fault here!  Rather, tc-proxy is following the redirect in the response from the server, and again adding the Authorization header.  It shouldn't be following that redirect.
