### ISSUE TITLE
Task group actions are not displayed

### ISSUE THREAD

**Issue by ricky26** [taskcluster/taskcluster#4061]
**Describe the bug**
The 'more' button which usually appears in the bottom right when there are task group actions is no longer appearing.

**To Reproduce**

1. Start a decision task which produces actions with `kind: 'task', context: []`.
2. Wait for the task to complete.
3. Notice that the button to access the action does not appear.

**Expected behavior**
The actions should still be displayed.

**Taskcluster version**
v39.0.0

**Additional context**
It looks like this is caused by upgrading the `sift` library to v13. Negating all of the incoming queries (by wrapping with `{$not: x}` seems to work, alarmingly). Rolling back to v8 resolves the issue.

When viewing the decision task itself, the action is returned from `/graphql` but is not displayed.

**Comment by ricky26** [comment]
More information (and a much more defined repro):
```
Welcome to Node.js v14.12.0.
Type ".help" for more information.
> const sift = require('sift').default;
undefined
> let f = sift({ $size: 0 });
undefined
> f([]) // <-- !!! This is bad! !!!
false
> f([1])
false
> f([2])
false
> f([1, 2, 2])
false
> let f = sift({ $size: 1 });
Uncaught SyntaxError: Identifier 'f' has already been declared
> f = sift({ $size: 1 });
[Function (anonymous)]
> f([])
false
> f([1])
true
> f([1, 2])
false

```

**Comment by ricky26** [comment]
I've filed an upstream issue: https://github.com/crcn/sift.js/issues/217

**Comment by djmitche** [comment]
Thanks!  I'll make a PR to roll back to v8.
