### ISSUE TITLE
Trying to use authorizedScopes with Taskcluster CLI produces errors

### ISSUE THREAD

**Issue by ricky26** [taskcluster/taskcluster#4072]
**Describe the bug**
In order to use `authorizedScopes` with the Taskcluster CLI, it has to be added to the config. However, when added, it produces errors.

For example, in `~/.config/taskcluster.yml`:
```yaml
config:
  authorizedScopes:
  - queue:get-artifact:hams/*
```

Results in:
```
failed to load configuration file, error: invalid value '["queue:get-artifact:hams/*"]' for config option 'config.authorizedScopes', error: Must be a list of strings
```

**To Reproduce**

1. Fill in your taskcluster CLI config file as above.
2. Run `taskcluster config`.
3. See error

**Expected behavior**
`authorizedScopes` should work in the Taskcluster CLI.

**Taskcluster version**
v39.0.0

**Additional context**
This appears to be due to the validation / casting done in the `authorizedScopes` implementation in `client-shell`. It might need to transformed rather than just checked (from `[]interface{}` to `[]string`).

CC @djmitche

**Comment by djmitche** [comment]
The config file caused lots of confusion for people, and also encouraged putting long-term credentials in there where any random script can use them -- something we do not want to encourage.  I'd like to introduce a different way of configuring this, more similar to to the other credentials.  So, `TASKCLUSTER_AUTHORIZED_SCOPES='["..", ".."]`.

I'll fix this particular bug here, but wanted to get some feedback on that idea as a followup.

**Comment by djmitche** [comment]
(^^ I moved that to #4166)

**Comment by ricky26** [comment]
I like the sound of the environment variable option. Especially as authorized scopes are part of auth. Since this is currently broken, is there any value in fixing it if you want to move all auth to just the environment?

**Comment by djmitche** [comment]
Too late :)  As you surmised, this was a pretty easy fix.
