### ISSUE TITLE
Return 404 from queue.getArtifact when an artifact has expired

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#4086]
Artifacts have an expiration time, and a periodic task deletes them after that time.  As a result, it's possible to find an artifact in the database with an expiration time in the past.  The queue service's `getArtifact` method should return a 404 in this case.

To get started on this, set up your development environment and then try to reproduce this situation in a test in `services/queue/test/artifact_test.js`.  Once you've done that -- created a failing test -- look at the implementation of `getArtifact` in services/queue/src/artifacts.js` and make a minimal change to make the test pass.

**Comment by jwhitlock** [comment]
How about ``410 Gone``? It it more precise, but does add a case for anyone switching on the status code.

**Comment by dhanesh12twice** [comment]
Hi djmitche,may i work on this bug?
is this  bug for the product firefox?

**Comment by djmitche** [comment]
I like 410 GONE!

@dhanesh12twice yes, you may!  This is an issue with Taskcluster, which is a CI platform that Firefox uses, but is not itself part of Firefox.  Still interested?

**Comment by dhanesh12twice** [comment]
@djmitche do i need to build anyother product? I have build firefox alredy . Just tell me what i need to do.
Thank you,
Dhanesh

**Comment by djmitche** [comment]
Building firefox is an achievement, so -- nice work 👍🏽 

This is a different product, yes.  There are some [devleopment docs here](https://github.com/taskcluster/taskcluster/blob/main/dev-docs/development-process.md) that detail how to get things set up for development.  Note that if you use Windows, you'll need to use WSL or a Linux VM to build Taskcluster.  You can ignore the "Hacking on the UI" section for this bug, as it does not require changes to the UI.

You'll be changing the queue service, so let me know when you've got that service's tests running (`yarn workspace taskcluster-queue test`).

**Comment by dhanesh12twice** [comment]
@djmitche huh..it seems overwhelming at the moment..haha. Give me some time to setup the basics. 
Thank you

**Comment by djmitche** [comment]
Sure thing -- it's a lot of setup.  Take your time!
