### ISSUE TITLE
[UI] Ignore casing when matching search term in Task Group

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#409]
STR:

1. Navigate to https://taskcluster-web.netlify.com/tasks/groups/PnUuYtALTAqY-P9HRHYRrw
2. Type 'retrigger' in the search box below the progress buttons and then press enter

![Screen Shot 2019-03-13 at 9 12 42 AM](https://user-images.githubusercontent.com/3766511/54281490-3935ed80-4570-11e9-9391-254a11ae048e.png)

**Actual**: No tasks available, however if you type "Retrigger" and then press enter then there will be some matches.
**Expected**: Some tasks match this name

Solution: We need to ignore casing when comparing strings

**Comment by HarieshJay** [comment]
Hi @helfi92,

May I work on this issue?
This would be my first fix, so hopefully, it's not too intensive.

**Comment by helfi92** [comment]
Go for it :)

**Comment by HarieshJay** [comment]
Could you please assign me to this task?

**Comment by helfi92** [comment]
Done. You should accept the invitation :)

**Comment by HarieshJay** [comment]
Perfect, Thanks!

**Comment by HarieshJay** [comment]
I am having a little trouble setting up the taskcluster-web UI application, and I am not finding IRC helpful. Is there any other resource I can check out?

**Comment by helfi92** [comment]
What problem are you facing?

**Comment by HarieshJay** [comment]
I am not sure how to actually run the UI application.

I followed the docs in the taskcluster/ui folder that first said to set up the taskcluster/services/web-server docs, which I did and can run http://localhost:3050/playground on my local environment, but I do not know how to run anything besides that.

Then I added a .env file to the root of the directory with the contents:


APPLICATION_NAME="Taskcluster"
PORT="9000"

TASKCLUSTER_ROOT_URL="https://taskcluster.net"



If I run "yarn start" in the UI folder I get the error that says:

**yarn run v1.13.0

$ dotenv webpack-dev-server -- --mode development

/bin/sh: 1: dotenv: not found

error Command failed with exit code 127.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command**


Running yarn start in the services/web-server folder executes as such:

**yarn run v1.13.0
$ NODE_ENV=development webpack

webpack is watching the files…

Hash: 8cf04bb20e22b1abec65
Version: webpack 4.29.6
Time: 803ms
Built at: 03/17/2019 4:01:38 PM
   Asset     Size  Chunks             Chunk Names
index.js  496 KiB   index  [emitted]  index


No Pulse namespace defined; no Pulse messages will be received.


Web server running on port 3050.

Open the interactive GraphQL Playground and schema explorer in your browser at:
        http://localhost:3050/playground**


Thanks for the help,


And If there is some slack group/ discord that can better help me, then please direct me there. I don't find the IRC particularly helpful.

**Comment by helfi92** [comment]
> Then I added a .env file to the root of the directory with the contents.

The `.env` file should be located under the `ui` directory.

> If I run "yarn start" in the UI folder I get the error that says:

Run `yarn install` before to install all the dependencies.

```bash
yarn install
yarn start
```

> Running yarn start in the services/web-server folder executes as such

That's fine.

**Comment by HarieshJay** [comment]
Where would you actually find the UI application, since the server is only running on port 3050, and not on 9000 as the docs stated and as I put in the .env variable?

**Comment by helfi92** [comment]
> Where would you actually find the UI application, since the server is only running on port 3050, and not on 9000 as the docs stated and as I put in the .env variable?

Assuming you put PORT=9000 in `ui/.env`, the UI will be displayed on http://localhost:9000/

<img width="423" alt="Screen Shot 2019-03-17 at 5 08 30 PM" src="https://user-images.githubusercontent.com/3766511/54497959-50aa0900-48d7-11e9-8505-76a3fea44913.png">

**Comment by HarieshJay** [comment]
Thank you very much,

It finally works! I am getting a network error now, but I should be able to figure that out on my own.

**Comment by HarieshJay** [comment]
Hi again,

I am having the same error that appeared in this [issue:](https://github.com/taskcluster/taskcluster/issues/175)


[Here](https://imgur.com/a/VUn4Ciy) it is on my computer:

Did you guys end up finding the problem?

I am running a server on both [/ui](https://imgur.com/a/WqLAEgS) and [/services/web-server](https://imgur.com/a/6Q3ILkL)

This is my .env file in /ui:
```
APPLICATION_NAME="Taskcluster"

TASKCLUSTER_ROOT_URL="https://taskcluster.net"


APPLICATION_NAME="Taskcluster"
AUTH0_DOMAIN="auth.mozilla.auth0.com"
AUTH0_CLIENT_ID="29t2n3LKKnyTbGtWmfTkQpau0mp7QmMH"
AUTH0_REDIRECT_URI="http://localhost:5080/login"
AUTH0_RESPONSE_TYPE="token id_token"
AUTH0_SCOPE="openid profile"
PORT="9000"
```

This my .env file in /services/web-server
```
APPLICATION_NAME="Taskcluster"



APPLICATION_NAME="Taskcluster"
PORT="9000"

TASKCLUSTER_ROOT_URL="https://taskcluster.net"


DEBUG=* yarn start
```

You suggested to include that DEBUG line, but I wasn't sure where.

Thanks for the help again.

**Comment by helfi92** [comment]
Two things:
1. There shouldn't be any `.env` file in `services/web-server`. Delete it.
2. In `user-config.yml`, delete everything under `pulse`. The end output should be:

```bash
defaults:
  taskcluster:
      rootUrl: "https://taskcluster.net"
```

**Comment by HarieshJay** [comment]
I have done those 2 things and I still get the "Network error: Failed to fetch error".

Also, when I delete the .env file the web-server defaults to port 3050, while the ui server is at port 9000, is that fine?

**Comment by helfi92** [comment]
> Also, when I delete the .env file the web-server defaults to port 3050, while the ui server is at port 9000, is that fine?

Yes, the ports need to be different.

> I have done those 2 things and I still get the "Network error: Failed to fetch error".

Did you restart the server after doing that?

**Comment by HarieshJay** [comment]
Yea, I turned off both servers and ran yarn and yarn build just in case, and then yarn start again.

**Comment by helfi92** [comment]
Can you show me the content of both `.env` and `user-config.yml`.

**Comment by HarieshJay** [comment]
Here is my .env in /ui
```
APPLICATION_NAME="Taskcluster"

TASKCLUSTER_ROOT_URL="https://taskcluster.net"


APPLICATION_NAME="Taskcluster"
AUTH0_DOMAIN="auth.mozilla.auth0.com"
AUTH0_CLIENT_ID="29t2n3LKKnyTbGtWmfTkQpau0mp7QmMH"
AUTH0_REDIRECT_URI="http://localhost:5080/login"
AUTH0_RESPONSE_TYPE="token id_token"
AUTH0_SCOPE="openid profile"
PORT="9000"
```

And here is my user-config.yml inside /services/web-server
```
defaults:
  taskcluster:
      rootUrl: "https://taskcluster.net"
 
```

**Comment by helfi92** [comment]
There seems to be two `APPLICATION_NAME` in `ui/.env`. Please remove one of them.

**Comment by helfi92** [comment]
How are you running the web server?

**Comment by HarieshJay** [comment]
I just run yarn start in the web-server folder

**Comment by helfi92** [comment]
Run it with:

```bash
DEBUG=* yarn start
```

and see if you see anything interesting there.

**Comment by HarieshJay** [comment]
This is the output I got

```
hariesh@hariesh-HP-EliteBook-840-G3:~/Documents/Programming/OpenSource/Mozilla/src/taskcluster/services/web-server$ DEBUG=* yarn start
yarn run v1.13.0
$ NODE_ENV=development webpack
  snapdragon:compiler initializing /home/hariesh/Documents/Programming/OpenSource/Mozilla/src/taskcluster/node_modules/snapdragon/lib/compiler.js +0ms
  snapdragon:parser initializing /home/hariesh/Documents/Programming/OpenSource/Mozilla/src/taskcluster/node_modules/snapdragon/lib/parser.js +2ms

webpack is watching the files…

  babel:config:loading:files:plugins Loaded plugin '/home/hariesh/Documents/Programming/OpenSource/Mozilla/src/taskcluster/node_modules/@babel/plugin-syntax-dynamic-import/lib/index.js' from '/home/hariesh/Documents/Programming/OpenSource/Mozilla/src/taskcluster/services/web-server'. +0ms
  babel:config:loading:files:plugins Loaded plugin '/home/hariesh/Documents/Programming/OpenSource/Mozilla/src/taskcluster/node_modules/@babel/plugin-proposal-class-properties/lib/index.js' from '/home/hariesh/Documents/Programming/OpenSource/Mozilla/src/taskcluster/services/web-server'. +2ms
  babel:config:loading:files:plugins Loaded preset '/home/hariesh/Documents/Programming/OpenSource/Mozilla/src/taskcluster/node_modules/@babel/preset-env/lib/index.js' from '/home/hariesh/Documents/Programming/OpenSource/Mozilla/src/taskcluster/services/web-server'. +101ms
Hash: 8cf04bb20e22b1abec65
Version: webpack 4.29.6
Time: 754ms
Built at: 03/19/2019 5:49:58 PM
   Asset     Size  Chunks             Chunk Names
index.js  496 KiB   index  [emitted]  index
  express:application set "x-powered-by" to true +0ms
  express:application set "etag" to 'weak' +2ms
  express:application set "etag fn" to [Function: generateETag] +0ms
  express:application set "env" to 'development' +1ms
  express:application set "query parser" to 'extended' +0ms
  express:application set "query parser fn" to [Function: parseExtendedQueryString] +0ms
  express:application set "subdomain offset" to 2 +0ms
  express:application set "trust proxy" to false +0ms
  express:application set "trust proxy fn" to [Function: trustNone] +0ms
  express:application booting in development mode +0ms
  express:application set "view" to [Function: View] +0ms
  express:application set "views" to '/home/hariesh/Documents/Programming/OpenSource/Mozilla/src/taskcluster/services/web-server/views' +1ms
  express:application set "jsonp callback name" to 'callback' +0ms
  express:application set "view engine" to 'ejs' +0ms
  express:application set "views" to 'src/views' +0ms
  express:router use '/' query +0ms
  express:router:layer new '/' +0ms
  express:router use '/' expressInit +1ms
  express:router:layer new '/' +0ms
  express:router use '/' corsMiddleware +0ms
  express:router:layer new '/' +0ms
  express:router use '/' initialize +0ms
  express:router:layer new '/' +0ms
  express:router use '/' <anonymous> +1ms
  express:router:layer new '/' +0ms
  express:router use '/' compression +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/graphql' +0ms
  express:router:layer new '/graphql' +0ms
  express:router:route post '/graphql' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/playground' +0ms
  express:router:layer new '/playground' +0ms
  express:router:route get '/playground' +0ms
  express:router:layer new '/' +0ms


No Pulse namespace defined; no Pulse messages will be received.
  express:router use '/graphql' <anonymous> +73ms
  express:router:layer new '/graphql' +0ms
  express:router use '/.well-known/apollo/server-health' <anonymous> +0ms
  express:router:layer new '/.well-known/apollo/server-health' +0ms
  express:router use '/graphql' corsMiddleware +0ms
  express:router:layer new '/graphql' +0ms
  express:router use '/graphql' jsonParser +0ms
  express:router:layer new '/graphql' +1ms
  express:router use '/graphql' <anonymous> +0ms
  express:router:layer new '/graphql' +0ms
  express:router use '/graphql' <anonymous> +0ms
  express:router:layer new '/graphql' +0ms


Web server running on port 3050.

Open the interactive GraphQL Playground and schema explorer in your browser at:
        http://localhost:3050/playground



```

**Comment by helfi92** [comment]
Ok, that looks good. What about the ui, what do you see in the terminal?

**Comment by helfi92** [comment]
Also, what url are you using for which you are getting an error?

**Comment by HarieshJay** [comment]
When I run DEBUG=* yarn start on ui I get a large output which is at least a couple hundred lines long, and when I run just yarn start I get:

```
yarn run v1.13.0
$ dotenv webpack-dev-server -- --mode development
ℹ ｢wds｣: Project is running at http://localhost:9000/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: 404s will fallback to /index.html
ℹ ｢wdm｣: Time: 18091ms
ℹ ｢wdm｣: Compiled successfully.

```
I get that error on several pages including /tasks/index, and /tasks/groups/ whenever I search for something.

**Comment by helfi92** [comment]
Oh, try making `PORT=5080` instead of 9000.

**Comment by HarieshJay** [comment]
Perfect it works now.
Thank you so much!

**Comment by helfi92** [comment]
I'll try and see if I can make this work.

**Comment by helfi92** [comment]
@HarieshJay In case you were wondering how to do this, I was able to do it in https://github.com/taskcluster/taskcluster/pull/532/commits/a1d7bb1c1270e5a0006545fb9ae83d33a62b4271 :) Thanks for offering your help!

**Comment by HarieshJay** [comment]
Thanks for working on this. 

Sorry I couldn't finish it in time.
