### ISSUE TITLE
Rerun task doesn't update status on PR

### ISSUE THREAD

**Issue by JohanLorenzo** [taskcluster/taskcluster#41]
Happened on https://github.com/mozilla-releng/build-puppet/pull/82. 

# STR

1. Open PR and let tests run.
2. Have one task failing
3. When the task graph is done, rerun failed task.
4. Let failed task pass.
5. See taskgraph being green, but PR still showing red.

**Comment by lotas** [comment]
I will close this issue in favor of #5085
