### ISSUE TITLE
Error boundary causes infinite loops

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#4110]
..and these loops crash the browser, as they don't stop when Firefox's "do you want to stop this script" prompt appears.

STR (I think):

* Write a render method that raises an exception

The error appears in the console but moves too quickly and crashes the browser too quickly to scroll back.  I think it shows the original exception with traceback, followed by "React will try this in your error boundary, AppComponent".

I've seen this during development -- and I've also see exceptions in a render method *not* cause this!  But @lissyx has seen similar things in the production UI (at least, hanging the browser).

Maybe we should just remove the error boundary?

**Comment by lissyx** [comment]
I was thinking how much should this also be filed against gecko ? Sounds like à trivial DoS ? Given how it was making my browser suffer, if its the same cause (and the description make it likely)

**Comment by djmitche** [comment]
If we can get some additional data, or a repro, that might be useful, yeah.

**Comment by djmitche** [comment]
I just added an ErrorBoundary to the mentoring app, so this is fresh in my mind..

**Comment by djmitche** [comment]
```patch
diff --git a/ui/src/views/HomeOrDashboard/index.jsx b/ui/src/views/HomeOrDashboard/index.jsx
index 501e5d944..132d7206e 100644
--- a/ui/src/views/HomeOrDashboard/index.jsx
+++ b/ui/src/views/HomeOrDashboard/index.jsx
@@ -7,15 +7,11 @@ const Home = lazy(() => import(/* webpackChunkName: 'Home' */ '../Home'));
 const Dashboard = lazy(() =>
   import(/* webpackChunkName: 'Dashboard' */ '../Dashboard')
 );
 
 @hot(module)
 @withAuth
 export default class HomeOrDashboard extends Component {
   render() {
-    return this.props.user ? (
-      <Dashboard {...this.props} />
-    ) : (
-      <Home {...this.props} />
-    );
+    throw new Error('uhoh');
   }
 }
```
and letting that load for a few seconds is enough to nearly crash the browser.

**Comment by djmitche** [comment]
Ah, this is because on error, it attempts to re-render the same components with an error bar overlaid.  That's pretty silly.

**Comment by djmitche** [comment]
I suspect it's just killing the browser by spewing massive quantities into the console in a tight loop.  I can't figure out how to reproduce this in a reduced test-case, though.  React seems to have some protections against this, as it seems to stop the loop after 2-3 iterations.  Somehow TC must be defeating those protections!

**Comment by djmitche** [comment]
And having to restart the browser for every debugging iteration is getting tiresome!
