### ISSUE TITLE
Hooks don't display

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#412]
STR:
* https://taskcluster-web.netlify.com/hooks/hg-push/autoland

I suspect that the GraphQL is assuming that the task template will match a task definition.  It doesn't -- it's a JSON-e data structure so entirely arbitrary.

**Comment by helfi92** [comment]
I'm on it.

**Comment by djmitche** [comment]
Hm, still not working:

https://taskcluster-web.netlify.com/hooks/hg-push/try is another example.

**Comment by djmitche** [comment]
![Screenshot_2019-03-14 Hook - Taskcluster](https://user-images.githubusercontent.com/28673/54371858-28f14180-4648-11e9-9b58-b78a63168d81.png)

**Comment by djmitche** [comment]
Or, was the fix just not deployed to production?

i see in the network inspector:
```
{
  "errors": [
    {
      "message": "Field \"task\" of type \"HookTask!\" must have a selection of subfields. Did you mean \"task { ... }\"?",
      "locations": [
        {
          "line": 35,
          "column": 5
        }
      ],
      "extensions": {
        "code": "GRAPHQL_VALIDATION_FAILED"
      }
    }
  ]
}
```
(would it make sense to show that error, too?)

**Comment by helfi92** [comment]
Sorry, I forgot auto deployment was turned off after bringing web-server to the monorepo. I just deployed it. https://taskcluster-web.netlify.com/hooks/hg-push/autoland work for me. Can you confirm?

**Comment by djmitche** [comment]
Sweet, yes, and sorry for the false alarm!
