### ISSUE TITLE
Hook errors are not displayed

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#4124]
https://community-tc.services.mozilla.com/hooks/project-fuzzing/grizzly-reduce-reset-error lists a bunch of firings as "ERROR", but clicking the (i) shows 
![image](https://user-images.githubusercontent.com/28673/102410816-15ae9b00-3fbf-11eb-8db1-d72d4a508147.png)
and inspecting that element shows no text.  Yet there's an error from the API:
https://gist.github.com/djmitche/eb1995b6d2de40bbcdeae6eeedfea35e

**Comment by uditmishra128** [comment]
Can I work on this issue.

**Comment by uditmishra128** [comment]
Can I work in this issue . Please guide me.

**Comment by djmitche** [comment]
Sure!  The first bit is to get the Taskcluster development environment set up.  That's documented [here](https://github.com/taskcluster/taskcluster/blob/main/dev-docs/development-process.md).

Also, the link in the first comment no longer shows errors.  I made a new hook with some errors on it, https://community-tc.services.mozilla.com/hooks/project-taskcluster/testing-4124.

**Comment by uditmishra128** [comment]
Thanks, I'll check it out.

**Comment by lotas** [comment]
this was fixed already
