### ISSUE TITLE
[UI] taskcluster.net/docs

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#413]
Deploy new docs on taskcluster.net/docs.

TODO:

* [x] Create a new Heroku app taskcluster-net
* [x] Create a CloudFront entry that points to the heroku app
* [x] Redirect docs.tc.net to tc.net/docs (aws lambda?)

**Comment by djmitche** [comment]
Let's talk about this on Friday before pulling the switch.

**Comment by djmitche** [comment]
We talked about using https://taskcluster.net/docs instead.  And that once we have figured out what to do with worker docs, we can start redirecting from https://docs.taskcluster.net/docs to this site.

**Comment by helfi92** [comment]
https://taskcluster.net.
