### ISSUE TITLE
handle missing property `taskId` more gracefully in task viewer

### ISSUE THREAD

**Issue by escapewindow** [taskcluster/taskcluster#4154]
**Describe the bug**

I'm not 100% sure what the culprit is, but:

- a task `Zdh9XqQGSK6XciSvVyfopQ` exists
- I'm able to download artifacts from it
- I'm able to view its task definition
- going to https://firefox-ci-tc.services.mozilla.com/tasks/Zdh9XqQGSK6XciSvVyfopQ gives me `can't access property "taskId", t is null`

**To Reproduce**

1. Go to https://firefox-ci-tc.services.mozilla.com/tasks/Zdh9XqQGSK6XciSvVyfopQ
2. See error

**Expected behavior**

I expect to see the task runs, statuses, dependencies, etc as normal.

**Taskcluster version**

39.1.1-6-g65facdf39

**Screenshots**
<img width="1036" alt="Screen Shot 2020-12-22 at 10 35 09 AM" src="https://user-images.githubusercontent.com/826343/102921541-63088d80-4441-11eb-9d2b-3d6876d9df4e.png">

**Platform (please complete the following information):**

 - OS: OSX 11.1 (intel)
 - Browser: Firefox Nightly
 - Version: 86.0a1 (2020-12-22) (64-bit)

**Additional context**

I get `null is not an object (evaluating 't.taskId')` on logged out Safari. I get the `can't access property..." error in Firefox Nightly, where I'm signed in.

**Comment by djmitche** [comment]
I think this is because its dependency, SCADQGgMSE-HeAF4btfepQ, has expired -- #3983.
