### ISSUE TITLE
Triggering builds through tagging

### ISSUE THREAD

**Issue by jugglinmike** [taskcluster/taskcluster#42]
I'd like to trigger TaskCluster to run in response to pushing a tag to my repository on GitHub. The GitHub API docs on the "push" event read, "Any Git push to a Repository, including editing tags or branches." This leads me to believe I can react to tags in my `.taskcluster.yml` file with something like

    $if: 'event.ref == "refs/heads/master" || event.ref[:13] == "refs/tags/tc-"'

I can verify that the webhook event was sent from GitHub, but I don't know how to determine if this triggered any work on TaskCluster. Under these circumstances, I would expect that the tagged commit would be updated with a "build status" indicator icon in the repository's history listing.

Is this expected to trigger activity on TaskCluster? If so, is there some other way to view the tasks? Thanks!

**Comment by djmitche** [comment]
No answer, so I think we can close this..
