### ISSUE TITLE
Remove minification from yarn generate

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#4226]
The `yarn minify` is a good idea, but means that renovate PRs almost always fail and require some followup.  That's preventing automerge.

What if we make `yarn minify` a separate admin command, that we can apply manually in its own PR from time to time (and if we don't get around to it, oh well too bad)?  Then Renovate PRs will always succeed.

@imbstack as the one with the most context on yarn deps, your thoughts?

**Comment by imbstack** [comment]
Seems fine to me. If we really want to get fancy we could make a task that only runs on master that doesn't fail when we haven't minified but does email us. Probably too much work though

**Comment by djmitche** [comment]
It would email us a lot :)

We could maybe make a hook to do that 🤷🏽
