### ISSUE TITLE
Task create page only shows an error

### ISSUE THREAD

**Issue by ricky26** [taskcluster/taskcluster#4239]
**Describe the bug**
When trying to create a task, the error `Function yaml.safeDump is removed in js-yaml 4. Use yaml.dump instead, which is now safe by default.` is seen. It looks like this was caused by an upgrade to `js-yaml`.

**To Reproduce**

1. Go to the task creation page
2. See error

**Expected behavior**
The task creation page should display the task editor.

**Taskcluster version**
v40.0.0

**Comment by djmitche** [comment]
🤦🏽 

I think I looked for `yaml.safeDump`, but the UI code destructures everything so it's just `safeDump` there.
