### ISSUE TITLE
[UI] display "plain old" JSON in pulse inspector

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#424]
![Screenshot_2019-03-14 Pulse Messages - Taskcluster](https://user-images.githubusercontent.com/28673/54371456-699c8b00-4647-11e9-96f0-6edf9b3de235.png)

This tree-shaped JSON display is confusing, but more importantly very difficult to copy/paste from.  I need to reconstruct that message and the only way to do so is to retype it :(

**Comment by helfi92** [comment]
Agreed, It's definitely not the best to copy/paste. I'm on it.

**Comment by djmitche** [comment]
(I'd be happy to drop all uses of whatever component generates that output)

**Comment by helfi92** [comment]
@djmitche I'm not sure I follow. Are you proposing we don't show the payload?

**Comment by djmitche** [comment]
No, just to display the JSON as JSON like we do in most of the UI

**Comment by helfi92** [comment]
\o/ I like that
