### ISSUE TITLE
View task definition links require queue:get-task:

### ISSUE THREAD

**Issue by ricky26** [taskcluster/taskcluster#4240]
**Describe the bug**
Clicking view task definition on a task links the the API for `getTask` which doesn't work on private Taskcluster instances.

**To Reproduce**

1. Setup a Taskcluster instance with an empty anonymous role.
2. Create a task.
3. Click 'View task definition'.

**Expected behavior**
Viewing the task definition in the UI should use the user's authentication.

**Taskcluster version**
v39.1.0

**Comment by djmitche** [comment]
We should probably display it as text in the UI (sort of like the log viewer in that it's a separate view from the main task view).
