### ISSUE TITLE
Calling listArtifacts on a task with a Link artifact causes an error

### ISSUE THREAD

**Issue by ricky26** [taskcluster/taskcluster#4248]
**Describe the bug**
When calling listArtifacts on a task with a Link artifact, the following error is printed:

```
Error: Output schema validation error: 
    at ServerResponse.res.reply (/app/libraries/api/src/middleware/schema.js:80:23)
    at Proxy.<anonymous> (/app/services/queue/src/artifacts.js:626:14)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

It looks like this is because `contentType` is undefined.

**To Reproduce**

1. Create a Link artifact on a Task.
2. Navigate to the task page.
3. Open the logs for the queue-web service.

**Expected behavior**
Link artifacts should not impact the listArtifacts endpoint.

**Taskcluster version**
v40.0.3

@djmitche since this one doesn't involve db functions, I'm happy to have a look. :sweat_smile:

**Comment by djmitche** [comment]
Wow, I did a great job of this :(

**Comment by ricky26** [comment]
I'm happy to be the canary here! :bird:
