### ISSUE TITLE
[UI] Add a way to preview inputs that accept markdown

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#425]
STR:

1. Navigate to https://taskcluster-web.netlify.com/hooks/garbage/abc456
2. Write some markdown in the description text field

![Screen Shot 2019-03-14 at 1 50 27 PM](https://user-images.githubusercontent.com/3766511/54379648-3286a380-4660-11e9-8e0c-739714e70e20.png)

**Expected**: There is a way to preview the rendered markdown
**Actual**: There is no way to preview the render markdown.

**Comment by helfi92** [comment]
One way to do this is to have the text field nested in a [tab panel](https://material-ui.com/demos/tabs/#tabs) where one tab would be the rendered markdown and the other the raw input.

**Comment by projectyang** [comment]
Hey @helfi92,

I'd like to tackle this.

**Comment by helfi92** [comment]
Hey @projectyang 👋

Go for it!
