### ISSUE TITLE
0059 migration is running at 50 items/sec

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#4250]
That's really slow!  Why?

![image](https://user-images.githubusercontent.com/28673/104362909-680da980-54e2-11eb-9bd9-ecd8970ff2c0.png)

**Comment by djmitche** [comment]
@sciurus will help me get DB access tomorrow to experiment with this -- until then we'll stop the migration.

I expect the issue is that the `state`-based query isn't correctly using the index to find the place to start in the tasks table, and instead each batch is starting over at the beginning of the table and spending an increasing fraction of its time scanning for un-processed rows (the high read load) before processing those rows (the vanishing write load).  I suspect the sharp spike in read load is when the query optimizer decided, for its own nefarious reasons, that the index was passé and sequential scans were the way to go.

**Comment by sciurus** [comment]
"yarn run v1.22.10\n",
 "$ node db/src/main.js upgrade\n",
 "12 Jan 14:24:25 - ..ensuring online functions are removed\n",
 "12 Jan 14:24:25 - upgrading database to version 59\n",
 "12 Jan 14:24:25 - ..ensuring online functions are removed\n",
 "12 Jan 14:24:25 - ..running migration script\n",
 "12 Jan 14:24:25 - ..defining methods\n",
 "12 Jan 14:24:25 -    defining create_task\n",
 "12 Jan 14:24:25 -    defining get_task\n",
 "12 Jan 14:24:25 -    defining get_tasks_by_task_group\n",
 "12 Jan 14:24:25 - ..updating version\n",
 "12 Jan 14:24:25 - ..checking completion of online migration for db version 59\n",
 "12 Jan 14:24:25 -    1 items complete at 71.4/s\n",
 "12 Jan 14:24:27 -    898 items complete at 566.9/s\n",
 "12 Jan 14:24:29 -    2747 items complete at 697/s\n",
 "12 Jan 14:24:34 -    6439 items complete at 782.6/s\n",
 "12 Jan 14:24:42 -    13647 items complete at 813.8/s\n",
 "12 Jan 14:24:59 -    28788 items complete at 858.5/s\n",
 "12 Jan 14:25:32 -    53415 items complete at 803.9/s\n",
 "12 Jan 14:26:32 -    99387 items complete at 785.1/s\n",
 "12 Jan 14:27:33 -    149085 items complete at 795/s\n",
 "12 Jan 14:28:33 -    198681 items complete at 801.7/s\n",
 "12 Jan 14:29:33 -    243387 items complete at 790.6/s\n",
 "12 Jan 14:30:33 -    284935 items complete at 774.4/s\n",
 "12 Jan 14:31:35 -    295564 items complete at 687.5/s\n",
 "12 Jan 14:32:53 -    297512 items complete at 586/s\n",
 "12 Jan 14:33:57 -    317572 items complete at 555.5/s\n",
 "12 Jan 14:35:00 -    321835 items complete at 507.2/s\n",
 "12 Jan 14:36:01 -    336160 items complete at 483.5/s\n",
 "12 Jan 14:37:02 -    351339 items complete at 464.2/s\n",
 "12 Jan 14:38:03 -    365451 items complete at 442.9/s\n",
 "12 Jan 14:39:03 -    378285 items complete at 412.1/s\n",
 "12 Jan 14:40:04 -    390637 items complete at 383.8/s\n",
 "12 Jan 14:41:06 -    401755 items complete at 356.3/s\n",
 "12 Jan 14:42:17 -    410728 items complete at 327.6/s\n",
 "12 Jan 14:43:25 -    411056 items complete at 305.2/s\n",
 "12 Jan 14:44:32 -    411361 items complete at 286/s\n",
 "12 Jan 14:46:04 -    411647 items complete at 263.2/s\n",
 "12 Jan 14:47:10 -    411910 items complete at 249/s\n",
 "12 Jan 14:48:53 -    412159 items complete at 229.5/s\n",
 "12 Jan 14:49:55 -    412389 items complete at 219/s\n",
 "12 Jan 14:51:32 -    412608 items complete at 204.5/s\n",
 "12 Jan 14:52:42 -    412812 items complete at 195.1/s\n",
 "12 Jan 14:55:11 -    413195 items complete at 177.6/s\n",
 "12 Jan 14:57:13 -    413547 items complete at 165.3/s\n",
 "12 Jan 14:59:27 -    413712 items complete at 153.7/s\n",
 "12 Jan 15:01:43 -    413866 items complete at 143.5/s\n",
 "12 Jan 15:03:57 -    414009 items complete at 134.6/s\n",
 "12 Jan 15:06:13 -    414144 items complete at 126.6/s\n",
 "12 Jan 15:08:29 -    414271 items complete at 119.6/s\n",
 "12 Jan 15:10:42 -    414391 items complete at 113.3/s\n",
 "12 Jan 15:12:56 -    414504 items complete at 107.6/s\n",
 "12 Jan 15:15:10 -    414612 items complete at 102.4/s\n",
 "12 Jan 15:17:29 -    414714 items complete at 97.5/s\n",
 "12 Jan 15:19:39 -    414812 items complete at 93.3/s\n",
 "12 Jan 15:21:50 -    414905 items complete at 89.4/s\n",
 "12 Jan 15:24:04 -    414994 items complete at 85.7/s\n",
 "12 Jan 15:26:38 -    415080 items complete at 81.9/s\n",
 "12 Jan 15:28:57 -    415162 items complete at 78.6/s\n",
 "12 Jan 15:31:15 -    415241 items complete at 75.7/s\n",
 "12 Jan 15:33:27 -    415317 items complete at 73/s\n",
 "12 Jan 15:35:37 -    415390 items complete at 70.5/s\n",
 "12 Jan 15:37:51 -    415461 items complete at 68.1/s\n",
 "12 Jan 15:40:02 -    415529 items complete at 66/s\n",
 "12 Jan 15:42:15 -    415595 items complete at 63.9/s\n",
 "12 Jan 15:44:33 -    415659 items complete at 61.8/s\n",
 "12 Jan 15:47:04 -    415721 items complete at 59.7/s\n",
 "12 Jan 15:49:53 -    415781 items complete at 57.6/s\n",
 "12 Jan 15:52:40 -    415839 items complete at 55.6/s\n",
 "12 Jan 15:55:30 -    415895 items complete at 53.7/s\n",
 "12 Jan 15:58:20 -    415949 items complete at 51.9/s\n",
 "12 Jan 16:01:01 -    416001 items complete at 50.3/s\n",
 "12 Jan 16:03:47 -    416051 items complete at 48.7/s\n",
 "12 Jan 16:06:33 -    416100 items complete at 47.2/s\n",
 "12 Jan 16:09:26 -    416147 items complete at 45.8/s\n",
 "12 Jan 16:12:00 -    416193 items complete at 44.5/s\n",
 "12 Jan 16:14:27 -    416238 items complete at 43.4/s\n",
 "12 Jan 16:17:02 -    416281 items complete at 42.3/s\n",
 "12 Jan 16:19:38 -    416323 items complete at 41.2/s\n",
 "12 Jan 16:22:10 -    416364 items complete at 40.2/s\n",
 "12 Jan 16:24:44 -    416404 items complete at 39.2/s\n",
 "12 Jan 16:27:11 -    416443 items complete at 38.3/s\n",
 "12 Jan 16:29:42 -    416481 items complete at 37.4/s\n",
 "12 Jan 16:32:04 -    416518 items complete at 36.6/s\n",
 "12 Jan 16:34:31 -    416555 items complete at 35.8/s\n",
 "12 Jan 16:36:59 -    416591 items complete at 35/s\n",
 "12 Jan 16:39:24 -    416626 items complete at 34.3/s\n",
 "12 Jan 16:41:52 -    416660 items complete at 33.6/s\n",
 "12 Jan 16:44:17 -    416694 items complete at 32.9/s\n",
 "12 Jan 16:46:46 -    416727 items complete at 32.2/s\n",
 "12 Jan 16:49:16 -    416759 items complete at 31.6/s\n",
 "12 Jan 16:51:52 -    416791 items complete at 30.9/s\n",
 "12 Jan 16:54:23 -    416822 items complete at 30.3/s\n",
 "12 Jan 16:56:56 -    416852 items complete at 29.7/s\n",
 "12 Jan 16:59:33 -    416882 items complete at 29.1/s\n",
 "12 Jan 17:02:18 -    416911 items complete at 28.5/s\n",
 "12 Jan 17:04:56 -    416940 items complete at 28/s\n",
 "12 Jan 17:07:29 -    416968 items complete at 27.4/s\n",
 "12 Jan 17:09:59 -    416995 items complete at 26.9/s\n",
 "12 Jan 17:12:26 -    417022 items complete at 26.5/s\n",
 "12 Jan 17:14:51 -    417048 items complete at 26/s\n",
 "12 Jan 17:17:21 -    417074 items complete at 25.5/s\n",
 "12 Jan 17:19:48 -    417100 items complete at 25.1/s\n",
 "12 Jan 17:22:22 -    417125 items complete at 24.7/s\n",
 "12 Jan 17:24:56 -    417150 items complete at 24.2/s\n",
 "12 Jan 17:27:27 -    417174 items complete at 23.8/s\n",
 "12 Jan 17:29:59 -    417198 items complete at 23.4/s\n",
 "12 Jan 17:32:43 -    417221 items complete at 23/s\n",
 "12 Jan 17:35:22 -    417244 items complete at 22.6/s\n",
 "12 Jan 17:38:02 -    417267 items complete at 22.2/s\n",
 "12 Jan 17:40:36 -    417289 items complete at 21.9/s\n",
 "12 Jan 17:43:16 -    417311 items complete at 21.5/s\n",
 "12 Jan 17:45:52 -    417333 items complete at 21.2/s\n",
 "12 Jan 17:48:24 -    417354 items complete at 20.8/s\n",
 "12 Jan 17:50:55 -    417375 items complete at 20.5/s\n",
 "12 Jan 17:53:23 -    417396 items complete at 20.2/s\n",
 "12 Jan 17:55:56 -    417416 items complete at 19.9/s\n",
 "12 Jan 17:58:28 -    417436 items complete at 19.6/s\n",
 "12 Jan 18:00:59 -    417456 items complete at 19.3/s\n",
 "12 Jan 18:03:33 -    417475 items complete at 19/s\n",
 "12 Jan 18:06:13 -    417494 items complete at 18.7/s\n",
 "12 Jan 18:08:41 -    417513 items complete at 18.5/s\n",
 "12 Jan 18:11:14 -    417531 items complete at 18.2/s\n",
 "12 Jan 18:13:47 -    417549 items complete at 17.9/s\n",
 "12 Jan 18:16:29 -    417567 items complete at 17.7/s\n",
 "12 Jan 18:19:05 -    417585 items complete at 17.4/s\n",
 "12 Jan 18:21:40 -    417602 items complete at 17.2/s\n",
 "12 Jan 18:24:13 -    417619 items complete at 16.9/s\n",
 "12 Jan 18:26:53 -    417636 items complete at 16.7/s\n",
 "12 Jan 18:29:24 -    417653 items complete at 16.5/s\n",
 "12 Jan 18:31:49 -    417669 items complete at 16.2/s\n",
 "12 Jan 18:34:19 -    417685 items complete at 16/s\n",
 "12 Jan 18:37:00 -    417701 items complete at 15.8/s\n",
 "12 Jan 18:39:40 -    417717 items complete at 15.6/s\n",
 "12 Jan 18:42:23 -    417733 items complete at 15.4/s\n",
 "12 Jan 18:45:01 -    417748 items complete at 15.2/s\n",
 "12 Jan 18:47:39 -    417763 items complete at 15/s\n",
 "12 Jan 18:50:18 -    417778 items complete at 14.8/s\n",
 "12 Jan 18:53:01 -    417793 items complete at 14.6/s\n",
 "12 Jan 18:55:43 -    417808 items complete at 14.4/s\n",
 "12 Jan 18:58:25 -    417822 items complete at 14.2/s\n",
 "12 Jan 19:01:03 -    417836 items complete at 14/s\n",
 "12 Jan 19:03:44 -    417850 items complete at 13.8/s\n",
 "12 Jan 19:06:18 -    417864 items complete at 13.6/s\n",
 "12 Jan 19:08:54 -    417878 items complete at 13.5/s\n",
 "12 Jan 19:11:20 -    417891 items complete at 13.3/s\n",
 "12 Jan 19:13:46 -    417904 items complete at 13.1/s\n",
 "12 Jan 19:16:16 -    417917 items complete at 13/s\n",
 "12 Jan 19:18:49 -    417930 items complete at 12.8/s\n",
 "12 Jan 19:21:20 -    417943 items complete at 12.7/s\n",
 "12 Jan 19:23:53 -    417956 items complete at 12.5/s\n",
 "12 Jan 19:26:23 -    417969 items complete at 12.4/s\n",
 "12 Jan 19:28:58 -    417981 items complete at 12.2/s\n",
 "12 Jan 19:31:24 -    417993 items complete at 12.1/s\n",
 "12 Jan 19:33:49 -    418005 items complete at 11.9/s\n",
 "12 Jan 19:36:22 -    418017 items complete at 11.8/s\n",
 "12 Jan 19:38:47 -    418029 items complete at 11.7/s\n",
 "12 Jan 19:41:03 -    418041 items complete at 11.5/s\n",
 "12 Jan 19:43:18 -    418053 items complete at 11.4/s\n",
 "12 Jan 19:45:32 -    418064 items complete at 11.3/s\n",
 "12 Jan 19:47:42 -    418075 items complete at 11.2/s\n",
 "12 Jan 19:50:00 -    418086 items complete at 11/s\n",
 "12 Jan 19:52:11 -    418097 items complete at 10.9/s\n",
 "12 Jan 19:54:26 -    418108 items complete at 10.8/s\n",
 "12 Jan 19:56:42 -    418119 items complete at 10.7/s\n",
 "12 Jan 19:58:54 -    418130 items complete at 10.6/s\n",
 "12 Jan 20:01:08 -    418141 items complete at 10.5/s\n",
 "12 Jan 20:03:19 -    418151 items complete at 10.4/s\n",
 "12 Jan 20:05:31 -    418161 items complete at 10.3/s\n",
 "12 Jan 20:07:43 -    418171 items complete at 10.2/s\n",
 "12 Jan 20:09:53 -    418181 items complete at 10.1/s\n",
 "12 Jan 20:12:02 -    418191 items complete at 10/s\n",
 "12 Jan 20:14:12 -    418201 items complete at 9.9/s\n",
 "12 Jan 20:16:26 -    418211 items complete at 9.8/s\n",
 "12 Jan 20:18:37 -    418221 items complete at 9.7/s\n",
 "12 Jan 20:20:49 -    418231 items complete at 9.6/s\n",
 "12 Jan 20:22:59 -    418241 items complete at 9.5/s\n",
 "12 Jan 20:25:13 -    418250 items complete at 9.4/s\n",
 "12 Jan 20:27:24 -    418259 items complete at 9.3/s\n",
 "12 Jan 20:29:36 -    418268 items complete at 9.2/s\n",
 "12 Jan 20:31:46 -    418277 items complete at 9.1/s\n",
 "12 Jan 20:33:57 -    418286 items complete at 9/s\n",
 "12 Jan 20:36:10 -    418295 items complete at 8.9/s\n",
 "12 Jan 20:38:23 -    418304 items complete at 8.8/s\n",
 "12 Jan 20:40:35 -    418313 items complete at 8.7/s\n",
 "12 Jan 20:42:50 -    418322 items complete at 8.7/s\n",
 "12 Jan 20:45:08 -    418331 items complete at 8.6/s\n",
 "12 Jan 20:47:22 -    418340 items complete at 8.5/s\n",
 "12 Jan 20:49:36 -    418348 items complete at 8.4/s\n",
 "12 Jan 20:51:51 -    418356 items complete at 8.3/s\n",
 "12 Jan 20:54:08 -    418364 items complete at 8.2/s\n",
 "12 Jan 20:56:25 -    418372 items complete at 8.1/s\n",
