### ISSUE TITLE
Upgrade to Karma 6

### ISSUE THREAD

**Issue by jwhitlock** [taskcluster/taskcluster#4256]
[Karma 6.0.0](https://github.com/karma-runner/karma/blob/master/CHANGELOG.md#600-2021-01-13) has some dependency updates to fix CVEs, and also has some breaking changes that prevent a smooth upgrade. See PR #4253 for the failing tests.

Known issues:

* [karma-webpack](https://github.com/ryanclark/karma-webpack) uses dependency injection for ``customFileHandlers``, which is not supported in Karma 6.0.0 (but is in 6.0.1)

**Comment by jwhitlock** [comment]
[Karma 6.0.1](https://github.com/karma-runner/karma/blob/master/CHANGELOG.md#601-2021-01-20) added ``customFileHandlers`` back with a deprecation warning, due to plugins like ``karma-webpack`` needing to be updated to stop using it. Meanwhile, ``karma-webpack`` is working on a release that supports Karma 6, but hasn't committed to a release date.

**Comment by djmitche** [comment]
I think #4352 was that `karma-webpack` release, so maybe this is ready to go.

**Comment by jwhitlock** [comment]
Now we can install Karma 6.1.0, but not karma-webpack 5.0.0, which requires a webpack upgrade. I'm adding that to the existing webpack PR #4001.
