### ISSUE TITLE
Thread task.projectId through UI

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#4269]
* add projectId to web-server's Task entity
* add projectId to the default task-creator task, with a site-specific value
* show projectId in task inspector

**Comment by alopezz** [comment]
As discussed on matrix, we can do this at the same time as we update the UI for `taskQueueId`. I'm happy to take care of this once both #4271 and #4277 land.

**Comment by djmitche** [comment]
The UI is a bit wonky so please feel free to ask questions (noting that US people aren't around much todya)

**Comment by djmitche** [comment]
@alopezz I hope you don't mind, but I think I'll take this to wrap it up.

**Comment by alopezz** [comment]
OK, I've been busier than usual lately so I haven't even tried to start, so it's fine.
