### ISSUE TITLE
Allow setting the GitHub status context in .taskcluster.yml

### ISSUE THREAD

**Issue by jgraham** [taskcluster/taskcluster#43]
For wpt we have a situation where on some pushes we run multiple TaskCluster taskgroups with different settings (this is controlled by pushes to different branches). Unfortunately the way that the status API works in GitHub it will hide all but the latest run with a specific context name, making it hard fo figure out where to find all the results. This could be solved by giving the ability to override the context name for a specific set of tasks from the `.taskcluster.yml` file.

The main issue is presumably that this wants to be per repository, not per task, so one ends up duplicating some of the task logic to set the right context for each event.

**Comment by djmitche** [comment]
Closing this as status-specific..
