### ISSUE TITLE
quarantine metadata / comment

### ISSUE THREAD

**Issue by escapewindow** [taskcluster/taskcluster#4343]
In [bug 1689822](https://bugzilla.mozilla.org/show_bug.cgi?id=1689822), we had machines quarantined that shouldn't have been. We don't know who quarantined a machine, when, or why, just if it's quarantined, and the time it will come out of quarantine.

Can we:
- add metadata to the quarantine UI: who quarantined and when? (If we don't store this info, then we may need to update the backend as well)
- add metadata to the backend+UI: a comment and/or why section. I imagine being able to query for this information through the api would be good for both the UI and for people looking to generate reports.

This isn't actively blocking any priority task, but resolving this issue would help us maintain hardware or other long-lived pools.

**Comment by lotas** [comment]
This was deployed to community-tc
