### ISSUE TITLE
Log viewer no longer jumps to lines

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#4364]
STR:
 * Go to https://community-tc.services.mozilla.com/tasks/GhfdBxW-T36lNB-15u8jcg/runs/0/logs/public/logs/live.log
 * search for "FAIL:"
 * click the line that failed

Expected: shows all log lines around that line

Actual: jumps to the first line of the logs

**Comment by rajatgupta24** [comment]
Hi @djmitche I'm new here and like to work on this, i guess i understood the problem 
I search FAIL as you can see in screenshot
![image](https://user-images.githubusercontent.com/55191777/107397274-850abc00-6b24-11eb-8707-0f4c8435277b.png)

and enter the line i want to go but that didn't take me to the line 
![image](https://user-images.githubusercontent.com/55191777/107397348-95bb3200-6b24-11eb-834a-45409ede11a5.png)

**Comment by djmitche** [comment]
Ah, good job spotting that "go to line number" doesn't work, either.  Now, the next step is "why?"  (and I don't know the answer!)

**Comment by djmitche** [comment]
@rajatgupta24 how is this going?

**Comment by rajatgupta24** [comment]
Sorry @djmitche but I couldn't figure out what causes this to happen.

**Comment by djmitche** [comment]
OK!  I don't know either, so we're together in that :)

**Comment by jwhitlock** [comment]
These both worked for me, in Safari 14 and Firefox 90 Dev Edition:
* Search for `FAIL:`, click on result, go to that line 13357
* Click "123" button, enter line 10000, go to that line

Maybe this was fixed by an unrelated update? I'll close on confirmation by another user, or after a few days.

**Comment by jwhitlock** [comment]
Tried again today, and it worked. Thanks, mystery update!
