### ISSUE TITLE
Clicking on roles does not go to the role

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#4377]
STR:
 * Open the "Authorization" -> "Roles" view
 * Click on a role

Expected: go to the role view

Actual: nothing but a Material-UI ripple

![bug](https://user-images.githubusercontent.com/28673/107246707-83df6f00-69fe-11eb-9d8b-47fa54e9c51c.png)

**Comment by rbrishabh** [comment]
Hi @djmitche! Mind if I take a look on this one next?

**Comment by djmitche** [comment]
I think @joeyouss is working on this one, per the #taskcluster channel on chat.mozilla.org.

**Comment by rbrishabh** [comment]
Okay! Is there anything else I can help with? @djmitche, feel free to tag me on that issue! :)

**Comment by joeyouss** [comment]
> I think @joeyouss is working on this one, per the #taskcluster channel on chat.mozilla.org.

Thank you. I will start working on it

**Comment by djmitche** [comment]
@mrsVelena has fixed this up in the process of addressing bug 2393 (where it was introduced).

@joeyouss sorry about that!  Please let me know if you need a hand finding another issue..

**Comment by joeyouss** [comment]
Hey ! Sure i had my exams so couldn't do it. I still have it for a few days. Let me know what issue would be okay

**Comment by djmitche** [comment]
https://codetribute.mozilla.org/projects/taskcluster is a good place to start looking for issues
