### ISSUE TITLE
Begin every docs page with its title in a header

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#439]
The old site begins each page with an `h1` containing its title.  The new site does not, since that title appears in the navigation bar.  But that means that most pages just jump right in with a paragraph, lacking the visual context of the heading.  Let's consider adding the heading back in.

**Comment by helfi92** [comment]
STR:

1. Navigate to https://taskcluster-web.netlify.com/docs/reference/platform/auth/docs/clients

**Expected**: There is a title "Clients" below the blue app bar

**Actual**: There is no title below the blue app bar

<img width="898" alt="Screen Shot 2019-03-15 at 11 17 29 PM" src="https://user-images.githubusercontent.com/3766511/54470079-85ec1500-4778-11e9-806e-d444e6c52bcd.png">

**Comment by littlebobby** [comment]
hey, can I work on this issue as my first contribution? To clarify, I just need to add a `h1` title back to the main contents, and there is no need to remove the one showing in the `app bar`. Am I right?

**Comment by djmitche** [comment]
That's right!  Once you accept the invitation to this repository, let me know here and I'll assign the issue to you.

**Comment by littlebobby** [comment]
hey, I accepted just now. Thank you for your invitation!

**Comment by helfi92** [comment]
Resolved in https://github.com/taskcluster/taskcluster/commit/e5bbac637806fcd917c154409c8728780e6e629f.
