### ISSUE TITLE
Residual images need to be deleted in the case of failure

### ISSUE THREAD

**Issue by owlishDeveloper** [taskcluster/taskcluster#44]
I noticed that if the build process fails (in particular, it seems to be a concern for a process where we install things on an image) the residual image is left on the disk. It lacks tags, and looks like just a copy of a base image. I think these are best be deleted in case of failure

(Example - building tools service. If the installation of nginx on a node image fails, we are left with an untagged copy of the original node image)

**Comment by djmitche** [comment]
Can you give an example of this?  It sounds like intermediate images from the build process are left over?  I'm not sure how to clean those up, since we don't ever see the id for them..

**Comment by owlishDeveloper** [comment]
>  It sounds like intermediate images from the build process are left over?

Yep. I don't remember the specific example at the moment... But the id could definitely be seen by running `docker images` command

**Comment by djmitche** [comment]
I *think* this will be fixed when we're just building one image.  The overall 'docker build' command, though, creates intermediate images as it runs.  I don't think there's any way to cancel an ongoing docker-build command, though.  I'm not sure we could ever fix this...
