### ISSUE TITLE
Add deployment documentation

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#441]
Let's get started with some documentation on how to deploy taskcluster.  For the moment, that can mostly refer to the terraform as authoritative.

**Comment by djmitche** [comment]
I think this will wait a few weeks until we've worked out the new deployment process that is compatbile with cloudops /cc @edunham and @imbstack

**Comment by nowaktz** [comment]
A few weeks already passed :wink:
Was there any progress?

**Comment by djmitche** [comment]
Ah, I forgot I'd filed this issue -- we now have [deployment docs!](https://docs.taskcluster.net/docs/manual/deploying/)

Are you looking for such documentation, or for an issue to work on?

**Comment by nowaktz** [comment]
Thanks! I'm looking for a simple way to deploy Taskcluster with TreeHerder and other services (e.g. [MinIO](https://github.com/minio/minio) in place of AWS S3, and simple local RabbitMQ cluster) necessary to bootstrap an experimental build/test/deploy pipeline.

Any chance that you have such a recipe?

**Comment by djmitche** [comment]
Cool!  https://lists.mozilla.org/listinfo/tools-taskcluster would be a good place to discuss that.  I don't know too much about deploying treeherder, but as far as Taskcluster things should be relatively straightforward as long as you've got a Kubernetes environment to put it in.

As far as clouds:
 * AWS is used for artifact storage.  I suspect that some minor patches could make that work with minio.  We have an ["Object Service"](https://github.com/taskcluster/taskcluster-rfcs/blob/master/rfcs/0120-artifact-service.md) proposed but not yet implemented that would support pluggable storage backends.
 * We support automatic provisioning of workers on AWS and GCP, as well as "manual" deployment anywhere you'd like (but without dynamic provisioning).  Worker-manager has a nice model for pluggable dynamic provisioning backends, so if you wanted to use, say, DigitalOcean or an on-prem cloud, you could potentially implement that and we'd be happy to see it upstreamed.
 * We use Azure tables and blob storage as the services' data backend.  We're hoping to move to Postgres, but that project is not begun yet.  So at the moment you'll pretty much have to have an Azure account.
 * A RabbitMQ deployment will be fine.

You can find more docs -- admittedly partial -- on deploying TC at https://docs.taskcluster.net/docs/manual/deploying/.

**Comment by djmitche** [comment]
Oh, haha, I'd already linked to that :)
