### ISSUE TITLE
Add support for uploading and downloading to the Python clients

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#4424]

**Comment by djmitche** [comment]
@escapewindow, @jwhitlock can I get your 10% review on https://github.com/taskcluster/taskcluster/compare/main...djmitche:issue4424?  Specifically around the "reader", "writer", and "factory" thing -- is there already something like that which I'm missing in the async Python world?

**Comment by jwhitlock** [comment]
I don't have much practical experience with asyncio, so I don't feel too confident giving advice. Most of what I know comes from Brad Solomon's [Async IO in Python: A Complete Walkthrough](https://realpython.com/async-io-python/#using-a-queue), and the last section has a list of [libraries that work with async/await](https://realpython.com/async-io-python/#libraries-that-work-with-asyncawait). You've already found ``aiohttp``.

[aiofiles](https://github.com/Tinche/aiofiles) wraps file I/O operations in async. It does this by running the blocking file I/O in a thread, which appears to be the standard, supported technique for getting code like this into async. I haven't had a chance to use it yet. The project appears active, and not too clever.

I think you'll need something similar, like [run_in_executor](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor), to keep local file operations from blocking, or just try ``aiofiles``.

I'm excited to see some async Python code in the real world!

**Comment by djmitche** [comment]
Thanks!  I think aiofiles.File would satisfy the "writer" and "reader" definitions, so that may be a drop-in fit without requiring any additional dependency.  I could add a test dependency on that library and verify that, and then document how to use it.

In the cold light of Monday morning, I realize that the "factory" instances are probably overkill and I could just require callables.  For factories that need to track state, it's easy enough to use a closure or a class with `__call__`.  So, I'll refactor that a bit.

**Comment by escapewindow** [comment]
You have comments about my two main points. I *think* with your `asyncio.gather` call, you're basically eating exceptions and not detecting them. And similarly, if we can detect exceptions, we should be able to specify retry parameters.

There's a [`retry_async`](https://github.com/mozilla-releng/scriptworker/blob/master/src/scriptworker/utils.py#L223-L267) and [`raise_future_exceptions` / `get_results_and_future_exceptions`](https://github.com/mozilla-releng/scriptworker/blob/master/src/scriptworker/utils.py#L383-L443) in scriptworker that may be useful.

**Comment by djmitche** [comment]
Ah, thanks, I misunderstood the meaning of `gather(.. return_exceptions)`.  I'll try to catch that error with some tests :)

**Comment by djmitche** [comment]
I had also missed `resp.raise_for_status` everywhere!  Tests FTW :)
