### ISSUE TITLE
Show task status in hook last-fired component

### ISSUE THREAD

**Issue by calixteman** [taskcluster/taskcluster#4426]
For example:
https://firefox-ci-tc.services.mozilla.com/hooks/project-relman/bugzilla-dashboard-backend-production

`Fire status` is green but the task failed and so the UI gives the impress that everything fine when it isn't.
So it would be nice to add a thing to give the status of the task itself in the main UI.

**Comment by djmitche** [comment]
The "fire status" is the result of *creating* the task, so it's valid and useful information, but you're right that it would also be useful to see how the task was executed in this UI.  Title updated :)

**Comment by lotas** [comment]
this was implemented already, closing
