### ISSUE TITLE
Update all docs links in the UI, docs

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#443]
Lots of links are currently pointing to `https://docs.taskcluster.net` or possibly to pages that are no longer present.  Let's make a sweep and update those all to be internal links.

**Comment by sudipt1999** [comment]
Can I work on this !

**Comment by djmitche** [comment]
Yep, that sounds like about it!  Anything linking directly to a `taskcluster.net` hostname needs to get changed.

**Comment by sudipt1999** [comment]
Changed to internal `readme` files!

**Comment by djmitche** [comment]
Note that you may want to wait for #476 to land before getting too into this -- it moves a lot of files around!

**Comment by sudipt1999** [comment]
I guess that the only way, since all the docs are being moved to `ui/docs` also #444 is related to this bug only so I need to wait a little! Thank you

**Comment by djmitche** [comment]
Yes, that work was blocking a lot of other things so I prioritized it.  Soon!

**Comment by djmitche** [comment]
@allcontributors please add @sudipt1999 for code

**Comment by sudipt1999** [comment]
Since pr #476 has been merged, I will start working on it!

**Comment by helfi92** [comment]
I believe this is done :)
