### ISSUE TITLE
Builder needs a retry

### ISSUE THREAD

**Issue by owlishDeveloper** [taskcluster/taskcluster#45]
While working on a project where I had to use builder frequently, I noticed that sometimes the creation of an image fails for some relatively force majeure reasons (like connectivity problems during `npm install` etc). When restarted with no changes made, the builder is usually able to complete the build. So I thought that it would be great if the builder could restart the failed build on its own, at least a couple of times, so that I don't have to watch it too closely.

Also, it would be great if it could happily skip things after the third failed retry, so that the maximum possible amount of images could be built without human intervention.

**Comment by djmitche** [comment]
Let's handle this in https://bugzilla.mozilla.org/show_bug.cgi?id=1551607.
