### ISSUE TITLE
Tasks aren't generated for github events unless .taskcluster.yml exists in main branch

### ISSUE THREAD

**Issue by jschwartzentruber** [taskcluster/taskcluster#4502]
**Describe the bug**

I opened [a PR](https://github.com/MozillaSecurity/prefpicker/pull/16) to move https://github.com/MozillaSecurity/prefpicker/ CI from Travis CI to Taskcluster (community-tc). The initial branch push (https://github.com/MozillaSecurity/prefpicker/pull/16/commits/9d952af6dc95430c9ad8adae6cb97d1f807608a0) did generate a push task, but subsequent pushes in the same branch generated no tasks. No PR tasks were ever generated.

**To Reproduce**

1. Create a PR to add .taskcluster.yml to a repo that has none
2. Push another commit to the PR branch
3. See that tasks are created for step 1 but not step 2

**Expected behavior**

* Push/release tasks should be generated for any branch that contains .taskcluster.yml
* PR tasks should be generated for any branch where the head (branch to be merged) contains .taskcluster.yml (and author meets collaborator policy).

**Taskcluster version**
41.0.2

**Screenshots**
![image](https://user-images.githubusercontent.com/4673461/109869741-3fc73f00-7c37-11eb-9fc1-5f8af73db643.png)

**Comment by jschwartzentruber** [comment]
I should mention that the force-push shown was only to try to trigger tasks to run.  `c1653bd` and `8702b14` are identical commits and neither triggered tasks.

**Comment by jschwartzentruber** [comment]
Adding a dummy taskcluster.yml to the main branch didn't help. Is it possibly using the base/before ref to get .taskcluster.yml and not the head/after ref?

https://github.com/MozillaSecurity/prefpicker/commit/a52d6af9032fc5f00fbbfee4bf147a7e6737216c

The PR was rebased on that, and still no tasks.

**Comment by imbstack** [comment]
I _think_ this is actually another issue where the .tc.yml was invalid in this case but we weren't commenting because the way it was invalid was happening outside of our try/catch. I'll have a PR up shortly for this

**Comment by jschwartzentruber** [comment]
Is the tc.yml invalid though? It passes schema validation using https://github.com/marco-c/taskcluster_yml_validator/, and I can copy/create the task manually with the ui.

**Comment by jschwartzentruber** [comment]
This is still occurring (eg here: https://github.com/MozillaSecurity/prefpicker/commit/45ec76f803e285b0a5a1ddbdd435d4c0f916ea11).

Now I see the TC error, but it doesn't appear related to my tc.yml as we suspected. It's a different error message from #4517.

**Comment by djmitche** [comment]
I think the issue is that the `.taskcluster.yml` is generating an array of tasks directly, rather than an array of `{taskId: .., task: ..}`.  A test render gives:

```
version: 1
policy: ..
tasks:
  - taskId: ...
    provisionerId: ..
    workerType: ..
```
instead of
```
version: 1
policy: ..
tasks:
  - taskId: ...
    task:
      provisionerId: ..
      workerType: ..
```

Admittedly, that's a terrible error message for that issue!

**Comment by djmitche** [comment]
I'm totally off-base there -- please ignore.

**Comment by djmitche** [comment]
(I got there looking for `/.task\>/` and the source-code mislead me.

**Comment by djmitche** [comment]
OK, looks like I tracked it down.  We do a topological sort of the tasks, using dependencies. But since there's a dependency on `NmOU83KwRJGjk-btMbOOPA`, that's not one of the new tasks, the topological sort ends up including an `undefined` task.  Which causes the failure.
