### ISSUE TITLE
task demotion causes older task to get mapped to 'latest'

### ISSUE THREAD

**Issue by Archaeopteryx** [taskcluster/taskcluster#4515]
**Describe the bug**
A demotion of a task in its task definition (e.g. 'Bugzilla' task from tier 1 to tier 2 in [bug 1691479](https://bugzilla.mozilla.org/show_bug.cgi?id=1691479)) stops the 'latest' index from updating.
https://firefox-ci-tc.services.mozilla.com/tasks/index/gecko.v2.mozilla-central.latest.source/source-bugzilla-info points to https://firefox-ci-tc.services.mozilla.com/tasks/Fr-fdBouSq2u85sKOAswOg when it still ran as tier 1.

**Expected**
'Latest' task is from the latest push with a successful task of its kind (and uses the latest successful task from that push).

* [source](https://searchfox.org/mozilla-central/rev/44695ef057e422a8d6c6056972bdf32766c36187/taskcluster/taskgraph/transforms/task.py#1714-1722)
* implemented in [bug 1304019](https://bugzilla.mozilla.org/show_bug.cgi?id=1304019)
* documentation for [task rank](https://docs.taskcluster.net/docs/reference/core/index#task-rank)

**Comment by djmitche** [comment]
The index is doing what it promises here, so there's no TC bug to fix.  If this should truly be "latest", then the rank should be a timestamp or some other monotonic value, regardless of tier.  I assume the tier-related logic is there to solve a different problem :)

I think the right fix here is to delete the existing index entry.  Unfortunately, there is no "delete" option, but calling `insertTask` with a short expiration time and a rank higher than the current rank should do the trick.

I moved an existing bug to #4516 to add a delete method, but don't wait for that to land to address this issue.

**Comment by Archaeopteryx** [comment]
Can you run the `insertTask` call, please? I have only scopes for `index:insert-task:gecko.v2.try.*` and tried to replace it with https://firefox-ci-tc.services.mozilla.com/tasks/HFgsz9BOSWKXpN9FZibclA

**Comment by djmitche** [comment]
I don't have the scopes, either :( -- release engineering has all the scopes for that deployment.
