### ISSUE TITLE
Github decision raises "Cannot read property 'taskId' of undefined"

### ISSUE THREAD

**Issue by jschwartzentruber** [taskcluster/taskcluster#4517]
**Describe the bug**

When pushing a [tagged commit](https://github.com/MozillaSecurity/prefpicker/commit/2d0139c3379fcbb052f0f4c10d85cc0b272b7fb1) to Github and creating a GH release, 3 task groups are created by [our configuration](https://github.com/MozillaSecurity/prefpicker/blob/2d0139c3379fcbb052f0f4c10d85cc0b272b7fb1/.taskcluster.yml):
1. [**push**](https://community-tc.services.mozilla.com/tasks/groups/f1FwTSReTyWtt2x_R9uiFw): `py35`, `py36`, `py37`, `py38`, `py39`, `lint`
2. [**tag**](https://community-tc.services.mozilla.com/tasks/groups/TuK05HrKS1-Lep9V7PqGJw): `py35`, `py36`, `py37`, `py38`, `py39`, `lint`
3. [**release**](https://community-tc.services.mozilla.com/tasks/groups/YftCOQVHQ22Ig1awp-BjRA): `py35`, `py36`, `py37`, `py38`, `py39`, `lint`, `release`

The first 6 tasks in each group are created by a json-e `map`, so are identical between all tasks groups. Yet we are seeing an error only in the **release** task group, where `py39`, `lint`, and `release` tasks fail to be created with the message: `"Cannot read property 'taskId' of undefined"`

**To Reproduce**
This was happening consistently when the `py38-win` task in [the configuration](https://github.com/MozillaSecurity/prefpicker/blob/2d0139c3379fcbb052f0f4c10d85cc0b272b7fb1/.taskcluster.yml#L43) was enabled, but was hidden until #4504 surfaced the error. But now different lines in the Linux task `map` are raising (or not) with no other variation, so I don't think this has anything to do with the `.taskcluster.yml`. If it is related to our configuration, the error is too vague to identify the underlying issue.

**Expected behavior**
All tasks in group should be created, or an error surfaced as to why task creation failed.

**Taskcluster version**
41.0.2

**Platform**
github

**Additional context**
Originally filed as #4502 before #4504 surfaced the error.

**Comment by djmitche** [comment]
I *think* this was addressed in #4504, if I understand comments in #4502 correctly.

**Comment by jschwartzentruber** [comment]
I opened this after #4504, but I think this is a different problem. In this case, the `release` task above had a non-existent dependency, where the task definition was commented out [here](https://github.com/MozillaSecurity/prefpicker/blob/2d0139c3379fcbb052f0f4c10d85cc0b272b7fb1/.taskcluster.yml#L43), but the slug was still used as a dependency [here](https://github.com/MozillaSecurity/prefpicker/blob/2d0139c3379fcbb052f0f4c10d85cc0b272b7fb1/.taskcluster.yml#L141).

Although the error does make sense here, it doesn't point to where the problem is in the tc.yml. I would have expected the `release` task to be created but never scheduled (since one dependency doesn't exist) or to get a specific error message that there's an unknown task listed in dependencies.

**Comment by djmitche** [comment]
With the change in #4538, this will result in an error from the queue complaining that a dependency doesn't exist.  Prior to that PR, tc-github would choke (with the useless error message in the title of this issue) on such a configuration before passing it to the queue.  I think this is the best we can do -- the queue knows which tasks exist and which do not, so it should be the one to produce that error message.
