### ISSUE TITLE
[UI] show git version somewhere out of the way

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#453]
We have `.git-version` in the root of the repository, when taskcluster is deployed.  We currently use that in logging to indicate which version of Taskcluster we're running.  As we get more and more deployments running, it would be helpful to have that visible somewhere in the UI as well so that users can report the version they're running.  @helfi92 what do you think would be most appropriate way to do this?  Random ideas from me:
 * ``console.log(`Taskcluster version ${gitVersion}`)`` on load
 * display it in a small font at the bottom of the navigation drawer
 * on a new "About Taskcluster" page

Also, note that `.git-version` may not always exist (such as when running locally), so the implementation should be able to handle an undefined value.

**Comment by helfi92** [comment]
Out of curiosity, why do we put the version of Taskcluster in a file named `.git-version` instead of something like `.taskcluster-version`?

Having it below the application name sounds good to me:

![Screen Shot 2019-03-18 at 11 48 57 AM](https://user-images.githubusercontent.com/3766511/54543344-e09d9080-4973-11e9-873f-1f79f47ea691.png)

**Comment by djmitche** [comment]
We could change the filename.  I don't think there's any particular reason for that name.

**Comment by iFlameing** [comment]
@djmitche can you assign me this?

**Comment by djmitche** [comment]
I need to invite you to the org first.  Once you've accepted, let me know and I will assign.

**Comment by djmitche** [comment]
Oops, I don't have my Github password with me.  @helfi92 any chance you could invite @iFlameing?  Otherwise I will in the next day.

**Comment by helfi92** [comment]
Invitation sent.

**Comment by iFlameing** [comment]
@djmitche accepted the invitation.

**Comment by djmitche** [comment]
Thanks hassan :)

**Comment by iFlameing** [comment]
@djmitche where I can see the prototype of .git-version file?

**Comment by djmitche** [comment]
You can see what the running docker image looks like with
```
docker run -ti --rm taskcluster/taskcluster-monoimage:SVC-8c70f90225ae bash
```
and you'll see the file in `/app`.

**Comment by helfi92** [comment]
@allcontributors[bot] please add @iFlameing  for code!

**Comment by iFlameing** [comment]
When I run the above command, I successfully pull the image but when I am running the command in bash i.e(
bash-4.4#  /app .
bash: /app: Is a directory
)

I got the following error. what should I do now?

**Comment by djmitche** [comment]
Right, is is a directory.  It has a file in it, named `.git-version` :)

**Comment by iFlameing** [comment]
I have to just include this string below the application name right?

**Comment by djmitche** [comment]
Yes.  I'll defer to @helfi92 as to exactly how to format it.

**Comment by helfi92** [comment]
👋 Having the version number displayed in the bottom of the navigation drawer sounds good to me. See the purple box in the screenshot below. Thanks!

<img width="366" alt="Screen Shot 2019-04-21 at 3 04 53 PM" src="https://user-images.githubusercontent.com/3766511/56474394-19cf9180-6447-11e9-95b7-ae979e18fc51.png">

**Comment by iFlameing** [comment]
@helfi92 I found that we can use [Filereader](https://developer.mozilla.org/en-US/docs/Web/API/FileReader) to read the .git-version file and output the App version to the pink area. can you please! tell me if I am in the right direction or not?

**Comment by helfi92** [comment]
You could probably use the `import` statement. Something like https://github.com/taskcluster/taskcluster/blob/47e624812b715d30fdee85f046df1b440ef05992/ui/src/views/Documentation/index.jsx#L116.

**Comment by iFlameing** [comment]
@helfi92 when I am importing the .git-version as you suggested above. I am getting this error, I am not able to understand it.

```Javascript
ERROR in ../.git-version 1:7
Module parse failed: Identifier directly after number (1:7)
You may need an appropriate loader to handle this file type.
> 8026691dab4045166c5a1798f3c7661ee622da4e
```

**Comment by helfi92** [comment]
Can you share the code you are trying to use, please?

**Comment by iFlameing** [comment]
You can see the modified code at https://pastebin.com/f201BqdK

**Comment by helfi92** [comment]
Can you show me what files are being modified? I think if you do `git diff | pbcopy` in your terminal and paste the code here, then It'll do.

**Comment by iFlameing** [comment]
diff --git a/ui/src/components/Dashboard/index.jsx b/ui/src/components/Dashboard/index.jsx
index 0dda7b9..c6a386e 100644

```bash
--- a/ui/src/components/Dashboard/index.jsx
+++ b/ui/src/components/Dashboard/index.jsx
@@ -188,8 +188,24 @@ export default class Dashboard extends Component {
     navOpen: false,
     showHelpView: false,
     error: null,
 +   versionNumber: null,
   };
 
+  componentDidMount() {
+    this.load();
+  }
+
+  async load() {
+    try {
+      const versionNumber = await import(`../../../../.git-version`);
+
+      this.setState({ versionNumber });
+    } catch (error) {
+      // eslint-disable-next-line no-console
+      console.log(error);
+    }
+  }
+

```

**Comment by helfi92** [comment]
Ah, this is probably because webpack was not told how to import a file as a string. You can do:

```bash
# run this command inside the `ui` directory
yarn add -D raw-loader
```

Then add the following diff in `.neutrinorc.js`

```diff
diff --git a/ui/.neutrinorc.js b/ui/.neutrinorc.js
index c44eba665..599284fc9 100644
--- a/ui/.neutrinorc.js
+++ b/ui/.neutrinorc.js
@@ -153,6 +153,11 @@ module.exports = {
           .use('json-loader')
             .loader('json-loader');
 
+      neutrino.config.module
+        .rule('git-version')
+          .test(/\.git-version$/)
+          .use('raw-loader')
+            .loader('raw-loader');
     },
     (neutrino) => {
       neutrino.config.resolve
```

**Comment by iFlameing** [comment]
@helfi92 I am stuck at a position where I can't figure out how I can handle the error if .git-version file not present in a directory. I searched a lot but didn't find any solution. currently, when I am deleting the .git-version file it shows me this error:- 
```bash
ERROR in ../.git-version
Module build failed (from ./node_modules/raw-loader/dist/cjs.js):
Error: ENOENT: no such file or directory, open '/home/iflameing/Documents/github/taskcluster/.git-version'
```
can you provide me some link from where I can learn it :) 
after implementing your changes as you suggested the drawer looks like this
![Screenshot from 2019-05-01 23-14-09](https://user-images.githubusercontent.com/33936987/57032460-0f43a200-6c68-11e9-998f-9020f5ec298f.jpg)

**Comment by helfi92** [comment]
Could you push your changes, please? That way I can take a look at the error on my machine.

**Comment by helfi92** [comment]
@djmitche 

> Also, note that .git-version may not always exist (such as when running locally), so the implementation should be able to handle an undefined value.

Right now importing a file that doesn't exist causes webpack to throw. @djmitche Would it be possible to either:
1. Rename `.git-version` to `git-version` or `taskcluster-version`. `require.context` excludes dot files so it's hard to check if the file exist.
2. Put `.git-version` in a parent directory e.g., `meta`. In webpack's build process, when webpack is not sure whether a file exists or not, it will minify the full directory. Having `.git-version` in its own directory will make sure webpack doesn't minify all of the files.

I like the first approach but I'm open to the second. Thoughts?

**Comment by djmitche** [comment]
Renaming is fine, but note that the file is used by `taskcluster-lib-monitor` as well, so you'll need to make sure that still works properly, as well as changing the `yarn build` process that creates the file.

**Comment by helfi92** [comment]
Resolved in https://github.com/taskcluster/taskcluster/commit/4f068930c5e87fc6c3f208b42e60f7204f063079.
