### ISSUE TITLE
client-shell: Support completions for other shells

### ISSUE THREAD

**Issue by ahal** [taskcluster/taskcluster#4534]
It looks like cobra supports command completions for `bash`, `zsh`, `fish` and `PowerShell` out of the box:
https://github.com/spf13/cobra/blob/master/shell_completions.md

But `taskcluster-cli completions` only supports `bash`. Would be awesome if we could hook up cobra's default completion command here instead.

**Comment by samihda** [comment]
@djmitche I created a PR to address this, please have a look.
