### ISSUE TITLE
[UI] provide a universal schema viewer

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#459]
Sometimes I just want to link to a particular schema or sub-schema, rather than finding a documentation page that includes that schema.

Let's add a "Schema Index" to the docs page, that lists all schemas in the references by their `$id` and displays the selected schema.

**Comment by arshadkazmi42** [comment]
@djmitche I would like to take this up, can you share some more details about this issue

**Comment by djmitche** [comment]
Awesome!

If you look on a page like [auth api docs](https://docs.taskcluster.net/docs/reference/platform/auth/api#client), you'll see a schema (under "Response Payload" in this case).  This is a [JSON schema](http://json-schema.org/) and comes from [the JS source](https://github.com/taskcluster/taskcluster/blob/master/services/auth/schemas/v1/get-client-response.yml).  We have *lots* of schemas.

Each JSON schema has an `$id` that identifies it.  If you click "show source" under "Response Payload" you can see the raw schema, and it starts with:

```
{
  "$id": "/schemas/auth/v1/get-client-response.json#",
```

Right now, the only way to find a schema is to look at an API method or Pulse exchange that links to it.  So this bug suggests adding a new page ("Schema Index") to the reference section that lists all schemas by their `$id`, each with a link to a view of that schema's contents.

If you have a look at how schemas are rendered now, you'll see that all schemas for the entire Taskcluster deployment are stored in a single data structure that's already loaded in memory -- so there's not even any need to fetch data from tc-web-server to render this view.

Let me know if you have more questions!

**Comment by arshadkazmi42** [comment]
Any suggestions for any `ListComponent` which I can use to render this?

**Comment by arshadkazmi42** [comment]
Should we make the page UI similar to this page?
https://docs.taskcluster.net/docs/reference/platform/queue/task-schema

**Comment by helfi92** [comment]
> Should we make the page UI similar to this page?
https://docs.taskcluster.net/docs/reference/platform/queue/task-schema

Given that we will have a lot of schemas to display, we can put each schema in a panel. Something like https://taskcluster-web.netlify.com/docs/reference/platform/auth/api.

> I was looking through the code and the structure of docs.
I found this file
https://github.com/taskcluster/taskcluster/blob/master/generated/docs-table-of-contents.json
Do we have to add new page details in this file, or its auto-generated file and details need to be configured somewhere else?

The only thing that will be required is to run `yarn generate` in the root directory of the monorepo. `yarn generate` will inspect the contents of `ui/docs` and update the table of contents file.

**Comment by arshadkazmi42** [comment]
> If you have a look at how schemas are rendered now, you'll see that all schemas for the entire Taskcluster deployment are stored in a single data structure that's already loaded in memory -- so there's not even any need to fetch data from tc-web-server to render this view.

Where can I find the loaded data structure? If I want to access the loaded data in a component?

**Comment by helfi92** [comment]
The references files is auto generated so it will be under the `generated` directory. https://github.com/taskcluster/taskcluster/blob/master/generated/references.json
