### ISSUE TITLE
 Stop using gopkg.in/tylerb/graceful.v1

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#4594]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1581546 for background.

**Comment by marti1125** [comment]
Hi @djmitche I would like to take this issue 😃

**Comment by djmitche** [comment]
Great!  This requires a bit of familiarity with http servers in Go.  I would start by:

* Looking at the current use of this package to see how it's used.  
* Find another way to implement that functionality
  * Maybe it's not necessary at all!
  * Maybe there's another package that does something similar
  * Maybe this package is simple enough that the necessary functionality can be re-implemented within Taskcluster

**Comment by marti1125** [comment]
Is this lib? https://github.com/tylerstillwater/graceful
I would like to recommend to you https://github.com/gorilla/mux
I used in microservices

**Comment by djmitche** [comment]
That's the one, yes!

**Comment by marti1125** [comment]
Could you share me the instructions for get start with the project, please?

**Comment by djmitche** [comment]
Sure, it's [here](https://github.com/taskcluster/taskcluster/blob/main/dev-docs/development-process.md).  You can focus on the Go bits for this particular task, so basically clone the repo and run `go test ./clients/client-shell/...`.

**Comment by marti1125** [comment]
Hi @djmitche I made a PR. status: WIP. Could you check my progress? and How to I could test it?
https://github.com/taskcluster/taskcluster/pull/4627

**Comment by samihda** [comment]
Looks like this is still open, and there hasn't been any activity for a while.

I just took the liberty of opening a new PR linked above, if only for my own exercise. I believe it should serve our purpose here (without making a lot of changes), but let me know what you think in any case @djmitche.

**Comment by djmitche** [comment]
Nice!  Thanks for jumping into this issue -- and, nice fix!
