### ISSUE TITLE
[generic-worker] Support headless

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#4595]
See
* https://bugzilla.mozilla.org/show_bug.cgi?id=1588799
* https://bugzilla.mozilla.org/show_bug.cgi?id=1609102

**Comment by petemoore** [comment]
Note, I started work on this in #4268 but didn't complete it. It may be a useful reference for anybody that tackles this in future.

**Comment by aerickson** [comment]
Both linked Bugzillas are closed. Is this really done?
