### ISSUE TITLE
Make the `__heartbeat__` service endpoint verify backend services

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#4597]
https://bugzilla.mozilla.org/show_bug.cgi?id=1588145

Maybe we can build some kind of simple plugin-registration thing in tc-lib-app or tc-lib-api that will allow various other libraries (tc-lib-postgres, tc-lib-pulse, and maybe service-specific things like clouds) to feed info into the heartbeat.

**Comment by mostlygeek** [comment]
This may have been closed by issue PR #2575.  However: 

- the `__lbheartbeat__` is implemented appropriately.  Just returns an `HTTP 200` no matter what. 
- The `__version__/` appears to be reusable, as long as a `const taskclusterVersionFile = path.resolve(rootdir.get(), 'version.json');` exists
- the `/__heartbeat__` always returns a 200.   The intent of heartbeat is to encode checking logic to ensure the service is operating as expected. 

@djmitche in your PR is `__heartbeat__` meant to be overridden by more specific implementations?

**Comment by djmitche** [comment]
I wasn't sure what to do with that, as the dockerflow spec is pretty vague on the topic, and the webops folks didn't have any specific need for that data, so I didn't push Hassan to do anything more complicated.

But that idea makes sense -- some configuration of tc-lib-app that allows a service to register callbacks for whatever kind of "health" seems most appropriate for that service.

**Comment by matt-boris** [comment]
We will create individual `/__heartbeat__` endpoints for all of the TC services (as identified in https://github.com/taskcluster/taskcluster/projects/11) to then be consumed by a service like https://github.com/mozilla-services/telescope or Pingdom.
