### ISSUE TITLE
Add no-unused-vars

### ISSUE THREAD

**Issue by ydidwania** [taskcluster/taskcluster#46]
Is there any specific reason why  we have left out `no-unused-vars` ?

**Comment by djmitche** [comment]
@imbstack @owlishDeveloper good question :)

**Comment by owlishDeveloper** [comment]
We didn't use that rule before (and there are lots of unused variables in the code). 🤔 It's not a bad rule in its own... Especially as far as unused imports go. I don't know

THe documentation seems to suggest that `The "extends": "eslint:recommended" property in a configuration file enables this rule.` - I did see `"extends": "eslint:recommended"` in @imbstack's PR, I'm not sure

**Comment by imbstack** [comment]
Yeah, it is just disabled since it was going to be a lot of work to fix. @hybrid1999 is fixing it now!

**Comment by djmitche** [comment]
The complexity around fixing it is that we want to allow function arguments that are unused, as often function signatures are formulaic.  For example [json-e](https://github.com/taskcluster/json-e/blob/master/src/index.js) defines a bunch of operators, all of which get `(template, context)` whether they need either of those or not.  It's easier for someone reading the code later to know that context is available, even if it's not used, if all of the functions have the same signature:
```
operators.$eval = (template, context) => {
operators.$flatten = (template, context) => {
operators.$flattenDeep = (template, context) => {
operators.$fromNow = (template, context) => {
operators.$if = (template, context) => {
operators.$json = (template, context) => {
operators.$let = (template, context) => {
operators.$map = (template, context) => {
operators.$match = (template, context) => {
operators.$merge = (template, context) => {
operators.$mergeDeep = (template, context) => {
operators.$reverse = (template, context) => {
operators.$sort = (template, context) => {
```

at least Python and Rust do this by default in their style guidelines.

**Comment by imbstack** [comment]
I believe if we set [args](https://eslint.org/docs/rules/no-unused-vars#args) as an option to it, it should work for our case.

**Comment by imbstack** [comment]
This work is being tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1518568
