### ISSUE TITLE
Make a new deployment outside of GCP, fix resulting issues

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#4631]
I'm working on this with @masterWayZ.

Issues encountered:
 * ~~update `development-process.md` (#4638)~~
   * ~~move to another file, since this is not required for development~~
   * ~~azure account is not required~~
   * ~~postgres version 11.x~~
 * Is Helm 2 still supported? (#4758)
 * AWS is not required initially (after #4549 lands)
 * CloudAMQP's free tier is not enough (doesn't allow managing users, perms) (#4758)
 * support for non-GKE clusters (#3295)
 * bugs in `dev:init` (#4757)
 * TC requires RabbitMQ use TLS (#4648) 
 * `yarn build --push` tries to push to the official repo (#4649)

**Comment by djmitche** [comment]
@MasterWayZ how's this going?  Are there issues to file based on your notes?  Maybe even PRs? :)

**Comment by djmitche** [comment]
I think everything here is broken out into other issues or PRs -- @MasterWayZ is there anything else you would like to address here, or should we close this issue?

**Comment by MasterWayZ** [comment]
@djmitche I think we have everything, unless you also would want a doc on setting up the stateless DNS server? Other than that I can't think of anything else.

**Comment by djmitche** [comment]
I'm hesitant to document that at all!  It's really not a sustainable solution, or one we would be comfortable fixing bugs in.
