### ISSUE TITLE
Make it so that you can specify rabbitmq to use TLS or not

### ISSUE THREAD

**Issue by MasterWayZ** [taskcluster/taskcluster#4648]
Some people, especially in development deployments, may want to do a simple RabbitMQ installation with no SSL, this issue is there so we can make this possible.

**Comment by djmitche** [comment]
https://www.rabbitmq.com/ssl.html#tls-connectivity-options

The first option looks like it's getting into the guts of Erlang.. no fun.  The second option is no great advantage if the RabbitMQ server and proxy are in the same network as the TC services connecting to them.  So, I think there's a valid case for un-encrypted RabbitMQ on a private network.
