### ISSUE TITLE
[ui/docs] drop "Presentations" field

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#472]
This is [currently a 404](https://taskcluster-web.netlify.com/docs/resources), and it seems the content itself remains in the tc-docs repo.  For an unknown reason, it's also a 404 on the [old docs site](https://docs.taskcluster.net/docs/presentations).

We could potentially move that content somewhere else (tc-media, perhaps), but most of it is horribly out of date anyway.  So, I'd propose we just drop the menu item.

@petemoore I think you did most of the work to put that section together.  What do you think?

**Comment by petemoore** [comment]
I think the youtube videos still have value (setting up Windows worker types) but I don't recall any other presentations which may still be useful. Is there any way of digging up the old page to see what was there before?

**Comment by djmitche** [comment]
It's all still in the repo, with the index at https://github.com/taskcluster/taskcluster-docs/blob/master/src/presentations/index.md

**Comment by djmitche** [comment]
Linking to YouTube videos is a lot easier than hosting a reveal.js presentation, so we could definitely keep those around.
