### ISSUE TITLE
Python client not building the correct URL to start with

### ISSUE THREAD

**Issue by ionutgoldan** [taskcluster/taskcluster#4760]
**Describe the bug**

Using a Python client code such as `queue.getLatestArtifact(decision_task_id, 'public/actions.json')` fails because
the URL built by the library isn't the final one. When requesting it via HTTP GET, the endpoint redirects to
a different one & the Python library errors out with a generic `TaskclusterRestFailure` exception.

We started experiencing this issue after [issue 4057](https://github.com/taskcluster/taskcluster/issues/4057) got resolved.

**To Reproduce**

1. Ensure you have a Python interpreter provisioned with `taskcluster>=40.0.0` & `taskcluster-urls`.
2. On a Python module, instantiate a [Queue](https://docs.taskcluster.net/docs/reference/platform/queue) client.
3. Call `buildUrl('S9eGq7wORNSuwSnHMDLQaQ', 'public/actions.json')` on the instanced.

**Expected behavior**

`buildUrl()` method generates https://firefoxci.taskcluster-artifacts.net/S9eGq7wORNSuwSnHMDLQaQ/0/public/actions.json

**Taskcluster version**

`buildUrl()` method generates https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/S9eGq7wORNSuwSnHMDLQaQ/artifacts/public/actions.json
When the client library' s code is fetching it, the backend redirects it, causing an improperly handled exception within the lib.

**Screenshots**

**Platform (please complete the following information):**

 - OS: Linux (though this is a cross platform issue)
 - Version >= 40.0.0

**Comment by djmitche** [comment]
That work in progress is [these issues](https://github.com/taskcluster/taskcluster/issues?q=is%3Aopen+is%3Aissue+label%3Aobject-service) more or less.
