### ISSUE TITLE
json schema validation in CI does not report integer with minLength/maxLength

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#4790]
**Describe the bug**
@vnzongzna reported in the mozilla #taskcluster matrix channel that the [github-push-message schema](https://community-tc.services.mozilla.com/references/schemas/github/v1/github-push-message.json) defines `installationId` as `integer` with properties `minLength` and `maxLength` which are restrictions which apply to `string` and not `integer`.

As far as I see, no schema validation check in our CI threw up this mistake, and suggests that either our schema validation isn't running, or isn't able to report on this failure condition.

**To Reproduce**

1. Open https://community-tc.services.mozilla.com/references/schemas/github/v1/github-push-message.json
2. Note that `installationId` is defined as `integer` yet contains properties `minLength` and `maxLength`

**Expected behavior**
CI should report failures for properties defined as type `integer` with properties `minLength` or `maxLength`.

**Taskcluster version**
42.1.1

**Additional context**
It may be that our schemas validate against a version of jsonschema whose schema allows additional properties in the schema itself, and thus ignores `minLength`/`maxLength` rather than recognising they have no place in an integer definition. If I remember correctly, we extend the base schema to add additional controls (such as enforcing that `additionalProperties` is always specified) - perhaps we could adapt our extension of the base schema to not allow custom properties, or at least not allow additional properties whose names match recognised json schema properties. This is all rather hypothetical, as i haven't confirmed this is really the reason we didn't pick up the mismatch, but this context may be useful for anyone that dives into this issue.

**Comment by djmitche** [comment]
This was fixed in 4c6eafd9b65e2b4097f08e19770631ba14a051ff.  Ajv's strict mode (added in v7) catches a lot more than our custom schema ever did, and with better error messages :)
