### ISSUE TITLE
[UI] Entry component padding in docs

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#488]
STR:

1. Navigate to https://taskcluster-web.netlify.com/docs/reference/platform/auth/logs

**Actual**: The text is too close to the border.

<img width="927" alt="Screen Shot 2019-03-23 at 9 02 09 AM" src="https://user-images.githubusercontent.com/3766511/54866484-a3a61500-4d4a-11e9-95eb-04a90be18292.png">

**Expected**: There is enough padding (24px).

<img width="923" alt="Screen Shot 2019-03-23 at 9 05 30 AM" src="https://user-images.githubusercontent.com/3766511/54866500-d7813a80-4d4a-11e9-94a4-066943c63d6f.png">

**Comment by RizwanSyed357** [comment]
hey - this looks interesting. Can you assign it to me please? This will be my third patch to Firefox :)

**Comment by helfi92** [comment]
👋 @RizwanSyed357 

Go for it :)

**Comment by helfi92** [comment]
Check your email, I sent you an invitation.

**Comment by helfi92** [comment]
This issue is no longer relevant since we don't show long descriptions on the panel header anymore.

![Screen Shot 2019-04-02 at 6 13 56 PM](https://user-images.githubusercontent.com/3766511/55439623-32990580-5573-11e9-806e-cf662aaa94f3.png)

@RizwanSyed357 Aplogies for that. As always, if you're interested in another issue, let me know and I'll assign it to you. Thanks!
