### ISSUE TITLE
docker-worker tests failing

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#4902]
The docker-worker tests began failing a few days ago.  Check pushes to main to see the failures in action.

**Comment by djmitche** [comment]
```
  docker-worker:dockerImage pull image failed Next Attempt in: 873.32 ms. Image: tutum/curl:latest. Error: (HTTP code 404) unexpected - pull access denied for tutum/curl, repository does not exist or may require 'docker login' 
```
what is tutum anyway?

**Comment by jwhitlock** [comment]
https://hub.docker.com/u/tutum has several published images. The most recent was updated 3 years ago. The homepage http://www.tutum.co is now a parked domain.

Looks like it was widely used in Stackoverflow answers in 2018 / 2019, like:

https://stackoverflow.com/a/53288814/10612

```
kubectl run curl -it --rm --image=tutum/curl -- sh
```

They were acquired by Docker in 2015:

https://www.docker.com/blog/docker-acquires-tutum/

I imagine it can be replaced with the official curl image, once we figure out what is calling it...

https://hub.docker.com/r/curlimages/curl
