### ISSUE TITLE
Show task definition in yaml format

### ISSUE THREAD

**Issue by marco-c** [taskcluster/taskcluster#4905]
Task definitions in pages such as https://community-tc.services.mozilla.com/tasks/XRUHNFm9TceiWydoSzFG9g/definition are shown in JSON format.
The input to https://community-tc.services.mozilla.com/tasks/create is instead YAML format.

Manually creating a task by copying and pasting from existing task definitions is a bit painful because of the mismatch.

**Comment by djmitche** [comment]
I think this is a dup of #4242.

**Comment by marco-c** [comment]
Yes, fixing #4242 would fix this too.
