### ISSUE TITLE
Current k8s ingress will no longer be supported in k8s v1.22+

### ISSUE THREAD

**Issue by imbstack** [taskcluster/taskcluster#4912]
Poking around @MasterWayZ's deployment to debug an issue with the new taskcluster release, we found a good number of logs in the ingress pod:

```
networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
```

So we should get on that relatively soon.

**Comment by Eijebong** [comment]
Didn't know there was an issue for that. This has been fixed by https://github.com/taskcluster/taskcluster/pull/5464
