### ISSUE TITLE
Use application/json for dockerflow endpoints `__heartbeat__` etc.

### ISSUE THREAD

**Issue by jwhitlock** [taskcluster/taskcluster#4940]
The UI returns an empty JSON dict ``{}`` with the header ``content-type: application/octet-stream`` for the two endpoints:

* `https://community-tc.services.mozilla.com/__heartbeat__`
* `https://community-tc.services.mozilla.com/__lbheartbeat__`

This prompts the browser to download them instead of display them as JSON.

The header ``content-type: application/json`` is used for the version endpoint, so it is displayed in-browser:

* `https://community-tc.services.mozilla.com/__version__`

**To Reproduce**

1. View `https://community-tc.services.mozilla.com/__version__` in a browser as JSON
2. View `https://community-tc.services.mozilla.com/__heartbeat__` in a browser, you are prompted to download it.

**Expected behavior**

Visiting ``__heartbeat__`` and ``__lbheartbeat__`` display an empty JSON object in the browser.

**Taskcluster versions**

* v43.2.0 (`https://firefox-ci-tc.services.mozilla.com/__heartbeat__`)
* v44.0.0 (community-ci)
* v44.1.0 / current main branch

**Comment by matt-boris** [comment]
On v44.6.1, `/__lbheartbeat__` now returns json (no download request). Some additional work needs to be done to get the `/__heartbeat__` endpoint to return properly, but I'll follow up with that work in the implementation of the heartbeat endpoint task #4597.
