### ISSUE TITLE
Deprecated usage of highlight.js 10.7.0

### ISSUE THREAD

**Issue by jwhitlock** [taskcluster/taskcluster#4947]
**Describe the bug**

When viewing a task in the UI, this message is displayed in the console:

```
Deprecated as of 10.7.0. highlight(lang, code, ...args) has been deprecated.
Deprecated as of 10.7.0. Please use highlight(code, options) instead.
https://github.com/highlightjs/highlight.js/issues/2277
```
The message is generated from ``Tasks.TaskGroup.cd2cd260.js:11:71365``.

**To Reproduce**

1. Open the developer tools, Console
2. Go to https://community-tc.services.mozilla.com/tasks
3. Click to view a task

**Expected behavior**

No deprecation message.

**Taskcluster version**

* Present in 44.1.0 on Community-TC
* Present in 43.2.0 on Firefox-ci

**Additional context**

The linked issue https://github.com/highlightjs/highlight.js/issues/2277 has a working example of changing the call to `highlight`.

**Comment by Tanmay000009** [comment]
Hey, I am new around here. Can I contribute?

**Comment by jwhitlock** [comment]
Thanks @Tanmay000009! A good place to start is getting a development environment setup. See https://github.com/taskcluster/taskcluster/blob/main/dev-docs/development-process.md. You'll need the first two sections, "Setup" and "Hacking on the UI". You then should be able to reproduce the issue in your development environment and start working on the fix.

**Comment by Tanmay000009** [comment]
@jwhitlock thank you so much! The documentation is really helpful and easy to understand. I would like to work on the issue and try to contribute, if it's possible, please allot the issue to me.

**Comment by Tanmay000009** [comment]
@jwhitlock  I am getting errors:
`yarn start`

yarn run v1.22.10
$ cross-env NODE_ENV=development node src/main.js devServer
AssertionError [ERR_ASSERTION]: readDbUrl is required
    at Function.setup (/media/tanmay000009/Web Dev/taskcluster/libraries/postgres/src/Database.js:60:5)
    at Object.exports.setup (/media/tanmay000009/Web Dev/taskcluster/db/src/setup.js:6:25)
    at setup (/media/tanmay000009/Web Dev/taskcluster/services/web-server/src/main.js:186:50)
    at /media/tanmay000009/Web Dev/taskcluster/libraries/loader/src/index.js:109:33
    at new Promise (<anonymous>)
    at /media/tanmay000009/Web Dev/taskcluster/libraries/loader/src/index.js:107:18
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

---------------
I even tried the solution provided in #2637
https://github.com/taskcluster/taskcluster/issues/2637#issuecomment-617997973
```sh
export READ_DB_URL=postgresql://postgres@localhost/postgres
export WRITE_DB_URL=postgresql://postgres@localhost/postgres
```

**Comment by jwhitlock** [comment]
@Tanmay000009 sorry to hear that. The instructions are working for me:

```bash
> export TEST_DB_URL=postgresql://postgres@localhost/postgres
> export READ_DB_URL=$TEST_DB_URL
> export WRITE_DB_URL=$TEST_DB_URL
> export TASKCLUSTER_ROOT_URL=https://community-tc.services.mozilla.com
> cd services/web-server
> yarn
yarn install v1.22.10
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
[5/5] 🔨  Building fresh packages...

✨  Done in 3.01s.
> yarn start
yarn run v1.22.10
$ cross-env NODE_ENV=development node src/main.js devServer


Web server running on port 3050.

Open the interactive GraphQL Playground and schema explorer in your browser at:
          http://localhost:3050/playground
```

Are you setting the environment variables in the same shell session where you are running `yarn start`?

**Comment by Tanmay000009** [comment]
Thank you so much @jwhitlock . Found my mistake, I didn't run them all in the same terminal. Thank you for helping.

**Comment by jwhitlock** [comment]
> Should I add a note for the same in: https://github.com/taskcluster/taskcluster/blob/main/dev-docs/development-process.md ?
> So that newbies like me don't get stuck on this mistake

If you think there is a clearer way to say it, please open a PR!

**Comment by Tanmay000009** [comment]
@jwhitlock I have opened PR as you mentioned! https://github.com/taskcluster/taskcluster/pull/4977
Although now that I think about it, I guess showed have opened a separate issue and referenced it. Hope my PR was appropriate, if not please do help me with the same. Thank you so much for the exprience you are helping me gain!

**Comment by jwhitlock** [comment]
I had some feedback on PR #4977, please consider it in the next version. I don't necessarily open an issue to track documentation changes.

PRs expect to have a changelog entry as well, see https://github.com/taskcluster/taskcluster/blob/main/dev-docs/best-practices/changelog.md for details. I agree with that doc, that "silent" is a good semvar level for most documentation changes. So, to generate a changelog, you'd run something like:

```
yarn changelog --no-issue --silent --developers
```

**Comment by Tanmay000009** [comment]
@jwhitlock Thank you so much for guiding me on changelogs! I even added a changelog to the main pr regarding issue #4947 .
#4978 . 
I'll redo changes on dev-docs, and open a new PR as I am not able to edit on that PR. (About moving up note)
Thank you for guiding me, hope there are no issues with my PR #4978
