### ISSUE TITLE
Update staff on "People of Taskcluster"

### ISSUE THREAD

**Issue by jwhitlock** [taskcluster/taskcluster#4955]
On https://community-tc.services.mozilla.com/docs/people, update the staff list:

* Remove @djmitche and @imbstack 
* Add @leplatrem and @bsieber-mozilla 

The page source is https://github.com/taskcluster/taskcluster/blob/main/ui/docs/people.mdx, but the update mechanism may take some research.

**Comment by jwhitlock** [comment]
PR #4981 does most of this.

**Comment by jwhitlock** [comment]
Calling this done, except for one person. @bsieber-mozilla feel free to add yourself to the staff list, that could be the first contribution. If you want something more substantial, let me know and we can find a good candidate.

**Comment by bsieber-mozilla** [comment]
I added an issue #4988 

An attempt to follow this comment in this [CONTRIBUTING.md](https://github.com/taskcluster/taskcluster/blob/main/CONTRIBUTING.md doc):
"Note that we use all-contributors to make sure everyone gets credit for their work on Taskcluster. You can add new people to the list using the @all-contributors bot."

**Comment by bsieber-mozilla** [comment]
@all-contributors please add @bsieber-mozilla for code and staff

**Comment by bsieber-mozilla** [comment]
@all-contributors please add @bsieber-mozilla for both staff and code
