### ISSUE TITLE
Clicking on a role row only works if you click on the text part of it

### ISSUE THREAD

**Issue by Eijebong** [taskcluster/taskcluster#4962]
On the roles page, clicking anywhere on a role row will make said row blink. It will only allow you to edit it if you click on the text part of it (the role name) which is very confusing.

Firefox 92 on linux.

**Comment by jwhitlock** [comment]
Confirmed on:

* https://firefox-ci-tc.services.mozilla.com/auth/roles
* https://community-tc.services.mozilla.com/auth/roles

Row clicking works on pages like [tasks on community-tc](https://community-tc.services.mozilla.com/tasks) and the [task index on firefox-ci](https://firefox-ci-tc.services.mozilla.com/tasks/index). A comparison of this table versus other correctly working tables may find the issue.
