### ISSUE TITLE
[UI] Hooks list focus state

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#497]
STR:

1. https://taskcluster-web.netlify.com/hooks
2. Press the tab key many times until the focus is on the first element of the hooks list

**Expected**: The focus effect background color looks like

![Screen Shot 2019-03-26 at 7 55 35 AM](https://user-images.githubusercontent.com/3766511/54995215-9718fb00-4f9c-11e9-9477-6a3fe1a85f90.png)

**Actual**:

![Screen Shot 2019-03-26 at 7 54 40 AM](https://user-images.githubusercontent.com/3766511/54995216-9718fb00-4f9c-11e9-83bc-a553debb9178.png)

**Comment by VirmaniDivya** [comment]
Hi! Can I take up this issue, please?

**Comment by shubhamgupta2956** [comment]
@helfi92 I would like to take this issue.
One more thing, I am having difficulty in running web-services due to which `Network error: Failed to fetch` is coming when I open hooks page in my setup. Also when I start web services with `yarn start` it gives this output:
`$ NODE_ENV=development node src/main.js devServer


No Pulse namespace defined; no Pulse messages will be received.
Error: Unable to use "github" login strategy without taskcluster clientId and accessToken
    at Github.useStrategy (/home/savitar/opensource/taskcluster/services/web-server/src/login/strategies/github.js:84:13)
    at Object.values.forEach.strategy (/home/savitar/opensource/taskcluster/services/web-server/src/servers/createApp.js:39:14)
    at Array.forEach (<anonymous>)
    at module.exports (/home/savitar/opensource/taskcluster/services/web-server/src/servers/createApp.js:38:29)
    at setup (/home/savitar/opensource/taskcluster/services/web-server/src/main.js:105:39)
    at Promise (/home/savitar/opensource/taskcluster/libraries/loader/src/index.js:149:33)
    at new Promise (<anonymous>)
    at loaded.(anonymous function).Promise.all.then.deps (/home/savitar/opensource/taskcluster/libraries/loader/src/index.js:147:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`
Please help me solving this issue. Thanks.

**Comment by helfi92** [comment]
> Error: Unable to use "github" login strategy without taskcluster clientId and accessToken

You'll want to remove `github` from the login strategies and then try running the server again.

**Comment by helfi92** [comment]
Make sure https://github.com/taskcluster/taskcluster/tree/master/services/web-server#github is **not** configured or set to an empty object.

**Comment by shubhamgupta2956** [comment]
@helfi92 it is still showing `Network error: failed to fetch` even after starting web services. Please help me with how to get a list of entries in pages

**Comment by helfi92** [comment]
Could you show me the output of both terminals, please? Btw, to put code segments in the comment section, you can refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting. It will make it easier in terms of readability.

**Comment by shubhamgupta2956** [comment]
![Screenshot from 2019-06-17 01-58-07](https://user-images.githubusercontent.com/43504292/59569193-b9a24800-90a3-11e9-8814-d4b1b8d9706d.png)
![Screenshot from 2019-06-17 01-57-57](https://user-images.githubusercontent.com/43504292/59569194-b9a24800-90a3-11e9-89f6-5e9ee1fb0b85.png)
These are the screenshots of my browser page and terminal. It is not showing any error in terminal now but still showing errors in my browser.

**Comment by helfi92** [comment]
For web-server, instead of `yarn start` use

```bash
TASKCLUSTER_ROOT_URL="https://taskcluster.net" yarn start
```

Let me know if that helps.

**Comment by shubhamgupta2956** [comment]
I have tried that too but it is still giving the same error in browser.

**Comment by helfi92** [comment]
Interesting. Did you change `services/web-server/config.yml` by any chance? Could you show me the output of `git diff`. Also, did you create a `user-config.yml`? If so, what is the content of that file?

**Comment by shubhamgupta2956** [comment]
![Screenshot from 2019-06-18 22-11-07](https://user-images.githubusercontent.com/43504292/59702949-8633fa80-9216-11e9-8c29-df2a2309d996.png)
Content of user-config.yml:-
```
defaults:
  taskcluster:
      rootUrl: "https://taskcluster-development.net"
  pulse:
    namespace:
    username: ..
    password: ..
    hostname: ..
    vhost: ..
  login:
    strategies:
```

**Comment by helfi92** [comment]
Change `user-config.yml` to:

```bash
defaults:
  taskcluster:
      rootUrl: https://taskcluster.net
```

**Comment by shubhamgupta2956** [comment]
I tried it now but problem still remains the same with same output on the browser.

**Comment by helfi92** [comment]
What is the output of `.env` in the `ui` directory?

**Comment by shubhamgupta2956** [comment]
Did you mean output of `env`. It is:-
```CLUTTER_IM_MODULE=xim
NVM_DIR=/home/savitar/.nvm
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
LESSCLOSE=/usr/bin/lesspipe %s %s
TERMINATOR_UUID=urn:uuid:77867cf9-fd5d-43f1-ade2-759d336be2ba
LANG=en_IN
DISPLAY=:0
COLORTERM=truecolor
NVM_CD_FLAGS=
PERL_MB_OPT=--install_base "/home/comedian/perl5"
USERNAME=savitar
JAVA_HOME=/usr/lib/jvm/java-11-oracle
J2SDKDIR=/usr/lib/jvm/java-11-oracle
XDG_VTNR=2
FZF_CTRL_R_OPTS=--preview 'echo {}' --preview-window down:3:hidden:wrap --bind '?:toggle-preview' --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort' --header 'Press CTRL-Y to copy command into clipboard' --border
SSH_AUTH_SOCK=/tmp/ssh-1aw6RINWNWcO/agent.3693
MANDATORY_PATH=/usr/share/gconf/i3.mandatory.path
XDG_SESSION_ID=2
DERBY_HOME=/usr/lib/jvm/java-11-oracle/db
USER=savitar
DESKTOP_SESSION=i3
QT4_IM_MODULE=xim
GOPATH=/home/savitar/go
DEFAULTS_PATH=/usr/share/gconf/i3.default.path
PWD=/home/savitar/opensource/taskcluster/ui
HOME=/home/savitar
J2REDIR=/usr/lib/jvm/java-11-oracle
SSH_AGENT_PID=4093
QT_ACCESSIBILITY=1
XDG_SESSION_TYPE=x11
XDG_DATA_DIRS=/usr/share/i3:/usr/local/share:/usr/share:/var/lib/snapd/desktop
TERMINATOR_DBUS_NAME=net.tenshu.Terminator20x1a6021154d881c
XDG_SESSION_DESKTOP=i3
PERL_MM_OPT=INSTALL_BASE=/home/comedian/perl5
PERL_LOCAL_LIB_ROOT=/home/comedian/perl5
GTK_MODULES=gail:atk-bridge
TERMINATOR_DBUS_PATH=/net/tenshu/Terminator2
WINDOWPATH=2
VTE_VERSION=5401
TERM=xterm-256color
SHELL=/usr/bin/fish
QT_IM_MODULE=ibus
XMODIFIERS=@im=ibus
IM_CONFIG_PHASE=2
NVM_BIN=/home/savitar/.nvm/versions/node/v10.15.3/bin
XDG_CURRENT_DESKTOP=i3
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
PERL5LIB=/home/comedian/perl5/lib/perl5
XDG_SEAT=seat0
SHLVL=2
LANGUAGE=en_IN:en
GDMSESSION=i3
LOGNAME=savitar
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
XDG_RUNTIME_DIR=/run/user/1000
XAUTHORITY=/run/user/1000/gdm/Xauthority
XDG_CONFIG_DIRS=/etc/xdg/xdg-i3:/etc/xdg
PATH=/home/savitar/.cargo/bin:/home/comedian/perl5/bin:/home/savitar/xdman:/home/savitar/.yarn/bin:/home/savitar/.nvm/versions/node/v10.15.3/bin:/home/savitar/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-11-oracle/bin:/usr/lib/jvm/java-11-oracle/db/bin:/usr/local/go/bin:/home/savitar/go/bin/bin:/home/savitar/go/bin:/home/savitar/.config/composer/vendor/bin:/home/savitar/bin:/home/savitar/.rvm/bin
OMF_PATH=/home/savitar/.local/share/omf
OMF_CONFIG=/home/savitar/.config/omf
LOGIN=savitar
FZF_CTRL_T_OPTS=--preview '~/.vim/plugged/fzf.vim/bin/preview.rb {} | head -200'
LESSOPEN=| /usr/bin/lesspipe %s
GTK_IM_MODULE=ibus
_=/usr/bin/env```

**Comment by helfi92** [comment]
Sorry, I was referring to https://github.com/taskcluster/taskcluster/tree/master/ui#environment (i.e., `ui/.env`). It's not required to have this file. If you don't have it, no need to create it.

**Comment by helfi92** [comment]
Did you erase

```yaml
pulse:
    namespace:
    username: ..
    password: ..
    hostname: ..
    vhost: ..
  login:
    strategies:
```

from `services/web-server/user-config.yml`?

**Comment by shubhamgupta2956** [comment]
> Did you erase
> 
> ```yaml
> pulse:
>     namespace:
>     username: ..
>     password: ..
>     hostname: ..
>     vhost: ..
>   login:
>     strategies:
> ```
> 
> from `services/web-server/user-config.yml`?

yes

**Comment by shubhamgupta2956** [comment]
> Sorry, I was referring to https://github.com/taskcluster/taskcluster/tree/master/ui#environment (i.e., `ui/.env`). It's not required to have this file. If you don't have it, no need to create it.

I didn't have this file

**Comment by helfi92** [comment]
Try running `git checkout .` inside the root directory of the monorepo. After that, turn off both ui and web-server.

Inside `ui/`, run `yarn start`. Inside `services/web-server` run `yarn start`. What do you get now?

**Comment by shubhamgupta2956** [comment]
I am getting the same thing again.

**Comment by helfi92** [comment]
One second, I'll try cloning a fresh copy of the repo and see if I can replicate.

**Comment by helfi92** [comment]
Hm, could you try pulling the most recent changes and trying again. Something like:

```
git pull upstream master --rebase
```

**Comment by helfi92** [comment]
OK i figured it out. You need to run the ui on port 5080:

```
PORT=5080 yarn start
```

**Comment by helfi92** [comment]
Does it help?

**Comment by shubhamgupta2956** [comment]
> Does it help?

Yes it works. Thanks a lot. Just one more thing. When I save a hook it says that client with clientId shubham not found. What should I do for that?

**Comment by helfi92** [comment]
> Yes it works. Thanks a lot. Just one more thing. When I save a hook it says that client with clientId shubham not found. What should I do for that?

I don't think you need to worry about this issue for the focus state. Feel free to ignore this for now.

Regarding `ECONNRESET`, it's probably because the ui can't seem to connect to web-server. Make sure the web-server process is on.

**Comment by shubhamgupta2956** [comment]
@helfi92 I think this is the error in node_modules/material-ui-treeview as when I pressed tab multiple times in [https://hassanali.me/material-ui-treeview/](url) I got the same white shade there also. Can you please guide me how can I change its properties and whether I should change it or not.

**Comment by helfi92** [comment]
Ah, interesting. Good job for tracking this down. What you can do is send a pull-request to the material-ui-treeview repo. The repository is under my GitHub account so it will be easy for us to get the fix merged.

**Comment by shubhamgupta2956** [comment]
@helfi92 I am out of town now. I will try to send a pull request by Monday.

**Comment by helfi92** [comment]
Sounds good, thanks!

**Comment by shubhamgupta2956** [comment]
@helfi92 sorry for late reply. I have found that the color property
(```focused {
    background-color: theme.palette.grey[300]
},```) 
is set by node_modules/@material_ui. I tried hard to find a way to overwrite this property but can't find a good solution. Please guide me how can I solve it. Thanks.

**Comment by helfi92** [comment]
Ah, that's the culprit. Good job!

We could override the style in `src/ui/theme.js`. Something like:

```diff
diff --git a/ui/src/theme.js b/ui/src/theme.js
index ebf7d6b0b..754e5b22d 100644
--- a/ui/src/theme.js
+++ b/ui/src/theme.js
@@ -332,6 +332,13 @@ const createTheme = isDarkTheme => {
           maxWidth: 500,
         },
       },
+      MuiExpansionPanelSummary: {
+        root: {
+          '&$focused': {
+            backgroundColor: THEME.TEN_PERCENT_WHITE,
+          },
+        },
+      },
     },
   };
 };
```

I looked at https://github.com/mui-org/material-ui/blob/dbc788f7d231b4eceaa7a6a3e253104de5de9af0/packages/material-ui/src/ExpansionPanelSummary/ExpansionPanelSummary.js#L28 to understand how to override this value.

**Comment by helfi92** [comment]
Resolved in https://github.com/taskcluster/taskcluster/commit/680661c6488a0ebcbe3281b0fe5b43199a9d3f3a.
