### ISSUE TITLE
[UI] Show application name beside the logo

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#498]
STR:

1. Navigate to https://taskcluster-web.netlify.com/
2. Click the hamburger menu to open the navigation drawer

**Actual**:

<img width="267" alt="Screen Shot 2019-03-26 at 11 25 56 AM" src="https://user-images.githubusercontent.com/3766511/55010110-05b88180-4fba-11e9-8f6e-ea60456a26d9.png">

When the user hovers on "Taskcluster", the text is replaced by the logo:

<img width="336" alt="Screen Shot 2019-03-26 at 11 27 29 AM" src="https://user-images.githubusercontent.com/3766511/55010191-2b458b00-4fba-11e9-9e8e-56e29879c7dc.png">

**Expected**: (T) Taskcluster

We want to remove the hover effect and simply have the logo sit beside the application name.

**Comment by kritisingh1** [comment]
Hi @helfi92 I would like to work on this. May I take this up? Thanks!

**Comment by helfi92** [comment]
Go for it.

**Comment by djmitche** [comment]
@kritisingh1 I invited you to the organization.  Once you've accepted, let me know and I can assign this issue to you.

**Comment by kritisingh1** [comment]
@djmitche Accepted.

**Comment by helfi92** [comment]
How is it going @kritisingh1?

**Comment by kritisingh1** [comment]
I'm on it.

**Comment by helfi92** [comment]
Do you have any questions @kritisingh1? Let me know if there's anything unclear.

**Comment by kritisingh1** [comment]
Hi. Could you let me know how to start the local server of netlify for testing the changes? I can't find a relevant command in package.json. Builds and tests are completed successfully.

**Comment by helfi92** [comment]
Hi @kritisingh1. You don't need Netlify to start the local server. You just need two terminals, one running the UI and the other running the server. For this specific task I don't think you even need to have the server running.

Have a look at the [README](https://github.com/taskcluster/taskcluster/blob/master/ui/README.md) for how to run the UI. From the root of the project, I think you can do something like:

```bash
cd ui
yarn
yarn start
```

Does that help?
