### ISSUE TITLE
ViewTask UI doesn't handle similar named actions well

### ISSUE THREAD

**Issue by bhearsum** [taskcluster/taskcluster#4983]
I recently added a new action called `rerun-pr`, which is very similar in name to the existing `rerun` action. Depending on the situation, one or the other will be available as an action. The UI handles this fine for the case where `rerun` is enabled but `rerun-pr` is not, for example: https://firefox-ci-tc.services.mozilla.com/tasks/A0MP43PSTSCtPkChsME-XQ

But it is not handled well for the reverse. In these cases, there's two issues:
1) The `rerun-pr` action is shown, but with the wrong icon (a hammer instead of the "restart" icon)
2) The `rerun` action is _still_ shown, even though it's not present in `actions.json`

I poked at this a bit. The icon part is easily fixable by tweaking https://github.com/taskcluster/taskcluster/blob/5020df14256764a50d3b4d3f4e621c3ffda65f4a/ui/src/views/Tasks/ViewTask/index.jsx#L761

I'm pretty sure that https://github.com/taskcluster/taskcluster/blob/5020df14256764a50d3b4d3f4e621c3ffda65f4a/ui/src/views/Tasks/ViewTask/index.jsx#L941 is the cause of the second issue, although I wasn't able figure out why that block is being added despite `rerun` not being a key in `actionData`.

**Comment by escapewindow** [comment]
I wonder if, rather than hardcode action names in the UI code and having to update that code whenever we add a new action, maybe we could:
- create a `label` to icon mapping, with a default
- populate the actions in gecko and standalone taskgraph with those labels
- new actions can set an existing label, a new label (an unknown new label would fall through to the default), or none
- if we want a new icon for new labels, we can then file an issue to update the UI with a new icon and add the new label+icon to the map

We could then potentially use those labels for other types of action grouping elsewhere.

Still brainstorming: `label` may suggest we can apply multiple to each action. If so, we need to have rules about which icon gets applied if there are multiple labels that match icons. If we want to disallow that, we could use a different name: `type`, `kind`, `family`, ?

**Comment by hrahul2605** [comment]
Hey @bhearsum 
I'd like to work on this issue and get myself a bit more familiarised with the project.

I did setup my dev environment for the UI part, and made a small PR as well (#5009)

I opened the link you mentioned, but couldnt find any `rerun` action, i am assuming it has something to do with permissions.
So, if you could help me out a bit, i can solve up this issue.

**Comment by lotas** [comment]
Working on this issue. 
>  is the cause of the second issue, although I wasn't able figure out why that block is being added despite rerun not being a key in actionData.

As I understand logic inside this component, this `rerun` (plus some others) are the default actions, shown for all tasks.  
In case no actions are defined in task it renders that default set.

Now, when it comes to the tasks that contain custom actions, we should decide, if we want to show only those, or we want to show those + default set. @bhearsum  WDYT?

@escapewindow I like this idea to map actions.
At the moment `action.name` and `action.title` are used, and both should be unique. 

Would be good to get that list, or agree on same format, so we can show expected icons for those actions

**Comment by lotas** [comment]
Found some clarifications in the docs: https://community-tc.services.mozilla.com/docs/manual/design/conventions/actions/ui#specialized-triggering

> User interfaces should look for the desired action by name. The UI should check that there is exactly one matching action available for the given task or task-graph. If multiple actions match, the UI should treat that as an error (helping to avoid actions being surreptitiously replaced by similarly-named, malicious actions).

So I think showing `rerun` even if it wasn't in actions is expected.

**Comment by bhearsum** [comment]
> Now, when it comes to the tasks that contain custom actions, we should decide, if we want to show only those, or we want to show those + default set. @bhearsum WDYT?

I'm not active in this area, so I don't have a lot of great insight at this point. I _think_ that custom actions are typically additions to what already exists though. If that's the case, we would almost certainly need to use both, otherwise we would hide important actions like "Cancel".

**Comment by escapewindow** [comment]
> Found some clarifications in the docs: https://github.com/taskcluster/taskcluster/blob/main/ui/docs/manual/design/conventions/actions/ui.mdx#specialized-triggering
> 
> > User interfaces should look for the desired action by name. The UI should check that there is exactly one matching action available for the given task or task-graph. If multiple actions match, the UI should treat that as an error (helping to avoid actions being surreptitiously replaced by similarly-named, malicious actions).
> 
> So I think showing `rerun` even if it wasn't in actions is expected.

Note that `rerun` won't do anything in certain scenarios: the user doesn't have scopes, or we've disallowed the custom `rerun` action in, say, PRs where allowing for running custom actions in the PR might be a security hole. I've overheard that the `rerun` option existing in the UI but not actually working is a point of frustration for users.

**Comment by lotas** [comment]
> Note that rerun won't do anything in certain scenarios: the user doesn't have scopes, or we've disallowed the custom rerun action in, say, PRs where allowing for running custom actions in the PR might be a security hole. I've overheard that the rerun option existing in the UI but not actually working is a point of frustration for users.

In such case, it should be removed / disabled. And there is already a ticket #5049
