### ISSUE TITLE
enhancement request: local taskcluster proxy for debugging

### ISSUE THREAD

**Issue by escapewindow** [taskcluster/taskcluster#4993]
I love how the taskcluster proxy makes using taskcluster scopes + API calls super easy in automation :)

However, when we try to replicate a task locally (download the docker image, run the same commands in the local docker container), the very same proxy that makes things easier in automation makes it difficult to replicate the same steps locally.

I'm thinking we might be able to create a local taskcluster proxy that uses your tc creds? (That might not fully solve the problem for all users, unless they have all the scopes needed to run a given task, but it's a step in the right direction.)

- ```eval `taskcluster signin` ``` to set your client id + access token in your env
- run a command to launch the local taskcluster proxy, which refers to the client id + access token in env vars
  - this launches a daemon at, say, http://localhost:12345 , and possibly sets `TASKCLUSTER_PROXY_URL`
  - run the task steps; when the task hits `$TASKCLUSTER_PROXY_URL/API_PATH` the local proxy uses the tc creds + code to translate that into tc API calls.

I've had to hack around the proxy numerous times: sometimes I edit a function call to return a cleartext secret to avoid turning the TC Secrets proxy request into a TC API call, and then I try to remember not to commit that change. I'd love to be able to have this sort of helper tool to avoid that type of hackery.

**Comment by escapewindow** [comment]
Alternately, we could add a tc-client.py function that:

- looks for the TASKCLUSTER_PROXY_URL and uses it if specified
- otherwise falls back to direct API calls, using the tc creds in env vars

Then we could use that function wherever we're hitting the taskcluster proxy directly, which would allow for both hitting the proxy in automation and using direct API calls locally.

**Comment by escapewindow** [comment]
(Or is the proxy itself runnable locally?)

**Comment by jwhitlock** [comment]
It is possible to run taskcluster proxy locally - see https://github.com/taskcluster/taskcluster/tree/main/tools/taskcluster-proxy. I'm not what configuration you would want to allow a local task to run smoothly.

**Comment by escapewindow** [comment]
:) looks like we're done here, then. Thank you!
