### ISSUE TITLE
client-py does not handle redirects in `getArtifact` endpoint

### ISSUE THREAD

**Issue by ahal** [taskcluster/taskcluster#4998]
**Describe the bug**
The `artifacts` endpoint [is supposed to return a 303 response](https://docs.taskcluster.net/docs/reference/platform/queue/api#getArtifact). Specifically "Response: the HTTP response to this method is a 303 redirect to the URL from which the artifact can be downloaded". However the Python client appears to [fail on any 303 status](https://github.com/taskcluster/taskcluster/blob/main/clients/client-py/taskcluster/client.py#L514). So rather than following the redirect (or returning the URL pointed at by the redirect as the schema says we are supposed to), we raise an exception.

**To Reproduce**

Steps to reproduce the behaviour:

```python
>>> import taskcluster
>>> queue = taskcluster.Queue({"rootUrl": "https://firefox-ci-tc.services.mozilla.com"})
>>> queue.getArtifact("cCEzo2wFTCmPe65GJyO7ng", 0, "public/taskgraph/diffs/diff_autoland-onpush.txt")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ahal/.pyenv/versions/tc-bug/lib/python3.9/site-packages/taskcluster/generated/queue.py", line 467, in getArtifact
    return self._makeApiCall(self.funcinfo["getArtifact"], *args, **kwargs)
  File "/home/ahal/.pyenv/versions/tc-bug/lib/python3.9/site-packages/taskcluster/client.py", line 270, in _makeApiCall
    response = self._makeHttpRequest(entry['method'], _route, payload)
  File "/home/ahal/.pyenv/versions/tc-bug/lib/python3.9/site-packages/taskcluster/client.py", line 538, in _makeHttpRequest
    raise exceptions.TaskclusterRestFailure(
taskcluster.exceptions.TaskclusterRestFailure: None
```

After adding some debugging, I determined the response code here is a `303` (as the docs mention is possible).

**Expected behavior**

I'm a bit unsure about what is actually expected here. The docs say that the response schema is:
```
{
    "url": <url>
}
```

and that it's up to the consumer to handle downloading it. But I know of a consumer that is using this API (reviewbot) and it seems to both avoid the `303` error as well as return the contents of the artifact (rather than the URL). So I'm not sure what is going on here.

Either we should return the artifact contents (and the docs are wrong), or we should return the URL (and there's a second bug in the implementation here).

I'll admit I'm pretty confused about what's actually expected or how `reviewbot` is working...

**Comment by escapewindow** [comment]
For whatever reason, I'm using `buildUrl` in scriptworker, e.g. https://github.com/mozilla-releng/scriptworker/blob/54f807ef2cafd4c86faba9faa82147139b128d73/tests/test_integration.py#L279 or https://github.com/mozilla-releng/scriptworker/blob/54f807ef2cafd4c86faba9faa82147139b128d73/src/scriptworker/artifacts.py#L194-L220

**Comment by ahal** [comment]
Interesting, for my immediate use case I'm actually only interested in the URL anyway, so that unblocks me for now! I think this is still a valid issue though?

Also forgot to mention that if you craft the request via URL directly, the redirect is followed and artifact contents are displayed:
https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/cCEzo2wFTCmPe65GJyO7ng/runs/0/artifacts/public/taskgraph/diffs/diff_autoland-onpush.txt

**Comment by djmitche** [comment]
This was changed relatively recently in the Python client, because it was inconsistent between versions, and because things like reviewbot were taking advantage of the accidental feature that the client would parse the redirect as JSON.  This was done in #4058.  It's possible reviewbot is using an older version of the client.

Note that there are also artifact-download implementations in the clients now, if you *do* need to download the artifact content.

**Comment by djmitche** [comment]
Also, you can avoid this redirect nonsense with the [`artifact` method](https://docs.taskcluster.net/docs/reference/platform/queue/api#artifact).

Oh, I missed that this is failing on the 303 -- that's a bug, for sure.

**Comment by djmitche** [comment]
Huh, and it appears that is just not implemented!  This should be `>= 400`, not `>= 300`:
https://github.com/taskcluster/taskcluster/blob/685a0470d6ddb845552f33c245a18503c990c634/clients/client-py/taskcluster/client.py#L514

I suspect that in my haste I assumed that
[https://github.com/taskcluster/taskcluster/pull/4255/files#diff-4473111af54703e1b315989a29a278fd8c144ac1f360804d07dd1a45a6ec09e8](this test) verified the correct functionality, when it is testing a function too low in the abstraction hierarchy.

**Comment by escapewindow** [comment]
Heh, this may be [my bug](https://github.com/taskcluster/taskcluster-client.py/commit/83c53dcea46619858f5bd195feafee7a9a081689)

**Comment by marco-c** [comment]
The reviewbot is supposedly using the latest version, https://github.com/mozilla/code-review/blob/7174ecbf3216c03b5ca0a373926319705b25b0a2/tools/requirements.txt#L11.eeee

**Comment by marco-c** [comment]
The aiohttp docs (https://docs.aiohttp.org/en/stable/client_reference.html) state that redirects are followed if `allow_redirects` is set to True, and it is set to True by default.

I see https://github.com/taskcluster/taskcluster/blob/66941613e4242d69dd2aff3fb560359eb633d59c/clients/client-py/taskcluster/aio/asyncutils.py#L96 is not setting it to False, so it should follow redirects automatically.

I still don't understand the behavior difference between ahal's local run and the bot runs.
