### ISSUE TITLE
`cacheOverRestarts` doesn't refresh credentials when they expire

### ISSUE THREAD

**Issue by Eijebong** [taskcluster/taskcluster#5011]
Deployed a static runner with some help from https://github.com/mozilla/community-tc-config/blob/main/imagesets/generic-worker-win2016/bootstrap.ps1

After a few days, the runner stopped working because its credentials had expired. Removing its config file didn't fix it. Removing `cacheOverRestarts` from the worker-runner did fix it.

Windows 10, up to date
Runner version: 44.2.2

**Comment by djmitche** [comment]
Do you happen to have any logs around from this period?  In particular, I'd like to see from the worker-runner logs if it renewed the credentials or not.  Also, what is the [lifecycle.reregistrationTimeout](https://docs.taskcluster.net/docs/reference/core/worker-manager/static) configuration for your worker pool?

Particular log lines of interest:

https://github.com/taskcluster/taskcluster/blob/8ee192f2d9876bb51661dd4f0d21cbb90253572f/tools/worker-runner/registration/registration.go#L95

https://github.com/taskcluster/taskcluster/blob/8ee192f2d9876bb51661dd4f0d21cbb90253572f/tools/worker-runner/registration/registration.go#L136

https://github.com/taskcluster/taskcluster/blob/8ee192f2d9876bb51661dd4f0d21cbb90253572f/tools/worker-runner/registration/registration.go#L152

https://github.com/taskcluster/taskcluster/blob/8ee192f2d9876bb51661dd4f0d21cbb90253572f/tools/worker-runner/registration/registration.go#L169

**Comment by Eijebong** [comment]
> Also, what is the lifecycle.reregistrationTimeout configuration for your worker pool?

Default, 4 days

Logs:

```
2021/11/29 13:37:30 Loading worker-runner configuration from c:\worker-runner\runner.yml
2021/11/29 13:37:30 Loading cached state from c:\generic-worker\start-worker-cache.json
2021/11/29 13:37:30 Identified as worker ci/windows-2
2021/11/29 13:37:30 Starting worker
2021/11/29 13:37:30 Worker credentials expire in -44h44m27s
2021/11/29 14:13:57 Loading worker-runner configuration from c:\worker-runner\runner.yml
2021/11/29 14:13:57 Loading cached state from c:\generic-worker\start-worker-cache.json
2021/11/29 14:13:57 Identified as worker ci/windows-2
2021/11/29 14:13:57 Starting worker
2021/11/29 14:13:57 Worker credentials expire in -45h20m54s
```

And then I fixed it by removing the cache and got:

```
2021/11/29 14:21:49 Loading worker-runner configuration from c:\worker-runner\runner.yml
2021/11/29 14:21:49 Configuring with provider static
2021/11/29 14:21:51 Identified as worker ci/windows-2
2021/11/29 14:21:51 Getting secrets from secrets service
2021/11/29 14:21:52 WARNING: No worker secrets for worker pool project/windows.
2021/11/29 14:21:52 Configuring for worker implementation generic-worker
2021/11/29 14:21:52 provider metadata local-ipv4 not available; not setting config privateIP
2021/11/29 14:21:52 provider metadata instance-type not available; not setting config instanceType
2021/11/29 14:21:52 provider metadata instance-id not available; not setting config instanceID
2021/11/29 14:21:52 provider metadata region not available; not setting config region
2021/11/29 14:21:52 provider metadata availability-zone not available; not setting config availabilityZone
2021/11/29 14:21:52 provider metadata public-ipv4 not available; not setting config publicIP
2021/11/29 14:21:52 Writing files
2021/11/29 14:21:52 Starting worker
2021/11/29 14:21:52 Worker credentials expire in 95h59m59s
```

**Comment by djmitche** [comment]
Huh, well, -45h20m54s is a long time ago :)

**Comment by djmitche** [comment]
Is it possible that this worker was off for four days?  In general, if a worker is absent for a long time, it can't start back up again.  

But for a static worker, we might be able to make this work.  The weird bit is that it needs to call RegisterWorker again, rather than ReregisterWorker.  Which is roughly what removing the cache accomplishes.

Rather than do that automatically, I think it will be easier to have worker-runner fail with a useful error message in that condition.  Does that sound like a good compromise?

**Comment by Eijebong** [comment]
Sounds good to me yes.

The worker was off over a weekend because it's still in a test phase and running on my work computer.
