### ISSUE TITLE
Rust client CI fails

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#5016]
The Rust worker's CI is failing frequently, e.g., in https://github.com/taskcluster/taskcluster/pull/4958

**Comment by djmitche** [comment]
@petemoore if you want to assign this to me, I can take a look.

**Comment by petemoore** [comment]
Thanks Dustin!

**Comment by djmitche** [comment]
This is intermittent, and I'm having a hard time reproducing it locally.  I may resort to adding some debug output and waiting for it to fail in CI.

**Comment by djmitche** [comment]
Locally, I can't even reproduce this running in a tight cycle or running the whole test suite (in case there's something "leaking" between test cases).

**Comment by djmitche** [comment]
(I tried running the docker container locally, too, to no avail)

**Comment by djmitche** [comment]
No failures on main since this landed :(

**Comment by djmitche** [comment]
I tried running a few of these on the tutorial worker -- https://community-tc.services.mozilla.com/tasks/groups/GluSZhtQR7uCHqz4bCcPgg

**Comment by djmitche** [comment]
```
running 5 tests
test factory::test::cursor_reader_twice ... ok(B
test test::small_data_inline_upload ... ok(B
test test::large_data_inline_upload ... ok(B
test factory::test::file_reader_twice ... FAILED(B
test test::put_url ... ok(B
failures:
---- factory::test::file_reader_twice stdout ----
thread 'factory::test::file_reader_twice' panicked at 'assertion failed: `(left == right)`
  left: `[]`,
 right: `[72, 69, 76, 76, 79, 47, 87, 79, 82, 76, 68]`', upload/src/factory.rs:87:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
That's not the error I was trying to reproduce :(

**Comment by djmitche** [comment]
@petemoore is this still failing frequently?

**Comment by djmitche** [comment]
I'm assuming this is more-or-less fixed..
