### ISSUE TITLE
"e is undefined" when viewing task

### ISSUE THREAD

**Issue by mitchhentges** [taskcluster/taskcluster#504]
**Describe the bug**
Viewing [this task](https://taskcluster-web.netlify.com/tasks/cL0g7J-ERDiB8Vws7XvMhA) doesn't show me my information, but instead shows the error "e is undefined"

**To Reproduce**
I'm not sure why [this task](https://taskcluster-web.netlify.com/tasks/cL0g7J-ERDiB8Vws7XvMhA) is special, but it shows the error

**Expected behavior**
Show the task contents rather than the error

**Platform (please complete the following information):**
 - OS: Ubuntu 18.10
 - Firefox @ 66.0.2

**Comment by mitchhentges** [comment]
The task is now loading properly for me.
When I checked the Firefox console, there was no additional exception information.

Was this logged into an external exception-tracking system, like Sentry, so you have enough information?
Alternatively, is there some way I can collect more information and post it here next time this happens?

**Comment by helfi92** [comment]
We used to have sentry but was disabled. I'll work in setting up something to log into Stackdriver. For now, reporting the errors from the console is the only option.

**Comment by helfi92** [comment]
Filed https://github.com/taskcluster/taskcluster/issues/604.
