### ISSUE TITLE
pagination of artifacts list broken, switching to second page does not work

### ISSUE THREAD

**Issue by Archaeopteryx** [taskcluster/taskcluster#5045]
**Describe the bug**
Pages for a task contain a list of artifacts. If there are more than 1000 artifacts, pagination kicks in and only the first 1000 are shown. To navigate the list of tasks, the user has to click on `>`.

**To Reproduce**

1. Go to https://firefox-ci-tc.services.mozilla.com/tasks/VooOdpPAQsK2xFYyH2uDOQ#artifacts
2. On the right, expand "Artifacts".
3. Go to bottom of the artifacts list.
4. Click `>`.
5. Nothing changes.

**Expected behavior**
Switch to next watch of artifacts

**Taskcluster version**
43.2.0

**Additional context**
Retrieving the second batch [works with the API](https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/VooOdpPAQsK2xFYyH2uDOQ/runs/0/artifacts?continuationToken=WyJWb29PZHBQQVFzSzJ4Rll5SDJ1RE9RIiwwLCJwdWJsaWMvdGVzdF9pbmZvL2Jyb3dzZXJ0aW1lLXJlc3VsdHMvY25uLW5hdi93aW5kb3dyZWNvcmRpbmctMTY0MTgzMDExNjcyMC41Mi9mcmFtZS05NjktNTgyNzIucG5nIl0) ([first batch](https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/VooOdpPAQsK2xFYyH2uDOQ/runs/0/artifacts)).

The query to the graphql endpoint reports a bad request. Request data:
```
{"operationName":"PageArtifacts","variables":{"runId":0,"taskId":"VooOdpPAQsK2xFYyH2uDOQ","artifactsConnection":{"limit":1000,"cursor":"WyJWb29PZHBQQVFzSzJ4Rll5SDJ1RE9RIiwwLCJwdWJsaWMvdGVzdF9pbmZvL2Jyb3dzZXJ0aW1lLXJlc3VsdHMvY25uLW5hdi93aW5kb3dyZWNvcmRpbmctMTY0MTgzMDExNjcyMC41Mi9mcmFtZS05NjktNTgyNzIucG5nIl0=","previousCursor":"$$FIRST$$"}},"query":"query PageArtifacts($taskId: ID!, $runId: Int!, $connection: PageConnection!) {\n  artifacts(taskId: $taskId, runId: $runId, connection: $connection) {\n    ...Artifacts\n    __typename\n  }\n}\n\nfragment Artifacts on ArtifactsConnection {\n  pageInfo {\n    hasNextPage\n    hasPreviousPage\n    cursor\n    previousCursor\n    nextCursor\n    __typename\n  }\n  edges {\n    node {\n      name\n      contentType\n      __typename\n    }\n    __typename\n  }\n  __typename\n}\n"}
```

**Comment by Eijebong** [comment]
Response says `message: Variable "$connection" of required type "PageConnection!" was not provided.`

**Comment by Eijebong** [comment]
https://github.com/taskcluster/taskcluster/blob/main/ui/src/views/Tasks/ViewTask/index.jsx#L261

Shouldn't this be `connection` instead? Looks like it was changed in 11769844ce2b0cd66b3c2fe8a62192a376160da0 but the query wasn't updated to match the name.
