### ISSUE TITLE
When rerunning an action, it would be nice if the UI would automatically show the newly created run

### ISSUE THREAD

**Issue by Eijebong** [taskcluster/taskcluster#5046]
Right now it creates the run but doesn't switch to it, requiring me to click on the right arrow. Would be nice if it did that on its own

**Comment by lotas** [comment]
@Eijebong can you please confirm that this is still a thing? Trying locally, works fine. 
Although status updates are not being reflected automatically, but at least UI switches to the latest run

**Comment by lotas** [comment]
Ah I see.. there are some steps missing to reproduce it.

So what I've found if you just open the task page and rerun it, it goes to new step.
If you manually switch to some step, url gets update, and reruning a task no longer takes you to the next run.
