### ISSUE TITLE
Shell Client installation links are broken in README

### ISSUE THREAD

**Issue by matt-boris** [taskcluster/taskcluster#5063]
It appears to be due to the version using the latest _tag_ as opposed to _release_ version in the url.

See [here](https://github.com/taskcluster/taskcluster/tree/fdf6c822f1554159e4e361f73b0a64dba3f512a6/clients/client-shell#installation) for example.

Try visiting the link in the `curl` command: https://github.com/taskcluster/taskcluster/releases/download/v44.4.0/taskcluster-darwin-amd64 to verify the 404.

**Comment by djmitche** [comment]
I think the issue is that the releases have failed -- the latest (44.4.0) got partway finished but never actually published the release.  [Here](https://github.com/taskcluster/taskcluster/runs/4818067948) is the failed check.  @petemoore is there an issue tracking those problems?

**Comment by matt-boris** [comment]
Fixed with https://community-tc.services.mozilla.com/tasks/BuTi1jBmSPmZe7WY856XKA/
