### ISSUE TITLE
investigate running multiple worker-managers

### ISSUE THREAD

**Issue by escapewindow** [taskcluster/taskcluster#5064]
This is related to https://github.com/taskcluster/taskcluster-rfcs/issues/170 in that it's aimed at addressing worker-manager slowness, but we may or may not want this if we end up solving the slowness problem in some other way.

Since the Azure cloud processes slow down worker-manager (#4999) and that slows down all provisioning, that suggests that splitting the Azure worker management into a separate worker-manager process might isolate the issues to only Azure workers. If we take this further, it might make sense to have a worker-manager instance per cloud.

**Comment by djmitche** [comment]
I don't think this needs process isolation.

The architecture right now, is to [loop over worker pools and provision each one in turn](https://github.com/taskcluster/taskcluster/blob/fdf6c822f1554159e4e361f73b0a64dba3f512a6/services/worker-manager/src/provisioner.js#L123-L188).  That means, when it comes time to do a worker pool with a provisioner for a slow cloud (e.g., Azure), the other worker pools must wait.

It's clear this was not a good design decision!  It's possible that just parallelizing that loop (so, provision all worker pools in parallel) would address the issues here, but that's a bit of a complex change and I think it would warrant some thought about the larger consequences.  For example, would a huge EC2 worker pool (like testers) end up triggering rate limiting that would leave smaller EC2 pools starved for API access?  Would it still make sense to wait for all worker pools to complete a round of provisioning before starting the next round, or should they all just iterate independently?  If the latter, then some of the bookkeeping (particularly around `seen`) get a bit more complex.

**Comment by escapewindow** [comment]
Awesome :)

**Comment by djmitche** [comment]
(oh, and I think you meant worker-manager in the issue title?)

**Comment by djmitche** [comment]
See also #4810

**Comment by petemoore** [comment]
@escapewindow is it ok to close this issue in favour of #4810?

**Comment by escapewindow** [comment]
Yes :)
