### ISSUE TITLE
Right-click on links opens them

### ISSUE THREAD

**Issue by owlishDeveloper** [taskcluster/taskcluster#508]
**Description**
When you right-click on the link to see the context menu, it will show the context menu, but also navigate.

**To Reproduce**
1. Go to anywhere in the documentation on the new website (for example https://taskcluster-web.netlify.com/docs/manual/task-execution/queues )
2. Right-click on any link to another page within the docs (for example, on the above page, "queue service" link on the first line of text)
3. Observe being navigated to the linked page

**Expected behavior**
Right-click should not trigger navigation, only the context menu

**Platform**
 - OS X
 - Browser FF 65.01

**Comment by helfi92** [comment]
It seems to work on Chrome but not on Firefox.

**Comment by SimonSapin** [comment]
Middle click also navigates instead of opening a new tab.
