### ISSUE TITLE
When rerunning an action, its status doesn't update until the page gets refreshed

### ISSUE THREAD

**Issue by Eijebong** [taskcluster/taskcluster#5086]
- Rerun any action from the web interface
- Click on the `next` button (#5046 this step should not be needed)
- The action stays `Pending` forever until you refresh the page. It's worth noting that this is just visual, the task is properly scheduled.

**Comment by Eijebong** [comment]
This doesn't seem to happen when there are no available runners at the time of clicking rerun

**Comment by lotas** [comment]
Page was not listening to state updates and was simply using poll to re-fetch task every xx seconds, maybe that refetch was also not working properly. Latest fix from #5625 adds subscription to status updates, and reloads task with proper status information automatically on any task-related change. 

Btw, this subscription requires that anonymous role has `queue:get-task:*` (or currently logged in client)

**Comment by lotas** [comment]
I believe that was fixed with #5625, will close this
