### ISSUE TITLE
Copying artifact links in task UI should be simple

### ISSUE THREAD

**Issue by ahal** [taskcluster/taskcluster#5181]
**Describe the bug**
It's difficult to copy an artifact link (rather than downloading / opening it) from the task UI.

**To Reproduce**

1. Open a task in the UI, e.g: https://firefox-ci-tc.services.mozilla.com/tasks/HkcTlRWqSwGV9x1Oy9lOfQ#artifacts
2. Try to copy the artifact link
3. The only way to do so is to right click and use the browser's context menu (e.g "Copy Link Address" in Firefox).
4. This URL includes the `bewit` parameter which means if you send it to someone else, they won't be able to open it
5. So you first need to paste the URL into somewhere editable and manually remove the query parameter

**Expected behavior**

Copying the artifact URL should be easy.

**Additional Context**

In Releng we often just want to link people to the artifact. E.g, linking to the signed build in the task above.

**Comment by petemoore** [comment]
How about something like a copy button? e.g. like [this one](https://www.crushpixel.com/big-static15/preview4/copy-file-icon-duplicate-document-2141618.jpg)

**Comment by escapewindow** [comment]
I *think* the bewit showing up, even if it's a public URL, might have been a side effect of the [anonymous role](https://github.com/taskcluster/taskcluster/blob/66941613e4242d69dd2aff3fb560359eb633d59c/ui/docs/manual/deploying/anonymous-role.mdx). If, like in the firefoxci cluster, we grant the anonymous role to non-logged-in users, it might be best to skip the bewit.

**Comment by ahal** [comment]
Either a copy button or removing the `bewit` parameter make sense to me. Possible a copy button might be useful regardless, but I'm no UX designer :)

**Comment by lotas** [comment]
Started this https://github.com/taskcluster/taskcluster/pull/5218 
Will need to check which artifacts have `bewit` param, cannot see any locally
