### ISSUE TITLE
[UI] Group with task that failed with exception shows green favicon

### ISSUE THREAD

**Issue by mitchhentges** [taskcluster/taskcluster#519]
**Describe the bug**
[This task group](https://taskcluster-web.netlify.com/tasks/groups/JpzmQxqFTK2KlKsRDoUh6Q) has a task with the "exception" status, but the favicon for the group is still green.

This affects me because I see my taskcluster task with the green icon, I think "oh good, it passed!", but when I actually view the tab, I see that not all the builds are green

**To Reproduce**
1. Go to [this task group](https://taskcluster-web.netlify.com/tasks/groups/JpzmQxqFTK2KlKsRDoUh6Q)

**Expected behavior**
Only show a green icon if all the builds are green.
Show a red icon if any of the tasks have the "exception" status.

**Platform (please complete the following information):**
 - OS: Linux
 - Browser if applicable: Firefox
 - Version if applicable: 66

**Comment by helfi92** [comment]
Good catch! Sending a fix now.
