### ISSUE TITLE
CI needs to run/test `yarn build`

### ISSUE THREAD

**Issue by matt-boris** [taskcluster/taskcluster#5193]
**Describe the bug**

When releasing v44.6.0, we found a couple (at least) bugs in the build of the docker image due to us not running this task at PR creation time.

**To Reproduce**

1. Run `yarn build`

**Expected behavior**

Image can be built successfully. We need to be doing this on each PR so we know when things are breaking before we go to release.

**Taskcluster version**

v44.6.0

**Comment by lotas** [comment]
Could be possibly caused by this recent change: https://github.com/taskcluster/taskcluster/commit/20b868e827072de606197bcfb51198f9a5114c6b

**Comment by djmitche** [comment]
[There is a `yarn build` task](https://github.com/taskcluster/taskcluster/blob/8ed0f3ff45225ee6d7dc8dbe395e13e4990375c6/taskcluster/ci/meta/kind.yml#L37-L41).  So I guess the question is, how did it not find this error.  I'm not sure what the error was, so I can't say more.

I wouldn't suggest getting _too_ deep into trying to do a "fake" release on every push -- you'll quickly end up adding more code than you're testing.

Note that there's also a staging-release process.  If changes have landed that have you wondering if the release process is going to break, that will be a much more reliable way to check the process before doing a "real" release.  It pushes packages and images to lots of package registries, though, and I suspect doing that on every CI run will quickly get you in trouble with all of them.

**Comment by lotas** [comment]
@djmitche the problem was actually in the UI part of the application. Webpack was missing some config, so `yarn build` in `ui/` failed at release time. 
I'm not sure if top level `yarn build` was broken here at all.
