### ISSUE TITLE
reduce number of clicks to get to the log

### ISSUE THREAD

**Issue by escapewindow** [taskcluster/taskcluster#5217]
From the [community meeting notes](https://docs.google.com/document/d/1dCQScxwH04VInIntxesYVQ8te1IvLTZXWYrHNgi1Irc/edit):

[ahal] especially from Github
- [x] Link from checks UI
- [ ] Tail of the log
  - Idea: load last N lines through web-server
  - Idea: Show last N lines of logs on failed tasks in the task definition page

Personally, I almost never want the log UI, and almost always want the raw log. Having to click through to the log UI and then to the raw log is extra clicks I'd prefer to skip.

**Comment by escapewindow** [comment]
For the Github UI portion, IIRC we're able to add some text to each of the tasks in the checks view? Adding a log tail to that view may be a solution before we even get to the TC UI.

**Comment by ahal** [comment]
Yes, I looked into the checks API awhile back for this very purpose. We can add arbitrary [markdown formatted text](https://docs.github.com/en/rest/reference/checks#output-object). So a log tail + direct link to the log would be very helpful.

**Comment by lotas** [comment]
todo: check if there is a 64kb limit for a check run description

**Comment by matt-boris** [comment]
Introduced last 250 lines of `live.log` in GH checks UI in [v44.20.0](https://github.com/taskcluster/taskcluster/releases/tag/v44.20.0).
