### ISSUE TITLE
Update development documentation

### ISSUE THREAD

**Issue by lotas** [taskcluster/taskcluster#5221]
We need to update https://github.com/taskcluster/taskcluster/blob/main/dev-docs/development-process.md as described workflow is not working at the moment.

**Problem**: when running only web-server locally, it will fail talking to other microservices, so `/graphql` calls will fail with errors like:

```
Cannot GET /api/queue/v1/task/LfTWgh0LS3aa3RKGB5rPdg
404
```

Possible solutions:

1. Create stubs/mocks for such calls in local development
2. Launch all dependent services
    * using `docker-compose` 
    * or running all natively 

TODO:
- [ ] fix local dev environment
- [ ] update documentation on how to use it properly

**Comment by djmitche** [comment]
The intent in that document is to have web-server call out to a "real" deployment -- either community-tc or staging or a dev env.  Setting TASKCLUSTER_ROOT_URL should allow that, so I suspect you've set that variable incorrectly?

**Comment by lotas** [comment]
hmm.. I will try again, possibly I misunderstood the purpose of web-server. I thought it was only using database.
