### ISSUE TITLE
Hide pagination in the artifacts list unless there's more than 1000

### ISSUE THREAD

**Issue by Eijebong** [taskcluster/taskcluster#5246]
Right now the pagination arrows are present even if there's only one artifact, it looks a bit silly IMO. I think 1000 is the page limit

![92625813-7239-445a-b03a-31629dcc1337](https://user-images.githubusercontent.com/3650385/156143609-b31e25d5-79df-487e-9f66-c6a3e38e427f.png)

**Comment by lotas** [comment]
Thanks for QA, fix coming ;)

**Comment by Eijebong** [comment]
This was fixed by #5248
