### ISSUE TITLE
worker-runner credential renewal does not work if the system goes to sleep

### ISSUE THREAD

**Issue by Eijebong** [taskcluster/taskcluster#5269]
After having a windows multi-user worker running idle for a while, credentials expired and were not refreshed by start-worker meaning it was stuck and not accepting tasks anymore. start-worker should refresh those credentials and restart the worker I guess.

**Comment by djmitche** [comment]
Do you have logs from worker-runner?  It is designed to refresh credentials, so this shouldn't happen.

**Comment by Eijebong** [comment]
```
2022/03/06 12:13:04Z Could not claim work. 
CALL SUMMARY
============
Method: POST
Service: divvun-tc.thetc.se:
Response Body:
{
  "code": "AuthenticationFailed",
  "message": "ext.certificate.expiry < now\n\n---\n\n* method:     claimWork\n* errorCode:  AuthenticationFailed\n* statusCode: 401\n* time:       2022-03-06T12:13:04.935Z",
  "requestInfo": {
    "method": "claimWork",
    "params": {
      "0": "divvun/windows",
      "taskQueueId": "divvun/windows"
    },
    "payload": {
      "tasks": 1,
      "workerGroup": "ci",
      "workerId": "windows-2"
    },
    "time": "2022-03-06T12:13:04.935Z"
  }
}
Attempts: 1
(Permanent) HTTP response code 401
HTTP/2.0 401 Unauthorized
```

Got that a lot from generic-worker but nothing between 

```
2022/02/28 12:48:17 Writing files
2022/02/28 12:48:17 Starting worker
2022/02/28 12:48:17 Worker credentials expire in 95h59m59s
```

and 

```
2022/03/08 12:03:58 Loading worker-runner configuration from c:\worker-runner\runner.yml
2022/03/08 12:03:58 Configuring with provider static
2022/03/08 12:03:58 Identified as worker ci/windows-2
2022/03/08 12:03:58 Getting secrets from secrets service
2022/03/08 12:03:58 WARNING: No worker secrets for worker pool divvun/windows.
2022/03/08 12:03:58 Configuring for worker implementation generic-worker
```

**Comment by Eijebong** [comment]
Got 3 workers that didn't get any work for a week, and they all show the same thing

**Comment by djmitche** [comment]
OK, so according to that expiration message on 2022/02/28 12:48:17 the credentials expire 2022/03/04 12:48:16.  The renewal should happen 30 minutes before that time, so 2022/03/04 12:18:16.  At that time, 
https://github.com/taskcluster/taskcluster/blob/133b5db07c1b0f76be813b34901f323457734ae9/tools/worker-runner/registration/registration.go#L121-L136
should run.  That should either reregister, which would log:
https://github.com/taskcluster/taskcluster/blob/133b5db07c1b0f76be813b34901f323457734ae9/tools/worker-runner/registration/registration.go#L145
..or terminate, which would log:
https://github.com/taskcluster/taskcluster/blob/133b5db07c1b0f76be813b34901f323457734ae9/tools/worker-runner/registration/registration.go#L201
..or panic:
https://github.com/taskcluster/taskcluster/blob/133b5db07c1b0f76be813b34901f323457734ae9/tools/worker-runner/registration/registration.go#L131

I'm confused why none of that occurred.. and why there's no logging at all for another four days.  Any hints?

**Comment by Eijebong** [comment]
I have some suspicion on the windows VMs somehow not respecting my `don't go to S3-S5` power state and having a software low power state.

I have this on my VM config (libvirt):

```
  <pm>
    <suspend-to-disk enabled='no'/>
    <suspend-to-mem enabled='no'/>
  </pm>
```

but never explicitly setup windows not to go to sleep. Even if that was the reason I would still expect start-worker to realize that and refresh the credentials though

**Comment by djmitche** [comment]
Credentials can't be refreshed after they expire.  I'm surprised it didn't _try_ on waking up, though.  Maybe timers stop when sleeping?

**Comment by djmitche** [comment]
Huh, they do.  WTF.  This is the output of a script that logs every second, and sets a 60-second timer.  You can see where my laptop went to sleep (TIL it takes a _long_ time for the laptop to get around to actually sleeping) by the break in the 1-second logs, but then the timer doesn't expire until 60 _waking_ seconds have expired.  Note, too, that the `m` value (presumably the monotonic clock) doesn't continue to increment during the sleep.  I can confirm that this is the case at least back to Go1.15.  

```
timer starting 2022-03-08 19:12:46.457890739 -0500 EST m=+0.000015024
tick 2022-03-08 19:12:47.458122325 -0500 EST m=+1.000246649
tick 2022-03-08 19:12:48.458284228 -0500 EST m=+2.000408549
tick 2022-03-08 19:12:49.45838036 -0500 EST m=+3.000504687
tick 2022-03-08 19:12:50.458570463 -0500 EST m=+4.000694785
tick 2022-03-08 19:12:51.458787852 -0500 EST m=+5.000912175
tick 2022-03-08 19:12:52.458897958 -0500 EST m=+6.001022281
tick 2022-03-08 19:12:53.45899595 -0500 EST m=+7.001120272
tick 2022-03-08 19:12:54.459210313 -0500 EST m=+8.001334635
tick 2022-03-08 19:12:55.460373426 -0500 EST m=+9.002497753
tick 2022-03-08 19:12:56.460547374 -0500 EST m=+10.002671707
tick 2022-03-08 19:12:57.460778154 -0500 EST m=+11.002902478
tick 2022-03-08 19:12:58.460947141 -0500 EST m=+12.003071467
tick 2022-03-08 19:12:59.461169051 -0500 EST m=+13.003293377
tick 2022-03-08 19:13:00.461383151 -0500 EST m=+14.003507479
tick 2022-03-08 19:13:01.461641971 -0500 EST m=+15.003766294
tick 2022-03-08 19:13:02.461880118 -0500 EST m=+16.004004441
tick 2022-03-08 19:13:03.462099529 -0500 EST m=+17.004223853
tick 2022-03-08 19:13:04.462362516 -0500 EST m=+18.004486840
tick 2022-03-08 19:13:05.462578777 -0500 EST m=+19.004703104
tick 2022-03-08 19:13:06.462808437 -0500 EST m=+20.004932764
tick 2022-03-08 19:13:07.463044051 -0500 EST m=+21.005168375
tick 2022-03-08 19:13:08.463319428 -0500 EST m=+22.005443752
tick 2022-03-08 19:13:09.463388574 -0500 EST m=+23.005512899
tick 2022-03-08 19:13:10.463499215 -0500 EST m=+24.005623540
tick 2022-03-08 19:13:11.463999405 -0500 EST m=+25.006123728
tick 2022-03-08 19:13:12.464197978 -0500 EST m=+26.006322300
tick 2022-03-08 19:13:13.464459368 -0500 EST m=+27.006583685
tick 2022-03-08 19:13:14.464558242 -0500 EST m=+28.006682560
tick 2022-03-08 19:13:15.464660233 -0500 EST m=+29.006784556
tick 2022-03-08 19:13:16.464759853 -0500 EST m=+30.006884174
tick 2022-03-08 19:13:17.464977704 -0500 EST m=+31.007102053
tick 2022-03-08 19:13:18.465684142 -0500 EST m=+32.007808465
tick 2022-03-08 19:16:34.108206518 -0500 EST m=+34.402415475
tick 2022-03-08 19:16:35.10889196 -0500 EST m=+35.403100877
tick 2022-03-08 19:16:36.109092187 -0500 EST m=+36.403301143
tick 2022-03-08 19:16:37.109172589 -0500 EST m=+37.403381544
tick 2022-03-08 19:16:38.109276118 -0500 EST m=+38.403485069
tick 2022-03-08 19:16:39.1094165 -0500 EST m=+39.403625416
tick 2022-03-08 19:16:40.109480081 -0500 EST m=+40.403689036
tick 2022-03-08 19:16:41.109571182 -0500 EST m=+41.403780133
tick 2022-03-08 19:16:42.109679313 -0500 EST m=+42.403888298
tick 2022-03-08 19:16:43.109852121 -0500 EST m=+43.404061078
tick 2022-03-08 19:16:44.110042256 -0500 EST m=+44.404251213
tick 2022-03-08 19:16:45.110262681 -0500 EST m=+45.404471639
tick 2022-03-08 19:16:46.110484394 -0500 EST m=+46.404693347
tick 2022-03-08 19:16:47.110727301 -0500 EST m=+47.404936255
tick 2022-03-08 19:16:48.110936886 -0500 EST m=+48.405145843
tick 2022-03-08 19:16:49.111171026 -0500 EST m=+49.405379994
tick 2022-03-08 19:16:50.112272204 -0500 EST m=+50.406481155
tick 2022-03-08 19:16:51.112375798 -0500 EST m=+51.406584755
tick 2022-03-08 19:16:52.112523421 -0500 EST m=+52.406732380
tick 2022-03-08 19:16:53.112613966 -0500 EST m=+53.406822917
tick 2022-03-08 19:16:54.11280294 -0500 EST m=+54.407011899
tick 2022-03-08 19:16:55.112894878 -0500 EST m=+55.407103795
tick 2022-03-08 19:16:56.113037848 -0500 EST m=+56.407246803
tick 2022-03-08 19:16:57.113126033 -0500 EST m=+57.407334987
tick 2022-03-08 19:16:58.113214094 -0500 EST m=+58.407423047
tick 2022-03-08 19:16:59.113376354 -0500 EST m=+59.407585311
timer expired 2022-03-08 19:16:59.706141289 -0500 EST m=+60.000350206
tick 2022-03-08 19:17:00.113694361 -0500 EST m=+60.407903310
tick 2022-03-08 19:17:01.113964224 -0500 EST m=+61.408173180
```

**Comment by djmitche** [comment]
https://pkg.go.dev/time#hdr-Monotonic_Clocks
> On some systems the monotonic clock will stop if the computer goes to sleep. On such a system, t.Sub(u) may not accurately reflect the actual time that passed between t and u. 

apparently "some systems" include Linux and Windows :(

**Comment by djmitche** [comment]
@lotas any chance you can update the title of this issue?  Perhaps "worker-runner credential renewal does not work if the system goes to sleep"?

I suspect that the best we can do here is some kind of workaround like sleeping for one minute at most, and re-calculating the expiration offset at that time.  That is, _if_ we need to fix this.  It's worth noting that a host which sleeps past its credential expiration is totally out of luck.  WDYT?  Fix it or document that hosts with running workers shouldn't sleep?

**Comment by petemoore** [comment]
> Credentials can't be refreshed after they expire. I'm surprised it didn't _try_ on waking up, though. Maybe timers stop when sleeping?

https://github.com/golang/go/issues/23178
