### ISSUE TITLE
Github badges are not very distinguishable between error/success

### ISSUE THREAD

**Issue by Eijebong** [taskcluster/taskcluster#5271]
There's no color difference between the badges.

While the cat is cute I don't think it's very helpful to distinguish different states. IMO badges should be changed to match the github ones (green/red/yellow) to be recognizable.

**Comment by snomos** [comment]
See https://github.com/divvun/registry#languages for an example of how this makes it hard to see the build status of multiple repos at a glance.

**Comment by lotas** [comment]
How about #5279 ?

**Comment by snomos** [comment]
I like it, it is much improved. If the emojis at the end are being kept, I would prefer more differentiation between the error and the success cats, but other than that this looks good to me 👍

**Comment by lotas** [comment]
Thanks @snomos I'm not sure my designer skills would allow me to change cats :) but let me try some colors for them, too

**Comment by snomos** [comment]
One final comment: should there be a separate message/colour/emoji for "timed out" errors? Those are not real errors, rather a sign of another issue.

**Comment by lotas** [comment]
Hmm. Not sure what are they. @Eijebong you were recently adding functionality there, do you know which condition corresponds to the "timed out" errors?

**Comment by Eijebong** [comment]
Pretty sure `timed_out` is not handled right now. The badge would probably 404 if all tasks time out or return the wrong status if any other task has succeeded/failed.

We have a mapping here between taskcluster task statuses and github check conclusions, you can clearly see `timed_out`.

https://github.com/taskcluster/taskcluster/blob/841aab318e282aaebddefa5adcce60da86d18ecb/services/github/src/constants.js#L2

The badge generation takes the status back from github here:

https://github.com/taskcluster/taskcluster/blob/841aab318e282aaebddefa5adcce60da86d18ecb/services/github/src/api.js#L414-L419

computes a few things if we have checks to set the status to the "group status", and then returns a badge based on that here:

https://github.com/taskcluster/taskcluster/blob/841aab318e282aaebddefa5adcce60da86d18ecb/services/github/src/api.js#L448

The only badges we have:

```
[eijebong@plutonium] ~/code/taskcluster/services/github (main) >>> fd -e svg
assets/error.svg
assets/failure.svg
assets/newrepo.svg
assets/pending.svg
assets/success.svg
```

So either we're missing `timed_out`, `action_required`, `neutral` support or I'm missing something

**Comment by lotas** [comment]
Ah, I see now, thanks! 
Yes, there are more statuses than we have files. Let me add those as well.

**Comment by lotas** [comment]
btw, looking at the page with builds, those emojis look "strange". Should we get rid of those or make less intrusive? 
I was thinking about adding "T" (TC) logo instead, and making all badges same dimensions

**Comment by lotas** [comment]
alright, spent some more time, added new states and badges
