### ISSUE TITLE
Scroll to the end of the logs by default

### ISSUE THREAD

**Issue by Eijebong** [taskcluster/taskcluster#5274]
When I look at logs it's usually because something's wrong. When something's wrong, the message saying what's wrong is usually at then end, not the beginning. It would save time to scroll down to the bottom of the logs as soon as I display it instead of staying at the beginning

**Comment by lotas** [comment]
I guess it is somewhat related to #5217 
Idea was discussed before, time to implement something :)

**Comment by matt-boris** [comment]
@lotas I was thinking a quick win would be to auto-enable the `Follow Log` button. That'll load the page at the bottom of the logs (and will follow the stream of logs if it's currently being written to which I feel is more beneficial than seeing the top of the logs).
