### ISSUE TITLE
`can't access property "length", r is undefined` on hooks page when you don't have hooks scopes

### ISSUE THREAD

**Issue by Eijebong** [taskcluster/taskcluster#5277]
Other pages tell you which scopes you're missing. The hooks page tells you `can't access property "length", r is undefined` instead.

**Comment by lotas** [comment]
Can you please add URL? Is it just `/hooks` or some specific hook?

**Comment by Eijebong** [comment]
It's on `/hooks`. https://divvun-tc.thetc.se/hooks

**Comment by lotas** [comment]
confirmed :) thanks
