### ISSUE TITLE
When hovering over a task in a group task, the background color should change for the whole row

### ISSUE THREAD

**Issue by Eijebong** [taskcluster/taskcluster#5295]
Right now it only changes for half the row and on a large screen, with lots of jobs I sometimes struggle to associate the status with the name.
![90262c84-f322-429d-8572-ed7f74f9ed83](https://user-images.githubusercontent.com/3650385/158612935-cd26d2de-fa07-4d73-a341-f7287ec5a863.png)

**Comment by ahmedDevs** [comment]
Hey, I'd like to work on this issue.

**Comment by lotas** [comment]
@ahmedDevs please do!
