### ISSUE TITLE
Signing in through github while on a task definitions gives `buildSignedUrl missing required credentials` when you get back to taskcluster

### ISSUE THREAD

**Issue by Eijebong** [taskcluster/taskcluster#5318]
- Go to any task page (i.e https://divvun-tc.thetc.se/tasks/W_ZMb3EtTkSwE1F-fdYSbA)
- Logout / Log back in through github oauth
- Enjoy your `buildSignedUrl missing required credentials`

Refreshing the page fixes the issue.
My instance has `sign_public_artifact_urls: true` in its config

**Comment by matt-boris** [comment]
Dup #4943
