### ISSUE TITLE
[UI] Date picker calendar icon

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#533]
STR:

1. Navigate to http://localhost:5080/secrets/create

Actual:

![Screen Shot 2019-04-02 at 6 41 23 PM](https://user-images.githubusercontent.com/3766511/55440879-1303dc00-5577-11e9-9acb-47777d6f1b8c.png)

Expected: The calendar icon is above the line

**Comment by arshadkazmi42** [comment]
I can take this up, if no one is working on it.

**Comment by helfi92** [comment]
Go for it :)

**Comment by arshadkazmi42** [comment]
on debugging this, I see icon is getting rendered here
https://github.com/taskcluster/taskcluster/blob/master/ui/src/components/DatePicker/index.jsx#L34

It looks like its some material component. Where can I modify the code for this? Or are we planning on developing a new component for this?

**Comment by helfi92** [comment]
I don't think the issue is with the CalendarIcon. I think adding `alignItems: center` on the parent element should fix it.

**Comment by helfi92** [comment]
![Screen Shot 2019-04-11 at 4 16 32 PM](https://user-images.githubusercontent.com/3766511/55990232-33b5eb00-5c75-11e9-861a-4ba725cd13b6.png)

**Comment by arshadkazmi42** [comment]
> ![Screen Shot 2019-04-11 at 4 16 32 PM](https://user-images.githubusercontent.com/3766511/55990232-33b5eb00-5c75-11e9-861a-4ba725cd13b6.png)

I cant seem to find this css in React code, I think its part of DatePicker component.

**Comment by helfi92** [comment]
I pushed a fix in https://github.com/taskcluster/taskcluster/pull/568/files. Have a look to see if it makes sense. Happy to answer any questions :)

**Comment by arshadkazmi42** [comment]
@helfi92 Yes, it does make sense, override the styles of the component. I was planning on doing something like this but wasn't so sure where exactly to start.
I was also thinking, that there is somewhere CSS available which we will be able to modify to fix this.

**Comment by helfi92** [comment]
>  I was also thinking, that there is somewhere CSS available which we will be able to modify to fix this.

Agreed. Sometimes components expose properties to override internal components but I don't think the DatePicker did so we had to rely on CSS specificity to override the style.
