### ISSUE TITLE
[UI] Streamline trigger-hook flow

### ISSUE THREAD

**Issue by mitchhentges** [taskcluster/taskcluster#534]
From my usage of the Taskcluster UI so far, I have triggered hooks hundreds of times, but I've never supplied a custom `context`. Therefore, I'm making the broad assumption that, perhaps, supplying a `context` is an edge case?

If so, perhaps the hook-triggering UI can be optimized for the case where the `context` isn't edited. I'd love to avoid the think-and-click that happens every time the hook-trigger dialog comes up.

(One method would be to have two buttons: trigger hook, and trigger hook (with options) - though this has downsides in usability and complexity. :man_shrugging: )

What do you think? :thinking:

**Comment by helfi92** [comment]
I think we can have the initial focus be on the "Trigger Hook" button when opening the modal assuming that most hooks are triggered with an empty context. This would allow people to press the enter key right after the trigger hook dialog opens up.

**Comment by shubhamgupta2956** [comment]
@helfi92 I want to take this issue. Please assign it to me. Thanks

**Comment by shubhamgupta2956** [comment]
@helfi92 what I can understand in it is that we want the initial focus on the "TRIGGER HOOK" button in the dialog that opens so that the user just can press enter to trigger hook. But this thing is implemented in the code. Can you please explain me what we want to solve in this issue.

**Comment by helfi92** [comment]
> what I can understand in it is that we want the initial focus on the "TRIGGER HOOK" button in the dialog that opens so that the user just can press enter to trigger hook.

That's right!

> But this thing is implemented in the code. Can you please explain me what we want to solve in this issue. I am a bit confused.

Pressing "enter" might trigger a hook but the user doesn't know that. We want to show the ripple in the button to let the user know that the button is focused:

![Screen Shot 2019-06-25 at 7 06 54 PM](https://user-images.githubusercontent.com/3766511/60139616-8d11be80-977c-11e9-8afd-eccdf768c479.png)

**Comment by helfi92** [comment]
How is it going @shubhamgupta2956? Let me know if you had any questions :)

**Comment by shubhamgupta2956** [comment]
Sorry for inactivity @helfi92.

I had tried to search for the problem. Not sure but it seems that when we open dialog action, it takes it like the dialog box was in the same page and thus disables ripple effect. I am still confused about it and searching for proper solution.

**Comment by shubhamgupta2956** [comment]
@helfi92 am I going in correct direction. Is my assumption correct as I can hardly find any solution for it. Please suggest me in what direction should I go. Thanks.

**Comment by helfi92** [comment]
According to https://material-ui.com/api/button-base/#props, I think we should be able to add the focus ripple effect via the action prop:

```jsx
<Button action={actions => actions.focusVisible()}  ... />
```

Hopefully that helps.

**Comment by helfi92** [comment]
Resolved in 8b32ca1. Thank you @shubhamgupta2956 for your work.

**Comment by shubhamgupta2956** [comment]
Thanks @helfi92. Can you suggest what should I do next.

**Comment by helfi92** [comment]
Do you want to work on https://github.com/taskcluster/taskcluster/issues/965? Thank you for wanting to offer your help btw. It is very appreciated :)
