### ISSUE TITLE
Worker Manager should publish pulse message when worker is registered

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#5344]
Currently Worker Manager only publishes pulse messages when Worker Pool definitions are created or modified (not sure if deletions are also published?).

Ideally pulse messages would be published too for Worker state changes (e.g. worker spawned, worker claimed its credentials).

It could even be possible to have a service listening to these events and combining them with queue events to track all known workers, and the state they are in, and use its own database for this, rather than adding any load to Worker Manager to manage this state. Whether we eventually offload this to another service or not, the starting point would be publishing information to pulse about worker creation/registration.

**Comment by lotas** [comment]
that was implemented already
