### ISSUE TITLE
Copy artifact URL button is clipping the wrong link

### ISSUE THREAD

**Issue by ahal** [taskcluster/taskcluster#5348]
**Describe the bug**
When clicking the "Copy" button next to an artifact, the text copied to the clipboard looks similar to:
https://firefox-ci-tc.services.mozilla.comhttps//firefox-ci-tc.services.mozilla.com/api/queue/v1/task/M0BdslNvR1KAQ7F-u2or0Q/runs/1/artifacts/public%2Fbuild%2FMozillaVPN.pkg

Note that the root URL is listed twice, and the second one is missing the colon after `https`. I'm pretty sure this used to work.

**To Reproduce**

1. Go to a task
2. Click the "Copy" button next to an artifact
3. Paste it somewhere and inspect

**Taskcluster version**
44.8.4

**Comment by lotas** [comment]
Interesting. Some of the artifacts are fine on that very task. Looks like text files are being handled differently, and the bug was in this url concat:

https://github.com/taskcluster/taskcluster/blob/c569cf38ada0bc4f31dc3fed7e4d681bf9adbfbc/ui/src/components/TaskRunsCard/index.jsx#L289-L291

**Comment by Shubhamchinda** [comment]
@ahal I'd like to check this.

**Comment by lotas** [comment]
@Shubhamchinda not sure what is the status of your fix, but I had it to fix in my branch in order to fix something else, sorry :)

78a017fa1204296adff2ca0e8b73b18b98869fd1

**Comment by lotas** [comment]
Fix merged to main
