### ISSUE TITLE
UI: Worker pools table is not responsive

### ISSUE THREAD

**Issue by lotas** [taskcluster/taskcluster#5379]
Table on the [worker-manager](https://community-tc.services.mozilla.com/worker-manager) page has limited width and not responsive. Content is being hidden.

<img width="2150" alt="image" src="https://user-images.githubusercontent.com/83861/165063211-f233e9e7-a817-4bb4-a83e-cb5aeece7de8.png">

TODO:
* trim column widths to fit initial content (since whole content is limited at `~1600px`)
* make table responsive (maybe even hide some columns, i.e. email of the owner)

**Comment by matt-boris** [comment]
Same with this view https://firefox-ci-tc.services.mozilla.com/provisioners/gecko-t/worker-types/win10-64-2004 (likely the same component being used).

I noted in https://github.com/taskcluster/taskcluster/pull/5370 about how more columns are to be added to this view, and that makes this ticket you created that much more important, imo.

**Comment by matt-boris** [comment]
I'd also be in favor of just removing the email column from that view, as it's already listed in the worker pool detail page (when you click on one of the worker pool IDs). I feel like that column doesn't contain pertinent info for that list view.

**Comment by ahmedDevs** [comment]
Hey, if this issue is still open; I'm happy to take a crack at it:)

**Comment by lotas** [comment]
Hey @ahmedDevs, sure, be our guest :)

**Comment by ahmedDevs** [comment]
PR submitted.
