### ISSUE TITLE
500 when trying to get `latest` build for a repo branch using `checks-v2`

### ISSUE THREAD

**Issue by Eijebong** [taskcluster/taskcluster#5395]
`{"EnvVersion":"2.0","Fields":{"incidentId":"68462a0f-2931-49c3-81ff-86debe5c938b","message":"Cannot read properties of undefined (reading 'html_url')","method":"latest","name":"TypeError","stack":"TypeError: Cannot read properties of undefined (reading 'html_url')\n    at Proxy.<anonymous> (/app/services/github/src/api.js:550:44)","v":1},"Hostname":"taskcluster-github-web-659cc5b977-bjmss","Logger":"taskcluster.github.api","Pid":1,"Severity":3,"Timestamp":1651247395785000000,"Type":"monitor.error","message":"TypeError: Cannot read properties of undefined (reading 'html_url')\n    at Proxy.<anonymous> (/app/services/github/src/api.js:550:44)","requestId":"98d47701-4742-41b7-b5cc-02b1b044e4ed","serviceContext":{"service":"github","version":"44.13.0"},"severity":"ERROR","traceId":"5927b604-b439-49bd-a4c6-54646b2c9a19"}
`

Example on:
https://divvun-tc.thetc.se/api/github/v1/repository/divvun/divvun-manager-windows/main/latest

Repo exists and has taskcluster created checks.
https://github.com/divvun/divvun-manager-windows

**Comment by ahal** [comment]
Looks like I was going off the `check-suites` endpoint, but in reality `findTCChecks` was using the `check-runs` endpoint. Good news is the fix should be easy and actually simplify some logic.

This is why a staging Github service would be useful 😅
