### ISSUE TITLE
t is null

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#5409]
<img width="1410" alt="Screenshot 2022-05-01 at 17 52 02" src="https://user-images.githubusercontent.com/190790/166153914-7f44fe73-a307-4133-84a6-22b5ecd94efc.png">

**Comment by matt-boris** [comment]
Fixed in release v44.13.0 https://community-tc.services.mozilla.com/provisioners/proj-taskcluster/worker-types/gw-ci-macos
