### ISSUE TITLE
[UI] Unify order of delete buttons

### ISSUE THREAD

**Issue by mitchhentges** [taskcluster/taskcluster#543]
The location of the "delete" button is different between different pages. For example:
* For hooks, the delete button is on the bottom of the pop-up menu
* For roles, the delete button is on the top of the pop-up menu

I had built up a muscle-memory of the non-deletion action after working with hooks, and I just went to edit a role, but deleted it instead! :man_facepalming:

**Comment by helfi92** [comment]
Oh no! Sorry for that. Agreed, let's have the red button above the green one in the speed dial component. We should also add an extra layer of protection by showing a confirmation box when deleting...but we can take care of that later.

**Comment by arshadkazmi42** [comment]
@helfi92 I would like to take this up

**Comment by helfi92** [comment]
Go for it. This will make @mitchhentges really happy :)

**Comment by arshadkazmi42** [comment]
Can you share create pages url?
@helfi92 Do I need to setup backend also to work on this?

**Comment by arshadkazmi42** [comment]
Created a PR

**Comment by helfi92** [comment]
Thanks @arshadkazmi42! I will look at it as soon as I get the chance.
