### ISSUE TITLE
Taskcluster CI does not report to Github the status of a task re-run

### ISSUE THREAD

**Issue by jonalmeida** [taskcluster/taskcluster#5437]
**Describe the bug**

The Github UI in a pull request does not update when a failed task has been re-run. So it looks like the task is still failed until you click into it and go to the tc UI or until a success is posted.

**To Reproduce**

1. Have a Github project with Taskcluster CI running on pull requests.
2. Have one of the CI tasks fail.
3. Observe status of the task on Github UI.
4. Re-run the task from taskcluster CLI (or any other preferred way).
3. Observe status of the task on Github UI.

**Expected behaviour**

- At 3, the status should show a failure.
- At 5, the status should show running.

**Actual behaviour**
- At 3, the status shows a failure.
- At 5, the status shows a failure.

**Taskcluster version**

44.13.5

**Screenshots**

This task was restarted and is currently running, but the UI still shows the task as a failure:
<img width="924" alt="Screen Shot 2022-05-09 at 3 13 07 PM" src="https://user-images.githubusercontent.com/1370580/167481793-39d807b9-b3e9-4149-a540-31f0d46609fd.png">

**Platform (please complete the following information):**

 - OS: Mac OS
 - Browser if applicable: firefox
 - Version if applicable: 102.0a1 (2022-05-06) (64-bit)

**Additional context**

**Comment by lotas** [comment]
Hi @jonalmeida  thanks for reporting this. 
Can you please tell me how you do "Re-run the task from taskcluster CLI" this step?

**Comment by jonalmeida** [comment]
@lotas I used the CLI tool for my device. For example: [`taskcluster-darwin-amd64`](https://github.com/taskcluster/taskcluster/releases/download/v44.13.6/taskcluster-darwin-amd64)

Then:
1. `TASKCLUSTER_ROOT_URL=https://firefox-ci-tc.services.mozilla.com/; taskcluster signin`
2. Authenticated.
3. `taskcluster task rerun [taskId]`

**Comment by lotas** [comment]
Indeed. Let's keep both until resolved.

**Comment by jonalmeida** [comment]
I'm quite alright with closing this as a dupe since Aki has commented on that bug on behalf of MoCo mobile. :)

**Comment by lotas** [comment]
alright :) Let's then close this one and work on the fix in #5085. 
Thanks!
