### ISSUE TITLE
Add functionality to remove cloud worker from UI 

### ISSUE THREAD

**Issue by lotas** [taskcluster/taskcluster#5440]
According to sheriff's [how-to notes](https://wiki.mozilla.org/Sheriffing/How_To/Intermittent_bugs#Machine-specific_failures) it was possible to terminate cloud worker from the UI, but it is not anymore.

TODO

- Add remove worker functionality to remove single cloud VM. This should call worker-manager's `removeWorker` endpoint.
- Add batch action to remove all workers in the pool

**Comment by lotas** [comment]
@Archaeopteryx I was going through my notes and noticed this one. I believe this is still an issue for you? 
How often do you go through this manual worker removal? 
How often do you remove all of the workers in a single pool? (I mean if it makes sense to add this to UI, or this is something to be better done manually?)

Thanks!

**Comment by matt-boris** [comment]
I'd imagine that a `terminate` button could live on each row in the table here https://firefox-ci-tc.services.mozilla.com/provisioners/gecko-t/worker-types/win10-64-2004-gpu but am questioning the best location for a `terminate all` button.

Maybe one at the top of that same page? Or maybe in each row of this table https://firefox-ci-tc.services.mozilla.com/worker-manager? Or even the worker pool detail view https://firefox-ci-tc.services.mozilla.com/worker-manager/comm-1%2Fb-linux.

What do you guys think? @Archaeopteryx @lotas

**Comment by Archaeopteryx** [comment]
> How often do you go through this manual worker removal?
Usually 0-3x per week

> How often do you remove all of the workers in a single pool?
Once per quarter or less. This might be more interesting for Pete or RelOps when new AMIs get deployed. But doing it from the command line should be fine. At the moment code sheriffs [retrieve the list of machines known to the pool](https://wiki.mozilla.org/Sheriffing/How_To/Intermittent_bugs#Machine-specific_failures) (even ones which got released) and try to terminate each.

Code sheriffs' workflow is to enter the TC UI on the page for a task, navigate to the machine for the worker instance which lists the tasks it executed and their results. Here they can see if the machine needs to be terminated. Terminating a single machine from the list view would be an uncommon workflow for code sheriffs but might be the fastest way for RelEng. They could search the list for the ID and then initiate the termination.

**Comment by matt-boris** [comment]
@Archaeopteryx thanks for these notes.

Just to clarify what you're referring to, I'm going to provide a link to a page.

> navigate to the machine for the worker instance which lists the tasks it executed and their results

You would like to see a terminate worker button on this page? https://firefox-ci-tc.services.mozilla.com/provisioners/gecko-1/worker-types/b-linux-gcp/workers/us-central1/101278286944937797

**Comment by Archaeopteryx** [comment]
Yes.
