### ISSUE TITLE
Add retries to `execCommand` method

### ISSUE THREAD

**Issue by matt-boris** [taskcluster/taskcluster#5459]
`release-publish` tasks intermittently fail due to the [`dockerPush`](https://github.com/taskcluster/taskcluster/blob/66941613e4242d69dd2aff3fb560359eb633d59c/infrastructure/tooling/src/utils/docker.js#L246-L291) command failing, usually during the build websocktunnel docker image. This is fixed by rerunning the task over a few times until it succeeds. An extra param passed to `execCommand` with number of retires may be a good solution for the short term.

**Comment by lotas** [comment]
It could also be some quirk of streams/pipes, maybe there's another bug that fails.
But in general retries sounds like a good idea
