### ISSUE TITLE
Log additional information for Github webhook events

### ISSUE THREAD

**Issue by kkleemola** [taskcluster/taskcluster#5506]
Currently when trying to troubleshoot intermittent failures for the Github integration, minimal information is logged about the webhook events received (only the installation id and the event id - these identifiers may not be easily accessible by those doing the troubleshooting).

Including additional information from the webhook request would allow less people to start to troubleshoot intermittent failures - organization, repository and action should all be common fields that would give us a bit more immediate context when debugging.

**Comment by kkleemola** [comment]
@lotas Thanks for this! Do I need to adjust the logging levels to enable this?

firefoxci has `level: root:notice handlers:debug` for github

(stage has level: debug and community is default notice, I can enable for community as well.)

**Comment by lotas** [comment]
@kkleemola yes, you need `debug` level for this. Once this change gets deployed
