### ISSUE TITLE
Error banner when logging in: `buildSignedUrl missing required credentials`

### ISSUE THREAD

**Issue by ahal** [taskcluster/taskcluster#5512]
Lately I've noticed when logging in to the TC web UI I get a  big red banner afterwards:
![image](https://user-images.githubusercontent.com/273734/173444333-07f23543-999c-4f9e-8a48-bd3cbd7eaa88.png)

This happens on both the `firefox-ci` and `community` instances.

If I refresh the page, it appears that the login was actually successful and things seem to work as normal. So it's more of an inconvenience / source of confusion.

**Comment by matt-boris** [comment]
Dup #4943
