### ISSUE TITLE
Support Postgresql > 11

### ISSUE THREAD

**Issue by mostlygeek** [taskcluster/taskcluster#5514]
PostgreSQL 11 is EOL Nov/2023.   This issue is to track work updating Taskcluster to support PostgreSQL > 11.

**Comment by matt-boris** [comment]
More information here https://www.postgresql.org/support/versioning/



Version | Current minor | Supported | First Release | Final Release
-- | -- | -- | -- | --
14 | 14.3 | Yes | September 30, 2021 | November 12, 2026
13 | 13.7 | Yes | September 24, 2020 | November 13, 2025
12 | 12.11 | Yes | October 3, 2019 | November 14, 2024
11 | 11.16 | Yes | October 18, 2018 | November 9, 2023
