### ISSUE TITLE
[UI] Hard to know requests fail when on tall pages

### ISSUE THREAD

**Issue by mitchhentges** [taskcluster/taskcluster#554]
When an action fails (such as when your authentication tokens have expired), a red banner appears at the top of the screen. However, on taller pages, if you aren't at the top of the screen, it seems like the action succeeded, because the button you clicked is clickable again, and nothing notable happened (other than the page shifting down by an inconspicuous amount).

Perhaps the red banner should show at the top of the screen, regardless of how far the user has scrolled down?

**To reproduce:**
1. Sign into Taskcluster
2. Wait a full day (or however long it takes for your token to expire)
3. Go to a tall page [(e.g.: this hook)](https://taskcluster-web.netlify.com/hooks/garbage/taskgraph-reference-browser-mhentges) scroll to the bottom, and click the save button.

**Comment by helfi92** [comment]
Agreed. We should find a better way to deliver the error message to the user.

> Perhaps the red banner should show at the top of the screen, regardless of how far the user has scrolled down?

We could give that a try and see if it's good enough.
