### ISSUE TITLE
The error display for hooks that errored out due to missing scopes shows nothing but an empty red box

### ISSUE THREAD

**Issue by Eijebong** [taskcluster/taskcluster#5566]
To reproduce:

- Create a hook and forget `provisionerId` in the task description. (or anything that'll make it complain about missing scopes)
- Save hook and trigger it manually. It'll tell you which scopes you're missing.
- Go back to the hook page, you'll see that the last firing failed and have an `i` button. Click it.

![hooks1](https://user-images.githubusercontent.com/3650385/178960085-25d6b054-e623-4e0a-8b3e-8e3bdd13452b.png)

- Red box

![hooks2](https://user-images.githubusercontent.com/3650385/178960266-d8caf9b1-eaa4-4f6f-967e-5262d156bfc6.png)

If we can't show the scopes error for some reason maybe this should at least have some default text.

**Comment by lotas** [comment]
This should be fixed with https://github.com/taskcluster/taskcluster/pull/5848
