### ISSUE TITLE
The worker type selector on the `Create Task` page is missing left padding when focused

### ISSUE THREAD

**Issue by Eijebong** [taskcluster/taskcluster#5611]
![padding](https://user-images.githubusercontent.com/3650385/183374345-8d65d6e5-0b14-4487-91b0-7aa95a1cdae9.png)

To repro, change the worker type with the select and don't click anywhere else on the page or press tab a couple times until that element is focused.

**Comment by ahmedDevs** [comment]
Hey, I'm interested in taking this on.

**Comment by lotas** [comment]
Hi @ahmedDevs, sure, go ahead!

**Comment by ahmedDevs** [comment]
Hey is that the issue you're referring to?
![error-repro](https://user-images.githubusercontent.com/102767737/183794055-abe5b805-09e2-4d80-91ec-ac6b54b48e2b.png)

**Comment by ahmedDevs** [comment]
Hey, is that the error you're referring to?
![error-repro](https://user-images.githubusercontent.com/102767737/183807718-6924110b-66aa-4766-a6ba-847fe6e14058.png)

**Comment by Eijebong** [comment]
Nah. While I don't really like the circle in the middle of the button on hover, this seem to be a design choice and not a bug.

The issue I'm referring to is on the worker type selector. If you change the value from `Docker worker` to anything else and don't click back on the page, you'll see that the leftmost character is touching the left border which looks very weird.

**Comment by ahmedDevs** [comment]
It appears that the issue is a result of the default stylings of a certain class from the MUI library. I added code to the theme.js file to override the default styling and set it to the desired one.
