### ISSUE TITLE
Convert taskcluster-bot from an org member to an outside collaborator

### ISSUE THREAD

**Issue by cknowles-admin** [taskcluster/taskcluster#5639]
In discussions around the upcoming effort to migrate this org to GitHub Enterprise, and enforce SAML/SSO on the org, we need to deal with the non-human members of the org.  The only one found is [taskcluster-bot](https://github.com/orgs/taskcluster/people/taskcluster-bot).  Given that it's only got access to 1 repo (this one), and is only doing repo-level things, this is a good candidate for conversion to an outside collaborator. 

I'm happy to do the button pushing, I just need assistance from a member of the taskcluster org that has familiarity with the bot and its function available to confirm that things are well, and if we need to roll back to member they'll need to have access to the bot's associated email account.  

Let me know if you have questions, or when a good time to schedule this would be.

**Comment by matt-boris** [comment]
@cknowles-admin @aerickson-admin could we please get this migrated over and I'll verify things are working still over the following days? Feel free to slack me

**Comment by cknowles-admin** [comment]
I'll reach out on slack for final negotiations.

**Comment by cknowles-admin** [comment]
Confirmed that they had email/login capabilities, and that there are no timing restrictions.
Did the conversion - confirmed that the bot account maintained the access to the taskcluster/taskcluster repository that it had as a member.  
At this point I think this is closed, but feel free to reach out if there are questions or concerns.

**Comment by matt-boris** [comment]
Thanks for your help @cknowles-admin!
