### ISSUE TITLE
Github integration fails to change status updates

### ISSUE THREAD

**Issue by lotas** [taskcluster/taskcluster#5653]
Introduced in the latest release 44.19.1, github falls into some sort of race condition or uses incorrect check run to update status.
Example: https://github.com/mozilla-releng/build-mar/runs/8135486860 
Although task was resolved https://firefox-ci-tc.services.mozilla.com/tasks/X0wOnzqKTEmMEBYPqDpNbg 

Related to #5085

**Comment by lotas** [comment]
Looks like extra check-run was created
Github shows this: https://github.com/mozilla-releng/build-mar/runs/8135486860 (check run id=8135486860)

While in the database it has check run id=8135486858
```
AjOxKKGBQICzk3a_lxBvjQ	X0wOnzqKTEmMEBYPqDpNbg	8089061093	8135486858
```

**Comment by lotas** [comment]
<img width="1353" alt="image" src="https://user-images.githubusercontent.com/83861/187997781-796f5f24-2b0f-4774-afd4-91bb25d41658.png">

two handlers created check run at the same time
`taskDefined` and `status`

Status handler should check if checkrun exists right before creating new status

**Comment by jcscottiii** [comment]
I think this may also be impacting the WPT [repo](https://github.com/web-platform-tests/wpt).

There are many instances where the tasks are still in Queued.
![image](https://user-images.githubusercontent.com/7788930/188015449-f538a509-fe13-43d5-aced-542975dda765.png)

Upon examining this particular [run](https://github.com/web-platform-tests/wpt/runs/8107718187). You will see many of the taskcluster runs are in queued.

For example the download-firefox-nightly is marked as queued in Github
![image](https://user-images.githubusercontent.com/7788930/188015801-e368023e-0649-44aa-ad23-81547a61fb17.png)

However the task is marked as completed in taskcluster
https://community-tc.services.mozilla.com/tasks/bCic8tjzTFCfgFqJ9cu3eA

![image](https://user-images.githubusercontent.com/7788930/188015875-cb5cc35c-06b0-45dc-82d4-d532c1e48102.png)


This deployment is using that affected version, `44.19.1`:
![image](https://user-images.githubusercontent.com/7788930/188015991-ea89d266-7172-48cb-bbeb-56d4c5fa34f2.png)
