### ISSUE TITLE
[UI] cancel button dosen't closes the modal

### ISSUE THREAD

**Issue by sudipt1999** [taskcluster/taskcluster#567]
**To Reproduce**
1. Go to [https://docs.taskcluster.net/docs](https://docs.taskcluster.net/docs)
2. Click on  Sign in
3. Click on Close

**Expected behavior**
Modal should close

**Screenshots**

![Screenshot from 2019-04-13 16-56-46](https://user-images.githubusercontent.com/38929617/56079166-4f082e00-5e0e-11e9-8936-7887298d0b61.png)

**Comment by helfi92** [comment]
I can't seem to replicate. What browser and version are you using?

**Comment by sudipt1999** [comment]
Google Chrome

**Comment by helfi92** [comment]
What version of Firefox?

**Comment by buscasangre** [comment]
@sudipt1999  I am using Mozilla Firefox 66.0.2 and there is no such kind of problem .

**Comment by sudipt1999** [comment]
@buscasangre  my version is same as yours 66.0.2 (64-bit), 

Please see this!
![Peek 2019-04-14 21-43](https://user-images.githubusercontent.com/38929617/56095852-78a08280-5efe-11e9-808e-d51578ace4a8.gif)

**Comment by buscasangre** [comment]
@sudipt1999  the same problem is in chrome browser too and this dialog box is only causing problem when you are selecting the sign in option from the top left corner . This is working fine when we select the sign in option from the top right corner.

**Comment by helfi92** [comment]
> only causing problem when you are selecting the sign in option from the top left corner

Agreed. I was able to replicate.
