### ISSUE TITLE
Grant dw-ci tasks the docker-worker capability disableSeccomp

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#5739]
The `disableSeccomp` capability is required by the dw-ci task that runs the docker-worker tests, in order that the docker-worker tests themselves have the capability.

_Originally posted by @jschwartzentruber in https://github.com/taskcluster/taskcluster/issues/5695#issuecomment-1271591913_

**Comment by matt-boris** [comment]
Completed via https://github.com/taskcluster/taskcluster/pull/5744
