### ISSUE TITLE
Context menu labels not visible except for half of last character

### ISSUE THREAD

**Issue by ahal** [taskcluster/taskcluster#5742]
**Describe the bug**
The three dot context menu labels are covered in solid blue. Just the last character is partially visible. See screenshot.

This is reproducible for me on all tasks and task group pages.

**To Reproduce**
Hover over the three dot menu on any task or task group.

**Expected behavior**
Labels are visible.

**Taskcluster version**
44.20.4 and 44.23.0 (I can repro on fxci and community)

**Screenshots**
![tc-bug](https://user-images.githubusercontent.com/273734/198370939-39478fa2-1f88-4f65-a93f-434d9aa45ab3.png)

**Platform (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox Nightly 108

**Comment by ahal** [comment]
I wonder if this is a Firefox bug, as I'm not aware of any recent TC deployments and I can't reproduce this in Edge..

**Comment by matt-boris** [comment]
> I wonder if this is a Firefox bug, as I'm not aware of any recent TC deployments and I can't reproduce this in Edge..

I just tried reproducing on stable Firefox and cannot. Though, I am seeing this on Nightly.

**Comment by matt-boris** [comment]
I actually can't reproduce anymore after getting the latest Nightly

**Comment by ahal** [comment]
Oh lol, I just updated and can't reproduce anymore either.. Must have been a regression that got fixed recently. Figures I would file this with the fix just waiting to be applied on my system.
