### ISSUE TITLE
[clients] verify hashes for simple downloads

### ISSUE THREAD

**Issue by escapewindow** [taskcluster/taskcluster#5767]
If this isn't implemented already.

**Comment by djmitche** [comment]
By this, do you mean something like
```
$ taskcluster download $TASK_ID $RUN_ID public/some.data
Downloading...
Downloaded 13MB
$
```

**Comment by escapewindow** [comment]
I filed this after our object service meeting.
Looks like `taskcluster download` already exists. If we also verify the sha on download, either with a flag or by defaulg, then this issue is resolved.

**Comment by djmitche** [comment]
Ah, in fact it does not verify the hash on download, as the client-go implementation does not.  In fact, it looks like none of the clients do so for "simple" downloads.  I think the intent was to implement this with the "full" download type, but in principle there's no reason not to do so with the simple type (and it would avoid potential downgrade attacks).

@escapewindow can you assign this to me, and change the title to "[clients] verify hashes for simple downloads"?

**Comment by djmitche** [comment]
Hm, https://github.com/taskcluster/taskcluster/issues/4624 suggests a slightly-more-than-simple download method, which includes hashes.  I'll add a note there that clients should support some "allow un-checked downloads" option, without which the "simple" download method will not be alowed, thereby avoiding downgrade attacks.  

So, I think there's nothing to do here, but let's leave this open depending on #4624.

**Comment by djmitche** [comment]
closing as #4624 is closed.
