### ISSUE TITLE
[UI] Add top margin to headers in documentation

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#577]
STR:

1. Navigate to something like https://taskcluster-web.netlify.com/docs/manual/design/apis/pulse#taskcluster-pulse-resources

**Expected**:

![Screen Shot 2019-04-15 at 10 24 30 AM](https://user-images.githubusercontent.com/3766511/56140334-b2a66e80-5f68-11e9-878b-64e1407d0eae.png)

**Actual**:

![Screen Shot 2019-04-15 at 10 23 32 AM](https://user-images.githubusercontent.com/3766511/56140347-b803b900-5f68-11e9-8ee1-305862888216.png)

_Note: The margin top should be applied to all headers, except the first header in docs_

**Comment by arshadkazmi42** [comment]
@helfi92 I would like to work on this
