### ISSUE TITLE
[UI] Interactive Task re-wording

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#578]
Many users don't know the feature of connecting to SSH when creating a task. I think this is because the word "Interactive" is a bit vague for the average user. We should consider changing the wording. For example, when creating a task, instead of saying "Create Interactive" we should say "Create with SSH".

**Comment by shubhamgupta2956** [comment]
hi,
I am new to open source and want to contribute to this issue. Please guide me on how to start.

**Comment by helfi92** [comment]
Welcome @shubhamgupta2956. See the [README](https://github.com/taskcluster/taskcluster/blob/master/ui/README.md) for how to get the UI running. Let me know if you had questions.

**Comment by shubhamgupta2956** [comment]
@helfi92 please review my pr and let me know about anything wrong with it or any other thing
