### ISSUE TITLE
[UI] Secrets view UX

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#581]
STR:

1. Navigate to https://taskcluster-web.netlify.com/ and login
2. Navigate to https://taskcluster-web.netlify.com/secrets/garbage%2Fhassan%2Ftest

**Expected**: The Save button is visible and shows a confirmation message when a user click on "Save".

![Screen Shot 2019-04-16 at 10 29 30 AM](https://user-images.githubusercontent.com/3766511/56218209-8b1bd880-6032-11e9-8e65-ab74c8de3c28.png)

**Actual**: The save button is hidden inside the speed dial component and doesn't show a confirmation message when a user clicks on the save icon.

![Screen Shot 2019-04-16 at 10 29 01 AM](https://user-images.githubusercontent.com/3766511/56218169-79d2cc00-6032-11e9-9994-158e6aaba805.png)
![Screen Shot 2019-04-16 at 10 27 07 AM](https://user-images.githubusercontent.com/3766511/56218170-7a6b6280-6032-11e9-9866-0956ee2aa248.png)

Inspiration: Similar to something like https://taskcluster-web.netlify.com/hooks/garbage/abc456.

**Comment by shubhamgupta2956** [comment]
@helfi92 I am interested in taking this issue. Please assign it to me.

**Comment by helfi92** [comment]
Please accept the invitation in https://github.com/taskcluster/taskcluster/invitations :)

**Comment by helfi92** [comment]
@shubhamgupta2956 I think we are still missing the confirmation message when a user saves a secret. https://github.com/taskcluster/taskcluster/issues/581#issuecomment-483691829

Feel free to create a new PR. Don't forget to pull in the recent changes first so that you have a fresh copy of the codebase:

```bash
git checkout master
git pull upstream master
git checkout -b save-secret-add-confirmation-message
```

**Comment by helfi92** [comment]
@shubhamgupta2956 Thank you again for the confirmation message. It looks really good! The last I see us doing on this view would be to disable the save button unless some values have changed. Something similar to how we do it in the hooks view. You can look at https://github.com/taskcluster/taskcluster/pull/202/files for inspiration. It will involve adding the `isSecretDirty` logic.

**Comment by shubhamgupta2956** [comment]
Thanks @helfi92 for adding me as contributor. I have made a new PR #833 to add isSecretDirty logic.

**Comment by helfi92** [comment]
My pleasure! Really happy with the work you're doing. I will review the PR soon. What's next for you? Did you want to tackle https://github.com/taskcluster/taskcluster/issues/598? It's a similar issue but it will get you involved with different views (clients and roles). If you're interested, feel free to comment on the issue directly. Thanks again for your work!
