### ISSUE TITLE
[UI] better error message on nonexistent task group

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#592]
**Describe the bug**
When a taskGroup is not found, the error is "e.taskGroupConnection is null"

**To Reproduce**
https://taskcluster-staging.net/tasks/groups/PPgFNzlMSRe99wlGNg6tUw

**Expected behavior**
A clear and concise error message :)

**Comment by helfi92** [comment]
FYI, the browser currently throws: Unable to connect to https://taskcluster-staging.net/tasks/groups/PPgFNzlMSRe99wlGNg6tUw.

**Comment by djmitche** [comment]
Huh, that link works fine for me, even in Chrome.  Notably, it complains "Cannot read property 'edges' of null" in chrome, but maybe that's just different words for the same error.

**Comment by helfi92** [comment]
Weird. Works on my phone, just not on my laptop.

**Comment by djmitche** [comment]
Maybe something in /etc/hosts?

**Comment by helfi92** [comment]
`cat /etc/hosts` shows:

```bash
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost

```
