### ISSUE TITLE
"Rerun" fails with message in console

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#594]
**Describe the bug**
Clicking "rerun" on a task does nothing, but gives an error in the console.

**To Reproduce**
1. https://taskcluster-staging.net/tasks/EJnb_6N-QRSQnzGmNdrxtA
1. Click "rerun"

**Expected behavior**
Rerun succeeds, or fails with an error.

**Comment by helfi92** [comment]
Created https://github.com/taskcluster/taskcluster/pull/595.

By the way, when I try to run the task, an error is thrown:

![Screen Shot 2019-04-17 at 1 35 23 PM](https://user-images.githubusercontent.com/3766511/56308674-e1157c80-6115-11e9-9a14-97beb2493fee.png)

I think the error is coming from https://github.com/taskcluster/taskcluster/blob/c85e4e4fbc395e4212452a1dfce70afb4451d331/ui/src/utils/validateActionsJson.js#L13 Do you know if anything changed?

**Comment by djmitche** [comment]
It's possible that we've started using v7 schemas in actions recently -- I don't remember that, but I forget things :)

See the "Please Note" [here](https://github.com/epoberezkin/ajv#using-version-6) -- it should be a matter of adding that line.

**Comment by helfi92** [comment]
Makes sense. Thank you.
