### ISSUE TITLE
[UI] Auth Client UX

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#598]
Same as https://github.com/taskcluster/taskcluster/issues/581 but for the auth clients and roles view:

Client Form: https://taskcluster-web.netlify.com/auth/clients/github%2Fhelfi92%2F

Role Form: https://taskcluster-web.netlify.com/auth/roles/github-admin%3A*

**Comment by shubhamgupta2956** [comment]
@helfi92 I want to take this issue. Please assign it to me. Thanks.

**Comment by helfi92** [comment]
I think the only thing left would be to add the snackbar confirmation when saving a role/client. Awesome work so far!

**Comment by shubhamgupta2956** [comment]
I will add it and submit a PR for it.Thanks.

**Comment by helfi92** [comment]
Thank you for your work @shubhamgupta2956. Very nice!
