### ISSUE TITLE
Transform docker-worker task.payload.capabilities.devices.loopbackAudio via payload transformation to generic-worker format

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#5980]

**Comment by matt-boris** [comment]
This is not used in FxCI at all. We'll likely start our implementation on the video loopback device first, then copy across to audio, as they will be fairly similar.

**Comment by matt-boris** [comment]
Completed in https://github.com/taskcluster/taskcluster/pull/6419.
