### ISSUE TITLE
[UI] "signature" in API docs should include payload

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#605]
**Describe the bug**
The signature of a method that takes a request payload should include the `payload` argument

**To Reproduce**
1. Go to https://docs.taskcluster.net/docs/reference/core/notify/api#email
1. Expand the email method

**Expected behavior**
Should see `email(payload)`.

**Screenshots**
![Screenshot_2019-04-18 Api - Taskcluster](https://user-images.githubusercontent.com/28673/56373090-3ad97d80-61ce-11e9-823a-6606ec69b6ce.png)

**Comment by arshadkazmi42** [comment]
@djmitche I can take this up.
Can you give some more details, what exactly needs to be done here? 
Adding payload with the other details? And from where we can get the payload?

**Comment by djmitche** [comment]
The payload is already defined below -- we just need to include a parameter named `payload` in the signature.  [Here](https://github.com/taskcluster/taskcluster-docs/blob/125a1319e7ffabb161ebcec29827bf300c112163/layout/reference.pug#L91-L103) is how it was done in the old docs site.

I'll invite you to the repo. Once you accept, I can assign this to you :)

**Comment by arshadkazmi42** [comment]
I will have a look at it later today.
I have accepted the invite
