### ISSUE TITLE
Add an easier way of copying a task definition

### ISSUE THREAD

**Issue by Eijebong** [taskcluster/taskcluster#6052]
Right now when you click on `task definition` for a task you get to a page where it's difficult to select the whole content as pressing ctrl-A will select other things on the page and there's no button to either select or copy just said description

Might be a good idea to add such a button that puts the task description in the clibpboard.

**Comment by AmineVolk** [comment]
Hello @Eijebong @lotas ,
I will happy to do it :)
@Eijebong  when you talk about the task description, do you mean the "Task Details" ?

![image](https://user-images.githubusercontent.com/37228315/217090918-41a8f068-4702-4c08-ae0e-8132e3ac1ccc.png)

**Comment by Eijebong** [comment]
What I mean by task definition is the one you get when you click on `Full task definition`. Here's an example: https://firefox-ci-tc.services.mozilla.com/tasks/KvZH6DD-SPGVwf0ZSQ24Qg/definition

**Comment by AmineVolk** [comment]
Ah okay, i understand.
I will do it.

**Comment by AmineVolk** [comment]
@lotas @Eijebong The MR is ready.

**Comment by lotas** [comment]
Awesome, thanks @AmineVolk !
