### ISSUE TITLE
pg_dump dev requirement not documented

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#6079]
To set up a taskcluster development environment, you currently need pg_dump installed on your host. Used here:

* https://github.com/taskcluster/taskcluster/blob/66941613e4242d69dd2aff3fb560359eb633d59c/infrastructure/tooling/src/generate/generators/db-schema-dump.js#L36

We currently don't document that a native postgres client is required in
* https://github.com/taskcluster/taskcluster/blob/fe1d0cbe16ee2f68e500335ae5a140324b5b6369/dev-docs/development-process.md

If this is the only place a native client is used, we might be better off just running some equivalent sql commands and using taskcluster-lib-postgres which already seems to be required in that source code, rather than executing a native binary. Or maybe it isn't trivial to do via sql (although i expect there probably will be some built in postgres function(s) to do it), and we are just better off documenting the requirement.

Not sure if this is the only place a native client is currently required.

**Comment by djmitche** [comment]
The formatting of the output is implemented in `pg_dump`.  I didn't find any simple way to do this without using `pg_dump` directly.  Where by "simple" I mean less complicated than parsing all of postgres's internal schema tables and trying to produce equivalent SQL.

A postgres client is also often useful for poking around in the DB during testing, so I don't think it's a lot to ask that devs install it.
