### ISSUE TITLE
[UI] Add capacity to edit bindings in hooks view

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#610]
The [old UI](https://tools.taskcluster.net/hooks/garbage/test) allows users to edit the bindings property of a hook.  We need the same functionality in the new UI.

**Comment by helfi92** [comment]
Not sure why this was omitted. We should definitely add a way to edit bindings.

**Comment by helfi92** [comment]
@arshadkazmi42 Is this something you would be interested in tackling? :-)

**Comment by arshadkazmi42** [comment]
Yes. I am interested to work on this. Can you give some more details, what I understand from this is that `Edit Hook` button is missing in the new UI in current repo

**Comment by helfi92** [comment]
> Yes. I am interested to work on this

Thank you, you're awesome :-)

> Can you give some more details, what I understand from this is that Edit Hook button is missing in the new UI in current repo

In the new UI the "edit" and "new" form are using the same form so we don't need an edit button. Example:
* New hook form - https://taskcluster-web.netlify.com/hooks/create
* Existent hook form - https://taskcluster-web.netlify.com/hooks/garbage/test

What we want is to add a similar UI to https://taskcluster-web.netlify.com/pulse-messages?bindings[0][exchange]=exchange%2Ftaskcluster-treeherder%2Fv1%2Fjobs&bindings[0][pattern]=%23 below "Schedule" to make sure we are consistent with the new UI design.

![Screen Shot 2019-05-06 at 12 55 18 PM](https://user-images.githubusercontent.com/3766511/57241088-3dc1d400-6ffe-11e9-9bfc-550897ef0a5d.png)

Let me know if you have questions.

**Comment by arshadkazmi42** [comment]
What I understood from this is, this needs to be change

<img width="1587" alt="Screen Shot 2019-05-06 at 10 34 13 PM" src="https://user-images.githubusercontent.com/4654382/57241689-2eb74200-704f-11e9-9658-d223fda18cfe.png">

to this

<img width="1597" alt="Screen Shot 2019-05-06 at 10 34 30 PM" src="https://user-images.githubusercontent.com/4654382/57241788-6c1bcf80-704f-11e9-8284-ec9f48479db3.png">

**Comment by helfi92** [comment]
> <img width="1597" alt="Screen Shot 2019-05-06 at 10 34 30 PM" src="https://user-images.githubusercontent.com/4654382/57241788-6c1bcf80-704f-11e9-8284-ec9f48479db3.png">

This stays the same because the old UI also has a "Schedule" section.

Unlike the old UI, the new UI doesn't have a "Bindings" section. The "Bindings" section consists of 2 text fields _Pulse Exchange_ and _Routing Key Pattern_. We should add those.

The task would roughly be to:
* Add a label "Bindings"
* Add 2 text fields
* Add a plus button
* When the user types something in both fields then clicks on the plus button, the binding should be displayed below the text fields
* Add a garbage icon to allow a user to delete a binding

Does it make a bit more sense?

**Comment by arshadkazmi42** [comment]
> Does it make a bit more sense? There's no need to remove anything from the current UI. We are just adding stuff to it.

Yes got it now. I will start looking into it. Thank you for detailed explaination

**Comment by helfi92** [comment]
My pleasure!

**Comment by arshadkazmi42** [comment]
> > <img alt="Screen Shot 2019-05-06 at 10 34 30 PM" width="1597" src="https://user-images.githubusercontent.com/4654382/57241788-6c1bcf80-704f-11e9-8284-ec9f48479db3.png">
> 
> This stays the same because the old UI also has a "Schedule" section.
> 
> Unlike the old UI, the new UI doesn't have a "Bindings" section. The "Bindings" section consists of 2 text fields _Pulse Exchange_ and _Routing Key Pattern_. We should add those.
> 
> The task would roughly be to:
> 
>     * Add a label "Bindings"
> 
>     * Add 2 text fields
> 
>     * Add a plus button
> 
>     * When the user types something in both fields then clicks on the plus button, the binding should be displayed below the text fields
> 
>     * Add a garbage icon to allow a user to delete a binding
> 
> 
> Does it make a bit more sense? There's no need to remove anything from the current UI. We are just adding stuff to it.

@helfi92 I am a bit confused, so above mentioned things needs to be added in [this](https://taskcluster-web.netlify.com/pulse-messages?bindings%5B0%5D%5Bexchange%5D=exchange%2Ftaskcluster-treeherder%2Fv1%2Fjobs&bindings%5B0%5D%5Bpattern%5D=%23) page?
As that page already contains `Add Binding` option.

Or it needs to be added in [this](https://taskcluster-web.netlify.com/hooks/create) below `Schedule`?

**Comment by helfi92** [comment]
> so above mentioned things needs to be added in this page?

No, nothing needs to be added to the pulse-messages view. The screenshot was simply used to show you how bindings were implemented in a different view for inspiration.

> Or it needs to be added in this below Schedule?

You are correct here. The change will be located in the hook view.
