### ISSUE TITLE
Error when calling Get a Worker API Endpoint

### ISSUE THREAD

**Issue by jwmoss** [taskcluster/taskcluster#6109]
**Describe the bug**
`listWorkersForWorkerPool` method one is too greedy and gets also the requests coming for worker call

**To Reproduce**

Open powershell, populate the clientId and accessToken, and run the below.

```Powershell
Invoke-RestMethod -Uri "https://firefox-ci-tc.services.mozilla.com/api/worker-manager/v1/workers/gecko-t/win11-64-2009/canadacentral/vm-bfarycpest6jyozcgdfjgazzkhve9t86bzj" -Headers @{
    clientId    = $ENV:TASKCLUSTER_CLIENT_ID
    accessToken = $ENV:TASKCLUSTER_ACCESS_TOKEN
}
```

**Expected behavior**

**Taskcluster version**

**Screenshots**

**Platform (please complete the following information):**

 - OS: Windows
 - Browser if applicable [e.g. firefox, safari]
 - Version if applicable [e.g. 57]

**Additional context**
Existing bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1560645

**Comment by djmitche** [comment]
I'm surprised that tests haven't caught this!  Even correctly escaping the workerPoolId doesn't help:

https://firefox-ci-tc.services.mozilla.com/api/worker-manager/v1/workers/gecko-t%2fwin11-64-2009/canadacentral/vm-bfarycpest6jyozcgdfjgazzkhve9t86bzj

still returns 
```
Invalid URL patterns:
URL parameter 'workerPoolId' given as 'gecko-t/win11-64-2009/canadacentral/vm-bfarycpest6jyozcgdfjgazzkhve9t86bzj' must match regular expression: '/^[a-zA-Z0-9-_]{1,38}\/[a-z]([-a-z0-9]{0,36}[a-z0-9])?$/'

---

* method:     listWorkersForWorkerPool
* errorCode:  InvalidRequestArguments
* statusCode: 400
* time:       2023-03-15T22:03:26.643Z
```

Separately from the bug being described, note that clientid and accessToken aren't headers.  In fact, sending the access token in cleartext is probably a bad idea! You can just fetch this URL with curl or a browser.

**Comment by djmitche** [comment]
Oh, the `:` in `/workers/<workerPoolId>:/<workerGroup>/<workerId>` is critical!  It works if you include that colon.

But, I think that was a typo that just never got caught, because the client libraries also include the colon.

I'll make a PR to remove the colon, with backward compatibility.

**Comment by lotas** [comment]
oh, that's really interesting @djmitche ! When I saw it yesterday I thought this was because of the extra asterisk in `listWorkersForWorkerPool` - `'/workers/:workerPoolId(*)'`

And tests never caught this because they are using helpers that wrap api calls with direct function calls and skip the routing part completely (or I'm missing something)

**Comment by djmitche** [comment]
The tests do use an HTTP request and response, but they use the client libraries (same as everyone else) which were dutifully including a `:` character there, so everything matched.

The bug only appeared when @jwmoss attempted to make the request using a raw HTTP client and missed the `:` character in the documentation.
