### ISSUE TITLE
Worker Manager not killing rogue/zombie instances

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#6142]
**Describe the bug**
Worker Manager should kill rogue/zombie instances, when they are not effective.

**To Reproduce**

Run Worker Manager, then have a worker that crashes with out of memory, or something similar.

**Expected behavior**

Worker Manager notices that the worker is not routinely calling `queue.claimWork` or `queue.reclaimTask`, and therefore terminates the instance it is running on.

**Taskcluster version**
All versions

**Screenshots**

![image](https://user-images.githubusercontent.com/190790/228864603-36a1068c-495e-4e4c-ba47-1817a148572a.png)

**Additional context**

Worker Manager should kill all instances that:

a) were requested more than e.g. 30 minutes ago, and are not yet known by the Queue, and
b) workers that are known by the Queue, but haven’t called `queue.claimWork` nor `queue.reclaimTask` in the last hour

**Comment by petemoore** [comment]
😭😭😭😭😭😭😭😭

**Comment by djmitche** [comment]
> only scans through the workers that are visible to the queue

When did that change occur? That's pretty bizarre!

**Comment by lotas** [comment]
> > only scans through the workers that are visible to the queue
> 
> When did that change occur? That's pretty bizarre!

those are mostly fuzzing windows machines, it happened few times in the past weeks, most common reason - generic-worker dies with OOM

**Comment by lotas** [comment]
so we know those generic workers die and they stop talking to queue api. We can check inside the scanner loop if they are known to queue, and if queue doesn't know about them anymore, it means something unexpected happen, so it should be stopped

**Comment by lotas** [comment]
I checked db again and it seems like those workers are actually being killed, but only after the `terminateAfter` timeout:
<img width="1343" alt="image" src="https://user-images.githubusercontent.com/83861/230052345-bd7cf364-80cf-4c02-aa86-4acfa24e4855.png">

So w-m does kill those, but not quick enough. 
So we need to think about a more reliable solution to see if worker is still alive or it should be removed

**Comment by petemoore** [comment]
> So w-m does kill those, but not quick enough. So we need to think about a more reliable solution to see if worker is still alive or it should be removed

I think this would be covered by the proposed solution above:

> Worker Manager should kill all instances that:
> 
> a) were requested more than e.g. 30 minutes ago, and are not yet known by the Queue, and
> b) workers that are known by the Queue, but haven’t called queue.claimWork nor queue.reclaimTask in the last hour

There is an a) and b) because a) is the case where a worker never shows up, and b) is the case that the worker shows up, but at some point disappears unexpectedly.
