### ISSUE TITLE
Investigate "terminateAfter time exceeded" errors

### ISSUE THREAD

**Issue by lotas** [taskcluster/taskcluster#6186]
While investigating `claim-expired` exceptions, I've noticed some pattern in azure workers - they are being created, register themselves, start claiming tasks, but then get shutdown with `terminateAfter time exceeded` reason.

There are hundreds of those daily and about 2k in a week. 
Usually termination and registration are 5-10min apart. 

My theory is that `worker-scanner` is operating on a "stale" data. It fetches batches of 1000 workers and then iterates them. 
What I think happens is that between `worker-scanner` has fetched this worker in batch, and by the time it reached it to check on state, worker has already started up, registered and started claiming work. Registration call should have updated `provider_data->>'terminateAfter'` to be +96hours (based on pool config). 
But `worker-scanner` doesn't refetch this record, so when it sees instance is running but `terminateAfter` has previous value, it forces this worker to be shut down, despite it doing some work already.

**Comment by lotas** [comment]
some of those might be the ones that were slow to start, and were not fully working after 30min (pool config)

**Comment by djmitche** [comment]
My general sense of Azure was that it is designed for forklifted datacenters. VMs are created once, probably via the portal, and then just run forever, or are maybe powered down and back up. So, the APIs for creating and destroying VMs aren't typically used in the dynamic way that TC uses them, and are slow and rate-limited and just difficult to automate this way.

It may be worth looking for other ways to do this. Maybe you can get some time from a CSE at Azure? Maybe there are other apps like TC that use Azure in a dynamic fashion, where we could learn some lessons?

**Comment by lotas** [comment]
I fetched from logs all workers that were terminated with `terminateAfter time` errors
There were `2108` in the last week. 
Then I ran a script for each of the worker to see if it was already doing something from the logs, and it showed that `1808` workers have been seen as registered and were already claiming work.
That's `85%`
