### ISSUE TITLE
Allow a configurable maxRunTime for generic worker

### ISSUE THREAD

**Issue by bhearsum** [taskcluster/taskcluster#6269]
As I understand it, generic worker currently hardcodes a maximum run time of 1 day (86400 seconds). This has been a pretty sane and safe default for a long time, but there are certain use cases where longer run times are useful and necessary. The specific example I'm working with now is training language models for Firefox Translations, but I know that @rail has unrelated use cases as well (and I'm sure there's others out there, eg: possibly fuzzing).

Allowing the max run time to be overridden in the generic worker config would be one way to accomplish this, and reduce the possibility of huge max run times for tasks in pools where it is absolutely not needed.

**Comment by gabrielBusta** [comment]
We really need this to run the ML model training tasks for firefox-translations-training. These tasks can run for weeks, and we would like to set the maxRunTime to a month (about 2 million seconds.) There are more details on https://github.com/mozilla/firefox-translations-training/issues/153

I guess we could also just bump the maximum on the schema to a bigger number? To unblock the model training? But... this seems like a good safeguard for other projects that don't run model training jobs.

What changes would be required to add a configuration field that allows the maximum run-time to be set per-pool?

**Comment by gabrielBusta** [comment]
IIUC what you are suggesting @bhearsum is a value in the config so we can set this maximum value?

    {
      "maximumMaxRunTime": 2628000,
      "accessToken": "********************************************",
      "cachesDir": "/Library/Caches/generic-worker/caches",
      "cleanUpTaskDirs": true,
      "clientId": "project/foo/bar/my/client",
      "disableReboots": false,
      "downloadsDir": "/Library/Caches/generic-worker/downloads",
      "ed25519SigningKeyLocation": "/etc/generic-worker/ed25519_key",
      ...
    }
The code in generic-worker doesn't seem to check the value of maxRunTime (and seems to rely on the generic-worker schemas to enforce the limit.)

Maybe we could delete for maximum for maxRunTime and enforce the limit using config? Then default that config value to a sensible default like 1 day?

**Comment by gabrielBusta** [comment]
Suggestion: could we get rid of the `maximum` in `maxRunTime`? Since the `maxRunTime` is `required` in the task payload, I think we can leave it up to the people implementing the task to decide what is an appropriate `maxRunTime` for the task being implemented. If do want to set a limit why not `9223372036854775807`? (the maximum value that can be represented with an `int64`.) Configuring it in a config value that can be read at run time sounds nice, but it seems counter-intuitive (to me.)

**Comment by gabrielBusta** [comment]
I tinkered with that possibility as well and it seems doable, but it just seemed kinda weird that it would fail at run-time and allow an invalid value pass the schema.

**Comment by gabrielBusta** [comment]
That being said, I guess it wouldn't hurt to add a safeguard in the form of a config value ¯\_(ツ)_/¯

**Comment by petemoore** [comment]
I do have one major concern here for the record, which I've shared here: https://github.com/mozilla/firefox-translations-training/issues/153#issuecomment-1672965678

**Comment by lotas** [comment]
I think we should close this one? @gabrielBusta made necessary changes and we merge his latest PR https://github.com/taskcluster/taskcluster/pull/6490 
Would be released soon
