### ISSUE TITLE
[UI] Stop rendering a List & ListITem in `TableCellListItem`

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#627]
Context: From https://github.com/taskcluster/taskcluster/pull/566#discussion_r277479268:

We should:
* Rename `TableCellListItem` to something else (something without the ListItem suffix)
* Possibly add the following diff:

```diff
diff --git a/ui/src/components/TableCellListItem/index.jsx b/ui/src/components/TableCellListItem/index.jsx
index 45a4cae94..48f869040 100644
--- a/ui/src/components/TableCellListItem/index.jsx
+++ b/ui/src/components/TableCellListItem/index.jsx
@@ -44,9 +44,11 @@ export default class TableCellListItem extends Component {
     return (
       <List
         dense={dense}
+        component="div"
         classes={{ root: classes.root }}
         className={className}>
         <ListItem
+          component="span"
           classes={{ gutters: classes.listItem }}
           className={classes.listItemButton}
           {...props}>
```

**Comment by ruchikabgosain** [comment]
Hey @helfi92 i would like to take this up. Since i'm a beginner, any guides would be appreciated! Thankyou :)

**Comment by helfi92** [comment]
Hey @ruchikabgosain. I believe you are working on https://github.com/taskcluster/taskcluster/issues/975. Once that is done, we could talk about your next issue. Hope that's okay :)

**Comment by ruchikabgosain** [comment]
Hey @helfi92 , right, i will let you know :)

**Comment by helfi92** [comment]
How is it going @ruchikabgosain?

**Comment by ruchikabgosain** [comment]
Hey Hassan
I'm still working on the previous issue and having some issues with it
since I haven't previously worked with React. It would be great if you
could help me out.
Thankyou and Have a nice weekend!

**Comment by ruchikabgosain** [comment]
Hey @helfi92 the previous issue has been done! Let me know if i can take this up?

**Comment by helfi92** [comment]
Go for it.
