### ISSUE TITLE
Skip CI works on dependabot PRs that include commits with this message in logs

### ISSUE THREAD

**Issue by lotas** [taskcluster/taskcluster#6304]
Dependabot opened a PR https://github.com/taskcluster/taskcluster/pull/6291 

In the release notes there was a commit:
```
9de3c00 chore(release): 6.4.2 [skip ci]
```
so no builds were produced.

Github shows that he is expecting tasks to run.
<img width="870" alt="image" src="https://github.com/taskcluster/taskcluster/assets/83861/99f907c0-5409-4ea4-8fe6-e7ffe8ecc0bb">

**Comment by lotas** [comment]
actually, [github](https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs) only checks commit messages, not pull request body, maybe we should follow same principle

**Comment by petemoore** [comment]
That works for me.

When we change this, we probably should add a note to the former RFC to say that behaviour has now been changed.
