### ISSUE TITLE
Handle spot termination notifications in google cloud

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#6318]
Currently we intercept spot termination notifications for [AWS](https://github.com/taskcluster/taskcluster/blob/da7a913ba011142a56b5e65ef26dba9217f0d11a/tools/worker-runner/provider/aws/awsprovider.go#L103-L120) and [Azure](https://github.com/taskcluster/taskcluster/blob/2ba0c51ddb0ce8a356e33db4b67622e07a906ce5/tools/worker-runner/provider/azure/azure.go#L111-L144) but not for Google Cloud.

Apparently we use spot VMs in Google Cloud too, so we should handle spot termination notifications there too. Google Cloud docs are [here](https://cloud.google.com/compute/docs/instances/spot#preemption).

**Comment by matt-boris** [comment]
Issue was tracked [here](https://github.com/taskcluster/taskcluster/issues/6530) and spot termination logic was improved upon in https://github.com/taskcluster/taskcluster/pull/6925.
