### ISSUE TITLE
Wayland support on Linux/multiuser

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#6319]
Currently Linux multiuser engine only supports gdm3. We should look into adding support for Wayland, since that is needed for firefox CI.

The UI integration for multiuser is currently pretty trivial, it is modelled after the Windows implementation, where it is assumed that a reboot and automatic login is required as a newly generated user in order to get a fresh graphical session.

It may be that this isn't required or optimal in general, so alternative approaches could also be investigated. May require consultation with Linux graphics domain experts.

**Comment by Eijebong** [comment]
I don't understand why any change is necessary here. Recent enough versions of gdm should be using a wayland graphical session by default. It's up to gdm's configuration to choose which system to use. See https://wiki.archlinux.org/title/GDM#Use_Xorg_backend

See also https://wiki.archlinux.org/title/GDM#Automatic_login to see how to change the session used by the auto log in.

**Comment by petemoore** [comment]
Thanks Bastien! 

> May require consultation with Linux graphics domain experts.

That's you! 😄 Thanks for your guidance here. Agreed it looks like we can continue to use gdm3 also with wayland, which as you say, is the default now in gdm.

At the moment, we only support running Generic Worker on Linux environments that are running Gnome Desktop Manager, which is a bit limited, so I'm keen to work out how we can/should support other setups too. The dependency on gdm is mostly to emulate what we do on other platforms (macOS, Windows) where we provide a desktop environment with a login session for a generated task user, and reboot the machine and auto-login as that user. It could well be that this is overkill for many tasks. It is done this way currently to try to provide realistic desktop environments for tests that require a real desktop. Let's discuss this in future community meetings, to see if we can work out what other use cases it makes sense to support. It may be that we then create other issues for other setups we want to support, and remove the dependency on gdm, which might not be what all task authors want to use.

**Comment by petemoore** [comment]
I'm going to reopen, since we are currently blocked on supporting Wayland without an X server on GCP due to #6412. When #6412 is resolved, we can probably close this issue, but I'll reopen it so we remember to check everything is working as required when #6412 has been fixed. Perhaps we will solve that issue, but encounter a new one that still prevents Wayland from running natively (without needing an X11 compatibility layer).
