### ISSUE TITLE
Higher priority decision tasks, or run in dedicated pool etc

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#6340]
Decision tasks block other tasks, yet they are scheduled with same priority as regular tasks. This means that sometimes entire task graphs are blocked by competing tasks of the same priority on the same worker pool, e.g. a build or test task could be delaying a decision task for a different push. I noticed this because we have a Generic Worker decision task which first has to be created by the mono repo decision task, and so it can take a long time before e.g. a Generic Worker build/test task is even generated, let alone run. We should solve that by moving the Generic Worker decision task into the main decision task, but it still highlights an issue. Note, this doesn't have to be solved with using a different priority, another option is having dedicated worker pool for decision tasks, which scales quickly, and has generous max capacity. Another option is fewer worker pools, and adjusted priority. This is probably more of a discussion point right now than a hard requirement. We have a few knobs we can tweak, would be nice to think about the situation holistically, and work out a nice solution that balances concerns and optimises end-to-end times as much as possible within given cost constraints etc.

**Comment by matt-boris** [comment]
Looks like we could try just including `Priority: "highest"` to [this block](https://github.com/taskcluster/taskcluster/blob/main/workers/generic-worker/gw-decision-task/main.go#L296-L314).

**Comment by matt-boris** [comment]
Ah, nvm. Looks like all tasks aside from the initial decision task get their priority from https://github.com/taskcluster/taskcluster/blob/main/taskcluster/ci/config.yml#L4
