### ISSUE TITLE
[Docs] Report docs links that are not found

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#635]
We probably have a lot of broken links from so many years of changing the docs. Given that we are dealing with a single page application, it would be tricky to use a crawler since it would be tricky to tell the crawler what a 404 page looks like. To that end, whenever a user lands on the 404 page in production, we should report that link to a place like Stackdriver.

**Comment by helfi92** [comment]
Blocker: https://github.com/taskcluster/taskcluster/issues/604

**Comment by petemoore** [comment]
> Given that we are dealing with a single page application, it would be tricky to use a crawler since it would be tricky to tell the crawler what a 404 page looks like.

@helfi92 Can we test for a 404 page based on the HTTP status code rather than the page content?

**Comment by helfi92** [comment]
We technically won't check for 404 because the docs are not stored in the server. They are stored locally. The way we could do it involves modifying the following  `catch` statement in https://github.com/taskcluster/taskcluster/blob/32d6afd4c525f3eb6eb5e1cb30491df9b02bf454/ui/src/views/Documentation/index.jsx#L126-L137 to be:

```jsx
catch (error) {
  this.setState({ error });

  if (err.code === 'MODULE_NOT_FOUND') {
    // Report link not found
  }
}
```

**Comment by kanurag94** [comment]
Hi @helfi92 , I started out with setting up taskcluster and came up with many broken links in contributing readme. I will be fixing them

**Comment by djmitche** [comment]
404s haven't been a big issue, to be honest.
