### ISSUE TITLE
[UI] Last fired result table "Result" column unclear

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#636]
From a discussion on IRC:

```
<pmoore> hassan: one small issue i noticed is that everything appears green here: https://taskcluster-web.netlify.com/hooks/hg-push/nss-try but if you click on the 4th/5th listed task, they actually failed (e.g. d0EzBuOFQSyBczrS0lxb6g)

<hassan> pmoore: i think the result column means the hook successfully triggered. it's probably not clear. i'll file a bug to make that clearer
```

Let's remove that confusion :)

**Comment by Biboswan** [comment]
Previously I named it the table title as `Last Fire Attempts` and may be replace `result` with Fire Status`?

**Comment by helfi92** [comment]
What do you think about "Trigger Status"?

**Comment by djmitche** [comment]
"Fire" means that the hook tried to create a task.

"Trigger" is specific to the triggerHook and triggerHookWithToken methods, and doesn't include firings at particular times or in response to pulse messages.

**Comment by Biboswan** [comment]
Hence i think `Fire Status` to be apt
