### ISSUE TITLE
Documentation: typo in several places, "exists" instead of "exits" 

### ISSUE THREAD

**Issue by titooan** [taskcluster/taskcluster#6484]
In TaskCluster documentation (eg [here](https://docs.taskcluster.net/docs/reference/workers/docker-worker/payload)), the word "exits" is written with a typo in several places

**Comment by djmitche** [comment]
There's a typo in the issue title too :) 
```patch
-If the task exists
+If the task exits
```

**Comment by titooan** [comment]
🙈 Oh that's ironic. 
Thanks for noticing!
