### ISSUE TITLE
`TestRevisionNumberStored` failure on main recently

### ISSUE THREAD

**Issue by Eijebong** [taskcluster/taskcluster#6513]
**Describe the bug**

```
--- FAIL: TestRevisionNumberStored (0.00s)
    main_test.go:55: Git revision could not be determined - got '' but expected to match regular expression '^[0-9a-f](40)$'
        Did you specify `-ldflags "-X github.com/taskcluster/taskcluster/v55/workers/generic-worker.revision=<GIT REVISION>"` in your go test command?
        Try building generic-worker using the /workers/generic-worker/build.(sh|cmd) script in the taskcluster monorepo.
```

**To Reproduce**
To match what CI is doing:

```
cd workers/generic-worker
export GW_TESTS_RUN_AS_CURRENT_USER=true
export GORACE=history_size=7
export CGO_ENABLED=1

go install -tags multiuser -v -ldflags '-X main.revision=8b8c2f92f348dd125177f719e4def3e280d9a34c' ./...
go test -tags multiuser -failfast -timeout 20m -ldflags '-X github.com/taskcluster/taskcluster/v54/workers/generic-worker.revision=8b8c2f92f348dd125177f719e4def3e280d9a34c' -race -vet=off . -run TestRevisionNumberStored
```

**Comment by Eijebong** [comment]
The test is checking the `revision` variable here: https://github.com/taskcluster/taskcluster/blob/baefd96a954ebc7b1248e68434eb965fadd479d4/workers/generic-worker/main.go#L65

This variable is supposed to be set at link time by `-ldflags '-X main.revision=8b8c2f92f348dd125177f719e4def3e280d9a34c'`.

During testing, we can see that it's actually set through the full package path, `'-X github.com/taskcluster/taskcluster/v54/workers/generic-worker.revision=8b8c2f92f348dd125177f719e4def3e280d9a34c'`

Now, if you don't pay much attention to that, it looks correct. Except we're on version 55 right now.

I started digging through the history and found out that every version bump would update the version in `tasks.yml`.

See https://github.com/taskcluster/taskcluster/commit/9fe17f6048329bc1ec63dad3a8e14b7ca879d1d6#diff-dca1e9fc9cc768f225a74371a9fb518db060e3e3e872093d22c9f3632489cf3dR191 and https://github.com/taskcluster/taskcluster/commit/56ad2310771e6655ea1bbff3dc6f84d19f37bcf9#diff-dca1e9fc9cc768f225a74371a9fb518db060e3e3e872093d22c9f3632489cf3dR191 for example.

`v55` did not do that, probably because the task was moved in 13c21c268bfc62726064ece7740b7ad92d70e21b from `workers/generic-worker/gw-decision-task/tasks.yml` to `taskcluster/ci/generic-worker/kind.yml`

**Comment by Eijebong** [comment]
Found it. https://github.com/taskcluster/taskcluster/blob/baefd96a954ebc7b1248e68434eb965fadd479d4/infrastructure/tooling/src/release/tasks.js#L209 was updating the previous file but not the new one. I'll add the new location to the list and fix the issue :)

**Comment by matt-boris** [comment]
Thanks so much for digging into this!
