### ISSUE TITLE
[github] Alerting on webhook event failure

### ISSUE THREAD

**Issue by ahal** [taskcluster/taskcluster#6537]
There was a recent Github webhook related outage where the events failed to validate the webhook secret. We didn't realize they were failing until developers started to complain ~3 hours later.

It would be nice if Taskcluster could generate some kind of alerts when webhooks fail so we get notified sooner. We probably don't want to alert on unsupported events though.

**Comment by matt-boris** [comment]
Yarik did make it report that signature mismatch error to sentry now in https://github.com/taskcluster/taskcluster/pull/6531.

Are you referring to more generally speaking, all webhook failures?

**Comment by ahal** [comment]
Ah this is probably good enough! Thanks. I'm not sure where these end up or whether releng has access, but that's not a TC problem.
