### ISSUE TITLE
[UI] Resetting the store causes issues in the UI

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#654]
STR:

1. Navigate to https://taskcluster-web.netlify.com/tasks/groups/e_7vMlcZTcys5OQ03EPFSQ while being logged out
2. Login

Expected: 

<img width="1336" alt="Screen Shot 2019-04-29 at 6 53 40 PM" src="https://user-images.githubusercontent.com/3766511/56932030-263f9400-6ab0-11e9-9a51-a2305dd5dc70.png">

Actual: The task status cards shows a loading symbol that never goes away 

<img width="1336" alt="Screen Shot 2019-04-29 at 6 53 03 PM" src="https://user-images.githubusercontent.com/3766511/56932011-12942d80-6ab0-11e9-94ed-c3b393c302b4.png">

The culprit: https://github.com/taskcluster/taskcluster/blob/771c78c6d6606591e51c1576e4555defc31894e9/ui/src/components/SignInDialog/index.jsx#L70

This line causes the store to be cleared and all active queries to be refetched. The only problem is that for many of our views, we depend on `fetchMore` to fetch the full list. Refetching active queries will only fetch the first query.

To fix this issue, we should rely on the `key` prop and the `networkPolicy` property to refetch active queries. Changing the `key` prop of a component in React will re-render that component. This will have a similar effect as `resetStore`.

**Comment by djmitche** [comment]
In "Learning GraphQL", I noticed that the process they use is `cache.readQuery` -> modify value -> `cache.writeQuery`.  Would that help in this case?

**Comment by helfi92** [comment]
> In "Learning GraphQL", I noticed that the process they use is cache.readQuery -> modify value -> cache.writeQuery. Would that help in this case?

We want to re-fetch the full query when a user logs in/out to make sure the state reflects the current user's permissions. `readQuery` and `writeQuery` only interacts with the cache unfortunately.
