### ISSUE TITLE
Fix SchemaTable to parse refs relatively

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#657]
The `readReference` function in `ui/src/components/SchemaTable/index.jsx` currently treats relative `$ref` as relative to id `/schemas/<serviceName>`.  This is the calculation that should be used to find a schema for a reference document's "input" or "output" property, but *not* how `$ref` should be parsed -- it should be parsed using the usual relative-URL joining.

**Comment by djmitche** [comment]
WIP on `issue657`.  I'll wait until #651 lands, as I think this will conflict.

**Comment by helfi92** [comment]
Possibly related: https://github.com/taskcluster/taskcluster/issues/689.
