### ISSUE TITLE
Windows Defender interfering with Generic Worker unit test TestAbortAfterMaxRunTime

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#6578]
We are getting permanent failure of Generic Worker unit test TestAbortAfterMaxRunTime on Windows Server 2022.

Cause is upstream issue: https://github.com/mozilla/community-tc-config/issues/681

**Comment by matt-boris** [comment]
Upstream issue was fixed and deployed out to our windows machines. First tested successfully here https://community-tc.services.mozilla.com/tasks/TDnLOLtwSTGlg0aAo1pzsw. Closing.
