### ISSUE TITLE
[web-server] log credential generation

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#662]
https://github.com/taskcluster/taskcluster/pull/547/files#r276752600

**Comment by helfi92** [comment]
I assume you want this to be done via `monitor.info()`.

**Comment by djmitche** [comment]
This partly addresses https://bugzilla.mozilla.org/show_bug.cgi?id=1307271 (but that bug also includes logging for changes to roles and clients' scopes, from the auth service)
