### ISSUE TITLE
CI tasks should depend on linting to succeed before running

### ISSUE THREAD

**Issue by matt-boris** [taskcluster/taskcluster#6621]
This will help to not waste resources.

Here's an example with go lint failing https://community-tc.services.mozilla.com/tasks/groups/JJQw9Kj6RIaN6ykMO6jXnw. Ideally, the tests wouldn't start until `lint-golang` is successful.

This should be done for go, node, and python (if applicable).

**Comment by lotas** [comment]
Is this only about `go`? 
In `js` it can be lint failing on unnecessary `;` so isn't really blocking. But maybe those could be separated somehow by severity

**Comment by matt-boris** [comment]
Doesn't look like this is an issue with nodejs. It will only fail the `lint-nodejs` task. I'm checking now for python...

**Comment by matt-boris** [comment]
Also not an issue with python. I'll just fix for go then :)
