### ISSUE TITLE
`yarn run` doesn't support shell like `npm run`

### ISSUE THREAD

**Issue by lotas** [taskcluster/taskcluster#6668]
At the moment `yarn run dev:start` will not work because yarn's shell interpreter [does not support control structures](https://github.com/yarnpkg/berry/tree/master/packages/yarnpkg-shell#non-goals)

`npm run dev:start` still works

This problem can be fixed in several ways:
- generate `docker-compose.override.yml` separately and always assume it exists
- move that logic into separate (shell) script and invoke it instead

**Comment by matt-boris** [comment]
This is related to our recent upgrade to yarn v4 https://github.com/taskcluster/taskcluster/pull/6646.

**Comment by Eijebong** [comment]
Just got hit by that. An easy workaround would be something like this:

```diff
diff --git a/package.json b/package.json
index 4fde3f998..5a3bf45da 100644
--- a/package.json
+++ b/package.json
@@ -190,7 +190,7 @@
     "changelog:check": "node infrastructure/tooling/src/main.js changelog:check",
     "start": "docker compose up -d",
     "stop": "docker compose down --remove-orphans",
-    "dev:start": "docker compose -f docker-compose.yml -f docker-compose.dev.yml `if [ -e ./docker-compose.override.yml ]; then echo '-f docker-compose.override.yml'; fi` up -d",
+    "dev:start": "sh -c \"docker compose -f docker-compose.yml -f docker-compose.dev.yml `if [ -e ./docker-compose.override.yml ]; then echo '-f docker-compose.override.yml'; fi` up -d\"",
     "dev:stop": "docker compose -f docker-compose.yml -f docker-compose.dev.yml `if [ -e ./docker-compose.override.yml ]; then echo '-f docker-compose.override.yml'; fi` down --remove-orphans",
     "prod:start": "docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d",
     "prod:stop": "docker compose -f docker-compose.yml -f docker-compose.prod.yml down --remove-orphans",
```

**Comment by lotas** [comment]
yeah, or we just use a dedicated `.sh` script for this :) 

Another approach could be to add a proper local dev init step. Which could create default override file, initialize static clients. (There avoid storing hardcoded credentials in `./docker/env/.svc` files)

**Comment by thakkarujas5** [comment]
Hi, I would like to work on this issue.

**Comment by lotas** [comment]
@thakkarujas5 ticket is yours :)

**Comment by thakkarujas5** [comment]
Hi,  @lotas do we want to go with the sh script approach or the alternate approach you suggested of the local dev init step? If it is the second approach, can you brief about the idea a little bit more?

**Comment by lotas** [comment]
hi @thakkarujas5 
I think the simplest the better, we can go with `sh` approach, thanks

**Comment by thakkarujas5** [comment]
`#!/bin/bash

if [ -e ./docker-compose.override.yml ]; then
    override_file="-f docker-compose.override.yml"
    docker compose -f docker-compose.yml -f docker-compose.dev.yml $override_file up -d
fi
`

Have added this sh script, do we need any more checks?

Also made similar change for the dev:stop script

**Comment by lotas** [comment]
> #!/bin/bash
> 
> if [ -e ./docker-compose.override.yml ]; then override_file="-f docker-compose.override.yml" docker compose -f docker-compose.yml -f docker-compose.dev.yml $override_file up -d fi
> 
> Have added this sh script, do we need any more checks?
> 
> Also made similar change for the dev:stop script

Thanks!
I don't have a strong opinion, but maybe keeping it inside the `package.json` would be easier for now with the `sh -c ".."` approach? Less files to manage :)

**Comment by thakkarujas5** [comment]
Raised the PR with appropriate changes.

**Comment by lotas** [comment]
Thanks @thakkarujas5
