### ISSUE TITLE
generic worker sometimes shuts down a worker while seemingly working on a task

### ISSUE THREAD

**Issue by bhearsum** [taskcluster/taskcluster#6681]
A concrete case of this that I came across yesterday was with https://firefox-ci-tc.services.mozilla.com/tasks/bs8RlnGKTOebtoPHGHt_4A/runs/0, which ran on Windows in Azure. We can see that run 0 was claimed at `2023-11-13T17:40:38.174Z` by `vm-adjkhsxbq02zfovzpgatfaftfjp3dlqewam`, and then resolved 20 minutes later with `CLAIM_EXPIRED`. In the worker logs, I found what seems to be contradictory information:
```
Nov 13 17:40:36Z vm-adjkhsxbq02zfovzpgatfaftfjp3dlqewam.reddog.microsoft.com worker-runner-service 2023/11/13 17:40:36 polling for termination-time 
Nov 13 17:41:06Z vm-adjkhsxbq02zfovzpgatfaftfjp3dlqewam.reddog.microsoft.com worker-runner-service 2023/11/13 17:41:06 polling for termination-time 
Nov 13 17:41:36Z vm-adjkhsxbq02zfovzpgatfaftfjp3dlqewam.reddog.microsoft.com worker-runner-service 2023/11/13 17:41:36 polling for termination-time 
Nov 13 17:42:06Z vm-adjkhsxbq02zfovzpgatfaftfjp3dlqewam.reddog.microsoft.com worker-runner-service 2023/11/13 17:42:06 polling for termination-time 
Nov 13 17:42:30Z vm-adjkhsxbq02zfovzpgatfaftfjp3dlqewam.reddog.microsoft.com worker-runner-service 2023/11/13 17:42:30 Error: (Intermittent) HTTP response code 502 
Nov 13 17:42:30Z vm-adjkhsxbq02zfovzpgatfaftfjp3dlqewam.reddog.microsoft.com worker-runner-service HTTP/2.0 502 Bad Gateway 
Nov 13 17:42:30Z vm-adjkhsxbq02zfovzpgatfaftfjp3dlqewam.reddog.microsoft.com worker-runner-service Content-Length: 332 
Nov 13 17:42:30Z vm-adjkhsxbq02zfovzpgatfaftfjp3dlqewam.reddog.microsoft.com worker-runner-service Alt-Svc: clear 
Nov 13 17:42:30Z vm-adjkhsxbq02zfovzpgatfaftfjp3dlqewam.reddog.microsoft.com worker-runner-service Content-Type: text/html; charset=UTF-8 
Nov 13 17:42:30Z vm-adjkhsxbq02zfovzpgatfaftfjp3dlqewam.reddog.microsoft.com worker-runner-service Date: Mon, 13 Nov 2023 17:42:30 GMT 
Nov 13 17:42:30Z vm-adjkhsxbq02zfovzpgatfaftfjp3dlqewam.reddog.microsoft.com worker-runner-service Referrer-Policy: no-referrer 
Nov 13 17:42:30Z vm-adjkhsxbq02zfovzpgatfaftfjp3dlqewam.reddog.microsoft.com worker-runner-service <html><head> 
Nov 13 17:42:30Z vm-adjkhsxbq02zfovzpgatfaftfjp3dlqewam.reddog.microsoft.com worker-runner-service <meta http-equiv="content-type" content="text/html;charset=utf-8"> 
Nov 13 17:42:30Z vm-adjkhsxbq02zfovzpgatfaftfjp3dlqewam.reddog.microsoft.com worker-runner-service <title>502 Server Error</title> 
Nov 13 17:42:30Z vm-adjkhsxbq02zfovzpgatfaftfjp3dlqewam.reddog.microsoft.com worker-runner-service </head> 
Nov 13 17:42:30Z vm-adjkhsxbq02zfovzpgatfaftfjp3dlqewam.reddog.microsoft.com worker-runner-service <body text=#000000 bgcolor=#ffffff> 
Nov 13 17:42:30Z vm-adjkhsxbq02zfovzpgatfaftfjp3dlqewam.reddog.microsoft.com worker-runner-service <h1>Error: Server Error</h1> 
Nov 13 17:42:30Z vm-adjkhsxbq02zfovzpgatfaftfjp3dlqewam.reddog.microsoft.com worker-runner-service <h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2> 
Nov 13 17:42:30Z vm-adjkhsxbq02zfovzpgatfaftfjp3dlqewam.reddog.microsoft.com worker-runner-service <h2></h2> 
Nov 13 17:42:30Z vm-adjkhsxbq02zfovzpgatfaftfjp3dlqewam.reddog.microsoft.com worker-runner-service </body></html> 
Nov 13 17:42:36Z vm-adjkhsxbq02zfovzpgatfaftfjp3dlqewam.reddog.microsoft.com worker-runner-service 2023/11/13 17:42:36 polling for termination-time 
Nov 13 17:42:50Z vm-adjkhsxbq02zfovzpgatfaftfjp3dlqewam.reddog.microsoft.com worker-runner-service 2023/11/13 17:42:50 No task claimed. Idle for 7m14.3394143s (will exit if no task claimed in 2m45.6605857s). 
<more of the same for a bit>
 Nov 13 17:45:47Z vm-adjkhsxbq02zfovzpgatfaftfjp3dlqewam.reddog.microsoft.com worker-runner-service 2023/11/13 17:45:46 Looking for existing task users to delete... 
Nov 13 17:45:47Z vm-adjkhsxbq02zfovzpgatfaftfjp3dlqewam.reddog.microsoft.com worker-runner-service 2023/11/13 17:45:46 Running command: wmic useraccount get name 
Nov 13 17:45:47Z vm-adjkhsxbq02zfovzpgatfaftfjp3dlqewam.reddog.microsoft.com worker-runner-service 2023/11/13 17:45:46 Worker idle for idleShutdownTimeoutSecs seconds (10m10.2536984s) 
Nov 13 17:45:47Z vm-adjkhsxbq02zfovzpgatfaftfjp3dlqewam.reddog.microsoft.com worker-runner-service 2023/11/13 17:45:46 Saving file file-caches.json (absolute path: C:\worker-runner\file-caches.json) 
Nov 13 17:45:47Z vm-adjkhsxbq02zfovzpgatfaftfjp3dlqewam.reddog.microsoft.com worker-runner-service 2023/11/13 17:45:46 Saving file directory-caches.json (absolute path: C:\worker-runner\directory-caches.json) 
Nov 13 17:45:47Z vm-adjkhsxbq02zfovzpgatfaftfjp3dlqewam.reddog.microsoft.com worker-runner-service 2023/11/13 17:45:46 Running command: icacls 'file-caches.json' /grant:r 'Administrators:(GA)' /inheritance:r 
Nov 13 17:45:47Z vm-adjkhsxbq02zfovzpgatfaftfjp3dlqewam.reddog.microsoft.com worker-runner-service 2023/11/13 17:45:46 Running command: icacls 'directory-caches.json' /grant:r 'Administrators:(GA)' /inheritance:r 
Nov 13 17:45:47Z vm-adjkhsxbq02zfovzpgatfaftfjp3dlqewam.reddog.microsoft.com worker-runner-service 2023/11/13 17:45:46 Running command: icacls 'tasks-resolved-count.txt' /grant:r 'Administrators:(GA)' /inheritance:r 
Nov 13 17:45:47Z vm-adjkhsxbq02zfovzpgatfaftfjp3dlqewam.reddog.microsoft.com worker-runner-service 2023/11/13 17:45:46 Exiting worker with exit code 68 
Nov 13 17:45:47Z vm-adjkhsxbq02zfovzpgatfaftfjp3dlqewam.reddog.microsoft.com worker-runner-service
2023/11/13 17:45:46 WORKER_METRICS {"eventType":"instanceShutdown","instanceType":"Standard_F8s_v2","region":"eastus","timestamp":1699897546,"worker":"generic-worker","workerId":"vm-adjkhsxbq02zfovzpgatfaftfjp3dlqewam","workerPoolId":"gecko-t/win10-64-2009"} 
Nov 13 17:45:47Z vm-adjkhsxbq02zfovzpgatfaftfjp3dlqewam.reddog.microsoft.com worker-runner-service 2023/11/13 17:45:46 Immediate shutdown being issued... 
Nov 13 17:45:47Z vm-adjkhsxbq02zfovzpgatfaftfjp3dlqewam.reddog.microsoft.com worker-runner-service 2023/11/13 17:45:46 Running command: 'C:\Windows\System32\shutdown.exe' /s /t 3 /c 'generic-worker idle timeout' 
Nov 13 17:45:47Z vm-adjkhsxbq02zfovzpgatfaftfjp3dlqewam.reddog.microsoft.com worker-runner-service 2023/11/13 17:45:46 exit status 68 
```

Notably, there's nothing around the claim time that indicates the worker claimed the task (just the `polling for termination-time` messages). A couple of minutes later there's a 502 which presumably originated from the termination polling code, although it's difficult to be sure. Eventually we get `No task claimed`, and a warning that the worker will shut down, which it eventually does.

https://firefox-ci-tc.services.mozilla.com/tasks/DZvVQ-VUTPSyPBBS13Bwfg/runs/0 is another example of where this _may_ have happened (we don't have worker nor live logs for these, unfortunately, so it's difficult to confirm). This is a Linux task in GCP, and in both run 0 and run 1 the worker disappeared after a number of hours. https://firefox-ci-tc.services.mozilla.com/tasks/Gc5b4d-JT-OrIhhcppbd3g/runs/0 is another case like that, except we see the same thing with the Windows task above, where the expiration happens after 20 minutes.

I haven't had a chance to run any queries yet, but 9/10 retries I found on https://treeherder.mozilla.org/jobs?repo=mozilla-central&resultStatus=retry%2Crunning%2Cpending%2Crunnable&selectedTaskRun=AyJIoo5gQXCrAjBvCLSFow.0 seem to be hitting this, and it happens on Linux, Mac, and Windows.

**Comment by bhearsum** [comment]
Here's a quick query showing a big spike in claim expired beginning around the start of October: https://sql.telemetry.mozilla.org/queries/95924/source?p_date=2023-08-01#236915

**Comment by bhearsum** [comment]
I ended up filing https://github.com/taskcluster/taskcluster/issues/6682 for the claim expired increase, which may or may not be the same root cause.

**Comment by lotas** [comment]
Yes, we are debugging logs of this task and this worker and came to a conclusion that `502` was indeed coming from taskcluster api, not internal metadata endpoint. Timestamps match perfectly.

What happens here:
1. worker calls `queue.claimWork`
2. queue responds with a task after 8s
3. worker keeps waiting for this response, but it's lost somewhere between k8s pod, ingress, load balancer and worker
4. after a minute or longer GLB sends `502` because it couldn't relay the response from the pod
5. worker thinks it was temp issues, keep polling for more work with `queue.claimWork`

So we have an issue here is that queue service have no way to tell if work that was assigned to a worker is being actually executed.  For queue service it looks like worker is simply asking for more work.

I guess we can close this one and focus on the #6682. 

Also, this perfectly explains why we couldn't find reasons for large amount of claim-expires in the past, because we didn't consider this scenario back then.

**Comment by bhearsum** [comment]
I'm good with that.

> https://firefox-ci-tc.services.mozilla.com/tasks/DZvVQ-VUTPSyPBBS13Bwfg/runs/0 is another example of where this may have happened (we don't have worker nor live logs for these, unfortunately, so it's difficult to confirm). 

For completeness, I'll note that I confirmed that this was actually a spot termination and unrelated to #6682.

**Comment by petemoore** [comment]
> I'm good with that.
> 
> > https://firefox-ci-tc.services.mozilla.com/tasks/DZvVQ-VUTPSyPBBS13Bwfg/runs/0 is another example of where this may have happened (we don't have worker nor live logs for these, unfortunately, so it's difficult to confirm).
> 
> For completeness, I'll note that I confirmed that this was actually a spot termination and unrelated to #6682.

Spot terminations should result in exception/worker-shutdown rather than claim-expired, so there is definitely something up there too. Workers are meant to detect incoming spot terminations, and handle them, before the spot termination occurs. They should have ample notice in order to resolve the task as exception/worker-shutdown and upload artifacts. Another thing that is curious is that claim-expired task has artifacts uploaded, which normally occurs at the end of a task, which normally we would not reach with claim-expired, so this one still is a bit of a mystery for me.

**Comment by bhearsum** [comment]
I ended up filing https://github.com/taskcluster/taskcluster/issues/6684 for the spot termination part of this.
