### ISSUE TITLE
spot termination on generic worker not handled gracefully

### ISSUE THREAD

**Issue by bhearsum** [taskcluster/taskcluster#6684]
I've seen this a number of times on translations workers. A concrete example is https://firefox-ci-tc.services.mozilla.com/tasks/DZvVQ-VUTPSyPBBS13Bwfg/runs/1, which ran for 11 hours before being terminated (which I confirmed with the Cloud Audit logs). It managed to upload a few artifacts, but not everything that we expected to exist at that point.

The run resolved with `CLAIM_EXPIRED`, which I understand is not what's expected in this scenario.

Unfortunately, we do not have worker or worker runner logs for these instances at the moment, so I can't provide any of that information. I also looked in the GCP Console for logs, but there was nothing other than initial startup (before generic worker runs), and the preemption notice.

This happened with the simple engine, and version 55.1.1.

**Comment by Eijebong** [comment]
For the record, that version is the one that added spot termination handling for GCP https://github.com/taskcluster/taskcluster/releases/tag/v55.1.1

**Comment by bhearsum** [comment]
I _think_ we established that this was caused by worker runner, not generic worker. We're currently working to upgrade that on the affected workers. I'll re-open or file something new if we see still have issues after that.
