### ISSUE TITLE
generic-worker binary is not readable and executable by task user

### ISSUE THREAD

**Issue by jschwartzentruber** [taskcluster/taskcluster#6701]
**Describe the bug**
Darwin simple generic-worker returns exit code 69 because executable check fails.
The task works fine in v58.0.0, so I there is something invalid in the check.

**To Reproduce**

The worker is started from a github check using this script:
https://github.com/MozillaSecurity/grizzly/blob/d39806b4c1639315cc8427217c118bb62ee6bcfa/.github/scripts/start-worker.sh

**Expected behavior**
Task should run without error.

**Taskcluster version**
v58.0.1

**Screenshots**

failing worker (v58.0.1):
https://github.com/MozillaSecurity/grizzly/actions/runs/6961104216/job/18942015809?pr=390

successful worker (v58.0.0):
https://github.com/MozillaSecurity/grizzly/actions/runs/6961763493/job/18944044575

**Platform (please complete the following information):**

 - OS: darwin (amd64)
 - Version 12.6.9

**Additional context**

**Comment by matt-boris** [comment]
So right [here](https://github.com/MozillaSecurity/grizzly/blob/d39806b4c1639315cc8427217c118bb62ee6bcfa/.github/scripts/start-worker.sh#L51), I would try `chmod a+x …` instead.

This is what we use in our image building process and it’s worked well for us and that’s what’s documented in the installation steps https://docs.taskcluster.net/docs/reference/workers/generic-worker/installing

**Comment by matt-boris** [comment]
https://pkg.go.dev/os/exec#Cmd.Dir needed to be set to the empty string for simple engine. PR incoming...
