### ISSUE TITLE
[Docs] Write a simple crawler that indexes our doc files

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#677]
Problem: https://taskcluster-web.netlify.com/docs doesn't have a search bar that can search through our docs.

Solution: Let's write a simple crawler that indexes the .md/.mdx files. We would then be able to use the result of that crawler to add search support to our docs.

**Comment by arshadkazmi42** [comment]
I would like to take this up.
Can you give some more details on the issue. What type of crawler is needed here?

**Comment by helfi92** [comment]
Hey @arshadkazmi42 👋

I have an implementation on my local machine of the crawler. I just need to finalize it and then I should be ready to push it. Once the crawler is merged, we will need to hook it up to the frontend. Maybe you can help here :) I should have assigned the issue to myself earlier. Sorry for the trouble. I'll ping you once we are ready with the second part of this task.
