### ISSUE TITLE
The claimed tasks / pending tasks view don't display errors if the can't fetch the task list

### ISSUE THREAD

**Issue by Eijebong** [taskcluster/taskcluster#6775]
Go here without being authenticated: https://community-tc.services.mozilla.com/provisioners/proj-mozci/worker-types/ci/claimed-tasks

See nothing happen, look at network requests.

![image](https://github.com/taskcluster/taskcluster/assets/3650385/386bc641-5a4b-44bc-adcf-c0ccf4ee1863)

![image](https://github.com/taskcluster/taskcluster/assets/3650385/2556a957-ae6d-474f-b6f2-3f2ef755e757)

**Comment by lotas** [comment]
Awesome :) Thanks!
