### ISSUE TITLE
feature request: /tasks/create: provide a simple payload for each worker type

### ISSUE THREAD

**Issue by aerickson** [taskcluster/taskcluster#6792]
The /tasks/create web interface is super handy for testing work pools, but certain payloads (docker-worker) are painful to craft by hand. 

It would be sweet if there was a button (perhaps next to validate) to inject a basic helloWorld config into the editor that would provide a starting point.

**Comment by matt-boris** [comment]
If you change your schema from the dropdown next to the validate schema button, then in the bottom right, click on reset editor, it'll do what you're requesting :) Unless you're referring more to a direct button to do this vs this path?

**Comment by aerickson** [comment]
Aaah, exactly what I wanted. :) A bit hidden, but I can live with it. Thanks!

**Comment by lotas** [comment]
I think we could move that button indeed. It's not obvious that reset will update the payload as needed.
