### ISSUE TITLE
Task log page "Raw Log" button should not use stale signed URLs

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#6795]
**Describe the bug**
When clicking on "Raw Log" you can currently receive a 401 error (even for public artifacts!), if you opened then task log page more than 60s beforehand. It would be better to sign the url with a bewit at the time the user clicks "Raw Log" rather than when the page is rendered.
Note, #6724 is about not signing urls for public artifacts, which is related, but not the same as this issue.

**Comment by lotas** [comment]
URL is generated at render time here:
https://github.com/taskcluster/taskcluster/blob/main/ui/src/views/Tasks/TaskLog/index.jsx#L84

We could generate the url at click time to avoid this error

**Comment by Eijebong** [comment]
FYI, this is the same as #5033

**Comment by lotas** [comment]
oh indeed, thanks @Eijebong
I'll close both when the fix will be ready.
