### ISSUE TITLE
spot instance terminations in GCP aren't handled correctly

### ISSUE THREAD

**Issue by bhearsum** [taskcluster/taskcluster#6802]
https://firefox-ci-tc.services.mozilla.com/tasks/GYYVwr5RS-61EM8otXtMNg/runs/0 is a task that I confirmed to be killed by a spot instance preemption. Logs show it being noticed and handled:
> Jan 25 11:17:12Z [translations-1-b-linux-v100-gpu-4-300g-zlyc9cmhtlqiaqxuzsym0q-1](https://my.papertrailapp.com/systems/translations-1-b-linux-v100-gpu-4-300g-zlyc9cmhtlqiaqxuzsym0q-1/events?focus=1687134496819937292&selected=1687134496819937292) [start-worker](https://my.papertrailapp.com/groups/1141234/events?q=program%3Astart-worker&focus=1687134496819937292&selected=1687134496819937292) 2024/01/25 11:17:11 GCP Metadata Service says termination is imminent
Jan 25 11:17:12Z [translations-1-b-linux-v100-gpu-4-300g-zlyc9cmhtlqiaqxuzsym0q-1](https://my.papertrailapp.com/systems/translations-1-b-linux-v100-gpu-4-300g-zlyc9cmhtlqiaqxuzsym0q-1/events?focus=1687134496819937294&selected=1687134496819937294) [start-worker](https://my.papertrailapp.com/groups/1141234/events?q=program%3Astart-worker&focus=1687134496819937294&selected=1687134496819937294) 2024/01/25 11:17:11 Got graceful-termination request with finish-tasks=false
Jan 25 11:17:12Z [translations-1-b-linux-v100-gpu-4-300g-zlyc9cmhtlqiaqxuzsym0q-1](https://my.papertrailapp.com/systems/translations-1-b-linux-v100-gpu-4-300g-zlyc9cmhtlqiaqxuzsym0q-1/events?focus=1687134496819937297&selected=1687134496819937297) [start-worker](https://my.papertrailapp.com/groups/1141234/events?q=program%3Astart-worker&focus=1687134496819937297&selected=1687134496819937297) 2024/01/25 11:17:11 Killing process tree with parent PID 1637... (0xc000308a20)
Jan 25 11:17:12Z [translations-1-b-linux-v100-gpu-4-300g-zlyc9cmhtlqiaqxuzsym0q-1](https://my.papertrailapp.com/systems/translations-1-b-linux-v100-gpu-4-300g-zlyc9cmhtlqiaqxuzsym0q-1/events?focus=1687134496819937298&selected=1687134496819937298) [start-worker](https://my.papertrailapp.com/groups/1141234/events?q=program%3Astart-worker&focus=1687134496819937298&selected=1687134496819937298) 2024/01/25 11:17:11 Process tree with parent PID 1637 killed.
Jan 25 11:17:12Z [translations-1-b-linux-v100-gpu-4-300g-zlyc9cmhtlqiaqxuzsym0q-1](https://my.papertrailapp.com/systems/translations-1-b-linux-v100-gpu-4-300g-zlyc9cmhtlqiaqxuzsym0q-1/events?focus=1687134496824131587&selected=1687134496824131587) [start-worker](https://my.papertrailapp.com/groups/1141234/events?q=program%3Astart-worker&focus=1687134496824131587&selected=1687134496824131587) 2024/01/25 11:17:11 WARNING: no such process
Jan 25 11:17:12Z [translations-1-b-linux-v100-gpu-4-300g-zlyc9cmhtlqiaqxuzsym0q-1](https://my.papertrailapp.com/systems/translations-1-b-linux-v100-gpu-4-300g-zlyc9cmhtlqiaqxuzsym0q-1/events?focus=1687134496824131588&selected=1687134496824131588) [start-worker](https://my.papertrailapp.com/groups/1141234/events?q=program%3Astart-worker&focus=1687134496824131588&selected=1687134496824131588) 2024/01/25 11:17:11 Killing process tree with parent PID 1638... (0xc000308b70)
Jan 25 11:17:12Z [translations-1-b-linux-v100-gpu-4-300g-zlyc9cmhtlqiaqxuzsym0q-1](https://my.papertrailapp.com/systems/translations-1-b-linux-v100-gpu-4-300g-zlyc9cmhtlqiaqxuzsym0q-1/events?focus=1687134496878657541&selected=1687134496878657541) [start-worker](https://my.papertrailapp.com/groups/1141234/events?q=program%3Astart-worker&focus=1687134496878657541&selected=1687134496878657541) 2024/01/25 11:17:11 Process tree with parent PID 1638 killed.
Jan 25 11:17:12Z [translations-1-b-linux-v100-gpu-4-300g-zlyc9cmhtlqiaqxuzsym0q](https://my.papertrailapp.com/systems/translations-1-b-linux-v100-gpu-4-300g-zlyc9cmhtlqiaqxuzsym0q/events?focus=1687134498824814592&selected=1687134498824814592) [start-worker](https://my.papertrailapp.com/groups/1141234/events?q=program%3Astart-worker&focus=1687134498824814592&selected=1687134498824814592) 2024/01/25 11:17:11 polling for termination-time
Jan 25 11:17:12Z [translations-1-b-linux-v100-gpu-4-300g-zlyc9cmhtlqiaqxuzsym0q](https://my.papertrailapp.com/systems/translations-1-b-linux-v100-gpu-4-300g-zlyc9cmhtlqiaqxuzsym0q/events?focus=1687134498824814593&selected=1687134498824814593) [start-worker](https://my.papertrailapp.com/groups/1141234/events?q=program%3Astart-worker&focus=1687134498824814593&selected=1687134498824814593) 2024/01/25 11:17:11 GCP Metadata Service says termination is imminent
Jan 25 11:17:12Z [translations-1-b-linux-v100-gpu-4-300g-zlyc9cmhtlqiaqxuzsym0q](https://my.papertrailapp.com/systems/translations-1-b-linux-v100-gpu-4-300g-zlyc9cmhtlqiaqxuzsym0q/events?focus=1687134498824814594&selected=1687134498824814594) [start-worker](https://my.papertrailapp.com/groups/1141234/events?q=program%3Astart-worker&focus=1687134498824814594&selected=1687134498824814594) 2024/01/25 11:17:11 Got graceful-termination request with finish-tasks=false
Jan 25 11:17:12Z [translations-1-b-linux-v100-gpu-4-300g-zlyc9cmhtlqiaqxuzsym0q](https://my.papertrailapp.com/systems/translations-1-b-linux-v100-gpu-4-300g-zlyc9cmhtlqiaqxuzsym0q/events?focus=1687134498824814595&selected=1687134498824814595) [start-worker](https://my.papertrailapp.com/groups/1141234/events?q=program%3Astart-worker&focus=1687134498824814595&selected=1687134498824814595) 2024/01/25 11:17:11 Killing process tree with parent PID 1637... (0xc000308a20)
Jan 25 11:17:12Z [translations-1-b-linux-v100-gpu-4-300g-zlyc9cmhtlqiaqxuzsym0q](https://my.papertrailapp.com/systems/translations-1-b-linux-v100-gpu-4-300g-zlyc9cmhtlqiaqxuzsym0q/events?focus=1687134498824814596&selected=1687134498824814596) [start-worker](https://my.papertrailapp.com/groups/1141234/events?q=program%3Astart-worker&focus=1687134498824814596&selected=1687134498824814596) 2024/01/25 11:17:11 Process tree with parent PID 1637 killed.
Jan 25 11:17:12Z [translations-1-b-linux-v100-gpu-4-300g-zlyc9cmhtlqiaqxuzsym0q](https://my.papertrailapp.com/systems/translations-1-b-linux-v100-gpu-4-300g-zlyc9cmhtlqiaqxuzsym0q/events?focus=1687134498824814597&selected=1687134498824814597) [start-worker](https://my.papertrailapp.com/groups/1141234/events?q=program%3Astart-worker&focus=1687134498824814597&selected=1687134498824814597) 2024/01/25 11:17:11 WARNING: no such process
Jan 25 11:17:12Z [translations-1-b-linux-v100-gpu-4-300g-zlyc9cmhtlqiaqxuzsym0q](https://my.papertrailapp.com/systems/translations-1-b-linux-v100-gpu-4-300g-zlyc9cmhtlqiaqxuzsym0q/events?focus=1687134498824814598&selected=1687134498824814598) [start-worker](https://my.papertrailapp.com/groups/1141234/events?q=program%3Astart-worker&focus=1687134498824814598&selected=1687134498824814598) 2024/01/25 11:17:11 Killing process tree with parent PID 1638... (0xc000308b70)
Jan 25 11:17:12Z [translations-1-b-linux-v100-gpu-4-300g-zlyc9cmhtlqiaqxuzsym0q](https://my.papertrailapp.com/systems/translations-1-b-linux-v100-gpu-4-300g-zlyc9cmhtlqiaqxuzsym0q/events?focus=1687134498824814599&selected=1687134498824814599) [start-worker](https://my.papertrailapp.com/groups/1141234/events?q=program%3Astart-worker&focus=1687134498824814599&selected=1687134498824814599) 2024/01/25 11:17:11 Process tree with parent PID 1638 killed.

But the run of the task still ends up failing with `CLAIM_EXPIRED`, and no artifacts have been uploaded.

My understanding was that we should be uploading any artifacts that exist already, and failing with `WORKER_SHUTDOWN` - although it's possible that my expectations are wrong here.

This is with generic-worker & worker-runner 59.1.3.

**Comment by bhearsum** [comment]
(Related issue in another project: https://github.com/mozilla/firefox-translations-training/issues/400)

**Comment by petemoore** [comment]
It looks from the logs like maybe worker runner sends the message to generic worker, generic worker starts the process abortion, and while it is killing the task command processes, worker manager sends another request to terminate to generic worker. Generic worker holds a mutex when updating task state - it wouldn't surprise me if we are ending up with some kind of deadlock here, due to receiving multiple termination requests from worker runner. This is just a working hypothesis. I can see however, that the requests are reaching generic-worker, and it is calling the Abort function, but it looks like it isn't successfully updating the status.
Perhaps the fix here is for worker runner not to resend the termination request if it successfully sends it, or for Generic Worker to ignore future abort requests, once it has received one. This is assuming the hypothesis is correct, of course. It should be possible to create a unit test that exercises this behaviour to see if this is what is really happening. Thanks for grabbing the task log! How did you do that? Was it just luck that you were tailing it at the time?

**Comment by petemoore** [comment]
Note, the hypothesis is based on seeing two log lines with:
```
Got graceful-termination request with finish-tasks=false
```

**Comment by bhearsum** [comment]
Another interesting thing from logs is this case, where we're polling every 30 seconds, and then 8 seconds after a poll the system starts shutting down:
```
 Jan 30 10:32:00Z translations-1-b-linux-v100-gpu-4-1tb-fqyy7djjszsfazxznsdfna-1 start-worker 2024/01/30 10:32:00 polling for termination-time
Jan 30 10:32:30Z translations-1-b-linux-v100-gpu-4-1tb-fqyy7djjszsfazxznsdfna-1 start-worker 2024/01/30 10:32:30 polling for termination-time
Jan 30 10:33:00Z translations-1-b-linux-v100-gpu-4-1tb-fqyy7djjszsfazxznsdfna-1 start-worker 2024/01/30 10:33:00 polling for termination-time
Jan 30 10:33:08Z translations-1-b-linux-v100-gpu-4-1tb-fqyy7djjszsfazxznsdfna-1 systemd-logind Power key pressed.
Jan 30 10:33:08Z translations-1-b-linux-v100-gpu-4-1tb-fqyy7djjszsfazxznsdfna-1 systemd-logind Powering Off...
Jan 30 10:33:09Z translations-1-b-linux-v100-gpu-4-1tb-fqyy7djjszsfazxznsdfna-1 systemd-logind System is powering down.
```

That seems to suggest that GCP didn't actually publish the pre-emption notice, or that worker-runner isn't finding it correctly.

The [GCP docs on spot termination](https://cloud.google.com/compute/docs/instances/spot#preemption-process) don't mention anything about using the metadata service either - they talk about "ACPI G2 Soft Off" as the mechanism for signaling a preemption.

**Comment by bhearsum** [comment]
> It looks from the logs like maybe worker runner sends the message to generic worker, generic worker starts the process abortion, and while it is killing the task command processes, worker manager sends another request to terminate to generic worker. Generic worker holds a mutex when updating task state - it wouldn't surprise me if we are ending up with some kind of deadlock here, due to receiving multiple termination requests from worker runner. This is just a working hypothesis. I can see however, that the requests are reaching generic-worker, and it is calling the Abort function, but it looks like it isn't successfully updating the status. Perhaps the fix here is for worker runner not to resend the termination request if it successfully sends it, or for Generic Worker to ignore future abort requests, once it has received one. This is assuming the hypothesis is correct, of course. It should be possible to create a unit test that exercises this behaviour to see if this is what is really happening. Thanks for grabbing the task log! How did you do that? Was it just luck that you were tailing it at the time?

The logs pasted are from papertrail & the GCP Log Explorer

**Comment by matt-boris** [comment]
> The [GCP docs on spot termination](https://cloud.google.com/compute/docs/instances/spot#preemption-process) don't mention anything about using the metadata service either - they talk about "ACPI G2 Soft Off" as the mechanism for signaling a preemption.

I think you're onto something here @bhearsum... This metadata API looks almost like a response to say if the VM has already been shutdown by preemption.

**Comment by bhearsum** [comment]
https://stackoverflow.com/a/57862925 seems to cover a lot of the fine details.

**Comment by bhearsum** [comment]
It seems like reacting to the ACPI event properly would be sensible regardless of what the metadata service does - we will almost certainly notice the preemption through that before the metadata service - and reacting to that gives us the maximum amount of time to upload artifacts and shut down correctly.

**Comment by ahal** [comment]
> and reacting to that gives us the maximum amount of time to upload artifacts and shut down correctly.

Maybe? The stackoverflow post does warn that depending on the system, the shutdown script could be ran relatively late in the OS shutdown process.

That post also mentions a long lived http request to the metadata service as a possible option. If we're already polling that every 30s, maybe switching that logic to a persistent connection would be easier to implement.

**Comment by matt-boris** [comment]
> maybe switching that logic to a persistent connection would be easier to implement

I think we should first try this to see if we could get a quick-win. What do you guys think?

**Comment by bhearsum** [comment]
I did a quick test on a VM with both a shutdown script and an init script. Here's the relevant journald output:
> Jan 30 16:52:52 example-instance systemd[1]: Stopping bhearsum shutdown test...
> Jan 30 16:52:52 example-instance sh[955]: bhearsum test shutdown
> Jan 30 16:52:52 example-instance google_metadata_script_runner[954]: Found shutdown-script in metadata.
> Jan 30 16:52:52 example-instance google_metadata_script_runner[954]: shutdown-script: Shutting down!  Seeing if [PROGRAM_NAME] is running.

The systemd unit used was:
```
[Unit]
Description=bhearsum shutdown test

[Service]
Type=oneshot
RemainAfterExit=true
ExecStop=/bin/sh -c "echo bhearsum test shutdown"

[Install]
WantedBy=multi-user.target
```

**Comment by bhearsum** [comment]
> > maybe switching that logic to a persistent connection would be easier to implement
> 
> I think we should first try this to see if we could get a quick-win. What do you guys think?

I think it's worth a try; I would prefer to give it a shot in a dev VM and compare it to the shutdown script / init script before we actually go through the process of rolling out new images, though.

**Comment by matt-boris** [comment]
> I did a quick test on a VM with both a shutdown script and an init script.

Did you just use the shutdown script google provides in the docs?

**Comment by bhearsum** [comment]
> > I did a quick test on a VM with both a shutdown script and an init script.
> 
> Did you just use the shutdown script google provides in the docs?

Yeah, literally with the placeholders still in there. The only purpose was to see when it gets executed vs. a systemd unit.

**Comment by matt-boris** [comment]
Building a new image for https://community-tc.services.mozilla.com/worker-manager/proj-taskcluster%2Fgw-ubuntu-staging-google off of this commit https://github.com/taskcluster/taskcluster/pull/6806/commits/9da34e3fcd702ec89bc4bdda3a314efdb189d110.

**Comment by matt-boris** [comment]
The hanging GET request on the metadata service API does not return back before the instance is preempted. We should discuss steps forward in this week's community meeting.

**Comment by ahal** [comment]
Oh well, thanks for trying it out!

**Comment by matt-boris** [comment]
[Shutdown scripts](https://cloud.google.com/compute/docs/instances/create-use-spot#handle-preemption) are needed instead. These can be provided as part of worker manager config for a pool by adding the `metadata` block to the launch configs and creating a key `shutdown-script` (or [something different](https://cloud.google.com/compute/docs/shutdownscript#provide_a_shutdown_script_on_windows_instances) if you're on windows) with the value being a script to use in order to send `SIGTERM` (`kill -15 <PID>`) to the running `generic-worker` process.

I just opened up https://github.com/taskcluster/taskcluster/pull/6925 to have generic worker listen for `SIGTERM` signals to trigger a graceful termination off of.
