### ISSUE TITLE
Rename simple engine to make it apparent it should not be used in production environments

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#6832]
Simple engine really should not be used in production, since it is inherently insecure. The only real use case is for development setups and unit testing. Update the engine name to reflect this, as it is commonly thought to be suitable for production.

**Comment by djmitche** [comment]
Twisted Python used to have a class named InMemoryUsernamePasswordDatabaseDoNotUseUnderAnyCircumstances or something like that -- and it was used all over the place in demos and small apps.

If this engine is only useful for development and testing (of Taskcluster, right?), then maybe `testing-engine` is a good name.

It's also worth considering the cost of maintaining the engine, and the fidelity of the resulting tests. Would development be easier with this engine removed entirely?

**Comment by matt-boris** [comment]
➕ to `insecure` or `testing` engine
