### ISSUE TITLE
non-utf8 output in interactive tasks causes them to abort

### ISSUE THREAD

**Issue by bhearsum** [taskcluster/taskcluster#6848]
non-utf8 output to the shell in an interactivate task causes the session to be closed. For example, cat'ing /dev/urandom is a quick way to reproduce (but there are also ways this can happen that happen in real life scenarios).

On the worker, we see:
```2024/02/20 20:57:44 Error occured: websocket: close 1006 (abnormal closure): unexpected EOF```

Debugging with Chrome, I found: "Could not decode a text frame as UTF-8."

The first error we in websocktunnel code comes from [copyWsData's call to Gorilla's Conn.NextReader](https://github.com/taskcluster/taskcluster/blob/3d8b26bd128c5cf085d652cb0960899a33712966/tools/websocktunnel/wsproxy/wsproxy.go#L141). After some additional debugging, it looks like that error originates from [advanceFrame](https://github.com/gorilla/websocket/blob/695e9095ce8736ac99c83939ca6b0fe93768f680/conn.go#L819-L821), and based on our ultimate message it seems like that we're hitting [this path which returns an unexpectedEOF](https://github.com/gorilla/websocket/blob/695e9095ce8736ac99c83939ca6b0fe93768f680/conn.go#L370-L372).

It _seems_ unlikely to me that this is a bug in the websocktunnel or the Gorilla library that we're using. My guess is that something is happening in the interactive task UI that's causing some invalid (or possibly empty) data to be sent to the websocktunnel, which is what's making Gorilla unhappy. There's clearly a call to [TextEncode for every keystroke](https://github.com/taskcluster/taskcluster/blob/3d8b26bd128c5cf085d652cb0960899a33712966/ui/src/components/Shell/index.jsx#L113), although I haven't been able to confirm what is or is not happening there.

@Eijebong - I don't suppose you have any insight here? It looks like you touched it last :grimacing: 

(See https://github.com/mozilla/firefox-translations-training/issues/355 for some early investigation of this.)

**Comment by bhearsum** [comment]
Small correction from the earlier comment: the specific issue we're seeing is _decoding_ output, which makes it more likely to be linked to https://github.com/taskcluster/taskcluster/blob/3d8b26bd128c5cf085d652cb0960899a33712966/ui/src/components/Shell/index.jsx#L99-L104. (There might also be an issue with non-utf-8 input, but I haven't tested that.)

**Comment by lotas** [comment]
Great finding Ben!

**Comment by Eijebong** [comment]
Nice find indeed, thanks for the ping.
