### ISSUE TITLE
docker worker interactive tasks do not work properly curses applications

### ISSUE THREAD

**Issue by bhearsum** [taskcluster/taskcluster#6850]
From a user report:
> the output to the screen is garbled and input doesn't seem to work correctly or it's just confusing with the garbled text
> I'm seeing two odd things, tmux is now not working either.
> tmux says "open terminal failed: terminal does not support clear"
> And then when I load vim the old output is still on the screen.

![image](https://github.com/taskcluster/taskcluster/assets/49649/c467b9b3-3b6e-4048-872e-d5e813779bfd)

I gave this a try myself, and it looks to me like they're behaving similarly to when you use  `docker run` without `-t`. It's quite clear in the code that we are [requesting a tty](https://github.com/taskcluster/taskcluster/blob/3d8b26bd128c5cf085d652cb0960899a33712966/ui/src/components/Shell/index.jsx#L56-L81) though, and resizing works (which also requires a tty) - so this is probably a red herring.

@Eijebong - I'm not sure if know much about this one, but I'll flag you anyways on the off chance :)

**Comment by bhearsum** [comment]
You're a saint!

**Comment by Eijebong** [comment]
Well that was easy:

```
[eijebong@plutonium] /usr/share/terminfo  >>> fd hterm
h/hterm
h/hterm-256color
```

Plus now you get pretty colors:

![image](https://github.com/taskcluster/taskcluster/assets/3650385/52b3fd7b-d58a-4238-9709-83bbb2f75e7d)

**Comment by bhearsum** [comment]
For posterity, this was filed against docker-worker but fixed in generic-worker. Because docker-worker is desupported, my understanding is that we won't be fixing it there.
