### ISSUE TITLE
D2G: Xvfb issue with a docker-worker task

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#6880]
Working docker-worker task: https://firefox-ci-tc.services.mozilla.com/tasks/Ocx2P0iCSAeMrcRZrG4t-g/runs/0/logs/public/logs/live.log

Failing generic-worker task: https://firefox-ci-tc.services.mozilla.com/tasks/U5dS50DdRlqh7sOztqqjSQ/runs/0/logs/live/public/logs/live.log

**Comment by aerickson** [comment]
Latest thinking is that `--privileged` is needed in the payload (see https://community-tc.services.mozilla.com/docs/reference/workers/docker-worker/payload). We haven't been able to test this yet.

Tracking in https://mozilla-hub.atlassian.net/browse/RELOPS-865 also.

**Comment by aerickson** [comment]
Other issues mentioning `--privileged`:
- https://github.com/taskcluster/taskcluster/issues/6864
- https://github.com/taskcluster/taskcluster/issues/6888

**Comment by petemoore** [comment]
I believe this was fixed by #6891.
