### ISSUE TITLE
D2G: Running rr under generic worker and podman requires --privileged

### ISSUE THREAD

**Issue by pyoor** [taskcluster/taskcluster#6888]
**Describe the bug**
Under docker worker, running [bugmon-monitor tasks ](https://community-tc.services.mozilla.com/hooks/project-fuzzing/bugmon) which called [rr](https://github.com/rr-debugger/rr) would execute without issue.  After migrating to d2g and generic worker, these tasks began [failing](https://community-tc.services.mozilla.com/tasks/evzR-_XzS0mKjTDanC8G0g).  Adding `{ capabilities: { privileged: true } }` to the task allowed the execution of `rr`.

**To Reproduce**

1. Create a generic worker which executes the following command:
```podman run --rm -it docker.io/mozillasecurity/bugmon:latest rr```
2. The task will fail.

**Expected behavior**
The task should execute successfully.

**Comment by petemoore** [comment]
[This](https://community-tc.services.mozilla.com/tasks/evzR-_XzS0mKjTDanC8G0g/runs/0/logs/project/fuzzing/bugmon/live.log#L7) is interesting:

```
ERROR:bugmon.utils:Failed to upload pernosco session: rr is out of date. Please install `rr` master and make sure it's on your $PATH.
```

**Comment by matt-boris** [comment]
Fixed with https://github.com/taskcluster/taskcluster/issues/6890.
