### ISSUE TITLE
[Docs] schema is undefined

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#689]
From https://github.com/taskcluster/taskcluster/pull/651#issuecomment-488938780:

> Is the following expected?
> 
> ![Screen Shot 2019-05-02 at 3 36 36 PM](https://user-images.githubusercontent.com/3766511/57101866-2af28b00-6cf0-11e9-877e-2ef1ac8bad85.png)

I don't think this is expected.
I did some digging on this and found `references.json` file these two specific schema has below values

```
"allOf": [
        {
          "$ref": "./metaschema.json#"
        },
        {
          "$ref": "#/definitions/topLevelMetadata"
        }
      ],
```

and for this reference is going in and executing this code

`https://github.com/taskcluster/taskcluster/blob/master/ui/src/components/SchemaTable/index.jsx#L141-L162`

and its crashing at 

`https://github.com/taskcluster/taskcluster/blob/master/ui/src/components/SchemaTable/index.jsx#L152`

I am exactly sure, how to process this, `allOf` key.

**Comment by arshadkazmi42** [comment]
@helfi92 I can have a look at it.
I understand the bug, but not sure what is the expected fix for this?
Any inputs here?

**Comment by helfi92** [comment]
@djmitche Is this by any chance related to https://github.com/taskcluster/taskcluster/issues/657?

**Comment by djmitche** [comment]
I think it's the same, yes.

**Comment by helfi92** [comment]
I guess we can close this issue then. Thanks!
