### ISSUE TITLE
Github badge times out for non-existing branches

### ISSUE THREAD

**Issue by lotas** [taskcluster/taskcluster#6954]
Requests like `https://community-tc.services.mozilla.com/api/github/v1/repository/mozilla/readability/master/badge.svg` are failing with 502

In logs we can see:

```
GET /repos/mozilla/readability/commits/master/statuses - 404 
```

But instead of returning 404 or some generic badge, service times out

**Comment by thakkarujas5** [comment]
Hi, I would like to work on this issue.

**Comment by thakkarujas5** [comment]
Have tried out some stuff and mentioned it here:
[Issue-6954 Writeup](https://docs.google.com/document/d/1qAxpe3Xcck5B1Yx3o_nfOw3kV58IXcs0J0fnm_HILQ0/edit?usp=sharing)
Will it be possible for you to verify whether what I am doing is correct or need some course correction.

**Comment by lotas** [comment]
This is a great direction @thakkarujas5, I left few comments in that doc. Thanks

**Comment by thakkarujas5** [comment]
> This is a great direction @thakkarujas5, I left few comments in that doc. Thanks

Yes, had seen the comments, working on fixing it, will keep you posted.

**Comment by thakkarujas5** [comment]
Have updated the doc with my progress. Thank you!

**Comment by lotas** [comment]
Thanks @thakkarujas5 .. it gets complicated in there, as github client library is configured to do retries on 404.. so we end up in this "forever-loop" (which should only be 3 retries by derfault?) 
And since we check both statuses and checks apis, there are multiple requests being retried constantly

we should probably find a smarter way to check if branch exists? 

<img width="758" alt="image" src="https://github.com/taskcluster/taskcluster/assets/83861/cb52e39d-552e-4088-968a-fc8b5532f66a">

**Comment by thakkarujas5** [comment]
Have submitted the patch for this issue, let me know if any changes are required.
