### ISSUE TITLE
`findTasksAtIndex` is really slow, even for queries of a single index

### ISSUE THREAD

**Issue by Alphare** [taskcluster/taskcluster#6957]
**Describe the bug**

On the production Firefox TC, Querying `findTasksAtIndex` takes 20+ seconds to answer if it does at all before getting timed out, no matter how small the list of indexes provided (aside from the empty list).

**To Reproduce**

```
curl -X POST https://firefox-ci-tc.services.mozilla.com/api/index/v1/tasks/indexes -H 'Content-Type: application/json' -d '{"indexes": ["doesnotexist"]}'
```

**Expected behavior**

I expect this query to take (well) under a second, removing any network latency. I measured the network latency for other calls to be <100ms at the time of testing.

**Taskcluster version**

v64.1.0+

**Screenshots**

The current query and its analysis:

![image](https://github.com/taskcluster/taskcluster/assets/9445758/99af47be-ae93-4f7f-804c-c71b74b2ce4c)

A mockup of a better solution:

![image](https://github.com/taskcluster/taskcluster/assets/9445758/befd28d0-c0eb-45ee-a019-406329c048d5)

**Additional context**

We have figured out that the culprit is the SQL query doing a sequential read of the database and concatenating the namespace and name of each task before being able to answer, which takes a very long time.

Possible solutions include adding an index for this concatenation or - likely a much better solution - splitting the namespace from the name in the subquery to reduce this all to a hash join.

**Comment by lotas** [comment]
Looks like initial version of this function guaranteed the same order of results, despite input being random

Updated one returns tasks in the same order as the indexes in the request:

“[idxA, idxB, idxC]” -> [taskA, taskB, taskC]
“[idxC, idxB, idxA]” -> [taskC, taskB, taskA]

I don't think it is breaking anything and we can keep it this way

**Comment by Alphare** [comment]
> I don't think it is breaking anything and we can keep it this way

In fact, this was actually required in order to do anything useful with the output since we return arrays and not objects. Good fix, then. :)
