### ISSUE TITLE
multi g-w is inappropriate for containerized workloads

### ISSUE THREAD

**Issue by aerickson** [taskcluster/taskcluster#6975]
- For containerized workloads where the container is reset after each job, multi g-w creating a user per task is not necessary and adds significant overhead in time and complexity (see https://github.com/taskcluster/taskcluster/issues/6974).
  - Current examples of containerized workloads: Android Bitbar testing (uses simple g-w in a Docker container run on vendor's infra), Ubuntu 22.04 Wayland Virtualbox hosts, and the in-development Mac container virualization project.
- Also inappropriate temporarily because multi g-w currently requires GUI currently on Mac and Linux (see https://github.com/taskcluster/taskcluster/issues/6786).

**Comment by matt-boris** [comment]
We'll track the two points in their respective issues: #6974 and #6786 (also duplicated in https://github.com/taskcluster/taskcluster/issues/4595).

Going to close this, as I _think_ this would be solved with the above tickets being handled. Please reopen and explain if I misunderstood!

**Comment by aerickson** [comment]
I think even after the GUI requirement is removed, it doesn't make sense to be creating per-task users in a containerized environment (where the container is being deleted and recreated after each task).

I agree that if https://github.com/taskcluster/taskcluster/issues/6974 results in a multi g-w that can use a static user, this is done... so I guess we can close this.
