### ISSUE TITLE
[UI] In Hook's "last fired attempts", show task status, not hook-fire status

### ISSUE THREAD

**Issue by mitchhentges** [taskcluster/taskcluster#698]
My initial reaction to seeing the status column in "last fired attempts" is that it's the status of the hook's task, not the status of the intermediate "hook fire" action.

Perhaps this display could be made easier to understand and more useful by showing the triggered _task's_ status, rather than just the status of the hook fire itself?

**Comment by mitchhentges** [comment]
Looks like this is related to #636 :)

**Comment by helfi92** [comment]
There won't be a triggered task's status if the trigger itself fails so we would still need to show the hook fire status if we decide to a column for the task status.

Example:

![Screen Shot 2019-05-06 at 8 20 10 AM](https://user-images.githubusercontent.com/3766511/57224567-e90b6280-6fd7-11e9-85a0-87ebb426f6b2.png)

Adding the task status would require an extra request for every hook trigger returned by the endpoint. The endpoint is not paginated so if a hook has 1000 triggers, there will be 1000 additional requests.

**Comment by mitchhentges** [comment]
I think the page is limited to five "last fired attempts", IIRC.
I agree that if the hook fails, the "status" should still be "error"/"failed" (to me, I'd argue that the "task I trigger" failed if the hook fails to work).

**Comment by helfi92** [comment]
> I think the page is limited to five "last fired attempts", IIRC.

The UI limits it to 5 per page but the request still requests all of them. In other words, there are no network requests being done when a user clicks next or previous.

> I agree that if the hook fails, the "status" should still be "error"/"failed" (to me, I'd argue that the "task I trigger" failed if the hook fails to work).

If we do add a "Task Status" column, we could still keep "Fire Status".

> The endpoint is not paginated so if a hook has 1000 triggers, there will be 1000 additional requests.

Note that all of the additional requests will happen in the back end so it's not as bad as it sounds. We could give it a try and see :)

**Comment by mitchhentges** [comment]
Oh, I see, I didn't notice that it was paginated on the front-end (I hadn't found a need to jump to a build > 5 runs old yet).

> If we do add a "Task Status" column, we could still keep "Fire Status".

As a user, I'm not sure that this makes sense - the purpose of this column is to tell me at a glance if my build failed. _If_ it failed, I want to determine why. If it _didn't_, I want to see a success. Showing the states separately more-closely models the internals of taskcluster, but I'd argue that it adds unnecessary complexity and elements to the UI.

> Note that all of the additional requests will happen in the back end so it's not as bad as it sounds. We could give it a try and see :)

Yikes, yeah, I didn't originally realize that you _did_ fetch all the last fired attempts, I thought it was hard-limited to 5. Yeah, I'm :man_shrugging: that this still makes sense to do.

**Comment by helfi92** [comment]
Closing as `WONTFIX` for now. Happy to reconsider if this issue is flagged to me again. Thanks @mitchhentges for filing it :)
