### ISSUE TITLE
auto cancellation of github PR tasks does not work well if initial task fails

### ISSUE THREAD

**Issue by bhearsum** [taskcluster/taskcluster#6984]
Over in https://github.com/mozilla-releng/k8s-autoscale/pull/160 I'm iterating on adding Taskgraph to that repo. Some of my early attempts failed to run a decision task correctly. Each push I made after such an attempt ended up with an error like:
<details>

<summary>Uh oh! Looks like an error! Details</summary>

Taskcluster-GitHub attempted to cancel previously created task groups with following scopes:

```
assume:repo:github.com/mozilla-releng/k8s-autoscale:*, queue:seal-task-group:taskcluster-github/*, queue:cancel-task-group:taskcluster-github/*
```

No task-group with taskGroupId: `FKRVQdp5RcKNeGSYXeTNOw`

---

* method:     sealTaskGroup
* errorCode:  ResourceNotFound
* statusCode: 404
* time:       2024-04-23T19:57:23.585Z

</details>

...and indeed, the group doesn't exist because the decision task failed.

Presumably we should catch and ignore 404s in this case?

**Comment by lotas** [comment]
Good point! Thanks for raising this. 

Queue methods are returning 404 because task group didn't have a chance to be created yet, but github handler should detect this and silently ignore this 

sending a fix here: https://github.com/taskcluster/taskcluster/pull/6989

**Comment by bhearsum** [comment]
Thanks for the quick fix!
