### ISSUE TITLE
Image on https://taskcluster.net/ seems to be broken

### ISSUE THREAD

**Issue by rcurranmoz** [taskcluster/taskcluster#7033]
<img width="1124" alt="Screenshot 2024-05-22 at 12 36 24 PM" src="https://github.com/taskcluster/taskcluster/assets/139882866/653afc91-bdd4-4451-8044-45c15463f888">

See screenshot for examples in Safari and Firefox

**Comment by lotas** [comment]
oh indeed, thank you Ryan, I'll check
