### ISSUE TITLE
Add an Option to the Helm Chart to Disable Secret Creation

### ISSUE THREAD

**Issue by aaskat** [taskcluster/taskcluster#7035]
We are trying to deploy TC using ArgoCD (GitOps approach), and for fetching secrets, we are using the External Secret Operator (ESO). Currently, TC stores secrets as files, which does not work for our setup.

Could you consider adding an extra flag to the Helm chart to disable secret creation? This would allow us to use the secrets defined by ESO instead of the ones defined in the Helm charts.

This enhancement would simplify our deployment process and integrate seamlessly with our existing ESO-managed secrets.

**Comment by lotas** [comment]
Thanks!
This is something that can be done already by adding new flag in helm chart.

The only "technical issue" at the moment is that template generation is using [json-e](https://json-e.js.org/) for producing final templates, and final templates are being consumed by `helm template` which are golang templates.
So the end template in helm sense may not be a valid json/yaml. 

I need to check if it would be possible to wrap whole secrets resource into conditional block or we'll need some other way to isolate/remove those
