### ISSUE TITLE
Separate Sensitive Secret Values from Plain Configuration Values in Kubernetes Secrets

### ISSUE THREAD

**Issue by aaskat** [taskcluster/taskcluster#7036]
Currently, all configuration values are being placed in secrets instead of using ConfigMaps for plain configuration. This approach increases the number of secrets unnecessarily.

Could you make changes to separate the configuration values, reducing the number of secrets? I see that the secrets are generated by a JS script that reads the contents of service config.yaml files.

Separating the configuration into ConfigMaps where possible would make managing configuration data and secrets easier.

**Comment by lotas** [comment]
@aaskat feature is ready but not yet deployed (or fully tested)

Feel free to take `feat/7036-introduce-configmaps-k8s` branch for experiments already.
It contains both conditional resources #7035 and split between configmap and secret
