### ISSUE TITLE
generic-worker should set TASKCLUSTER_INSTANCE_TYPE

### ISSUE THREAD

**Issue by JohanLorenzo** [taskcluster/taskcluster#7070]
Found by @glandium in [bug 1903428](https://bugzilla.mozilla.org/show_bug.cgi?id=1903428#c0)

> However, TASKCLUSTER_INSTANCE_TYPE is [only set by docker worker](https://github.com/search?q=repo%3Ataskcluster%2Ftaskcluster%20TASKCLUSTER_INSTANCE_TYPE&type=code), not generic worker.

@petemoore, what would be the complexity to add a line like: 

https://github.com/taskcluster/taskcluster/blob/35b4e2d01200b90ddaaa87669a6ea177577ce499/workers/docker-worker/src/task.js#L364

to generic-worker? 

Having this environment variable will help with cost saving. We will be able to pinpoint what instance types are taking longer to clone hg.mozilla.org, for example.

**Comment by petemoore** [comment]
This was an undocumented feature of Docker Worker, which we weren't sure was being used. Since it is being used, I guess we can add it!

**Comment by petemoore** [comment]
UPDATE: i've just read the bugzilla bug, I see a bunch of code is using it, then let's just add it to Generic Worker. 👍
