### ISSUE TITLE
Version parameter output not consistent

### ISSUE THREAD

**Issue by jwmoss** [taskcluster/taskcluster#7073]
When running `--version` against livelog, generic-worker, start-worker, or taskcluster-proxy, the output is different. I would love to see  `--version` be updated to output a string with the semantic version. Examples below (on Windows):

Desired output

```
PS C:\Users\Jonathan.Moss\Downloads> .\livelog-windows-amd64.exe --version
65.2.0

PS C:\Users\Jonathan.Moss\Downloads> generic-worker-multiuser-windows-amd64.exe --version
65.2.0

PS C:\Users\Jonathan.Moss\Downloads> .\start-worker-windows-amd64.exe --version
65.2.0

PS C:\Users\Jonathan.Moss\Downloads> .\taskcluster-proxy-windows-amd64.exe --version
65.2.0

```

Current output

```
PS C:\Users\Jonathan.Moss\Downloads> .\livelog-windows-amd64.exe --version
2024/06/20 14:32:18 input server listening...

PS C:\Users\Jonathan.Moss\Downloads> generic-worker-multiuser-windows-amd64.exe --version
2024/06/20 18:27:29Z Making system call GetProfilesDirectoryW with args: [C000187520 C0002DEA10]
2024/06/20 18:27:29Z   Result: 1 0 The operation completed successfully.
generic-worker (multiuser engine) 65.2.0 [ revision: https://github.com/taskcluster/taskcluster/commits/f1da8f28dd7cf943c772a39b87039d7bc8118ac8 ]

PS C:\Users\Jonathan.Moss\Downloads> .\start-worker-windows-amd64.exe --version
start-worker 65.2.0

PS C:\Users\Jonathan.Moss\Downloads> .\taskcluster-proxy-windows-amd64.exe --version
Taskcluster proxy 65.2.0 (git revision f1da8f28dd7cf943c772a39b87039d7bc8118ac8)
```

**Comment by lotas** [comment]
I'm not sure if there are any standards for the version string, but I see other tools are also providing extended information with `--version`/`version` command arg. Some include sub-component versions, build info, etc

Maybe for the automation/integration purposes this could be a `--short-version` flag or something that would only return semantic version string and not more?

**Comment by petemoore** [comment]
> Looks like generic-worker still outputs other information before the short version
> 
> ```
> 2024/07/12 14:56:33Z Making system call GetProfilesDirectoryW with args: [C0000F5520 C0002B4A50]
> 2024/07/12 14:56:33Z   Result: 1 0 The operation completed successfully.
> 67.1.0
> ```

I think that is logged to standard error. The version is logged to standard out.

**Comment by petemoore** [comment]
> This is standard output. Code where I'm using this in our integration tests:
> 
> https://github.com/mozilla-platform-ops/worker-images/blob/main/tests/win/windows_worker_runner.tests.ps1#L38-L40

This looks like it should be standard error: https://github.com/taskcluster/taskcluster/blob/a401198287c6eb46f9d2b695fd0db02254bcf5d3/workers/generic-worker/win32/wrap_dll_windows.go#L33

Maybe standard out and standard error are getting merged somehow?

**Comment by lotas** [comment]
> > > Looks like generic-worker still outputs other information before the short version
> > > ```
> > > 2024/07/12 14:56:33Z Making system call GetProfilesDirectoryW with args: [C0000F5520 C0002B4A50]
> > > 2024/07/12 14:56:33Z   Result: 1 0 The operation completed successfully.
> > > 67.1.0
> > > ```
> > 
> > 
> > I think that is logged to standard error. The version is logged to standard out.
> 
> This is standard output. Code where I'm using this in our integration tests:
> 
> https://github.com/mozilla-platform-ops/worker-images/blob/main/tests/win/windows_worker_runner.tests.ps1#L38-L40

Can you please try this with `-RedirectStandardError $null` flag? Maybe it merges both streams by default?
