### ISSUE TITLE
Livelog failure

### ISSUE THREAD

**Issue by starhu521** [taskcluster/taskcluster#7078]
I met a problem "ERROR(s) encountered: signal: broken pipe", maybe cause of livelog failure "WARNING: Livelog failure: error 'exit status 1' and livelog output:", but i'm not sure. And I'm sure my port 38188 is free. The file is the log and I just hide private infos.
 
And I deploy many simple generic-workers on the same machine, and I open the livelog, the have different ports: expose base and base+1.

This my worker key log:
![image](https://github.com/taskcluster/taskcluster/assets/23275495/d062128c-b356-4d8c-8cbe-19cb1e4fcdc1)

This is my task log, it has the worker version info:
![image](https://github.com/taskcluster/taskcluster/assets/23275495/b827124d-06a9-4391-b66c-a55dd61e8ccd)

This is my worker config:
{
  "accessToken": "xxxx",
  "clientId": "xxxxx",
  "ed25519SigningKeyLocation": "xxxxx",
  "rootURL": "xxxx",
  "workerId": "xxxx",
  "provisionerId": "xxxxx",
  "workerType": "gw-simple-linux",
  "livelogExecutable": "/usr/local/bin/livelog",
  "taskclusterProxyExecutable": "/usr/local/bin/taskcluster-proxy",
  "publicIP": "xxxx",
  "disableReboots": true,
  "livelogPortBase": 38187,
  "livelogExposePort": 38186
}

**Comment by lotas** [comment]
Thanks for filing this. 
Do you think it would be possible to test the most recent version? [v65.2.0](https://github.com/taskcluster/taskcluster/releases/tag/v65.2.0)  (please note that `simple` got renamed to `insecure`)

There were few fixes since than [v57.0.0 .. v65.2.0](https://community-tc.services.mozilla.com/docs/changelog?from=v57.0.0&q=generic)

How do you deploy multiple workers on the same machine? How are those being isolated? Is there a separate container for each process? Are all ports exposed for those (maybe they shouldn't)

**Comment by starhu521** [comment]
> Thanks for filing this. Do you think it would be possible to test the most recent version? [v65.2.0](https://github.com/taskcluster/taskcluster/releases/tag/v65.2.0) (please note that `simple` got renamed to `insecure`)
> 
> There were few fixes since then [v57.0.0 .. v65.2.0](https://community-tc.services.mozilla.com/docs/changelog?from=v57.0.0&q=generic)
> 
> How do you deploy multiple workers on the same machine? How are those being isolated? Is there a separate container for each process? Are all ports exposed for those (maybe they shouldn't be)?

Just run with different config, and my task is simple, I run all my task d2g in docker.
And the problem is not always occur, the probability is relatively low. In the same worker, this issue will be automatically resolved, Sometimes it can be restored after one task, and sometimes it can be restored after several tasks.

**Comment by starhu521** [comment]
Maybe I found the reason. Because I run many workers on the machine. The worker will establish a connection input stream with the livelog through a random port. So the random port may collide with the startup port of my other livelog programs.
So if I want run multiple workers on the same one machine, I need fixed all ports.

**Comment by lotas** [comment]
Oh great that you find what causes an issue for you! And this was indeed, not the "standard" approach we used before, but we have some features in roadmap that could allow running multiple tasks with single worker.

**Comment by starhu521** [comment]
> Oh great that you find what causes an issue for you! And this was indeed, not the "standard" approach we used before, but we have some features in roadmap that could allow running multiple tasks with single worker.

Yes, this saves a lot of money on simple tasks. I’m looking forward to your new features.
