### ISSUE TITLE
tc-github shouldn't report an error if sealTaskGroup fails with 404

### ISSUE THREAD

**Issue by jcristau** [taskcluster/taskcluster#7080]
**Describe the bug**

If a github PR fails to create any tasks at some point (missing scopes, buggy .taskcluster.yml, ...), all subsequent pushes will call sealTaskGroup on the never-created group, and report a spurious error to the PR.
See e.g. https://github.com/mozilla-releng/tooltool/pull/1186 and https://github.com/mozilla-releng/tooltool/commit/2a802ebad508f68c23810956fc11b2778dbd77e5#commitcomment-143393335.

**Expected behavior**

tc-github should probably ignore 404s from sealTaskGroup, or not add the group to its db until it actually exists.

**Taskcluster version**

65.1.0

**Comment by lotas** [comment]
Oh, that's a lot of comments.. And they all seem to have same contents, which should have been ignored as duplicates.. I'll check. 
Thanks

**Comment by lotas** [comment]
Fix ready.. turns out I was using incorrect properties in api response, so it always failed
