### ISSUE TITLE
worker manager thought tasks were pending despite them being cancelled

### ISSUE THREAD

**Issue by bhearsum** [taskcluster/taskcluster#7089]
The worker pool showed:
![image](https://github.com/taskcluster/taskcluster/assets/49649/1dc254a3-3178-402a-a840-553f4749152c)

Pending tasks were specifically two runs of the same task (which....seems impossible?):
![image](https://github.com/taskcluster/taskcluster/assets/49649/8aaca988-1cd6-4331-b16e-f12ba7a44dc7)

Both runs were `CANCELED`:
![image](https://github.com/taskcluster/taskcluster/assets/49649/4960a307-c96d-41cc-b0f5-c88b84a2efcd)

This happened in a pool where workers were successfully spinning up, but never claiming tasks due to an issue with the image, if it matters.

**Comment by lotas** [comment]
Thanks! This is interesting.

Database also shows that there are two runs of the same task present in the table:

<img width="1525" alt="image" src="https://github.com/taskcluster/taskcluster/assets/83861/cb0ee36f-d333-4c26-bef8-8a41cd2069ac">

**Comment by lotas** [comment]
I also discovered some other tasks that were cancelled but still were visible in pending_tasks table

```
dhD3iHpSdiJzDjOMVumMw	
cCdHPWwDQ5WF_8WLSnXmBw	
KTQInwyqSXmHb-_lC5LdaQ	
bQOSa86IRNSOfYzY3EZWIA	
SKd4nM-HQKOP-JC32lnx1g	
eXh09vSwS0GMXsxRsQeWhg	
```

`translations-1/b-linux-large-gcp-1tb`

**Comment by lotas** [comment]
it looks like this was implemented this way.. when the task is cancelled we only remove it from the claimed queue .. but task can also be cancelled in the pending state, and that message was not removed ... ooops
