### ISSUE TITLE
[UI] Can't expand "Authorization" in side-menu

### ISSUE THREAD

**Issue by mitchhentges** [taskcluster/taskcluster#711]
**To reproduce:**
1. Go to [Taskcluster](https://taskcluster-web.netlify.com/)
2. Click to open the menu, then click "Authorization"
3. The button doesn't expand, but rather you're brought to a 404 page

**Comment by helfi92** [comment]
Resolved in https://github.com/taskcluster/taskcluster/commit/29f2ec4679b01a269f118c9f59f187167f036c48. Deployment is in progress :)
