### ISSUE TITLE
Github integration: github check linked to wrong task

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#7123]
In [this PR](https://github.com/web-platform-tests/wpt/pull/46967) the CI ran against [this commit](https://github.com/web-platform-tests/wpt/pull/46967/commits/797049f25a67f7225439353692ddec0673993e44). The [task](https://community-tc.services.mozilla.com/tasks/CNSTs4g9QceUndyxn0BRBg) failed.

Later, I copied the [Generic Worker payload](https://community-tc.services.mozilla.com/tasks/CNSTs4g9QceUndyxn0BRBg/runs/0/logs/public/logs/live.log#L43-103) that D2G had generated, from the task log, and modified it, to run under `docker` instead of `podman`, to see if it would fix the task. All the details remained the same, except an additional scope, a slight modification of the task payload, and updated timestamps (creation, expiry, deadline). The new task kept the same taskGroupId, and thus appears in the [same taskgroup](https://community-tc.services.mozilla.com/tasks/groups/CNSTs4g9QceUndyxn0BRBg). The new task was https://community-tc.services.mozilla.com/tasks/Vv9PGqkdSTKzAdnEG_7blQ and resolved as exception.

However, in the original PR (linked above), the CI check associated with the initial commit, that used to link to the original task https://community-tc.services.mozilla.com/tasks/CNSTs4g9QceUndyxn0BRBg, now links to the new task https://community-tc.services.mozilla.com/tasks/Vv9PGqkdSTKzAdnEG_7blQ.

I expected the github check to be associated to the original task that ran for the original commit, not the new task that I created later.

**Comment by djmitche** [comment]
I think this is expected: the check status is associated with the last task to complete with the relevant route. This allows reruns/retries to update status results.

**Comment by petemoore** [comment]
Thanks Dustin! That makes sense. 👍
