### ISSUE TITLE
worker-manager vs quota errors

### ISSUE THREAD

**Issue by jcristau** [taskcluster/taskcluster#7129]
When an operation fails due to having run out of quota for a resource, w-m will typically retry it again and again and again, each time sending error email.  Is there a way to be smarter here and e.g. back off for a while?  Or not send email for each and every error?

**Comment by lotas** [comment]
I think until RFC191 is implemented, `notify.email` could check if the content is the same and not send the same email twice https://github.com/taskcluster/taskcluster/blob/v67.0.0/services/notify/src/notifier.js#L64 

But there's probably some detail that is different each time in the error which makes it non-unique.

We can probably patch https://github.com/taskcluster/taskcluster/blob/v67.0.0/services/worker-manager/src/providers/provider.js#L235-L241 to detect if it is a duplicate inside a worker manager
