### ISSUE TITLE
Large delay between task ending and pulse message or between pulse message and hook triggering

### ISSUE THREAD

**Issue by marco-c** [taskcluster/taskcluster#7143]
We have a hook, "project-relman/code-review-production", which is triggered on a pulse message (https://hg.mozilla.org/ci/ci-configuration/file/dd4251fea5f5195b48196f589287704c20907b2d/hooks.yml#l168).

"code-review-issues" is the task from mozilla-central that triggers the pulse message.

Often, there is a large delay between the ending of the code-review-issues task and the triggering of the hook.

For example, https://firefox-ci-tc.services.mozilla.com/tasks/LjSkgKN_R6uIuQRYxo8-JA finished at 2024-07-10T12:45:11.104Z, while https://firefox-ci-tc.services.mozilla.com/tasks/PoC_ztIRRFy2yRhfOiSTZA started at 2024-07-10T13:49:27.023Z.

**Comment by marco-c** [comment]
Linked to https://bugzilla.mozilla.org/show_bug.cgi?id=1907116.

**Comment by lotas** [comment]
There seems to be no delay in Pulse messages, as [PoC_ztIRRFy2yRhfOiSTZA](https://firefox-ci-tc.services.mozilla.com/tasks/PoC_ztIRRFy2yRhfOiSTZA) was created at `2024-07-10T12:45:11.138Z` which is when [LjSkgKN_R6uIuQRYxo8-JA](https://firefox-ci-tc.services.mozilla.com/tasks/LjSkgKN_R6uIuQRYxo8-JA)  was resolved `2024-07-10T12:45:11.104Z`

So I think we need to watch inside the [code-review/bot-gcp](https://firefox-ci-tc.services.mozilla.com/provisioners/code-review/worker-types/bot-gcp?sortBy=Last%20Active&sortDirection=desc) worker pool to see if those workers are not being created on time or there are too many jobs for them

Checking worker-manager logs I can see that it's the case indeed. Worker pool's max capacity is `10`, while there are moments in time where that queue has large number of pending tasks (saw `50` and `150`) 
here's when number of pending tasks was `> 10`
<img width="1497" alt="image" src="https://github.com/taskcluster/taskcluster/assets/83861/35f9fc00-15ea-4546-a172-1ed150c4050e">

My suggestion is that `maxCapacity` should be increased on that pool.

Are those tasks checking the same thing (latest state of code) or just small parts? Maybe it is reasonable to cancel/stop previous runs (if it applies)

**Comment by marco-c** [comment]
Thanks for the investigation! The tasks are analyzing Phabricator diffs, so we can't stop previous runs (each run corresponds to a different Phabricator diff). I'll increase the max capacity.

**Comment by marco-c** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1907315 and opened https://phabricator.services.mozilla.com/D216284.

I'm wondering if we can build some kind of alerting system to notify when such situations happen (worker pool that is often at max capacity and thus delaying tasks).

**Comment by lotas** [comment]
this is indeed an interesting metric that we should take care of. 
With the upcoming health-checking related improvements for the worker-manager, I think we can definitely think about including this.

It can either be an email alert to the worker-pool owner, or at least more data shown in the UI - number of pending tasks in the queue, average wait time, etc

**Comment by petemoore** [comment]
This is a cool idea indeed. Alerts could even include a recommended MaxCapacity setting.
