### ISSUE TITLE
Pending tasks not pending

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#7145]
https://community-tc.services.mozilla.com/provisioners/proj-relman/worker-types/generic-worker-ubuntu-22-04/pending-tasks shows 5 pending tasks. If you click on one of them, you will see they have been resolved.

If you go to https://community-tc.services.mozilla.com/worker-manager the correct pending count is displayed (0) so the issue seems only to be with the pending tasks page, and not the pending count totals in the worker pools page.

**Comment by lotas** [comment]
I checked the estimator logs, it showed indeed those 5 pending tasks were influencing the desired capacity one, so could have potentially started workers

**Comment by lotas** [comment]
This is likely related to the recent issue with cancelled tasks - https://github.com/taskcluster/taskcluster/issues/7089

**Comment by lotas** [comment]
ok, I don't think we should fix here anything, it is working as expected. 

When task is being scheduled, it is placed into "pending queue" with the `expires` set to the tasks deadline. 
All functions that fetch tasks form pending queues or check total count also check that `expires> now()`, so the provisioning part should not be affected. 
However, `expire-tasks` cron only runs once a day, so those already expired tasks may be still visible in that view even after they were technically expired. 

The only thing to fix here is the the `listPendingTasks` endpoint that doesn't check that expiry field and returns them regardless
