### ISSUE TITLE
test an increase to the maximum number of dependencies a task can have

### ISSUE THREAD

**Issue by bhearsum** [taskcluster/taskcluster#7151]
In the community meeting today we discussed at length whether or not the current maximum number of dependencies a task can have (100) is still sensible. The quick background is that having no limit caused stability issues in the past (see https://bugzilla.mozilla.org/show_bug.cgi?id=1316593#c1). That comment was written 8 years ago though, and it's not clear that it's all necessarily still true.

We've been able to workaround the limit very trivially in the past, but we have more recent use cases that are causing us to spend time and money copying artifacts through intermediate tasks to work around the limit. If we can remove or raise the limit it would avoid this, and remove complexity from a number of graphs.

In the meeting we agreed that we would do some testing to see how high the limit can go before it causes issues.

**Comment by lotas** [comment]
Ok, so I was able to run some tests. 
Turns out that major bottleneck is database, or the way we work with it. 

Dependency resolver job seemed to be doing just fine with any number of dependency, but `queue.createTask` execution time is growing with the number of dependencies. This is because each dependent task is being inserted in one table and then full task is fetched from a different table. And it was one by one. 
Adding batch db insert and fetch reduced that time to a bearable constant value! No longer growing exponentially. 

I've tested it with 5k and 10k dependencies, yes it takes a bit longer to process (~250ms on my dev machine) but not ~20s in the unoptimized query. 

@bhearsum what do you think that limit should be on your side?

**Comment by bhearsum** [comment]
If we're talking ideal, I'd say no limit :stuck_out_tongue:. But more seriously, 5000 would almost certainly get rid of all of our current usage of dummy tasks, which is my primary concern.

**Comment by lotas** [comment]
I guess there wouldn't be much of those tasks that require 5k dependencies? (within single task group) 

We can deploy this change to dev instance for example, and give it a better stress test there

**Comment by bhearsum** [comment]
> I guess there wouldn't be much of those tasks that require 5k dependencies? (within single task group)
> 
> We can deploy this change to dev instance for example, and give it a better stress test there

I'm not certain we would have any that go up quite that high, to be honest. I think tasks like [this one](https://firefox-ci-tc.services.mozilla.com/tasks/CE8fkTKWQFC9XfncKo8H3A) would end up with the most dependencies with the limit raised. It depends on 23 dummy tasks, which would mean it could end up with ~2300 direct dependencies.

**Comment by bhearsum** [comment]
Maybe also of note - if we end up raising this limit, we can test the impact of this by running some stuff on Try first. (Obviously this would still impact the production cluster, but it would be different than the 2x/day Nightly graphs having multiple tasks with 1000s of dependencies.)

**Comment by lotas** [comment]
Added a draft PR, will check broken tests tomorrow. 

With 10k dependencies `createTask` call takes <2s on my machine.. which is probably a lot still. 
Biggest part of it is being spent in fetching all tasks from db to determine if they are resolved https://github.com/taskcluster/taskcluster/pull/7158/files#diff-802856c3be274dbf1a20ac531d3092485444c29d18f76b319965040bdfeebc64R51 

This can probably be simplified into two separate queries (but missing indexes on few fields might still make them slow)
1. check expiration/deadline time 
2. check resolved tasks

**Comment by lotas** [comment]
Some other issues that appear after this change - task UI page is very slow because web-server is trying to attach all of those dependencies statuses by making separate calls
