### ISSUE TITLE
Task creator: Interactive toggle does not update state on first click

### ISSUE THREAD

**Issue by worldomonation** [taskcluster/taskcluster#716]
<img width="681" alt="Screen Shot 2019-05-08 at 16 31 35" src="https://user-images.githubusercontent.com/6549265/57414966-29710900-71af-11e9-8972-1adcf87a5885.png">

**Describe the bug**
Taskcluster UI does not refresh to reflect the updated state of interactive task creator form.

**To Reproduce**
1. Navigate to https://taskcluster-web.netlify.com/tasks/create/interactive
2. Click on the 'Interactive' toggle present on top left
3. See error

**Expected behavior**
Toggle value should move to reflect the updated state - in this case, ON.

**Actual behavior**
Interactive toggle does not move to ON state.
URL value updates to reflect that Interactive toggle has been toggled.

**Screenshots**
Attached.

**Platform (please complete the following information):**
- OS: macOS 10.13.6 (17G6030)
 - Browser: Firefox Nightly
 - Version:  68.0a1 (2019-05-06)

**Additional context**
If user clicks on 'Interactive' toggle a second time, the UI element shifts to represent ON state.

**Comment by helfi92** [comment]
Good catch. Created a pull-request to fix this :) Thanks for bringing this up!
