### ISSUE TITLE
linux runtime references chfn in a distro specific location

### ISSUE THREAD

**Issue by bhearsum** [taskcluster/taskcluster#7168]
https://github.com/taskcluster/taskcluster/pull/7154 added a dependency on this command, which is fine, but on Debian based systems it exists in `/usr/bin/chfn`, not `/usr/sbin/chfn`.

It's not immediately obvious to me what the right way to fix this is, so I'm filing instead of sending a PR :laughing:. I considered replacing it `which chfn`, but that seemed rather hacky.

cc @Eijebong

**Comment by Eijebong** [comment]
Oops, I assumed debian would be the annoying one here with putting half of the commands requiring root access in `/usr/sbin`. I think we can just switch it to `/usr/bin/chfn`, it exists on arch, debian and fedora
