### ISSUE TITLE
Add a `git` server backend for

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#7193]
@lauft pointed out that the sync model would map well to the Git model. We could build a server implementation wrapping Git, using a similar set of files to those in the cloud storage: a `latest` file, a bunch of version files, and a bunch of snapshot files.

The `latest` file would be contentious: changing in every commit. However, that's precisely enforcing the replica invariant. Those conflicts can occur both on `git pull` (when new versions arrive) and on `git push` (if `latest` has changed since `git pull`).

**Comment by djmitche** [comment]
Sorry, this is for task**champion**. I shouldn't make issues when I'm in a meeting.

**Comment by djmitche** [comment]
(https://github.com/GothenburgBitFactory/taskchampion/issues/441)

**Comment by Aga92-92** [comment]
C
