### ISSUE TITLE
Output schema validation error in artifact download

### ISSUE THREAD

**Issue by lotas** [taskcluster/taskcluster#7233]
Some example of the artifact that can not be returned:
 https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/DPT6AmPyTf-8s3Xvw_5Q3g/runs/1/artifacts/public%2Ftest_info%2Fvideo_mochitest-plain_09-04-2024_01%3A05%3A45%20PM.webm

```
"Output schema validation error: 
Schema Validation Failed!
Rejecting Schema: https://firefox-ci-tc.services.mozilla.com/schemas/queue/v1/get-artifact-response.json#
Errors:
  * data/url must match format "uri""
```

Artifact:
```
  {
    "task_id": "DPT6AmPyTf-8s3Xvw_5Q3g",
    "run_id": 1,
    "name": "public/test_info/video_mochitest-plain_09-04-2024_01:05:45 PM.webm",
    "storage_type": "s3",
    "content_type": "video/webm",
    "details": "{\"bucket\": \"firefoxcitc-public-artifacts\", \"prefix\": \"DPT6AmPyTf-8s3Xvw_5Q3g/1/public/test_info/video_mochitest-plain_09-04-2024_01:05:45 PM.webm\"}",
    "present": true,
    "expires": "2024-10-02 12:43:13.564+00"
  }
```

`createArtifact` was called with this uri: `/task/DPT6AmPyTf-8s3Xvw_5Q3g/runs/1/artifacts/public%2Ftest_info%2Fvideo_mochitest-plain_09-04-2024_01%3A05%3A45%20PM.webm`

Problem occurred on the docker-worker pool, it was not possible to confirm it on the generic-worker as files with spaces were uploaded with `+` signs

**Comment by lotas** [comment]
confirmed on docker-worker https://community-tc.services.mozilla.com/tasks/NLQVgjmZRN6TK1ADVopC_Q

**Comment by petemoore** [comment]
@jcristau suggested the following on matrix (thanks Julien!):

```
diff --git a/services/queue/src/bucket.js b/services/queue/src/bucket.js
index d21c3e792..8f025260f 100644
--- a/services/queue/src/bucket.js
+++ b/services/queue/src/bucket.js
@@ -104,17 +104,17 @@ Bucket.prototype.createGetUrl = async function(prefix, forceS3 = false) {
   if (this.bucketCDN && !forceS3) {
     return `${this.bucketCDN}/${prefix}`;
   }
   const command = new GetObjectCommand({
     Bucket: this.bucket,
     Key: prefix,
   });
   const { url } = await getEndpointFromInstructions(command.input, GetObjectCommand, this.s3.config);
-  url.pathname = path.join(url.pathname, prefix);
+  url.pathname = path.join(url.pathname, encodeURI(prefix));
   return url.href;
 };
 
 /**
  * Create a signed GET URL
  *
  * options:
  * {
```

We should also create a Queue test for this (or several tests) to check that weird characters like spaces in artifact names don't cause problems, if those characters are allowed.
