### ISSUE TITLE
Feature request: expose a GitHub URL endpoint to redirect to latest 

### ISSUE THREAD

**Issue by cvan** [taskcluster/taskcluster#724]
First off, thanks for Taskcluster. It's a fantastic tool. Would it be possible to add a URL that redirects to the latest **completed** Task from a GitHub repo using Taskcluster?

To give some context:

I work on the [Firefox Reality](https://github.com/mozillareality/firefoxreality) team. @bluemarvin did awesome work on integrating Taskcluster with our GitHub repo.

To test the latest on our master, our cross-discipline staff (L10n, QA, Designers, and Project Manager) uses this Taskcluster URL, https://github.taskcluster.net/v1/repository/MozillaReality/FirefoxReality/master/latest, to find the latest Taskcluster build Task and then if it's not **running** (which it usually is), folks get stuck and don't know how to find the URL for the previous Task to download the Artifacts.

Assuming the Task is **completed**, then this [documentation in our README](https://github.com/MozillaReality/FirefoxReality#advanced) works:

> 1. Load [this TaskCluster URL](https://github.taskcluster.net/v1/repository/MozillaReality/FirefoxReality/master/latest).
> 2. Click the `Firefox Reality for Android - Build - Master update →` link.
> 3. Click the `Run Artifacts` tab, and click to download the APK for your platform of choice.

Although cumbersome, this process involves several clicks which often confuses folks. And as mentioned above, usually the builds are still _**running**_ and not yet **completed**, so there's no obvious user-facing way (to my knowledge) to find the previously successful build for Firefox Reality.

So to allow users to download the APKs, I wrote a [simple service (hosted on Glitch)](https://fxr.glitch.me/) ([view source](https://glitch.com/edit/#!/fxr?path=server.js:1:0)) to request a few Taskcluster URLs to resolve the paths to the artifacts to find the correct APK for which we generate each platform/architecture. It's documented in Firefox Reality's [README](https://github.com/MozillaReality/FirefoxReality#download-developer-apks-debug-builds).

![](https://user-images.githubusercontent.com/203725/57356124-7d82db80-7124-11e9-9015-611640b8e860.png)

**Comment by djmitche** [comment]
The solution you've created -- custom dashboard with a little logic on the backend to find the latest -- is the preferred solution, since it means you can account for all of the particularities of your situation.  

However, we have some better support for linking directly to artifacts that you may not have found: [`index.findArtifactFromTask()`](https://docs.taskcluster.net/docs/reference/core/index/api#findArtifactFromTask).  This API method can take an index path and an artifact name, look up the latest task at that path, and then return a redirect to the named artifact.  You can find a bit more information [here](https://docs.taskcluster.net/docs/manual/using/artifacts).

Hopefully that is what you're looking for?

**Comment by cvan** [comment]
> However, we have some better support for linking directly to artifacts that you may not have found: [`index.findArtifactFromTask()`](https://docs.taskcluster.net/docs/reference/core/index/api#findArtifactFromTask). This API method can take an index path and an artifact name, look up the latest task at that path, and then return a redirect to the named artifact. You can find a bit more information [here](https://docs.taskcluster.net/docs/manual/using/artifacts).

This is helpful, thank you! I'll still need to stand up a service to do the API calls and redirects, but this info. can help me clean up the existing script. Feel free to close this issue, or if you feel others would benefit from having a similar service provided by Taskcluster's endpoints, feel free to keep it open. Thanks again!
