### ISSUE TITLE
Duplicate function in PulseMessages

### ISSUE THREAD

**Issue by arshadkazmi42** [taskcluster/taskcluster#729]
There is `handleInputChange` function defined twice in PulseMessages component

At these lines, [Line 143-145](https://github.com/taskcluster/taskcluster/blob/master/ui/src/views/PulseMessages/index.jsx#L143-L145) and [Line 168-179](https://github.com/taskcluster/taskcluster/blob/master/ui/src/views/PulseMessages/index.jsx#L168-L170)

**Comment by helfi92** [comment]
Good catch! Feel free to create a PR to remove on of them.
