### ISSUE TITLE
Log important worker config settings in task header

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#7305]
Some worker config settings fundamentally affect how tasks operated. Therefore it is useful to log these config settings in the task header, together with other information about the worker environment.

In particular, for multiuser enginer, this would be `runTasksAsCurrentUser` and `headlessTasks` config settings.

**Comment by matt-boris** [comment]
Maybe also think about anything extra to add in the `debugInfo` map as well https://github.com/taskcluster/taskcluster/blob/6967e681f93f02833d2040850778ae81d142fd7e/workers/generic-worker/main.go#L276-L290
