### ISSUE TITLE
[UI] Action buttons aren't doing anything

### ISSUE THREAD

**Issue by mitchhentges** [taskcluster/taskcluster#739]
**Describe the bug**
Clicking on a button such as "save" for a role isn't actually performing the intended action. The button "looks" clicked, but there's no network requests or errors in the console.

**To Reproduce**
1. Go to a hook, like [`fenix-nightly-staging`](https://taskcluster-web.netlify.com/auth/roles/hook-id%3Aproject-mobile%2Ffenix-nightly-staging)
2. Make a change (e.g.: to the description)
3. Click save

![test](https://user-images.githubusercontent.com/7784737/57704737-6b3ffa80-765a-11e9-9048-3cd686e9e78c.gif)
(don't mind the jittery gif, that's a screenrecording issue. The taskcluster UI problem is nonlocal, though :smile:)

**Comment by helfi92** [comment]
Seems to work for me both locally and in production. I'll send a PR to never use the cached version. That might help.

**Comment by djmitche** [comment]
Also, it *does* say "DO NOT EDIT" on that role :)

**Comment by helfi92** [comment]
This seems to be a known issue https://github.com/mui-org/material-ui/issues/13006.

**Comment by helfi92** [comment]
@mitchhentges Could you try to see if it works in https://deploy-preview-822--taskcluster-web.netlify.com/auth/roles/hook-id%3Aproject-mobile%2Ffenix-nightly-staging. I tried something a bit differently. If that doesn't work, I will request a machine where I can replicate this issue. Let's get this fixed!

**Comment by mitchhentges** [comment]
Interestingly, testing now, all of these work:
* `deploy-preview-822--taskcluster-web.netlify.com`
* `taskcluster-ui.herokuapp.com`
* `taskcluster-web.netlify.com`

I updated my machine from Ubuntu 18.04 to 19.04, perhaps the "touch" system changed?

**Comment by helfi92** [comment]
w00t! Really happy to hear that. Closing as WONTFIX.
