### ISSUE TITLE
New UI: The list of artifacts is confusing.

### ISSUE THREAD

**Issue by tomprince** [taskcluster/taskcluster#763]
**Describe the bug**
Looking at https://taskcluster-web.netlify.com/tasks/FsZs1H_ISa6xJQ6hmOr2rQ
- the buttons to scroll forward/back in the list are not obvious, so it isn't clear that there are more artifacts than are displayed
- scrolling forwards to the end, and then backwards gives inconsistent results: the first back press appears to make the UI think that it is on the first page of artifacts while displaying the second page, then after some time the automatic refresh switches it to the first page.

**Platform (please complete the following information):**
Firefox 66.05

**Comment by helfi92** [comment]
> the buttons to scroll forward/back in the list are not obvious, so it isn't clear that there are more artifacts than are displayed

I can see how this is possible. We can fix this by grouping the artifacts in a card so that it has a slightly different background.

> scrolling forwards to the end, and then backwards gives inconsistent results: the first back press appears to make the UI think that it is on the first page of artifacts while displaying the second page, then after some time the automatic refresh switches it to the first page.

Good catch. This is a bug.

**Comment by tomprince** [comment]
It also looks like the logs are being displayed as artifacts, or as the normal link, for the task I linked.

**Comment by helfi92** [comment]
@tomprince https://taskcluster-ui.herokuapp.com/tasks/FsZs1H_ISa6xJQ6hmOr2rQ. Better?

> It also looks like the logs are being displayed as artifacts, or as the normal link, for the task I linked.

I'm not sure I understand the issue. Could you help me understand, please.

_Note: We are moving away from Netlify. You can use https://taskcluster-ui.herokuapp.com instead._

**Comment by helfi92** [comment]
Closing for now but feel free to re-open if there are still issues.
