### ISSUE TITLE
[UI] Staying signed in

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#767]
From https://github.com/taskcluster/taskcluster/issues/750#issuecomment-494536404:

> Staying Signed In..

> Looking at ui/src/auth/AuthController.js, it seems to delete the user (including access_token) if the credentials (the TC clientId, etc., valid only for 15m) are expired when loadUser is called, which occurs at page load when the App component is mounted. I would expect this to result in a user being signed out when visiting the site after more than 15 minutes with no tabs open.

> That said, I can't reproduce this -- so I suspect this is something you've gotten right and I'm just not connecting the dots. Otherwise, this is good for followup, but probably high-priority as people will complain about being logged out when there are no TC tabs open.

**Comment by djmitche** [comment]
I'm even still logged in (via Github) this morning, so I'm leaning even more strongly toward "@djmitche is missing something".

**Comment by helfi92** [comment]
Resolved in https://github.com/taskcluster/taskcluster/commit/4999a958971eced7b77ecf832d9a7aa872edc6dd.
