### ISSUE TITLE
[UI] Rewrite top level classes as a regular functions

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#773]
Problem: Writing a hook inside a class [does not work in React](https://reactjs.org/docs/hooks-faq.html#should-i-use-hooks-classes-or-a-mix-of-both)
Solution: Rewrite the top level classes as regular functions so that users can start using hooks inside their views.

We would need to convert the following to regular functions
* src/App/Main.jsx
* src/App/index.jsx

Note:
* The `componentDidCatch` method can be handled via [react-error-boundary](https://github.com/bvaughn/react-error-boundary)

**Comment by subhdcode20** [comment]
I would love to work on this. I have recently started working with hooks.
Please guide me with the local environment setup?

**Comment by helfi92** [comment]
Welcome @subhdcode20. See the [README](https://github.com/taskcluster/taskcluster/blob/master/ui/README.md) for how to get the UI running. Let me know if you had questions.

**Comment by subhdcode20** [comment]
Hi @helfi92 , i was able to run the local environment. As expected, i am getting the Home view with a sign in option. 
We only need to convert the mentioned top level classes in the src/App/ directory to hooks and the rest will stay the same right?
Any pointers before i start working on this?

**Comment by helfi92** [comment]
> i was able to run the local environment

Good to hear!

> We only need to convert the mentioned top level classes in the src/App/ directory to hooks and the rest will stay the same right?

Right. I would probably start with the `Main.jsx` method since it looks to be less complicated. The goal of all of this is so that we can start using hooks in our views (`src/views`). I guess you'll know when it works when you're able to use something like `useState` inside something like `ui/src/views/CachePurges/ViewCachePurges/index.jsx` which can be accessed via http://localhost:5080/purge-caches. Hope that helps.

**Comment by subhdcode20** [comment]
Thanks, i will start working on a new branch soon. 
If i run into any issues will give you a mention here.

**Comment by subhdcode20** [comment]
Hey @helfi92 , i changed both mentioned components using hooks. A few points to discuss:
- i had to update `neutrinorc.js` for using `@hot-loader/react-dom` to enable hot reloading for hooks as mentioned in [docs](https://github.com/gaearon/react-hot-loader#react--dom).
- i tried using hooks in `ui/src/views/CachePurges/ViewCachePurges/index.jsx` as you suggested by replacing it with a basic hooks component and its working this way.
- the linting some times keeps giving old error which were already resolved which i am guessing is caching thing. Also a few other linting errors probably related to hoisting.

A review of the changes would be great. Should i push all the changes to a separate branch on the git repo so you can check it out?

**Comment by helfi92** [comment]
Hey! Yeah, push all the changes so I can take a look :) Thanks!

**Comment by subhdcode20** [comment]
I am getting this error on pushing to my new branch `subham-fix-773` :

`remote: Permission to taskcluster/taskcluster.git denied to subhdcode20.
fatal: unable to access 'https://github.com/taskcluster/taskcluster.git/': The requested URL returned error: 403`

**Comment by helfi92** [comment]
You'll want to create a fork of this project and push to your fork. Once you push to your fork, navigating to the UI will give you an option to create a PR from out of your fork.

![Screen Shot 2019-06-03 at 9 22 47 AM](https://user-images.githubusercontent.com/3766511/58805005-2c5dee80-85e1-11e9-8623-40e0df524dd8.png)

**Comment by subhdcode20** [comment]
Thanks. Created a pull request (#834) from my fork.

**Comment by subhdcode20** [comment]
Also, now i am getting this error `Module not found: Error: Can't resolve 'react-dom'` when i install `react-error-boundary` which seems like and issue with the webpack alias for `@hot-loader/react-dom` .
Not sure how to get around this and `react-error-boundary` also doesn't show in `package.json` when i install it! Any ideas?

**Comment by Rolikasi** [comment]
Hi, @subhdcode20.

**Comment by helfi92** [comment]
This is no longer needed. We started using hooks so we are OK to close this.
