### ISSUE TITLE
[UI] When viewing task, update page title with task name

### ISSUE THREAD

**Issue by mitchhentges** [taskcluster/taskcluster#795]
When I have multiple tasks open in separate tabs, it would be awesome if I could distinguish them by the tab title.

Note: some sites identify their pages/tabs by prefixing the title with their product name ("Taskcluster"). However, since we already have a recognizable icon, we might be able to use all available "title" space for the task name itself, which woudl be awesome

**Comment by helfi92** [comment]
Good idea.
