### ISSUE TITLE
[UI] Add a way to jump to a task ID/task group from the log viewer in less clicks

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#818]
Relates to https://github.com/taskcluster/taskcluster/issues/274#issue-412021119.

**Comment by ss77995ss** [comment]
I think it has already had a button to redirect to task ID/task group in the bottom right of the Log page. (Go to page like `http://localhost:5080/tasks/NlNDq14dSw-9GR9JBeIfrg/runs/0` directly) But maybe it is not clear enough for the users to notice the button.
<img width="1263" alt="Screen Shot 2019-07-19 at 21 20 11" src="https://user-images.githubusercontent.com/28031139/61538013-1742ff00-aa6b-11e9-9000-15c779c2afbe.png">

Maybe we can use buttons with text and icon would help?
<img width="150" alt="Screen Shot 2019-07-19 at 21 23 00" src="https://user-images.githubusercontent.com/28031139/61538342-c4b61280-aa6b-11e9-8251-a642a0b0dbd0.png">

**Comment by helfi92** [comment]
I think the user wants a way to jump to a different task ID than the one "View Task" button takes you to.

**Comment by ss77995ss** [comment]
OK, I see. Perhaps we can add a button to let the user enter the task or group ID and redirect to the target page?

**Comment by helfi92** [comment]
Good idea. I'm thinking of the following:

1. Use a SpeedDial component with the following buttons inside:
* Raw Log
* View Task
* View Different Task
2. Remove the current Raw Log button since it will be inside the speed dial
3. Clicking on "View Different Task" would open up a dialog asking to insert a task ID to view

**Comment by helfi92** [comment]
We use the SpeedDial component in many of our views. For example, https://taskcluster-ui.herokuapp.com/tasks/groups/dVkjPihESQeA8eugE2KJ4w.

**Comment by ss77995ss** [comment]
Cool, thanks for the information. Can I take this one up if nobody is working on it?

**Comment by helfi92** [comment]
Definitely. Go for it.

**Comment by ss77995ss** [comment]
Hi @helfi92 , I just created a PR for this issue and I leave some questions in it. Please kindly have a look when you have time, thanks!

**Comment by helfi92** [comment]
Many thanks @ss77995ss. I took a quick look and it looked really good :) I will review soon.

**Comment by helfi92** [comment]
Resolved in https://github.com/taskcluster/taskcluster/commit/e202a48c0183d8f4c9420ff7cb0a051e567b1d51.
