### ISSUE TITLE
Suggestions for improving UX of forms

### ISSUE THREAD

**Issue by owlishDeveloper** [taskcluster/taskcluster#825]
The conversation starts [here](https://github.com/taskcluster/taskcluster/pull/814#discussion_r289383883)

**Comment by helfi92** [comment]
If we wanted to implement the [last idea](https://github.com/taskcluster/taskcluster/pull/814#discussion_r289563602) of the discussion thread, the change would be really simple and would probably do the job. For each form that we have in the site, we would need to add the [`autoFocus`](https://material-ui.com/api/text-field/#props) property to the first `TextField` component. This will make the first input focused on page load.

**Comment by helfi92** [comment]
Forms that will require the change:
* [ ] [`ui/src/components/SecretForm/index.jsx`](https://github.com/taskcluster/taskcluster/blob/master/ui/src/components/SecretForm/index.jsx)
* [ ] [`ui/src/components/HookForm/index.jsx`](https://github.com/taskcluster/taskcluster/blob/master/ui/src/components/HookForm/index.jsx)
* [ ] [`ui/src/components/ClientForm/index.jsx`](https://github.com/taskcluster/taskcluster/blob/master/ui/src/components/ClientForm/index.jsx)
* [ ] [`ui/src/components/RoleForm/index.jsx`](https://github.com/taskcluster/taskcluster/blob/master/ui/src/components/RoleForm/index.jsx)
* [ ] [`ui/src/views/Quickstart/index.jsx`](https://github.com/taskcluster/taskcluster/blob/master/ui/src/views/Quickstart/index.jsx)

**Comment by steve-cahn** [comment]
Hey @helfi92 Hope I contributed correctly. Let me know if I did anything wrong, since this is my first time contributing to open source. Thanks!

**Comment by helfi92** [comment]
@steve-cahn I think there are two more forms we would need `autoFocus` then we should be able to consider this issue resolved :)
