### ISSUE TITLE
[UI] Improve layout of forms

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#835]
The UI of our forms tends to be quite compact. We should make it more "breathable" by adding more spaces between sections and perhaps using sub headers if it makes sense.

* [x] ui/src/components/SecretForm/index.jsx
* [x] ui/src/components/HookForm/index.jsx - https://github.com/taskcluster/taskcluster/pull/1410
* [x] ui/src/components/ClientForm/index.jsx
* [x] ui/src/components/RoleForm/index.jsx
* [x] ui/src/views/Quickstart/index.jsx - https://github.com/taskcluster/taskcluster/issues/1412
* [x] Worker pool form - https://github.com/taskcluster/taskcluster/pull/1470

**Comment by djmitche** [comment]
Just as a user datapoint, I feel the opposite -- I think the forms are really sparse and use a lot of screen-space per piece of information, making me scroll or zoom out to fit a useful amount of data onscreen. And I don't have a small screen :)

**Comment by helfi92** [comment]
Could you share a screenshot of a form that uses a lot of screen-space for you, please?

**Comment by djmitche** [comment]
![Screenshot_2019-06-04 Hook - Taskcluster](https://user-images.githubusercontent.com/28673/58886305-a8c00280-86b1-11e9-8b25-6b6c4f64f586.png)
![Screenshot_2019-06-04 Provisioners - Taskcluster](https://user-images.githubusercontent.com/28673/58886306-a8c00280-86b1-11e9-920f-b29211b85d3e.png)

There's a *lot* of background space there, especially horizontally, and labels, text-entry areas, and help text are all stacked vertically.

I don't mind it -- I've sort of resigned myself to Material Design taking over the web until someone popularizes a new gestalt -- but I don't think we should take steps to make it *more* sparse.

**Comment by djmitche** [comment]
BTW, this is not a criticism of tc-ui -- I think tc-ui is better-designed and easier to use than a lot of google sites that also employ MD.  It's a criticism of MD itself :)

**Comment by owlishDeveloper** [comment]
I wonder if we can make changes to make the forms both more breathable/organized _and_ compact (I also sometimes feel some forms could take less space) - for example, we could do double column layout on larger screens, adjust some components' sizes etc.

**Comment by djmitche** [comment]
That sounds wonderful :)

**Comment by chefoce** [comment]
Hi, I would like to contribute to this issue for outreachy project. Could you please assign it to me?

**Comment by djmitche** [comment]
Sure!  There is a bit of web design to do here, too, to think of a way to achieve both "breathable" and "compact" at the same time.  Try a few things, decide what you like best, and make a PR -- then @helfi92 and @owlishDeveloper can comment next week.

**Comment by chefoce** [comment]
Great!! i will start work in this right now, thanks

**Comment by chefoce** [comment]
Hi i tried to start working with [UI] Improve layout of forms #835, but i don’t have clear in what file should i do the improvement, could someone help me with that? thanks

**Comment by helfi92** [comment]
It turns out the two remaining forms are already assigned to other folks (see https://github.com/taskcluster/taskcluster/issues/835#issue-451984858). I filed https://github.com/taskcluster/taskcluster/issues/1539 and assigned it to you. Hope that's okay. Let me know if you had questions.
