### ISSUE TITLE
[UI] View Live log -> Follow automatically 

### ISSUE THREAD

**Issue by pocmo** [taskcluster/taskcluster#839]
In 99% of the cases where I need to read the log of a task, I need to read it from the bottom (to see the last error or copy some follow-up task ID). In the old UI when clicking on "Run logs" it had automatically "Follow log" enabled and jumped to the bottom of the log (or does it just remember what I used last? 🤷‍♂).

In the new UI I wonder if there could be a quick action next to "View Live Log" that also automatically enables follow and/or jumps to the bottom of the log immediately.

![Screenshot_2019-06-05 Android Components Module Lib Publicsuffixlist 0 56 0 Snapshot - Taskcluster](https://user-images.githubusercontent.com/89638/58952717-c2864600-8794-11e9-86da-55b8be1ea713.png)

**Comment by helfi92** [comment]
> In the old UI when clicking on "Run logs" it had automatically "Follow log" enabled and jumped to the bottom of the log (or does it just remember what I used last? 🤷‍♂).

It remembered what you used last.

I think we can probably just default to the bottom if most people start reading a log from the bottom.  It makes sense to me.

**Comment by ss77995ss** [comment]
Hi, can I take up this one? Thanks:)

**Comment by helfi92** [comment]
Go for it :)

**Comment by ss77995ss** [comment]
@helfi92 / I created a PR for this issue, please kindly have a look when you have time, thanks :)
