### ISSUE TITLE
[UI] Reposition log action buttons

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#840]
Log: http://localhost:5080/tasks/fRav6OG-Sbij116H7gfqag/runs/0/logs/https%3A%2F%2Fqueue.taskcluster.net%2Fv1%2Ftask%2FfRav6OG-Sbij116H7gfqag%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log

When viewing a log, let's position actions that interact directly with the log to be beside the search input.

**Actual:**

![Screen Shot 2019-06-05 at 10 19 07 AM](https://user-images.githubusercontent.com/3766511/58963553-66fb8e80-877b-11e9-9062-6d36bf01cb7a.png)

**Expected:**

![Screen Shot 2019-06-05 at 10 15 36 AM](https://user-images.githubusercontent.com/3766511/58963561-6b27ac00-877b-11e9-9962-cf7fff961fc7.png)

**Comment by helfi92** [comment]
In order to position the buttons beside the search input, we would probably need to do something like:

```jsx
<LazyLog ... />
<div className={classes.logActions}>
  <IconButton>
    <NumericIcon size={18} />
  </IconButton>
  <IconButton>
    <ArrowUpIcon size={18} />
  </IconButton>
  <IconButton>
    <ArrowDownIcon size={18} />
  </IconButton>
  <IconButton>
  // ...
</div>
```

```jsx
logActions: {
  position: 'absolute',
  top: 2,
  right: 340,
},
```

**Comment by arku** [comment]
@helfi92 Just submitted a [PR](https://github.com/taskcluster/taskcluster/pull/906) fixing this issue.

Take a look when you get a chance.

Btw, the 'Go to Line Number' does not work fine (or so I think). If I fill in 3025 in the dialog, it ends up on line 3096. Not sure what's going on there. Can you please check?

Thanks!

**Comment by helfi92** [comment]
> Btw, the 'Go to Line Number' does not work fine (or so I think). If I fill in 3025 in the dialog, it ends up on line 3096. Not sure what's going on there. Can you please check?

I just checked and was able to reproduce only when the follow button is first clicked. Otherwise, if it's not clicked, it works as expected. This is a bug. Thanks for catching it. I'll file an issue for it.

**Comment by helfi92** [comment]
Filed https://github.com/taskcluster/taskcluster/issues/908. Let me know if you wanted to tackle this issue as well :-)

**Comment by arku** [comment]
@helfi92 Perfect!

> Let me know if you wanted to tackle this issue as well :-)

Haha, for sure 🙂
