### ISSUE TITLE
[web-server] Refactor userIdFromIdentity

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#842]
https://github.com/taskcluster/taskcluster/pull/826#discussion_r290840581

**Comment by arku** [comment]
@helfi92 I would like to take a stab at this.

**Comment by arku** [comment]
@helfi92 I have submitted a [PR](https://github.com/taskcluster/taskcluster/pull/890) fixing this issue. Take a look when you get a chance.

Thanks!
