### ISSUE TITLE
Switch from implicit documenting of our code to explicit one

### ISSUE THREAD

**Issue by owlishDeveloper** [taskcluster/taskcluster#853]
Context: [here](https://github.com/taskcluster/taskcluster/pull/843#discussion_r291198728).

We would like to switch from implicit documenting of our code to explicit one, and add comments to spots in the code that we want to warn other developers about. For example, in that PR [I added warning comments to graphql code](https://github.com/taskcluster/taskcluster/pull/843/commits/fde2c4cbb23a06f4635a417874c0fe18094555ac)

**Comment by imbstack** [comment]
From what I've seen we have made this change! Marking as fixed.
