### ISSUE TITLE
Let's automate code style checking

### ISSUE THREAD

**Issue by owlishDeveloper** [taskcluster/taskcluster#854]
Currently, in lots of PRs to `web-server` and `web-ui` services we suggest stylistic changes that are important enough for us to suggest in a PR review. I propose we free up our cognitive resources for finding actual bugs, security vulnerabilities and the like, and automate the styling and naming checks by using project-specific linting rules.

**Comment by imbstack** [comment]
That's the big one that comes to mind but I really don't even mind that tbh. We could remove prettier from the ui or something? Either that or apply it to the rest of the code too.

**Comment by djmitche** [comment]
I think the issue here was that prettier was missing things that were being brought up in PRs.

**Comment by helfi92** [comment]
Another one that comes to mind is:

```
result.map(this.doSomething);
// vs
result.map((r) => this.doSomething(r))
```

**Comment by djmitche** [comment]
Hassan and I chatted a little, and there are cases where those two options are equivalent, but unless `this.doSomething = this.doSomething.bind(this)` has been called somewhere, the first form will lose the context for the `doSomething` method (meaning `this` won't refer to the right object).  I don't see any eslint checks that would catch this.

**Comment by petemoore** [comment]
I'm guessing we didn't intend to close this issue with #3374 since that PR was only about spacing around braces, so reopening...

**Comment by djmitche** [comment]
I did intend to close this, as there's nothing more actionable here.
