### ISSUE TITLE
Button colors/icons inconsistency

### ISSUE THREAD

**Issue by owlishDeveloper** [taskcluster/taskcluster#867]
**Describe the bug**
On Create Task page, we have a green button with a "plus" icon. The button performs Save operation. Typically, we have a blue button with a "plus" icon to open an editor or a creation interface, and a green button with a "diskette" icon to save things in the editor/creation interface.

I think we need to replace the "plus" icon with the "dikette" icon here to be consistent with the rest of the ui.

Purge Cache also has two buttons with "plus" icon - one blue to open creation interface, and one green to save. It seems the latter should also have the "diskette" icon.

Aws Provisioner has two green buttons with "plus" icon - one to open worker type editor, and the second one in the editor, to save the worker type. It seems the first one should be blue, and the second one should have the "diskette" icon

**Comment by djmitche** [comment]
I like that this also helps distinguish things for those with red/green color blindness :)

**Comment by Soundharyaam** [comment]
Hi, Is this up for grab? Can I work on this?

**Comment by helfi92** [comment]
> I think we need to replace the "plus" icon with the "dikette" icon here to be consistent with the rest of the ui.

> Purge Cache also has two buttons with "plus" icon - one blue to open creation interface, and one green to save. It seems the latter should also have the "diskette" icon.

> Aws Provisioner has two green buttons with "plus" icon - one to open worker type editor, and the second one in the editor, to save the worker type. It seems the first one should be blue, and the second one should have the "diskette" icon

Agreed 💯

**Comment by helfi92** [comment]
👋 @Soundharyaam Go for it.

**Comment by Soundharyaam** [comment]
@helfi92 Thank you.

**Comment by helfi92** [comment]
How is it going @Soundharyaam? Let me know if you had any questions.

**Comment by Soundharyaam** [comment]
Hi @helfi92 , Got some questions. Pinged in IRC.

**Comment by helfi92** [comment]
Ah, I missed the message. Just replied now.

**Comment by kanurag94** [comment]
Hi @helfi92 , Is anyone working on it? If not, I would like to work on this please?

**Comment by helfi92** [comment]
Feel free to give it a try. I haven't heard from @Soundharyaam for a bit.

**Comment by kanurag94** [comment]
@helfi92  Thank you

**Comment by helfi92** [comment]
How is it going @kanurag94? Let me know if you had any questions :-)

**Comment by kanurag94** [comment]
@helfi92 Can you help me

**Comment by helfi92** [comment]
Sure. How can I help?

**Comment by kanurag94** [comment]
> @helfi92 Can you help me find the files I should be looking to do changes. I searched the repo and didn't come up with mentioned icons

@helfi92

**Comment by kanurag94** [comment]
@helfi92 I couldn't find the save/diskette icon on the create task page : [Taskcluster Create task](https://taskcluster-ui.herokuapp.com/tasks/create/interactive)

Let me know if I am looking at the wrong place.

**Comment by kanurag94** [comment]
I'll be reporting soon, I have started working on this.
