### ISSUE TITLE
[ui] sign-in methods don't set window.opener, so callback doesn't work

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#874]
`callback.ejs` expects to post a message to `window.opener`, but currently the github sign-in (at least) is a link that does not result in `window.opener` being set, causing the postMessage to never happen.

**Comment by djmitche** [comment]
STR:
 * https://dustin.taskcluster-dev.net
 * sign in -> github
 * sign in

Result: "Logging In..." page, no login

**Comment by helfi92** [comment]
I just tried logging in with GitHub on https://dustin.taskcluster-dev.net. Login worked for me. Is it still not working for you?

**Comment by djmitche** [comment]
It doesn't. I'm using Firefox 68.0b7 and have tried with Content Blocking both in "Strict" and "Custom" modes.  I'll try "Standard"..

**Comment by djmitche** [comment]
Still no luck..

**Comment by helfi92** [comment]
Also works when I try on Chrome 75.0.3770.100. Does it work on Chrome for you?

**Comment by helfi92** [comment]
I wonder if it's an extension in Firefox causing this for you.

**Comment by djmitche** [comment]
Huh, it does work in a fresh Firefox profile.

**Comment by djmitche** [comment]
Oh, I also updated to the latest beta after this morning's sec vulns.  It seems to work even on my normal profile now -- so this was a Firefox bug!
