### ISSUE TITLE
[UI] Clicking on a scope that starts with assume:

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#884]
STR:

1.  Navigate to https://taskcluster-ui.herokuapp.com/auth/roles/hook-id%3Ahg-push%2Fautoland
2. View the expanded scopes.
3. Click on `assume:project:taskcluster:gecko:level-3-sccache-buckets` (a scope that begins with `assume:`)

Expected: The user is able to inspect that role. In other words, the user is navigated to `/auth/roles/project%3Ataskcluster%3Agecko%3Alevel-3-sccache-buckets`

Actual: The user is taken to the scope inspector https://taskcluster-ui.herokuapp.com/auth/scopes/assume%3Aproject%3Ataskcluster%3Agecko%3Alevel-3-sccache-buckets.

_Note regarding step 3: clicking on a scope that doesn't start with `assume:` should maintain the same current behavior_

**Comment by melvin2016** [comment]
Can you assign this to me?

**Comment by melvin2016** [comment]
can you guide me on the files to consider while working on this.

**Comment by helfi92** [comment]
👋 @melvin2016 

The first step is to go through https://github.com/taskcluster/taskcluster/blob/master/ui/README.md and make sure `localhost:5080/auth/roles/hook-id%3Ahg-push%2Fautoland` work for you. In terms of code, you can find the roles view in https://github.com/taskcluster/taskcluster/blob/master/ui/src/views/Roles/ViewRoles/Roles.jsx. Hope that helps.

**Comment by sonyshubham** [comment]
👋 @melvin2016,

Are you still working on this issue?

**Comment by tinoism** [comment]
👋 @melvin2016 @sonyshubham 
PR #949 should be able to close this issue. The issue was mainly due to the lack of conditional checks to distinguish between scopes that begin with `assume:` and those that don't. Adding the conditional check and branching off the linkage based on that should do the job.

**Comment by sonyshubham** [comment]
👋 @tinoism 
Thanks for the update, is there any issue I can start working on?

**Comment by helfi92** [comment]
> is there any issue I can start working on?

I believe you are now working on https://github.com/taskcluster/taskcluster/issues/639 :)

**Comment by sonyshubham** [comment]
> I believe you are now working on #639 :)

Yeah, I have started with that :)
