### ISSUE TITLE
[UI] Migrate to material-ui v4

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#895]

**Comment by arku** [comment]
@helfi92 I have submitted a [PR](https://material-ui.com/guides/migration-v3/#list) attempting to upgrade Material UI from v3 to v4. Take a look when you get a chance.

Thanks in advance!

**Comment by vishakhanihore** [comment]
@arku Are you still working on it?

**Comment by djmitche** [comment]
@vishakhanihore I see three [issues assigned to you](https://github.com/taskcluster/taskcluster/issues/assigned/vishakhanihore) right now.  Let's get those finished up first, please!

**Comment by Rolikasi** [comment]
@helfi92, I wanna try to finish it up!)

**Comment by helfi92** [comment]
I had to revert https://github.com/taskcluster/taskcluster/pull/1974#issue-341069514 :(

**Comment by kushthedude** [comment]
@Rolikasi Can I help in the same ?

**Comment by Rolikasi** [comment]
@kushthedude, yes) It would be great if you'll help me fix second issue in [#1974 (comment)](https://github.com/taskcluster/taskcluster/pull/1974#issuecomment-554037124)

**Comment by helfi92** [comment]
This is finally done. A big thank you for everyone who was involved in this! 😍
