### ISSUE TITLE
Check that headings in docs files match expectations

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#902]
In markdown files under `ui/docs`, the rule is:

* if there are any headings (`#`, `##`, etc.), then there should be a single top-level heading (`#`) at the beginning of the file
* if there are no headings besides a single top-level heading, there should be no top-level heading

Let's write a meta-check to verify this.

**Comment by subhamskm** [comment]
I want to take up this issue. Can you help me with some more info?

**Comment by djmitche** [comment]
Hi, great!  I've invited you as a collaborator and can assign the issue to you once you've accepted.

The `test` directory in the repository contains some test files that work over the whole repo -- for example, there is one that looks for misspellings of "Taskcluster".  You can add another test there.  I'd suggest writing a test that scans all markdown files in the `ui/docs` repository and checks that they are consistent with the rules above.

**Comment by subhamskm** [comment]
I don't know to write a test. But I would like to learn and contribute.

**Comment by djmitche** [comment]
Here's an example:
https://github.com/taskcluster/taskcluster/blob/10f24724047621d6e0f6ed342aed612b019f8be7/test/meta_test.js#L100-L121

You can add another `test(..)` clause like that to the same file.  You can probably use `glob` to find all markdown files, and then use some regular expressions to find and check the headings.

**Comment by djmitche** [comment]
By the way, we use `mocha` to run our tests, if you want to read some of the background on how it works.  You can run the meta tests with `yarn test:meta`.

**Comment by subhamskm** [comment]
Thanks! I am working on it.

**Comment by subhamskm** [comment]
`test('headings in docs files match expectations', async function () {
    const markdowns = glob.sync(
      'ui/docs/*/*.md',
      { cwd: ROOT_DIR });

    for (let filename of markdowns) {
      var data = fs.readFileSync(filename);
      var md = data.toString();
      var hd = [];

      //hd[i] stores the number of headings with level i
      hd[1] = md.match(/^# /gm).length;
      hd[2] = md.match(/^## /gm).length;
      hd[3] = md.match(/^### /gm).length;
      hd[4] = md.match(/^#### /gm).length;
      hd[5] = md.match(/^##### /gm).length;
      hd[6] = md.match(/^###### /gm).length;

      //counting levels of headings present and marking the top level 
      var countLevel = 0, topLevelHd = 7;
      for (var i = 1; i <= 6; i++) {
        if (hd[i] > 0) {
          countLevel++;
          if (i < topLevelHd)
            topLevelHd = i;
        }
      }

      // check if there is a single top-level heading
      if (topLevelHd < 7) {
        if (hd[topLevelHd] > 1) {
          throw new Error(`${filename} does not match the expectations`);
        }
      }

      //check if there are no headings besides a single top-level heading
      if (countLevel == 1) {
        if (hd[topLevelHd] == 1)
          throw new Error(`${filename} does not match the expectations`);
      }

    }
  });`

I think this may work.

**Comment by djmitche** [comment]
It may -- there's only one way to find out!

I'm a little confused reading your code, though -- it seems like "topLevelHead" refers to the *longest* string of `#`, rather than the shortest?  Anyway, running code is the ultimate proof :)

As examples of things that should fail:

* Remove `# Manipulating Tasks` from https://raw.githubusercontent.com/taskcluster/taskcluster/master/ui/docs/manual/tasks/manipulating.md
* Add `# Dependencies and Task Graphs` after `---` in https://raw.githubusercontent.com/taskcluster/taskcluster/master/ui/docs/manual/tasks/dependencies.md

**Comment by subhamskm** [comment]
"topLevelHead" refers to the longest string of #. I have tested the code and detected the changes you told to do in 'manipulating.md' and 'dependencies.md'. Also it detects an error in  'ui/docs/manual/using/administration.md' because there is no other heading than a single top-level heading.

**Comment by subhamskm** [comment]
It is saying 'permission to taskcluster/taskcluster denied' when trying to push the changes.

**Comment by djmitche** [comment]
Sounds good -- I'm looking forward to seeing the code!

> It is saying 'permission to taskcluster/taskcluster denied' when trying to push the changes.

You'll need to "Fork" the repository and push to your own fork, then make a pull request.
https://guides.github.com/introduction/flow/
