### ISSUE TITLE
[UI] Give special characters in scopes more emphasis

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#904]
STR:

* Navigate to https://taskcluster-ui.herokuapp.com/auth/roles/hook-id%3Ahg-push%2Fautoland
* View the expanded scopes.
    
**Expected:** `assume:`, `*` and `<..>` substrings are given more emphasis. This could probably be done by making the special characters have a bold font.

**Actual:** special characters are not standing out.

![Screen Shot 2019-06-24 at 5 59 40 PM](https://user-images.githubusercontent.com/3766511/60054889-e0ffa300-96a9-11e9-9c25-145c3bbe3f1d.png)

**Comment by subhamskm** [comment]
I want to take up this issue. Can you help me with some more info?

**Comment by helfi92** [comment]
👋 @subhamskm. Go for it. The part of the code where a scope is rendered can be found [here](https://github.com/taskcluster/taskcluster/blob/601536dd3207e37f4d72189d10a8f6272f1fcf26/ui/src/components/RoleForm/index.jsx#L205). Can't wait to see what you come up with :)

**Comment by subhamskm** [comment]
Hi @helfi92 , I am a beginner and I am not getting how to proceed. Can you help me out?

**Comment by arku** [comment]
@subhamskm Have you been to able to set up the project locally? If not, please refer to [this guide](https://github.com/taskcluster/taskcluster/blob/master/dev-docs/development-process.md). It would be helpful if you could provide more information on the issue you're running to.

**Comment by subhamskm** [comment]
> @subhamskm Have you been to able to set up the project locally? If not, please refer to [this guide](https://github.com/taskcluster/taskcluster/blob/master/dev-docs/development-process.md). It would be helpful if you could provide more information on the issue you're running to.

Thanks @arku. I am running into an issue.
![Screenshot (38)](https://user-images.githubusercontent.com/31374351/60689360-34f45e00-9eda-11e9-8ff5-de61116d7e70.png)
