### ISSUE TITLE
[UI] Confirmation dialog when deleting a hook

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#957]
Destructive actions (e.g., a delete operation) should have a confirmation step.
It’s an added click but will prevent accidental data loss frustration.

STR:

1. Navigate to http://localhost:5080/hooks/garbage/abc456
2. Hover/Click on the triple vertical dots icon then click on "Delete Hook"

![Screen Shot 2019-07-02 at 3 59 57 PM](https://user-images.githubusercontent.com/3766511/60542677-7de1c200-9ce2-11e9-8e75-30e6e8758ea7.png)

**Actual:** The client will try to delete right away

**Expected:** A confirmation dialog shows up using the custom [DialogAction](https://github.com/taskcluster/taskcluster/blob/master/ui/src/components/DialogAction/index.jsx) component.

**Comment by rbrishabh** [comment]
Can I take up this issue? Thanks!

**Comment by helfi92** [comment]
Go for it.

**Comment by rbrishabh** [comment]
Hi @helfi92 ! I am sorry for the delay!

I am not able to configure the user-config.yml file needed to start the taskcluster web-server service. Can you please help me with the same?

This is the error I am getting.

![taskcluster-error](https://user-images.githubusercontent.com/22501334/61400369-bb9f3700-a8ed-11e9-9478-b8453bbd6db2.png)

This is my user-config.yml file, it is situated in web-server directory.

![Untitled](https://user-images.githubusercontent.com/22501334/61401143-6f54f680-a8ef-11e9-97a0-24e8aa650759.png)



Where am I going wrong?

**Comment by helfi92** [comment]
Remove everything under `pulse` and `login`. That should hopefully fix the issue.

```yml
defaults:
  taskcluster:
    rootUrl: https://taskcluster.net
```

**Comment by rbrishabh** [comment]
Thanks! That fixed the issue!
Right now, when I hover over the three dots, it says (Auth Required) along with Delete Hook.

Do I need to set up taskcluster credentials as it is mentioned here? 
https://github.com/taskcluster/taskcluster/tree/master/services/web-server

**Comment by helfi92** [comment]
You should be able to login with any credentials (e.g., clientId: "foo", access token: "bar").

**Comment by rbrishabh** [comment]
Thanks a lot once again!

I did create a confirmation dialog and was able to implement it successfully.

Does it look okay? Or do I need to make any UI changes?

![how-is-it](https://user-images.githubusercontent.com/22501334/61410364-bc41c880-a901-11e9-8743-e260f8c45fd1.png)



Also I got a lot of prettier errors. How do I go about solving them? Thanks again!

**Comment by helfi92** [comment]
My pleasure :-) Good questions!

> Does it look okay? Or do I need to make any UI changes?

Add a `title` prop with value `Delete?`. Next, modify the body to say `This will delete <hook-group-id><hook-id>`.

> Also I got a lot of prettier errors. How do I go about solving them?

You can fix most linting errors by running `yarn lint --fix` inside the `ui` directory.

**Comment by rbrishabh** [comment]
Hey!

Does this look okay?

![is this ok](https://user-images.githubusercontent.com/22501334/61476361-7c82eb80-a9aa-11e9-9997-87b01858faf3.png)

Let me know if I need to make any other changes!

**Comment by helfi92** [comment]
> Does this look okay?

Yep.

> Also, I created user-config.yml. Before making a pull request, do I need to delete it?

No need to delete it. It is actually in `.gitignore` so git will not ask you to add it.
