### ISSUE TITLE
[UI] Redirect taskcluster-web.netlify.com to taskcluster-ui.herokuapp.com

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#969]
Netlify is only used for preview PRs. Let's have taskcluster-web.netlify.com redirect to the new site but not redirect preview URLs.

**Comment by arku** [comment]
@helfi92 Can we close this as it is done in https://github.com/taskcluster/taskcluster/pull/983 or is there something missing?

**Comment by helfi92** [comment]
It's actually not fixed. Not sure why at the moment. Let me know if you had any ideas. Navigating to https://taskcluster-web.netlify.com/ doesn't redirect to https://taskcluster-ui.herokuapp.com/ for example.

**Comment by arku** [comment]
@helfi92 I submitted a [PR](https://github.com/taskcluster/taskcluster/pull/1041) attempting to fix this issue. Hopefully, it works. Take a look when you get a chance.

**Comment by arku** [comment]
@helfi92 I tested this on an app of mine and the redirect rule works :ok_hand:

**Comment by helfi92** [comment]
w00t 🎉 The redirect works perfectly! Thanks for taking the time to look into it @arku :)
