### ISSUE TITLE
[UI] Show relative date in a tooltip

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#970]
STR:

1. Navigate to https://taskcluster-ui.herokuapp.com/tasks/index/gecko.v2.mozilla-beta.latest.firefox/linux64-opt
2. Hover on text below "Created"

Actual: Nothing appears
Expected: Show the actual date in a tooltip

Something similar to:

<img width="318" alt="Screen Shot 2019-07-04 at 2 56 27 PM" src="https://user-images.githubusercontent.com/3766511/60684484-f758ec00-9e6b-11e9-9a53-22ec0b0257ef.png">

but without the "(copy)" part.

**Comment by ivanicharts** [comment]
Can I take up this issue? Thanks!
