### ISSUE TITLE
Add ability to see the current document's location in documentation tree

### ISSUE THREAD

**Issue by owlishDeveloper** [taskcluster/taskcluster#975]
Currently, if I open a documentation page on the docs site, it doesn't show me the documentation tree and where the document is on that tree (for example, maybe I would like to see what other pages are there in the section and view some other pages from that section)

**To Reproduce**
1. Go to 'https://docs.taskcluster.net/docs/reference/integrations/github/' for example
2. Observe the table of contents on the left - the document won't be shown / highlighted there

**Expected behavior**
I would expect the table of contents on the left to show the currently opened document in the tree. A good example of what I am asking for is AWS documentation website: on the left side, they have the table of contents where you can see where the currently opened document belongs

**Comment by helfi92** [comment]
Works for https://docs.taskcluster.net/docs/reference/integrations/github. I think the issue happens only when there is a trailing slash at the end. Good catch. This should be fixed.

**Comment by ruchikabgosain** [comment]
Hey @helfi92 I would like to take this up. Is this issue available?

**Comment by helfi92** [comment]
Yep, go for it.

**Comment by helfi92** [comment]
The issue probably revolves around this line: https://github.com/taskcluster/taskcluster/blob/e4aeca4a794799920e016dceb01724b06f4b5415/ui/src/components/Dashboard/DocsSidebarList.jsx#L145.

**Comment by ruchikabgosain** [comment]
Hey @helfi92 , This is my suggestion, try replacing the code with this workaround. Let me know if this works. 

const isLinkActive = removeReadmeFromPath(location.pathname) === href || removeReadmeFromPath(location.pathname) === href + "/";``

**Comment by helfi92** [comment]
Resolved in https://github.com/taskcluster/taskcluster/commit/8c1ec40012aa2298f4b0bd2a4418e7e080e9ad98. Should be deployed in a bit :)
