### ISSUE TITLE
[UI] Extend logviewer scrollbar to the window

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#987]
STR:

1. Navigate to https://taskcluster-ui.herokuapp.com/tasks/A3nNtW92QFGETYErI_BR8Q/runs/0/logs/https%3A%2F%2Fqueue.taskcluster.net%2Fv1%2Ftask%2FA3nNtW92QFGETYErI_BR8Q%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log

![Screen Shot 2019-07-08 at 2 04 10 PM](https://user-images.githubusercontent.com/3766511/60832250-6777b280-a189-11e9-8cd3-bba4a188f96b.png)

**Actual:** The horizontal and verical scrollers are inside the page
**Expected:** Both scrollers sit on the window (full page)

The logviewer uses react-virtualized internally. Looking at their docs they seem to have a [WindowScroller](https://github.com/bvaughn/react-virtualized/blob/master/docs/WindowScroller.md) component that we could possibly use.

**Comment by ss77995ss** [comment]
Hi, can I take this up? Thanks:)

**Comment by helfi92** [comment]
Go for it. It's a tricky issue.

**Comment by ss77995ss** [comment]
Hi @helfi92 , I have some questions while I developing this issue
1. It seems like `Dashboard` max-width is `1592px` just curious why to set this number

<img width="1280" alt="Screen Shot 2019-07-21 at 01 57 31" src="https://user-images.githubusercontent.com/28031139/61582261-24d7b200-ab5b-11e9-8d60-480ec0a489be.png">

2. I tried to use the same way in `TaskGroupTable`, but they are a little different. In `Log` we use `LazyLog` component and not `List` and `LazyLog` does not have `scrollTo` function so we cannot execute this line in `Log`
https://github.com/taskcluster/taskcluster/blob/master/ui/src/components/TaskGroupTable/index.jsx#L188
Maybe we can add `WindowScroller` in `LazyLog` which is using `react-virtualized` and if it works we can use a prop to control whether we want to use it or not

**Comment by helfi92** [comment]
> It seems like Dashboard max-width is 1592px just curious why to set this number

We set a max width so that elements don't keep stretching on wider screen. This kind of constraint is done on many site, including GitHub.

> Maybe we can add WindowScroller in LazyLog which is using react-virtualized and if it works we can use a prop to control whether we want to use it or not

That sounds like a great idea.

**Comment by ss77995ss** [comment]
Hi @helfi92 , I'm working on this issue in `react-lazylog`, now. Can you help me know how to change the **Styleguidist Demo** page? I want to preview the `<LazyLog />` component with other layouts. Thanks.

**Comment by helfi92** [comment]
@ss77995ss I think the issue is in this repository but it doesn't hurt to look in react-lazylog. To run the styleguide, you have to run `yarn styleguide` to start the server. To change particular components, you could modify the README.md file inside `src/component/<component-name>`. It should update the styleguide.

**Comment by ss77995ss** [comment]
@helfi92 , I make some progress on this issue but `GoToLine` and `Follow` button is not working now. I think I need some advice or idea to fix this problem, thanks!

**Comment by JiwoonKim** [comment]
Hi! I'm an Outreachy Applicant and have completed the first step (sending screenshot). Can I take this issue?

**Comment by djmitche** [comment]
Hi @JiwoonKim please have a look.  @ss77995ss are you still working on this?

**Comment by ss77995ss** [comment]
@djmitche I'm confronting with some obstacles now, and still cannot figure it out yet, but it is OK to give someone a try :)

**Comment by kushthedude** [comment]
@djmitche @helfi92 I am new to this repo, I would like to solve this ticket. Can I work on it ?

**Comment by helfi92** [comment]
@JiwoonKim are you still working on this?

**Comment by JiwoonKim** [comment]
@djmitche I'm having a bit of difficulties in this problem. @kushthedude I think you can take this issue!

**Comment by vishakhanihore** [comment]
@helfi92 Is this issue still present?
<img width="1259" alt="Screenshot 2019-10-23 at 10 12 11 PM" src="https://user-images.githubusercontent.com/54327666/67415189-2e513a00-f5e2-11e9-8cf4-e5b45ae6bb35.png">

**Comment by helfi92** [comment]
Yep.

![Screen Shot 2019-10-23 at 2 35 10 PM](https://user-images.githubusercontent.com/3766511/67423486-5c168e80-f5a2-11e9-9640-77c7bf4df7b0.png)

**Comment by vishakhanihore** [comment]
I cant reproduce on safari, is it also firefox specific?
